### ISSUE TITLE
undefined method `downcase' for #<Pathname:bazaar>

### ISSUE THREAD

**Issue by g0hacker** [Homebrew/brew#1005]
Hi, I want to update brew, but got:

```
$ brew update
Error: undefined method `downcase' for #<Pathname:bazaar>
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:349:in `core_path'
/usr/local/Library/Homebrew/formulary.rb:301:in `loader_for'
/usr/local/Library/Homebrew/formulary.rb:219:in `factory'
/usr/local/Library/Homebrew/utils.rb:637:in `rescue in rescue in block in migrate_legacy_keg_symlinks_if_necessary'
/usr/local/Library/Homebrew/utils.rb:634:in `rescue in block in migrate_legacy_keg_symlinks_if_necessary'
/usr/local/Library/Homebrew/utils.rb:631:in `block in migrate_legacy_keg_symlinks_if_necessary'
/usr/local/Library/Homebrew/utils.rb:629:in `each'
/usr/local/Library/Homebrew/utils.rb:629:in `migrate_legacy_keg_symlinks_if_necessary'
/usr/local/Library/Homebrew/brew.rb:91:in `<main>'
```

I update brew every day, so it should be up to date.

**Comment by zmwangx** [comment]
Same issue as #1000, tracking there. We're working on a fix, sorry for the pain. It would be great if you could test to see if #1003 works for you.

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/brew/pull/1003 has shipped. Please update, and this should be fixed.

**Comment by Moddus** [comment]
Thank you so much!
