### ISSUE TITLE
Error during CI testing: File exists @ dir_s_mkdir - ./failed

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/brew#10498]
**`brew config` output**

https://github.com/Homebrew/homebrew-core/pull/70143/checks?check_run_id=1814099062

**`brew doctor` output**

https://github.com/Homebrew/homebrew-core/pull/70143/checks?check_run_id=1814099062

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

Two different testing runs of `go` at https://github.com/Homebrew/homebrew-core/pull/70143/checks?check_run_id=1814099077 and https://github.com/Homebrew/homebrew-core/pull/70143/checks?check_run_id=1814099062 failed with the same issue:

`File exists @ dir_s_mkdir - ./failed`

which seems like a `brew` error, not a formula error.

**What happened (include all command output)?**

`File exists @ dir_s_mkdir - ./failed` is the error observed after a failed `gdm` test.

```
2021-02-03T06:15:47.5799400Z [34m==>[0m [1m/usr/local/Cellar/gdm/1.4/bin/gdm save[0m
2021-02-03T06:15:47.5800300Z ======= Go Dependency Manager =======
2021-02-03T06:15:47.5803830Z = working dir: /private/tmp/gdm-test-20210203-65962-166114k
2021-02-03T06:15:47.5805850Z = GOPATH:      /private/tmp/gdm-test-20210203-65962-166114k
2021-02-03T06:15:47.5806760Z =====================================
2021-02-03T06:15:47.5807430Z Fatal error: exit status 1
2021-02-03T06:15:47.5808330Z An exception occurred within a child process:
2021-02-03T06:15:47.5809820Z [31mError:[0m gdm: failed
2021-02-03T06:15:47.5812000Z   Test::Unit::AssertionFailedError: <0> expected but was
2021-02-03T06:15:47.5812940Z <1>.
2021-02-03T06:15:47.5815450Z /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/gems/2.6.0/gems/test-unit-3.2.9/lib/test/unit/assertions.rb:55:in `block in assert_block'
2021-02-03T06:15:47.5818630Z /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/gems/2.6.0/gems/test-unit-3.2.9/lib/test/unit/assertions.rb:1636:in `_wrap_assertion'
2021-02-03T06:15:47.5822420Z /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/gems/2.6.0/gems/test-unit-3.2.9/lib/test/unit/assertions.rb:53:in `assert_block'
2021-02-03T06:15:47.5825980Z /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/gems/2.6.0/gems/test-unit-3.2.9/lib/test/unit/assertions.rb:240:in `assert_equal'
2021-02-03T06:15:47.5828690Z /usr/local/Homebrew/Library/Homebrew/formula_assertions.rb:19:in `shell_output'
2021-02-03T06:15:47.5831040Z /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gdm.rb:40:in `block in <class:Gdm>'
2021-02-03T06:15:47.5833400Z /usr/local/Homebrew/Library/Homebrew/formula.rb:1911:in `block (3 levels) in run_test'
2021-02-03T06:15:47.5837010Z /usr/local/Homebrew/Library/Homebrew/utils.rb:530:in `with_env'
2021-02-03T06:15:47.5839060Z /usr/local/Homebrew/Library/Homebrew/formula.rb:1910:in `block (2 levels) in run_test'
2021-02-03T06:15:47.5841040Z /usr/local/Homebrew/Library/Homebrew/formula.rb:900:in `with_logging'
2021-02-03T06:15:47.5843010Z /usr/local/Homebrew/Library/Homebrew/formula.rb:1909:in `block in run_test'
2021-02-03T06:15:47.5845160Z /usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `block in run'
2021-02-03T06:15:47.5847260Z /usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `chdir'
2021-02-03T06:15:47.5849190Z /usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `run'
2021-02-03T06:15:47.5852350Z /usr/local/Homebrew/Library/Homebrew/formula.rb:2157:in `mktemp'
2021-02-03T06:15:47.5854540Z /usr/local/Homebrew/Library/Homebrew/formula.rb:1903:in `run_test'
2021-02-03T06:15:47.5856420Z /usr/local/Homebrew/Library/Homebrew/test.rb:43:in `block in <main>'
2021-02-03T06:15:47.5858730Z /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
2021-02-03T06:15:47.5861250Z /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
2021-02-03T06:15:47.5863840Z /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:33:in `catch'
2021-02-03T06:15:47.5866270Z /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:33:in `catch'
2021-02-03T06:15:47.5872610Z /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
2021-02-03T06:15:47.5875020Z /usr/local/Homebrew/Library/Homebrew/test.rb:42:in `<main>'
2021-02-03T06:15:47.5875730Z 
2021-02-03T06:15:47.5899120Z [31mError:[0m File exists @ dir_s_mkdir - ./failed
```

**Comment by MikeMcQuaid** [comment]
The `failed` looks like it's related to the failed bottles CC @SeekingMeaning

**Comment by carlocab** [comment]
I think this can be fixed by changing [this line](https://github.com/Homebrew/homebrew-test-bot/blob/cdd2b5c5821e3c396138338d5c4ef1682c45245d/lib/tests/formulae.rb#L659)

```ruby
FileUtils.mkdir failed_dir
```

to

```ruby
FileUtils.mkdir_p failed_dir
```

I'll open a PR for that.

**Comment by fxcoudert** [comment]
@carlocab isn't that papering over the bug? I don't think that file is supposed to exist, really.

**Comment by carlocab** [comment]
It will exist (and I believe, is expected to exist) as long as there was an earlier failure in the CI run. So I think it fixes the bug, rather than papers over it?

**Comment by fxcoudert** [comment]
> as long as there was an earlier failure in the CI run

This is what I don't understand. There was no earlier failure for this formula in the CI run, I've checked.

Another way to ask the question is: why is this failing now? In other terms, what broke it? We've had CI checks with many failures before, and it was never a problem.

**Comment by carlocab** [comment]
>There was no earlier failure for this formula in the CI run, I've checked.

We are looking for a failure for a _different_ formula; one that was (successfully) built from source. This happened during the testing of `bitrise`. So, the timeline is:

1. `bitrise` is built from source, but its test fails.
2. `test-bot` creates a `failed` directory to house the failed `bitrise` bottle.
3. `gdm` is built from source, and its test also fails.
4. `test-bot` tries to create a `failed` directory to house the failed `gdm` bottle, but it fails because it has already created this directory in step 2.

This piece of code is new as of https://github.com/Homebrew/homebrew-test-bot/pull/561.
