### ISSUE TITLE
throwing a "undefined method `ohai_stdout_or_stderr' for #<ReporterHub:0x00007fe5f405a550>" error

### ISSUE THREAD

**Issue by luckman212** [Homebrew/brew#10536]
brew config
```
$ brew config
HOMEBREW_VERSION: 3.0.0-8-g984eb3f
ORIGIN: https://github.com/Homebrew/brew
HEAD: 984eb3f878e94f4de67bd25df5ed7d8319c3ab37
Last commit: 8 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c1abd946dcecc6819bb2d1cd44b13f7b68ad3936
Core tap last commit: 10 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /usr/local/bin/subl -w
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.30.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 13.0.1
macOS: 11.2-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: 12.4
```
brew doctor
```
 $ brew doctor
Your system is ready to brew.
```

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

`brew update`

**What happened (include all command output)?**

An ` undefined method `ohai_stdout_or_stderr' ` error is thrown when there is any output from `brew update` similar to the below

```
$ brew install bash
Updating Homebrew...
==> Auto-updated Homebrew!
Updated Homebrew from e98a91378 to 984eb3f87.
Updated 2 taps (homebrew/core and homebrew/cask).
Error: undefined method `ohai_stdout_or_stderr' for #<ReporterHub:0x00007fe5f405a550>
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:505:in `dump'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:148:in `update_report'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
```

This seems to be caused by the recent commit:
https://github.com/Homebrew/brew/commit/dbf65770aff73b4d3af26f71214f228a8180e92b#diff-05ec45190dab3db11df80b2c154648c8023837fa34917dce9d1bcde0acf9c005

**What did you expect to happen?**

no errors

**Step-by-step reproduction instructions (by running `brew` commands)**

`brew update` with brew 3.0.0-8-g984eb3f

**Comment by convenient** [comment]
Seeing this in our travis runs too on `osx_image: xcode12.2`
