### ISSUE TITLE
`cannot load such file -- bootsnap/bootsnap` after update, and cannot run any commands

### ISSUE THREAD

**Issue by scottrobertson** [Homebrew/brew#10699]
**`brew config` output**

Can't run it

**`brew doctor` output**

Can't run it

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

Run anything in brew

**What happened (include all command output)?**

```
Traceback (most recent call last):
	22: from /usr/local/Homebrew/Library/Homebrew/brew.rb:31:in `<main>'
	21: from /usr/local/Homebrew/Library/Homebrew/brew.rb:31:in `require_relative'
	20: from /usr/local/Homebrew/Library/Homebrew/global.rb:4:in `<top (required)>'
	19: from /usr/local/Homebrew/Library/Homebrew/global.rb:4:in `require_relative'
	18: from /usr/local/Homebrew/Library/Homebrew/load_path.rb:11:in `<top (required)>'
	17: from /usr/local/Homebrew/Library/Homebrew/load_path.rb:11:in `require'
	16: from /usr/local/Homebrew/Library/Homebrew/homebrew_bootsnap.rb:33:in `<top (required)>'
	15: from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.7.2/lib/bootsnap.rb:67:in `setup'
	14: from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.7.2/lib/bootsnap/compile_cache.rb:10:in `setup'
	13: from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:53:in `require_relative'
	12: from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	11: from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	10: from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	 9: from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	 8: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 7: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 6: from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.7.2/lib/bootsnap/compile_cache/iseq.rb:2:in `<top (required)>'
	 5: from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:44:in `require'
	 4: from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	 3: from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:89:in `register'
	 2: from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	 1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- bootsnap/bootsnap (LoadError)
```

**What did you expect to happen?**

Not to have bootsnap failure

**Step-by-step reproduction instructions (by running `brew` commands)**

I ran brew update, never had this issue before, and I had updated about a week ago.

I have tried reinstalling too. Trying to avoid fully uninstalling and installing again.

`brew update` is about all that runs, and it says it's already up to date.

**Comment by scottrobertson** [comment]
I managed to solve this by manually removing `/usr/local/Homebrew/Library/Homebrew/vendor/bundle` and running the installer again. 

It seems like it didn't finish the bundle process last time for some reason, and trying to reinstall (without deleting the vendor/bundle folder) does not run bundle again. Might be worth always running that on reinstall.
