### ISSUE TITLE
Custom Cask install failed on 3.0.11

### ISSUE THREAD

**Issue by chzchris** [Homebrew/brew#11059]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.0.11-51-g1435018
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1435018e11ab5537c7df12cc8d2d261d88121b5b
Last commit: 52 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 760281826c541a3e49b6c4d2850e5f0a6a944580
Core tap last commit: 77 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.29.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.0.0.32.28
Xcode: N/A
```

### `brew doctor` output

```shell
I would like to say the Warning line is not relevant. I tried to downgrade Homebrew to 3.0.10 and have the same warning, but it passed the Cask installation.

------------------------------------------------------------------------
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.


Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /opt/local/bin/ncursesw5-config
  /opt/local/bin/icu-config
  /opt/local/bin/neon-config
  /opt/local/bin/ncurses5-config
```

### 

The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

We have a custom Cask in our internal tap repo. The Cask looks like below.
When running `brew install --cask rpm` or reinstall via `brew reinstall --cask rpm` we got stanza error `Error: Download failed on Cask 'oms-rpm' with message: Cask 'oms-rpm' definition is invalid: 'version' stanza may only appear once.`

I have to downgrade to 3.0.10 and the installation passed. I guess this is a new bug introduced in 3.0.11

```
cask 'rpm' do
  version '4.4.9'
  sha256 '081216d4aeef3de8b778065372292aca24c3c7b3e3be97516e2a0615f425144f'

  url do
    require_relative '../scripts/credentials'
    "https://#{Credentials.artifactory_creds}@<INTERNAL_ARTIFACTORY>/artifactory/developer-tools/rpm/rpm-#{version}-12.dmg"
  end
  name "RPM Package Manager"
  homepage ‘<INTERNAL_ARTIFACTORY>/‘

  pkg "rpm-#{version}.mpkg"

  uninstall pkgutil: "org.macports.rpm"
end
```

### What happened (include all command output)?

When running `brew install --cask rpm` or reinstall via `brew reinstall --cask rpm` we got stanza error:
```
Error: Download failed on Cask 'oms-rpm' with message: Cask 'oms-rpm' definition is invalid: 'version' stanza may only appear once.
```

### What did you expect to happen?

It should install the Cask.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. Create the cask from the example I gave above.
2. Make sure you are on Homebrew 3.0.11 version
3. Run `brew install <CASK_NAME>`
```

**Comment by reitermarkus** [comment]
Please post the command output with `--verbose --debug`.

**Comment by chzchris** [comment]
@reitermarkus 
Thank for the reminder. Here is the output:
```
/usr/local/Homebrew c.chen % brew --version
Homebrew 3.0.11
Homebrew/homebrew-core (git revision 760281826c; last commit 2021-04-07)
Homebrew/homebrew-cask (git revision ed765449f1; last commit 2021-04-07)
/usr/local/Homebrew c.chen % brew reinstall --cask oms-rpm --verbose --debug
==> Cask::Installer#reinstall
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
Error: Download failed on Cask 'oms-rpm' with message: Cask 'oms-rpm' definition is invalid: 'version' stanza may only appear once.
/usr/local/Homebrew/Library/Homebrew/cask/dsl.rb:116:in `set_unique_stanza'
/usr/local/Homebrew/Library/Homebrew/cask/dsl.rb:209:in `version'
/usr/local/Homebrew/Library/Homebrew/cask/url.rb:133:in `public_send'
/usr/local/Homebrew/Library/Homebrew/cask/url.rb:133:in `method_missing'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-wday/Casks/oms-rpm.rb:7:in `block (2 levels) in load'
/usr/local/Homebrew/Library/Homebrew/cask/url.rb:114:in `instance_exec'
/usr/local/Homebrew/Library/Homebrew/cask/url.rb:114:in `call'
/usr/local/Homebrew/Library/Homebrew/cask/url.rb:185:in `block in initialize'
/usr/local/Homebrew/Library/Homebrew/lazy_object.rb:15:in `__getobj__'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/delegate.rb:97:in `respond_to_missing?'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/delegate.rb:82:in `respond_to?'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/delegate.rb:82:in `method_missing'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:39:in `downloader'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:25:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:169:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:71:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:98:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:140:in `reinstall'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/reinstall.rb:48:in `block in reinstall_casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/reinstall.rb:47:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/reinstall.rb:47:in `reinstall_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:130:in `reinstall'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
```

**Comment by chzchris** [comment]
While the debug mode gave me some contexts, I found this change is suspicious in [HERE](https://github.com/Homebrew/brew/commit/0b6b05d1aabb5401934a64cd683a460c5f9470c9#diff-36e54501800448632705c4798d391e5143cb33de37f349fcb9c9340e4fd30d74R133)

Looks like Homebrew added a check to the URL public send method and it triggered a stanza check [HERE](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/dsl.rb#L116) and raise the error. But I have no context on why this check was added in 3.0.11.
