### ISSUE TITLE
Pango dylib missing in gobject-introspection

### ISSUE THREAD

**Issue by DocEpsilon** [Homebrew/brew#11110]
### `brew config` output

```shell
% brew config
HOMEBREW_VERSION: 3.1.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: ccb05e5e0b7b925c3d6b531fa43b016fa4d0b72a
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3a8ae6717188caace0790e4705cdb7d5eac477ae
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.YtpqaZHJlq/org.xquartz:0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.3-arm64
CLT: 12.4.0.0.1.1610135815
Xcode: 12.4
Rosetta 2: false
```

### `brew doctor` output

```shell
% brew doctor                          
Your system is ready to brew.
```

### 

The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

Executing the following minimal example of a python script named `gitest.py`
```
cat gitest.py                                                                        
import gi
gi.require_version('Pango', '1.0')
from gi.repository import Pango
print(Pango.version_string())
```

I was trying to install  pympress. pympress is not bottled for apple silicon yet, hence I was building it from source:
`brew install --build-from-source pympress`

Executing pympress yields the same error message as shown below, when executing the script. Hence minimal example. 

Opened an issue with pympress github repo [here](https://github.com/Cimbali/pympress/issues/190). Got redirected to [gobject-introspection](https://gitlab.gnome.org/GNOME/gobject-introspection/-/issues/382). And those guys sent me to you:
"The Pango introspection data is generated by Pango at build time, and it's not part of gobject-introspection."

### What happened (include all command output)?

```
% python3 gitest.py     

** (process:11875): WARNING **: 14:02:11.062: Failed to load shared library 'libpango-1.0.0.dylib' referenced by the typelib: dlopen(libpango-1.0.0.dylib, 9): image not found
Traceback (most recent call last):
  File "/Users/epp/Documents/Python/PyDev/gitest.py", line 3, in <module>
    from gi.repository import Pango
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "/opt/homebrew/lib/python3.9/site-packages/gi/importer.py", line 145, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/opt/homebrew/lib/python3.9/site-packages/gi/overrides/__init__.py", line 118, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/opt/homebrew/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/homebrew/lib/python3.9/site-packages/gi/overrides/Pango.py", line 41, in <module>
    FontDescription = override(FontDescription)
  File "/opt/homebrew/lib/python3.9/site-packages/gi/overrides/__init__.py", line 195, in override
    assert g_type != TYPE_NONE
```

Skript fails with assertion error.

`Probable` Cause:

libpango-*.dylib not linked in girepository

```
% strings $(brew --prefix)/lib/girepository-1.0/*.typelib | grep libpango-[0-9.]*.dylib
zsh: no matches found: libpango-[0-9.]*.dylib
```

### What did you expect to happen?

Expected the script to print the pango version.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Running on Apple silicon MacBook Pro 13"


% brew install --build-from-source pympress
% pympress presentation.pdf
```
or
```
% python3 gitest.py
```
```

**Comment by carlocab** [comment]
I don't think `libpango-1.0.0.dylib` is meant to be linked into `lib/girepository-1.0`. We just use `meson` and `ninja` to build `pango`, and the build system doesn't put `libpango-1.0.0.dylib` there. There is, however, a `girepository-1.0` directory in `$(brew --prefix pango)/lib`, which was created by the build system.

This is more likely an issue of misconfigured `rpath`s.

Note that the lack of a bottle actually means that the formula isn't expected to work properly, and building from source isn't supported.
