### ISSUE TITLE
openssl@1.1 post-install fails

### ISSUE THREAD

**Issue by orlevi128** [Homebrew/brew#11135]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.1.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: dc3e8b485a166a73d6463320d9deaba6236f747c
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5a867203bca24613cc43b50beede5ddeda841b4f
Core tap last commit: 88 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_AUTO_UPDATE: set
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 12.0 build 1200
Git: 2.31.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.3-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### 

I ran `brew update` and am still able to reproduce my issue.
I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I was trying to set up my python environment (installing `pyenv`)
And after getting some SSL_CERTIFICATE errors, I've seen that `openssl` post-install didn't generate keys.

### What happened (include all command output)?

Running: `brew postinstall --debug --verbose openssl@1.1`
```
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb
==> Postinstalling openssl@1.1
/usr/bin/sandbox-exec -f /private/tmp/homebrew20210414-30287-1perx2t.sb nice ruby -W1 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/postinstall.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb
==> Regenerating CA certificate bundle from keychain, this may take a while...
Warning: The post-install step did not complete successfully
You can try again using:
  brew postinstall openssl@1.1
==> An exception occurred within a child process:
  Errno::EINTR: Interrupted system call @ rb_file_truncate - /private/tmp/20210414-30288-ge0qiu

/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `truncate'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `block in delegating_block'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb:148:in `block in macos_post_install'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb:145:in `select'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb:145:in `macos_post_install'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/on_os.rb:8:in `on_macos'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb:114:in `post_install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1089:in `block (2 levels) in run_post_install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:924:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1088:in `block in run_post_install'
/usr/local/Homebrew/Library/Homebrew/utils.rb:558:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1077:in `run_post_install'
/usr/local/Homebrew/Library/Homebrew/postinstall.rb:22:in `<main>'
```

### What did you expect to happen?

It shouldn't fail.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Running on MacOs Big Sur 11.2.3:

`brew install openssl@1.1`
```

**Comment by MikeMcQuaid** [comment]
@orlevi128 Do you have any virus checkers and/or security software installed?
