### ISSUE TITLE
brew install pulumi - No such file or directory @ rb_file_s_stat

### ISSUE THREAD

**Issue by stack72** [Homebrew/brew#11144]
### `brew config` output

```shell
▶ brew config
HOMEBREW_VERSION: 3.1.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: bc9b98aa0ba777889218ac51f67ccc76b0be6a28
Last commit: 6 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 22942f40c150f8ab09d6a3b7a589e3afc191316f
Core tap last commit: 35 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 11.0 build 1100
Git: 2.30.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 11.0.0.33.17
Xcode: N/A
```

### `brew doctor` output

```shell
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.


Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  dep
  glide
  go@1.13

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  delta
  awscli
  kubernetes-cli
  node
```

### 

I ran `brew update` and am still able to reproduce my issue.
I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

brew upgrade pulumi

to get the latest version of Pulumi that was just merged in https://github.com/Homebrew/homebrew-core/pull/75172

### What happened (include all command output)?

```
▶ brew install pulumi --debug
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pulumi.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/go.rb
==> Downloading https://ghcr.io/v2/homebrew/core/pulumi/manifests/2.25.0
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/3.1.2\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.7\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --header Accept:\ application/vnd.oci.image.index.v1\+json --header Authorization:\ Bearer\ QQ== --location --silent --head --request GET https://ghcr.io/v2/homebrew/core/pulumi/manifests/2.25.0
Already downloaded: /Users/stack72/Library/Caches/Homebrew/downloads/e2f1e34ca853a840b1463bbbede912702382098601c6390ff0d06e3335377b77--pulumi-2.25.0.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/pulumi/blobs/sha256:58c7b17e7a0c892f9ef0a362c000181bb3347afbc6ae8f6c86fb11addccc6036
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/3.1.2\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.7\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --header Authorization:\ Bearer\ QQ== --location --silent --head --request GET https://ghcr.io/v2/homebrew/core/pulumi/blobs/sha256:58c7b17e7a0c892f9ef0a362c000181bb3347afbc6ae8f6c86fb11addccc6036
Already downloaded: /Users/stack72/Library/Caches/Homebrew/downloads/876d7887283bc4bd9ba1a962c79c440309a2f507c643f90fea38b733fbc1e4ea--pulumi--2.25.0.catalina.bottle.tar.gz
/usr/local/Homebrew/Library/Homebrew/shims/scm/git --version
==> Pouring pulumi--2.25.0.catalina.bottle.tar.gz
tar xof /Users/stack72/Library/Caches/Homebrew/downloads/876d7887283bc4bd9ba1a962c79c440309a2f507c643f90fea38b733fbc1e4ea--pulumi--2.25.0.catalina.bottle.tar.gz -C /private/tmp/d20210414-67325-hov1xh
cp -pR /private/tmp/d20210414-67325-hov1xh/pulumi/. /usr/local/Cellar/pulumi
Error: No such file or directory @ rb_file_s_stat - /usr/local/Cellar/pulumi/2.25.0/INSTALL_RECEIPT.json
/usr/local/Homebrew/Library/Homebrew/keg_relocate.rb:73:in `stat'
/usr/local/Homebrew/Library/Homebrew/keg_relocate.rb:73:in `stat'
/usr/local/Homebrew/Library/Homebrew/keg_relocate.rb:73:in `block in replace_text_in_files'
/usr/local/Homebrew/Library/Homebrew/keg_relocate.rb:73:in `each'
/usr/local/Homebrew/Library/Homebrew/keg_relocate.rb:73:in `group_by'
/usr/local/Homebrew/Library/Homebrew/keg_relocate.rb:73:in `replace_text_in_files'
/usr/local/Homebrew/Library/Homebrew/keg_relocate.rb:66:in `replace_placeholders_with_locations'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:1149:in `pour'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:418:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:422:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:324:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:322:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:322:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
```

### What did you expect to happen?

installation to succeed

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew upgrade pulumi and brew install pulumi both give the same error
```

**Comment by carlocab** [comment]
Thanks for the report. We're aware of the issue; hopefully, a fix will be ready soon.

Apologies for the inconvenience!

**Comment by stack72** [comment]
Hi @carlocab 

Is this an issue only affecting Pulumi or other packages? Anything you need us to do here?

Paul

**Comment by carlocab** [comment]
It affects any bottles built after this commit: https://github.com/Homebrew/homebrew-core/commit/685eea39ffe258bb79e323d212c2e1ff020eefc4

**Comment by iMichka** [comment]
Fix is incoming: #11145

We will rebuild bottles once this is merged.

**Comment by carlocab** [comment]
`pulumi` rebuild at https://github.com/Homebrew/homebrew-core/actions/runs/749849682.

**Comment by stack72** [comment]
thanks so much folks - all fixed up and I have been able to reinstall!
