### ISSUE TITLE
bump-cask-pr is broken

### ISSUE THREAD

**Issue by dasmfm** [Homebrew/brew#11180]
### `brew config` output

```shell
% brew config
HOMEBREW_VERSION: 3.1.2-40-g520b811
ORIGIN: https://github.com/Homebrew/brew
HEAD: 520b8110e841c97918cb9b351ae645da4537c6c8
Last commit: 29 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5f873bab4925a6c1f4f2e079f89f843bb15f13c6
Core tap last commit: 12 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.31.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.3-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: 12.4
```

### `brew doctor` output

```shell
% brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  kubernetes-cli
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I'm trying to update "lens" cask via bump-cask-pr.

### What happened (include all command output)?

It fails with an error.

Looks like problem added with this commit:
https://github.com/Homebrew/brew/commit/63be66408e9787661831f9db818a3c2c0de2a795

```
% brew bump-cask-pr --version 4.2.2 lens
==> Downloading https://github.com/lensapp/lens/releases/download/v4.2.2/Lens-4.2.2.dmg
Already downloaded: /Users/borisklimenko/Library/Caches/Homebrew/downloads/069a35fc8abfc995f972305bc630a014f9ada114dd9d7a06bd619f9c239e8764--Lens-4.2.2.dmg
Warning: Cannot verify integrity of '069a35fc8abfc995f972305bc630a014f9ada114dd9d7a06bd619f9c239e8764--Lens-4.2.2.dmg'.
No checksum was provided for this resource.
For your reference, the checksum is:
  sha256 "d34753f6da17df2bfd89525ec6f5a521c00f8a512c7b245b3153ec7a302d5198"
==> replace /version\s+["']4\.2\.1["']/m with "version \"4.2.2\""
==> replace /sha256\s+["']edd299988416a471012618e70df1066bb2425fa3ea9e7ab3853e8f0186449b49["']/m with "sha256 \"d34753f6da17df2bfd89525ec6f5a521c00f8a512c7b245b3153ec7a302d5198\""
audit for lens: passed

1 file inspected, no offenses detected
Error: CLI arg for `fork_org` is not declared for this command
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/cli/args.rb:147:in `method_missing'
/usr/local/Homebrew/Library/Homebrew/utils/github.rb:512:in `block in create_bump_pr'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:316:in `block in cd'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:316:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:316:in `cd'
/usr/local/Homebrew/Library/Homebrew/utils/github.rb:484:in `create_bump_pr'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump-cask-pr.rb:178:in `bump_cask_pr'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
```

### What did you expect to happen?

I expect that pr with updated version will be created.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Just one command:

brew bump-cask-pr --version 4.2.2 lens
```

**Comment by carlocab** [comment]
Looks related to #11158.

CC @dawidd6

**Comment by carlocab** [comment]
Thanks, @dasmfm. Can you check if #11181 fixes this for you?

**Comment by VergeDX** [comment]
@cadrpear 
I have the same issues and seems the fix not working for me...
If any testing is needed, I'd like to do it.

**Comment by carlocab** [comment]
Did you try the fix in https://github.com/Homebrew/brew/pull/11181? What error message do you get from it?

**Comment by VergeDX** [comment]
@cadrpear Oh sorry I'm wrong, it did fix it for me.
I didn't switch branches correctly just now.
