### ISSUE TITLE
post-install step did not complete successfully (openssl@1.1, lzo, libressl, gnutls)

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [Homebrew/brew#11247]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.1.3-91-gfb7d19c
ORIGIN: https://github.com/Homebrew/brew
HEAD: fb7d19c6618f90b30c463fa854ae241fb5e0bacc
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 65969a0f96ab3ab1801286a02eaaca1bf7893423
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.GJP4ldUHE9/org.xquartz:0
HOMEBREW_EDITOR: /usr/local/bin/nano
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit skylake
Clang: 12.0 build 1200
Git: 2.31.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.3-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: 12.4
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  ilmbase
  libav
  lua@5.1
  polipo
  spdylay

Warning: You have installed Bitdefender. The "Traffic Scan" option interferes with
Homebrew's ability to download packages. See:
  https://github.com/Homebrew/brew/issues/5558

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /usr/local/opt/pkg-config

Warning: Putting non-prefixed coreutils in your path can cause GMP builds to fail.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Bitdefender is OFF
as for `/usr/local/opt/pkg-config` brew auto links this when doing `brew link pkg-config`
this issue is similar to https://github.com/Homebrew/brew/issues/10181
however, I am on an intel based mac.

I am getting `post-install step did not complete successfully` for the following
```
openssl@1.1
lzo
libressl
gnutls
```
Extra Info:
```
❯ which security
/usr/bin/security
❯ security list-keychains
    "/Users/ovidijus/Library/Keychains/login.keychain-db"
    "/Library/Keychains/System.keychain"
```

```
❯ brew irb
==> Interactive Homebrew Shell
Example commands available with: `brew irb --examples`

WARNING: This version of ruby is included in macOS for compatibility with legacy software. 
In future versions of macOS the ruby runtime will not be available by 
default, and may require you to install an additional package.

irb(main):001:0> `security list-keychains`
=> "    \"/Users/ovidijus/Library/Keychains/login.keychain-db\"\n    \"/Library/Keychains/System.keychain\"\n"
```

### What happened (include all command output)?

```
brew postinstall gnutls
zsh: correct 'gnutls' to '.gnutls' [nyae]? n
==> Postinstalling gnutls
==> Regenerating CA certificate bundle from keychain, this may take a while...
Warning: The post-install step did not complete successfully
You can try again using:
  brew postinstall gnutls
❯ brew postinstall libressl
==> Postinstalling libressl
==> Regenerating CA certificate bundle from keychain, this may take a while...
Warning: The post-install step did not complete successfully
You can try again using:
  brew postinstall libressl
❯ brew postinstall lzo
==> Postinstalling lzo
❯ brew postinstall openssl@1.1
==> Postinstalling openssl@1.1
==> Regenerating CA certificate bundle from keychain, this may take a while...
Warning: The post-install step did not complete successfully
You can try again using:
  brew postinstall openssl@1.1
  ```

### What did you expect to happen?

to finish? not sure whats going on or where it's failing

### Step-by-step reproduction instructions (by running `brew` commands)

all I did was
```shell
brew reinstall openssl@1.1 lzo libressl gnutls
```
& then it failed to do the postinstall.

**Comment by carlocab** [comment]
Sounds related to https://github.com/Homebrew/homebrew-core/issues/75156 and https://github.com/Homebrew/homebrew-core/issues/75003.

Are you running SentinelOne, perchance?

**Comment by XxUnkn0wnxX** [comment]
nope..
i just ran it with verbose...

```
==> Postinstalling openssl@1.1
/usr/bin/sandbox-exec -f /private/tmp/homebrew20210426-39340-1ww6oo3.sb nice ruby -W1 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/postinstall.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb
==> Regenerating CA certificate bundle from keychain, this may take a while...
Warning: The post-install step did not complete successfully
You can try again using:
  brew postinstall openssl@1.1
==> An exception occurred within a child process:
  Errno::EINTR: Interrupted system call @ rb_file_truncate - /private/tmp/20210426-39341-m2i3cg

/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `truncate'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `block in delegating_block'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb:148:in `block in macos_post_install'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb:145:in `select'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb:145:in `macos_post_install'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/on_os.rb:8:in `on_macos'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb:114:in `post_install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1089:in `block (2 levels) in run_post_install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:924:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1088:in `block in run_post_install'
/usr/local/Homebrew/Library/Homebrew/utils.rb:558:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1077:in `run_post_install'
/usr/local/Homebrew/Library/Homebrew/postinstall.rb:22:in `<main>'
```

i have noticed I have been getting quite a lot of `Errno::EINTR: Interrupted system call` lately.. not sure what is causing this...

**Comment by carlocab** [comment]
Are you running any other security/antivirus software?

**Comment by XxUnkn0wnxX** [comment]
Bitdefender is turned off 

I do run LittleSnitch & Adgurad, however, they monitor connections through a local VPN. they do not interfere with local files on the system...

i have tested this with both of them off, same result...

**Comment by carlocab** [comment]
Try doing
```
export HOMEBREW_TEMP=$HOME/tmp
mkdir $HOMEBREW_TEMP
brew postinstall openssl@1.1
```

**Comment by XxUnkn0wnxX** [comment]
nope still same issue...
`Errno::EINTR: Interrupted system call @ rb_file_truncate - /Users/ovidijus/tmp/20210426-63560-ecpfjk`

however, i have a hunch... i tried ish /bin/bash & i had no issues...

i think its my zsh shell...
i have oh-my-zsh setup.. going to go through plugins etc & see if any of them are causing this...

**Comment by carlocab** [comment]
Sounds like a config issue then, and not a bug in `brew`, so I'm closing this. Feel free to keep posting about your progress here, and I'll still try to help if I can.

**Comment by XxUnkn0wnxX** [comment]
well i'm not sure...

/bin/bash works fine

/usr/local/bin/bash
/usr/bin/zsh
/usr/local/zsh
fail

I even reset all shell config to bare bones with nothing in there & it still fails...

**Comment by XxUnkn0wnxX** [comment]
as a baseline test, i install homebrew on a mac with big sur on it which has never had homebrew installed & I get the same error...

**Comment by carlocab** [comment]
Ok, sounds suspicious. Reopening.

**Comment by Bo98** [comment]
I wonder if wrapping it in a:

```rb
begin
  tmpfile.truncate cert.size
rescue Errno::EINTR
  retry
end
```

is sufficient to workaround this.

**Comment by carlocab** [comment]
@XxUnkn0wnxX can you check if Bo's suggested fix above works? i.e. you can apply
```diff
diff --git a/Formula/openssl@1.1.rb b/Formula/openssl@1.1.rb
index 3fa43ec1db0..7b549821e29 100644
--- a/Formula/openssl@1.1.rb
+++ b/Formula/openssl@1.1.rb
@@ -145,7 +145,11 @@ class OpensslAT11 < Formula
       valid_certs.select do |cert|
         tmpfile.rewind
         tmpfile.write cert
-        tmpfile.truncate cert.size
+        begin
+          tmpfile.truncate cert.size
+        rescue Errno::EINTR
+          retry
+        end
         tmpfile.flush
         IO.popen("/usr/bin/security verify-cert -l -L -R offline -c #{tmpfile.path} &>/dev/null")
```
