### ISSUE TITLE
Error: undefined method `rebuild' for #<BottleSpecification:0x007ffbdbbc2760>

### ISSUE THREAD

**Issue by superwg1984** [Homebrew/brew#1147]
```
Error: undefined method `rebuild' for #<BottleSpecification:0x007ffbdbbc2760>
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Taps/homebrew/homebrew-php/Formula/php56.rb:16:in `block in <class:Php56>'
/usr/local/Library/Homebrew/software_spec.rb:91:in `instance_eval'
/usr/local/Library/Homebrew/software_spec.rb:91:in `bottle'
/usr/local/Library/Homebrew/formula.rb:1726:in `bottle'
/usr/local/Library/Taps/homebrew/homebrew-php/Formula/php56.rb:15:in `<class:Php56>'
/usr/local/Library/Taps/homebrew/homebrew-php/Formula/php56.rb:3:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:21:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:21:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:83:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:74:in `klass'
/usr/local/Library/Homebrew/formulary.rb:70:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:207:in `factory'
/usr/local/Library/Homebrew/formula.rb:1183:in `[]'
/usr/local/Library/Taps/homebrew/homebrew-php/Requirements/php-meta-requirement.rb:14:in `<class:PhpMetaRequirement>'
/usr/local/Library/Taps/homebrew/homebrew-php/Requirements/php-meta-requirement.rb:3:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/Taps/homebrew/homebrew-php/Abstract/abstract-php-phar.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/Taps/homebrew/homebrew-php/Formula/composer.rb:1:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:21:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:21:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:83:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:74:in `klass'
/usr/local/Library/Homebrew/formulary.rb:70:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:167:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:207:in `factory'
/usr/local/Library/Homebrew/formulary.rb:226:in `from_rack'
/usr/local/Library/Homebrew/formula.rb:1134:in `block in installed'
/usr/local/Library/Homebrew/formula.rb:1132:in `map'
/usr/local/Library/Homebrew/formula.rb:1132:in `installed'
/usr/local/Library/Homebrew/diagnostic.rb:1119:in `check_missing_deps'
/usr/local/Library/Homebrew/cmd/doctor.rb:34:in `block in doctor'
/usr/local/Library/Homebrew/cmd/doctor.rb:27:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:27:in `doctor'
/usr/local/Library/brew.rb:83:in `<main>'

**Comment by dunn** [comment]
We'll need your `brew config` and `brew doctor` but my guess is you haven't run `brew update` in a while.

**Comment by MikeMcQuaid** [comment]
I recommend running `brew update` twice which will almost certainly fix this.
