### ISSUE TITLE
Pip error when trying to install the awscli tool - sorry if this is the wrong place to ask for help

### ISSUE THREAD

**Issue by mattpackwood** [Homebrew/brew#11482]
### `brew config` output

```shell
Sorry, did not grab it...
```

### `brew doctor` output

```shell
Sorry, did not grab it...
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Install the awscli on Linuc

### What happened (include all command output)?

```console
mattpackwood@DESKTOP-6Q5TFLB:~$ brew install awscli
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 27 formulae.

==> Downloading https://github.com/aws/aws-cli/archive/2.2.7.tar.gz
Already downloaded: /home/mattpackwood/.cache/Homebrew/downloads/0bd1e6abcba0039ab29cb026b4b3fb212aad557afbcb2efb7bc5462e0caad4d2--aws-cli-2.2.7.tar.gz
==> python3 -m venv /home/linuxbrew/.linuxbrew/Cellar/awscli/2.2.7/libexec
==> /home/linuxbrew/.linuxbrew/Cellar/awscli/2.2.7/libexec/bin/pip install -v -r requirements.txt --ignore-installed /tm
Last 15 lines from /home/mattpackwood/.cache/Homebrew/Logs/awscli/02.pip:
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/home/linuxbrew/.linuxbrew/Cellar/awscli/2.2.7/libexec/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 180, in _main
status = self.run(options, args)
File "/home/linuxbrew/.linuxbrew/Cellar/awscli/2.2.7/libexec/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 204, in wrapper
return func(self, options, args)
File "/home/linuxbrew/.linuxbrew/Cellar/awscli/2.2.7/libexec/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 318, in run
requirement_set = resolver.resolve(
File "/home/linuxbrew/.linuxbrew/Cellar/awscli/2.2.7/libexec/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 136, in resolve
raise error from e
pip._internal.exceptions.DistributionNotFound: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
WARNING: You are using pip version 21.1.1; however, version 21.1.2 is available.
You should consider upgrading via the '/home/linuxbrew/.linuxbrew/Cellar/awscli/2.2.7/libexec/bin/python3.9 -m pip install --upgrade pip' command.
Removed build tracker: '/tmp/pip-req-tracker-sprdtbh0'

READ THIS: https://docs.brew.sh/Troubleshooting
```

### What did you expect to happen?

Install to suceed

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
N/A
```

**Comment by MikeMcQuaid** [comment]
Please open a discussion for this instead. For future issues: please run the requested commands.

**Comment by mattpackwood** [comment]
Will do!
