### ISSUE TITLE
Cannot restart service with `brew services restart foo`

### ISSUE THREAD

**Issue by convenient** [Homebrew/brew#11514]
### `brew config` output

```shell
[11:20:09] lukerodgers [~/src/brew-bug]$ brew config
HOMEBREW_VERSION: 3.1.11-20-gc6dd7ec
ORIGIN: https://github.com/Homebrew/brew
HEAD: c6dd7ec0eb1a1c2f661f499c269ce761f59dd085
Last commit: 45 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 30a210228f2644f17ed582ab00a58635d3718327
Core tap last commit: 68 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nano
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 12.0.5 build 1205
Git: 2.31.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.2-x86_64
CLT: 12.5.0.0.1.1617976050
Xcode: N/A
```

### `brew doctor` output

```shell
[11:20:04] lukerodgers [~/src/brew-bug]$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  elasticsearch
  mysql@5.6

Warning: The filesystem on /System/Volumes/Data appears to be case-sensitive.
The default macOS filesystem is case-insensitive. Please report any apparent problems.

Warning: Putting non-prefixed coreutils in your path can cause GMP builds to fail.

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> /Users/lukerodgers/.bash_profile
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I have also reproduced the above on a travis OSX image that I spun up. With latest version of brew it is broken there too. 

Restarting services does not appear to be working for me.

### What happened (include all command output)?

See the latest version being used
```bash
[11:23:01] lukerodgers [~/src/brew-bug]$ brew --version
Homebrew 3.1.11-20-gc6dd7ec
Homebrew/homebrew-core (git revision 456d18290c; last commit 2021-06-09)
Homebrew/homebrew-cask (git revision 69b24b6dd9; last commit 2021-06-09)
```

See the brewfile being used
```bash
[11:23:07] lukerodgers [~/src/brew-bug]$ cat Brewfile
tap "blackfireio/homebrew-blackfire"
brew "blackfire-agent", restart_service: true
```

See that the service cannot restart
```
[11:23:09] lukerodgers [~/src/brew-bug]$ brew bundle
Using blackfireio/blackfire
Error: wrong number of arguments (given 3, expected 1..2)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/services_cli.rb:212:in `start'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/services_cli.rb:189:in `block in restart'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/services_cli.rb:181:in `each'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/services_cli.rb:181:in `restart'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:80:in `services'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
Using blackfire-agent
Homebrew Bundle complete! 2 Brewfile dependencies now installed.
```

See that blackfire service is not running
```
[11:23:13] lukerodgers [~/src/brew-bug]$ brew services list | grep blackfire
blackfire-agent stopped
```

See that I can manually start it
```
[11:24:00] lukerodgers [~/src/brew-bug]$ brew services start blackfire-agent
==> Successfully started `blackfire-agent` (label: homebrew.mxcl.blackfire-agent)
[11:24:10] lukerodgers [~/src/brew-bug]$ brew services list | grep blackfire
blackfire-agent started lukerodgers /Users/lukerodgers/Library/LaunchAgents/homebrew.mxcl.blackfire-agent.plist
```

See that the restart process is broken
```
[11:24:13] lukerodgers [~/src/brew-bug]$ brew services restart blackfire-agent
Stopping `blackfire-agent`... (might take a while)
==> Successfully stopped `blackfire-agent` (label: homebrew.mxcl.blackfire-agent)
Error: wrong number of arguments (given 3, expected 1..2)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/services_cli.rb:212:in `start'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/services_cli.rb:189:in `block in restart'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/services_cli.rb:181:in `each'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/services_cli.rb:181:in `restart'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:80:in `services'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
```

### What did you expect to happen?

At the end of `brew bundle` the service should be running, also i should be able to do `brew services restart foo` and have that service restart

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
See above
```

**Comment by convenient** [comment]
https://github.com/Homebrew/homebrew-services/pull/354
