### ISSUE TITLE
homebrew postinstall openssl failed

### ISSUE THREAD

**Issue by Jingli2017** [Homebrew/brew#11643]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.2.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 09f7bc27a99469cf947431df4754737dfbadb31d
Last commit: 12 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 963715cc84a534d5a0f1d433391a913057c93939
Core tap last commit: 5 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0.5 build 1205
Git: 2.30.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.3-x86_64
CLT: 12.5.1.0.1.1623191612
Xcode: 12.5.1
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/jing.lijing/PycharmProjects/shopee/shopee_backend/venv/bin/python-config
  /Library/Frameworks/Python.framework/Versions/2.7/bin/python2-config
  /Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7-config
  /Library/Frameworks/Python.framework/Versions/2.7/bin/python-config

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libcrypto.1.1.dylib
  /usr/local/lib/libprotobuf-lite.7.dylib
  /usr/local/lib/libprotobuf.7.dylib
  /usr/local/lib/libprotoc.7.dylib
  /usr/local/lib/libssl.1.1.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/google/protobuf/compiler/code_generator.h
  /usr/local/include/google/protobuf/compiler/command_line_interface.h
  /usr/local/include/google/protobuf/compiler/cpp/cpp_generator.h
  /usr/local/include/google/protobuf/compiler/importer.h
  /usr/local/include/google/protobuf/compiler/java/java_generator.h
  /usr/local/include/google/protobuf/compiler/parser.h
  /usr/local/include/google/protobuf/compiler/plugin.h
  /usr/local/include/google/protobuf/compiler/plugin.pb.h
  /usr/local/include/google/protobuf/compiler/python/python_generator.h
  /usr/local/include/google/protobuf/descriptor.h
  /usr/local/include/google/protobuf/descriptor.pb.h
  /usr/local/include/google/protobuf/descriptor_database.h
  /usr/local/include/google/protobuf/dynamic_message.h
  /usr/local/include/google/protobuf/extension_set.h
  /usr/local/include/google/protobuf/generated_message_reflection.h
  /usr/local/include/google/protobuf/generated_message_util.h
  /usr/local/include/google/protobuf/io/coded_stream.h
  /usr/local/include/google/protobuf/io/gzip_stream.h
  /usr/local/include/google/protobuf/io/printer.h
  /usr/local/include/google/protobuf/io/tokenizer.h
  /usr/local/include/google/protobuf/io/zero_copy_stream.h
  /usr/local/include/google/protobuf/io/zero_copy_stream_impl.h
  /usr/local/include/google/protobuf/io/zero_copy_stream_impl_lite.h
  /usr/local/include/google/protobuf/message.h
  /usr/local/include/google/protobuf/message_lite.h
  /usr/local/include/google/protobuf/reflection_ops.h
  /usr/local/include/google/protobuf/repeated_field.h
  /usr/local/include/google/protobuf/service.h
  /usr/local/include/google/protobuf/stubs/common.h
  /usr/local/include/google/protobuf/stubs/once.h
  /usr/local/include/google/protobuf/text_format.h
  /usr/local/include/google/protobuf/unknown_field_set.h
  /usr/local/include/google/protobuf/wire_format.h
  /usr/local/include/google/protobuf/wire_format_lite.h
  /usr/local/include/google/protobuf/wire_format_lite_inl.h
  /usr/local/include/openssl/aes.h
  /usr/local/include/openssl/asn1.h
  /usr/local/include/openssl/asn1_mac.h
  /usr/local/include/openssl/asn1err.h
  /usr/local/include/openssl/asn1t.h
  /usr/local/include/openssl/async.h
  /usr/local/include/openssl/asyncerr.h
  /usr/local/include/openssl/bio.h
  /usr/local/include/openssl/bioerr.h
  /usr/local/include/openssl/blowfish.h
  /usr/local/include/openssl/bn.h
  /usr/local/include/openssl/bnerr.h
  /usr/local/include/openssl/buffer.h
  /usr/local/include/openssl/buffererr.h
  /usr/local/include/openssl/camellia.h
  /usr/local/include/openssl/cast.h
  /usr/local/include/openssl/cmac.h
  /usr/local/include/openssl/cms.h
  /usr/local/include/openssl/cmserr.h
  /usr/local/include/openssl/comp.h
  /usr/local/include/openssl/comperr.h
  /usr/local/include/openssl/conf.h
  /usr/local/include/openssl/conf_api.h
  /usr/local/include/openssl/conferr.h
  /usr/local/include/openssl/crypto.h
  /usr/local/include/openssl/cryptoerr.h
  /usr/local/include/openssl/ct.h
  /usr/local/include/openssl/cterr.h
  /usr/local/include/openssl/des.h
  /usr/local/include/openssl/dh.h
  /usr/local/include/openssl/dherr.h
  /usr/local/include/openssl/dsa.h
  /usr/local/include/openssl/dsaerr.h
  /usr/local/include/openssl/dtls1.h
  /usr/local/include/openssl/e_os2.h
  /usr/local/include/openssl/ebcdic.h
  /usr/local/include/openssl/ec.h
  /usr/local/include/openssl/ecdh.h
  /usr/local/include/openssl/ecdsa.h
  /usr/local/include/openssl/ecerr.h
  /usr/local/include/openssl/engine.h
  /usr/local/include/openssl/engineerr.h
  /usr/local/include/openssl/err.h
  /usr/local/include/openssl/evp.h
  /usr/local/include/openssl/evperr.h
  /usr/local/include/openssl/hmac.h
  /usr/local/include/openssl/idea.h
  /usr/local/include/openssl/kdf.h
  /usr/local/include/openssl/kdferr.h
  /usr/local/include/openssl/lhash.h
  /usr/local/include/openssl/md2.h
  /usr/local/include/openssl/md4.h
  /usr/local/include/openssl/md5.h
  /usr/local/include/openssl/mdc2.h
  /usr/local/include/openssl/modes.h
  /usr/local/include/openssl/obj_mac.h
  /usr/local/include/openssl/objects.h
  /usr/local/include/openssl/objectserr.h
  /usr/local/include/openssl/ocsp.h
  /usr/local/include/openssl/ocsperr.h
  /usr/local/include/openssl/opensslconf.h
  /usr/local/include/openssl/opensslv.h
  /usr/local/include/openssl/ossl_typ.h
  /usr/local/include/openssl/pem.h
  /usr/local/include/openssl/pem2.h
  /usr/local/include/openssl/pemerr.h
  /usr/local/include/openssl/pkcs12.h
  /usr/local/include/openssl/pkcs12err.h
  /usr/local/include/openssl/pkcs7.h
  /usr/local/include/openssl/pkcs7err.h
  /usr/local/include/openssl/rand.h
  /usr/local/include/openssl/rand_drbg.h
  /usr/local/include/openssl/randerr.h
  /usr/local/include/openssl/rc2.h
  /usr/local/include/openssl/rc4.h
  /usr/local/include/openssl/rc5.h
  /usr/local/include/openssl/ripemd.h
  /usr/local/include/openssl/rsa.h
  /usr/local/include/openssl/rsaerr.h
  /usr/local/include/openssl/safestack.h
  /usr/local/include/openssl/seed.h
  /usr/local/include/openssl/sha.h
  /usr/local/include/openssl/srp.h
  /usr/local/include/openssl/srtp.h
  /usr/local/include/openssl/ssl.h
  /usr/local/include/openssl/ssl2.h
  /usr/local/include/openssl/ssl3.h
  /usr/local/include/openssl/sslerr.h
  /usr/local/include/openssl/stack.h
  /usr/local/include/openssl/store.h
  /usr/local/include/openssl/storeerr.h
  /usr/local/include/openssl/symhacks.h
  /usr/local/include/openssl/tls1.h
  /usr/local/include/openssl/ts.h
  /usr/local/include/openssl/tserr.h
  /usr/local/include/openssl/txt_db.h
  /usr/local/include/openssl/ui.h
  /usr/local/include/openssl/uierr.h
  /usr/local/include/openssl/whrlpool.h
  /usr/local/include/openssl/x509.h
  /usr/local/include/openssl/x509_vfy.h
  /usr/local/include/openssl/x509err.h
  /usr/local/include/openssl/x509v3.h
  /usr/local/include/openssl/x509v3err.h

Warning: Unbrewed '.la' files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected '.la' files:
  /usr/local/lib/libprotobuf-lite.la
  /usr/local/lib/libprotobuf.la
  /usr/local/lib/libprotoc.la

Warning: Unbrewed '.pc' files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected '.pc' files:
  /usr/local/lib/pkgconfig/libcrypto.pc
  /usr/local/lib/pkgconfig/libssl.pc
  /usr/local/lib/pkgconfig/openssl.pc
  /usr/local/lib/pkgconfig/protobuf-lite.pc
  /usr/local/lib/pkgconfig/protobuf.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libcrypto.a
  /usr/local/lib/libprotobuf-lite.a
  /usr/local/lib/libprotobuf.a
  /usr/local/lib/libprotoc.a
  /usr/local/lib/libssl.a
(venv) C02FN1JAMD6P:shopee_backend jing.lijing$
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

install openssl using homebrew

### What happened (include all command output)?

brew reinstall openssl

Warning: The post-install step did not complete successfully
You can try again using:
  brew postinstall openssl@1.1

brew postinstall openssl@1.1
==> An exception occurred within a child process:
  Errno::EINTR: Interrupted system call @ apply2files - /private/tmp/20210703-94879-9afi4y

/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tempfile.rb:207:in `unlink'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tempfile.rb:207:in `unlink'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tempfile.rb:162:in `close'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tempfile.rb:168:in `close!'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb:156:in `macos_post_install'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/on_os.rb:8:in `on_macos'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb:115:in `post_install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1101:in `block (2 levels) in run_post_install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:924:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1100:in `block in run_post_install'
/usr/local/Homebrew/Library/Homebrew/utils.rb:550:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1089:in `run_post_install'
/usr/local/Homebrew/Library/Homebrew/postinstall.rb:22:in `<main>'

### What did you expect to happen?

without warning
Warning: The post-install step did not complete successfully

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew reinstall openssl

brew postinstall openssl@1.1
```

**Comment by gromgit** [comment]
> `Errno::EINTR: Interrupted system call @ apply2files - /private/tmp/20210703-94879-9afi4y`

Are you running an antivirus program or other security software? If so, try disabling it and running the postinstall again.
