### ISSUE TITLE
Trying to run any brew command fails on m1 Mac with macOS monterey

### ISSUE THREAD

**Issue by cliophate** [Homebrew/brew#11668]
### `brew config` output

```shell
Traceback (most recent call last):
	11: from /opt/homebrew/Library/Homebrew/brew.rb:31:in `<main>'
	10: from /opt/homebrew/Library/Homebrew/brew.rb:31:in `require_relative'
	 9: from /opt/homebrew/Library/Homebrew/global.rb:80:in `<top (required)>'
	 8: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 7: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 6: from /opt/homebrew/Library/Homebrew/os.rb:7:in `<top (required)>'
	 5: from /opt/homebrew/Library/Homebrew/os.rb:43:in `<module:OS>'
	 4: from /opt/homebrew/Library/Homebrew/os/mac.rb:60:in `prerelease?'
	 3: from /opt/homebrew/Library/Homebrew/os/mac.rb:28:in `version'
	 2: from /opt/homebrew/Library/Homebrew/os/mac/version.rb:33:in `from_symbol'
	 1: from /opt/homebrew/Library/Homebrew/os/mac/version.rb:33:in `fetch'
/opt/homebrew/Library/Homebrew/os/mac/version.rb:33:in `block in from_symbol': unknown or unsupported macOS version: :dunno (MacOSVersionError)
```

### `brew doctor` output

```shell
Traceback (most recent call last):
	11: from /opt/homebrew/Library/Homebrew/brew.rb:31:in `<main>'
	10: from /opt/homebrew/Library/Homebrew/brew.rb:31:in `require_relative'
	 9: from /opt/homebrew/Library/Homebrew/global.rb:80:in `<top (required)>'
	 8: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 7: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 6: from /opt/homebrew/Library/Homebrew/os.rb:7:in `<top (required)>'
	 5: from /opt/homebrew/Library/Homebrew/os.rb:43:in `<module:OS>'
	 4: from /opt/homebrew/Library/Homebrew/os/mac.rb:60:in `prerelease?'
	 3: from /opt/homebrew/Library/Homebrew/os/mac.rb:28:in `version'
	 2: from /opt/homebrew/Library/Homebrew/os/mac/version.rb:33:in `from_symbol'
	 1: from /opt/homebrew/Library/Homebrew/os/mac/version.rb:33:in `fetch'
/opt/homebrew/Library/Homebrew/os/mac/version.rb:33:in `block in from_symbol': unknown or unsupported macOS version: :dunno (MacOSVersionError)
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

No matter what command I run, they all fail and show the same error, as added above.

### What happened (include all command output)?

Running `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"` gives me error:

```
==> Checking for `sudo` access (which may request your password).
Password:
==> You are using macOS 12.0.
==> We do not provide support for this pre-release version.
This installation may not succeed.
After installation, you will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew\'s GitHub,
Twitter or IRC. You are responsible for resolving any issues you experience
while you are running this pre-release version.
==> This script will install:
/opt/homebrew/bin/brew
/opt/homebrew/share/doc/homebrew
/opt/homebrew/share/man/man1/brew.1
/opt/homebrew/share/zsh/site-functions/_brew
/opt/homebrew/etc/bash_completion.d/brew
/opt/homebrew
Press RETURN to continue or any other key to abort
==> /usr/bin/sudo /usr/sbin/chown -R cliophate:admin /opt/homebrew
==> Downloading and installing Homebrew...
/bin/bash: line 157: 86848 Killed: 9               "$@"
Failed during: git init -q
```

Running any `brew` command gives me
```
Traceback (most recent call last):
	11: from /opt/homebrew/Library/Homebrew/brew.rb:31:in `<main>'
	10: from /opt/homebrew/Library/Homebrew/brew.rb:31:in `require_relative'
	 9: from /opt/homebrew/Library/Homebrew/global.rb:80:in `<top (required)>'
	 8: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 7: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 6: from /opt/homebrew/Library/Homebrew/os.rb:7:in `<top (required)>'
	 5: from /opt/homebrew/Library/Homebrew/os.rb:43:in `<module:OS>'
	 4: from /opt/homebrew/Library/Homebrew/os/mac.rb:60:in `prerelease?'
	 3: from /opt/homebrew/Library/Homebrew/os/mac.rb:28:in `version'
	 2: from /opt/homebrew/Library/Homebrew/os/mac/version.rb:33:in `from_symbol'
	 1: from /opt/homebrew/Library/Homebrew/os/mac/version.rb:33:in `fetch'
/opt/homebrew/Library/Homebrew/os/mac/version.rb:33:in `block in from_symbol': unknown or unsupported macOS version: :dunno (MacOSVersionError)
```

### What did you expect to happen?

Either update or install homebrew. Or anything else for that matter.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. Open terminal
2. Run any commands starting with brew.
3. Failure
```

**Comment by MikeMcQuaid** [comment]
> ==> You are using macOS 12.0.
> ==> We do not provide support for this pre-release version.

**Comment by carlocab** [comment]
> ```
> ==> You are using macOS 12.0.
> ==> We do not provide support for this pre-release version.
> This installation may not succeed.
After installation, you will encounter build failures with some formulae.
> Please create pull requests instead of asking for help on Homebrew\'s GitHub,
Twitter or IRC. You are responsible for resolving any issues you experience
while you are running this pre-release version.
> ```
