### ISSUE TITLE
brew bottle --force-core-tap fails with undefined method `path' for nil:NilClass

### ISSUE THREAD

**Issue by mulle-nat** [Homebrew/brew#11692]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.2.1-70-g5659d74
ORIGIN: https://github.com/Homebrew/brew
HEAD: 5659d74ff59414d22e285d77a7fcfcd3c1bf0614
Last commit: 32 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: de28f292bdb87aa3653c9a40ff8e2ffd2200c99d
Core tap last commit: 63 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: 16-core 64-bit penryn
Clang: 12.0.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed with `brew diy`.
You should find replacements for the following formulae:
  mulle-clang-project
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Create a bottle for a local formula. 

### What happened (include all command output)?

Building the local formula works

```
brew install --verbose --formula --build-bottle mulle-clang-project.rb
...
==> Not running 'post_install' as we're building a bottle
You can run it manually using:
  brew postinstall mulle-clang-project
```

Building the bottle fails though:

```
brew bottle --force-core-tap mulle-clang-project.rb 
==> Determining mulle-clang-project bottle rebuild...
Error: undefined method `path' for nil:NilClass
Did you mean?  paths
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/formula_versions.rb:25:in `initialize'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bottle.rb:314:in `new'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bottle.rb:314:in `bottle_formula'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bottle.rb:105:in `block in bottle'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bottle.rb:104:in `each'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bottle.rb:104:in `bottle'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
```

### What did you expect to happen?

A bottle to appear.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
cat <<EOF > mulle-clang-project.rb
class MulleClangProject < Formula
  desc "Objective-C compiler for the mulle-objc runtime"
  homepage "https://github.com/Codeon-GmbH/mulle-clang-project"
  license "BSD-3-Clause"
  revision 1
  head "https://github.com/Codeon-GmbH/mulle-clang-project.git", branch: "mulle/12.0.0"

  url "https://github.com/Codeon-GmbH/mulle-clang-project/archive/refs/tags/12.0.0.0-RC2.tar.gz"
  sha256 "a8dd4bd48839e4a842fc7631331c10d0f8eb3b8a952f301e1c5a92723e02a387"

  def vendor
    "mulle-clang 12.0.0.0 (runtime-load-version: 17)"
  end

  bottle do
    root_url "https://github.com/Codeon-GmbH/mulle-clang-project/downloads/12.0.0.0-RC2"
  end

  depends_on 'cmake'   => :build
  depends_on 'ninja'   => :build 

  #  compiler_rt doesn't build on macos
  def install
    mkdir "build" do
      args = std_cmake_args
      args << '-DLLVM_ENABLE_PROJECTS=libcxxabi;libcxx;clang'
      args << '-DCMAKE_BUILD_TYPE=Release'
      args << '-DCLANG_VENDOR=mulle' 
      args << '-DCMAKE_INSTALL_MESSAGE=LAZY'
      args << "-DCMAKE_INSTALL_PREFIX='#{prefix}/root'"
      args << '../llvm'
  
      system "cmake", "-G", "Ninja", *args
      system "ninja", "install"
    end
    bin.install_symlink "#{prefix}/root/bin/clang" => "mulle-clang"
    bin.install_symlink "#{prefix}/root/bin/scan-build" => "mulle-scan-build"
  end

  def caveats
    str = <<~EOS
    To use mulle-clang inside homebrew formulae, you need a shim.
    See:
       https://github.com/Codeon-GmbH/mulle-clang-homebrew
    EOS
    str
  end

  test do
    system "#{bin}/mulle-clang", "--help"
  end
end
EOF

brew install --verbose --formula --build-bottle mulle-clang-project.rb
brew bottle --force-core-tap mulle-clang-project.rb
```

Don't do it though, it will take hours to build.
```

**Comment by carlocab** [comment]
Can you try putting `mulle-clang-project.rb` into a tap created with `brew tap-new` before installing it?

So it should be something like:
```
brew tap-new mulle-nat/clang
cp mulle-clang-project.rb $(brew --repo mulle-nat/clang)/Formula
brew install --build-bottle mulle-clang-project
brew bottle mulle-clang-project
```

**Comment by mulle-nat** [comment]
When I made a local tap, like you suggested, then I got it to work.

**Comment by Rylan12** [comment]
Glad it worked. I still think something is wrong here, even if it's just that the `--force-core-tap` flag should be removed. We shouldn't have an option do something that doesn't work.

**Comment by mulle-nat** [comment]
Just being able to use a local file without a tap, was somewhat more convenient.

**Comment by MikeMcQuaid** [comment]
> I still think something is still wrong here, even if it's just that the `--force-core-tap` flag should be removed.

It's a useful developer option. It should probably be hidden from the manpage and require `HOMEBREW_DEVELOPER` to be set.
