### ISSUE TITLE
`brew bundle dump` should work with the `nobody` user

### ISSUE THREAD

**Issue by Kentzo** [Homebrew/brew#11796]
### Provide a detailed description of the proposed feature

The `brew bundle dump` command should not require any privileges beyond read access to the Cellar and should not do any writes other than the specified `Brewfile`.

### What is the motivation for the feature?

As part of my backup routine I only store the list of all installed formulas obtained via the `brew bundle dump` and omit actual binaries. The backup routine is run by a launchd agent registered in the system domain. Since the program specified by the agent is run by root, I need to demote it to the least privileged user for the task and `nobody` is a reasonable choice.

### How will the feature be relevant to at least 90% of Homebrew users?

Removing unnecessary requirements and actions from `brew bundle dump` will allow the users to use it in similar devops contexts and at the very least spare all the users from unnecessary auto-update that is run for that command.

### What alternatives to the feature have been considered?

Manually traversing brew's directories.

**Comment by gromgit** [comment]
I note that the error you get doesn't actually stop the Brewfile from being populated.

In any case, there's already a solution for that: Set the `HOMEBREW_NO_AUTO_UPDATE` to some value.
```shell
$ rm -f /tmp/t.bundle

$ sudo -u nobody /usr/local/bin/brew bundle dump -f --file /tmp/t.bundle
Error: /usr/local/Cellar is not writable. You should change the
ownership and permissions of /usr/local/Cellar back to your
user account:
  sudo chown -R $(whoami) /usr/local/Cellar

$ ls -l /tmp/t.bundle
-rw-r--r-- 1 nobody wheel 448 Jul 31 12:30 /tmp/t.bundle

$ sudo -u nobody env HOMEBREW_NO_AUTO_UPDATE=1 /usr/local/bin/brew bundle dump -f --file /tmp/t.bundle2

$ ls -l /tmp/t.bundle2
-rw-r--r-- 1 nobody wheel 448 Jul 31 12:31 /tmp/t.bundle2

$ cmp /tmp/t.bundle /tmp/t.bundle2 && echo OK
OK
```

**Comment by Kentzo** [comment]
That's not the only error I get:

```
$ brew --version
Homebrew 3.2.5-19-gbdc3391
Homebrew/homebrew-core (git revision 8e371a080f; last commit 2021-07-30)
Homebrew/homebrew-cask (git revision b94910db07; last commit 2021-07-31)

$ sudo -u nobody env HOMEBREW_NO_AUTO_UPDATE=1 /usr/local/bin/brew bundle dump -f --file /tmp/Brewfile
Error: Permission denied @ dir_s_mkdir - /Users/kentzo/Library/Caches
```

**Comment by gromgit** [comment]
What's the output of:
```
sudo -u nobody env HOMEBREW_NO_AUTO_UPDATE=1 /usr/local/bin/brew bundle dump -d -v -f --file /tmp/Brewfile
```
?

**Comment by Kentzo** [comment]
```
$ ls -ld ~ ~/Library
drwxr-xr-x+ 84 kentzo  staff  2688 Aug  1 20:04 /Users/kentzo
drwx------+ 92 kentzo  staff  2944 Apr 11  2020 /Users/kentzo/Library

$ sudo -u nobody env HOMEBREW_NO_AUTO_UPDATE=1 /usr/local/bin/brew bundle dump -d -v -f --file /tmp/Brewfile
/usr/local/Homebrew/Library/Homebrew/shims/scm/git --version
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading
…
Error: Permission denied @ dir_s_mkdir - /Users/kentzo/Library/Caches
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/fileutils.rb:239:in `mkdir'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/fileutils.rb:239:in `fu_mkdir'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/fileutils.rb:217:in `block (2 levels) in mkdir_p'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/fileutils.rb:215:in `reverse_each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/fileutils.rb:215:in `block in mkdir_p'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/fileutils.rb:200:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/fileutils.rb:200:in `mkdir_p'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/pathname.rb:578:in `mkpath'
/usr/local/Homebrew/Library/Homebrew/cache_store.rb:75:in `write_if_dirty!'
/usr/local/Homebrew/Library/Homebrew/cache_store.rb:34:in `use'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2123:in `undeclared_runtime_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1809:in `runtime_dependencies'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:150:in `formula_to_hash'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:111:in `add_formula'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:38:in `map'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:38:in `formulae_by_full_name'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:23:in `formulae'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:55:in `dump'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dumper.rb:19:in `build_brewfile'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dumper.rb:29:in `dump_brewfile'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/dump.rb:9:in `run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/bundle.rb:111:in `bundle'
/usr/local/Homebrew/Library/Homebrew/brew.rb:131:in `<main>'
```

**Comment by MikeMcQuaid** [comment]
> $ sudo -u nobody env HOMEBREW_NO_AUTO_UPDATE=1 /usr/local/bin/brew bundle dump -f --file /tmp/Brewfile
> Error: Permission denied @ dir_s_mkdir - /Users/kentzo/Library/Caches

This won't have set `HOME` correctly if it's not trying to write into a cache directory for `kentzo`.

We'll review a PR for this but this is an extremely niche use-case with a trivial workaround, sorry.

**Comment by Kentzo** [comment]
> This won't have set `HOME` correctly if it's not trying to write into a cache directory for `kentzo`.

Not sure I understood this one. Do you mean I need to set up a trivial `HOME` directory for `nobody` and pass it into sudo environment?

**Comment by MikeMcQuaid** [comment]
@Kentzo I don't know. I just think it's not unsurprising that `nobody` cannot create a cache directory for `kentzo` and Homebrew needs this to be done.

**Comment by Kentzo** [comment]
FYI I have tried setting `HOME` inside to a directory writable by `nobody` and it did work.
