### ISSUE TITLE
Unknown download strategy homebrew_curl was requested

### ISSUE THREAD

**Issue by Ashtonian** [Homebrew/brew#11909]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.1.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 76cfe88b7628a8010bf98115627f6aced4ff8870
Last commit: 3 months ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b0e8f541cbb9fea59d79a18bd78b30584e81a4d5
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0.5 build 1205
Git: 2.33.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.5.1-x86_64
CLT: 12.5.0.22.11
Xcode: N/A
```

### `brew doctor` output

```shell
brew doctor                                                                                                                                                                                         1 ✘  15:10:21   ▓▒░

Error: Unknown download strategy homebrew_curl was requested.
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:1369:in `detect_from_symbol'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:1315:in `detect'
/usr/local/Homebrew/Library/Homebrew/resource.rb:176:in `url'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:77:in `url'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2487:in `url'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/opus.rb:4:in `<class:Opus>'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/opus.rb:1:in `block in load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:78:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:78:in `block in load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:90:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:110:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:195:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:350:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:185:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:180:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:340:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:404:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:452:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:425:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:739:in `block in check_for_unreadable_installed_formula'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:738:in `each'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:738:in `check_for_unreadable_installed_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:64:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:57:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:57:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

brew update and run brew doctor 

### What happened (include all command output)?

Unknown download strategy homebrew_curl was requested.

### What did you expect to happen?

Brew to update 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew doctor
```

**Comment by Ashtonian** [comment]
Fixed, brew update was complaining about git lock file and removing that and updating worked.

**Comment by kraktus** [comment]
I've the same issue, could you be a bit more specific on what you did to solve it?

**Comment by kraktus** [comment]
The issue for me was that I wasn't on the master branch. `cd $(brew --repository) && git checkout master` solved it.
