### ISSUE TITLE
`brew cleanup` should continue even if it wasn't permitted to remove a file

### ISSUE THREAD

**Issue by andreasabel** [Homebrew/brew#11924]
### Provide a detailed description of the proposed feature

Current situation:
```
$ brew cleanup --debug
...
Removing: /usr/local/Cellar/icu4c/67.1... (258 files, 71MB)
Error: Directory not empty @ dir_s_rmdir - /usr/local/Cellar/icu4c/67.1

/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/fileutils.rb:1431:in `rmdir'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/fileutils.rb:1431:in `block in remove_dir1'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/fileutils.rb:1442:in `platform_support'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/fileutils.rb:1430:in `remove_dir1'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/fileutils.rb:1423:in `remove'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/fileutils.rb:760:in `block in remove_entry'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/fileutils.rb:1480:in `ensure in postorder_traverse'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/fileutils.rb:1480:in `postorder_traverse'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/fileutils.rb:758:in `remove_entry'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/fileutils.rb:610:in `block in rm_r'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/fileutils.rb:606:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/fileutils.rb:606:in `rm_r'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/pathname.rb:589:in `rmtree'
/usr/local/Homebrew/Library/Homebrew/keg.rb:275:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:252:in `block in cleanup_keg'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:338:in `cleanup_path'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:252:in `cleanup_keg'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:238:in `each'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:238:in `cleanup_formula'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:190:in `block in clean!'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:189:in `each'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:189:in `clean!'
/usr/local/Homebrew/Library/Homebrew/cmd/cleanup.rb:58:in `cleanup'
/usr/local/Homebrew/Library/Homebrew/brew.rb:129:in `<main>'
```

Atm, `brew cleanup` crashes instead of continuing to clean up.

Feature suggestion: ignore errors, or at least if a flag like `--ignore-errors`, `-i` is given.

### What is the motivation for the feature?

There might be dynlibs I want to hang on so that upgrades do not remove them.  After all, other programs (outside of the `brew` universe) have been linked against than and `brew cleanup` breaks them mercilessly.  A simple workaround is to forbid `brew` to remove this files by making them read-only, but then `brew cleanup` crashes.

### How will the feature be relevant to at least 90% of Homebrew users?

I suppose only 10% use `brew` __exclusively__ for __everything__.

### What alternatives to the feature have been considered?

N/A

**Comment by carlocab** [comment]
I've merged #11931. If you're on the `brew` master branch (e.g. if you're run a dev command -- see `brew developer`), then you should be able to do this with `brew update`. If not, you can wait until it lands on a release tag, or run `brew developer on && brew update`.

**Comment by andreasabel** [comment]
@carlocab Wonderful, that's great!  I tried `HOMEBREW_NO_CLEANUP_FORMULAE=icu4c` with `brew cleanup` on the developer version and it did what I had wanted for a long time!

**Comment by carlocab** [comment]
`HOMEBREW_NO_CLEANUP_FORMULAE` is also in 3.2.11, so you don't need to be on the developer branch to use it.
