### ISSUE TITLE
Error: undefined method `formula' for true:TrueClass

### ISSUE THREAD

**Issue by CaledoniaProject** [Homebrew/brew#12053]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.2.11-127-g63bf99e
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 63bf99e68fc8ac19e662db185fd519a79895914e
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2722b373d4dac5535c6d0514fdcb915834b5ac25
Core tap last commit: 6 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local/homebrew
HOMEBREW_REPOSITORY: /usr/local/homebrew
HOMEBREW_CELLAR: /usr/local/homebrew/Cellar
HOMEBREW_CACHE: /Users/XXX/Library/Caches/homebrew/
HOMEBREW_CASK_OPTS: ["--require-sha"]
HOMEBREW_EDITOR: vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 1
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_NO_INSECURE_REDIRECT: set
HOMEBREW_TEMP: /Users/XXX/Library/Caches/homebrew/
Homebrew Ruby: 2.6.3 => /usr/local/homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: quad-core 64-bit haswell
Clang: 12.0.0 build 1200
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.0.0.32.29
Xcode: 12.4
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed with `brew diy`.
You should find replacements for the following formulae:
  python@2

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  bindfs
  lua@5.1

Warning: Your Cellar and TEMP directories are on different volumes.
macOS won't move relative symlinks across volumes unless the target file already
exists. Brews known to be affected by this are Git and Narwhal.

You should set the "HOMEBREW_TEMP" environment variable to a suitable
directory on the same volume as your Cellar.

Warning: Your Homebrew's prefix is not /usr/local.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/usr/local).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
unsupported configuration.


Warning: Some installed formulae are missing dependencies.
You should `brew install` the missing dependencies:
  brew install openjdk

Run `brew missing` for more details.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

brew upgrade

```
==> Upgrading 1 outdated package:
bindfs 1.14.8 -> 1.15.1
Error: bindfs has been disabled because it requires closed-source macFUSE!
Error: undefined method `formula' for true:TrueClass
/usr/local/homebrew/Library/Homebrew/upgrade.rb:173:in `upgrade_formula'
/usr/local/homebrew/Library/Homebrew/upgrade.rb:83:in `block in upgrade_formulae'
/usr/local/homebrew/Library/Homebrew/upgrade.rb:82:in `each'
/usr/local/homebrew/Library/Homebrew/upgrade.rb:82:in `upgrade_formulae'
/usr/local/homebrew/Library/Homebrew/cmd/upgrade.rb:188:in `upgrade_outdated_formulae'
/usr/local/homebrew/Library/Homebrew/cmd/upgrade.rb:107:in `upgrade'
/usr/local/homebrew/Library/Homebrew/brew.rb:129:in `<main>'
```

### What happened (include all command output)?

command crashed

### What did you expect to happen?

brew upgrade crashes but upgrading specific package works, please see the stack above.
I'm not sure what was wrong here.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew upgrade
```

**Comment by carlocab** [comment]
`brew config` and `brew doctor` absolutely are applicable here; please don't leave those out.

**Comment by CaledoniaProject** [comment]
@carlocab Updated

**Comment by carlocab** [comment]
What's the output of `brew upgrade --debug`? Do you still see this after uninstalling `bindfs`?

**Comment by alexchandel** [comment]
This happened to me twice the past ~5 minutes ago upgrading `outdated`.  `brew` is up to date.

```
==> Upgrading pango
  1.48.9 -> 1.48.10 

==> Pouring pango--1.48.10.big_sur.bottle.tar.gz
🍺  /usr/local/Cellar/pango/1.48.10: 65 files, 3.0MB
Removing: /usr/local/Cellar/pango/1.48.9... (65 files, 3.0MB)
Removing: /Users/alex/Library/Caches/Homebrew/pango--1.48.9... (730.3KB)
Error: undefined method `formula' for true:TrueClass
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:173:in `upgrade_formula'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:83:in `block in upgrade_formulae'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:82:in `each'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:82:in `upgrade_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:188:in `upgrade_outdated_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:107:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:129:in `<main>'
```

and again

```
brew upgrade
…
==> Downloading https://ghcr.io/v2/homebrew/core/libvpx/manifests/1.10.0_1
Already downloaded: /Users/alex/Library/Caches/Homebrew/downloads/164fd97e87b4543a5000f7bbb9b992fe326a0acd1ff0d645372084d1e071e03c--libvpx-1.10.0_1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/libvpx/blobs/sha256:cadad4e7b1bf8d5188da826ac6ecbb7729e0a26ce4665b40fc04386e780c4dc
Already downloaded: /Users/alex/Library/Caches/Homebrew/downloads/4431bcfa250ccd51f54b2640ce5148bef01c524e3679629a01c720d6c764dc56--libvpx--1.10.0_1.big_sur.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/libass/manifests/0.15.2
Already downloaded: /Users/alex/Library/Caches/Homebrew/downloads/e2f5fe958610fb9bb1c3482a92b51639fd03f845eb295914b9c495e3d02cd467--libass-0.15.2.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/libass/blobs/sha256:d11e2972aa5ae2e763cf4101712fac61421082db4d47720a8adc17b8a3e84a2
Already downloaded: /Users/alex/Library/Caches/Homebrew/downloads/dd5747e5398d5b39f6cd1bc93818db0b4e3b8d3491b73003996279bf1dedffd9--libass--0.15.2.big_sur.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/imagemagick/manifests/7.1.0-7
Already downloaded: /Users/alex/Library/Caches/Homebrew/downloads/287f30b2addc9ce81b7457f8a95c89048737c19c5271265391379f5eb1a22f59--imagemagick-7.1.0-7.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/imagemagick/blobs/sha256:7183ec417b94801b6192c4fc3c026e3b99b06b3794d98082d2675c4273
Already downloaded: /Users/alex/Library/Caches/Homebrew/downloads/4f4be2a79c8e69b5960cf3fe4582e5f2b921e2246f9b5ddb14384dea5df6222a--imagemagick--7.1.0-7.big_sur.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/cocoapods/manifests/1.11.2
Already downloaded: /Users/alex/Library/Caches/Homebrew/downloads/8162ba64a6f4439edd3a59d46324b82e248a64472783460c808ed9fa57345a84--cocoapods-1.11.2.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/cocoapods/blobs/sha256:594546dcde868d93407a2f056f7ee76769b90d4742f9a3b29bdfaba32add
Already downloaded: /Users/alex/Library/Caches/Homebrew/downloads/43ea1091a322c0f9bd279f021f23396f39adeb1d6eee6306ab40affc4d6db173--cocoapods--1.11.2.big_sur.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/buildifier/manifests/4.2.1
Already downloaded: /Users/alex/Library/Caches/Homebrew/downloads/c41f8dafaeef4f2eac98a828b24005801f3b4ac6cda63a41e98108f474f1bd24--buildifier-4.2.1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/buildifier/blobs/sha256:1155f17cc3bb102deccaa9e8ee5bff1a8742984d5901d809613c26e9a43
Already downloaded: /Users/alex/Library/Caches/Homebrew/downloads/792268038a6b0b6baf94fe46d0132b6edbce9aad466b5046fcf9350461f56cd0--buildifier--4.2.1.big_sur.bottle.tar.gz
Error: undefined method `formula' for true:TrueClass
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:173:in `upgrade_formula'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:83:in `block in upgrade_formulae'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:82:in `each'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:82:in `upgrade_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:188:in `upgrade_outdated_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:107:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:129:in `<main>'
```

**Comment by CaledoniaProject** [comment]
1. Removing bindfs worked for me, probably due to outdated formula.
2. I have another computer with bindfs installed, but no errors.

debug output is not helpful:
[brew-upgrade-debug.txt](https://github.com/Homebrew/brew/files/7158384/brew-upgrade-debug.txt)

**Comment by alexchandel** [comment]
`brew doctor` is clean.  Something is broken in `brew`

**Comment by Bo98** [comment]
I'll fix the `undefined method` error as that's indeed a bug.

But it's worth nothing it only happens following a previous error. In your case:

```
Error: bindfs has been disabled because it requires closed-source macFUSE!
```
