### ISSUE TITLE
brew upgrade: undefined method `fetch' for nil:NilClass

### ISSUE THREAD

**Issue by serban** [Homebrew/brew#12099]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.2.13-4-gbefaeba
ORIGIN: https://github.com/Homebrew/brew
HEAD: befaeba6c58152f27e6c6a0fe1aeedabfdfa86c3
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 096f0dfa34bbaf4e900fb07b9f99a8b2e30177d1
Core tap last commit: 27 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /Users/serban/homebrew
HOMEBREW_REPOSITORY: /Users/serban/homebrew
HOMEBREW_CELLAR: /Users/serban/homebrew/Cellar
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit haswell
Clang: 12.0.5 build 1205
Git: 2.33.0 => /Users/serban/homebrew/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.6-x86_64
CLT: 12.5.0.22.9
Xcode: 12.5
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /usr/local/bin/python3.5m-config
  /usr/local/bin/python2-config
  /usr/local/bin/python3.6m-config
  /usr/local/bin/python3.7-config
  /usr/local/bin/python2.7-config
  /usr/local/bin/python3.7m-config
  /usr/local/bin/python3.5-config
  /usr/local/bin/python-config
  /usr/local/bin/python3-config
  /usr/local/bin/pcre-config
  /usr/local/bin/python3.6-config

Warning: Your Homebrew's prefix is not /usr/local.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/usr/local).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
unsupported configuration.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

`brew upgrade go`

### What happened (include all command output)?

```
==> Upgrading 1 outdated package:
go 1.17 -> 1.17.1
Error: undefined method `fetch' for nil:NilClass
/Users/serban/homebrew/Library/Homebrew/formula_installer.rb:1139:in `fetch'
/Users/serban/homebrew/Library/Homebrew/upgrade.rb:71:in `block in upgrade_formulae'
/Users/serban/homebrew/Library/Homebrew/upgrade.rb:53:in `map'
/Users/serban/homebrew/Library/Homebrew/upgrade.rb:53:in `upgrade_formulae'
/Users/serban/homebrew/Library/Homebrew/cmd/upgrade.rb:188:in `upgrade_outdated_formulae'
/Users/serban/homebrew/Library/Homebrew/cmd/upgrade.rb:107:in `upgrade'
/Users/serban/homebrew/Library/Homebrew/brew.rb:129:in `<main>'
```

### What did you expect to happen?

Formulae are updated without issue.

### Step-by-step reproduction instructions (by running `brew` commands)

Run `brew upgrade go` or just a plain `brew upgrade`. The same error occurs for other packages such as `gmp`.

**Comment by Bo98** [comment]
This was an edge case after a recent refactor.

Should hopefully be fixed now!
