### ISSUE TITLE
formula.rb#specified_path calling exist? on a String causes brew install failures

### ISSUE THREAD

**Issue by paulgeringer** [Homebrew/brew#12104]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.2.13-29-g1f3de1d-dirty
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1f3de1d5b28e8ab52d96c4341e97117e14095380
Last commit: 11 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5166413830a90981bea227bc27975f647020e27c
Core tap last commit: 58 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 13.0.0 build 1300
Git: 2.28.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.6-x86_64
CLT: 13.0.0.0.1.1630607135
Xcode: N/A
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

`brew install python`

### What happened (include all command output)?

```
==> Pouring python@3.9--3.9.7.big_sur.bottle.tar.gz
Error: undefined method `exist?' for #<String:0x00007f9bc4882270>
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/formula.rb:315:in `specified_path'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:1177:in `pour'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:401:in `install'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:726:in `install_dependency'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:646:in `block in install_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:646:in `each'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:646:in `install_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:376:in `install'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:208:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:181:in `upgrade_formula'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:84:in `block in upgrade_formulae'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:83:in `each'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:83:in `upgrade_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:189:in `upgrade_outdated_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:107:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:129:in `<main>'
```

### What did you expect to happen?

brew to install python

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update
brew install python
```

**Comment by paulgeringer** [comment]
Issue appears to have been created with this commit: https://github.com/Homebrew/brew/commit/e8e1deeb32d645428229079f6826ed22a059cf52#diff-91b7d3ceb5b783bc460ef7957ed4a960e6d5988c20e925ee78a970e37b8b6954L325-R316
