### ISSUE TITLE
Plantuml missing dependencies

### ISSUE THREAD

**Issue by LosWochos76** [Homebrew/brew#12142]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.2.13
ORIGIN: https://github.com/Homebrew/brew
HEAD: 109f24fd601177dea4a754b43efe684903db2a83
Last commit: 9 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a260aebd5cb50110a0815f706e3bbbf5b99f4846
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 20
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 20-core 64-bit dunno
Clang: 13.0.0 build 1300
Git: 2.33.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.6-x86_64
CLT: 13.0.0.0.1.1630607135
Xcode: 13.0
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I installed plantuml in order to convert text-based UML-diagrams-descriptions to images.
I can successfully convert to PNG files but it fails to create PDF files because of missing dependencies, see here: https://plantuml.com/de/pdf

Those dependencies (Batik and FOP in a specific version) should be installed by homebrew as well.

### What happened (include all command output)?

java.lang.ClassNotFoundException: org.apache.batik.apps.rasterizer.SVGConverter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at net.sourceforge.plantuml.pdf.PdfConverter.convert(PdfConverter.java:57)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramInternalPdf(UmlDiagram.java:288)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:140)
	at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:157)
	at net.sourceforge.plantuml.PSystemUtils.exportDiagramsCuca(PSystemUtils.java:233)
	at net.sourceforge.plantuml.PSystemUtils.exportDiagrams(PSystemUtils.java:89)
	at net.sourceforge.plantuml.SourceFileReaderAbstract.getGeneratedImages(SourceFileReaderAbstract.java:171)
	at net.sourceforge.plantuml.Run.manageFileInternal(Run.java:527)
	at net.sourceforge.plantuml.Run.processArgs(Run.java:410)
	at net.sourceforge.plantuml.Run.manageAllFiles(Run.java:377)
	at net.sourceforge.plantuml.Run.main(Run.java:205)
Exception in thread "main" java.lang.UnsupportedOperationException
	at net.sourceforge.plantuml.pdf.PdfConverter.convert(PdfConverter.java:76)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramInternalPdf(UmlDiagram.java:288)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:140)
	at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:157)
	at net.sourceforge.plantuml.PSystemUtils.exportDiagramsCuca(PSystemUtils.java:233)
	at net.sourceforge.plantuml.PSystemUtils.exportDiagrams(PSystemUtils.java:89)
	at net.sourceforge.plantuml.SourceFileReaderAbstract.getGeneratedImages(SourceFileReaderAbstract.java:171)
	at net.sourceforge.plantuml.Run.manageFileInternal(Run.java:527)
	at net.sourceforge.plantuml.Run.processArgs(Run.java:410)
	at net.sourceforge.plantuml.Run.manageAllFiles(Run.java:377)
	at net.sourceforge.plantuml.Run.main(Run.java:205)

### What did you expect to happen?

A successfull conversion to PDF.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install plantuml
plantuml -tpdf [any plantuml file]
```

**Comment by LosWochos76** [comment]
BTW: Manually installing Batik and FOP using homebrew does not solve the problem either.
