### ISSUE TITLE
Error: unknown keyword: timeout for Tap repo with 3.2.15

### ISSUE THREAD

**Issue by paulmarsicloud** [Homebrew/brew#12215]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.2.15
ORIGIN: https://github.com/Homebrew/brew
HEAD: 92749f9c5243691f8e576aa1227cb9ebba509cd4
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a8d291e43426da55a6ceb3641323056ae8ffae57
Core tap last commit: 43 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0.0 build 1200
Git: 2.28.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/local/Homebrew/Library/Homebrew/shims/shared/curl
macOS: 10.15.7-x86_64
CLT: 12.0.0.32.29
Xcode: 12.2
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  aws-okta

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Warning: Found Ruby file outside lululemon/tools tap formula directory.
(/usr/local/Homebrew/Library/Taps/lululemon/homebrew-tools/Formula):
  /usr/local/Homebrew/Library/Taps/lululemon/homebrew-tools/custom_download_strategy.rb

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc

Warning: Your Xcode (12.2) is outdated.
Please update to Xcode 12.4 (or delete it).
Xcode can be updated from the App Store.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

From a private `tap` I am trying to install an application, but it is failing with:
```
brew install <REDACTED>
Warning: Treating <REDACTED> as a formula. For the cask, use homebrew/cask/<REDACTED>
==> Downloading <REDACTED>
Error: unknown keyword: timeout
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Taps/<REDACTED>/homebrew-tools/custom_download_strategy.rb:99:in `_fetch'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:408:in `fetch'
/usr/local/Homebrew/Library/Homebrew/resource.rb:147:in `fetch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/forwardable.rb:230:in `fetch'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2064:in `fetch'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:1149:in `fetch'
/usr/local/Homebrew/Library/Homebrew/install.rb:298:in `block in install_formulae'
/usr/local/Homebrew/Library/Homebrew/install.rb:272:in `map'
/usr/local/Homebrew/Library/Homebrew/install.rb:272:in `install_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:206:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:129:in `<main>'
```

### What happened (include all command output)?

See above for error

`custom_download_strategy.rb` is this file: https://gist.githubusercontent.com/minamijoyo/3d8aa79085369efb79964ba45e24bb0e/raw/92e25fea54d0effce2e79fd681b5fd6dab2d205b/private_strategy.rb

### What did you expect to happen?

Brew should have installed the app

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
When I downgrade brew to `3.2.14` this works without any issues:

cd /usr/local/Homebrew
git checkout 3.2.14
export HOMEBREW_NO_AUTO_UPDATE=1
brew --version
---
Homebrew 3.2.14
Homebrew/homebrew-core (git revision 525efcabe33; last commit 2021-10-08)
Homebrew/homebrew-cask (git revision 05c0b107e3; last commit 2021-10-08)
---
brew install <REDACTED>
Warning: Treating <REDACTED> as a formula. For the cask, use homebrew/cask/<REDACTED>
==> Downloading <REDACTED>
==> Installing <REDACTED> from <REDACTED>
Warning: Your Xcode (12.2) is outdated.
Please update to Xcode 12.4 (or delete it).
Xcode can be updated from the App Store.

==> mv <REDACTED> <REDACTED>
🍺  <REDACTED>: 3 files, 168.7MB, built in 124 seconds
```
```

**Comment by cgeisel** [comment]
Based on my reading of the code in download_strategy.rb, it looks like CurlGitHubPackagesDownloadStrategy is the strategy to use with a personal access token, which is how we were authenticating with a private repo previously.

However the current implementation looks for .artifact_domain, which I think maps to HOMEBREW_ARTIFACT_DOMAIN, which is going to prefix the url in the Formula, which results in a url like YOURTOKEN/https://github.com/your-private-org/your-private-repo that returns a 404.

Should this code be using .github_api_token which I think maps to HOMEBREW_GITHUB_API_TOKEN, or is there another way of doing this?

**Comment by Bo98** [comment]
> The code has since been removed.

To be clear: this isn't even recent. That code was deprecated nearly 3 years ago to the day (1.8.0) and likely disabled in 1.9.0.
