### ISSUE TITLE
brew test fails with "cannot load such file -- minitest" and "cannot load such file -- sorbet-runtime-stub"

### ISSUE THREAD

**Issue by ferhaty** [Homebrew/brew#12242]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.2.16-31-g976f9da
ORIGIN: https://github.com/Homebrew/brew
HEAD: 976f9daa12e86c9e1ff5ea88e95f3988a9855679
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1edaa475cac6db07b038d7cd3f3c0352d1312821
Core tap last commit: 5 minutes ago
Core tap branch: liqoctl
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 12.0.5 build 1205
Git: 2.33.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.5-x86_64
CLT: 12.5.1.0.1.1623191612
Xcode: N/A
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 13.0.


Warning: Some taps are not on the default git origin branch and may not receive
updates. If this is a surprise to you, check out the default branch with:
  git -C $(brew --repo homebrew/core) checkout master
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Trying to test a new formula which I'm creating. However, `brew test` keeps failing. `brew test` completely breaks my `brew` when I run it with any formula. I need to run `brew update-reset` to fix it again. 

```shell
$ brew
Traceback (most recent call last):
	9: from /usr/local/Homebrew/Library/Homebrew/brew.rb:29:in `<main>'
	8: from /usr/local/Homebrew/Library/Homebrew/brew.rb:29:in `require_relative'
	7: from /usr/local/Homebrew/Library/Homebrew/global.rb:4:in `<top (required)>'
	6: from /usr/local/Homebrew/Library/Homebrew/global.rb:4:in `require_relative'
	5: from /usr/local/Homebrew/Library/Homebrew/startup.rb:10:in `<top (required)>'
	4: from /usr/local/Homebrew/Library/Homebrew/startup.rb:10:in `require_relative'
	3: from /usr/local/Homebrew/Library/Homebrew/startup/sorbet.rb:9:in `<top (required)>'
	2: from /usr/local/Homebrew/Library/Homebrew/startup/sorbet.rb:9:in `require'
	1: from /usr/local/Homebrew/Library/Homebrew/standalone/sorbet.rb:11:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/standalone/sorbet.rb:11:in `require': cannot load such file -- sorbet-runtime-stub (LoadError)
```

### What happened (include all command output)?

```shell
$ brew test liqoctl
Fetching gem metadata from https://rubygems.org/.......
Fetching minitest 5.14.4
Fetching zeitwerk 2.4.2
Fetching concurrent-ruby 1.1.9
Installing zeitwerk 2.4.2
Installing minitest 5.14.4
Fetching public_suffix 4.0.6
Installing concurrent-ruby 1.1.9
Installing public_suffix 4.0.6
Fetching ast 2.4.2
Installing ast 2.4.2
Fetching bindata 2.4.10
Fetching msgpack 1.4.2
Installing bindata 2.4.10
Installing msgpack 1.4.2 with native extensions
Using bundler 1.17.3
Fetching byebug 11.1.3
Installing byebug 11.1.3 with native extensions
Fetching coderay 1.1.3
Installing coderay 1.1.3
Fetching colorize 0.8.1
Installing colorize 0.8.1
Fetching highline 2.0.3
Installing highline 2.0.3
Fetching connection_pool 2.2.5
Installing connection_pool 2.2.5
Fetching did_you_mean 1.5.0
Installing did_you_mean 1.5.0
Fetching diff-lcs 1.4.4
Installing diff-lcs 1.4.4
Fetching docile 1.4.0
Installing docile 1.4.0
Fetching unf_ext 0.0.8
Installing unf_ext 0.0.8 with native extensions
Fetching regexp_parser 2.1.1
Installing regexp_parser 2.1.1
Fetching hana 1.3.7
Installing hana 1.3.7
Fetching hpricot 0.8.6
Installing hpricot 0.8.6 with native extensions
Fetching uri_template 0.7.0
Installing uri_template 0.7.0
Fetching mime-types-data 3.2021.0901
Installing mime-types-data 3.2021.0901
Fetching net-http-digest_auth 1.4.1
Installing net-http-digest_auth 1.4.1
Fetching mini_portile2 2.6.1
Installing mini_portile2 2.6.1
Fetching racc 1.5.2
Installing racc 1.5.2 with native extensions
Fetching rubyntlm 0.6.3
Installing rubyntlm 0.6.3
Fetching webrick 1.7.0
Installing webrick 1.7.0
Fetching webrobots 0.1.2
Installing webrobots 0.1.2
Fetching method_source 1.0.0
Installing method_source 1.0.0
Fetching mustache 1.1.1
Installing mustache 1.1.1
Fetching parallel 1.21.0
Installing parallel 1.21.0
Fetching rainbow 3.0.0
Installing rainbow 3.0.0
Fetching sorbet-runtime 0.5.9226
Installing sorbet-runtime 0.5.9226
Fetching plist 3.6.0
Fetching rack 2.2.3
Installing plist 3.6.0
Fetching rdiscount 2.2.0.2
Installing rack 2.2.3
Installing rdiscount 2.2.0.2 with native extensions
Fetching rexml 3.2.5
Installing rexml 3.2.5
Fetching rspec-support 3.10.2
Installing rspec-support 3.10.2
Fetching sorbet-static 0.5.9226 (universal-darwin-14)
Installing sorbet-static 0.5.9226 (universal-darwin-14)
Fetching ruby-progressbar 1.11.0
Installing ruby-progressbar 1.11.0
Fetching unicode-display_width 2.1.0
Installing unicode-display_width 2.1.0
Fetching ruby-macho 2.5.1
Installing ruby-macho 2.5.1
Fetching simplecov-html 0.12.3
Installing simplecov-html 0.12.3
Fetching simplecov_json_formatter 0.1.3
Installing simplecov_json_formatter 0.1.3
Fetching sorbet-runtime-stub 0.2.0
Installing sorbet-runtime-stub 0.2.0
Fetching thor 1.1.0
Installing thor 1.1.0
Fetching warning 1.2.1
Installing warning 1.2.1
Fetching parser 3.0.2.0
Installing parser 3.0.2.0
Fetching addressable 2.8.0
Installing addressable 2.8.0
Fetching elftools 1.1.3
Installing elftools 1.1.3
Fetching i18n 1.8.10
Installing i18n 1.8.10
Fetching tzinfo 2.0.4
Installing tzinfo 2.0.4
Fetching commander 4.6.0
Installing commander 4.6.0
Fetching net-http-persistent 4.0.1
Installing net-http-persistent 4.0.1
Fetching bootsnap 1.9.1
Installing bootsnap 1.9.1 with native extensions
Fetching ecma-re-validator 0.3.0
Installing ecma-re-validator 0.3.0
Fetching mime-types 3.3.1
Installing mime-types 3.3.1
Fetching unf 0.1.4
Installing unf 0.1.4
Fetching pry 0.14.1
Installing pry 0.14.1
Fetching parallel_tests 3.7.3
Installing parallel_tests 3.7.3
Fetching nokogiri 1.12.5 (x86_64-darwin)
Installing nokogiri 1.12.5 (x86_64-darwin)
Fetching rspec-core 3.10.1
Installing rspec-core 3.10.1
Fetching rspec-expectations 3.10.1
Installing rspec-expectations 3.10.1
Fetching rspec-mocks 3.10.2
Installing rspec-mocks 3.10.2
Fetching sorbet 0.5.9226
Installing sorbet 0.5.9226
Fetching simplecov 0.21.2
Installing simplecov 0.21.2
Fetching unparser 0.6.0
Installing unparser 0.6.0
Fetching rubocop-ast 1.12.0
Installing rubocop-ast 1.12.0
Fetching patchelf 1.3.0
Installing patchelf 1.3.0
Fetching activesupport 6.1.4.1
Installing activesupport 6.1.4.1
Fetching parlour 6.0.1
Installing parlour 6.0.1
Fetching json_schemer 0.2.18
Installing json_schemer 0.2.18
Fetching domain_name 0.5.20190701
Installing domain_name 0.5.20190701
Fetching rspec-github 2.3.1
Installing rspec-github 2.3.1
Fetching rspec-retry 0.6.2
Installing rspec-retry 0.6.2
Fetching rspec_junit_formatter 0.4.1
Installing rspec_junit_formatter 0.4.1
Fetching rspec-its 1.3.0
Installing rspec-its 1.3.0
Fetching rspec 3.10.0
Installing rspec 3.10.0
Fetching rspec-sorbet 1.8.0
Fetching spoom 1.1.4
Installing rspec-sorbet 1.8.0
Installing spoom 1.1.4
Fetching simplecov-cobertura 1.4.2
Installing simplecov-cobertura 1.4.2
Fetching rbi 0.0.6
Fetching rubocop 1.22.0
Installing rbi 0.0.6
Fetching http-cookie 1.0.4
Fetching rspec-wait 0.0.9
Installing http-cookie 1.0.4
Installing rubocop 1.22.0
Installing rspec-wait 0.0.9
Fetching ronn 0.7.3
Fetching tapioca 0.5.2
Installing tapioca 0.5.2
Installing ronn 0.7.3
Fetching mechanize 2.8.1
Installing mechanize 2.8.1
Fetching rubocop-performance 1.11.5
Fetching rubocop-rails 2.12.3
Fetching rubocop-rspec 2.5.0
Installing rubocop-performance 1.11.5
Installing rubocop-rspec 2.5.0
Installing rubocop-rails 2.12.3
Fetching rubocop-sorbet 0.6.2
Installing rubocop-sorbet 0.6.2
Bundle complete! 34 Gemfile dependencies, 92 gems now installed.
Bundled gems are installed into `../../../../../Homebrew/Library/Homebrew/vendor/bundle`
Post-install message from sorbet:

  Thanks for installing Sorbet! To use it in your project, first run:

    bundle exec srb init

  which will get your project ready to use with Sorbet.
  After that whenever you want to typecheck your code, run:

    bundle exec srb tc

  For more docs see: https://sorbet.org/docs/adopting
Removing hana (1.3.7)
Removing rexml (3.2.5)
Removing mime-types-data (3.2021.0901)
Removing webrick (1.7.0)
Removing rubocop-ast (1.12.0)
Removing ruby-macho (2.5.1)
Removing tapioca (0.5.2)
Removing simplecov-cobertura (1.4.2)
Removing simplecov-html (0.12.3)
Removing docile (1.4.0)
Removing rbi (0.0.6)
Removing rspec-expectations (3.10.1)
Removing rubocop (1.22.0)
Removing concurrent-ruby (1.1.9)
Removing i18n (1.8.10)
Removing did_you_mean (1.5.0)
Removing rubocop-rails (2.12.3)
Removing mustache (1.1.1)
Removing ruby-progressbar (1.11.0)
Removing spoom (1.1.4)
Removing rspec (3.10.0)
Removing rspec-retry (0.6.2)
Removing rspec-wait (0.0.9)
Removing nokogiri-1.12.5-x86_64 (darwin)
Removing coderay (1.1.3)
Removing rspec_junit_formatter (0.4.1)
Removing webrobots (0.1.2)
Removing regexp_parser (2.1.1)
Removing highline (2.0.3)
Removing rubocop-rspec (2.5.0)
Removing elftools (1.1.3)
Removing http-cookie (1.0.4)
Removing simplecov (0.21.2)
Removing patchelf (1.3.0)
Removing mini_portile2 (2.6.1)
Removing thor (1.1.0)
Removing ronn (0.7.3)
Removing parlour (6.0.1)
Removing sorbet-runtime (0.5.9226)
Removing rspec-core (3.10.1)
Removing parser (3.0.2.0)
Removing rubocop-sorbet (0.6.2)
Removing warning (1.2.1)
Removing rainbow (3.0.0)
Removing ecma-re-validator (0.3.0)
Removing public_suffix (4.0.6)
Removing tzinfo (2.0.4)
Removing unf (0.1.4)
Removing rspec-its (1.3.0)
Removing pry (0.14.1)
Removing simplecov_json_formatter (0.1.3)
Removing racc (1.5.2)
Removing net-http-persistent (4.0.1)
Removing parallel (1.21.0)
Removing rspec-mocks (3.10.2)
Removing hpricot (0.8.6)
Removing byebug (11.1.3)
Removing plist (3.6.0)
Removing parallel_tests (3.7.3)
Removing sorbet-static-0.5.9226-universal-darwin (14)
Removing unicode-display_width (2.1.0)
Removing domain_name (0.5.20190701)
Removing diff-lcs (1.4.4)
Removing addressable (2.8.0)
Removing uri_template (0.7.0)
Removing rspec-github (2.3.1)
Removing unf_ext (0.0.8)
Removing method_source (1.0.0)
Removing sorbet (0.5.9226)
Removing activesupport (6.1.4.1)
Removing net-http-digest_auth (1.4.1)
Removing msgpack (1.4.2)
Removing json_schemer (0.2.18)
Removing rubyntlm (0.6.3)
Removing commander (4.6.0)
Removing unparser (0.6.0)
Removing colorize (0.8.1)
Removing rspec-sorbet (1.8.0)
Removing zeitwerk (2.4.2)
Removing bootsnap (1.9.1)
Removing bindata (2.4.10)
Removing rspec-support (3.10.2)
Removing minitest (5.14.4)
Removing mime-types (3.3.1)
Removing mechanize (2.8.1)
Removing connection_pool (2.2.5)
Removing rdiscount (2.2.0.2)
Removing ast (2.4.2)
Removing rack (2.2.3)
Removing sorbet-runtime-stub (0.2.0)
Removing rubocop-performance (1.11.5)
Error: cannot load such file -- minitest
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/formula_assertions.rb:11:in `require'
/usr/local/Homebrew/Library/Homebrew/formula_assertions.rb:11:in `<module:Assertions>'
/usr/local/Homebrew/Library/Homebrew/formula_assertions.rb:8:in `<module:Homebrew>'
/usr/local/Homebrew/Library/Homebrew/formula_assertions.rb:4:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/test.rb:42:in `require'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/test.rb:42:in `test'
/usr/local/Homebrew/Library/Homebrew/brew.rb:129:in `<main>'
```

### What did you expect to happen?

Display test results of the formula

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew test kubernetes-cli

$ brew
Traceback (most recent call last):
	9: from /usr/local/Homebrew/Library/Homebrew/brew.rb:29:in `<main>'
	8: from /usr/local/Homebrew/Library/Homebrew/brew.rb:29:in `require_relative'
	7: from /usr/local/Homebrew/Library/Homebrew/global.rb:4:in `<top (required)>'
	6: from /usr/local/Homebrew/Library/Homebrew/global.rb:4:in `require_relative'
	5: from /usr/local/Homebrew/Library/Homebrew/startup.rb:10:in `<top (required)>'
	4: from /usr/local/Homebrew/Library/Homebrew/startup.rb:10:in `require_relative'
	3: from /usr/local/Homebrew/Library/Homebrew/startup/sorbet.rb:9:in `<top (required)>'
	2: from /usr/local/Homebrew/Library/Homebrew/startup/sorbet.rb:9:in `require'
	1: from /usr/local/Homebrew/Library/Homebrew/standalone/sorbet.rb:11:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/standalone/sorbet.rb:11:in `require': cannot load such file -- sorbet-runtime-stub (LoadError)
```

**Comment by ferhaty** [comment]
Unfortunately it doesn't work. 

```
$ brew ruby -e 'Homebrew.install_bundler!; p which("bundle"); p `bundle --version`'
#<Pathname:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/bundle>
"Bundler version 1.17.3\n"

$ rm -rf ~/.gem/ruby/2.6.0/gems/bundler-*
$ rm -f ~/.gem/ruby/2.6.0/cache/bundler-* ~/.gem/ruby/2.6.0/specifications/bundler-* ~/.gem/ruby/2.6.0/bundle ~/.gem/ruby/2.6.0/bundler
$ brew test liqoctl
==> Installing 'bundler' gem
Fetching bundler-1.17.3.gem
Fetching gem metadata from https://rubygems.org/.......
Fetching concurrent-ruby 1.1.9
Fetching minitest 5.14.4
Fetching zeitwerk 2.4.2
Installing zeitwerk 2.4.2
Installing concurrent-ruby 1.1.9
Installing minitest 5.14.4
Fetching public_suffix 4.0.6
Installing public_suffix 4.0.6
Fetching ast 2.4.2
Installing ast 2.4.2
Fetching bindata 2.4.10
Installing bindata 2.4.10
Fetching msgpack 1.4.2
Installing msgpack 1.4.2 with native extensions
Using bundler 1.17.3
Fetching byebug 11.1.3
Installing byebug 11.1.3 with native extensions
Fetching coderay 1.1.3
Installing coderay 1.1.3
Fetching colorize 0.8.1
Installing colorize 0.8.1
Fetching highline 2.0.3
Installing highline 2.0.3
Fetching connection_pool 2.2.5
Installing connection_pool 2.2.5
Fetching did_you_mean 1.5.0
Installing did_you_mean 1.5.0
Fetching diff-lcs 1.4.4
Installing diff-lcs 1.4.4
Fetching docile 1.4.0
Installing docile 1.4.0
Fetching unf_ext 0.0.8
Installing unf_ext 0.0.8 with native extensions
Fetching regexp_parser 2.1.1
Installing regexp_parser 2.1.1
Fetching hana 1.3.7
Installing hana 1.3.7
Fetching hpricot 0.8.6
Installing hpricot 0.8.6 with native extensions
Fetching uri_template 0.7.0
Installing uri_template 0.7.0
Fetching mime-types-data 3.2021.0901
Installing mime-types-data 3.2021.0901
Fetching net-http-digest_auth 1.4.1
Installing net-http-digest_auth 1.4.1
Fetching mini_portile2 2.6.1
Installing mini_portile2 2.6.1
Fetching racc 1.5.2
Installing racc 1.5.2 with native extensions
Fetching rubyntlm 0.6.3
Installing rubyntlm 0.6.3
Fetching webrick 1.7.0
Installing webrick 1.7.0
Fetching webrobots 0.1.2
Installing webrobots 0.1.2
Fetching method_source 1.0.0
Installing method_source 1.0.0
Fetching mustache 1.1.1
Installing mustache 1.1.1
Fetching parallel 1.21.0
Installing parallel 1.21.0
Fetching rainbow 3.0.0
Installing rainbow 3.0.0
Fetching sorbet-runtime 0.5.9226
Installing sorbet-runtime 0.5.9226
Fetching plist 3.6.0
Installing plist 3.6.0
Fetching rack 2.2.3
Installing rack 2.2.3
Fetching rdiscount 2.2.0.2
Installing rdiscount 2.2.0.2 with native extensions
Fetching rexml 3.2.5
Installing rexml 3.2.5
Fetching rspec-support 3.10.2
Installing rspec-support 3.10.2
Fetching sorbet-static 0.5.9226 (universal-darwin-14)
Installing sorbet-static 0.5.9226 (universal-darwin-14)
Fetching ruby-progressbar 1.11.0
Installing ruby-progressbar 1.11.0
Fetching unicode-display_width 2.1.0
Installing unicode-display_width 2.1.0
Fetching ruby-macho 2.5.1
Installing ruby-macho 2.5.1
Fetching simplecov-html 0.12.3
Installing simplecov-html 0.12.3
Fetching simplecov_json_formatter 0.1.3
Installing simplecov_json_formatter 0.1.3
Fetching sorbet-runtime-stub 0.2.0
Installing sorbet-runtime-stub 0.2.0
Fetching thor 1.1.0
Installing thor 1.1.0
Fetching warning 1.2.1
Installing warning 1.2.1
Fetching parser 3.0.2.0
Installing parser 3.0.2.0
Fetching addressable 2.8.0
Installing addressable 2.8.0
Fetching elftools 1.1.3
Installing elftools 1.1.3
Fetching i18n 1.8.10
Installing i18n 1.8.10
Fetching tzinfo 2.0.4
Installing tzinfo 2.0.4
Fetching commander 4.6.0
Installing commander 4.6.0
Fetching net-http-persistent 4.0.1
Installing net-http-persistent 4.0.1
Fetching bootsnap 1.9.1
Installing bootsnap 1.9.1 with native extensions
Fetching ecma-re-validator 0.3.0
Installing ecma-re-validator 0.3.0
Fetching mime-types 3.3.1
Installing mime-types 3.3.1
Fetching unf 0.1.4
Installing unf 0.1.4
Fetching pry 0.14.1
Installing pry 0.14.1
Fetching parallel_tests 3.7.3
Installing parallel_tests 3.7.3
Fetching nokogiri 1.12.5 (x86_64-darwin)
Installing nokogiri 1.12.5 (x86_64-darwin)
Fetching rspec-core 3.10.1
Installing rspec-core 3.10.1
Fetching rspec-expectations 3.10.1
Installing rspec-expectations 3.10.1
Fetching rspec-mocks 3.10.2
Installing rspec-mocks 3.10.2
Fetching sorbet 0.5.9226
Installing sorbet 0.5.9226
Fetching simplecov 0.21.2
Installing simplecov 0.21.2
Fetching unparser 0.6.0
Installing unparser 0.6.0
Fetching rubocop-ast 1.12.0
Installing rubocop-ast 1.12.0
Fetching patchelf 1.3.0
Installing patchelf 1.3.0
Fetching activesupport 6.1.4.1
Installing activesupport 6.1.4.1
Fetching parlour 6.0.1
Installing parlour 6.0.1
Fetching json_schemer 0.2.18
Installing json_schemer 0.2.18
Fetching domain_name 0.5.20190701
Installing domain_name 0.5.20190701
Fetching rspec-github 2.3.1
Installing rspec-github 2.3.1
Fetching rspec-retry 0.6.2
Installing rspec-retry 0.6.2
Fetching rspec_junit_formatter 0.4.1
Installing rspec_junit_formatter 0.4.1
Fetching rspec-its 1.3.0
Installing rspec-its 1.3.0
Fetching rspec 3.10.0
Installing rspec 3.10.0
Fetching rspec-sorbet 1.8.0
Installing rspec-sorbet 1.8.0
Fetching spoom 1.1.4
Installing spoom 1.1.4
Fetching simplecov-cobertura 1.4.2
Installing simplecov-cobertura 1.4.2
Fetching rbi 0.0.6
Installing rbi 0.0.6
Fetching rubocop 1.22.0
Fetching http-cookie 1.0.4
Installing http-cookie 1.0.4
Installing rubocop 1.22.0
Fetching rspec-wait 0.0.9
Installing rspec-wait 0.0.9
Fetching ronn 0.7.3
Fetching tapioca 0.5.2
Installing ronn 0.7.3
Installing tapioca 0.5.2
Fetching mechanize 2.8.1
Installing mechanize 2.8.1
Fetching rubocop-performance 1.11.5
Fetching rubocop-rails 2.12.3
Fetching rubocop-rspec 2.5.0
Installing rubocop-performance 1.11.5
Installing rubocop-rspec 2.5.0
Installing rubocop-rails 2.12.3
Fetching rubocop-sorbet 0.6.2
Installing rubocop-sorbet 0.6.2
Bundle complete! 34 Gemfile dependencies, 92 gems now installed.
Bundled gems are installed into `../../../../../usr/local/Homebrew/Library/Homebrew/vendor/bundle`
Post-install message from sorbet:

  Thanks for installing Sorbet! To use it in your project, first run:

    bundle exec srb init

  which will get your project ready to use with Sorbet.
  After that whenever you want to typecheck your code, run:

    bundle exec srb tc

  For more docs see: https://sorbet.org/docs/adopting
Removing hana (1.3.7)
Removing rexml (3.2.5)
Removing mime-types-data (3.2021.0901)
Removing webrick (1.7.0)
Removing rubocop-ast (1.12.0)
Removing ruby-macho (2.5.1)
Removing tapioca (0.5.2)
Removing simplecov-cobertura (1.4.2)
Removing simplecov-html (0.12.3)
Removing docile (1.4.0)
Removing rbi (0.0.6)
Removing rspec-expectations (3.10.1)
Removing rubocop (1.22.0)
Removing concurrent-ruby (1.1.9)
Removing i18n (1.8.10)
Removing did_you_mean (1.5.0)
Removing rubocop-rails (2.12.3)
Removing mustache (1.1.1)
Removing ruby-progressbar (1.11.0)
Removing spoom (1.1.4)
Removing rspec (3.10.0)
Removing rspec-retry (0.6.2)
Removing rspec-wait (0.0.9)
Removing nokogiri-1.12.5-x86_64 (darwin)
Removing coderay (1.1.3)
Removing rspec_junit_formatter (0.4.1)
Removing webrobots (0.1.2)
Removing regexp_parser (2.1.1)
Removing highline (2.0.3)
Removing rubocop-rspec (2.5.0)
Removing elftools (1.1.3)
Removing http-cookie (1.0.4)
Removing simplecov (0.21.2)
Removing patchelf (1.3.0)
Removing mini_portile2 (2.6.1)
Removing thor (1.1.0)
Removing ronn (0.7.3)
Removing parlour (6.0.1)
Removing sorbet-runtime (0.5.9226)
Removing rspec-core (3.10.1)
Removing parser (3.0.2.0)
Removing rubocop-sorbet (0.6.2)
Removing warning (1.2.1)
Removing rainbow (3.0.0)
Removing ecma-re-validator (0.3.0)
Removing public_suffix (4.0.6)
Removing tzinfo (2.0.4)
Removing unf (0.1.4)
Removing rspec-its (1.3.0)
Removing pry (0.14.1)
Removing simplecov_json_formatter (0.1.3)
Removing racc (1.5.2)
Removing net-http-persistent (4.0.1)
Removing parallel (1.21.0)
Removing rspec-mocks (3.10.2)
Removing hpricot (0.8.6)
Removing byebug (11.1.3)
Removing plist (3.6.0)
Removing parallel_tests (3.7.3)
Removing sorbet-static-0.5.9226-universal-darwin (14)
Removing unicode-display_width (2.1.0)
Removing domain_name (0.5.20190701)
Removing diff-lcs (1.4.4)
Removing addressable (2.8.0)
Removing uri_template (0.7.0)
Removing rspec-github (2.3.1)
Removing unf_ext (0.0.8)
Removing method_source (1.0.0)
Removing sorbet (0.5.9226)
Removing activesupport (6.1.4.1)
Removing net-http-digest_auth (1.4.1)
Removing msgpack (1.4.2)
Removing json_schemer (0.2.18)
Removing rubyntlm (0.6.3)
Removing commander (4.6.0)
Removing unparser (0.6.0)
Removing colorize (0.8.1)
Removing rspec-sorbet (1.8.0)
Removing zeitwerk (2.4.2)
Removing bootsnap (1.9.1)
Removing bindata (2.4.10)
Removing rspec-support (3.10.2)
Removing minitest (5.14.4)
Removing mime-types (3.3.1)
Removing mechanize (2.8.1)
Removing connection_pool (2.2.5)
Removing rdiscount (2.2.0.2)
Removing ast (2.4.2)
Removing rack (2.2.3)
Removing sorbet-runtime-stub (0.2.0)
Removing rubocop-performance (1.11.5)
Error: cannot load such file -- minitest
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/formula_assertions.rb:11:in `require'
/usr/local/Homebrew/Library/Homebrew/formula_assertions.rb:11:in `<module:Assertions>'
/usr/local/Homebrew/Library/Homebrew/formula_assertions.rb:8:in `<module:Homebrew>'
/usr/local/Homebrew/Library/Homebrew/formula_assertions.rb:4:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/test.rb:42:in `require'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/test.rb:42:in `test'
/usr/local/Homebrew/Library/Homebrew/brew.rb:129:in `<main>'
```

**Comment by lewismc** [comment]
I just performed a `brew clean` and now I get the following
```
brew upgrade
/usr/local/Homebrew/Library/Homebrew/standalone/sorbet.rb:11:in `require': cannot load such file -- sorbet-runtime-stub (LoadError)
	from /usr/local/Homebrew/Library/Homebrew/standalone/sorbet.rb:11:in `<top (required)>'
	from /usr/local/Homebrew/Library/Homebrew/startup/sorbet.rb:9:in `require'
	from /usr/local/Homebrew/Library/Homebrew/startup/sorbet.rb:9:in `<top (required)>'
	from /usr/local/Homebrew/Library/Homebrew/startup.rb:10:in `require_relative'
	from /usr/local/Homebrew/Library/Homebrew/startup.rb:10:in `<top (required)>'
	from /usr/local/Homebrew/Library/Homebrew/global.rb:4:in `require_relative'
	from /usr/local/Homebrew/Library/Homebrew/global.rb:4:in `<top (required)>'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:29:in `require_relative'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:29:in `<main>'
```

**Comment by gromgit** [comment]
What's the output of `git -C /usr/local/Homebrew branch`?

I noticed that you're on a different branch in Homebrew core, so I'm wondering if you're also on a different branch in the Homebrew software itself. That would certainly explain why all the remedial measures taken thus far aren't working.

**Comment by lewismc** [comment]
Hi @gromgit
```bash
% git -C /usr/local/Homebrew branch
* master
  stable
  v1.0.3
  v1.0.4
```
