### ISSUE TITLE
Brew doctor throws error

### ISSUE THREAD

**Issue by Konafets** [Homebrew/brew#1244]
Running `$ brew doctor` gives the following error:

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libcdt.5.dylib
  /usr/local/lib/libcgraph.6.dylib
  /usr/local/lib/libgvc.6.dylib
  /usr/local/lib/libgvpr.2.dylib
  /usr/local/lib/libpathplan.4.dylib
  /usr/local/lib/libxdot.4.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/graphviz/arith.h
  /usr/local/include/graphviz/cdt.h
  /usr/local/include/graphviz/cgraph.h
  /usr/local/include/graphviz/color.h
  /usr/local/include/graphviz/geom.h
  /usr/local/include/graphviz/graphviz_version.h
  /usr/local/include/graphviz/gvc.h
  /usr/local/include/graphviz/gvcext.h
  /usr/local/include/graphviz/gvcjob.h
  /usr/local/include/graphviz/gvcommon.h
  /usr/local/include/graphviz/gvconfig.h
  /usr/local/include/graphviz/gvplugin.h
  /usr/local/include/graphviz/gvplugin_device.h
  /usr/local/include/graphviz/gvplugin_layout.h
  /usr/local/include/graphviz/gvplugin_loadimage.h
  /usr/local/include/graphviz/gvplugin_render.h
  /usr/local/include/graphviz/gvplugin_textlayout.h
  /usr/local/include/graphviz/gvpr.h
  /usr/local/include/graphviz/pack.h
  /usr/local/include/graphviz/pathgeom.h
  /usr/local/include/graphviz/pathplan.h
  /usr/local/include/graphviz/textspan.h
  /usr/local/include/graphviz/types.h
  /usr/local/include/graphviz/usershape.h
  /usr/local/include/graphviz/xdot.h

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
  /usr/local/lib/pkgconfig/libcdt.pc
  /usr/local/lib/pkgconfig/libcgraph.pc
  /usr/local/lib/pkgconfig/libgvc.pc
  /usr/local/lib/pkgconfig/libgvpr.pc
  /usr/local/lib/pkgconfig/libpathplan.pc
  /usr/local/lib/pkgconfig/libxdot.pc

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  binutilsfb
  dwarfutils
  graphviz
  jemallocfb
  node012
  ocaml
  php56
Error: /usr/local/Homebrew/Library/Taps/rcmdnk/homebrew-file/brew-file.rb:1: syntax error, unexpected <<
<<<<<<< 993416d995bac57048343ecae5526796fcdb485c
  ^
Please report this bug:
  https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:97:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:182:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:222:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:253:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:236:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1357:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1355:in `map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1355:in `installed'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:837:in `check_missing_deps'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:43:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

**Comment by Konafets** [comment]
Ok, solved it. Package `brew-file` was the culprit.
