### ISSUE TITLE
Can't use brew audit --new

### ISSUE THREAD

**Issue by ForesterBlox** [Homebrew/brew#12624]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.3.9-42-gd1a8199
/usr/local/Homebrew/Library/Homebrew/shims/shared/git --version
ORIGIN: https://github.com/Homebrew/brew
HEAD: d1a819986fede40cad588cd533e1d55171e2e124
Last commit: 8 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 04651e38e22d14829e66f48700e1c1053bb07296
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.nuRUgJ7uqq/org.xquartz:0
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby
CPU: quad-core 64-bit broadwell
Clang: 13.0.0 build 1300
Git: 2.30.1 => /Library/Developer/CommandLineTools/usr/bin/git
/usr/local/Homebrew/Library/Homebrew/shims/shared/curl --version
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.4-x86_64
CLT: 13.0.0.0.1.1630607135
Xcode: N/A
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9-config
  /Library/Frameworks/Python.framework/Versions/3.9/bin/python3-config

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/bash/alias.h
  /usr/local/include/bash/array.h
  /usr/local/include/bash/arrayfunc.h
  /usr/local/include/bash/assoc.h
  /usr/local/include/bash/bashansi.h
  /usr/local/include/bash/bashintl.h
  /usr/local/include/bash/bashjmp.h
  /usr/local/include/bash/bashtypes.h
  /usr/local/include/bash/builtins.h
  /usr/local/include/bash/builtins/bashgetopt.h
  /usr/local/include/bash/builtins/builtext.h
  /usr/local/include/bash/builtins/common.h
  /usr/local/include/bash/builtins/getopt.h
  /usr/local/include/bash/command.h
  /usr/local/include/bash/config-bot.h
  /usr/local/include/bash/config-top.h
  /usr/local/include/bash/config.h
  /usr/local/include/bash/conftypes.h
  /usr/local/include/bash/dispose_cmd.h
  /usr/local/include/bash/error.h
  /usr/local/include/bash/externs.h
  /usr/local/include/bash/general.h
  /usr/local/include/bash/hashlib.h
  /usr/local/include/bash/include/ansi_stdlib.h
  /usr/local/include/bash/include/chartypes.h
  /usr/local/include/bash/include/filecntl.h
  /usr/local/include/bash/include/gettext.h
  /usr/local/include/bash/include/maxpath.h
  /usr/local/include/bash/include/memalloc.h
  /usr/local/include/bash/include/ocache.h
  /usr/local/include/bash/include/posixdir.h
  /usr/local/include/bash/include/posixjmp.h
  /usr/local/include/bash/include/posixstat.h
  /usr/local/include/bash/include/posixtime.h
  /usr/local/include/bash/include/posixwait.h
  /usr/local/include/bash/include/shmbchar.h
  /usr/local/include/bash/include/shmbutil.h
  /usr/local/include/bash/include/shtty.h
  /usr/local/include/bash/include/stat-time.h
  /usr/local/include/bash/include/stdc.h
  /usr/local/include/bash/include/systimes.h
  /usr/local/include/bash/include/typemax.h
  /usr/local/include/bash/include/unionwait.h
  /usr/local/include/bash/jobs.h
  /usr/local/include/bash/make_cmd.h
  /usr/local/include/bash/pathnames.h
  /usr/local/include/bash/quit.h
  /usr/local/include/bash/shell.h
  /usr/local/include/bash/sig.h
  /usr/local/include/bash/siglist.h
  /usr/local/include/bash/signames.h
  /usr/local/include/bash/subst.h
  /usr/local/include/bash/syntax.h
  /usr/local/include/bash/unwind_prot.h
  /usr/local/include/bash/variables.h
  /usr/local/include/bash/version.h
  /usr/local/include/bash/xmalloc.h
  /usr/local/include/bash/y.tab.h
  /usr/local/include/lauxlib.h
  /usr/local/include/lua.h
  /usr/local/include/luaconf.h
  /usr/local/include/lualib.h

Warning: Unbrewed '.pc' files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected '.pc' files:
  /usr/local/lib/pkgconfig/bash.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/liblua.a

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  gtk+3
  gdk-pixbuf
  shared-mime-info
  atk
  vte3
  glib
  luarocks
  lua
  weechat
  gsettings-desktop-schemas

Warning: You have uncommitted modifications to Homebrew/homebrew-core.
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core && git stash && git clean -d -f

Uncommitted files:
  ?? .DS_Store
  ?? Formula/bottle_output.txt
  ?? Formula/brew-testing.rb
  ?? Formula/config.status
  ?? Formula/steps_output.txt
  ?? Formula/test-brew--1.0.4234234234.big_sur.bottle.tar.gz
  ?? Formula/test-brew.rb
  ?? bottle_output.txt
  ?? steps_output.txt
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I was trying to make a testing formula to print out "test" because I want to know how to make a homebrew formula.

### What happened (include all command output)?

I ran `brew audit --new brew-testing` but I got a big ruby error:

```
An error occurred while FormulaAudit/OSConditionals cop was inspecting /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/brew-testing.rb:1:0.
To see the complete backtrace run rubocop -d.
An error occurred while FormulaAudit/OSConditionals cop was inspecting /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/brew-testing.rb:1:0.
To see the complete backtrace run rubocop -d.

1 error occurred:
An error occurred while FormulaAudit/OSConditionals cop was inspecting /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/brew-testing.rb:1:0.
undefined method `metadata' for nil:NilClass
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-1.24.0/lib/rubocop/cli/command/execute_runner.rb:79:in `display_error_summary'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-1.24.0/lib/rubocop/cli/command/execute_runner.rb:58:in `display_summary'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-1.24.0/lib/rubocop/cli/command/execute_runner.rb:27:in `block in execute_runner'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-1.24.0/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-1.24.0/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-1.24.0/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-1.24.0/lib/rubocop/cli/command.rb:11:in `run'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-1.24.0/lib/rubocop/cli/environment.rb:18:in `run'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-1.24.0/lib/rubocop/cli.rb:71:in `run_command'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-1.24.0/lib/rubocop/cli.rb:78:in `execute_runners'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-1.24.0/lib/rubocop/cli.rb:47:in `run'
/usr/local/Homebrew/Library/Homebrew/utils/rubocop.rb:12:in `<main>'
Error: Failure while executing; `/usr/bin/env XDG_CACHE_HOME=/Users/chethawitdhitimanand/Library/Caches/Homebrew/style /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby /usr/local/Homebrew/Library/Homebrew/utils/rubocop.rb --format json --force-exclusion --parallel --config /usr/local/Homebrew/Library/.rubocop.yml /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/brew-testing.rb` exited with 2. Here's the output:
An error occurred while FormulaAudit/OSConditionals cop was inspecting /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/brew-testing.rb:1:0.
To see the complete backtrace run rubocop -d.
An error occurred while FormulaAudit/OSConditionals cop was inspecting /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/brew-testing.rb:1:0.
To see the complete backtrace run rubocop -d.

1 error occurred:
An error occurred while FormulaAudit/OSConditionals cop was inspecting /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/brew-testing.rb:1:0.
undefined method `metadata' for nil:NilClass
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-1.24.0/lib/rubocop/cli/command/execute_runner.rb:79:in `display_error_summary'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-1.24.0/lib/rubocop/cli/command/execute_runner.rb:58:in `display_summary'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-1.24.0/lib/rubocop/cli/command/execute_runner.rb:27:in `block in execute_runner'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-1.24.0/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-1.24.0/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-1.24.0/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-1.24.0/lib/rubocop/cli/command.rb:11:in `run'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-1.24.0/lib/rubocop/cli/environment.rb:18:in `run'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-1.24.0/lib/rubocop/cli.rb:71:in `run_command'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-1.24.0/lib/rubocop/cli.rb:78:in `execute_runners'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-1.24.0/lib/rubocop/cli.rb:47:in `run'
/usr/local/Homebrew/Library/Homebrew/utils/rubocop.rb:12:in `<main>'
{"metadata":{"rubocop_version":"1.24.0","ruby_engine":"ruby","ruby_version":"2.6.8","ruby_patchlevel":"205","ruby_platform":"x86_64-darwin14"},"files":[{"path":"/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/brew-testing.rb","offenses":[{"severity":"convention","message":"Trailing whitespace detected.","cop_name":"Layout/TrailingWhitespace","corrected":false,"correctable":true,"location":{"start_line":7,"start_column":1,"last_line":7,"last_column":2,"length":2,"line":7,"column":1}},{"severity":"convention","message":"Separate `system` commands into `\"chmod\", \"+x\", \"brew-test\"`","cop_name":"Homebrew/ShellCommands","corrected":false,"correctable":true,"location":{"start_line":24,"start_column":12,"last_line":24,"last_column":31,"length":20,"line":24,"column":12}},{"severity":"convention","message":"`test do` should not be empty","cop_name":"FormulaAudit/Test","corrected":false,"correctable":false,"location":{"start_line":28,"start_column":3,"last_line":29,"last_column":5,"length":13,"line":28,"column":3}},{"severity":"warning","message":"Empty block detected.","cop_name":"Lint/EmptyBlock","corrected":false,"correctable":false,"location":{"start_line":28,"start_column":3,"last_line":29,"last_column":5,"length":13,"line":28,"column":3}}]}],"summary":{"offense_count":4,"target_file_count":1,"inspected_file_count":1}}
```

### What did you expect to happen?

I want it to create a formula properly.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew create https://github.com/ForesterBlox/brew-testing/archive/refs/tags/v1.0.0.zip
brew audit --new brew-testing
```
```

**Comment by gromgit** [comment]
The errors seem to point to `Formula/brew-testing.rb` being b0rked. What's the output of `cat Formula/brew-testing.rb`?
