### ISSUE TITLE
Linux distro with UTF-8 characters in lsb_release breaks homebrew-bundle lockfile generation

### ISSUE THREAD

**Issue by colindean** [Homebrew/brew#12689]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.3.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 96137bc19e68398ebbb7033379df288cd8b9a3f9
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8bdba997f6c32cdd556b2ef21a619adf662f561a
Core tap last commit: 63 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: ["--appdir=/dev/null", "--fontdir=/home/colin/.fonts"]
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_DISPLAY: :0
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.8 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby
CPU: dodeca-core 64-bit zen
Clang: N/A
Git: 2.25.1 => /bin/git
Curl: 7.68.0 => /bin/curl
Kernel: Linux 5.11.0-44-generic x86_64 GNU/Linux
OS: elementary OS 6.1 Jólnir (jolnir)
Host glibc: 2.31
/usr/bin/gcc: 9.3.0
/usr/bin/ruby: 2.7.0
glibc: N/A
gcc@5: N/A
xorg: N/A
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I was trying to install a very simple Brewfile:

```
brew "docker-compose"
brew "rsstail"
```

### What happened (include all command output)?

hit an error.

```
Skipping rsstail (no bottle for Linux)
Skipping rsstail (no bottle for Linux)
Error: "\xC3" from ASCII-8BIT to UTF-8
Please report this bug:
  https://github.com/Homebrew/homebrew-bundle/issues
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/lib/ruby/2.6.0/json/common.rb:286:in `encode'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/lib/ruby/2.6.0/json/common.rb:286:in `generate'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/lib/ruby/2.6.0/json/common.rb:286:in `pretty_generate'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/locker.rb:76:in `lock'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/installer.rb:64:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/install.rb:10:in `run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/bundle.rb:94:in `bundle'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

### What did you expect to happen?

Run to completion, installing my dependencies.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
I summarized it and my debugging here: https://github.com/Homebrew/homebrew-bundle/issues/1043

The trick is running this on elementaryOS 6.1, which has an LSB description that includes an acute `o`.
```

**Comment by colindean** [comment]
I've traced it down to how Ruby handles reading the output of `lsb_release` when it gets the release version information:

https://github.com/Homebrew/brew/blob/7fc2159fcddd1deed70d2a7225d34750f080160b/Library/Homebrew/os/linux.rb#L14-L20

which calls

https://github.com/Homebrew/brew/blob/7fc2159fcddd1deed70d2a7225d34750f080160b/Library/Homebrew/utils/popen.rb#L8-L13

In Ruby 2.7 installed from distro repos:

```ruby
a = IO.popen("lsb_release -a", "r")
l = a.readlines
p l
p l.map(&:encoding)
```
outputs:
```
["Distributor ID:\tElementary\n", "Description:\telementary OS 6.1 Jólnir\n", "Release:\t6.1\n", "Codename:\tjolnir\n"]
[#<Encoding:UTF-8>, #<Encoding:UTF-8>, #<Encoding:UTF-8>, #<Encoding:UTF-8>]
```

but

```ruby
a = IO.popen("lsb_release -a", "rb")
l = a.readlines
p l
p l.map(&:encoding)
```
Outputs:
```
["Distributor ID:\tElementary\n", "Description:\telementary OS 6.1 J\xC3\xB3lnir\n", "Release:\t6.1\n", "Codename:\tjolnir\n"]
[#<Encoding:ASCII-8BIT>, #<Encoding:ASCII-8BIT>, #<Encoding:ASCII-8BIT>, #<Encoding:ASCII-8BIT>]
```

Ruby's JSON encoder tries to convert the ASCII-8BIT string to UTF-8 and fails because that's dangerous.

As I said in the linked issue on the `homebrew-bundle` repo, _a_ solution may be to force the encoding _or_ not read this particular call in binary mode (`popen(cmd, 'r')` instead of `'rb'`) when we're expecting UTF-8 data.
