### ISSUE TITLE
`brew pr-pull` unable to fetch bottles from workflow run

### ISSUE THREAD

**Issue by shivammathur** [Homebrew/brew#13127]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.4.6-31-g23cf66d
ORIGIN: https://github.com/Homebrew/brew
HEAD: 23cf66df6a198d422f139dc31f04b64b60ab1adb
Last commit: 8 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c199393579c6b73dcfb3b783c6b7ae1fde1e49e5
Core tap last commit: 12 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS: 3650
HOMEBREW_COLOR: set
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 2
HOMEBREW_NO_AUTO_UPDATE: set
Homebrew Ruby: 2.6.8 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby
CPU: dual-core 64-bit haswell
Clang: 11.0.0
Git: 2.35.1 => /bin/git
Curl: 7.68.0 => /bin/curl
Kernel: Linux 5.13.0-1021-azure x86_64 GNU/Linux
OS: Ubuntu 20.04.4 LTS (focal)
Host glibc: 2.31
/usr/bin/gcc: 9.4.0
/usr/bin/ruby: 2.7.0
glibc: N/A
gcc@5: N/A
xorg: N/A
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Fetching bottles from workflow run to upload to GitHub Packages

https://github.com/shivammathur/homebrew-php/runs/5984049807?check_suite_focus=true#step:9:41

### What happened (include all command output)?

After #13124 I'm getting this error in the `pr-pull` command.
```zsh
Error: undefined method `[]' for nil:NilClass
Do not report this issue until you've run `brew update` and tried again.
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/github.rb:315:in `block in get_workflow_run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/github.rb:314:in `select'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/github.rb:314:in `get_workflow_run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/pr-pull.rb:418:in `block (4 levels) in pr_pull'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/pr-pull.rb:417:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/pr-pull.rb:417:in `block (3 levels) in pr_pull'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/lib/ruby/2.6.0/fileutils.rb:128:in `chdir'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/lib/ruby/2.6.0/fileutils.rb:128:in `cd'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/pr-pull.rb:400:in `block (2 levels) in pr_pull'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/pr-pull.rb:399:in `block in pr_pull'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/pr-pull.rb:388:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/pr-pull.rb:388:in `pr_pull'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

### What did you expect to happen?

`brew pr-pull` to fetch the bottles from the workflow run and upload to the GitHub Package.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Please refer to this workflow:
https://github.com/shivammathur/homebrew-php/actions/runs/2152742738/workflow
```

**Comment by shivammathur** [comment]
@Bo98 Works now. Thanks for fixing it quickly
