### ISSUE TITLE
removed brew packages hijacks PATH variable in NPM or Yarn

### ISSUE THREAD

**Issue by lacostenycoder** [Homebrew/brew#13170]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.1.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 76cfe88b7628a8010bf98115627f6aced4ff8870
Last commit: 11 months ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 141aecf68fd05b252ffd64b84ef9e3937372ffff
Core tap last commit: 11 months ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_EDITOR: atom
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: dodeca-core 64-bit skylake
Clang: 10.0.0 build (parse error)
Git: 2.25.1 => /bin/git
Curl: 7.68.0 => /usr/bin/curl
Kernel: Linux 5.4.0-107-generic x86_64 GNU/Linux
OS: Linux Mint 20.1 (ulyssa)
Host glibc: 2.31
/usr/bin/gcc: 9.4.0
/usr/bin/ruby: 2.7.0
glibc: N/A
gcc@5: N/A
xorg: N/A
```

### `brew doctor` output

```shell
Unexpected header files:
  /usr/local/include/wkhtmltox/image.h
  /usr/local/include/wkhtmltox/pdf.h
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Simply trying to run `yarn install` in the root of my project.

### What happened (include all command output)?

I get an error which seems like the install is searching for a removed brew package.  I have removed `python3` from my brew installation, restarted terminals and still get this error.  It's like some ghost path from a previous installation is hanging around but I have no idea where.

```
error /home/lance/dev/qc/code/web/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments: 
Directory: /home/lance/dev/qc/code/web/node_modules/node-sass
Output:
Building: /home/lance/.nvm/versions/node/v14.19.1/bin/node /home/lance/dev/qc/code/web/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/home/lance/.nvm/versions/node/v14.19.1/bin/node',
gyp verb cli   '/home/lance/dev/qc/code/web/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.19.1 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "/home/linuxbrew/.linuxbrew/bin/python3" in the PATH
gyp verb `which` failed Error: not found: /home/linuxbrew/.linuxbrew/bin/python3
gyp verb `which` failed     at getNotFoundError (/home/lance/dev/qc/code/web/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/home/lance/dev/qc/code/web/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/home/lance/dev/qc/code/web/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /home/lance/dev/qc/code/web/node_modules/which/which.js:89:16
gyp verb `which` failed     at /home/lance/dev/qc/code/web/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /home/lance/dev/qc/code/web/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:191:21)
gyp verb `which` failed  /home/linuxbrew/.linuxbrew/bin/python3 Error: not found: /home/linuxbrew/.linuxbrew/bin/python3
gyp verb `which` failed     at getNotFoundError (/home/lance/dev/qc/code/web/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/home/lance/dev/qc/code/web/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/home/lance/dev/qc/code/web/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /home/lance/dev/qc/code/web/node_modules/which/which.js:89:16
gyp verb `which` failed     at /home/lance/dev/qc/code/web/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /home/lance/dev/qc/code/web/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:191:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "/home/linuxbrew/.linuxbrew/bin/python3", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/home/lance/dev/qc/code/web/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/home/lance/dev/qc/code/web/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/home/lance/dev/qc/code/web/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/home/lance/dev/qc/code/web/node_modules/which/which.js:80:29)
gyp ERR! stack     at /home/lance/dev/qc/code/web/node_modules/which/which.js:89:16
gyp ERR! stack     at /home/lance/dev/qc/code/web/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /home/lance/dev/qc/code/web/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:191:21)
gyp ERR! System Linux 5.4.0-107-generic
gyp ERR! command "/home/lance/.nvm/versions/node/v14.19.1/bin/node" "/home/lance/dev/qc/code/web/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/lance/dev/qc/code/web/node_modules/node-sass
gyp ERR! node -v v14.19.1
gyp ERR! node-gyp -v v3.8.0
```

No matter what I do I can't make anything forget about linuxbrew garbage.  I even commented out the `eval` to load homebrew in my `.profile` and when I try to run `npm install yarn` I get

```
gyp ERR! stack Error: Can't find Python executable "/home/linuxbrew/.linuxbrew/bin/python3", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/home/lance/dev/qc/code/web/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/home/lance/dev/qc/code/web/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/home/lance/dev/qc/code/web/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/home/lance/dev/qc/code/web/node_modules/which/which.js:80:29)
gyp ERR! stack     at /home/lance/dev/qc/code/web/node_modules/which/which.js:89:16
gyp ERR! stack     at /home/lance/dev/qc/code/web/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /home/lance/dev/qc/code/web/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:191:21)
gyp ERR! System Linux 5.4.0-107-generic
gyp ERR! command "/home/lance/.nvm/versions/node/v14.19.1/bin/node" "/home/lance/dev/qc/code/web/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/lance/dev/qc/code/web/node_modules/node-sass
gyp ERR! node -v v14.19.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
```

How to I make homebrew stop stealing python path???

### What did you expect to happen?

Install without errors.  Also not have a removed homebrew formula steal path of binaries to other package installers such as NPM or Yarn.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install python3
yarn install
```

Later, uninstall brew's python3

```
brew uninstall python3
```

Also use update-alternatives to select python2 or python3 as default python.

```
sudo update-alternatives --config python
```

Comment out `eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)` in .profile and restart terminal.

```
echo $PATH
```

it still shims `/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/`
```

**Comment by lacostenycoder** [comment]
This was not a homebrew issue.  The problem was that `node-gyp` needs NPM to set the real path to the python binary with `npm config set python /usr/bin/python2` for example.
