### ISSUE TITLE
Failed to install font-ubuntu-mono-derivative-powerline after commit b85f407e959d0420eaaaca25882335078aa70799

### ISSUE THREAD

**Issue by ckyoog** [Homebrew/brew#13359]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.4.11-171-g4054728
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 40547280302cf7add714fe765cc1f9f73b03c1fa
Last commit: 11 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: bb7727c3ab0f126740da1cc4005829f66cf6d1a6
Core tap last commit: 67 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.p3TPmd7qKr/org.xquartz:0
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit broadwell
Clang: 13.1.6 build 1316
Git: 2.32.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.4-x86_64
CLT: 13.4.0.0.1.1651278267
Xcode: 13.4
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  torrentcheck

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  libelf
  ntfs-3g
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Trying to install `font-ubuntu-mono-derivative-powerline`
```sh
HOMEBREW_NO_AUTO_UPDATE=1 brew install font-ubuntu-mono-derivative-powerline
```

### What happened (include all command output)?

The output
```sh
==> Cloning https://github.com/powerline/fonts/trunk/UbuntuMono
Updating /Users/ccgoo/Library/Caches/Homebrew/Cask/font-ubuntu-mono-derivative-powerline--svn
==> Checking out 53
Warning: No checksum defined for cask 'font-ubuntu-mono-derivative-powerline', skipping verification.
==> Installing Cask font-ubuntu-mono-derivative-powerline
==> Moving Font 'Ubuntu Mono derivative Powerline.ttf' to '/Users/ccgoo/Library/Fonts/Ubuntu Mono derivative Powerl
==> Moving Font 'Ubuntu Mono derivative Powerline Bold.ttf' to '/Users/ccgoo/Library/Fonts/Ubuntu Mono derivative P
==> Moving Font 'Ubuntu Mono derivative Powerline Bold Italic.ttf' to '/Users/ccgoo/Library/Fonts/Ubuntu Mono deriv
==> Moving Font 'Ubuntu Mono derivative Powerline Italic.ttf' to '/Users/ccgoo/Library/Fonts/Ubuntu Mono derivative
==> Backing Font 'Ubuntu Mono derivative Powerline Italic.ttf' up to '/usr/local/Caskroom/font-ubuntu-mono-derivati
==> Removing Font '/Users/ccgoo/Library/Fonts/Ubuntu Mono derivative Powerline Italic.ttf'
==> Backing Font 'Ubuntu Mono derivative Powerline Bold Italic.ttf' up to '/usr/local/Caskroom/font-ubuntu-mono-der
==> Removing Font '/Users/ccgoo/Library/Fonts/Ubuntu Mono derivative Powerline Bold Italic.ttf'
==> Backing Font 'Ubuntu Mono derivative Powerline Bold.ttf' up to '/usr/local/Caskroom/font-ubuntu-mono-derivative
==> Removing Font '/Users/ccgoo/Library/Fonts/Ubuntu Mono derivative Powerline Bold.ttf'
==> Backing Font 'Ubuntu Mono derivative Powerline.ttf' up to '/usr/local/Caskroom/font-ubuntu-mono-derivative-powe
==> Removing Font '/Users/ccgoo/Library/Fonts/Ubuntu Mono derivative Powerline.ttf'
==> Purging files for version latest of Cask font-ubuntu-mono-derivative-powerline
Error: Is a directory @ io_fread - /Users/ccgoo/Library/Caches/Homebrew/Cask/font-ubuntu-mono-derivative-powerline--svn
```
With some debug info
```sh
Error: Is a directory @ io_fread - /Users/ccgoo/Library/Caches/Homebrew/Cask/font-ubuntu-mono-derivative-powerline--svn
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/digest.rb:52:in `read'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/digest.rb:52:in `block in file'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/digest.rb:50:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/digest.rb:50:in `file'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/digest.rb:35:in `file'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:141:in `block in new_download_sha'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:141:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:141:in `new_download_sha'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:400:in `save_download_sha'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:252:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:117:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:79:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:78:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:78:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:179:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

### What did you expect to happen?

`font-ubuntu-mono-derivative-powerline` is installed successfully.

### Step-by-step reproduction instructions (by running `brew` commands)

<pre>
# Revert the commit <a href="https://github.com/Homebrew/brew/commit/b85f407e959d0420eaaaca25882335078aa70799">b85f407e959d0420eaaaca25882335078aa70799</a>

cd /usr/local/Homebrew
git checkout -b temp
git revert b85f407e959d0420eaaaca25882335078aa70799

# Install it again, this time it succeeds.

HOMEBREW_NO_AUTO_UPDATE=1 brew install font-ubuntu-mono-derivative-powerline

# The output

==> Cloning https://github.com/powerline/fonts/trunk/UbuntuMono
Updating /Users/ccgoo/Library/Caches/Homebrew/Cask/font-ubuntu-mono-derivative-powerline--svn
==> Checking out 53
Warning: No checksum defined for cask 'font-ubuntu-mono-derivative-powerline', skipping verification.
==> Installing Cask font-ubuntu-mono-derivative-powerline
==> Moving Font 'Ubuntu Mono derivative Powerline.ttf' to '/Users/ccgoo/Library/Fonts/Ubuntu Mono derivative Powerl
==> Moving Font 'Ubuntu Mono derivative Powerline Bold.ttf' to '/Users/ccgoo/Library/Fonts/Ubuntu Mono derivative P
==> Moving Font 'Ubuntu Mono derivative Powerline Bold Italic.ttf' to '/Users/ccgoo/Library/Fonts/Ubuntu Mono deriv
==> Moving Font 'Ubuntu Mono derivative Powerline Italic.ttf' to '/Users/ccgoo/Library/Fonts/Ubuntu Mono derivative
🍺  font-ubuntu-mono-derivative-powerline was successfully installed!
</pre>

Other fonts, like `font-roboto-mono-for-powerline`, also failed to get installed.

**Comment by apainintheneck** [comment]
This is a bug that I unfortunately introduced recently related to `version :latest` casks that use the Subversion download strategy. A fix is being worked on and hopefully will be available soon.
