### ISSUE TITLE
Installing fortio fails every time

### ISSUE THREAD

**Issue by lalloni** [Homebrew/brew#13372]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
❯ brew config
HOMEBREW_VERSION: 3.4.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 30e3d8883cde265cbc16ff94b49a3ac14137590e
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d2934c327a2126642f4200ec5c76789ca53df181
Core tap last commit: 26 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 13.1.6 build 1316
Git: 2.36.1 => /usr/local/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.4-x86_64
CLT: 13.4.0.0.1.1651278267
Xcode: 13.4.1


```shell
❯ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  aws-okta
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

```sh
❯ brew install fortio
==> Downloading https://ghcr.io/v2/homebrew/core/fortio/manifests/1.32.3
Already downloaded: /Users/plalloni/Library/Caches/Homebrew/downloads/964879d0d130b1d019d4fdea7b3a93d45aa69f8a3de1c02dea72d4d629bbf9aa--fortio-1.32.3.bottle_manifest.json
Error: undefined method `[]' for nil:NilClass
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:409:in `block in github_packages_manifest_resource_tab'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:408:in `each'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:408:in `find'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:408:in `github_packages_manifest_resource_tab'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:366:in `fetch_tab'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2395:in `fetch_bottle_tab'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:1180:in `fetch'
/usr/local/Homebrew/Library/Homebrew/install.rb:305:in `block in install_formulae'
/usr/local/Homebrew/Library/Homebrew/install.rb:278:in `map'
/usr/local/Homebrew/Library/Homebrew/install.rb:278:in `install_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:218:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

### What happened (include all command output)?

See above.

### What did you expect to happen?

fortio to be installed.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
See above.
```

**Comment by MikeMcQuaid** [comment]
Try to `brew fetch --force --retry fortio`.
