### ISSUE TITLE
Keg-only depends_on unaccessible from pip install

### ISSUE THREAD

**Issue by FiloSottile** [Homebrew/brew#1341]
I have a Formula (which I can't share but is really the Python boilerplate) that uses `virtualenv_install_with_resources`. One of the packages, cffi, depends on libffi, so I have `depends_on "libffi"` in there.

Something tries to run `brew` during the pip install, presumably in order to obtain the libffi import path, since it's keg only. However:

```
    sh: brew: command not found
```

The result is that the pip install doesn't find the libffi headers. The root cause is, I believe, that `brew` is not reachable from the superenv PATH:

```
PATH: /usr/local/Homebrew/Library/Homebrew/shims/super:/usr/local/opt/openssl/bin:/usr/local/opt/git/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

Secondarily, that error should stop the build, it should not go on with a corrupted import path.

Full log:

```
2016-10-21 16:54:11 +0100

/usr/local/Cellar/cfsetup/2016.9.2/libexec/bin/pip
install
-v
--no-deps
--no-binary
:all:
--ignore-installed
/private/tmp/cfsetup--cffi-20161021-44806-1k23hkg/cffi-1.8.3

Processing /private/tmp/cfsetup--cffi-20161021-44806-1k23hkg/cffi-1.8.3
  Running setup.py (path:/tmp/pip-eQvaYF-build/setup.py) egg_info for package from file:///private/tmp/cfsetup--cffi-20161021-44806-1k23hkg/cffi-1.8.3
    Running command python setup.py egg_info
    sh: brew: command not found
    running egg_info
    creating pip-egg-info/cffi.egg-info
    writing requirements to pip-egg-info/cffi.egg-info/requires.txt
    writing pip-egg-info/cffi.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/cffi.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/cffi.egg-info/dependency_links.txt
    writing entry points to pip-egg-info/cffi.egg-info/entry_points.txt
    writing manifest file 'pip-egg-info/cffi.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'pip-egg-info/cffi.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pip-egg-info/cffi.egg-info/SOURCES.txt'
  Source in /tmp/pip-eQvaYF-build has version 1.8.3, which satisfies requirement cffi==1.8.3 from file:///private/tmp/cfsetup--cffi-20161021-44806-1k23hkg/cffi-1.8.3
Skipping bdist_wheel for cffi, due to binaries being disabled for it.
Installing collected packages: cffi
  Running setup.py install for cffi: started
    Running command /usr/local/Cellar/cfsetup/2016.9.2/libexec/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-eQvaYF-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-JqoXZ6-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/cfsetup/2016.9.2/libexec/include/site/python2.7/cffi
    sh: brew: command not found
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.12-intel-2.7
    creating build/lib.macosx-10.12-intel-2.7/cffi
    copying cffi/__init__.py -> build/lib.macosx-10.12-intel-2.7/cffi
    copying cffi/api.py -> build/lib.macosx-10.12-intel-2.7/cffi
    copying cffi/backend_ctypes.py -> build/lib.macosx-10.12-intel-2.7/cffi
    copying cffi/cffi_opcode.py -> build/lib.macosx-10.12-intel-2.7/cffi
    copying cffi/commontypes.py -> build/lib.macosx-10.12-intel-2.7/cffi
    copying cffi/cparser.py -> build/lib.macosx-10.12-intel-2.7/cffi
    copying cffi/ffiplatform.py -> build/lib.macosx-10.12-intel-2.7/cffi
    copying cffi/lock.py -> build/lib.macosx-10.12-intel-2.7/cffi
    copying cffi/model.py -> build/lib.macosx-10.12-intel-2.7/cffi
    copying cffi/recompiler.py -> build/lib.macosx-10.12-intel-2.7/cffi
    copying cffi/setuptools_ext.py -> build/lib.macosx-10.12-intel-2.7/cffi
    copying cffi/vengine_cpy.py -> build/lib.macosx-10.12-intel-2.7/cffi
    copying cffi/vengine_gen.py -> build/lib.macosx-10.12-intel-2.7/cffi
    copying cffi/verifier.py -> build/lib.macosx-10.12-intel-2.7/cffi
    copying cffi/_cffi_include.h -> build/lib.macosx-10.12-intel-2.7/cffi
    copying cffi/parse_c_type.h -> build/lib.macosx-10.12-intel-2.7/cffi
    copying cffi/_embedding.h -> build/lib.macosx-10.12-intel-2.7/cffi
    running build_ext
    building '_cffi_backend' extension
    creating build/temp.macosx-10.12-intel-2.7
    creating build/temp.macosx-10.12-intel-2.7/c
    clang -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -DUSE__THREAD -I/usr/include/ffi -I/usr/include/libffi -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c c/_cffi_backend.c -o build/temp.macosx-10.12-intel-2.7/c/_cffi_backend.o
    c/_cffi_backend.c:15:10: fatal error: 'ffi.h' file not found
    #include <ffi.h>
             ^
    1 error generated.
    error: command 'clang' failed with exit status 1
    Running setup.py install for cffi: finished with status 'error'
Cleaning up...
  Removing source in /tmp/pip-eQvaYF-build
Command "/usr/local/Cellar/cfsetup/2016.9.2/libexec/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-eQvaYF-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-JqoXZ6-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/cfsetup/2016.9.2/libexec/include/site/python2.7/cffi" failed with error code 1 in /tmp/pip-eQvaYF-build/
Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/cfsetup/2016.9.2/libexec/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/Cellar/cfsetup/2016.9.2/libexec/lib/python2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/usr/local/Cellar/cfsetup/2016.9.2/libexec/lib/python2.7/site-packages/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/usr/local/Cellar/cfsetup/2016.9.2/libexec/lib/python2.7/site-packages/pip/req/req_install.py", line 880, in install
    spinner=spinner,
  File "/usr/local/Cellar/cfsetup/2016.9.2/libexec/lib/python2.7/site-packages/pip/utils/__init__.py", line 718, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "/usr/local/Cellar/cfsetup/2016.9.2/libexec/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-eQvaYF-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-JqoXZ6-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/cfsetup/2016.9.2/libexec/include/site/python2.7/cffi" failed with error code 1 in /tmp/pip-eQvaYF-build/

HOMEBREW_VERSION: 1.0.8
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 0296439c832a915be9b73456c0c26bc6c79c271d
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 680491b0117e69c197be1c6756954280a08bc92c
Core tap last commit: 79 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
GCC-4.2: build 0
Clang: 8.0 build 800
Git: 2.10.1 => /usr/local/opt/git/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_60
macOS: 10.12-x86_64
Xcode: 8.0
CLT: N/A
X11: N/A

HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local/opt/openssl:/usr/local/opt/libffi:/usr/local
CMAKE_INCLUDE_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/libxml2:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/apache2:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
CMAKE_FRAMEWORK_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks
MACOSX_DEPLOYMENT_TARGET: 10.12
PKG_CONFIG_PATH: /usr/local/opt/openssl/lib/pkgconfig:/usr/local/opt/libffi/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.12
HOMEBREW_SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/super:/usr/local/opt/openssl/bin:/usr/local/opt/git/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by MikeMcQuaid** [comment]
> The result is that the pip install doesn't find the libffi headers. The root cause is, I believe, that brew is not reachable from the superenv PATH

This is intentional.

> Secondarily, that error should stop the build, it should not go on with a corrupted import path.

Does `pip install` return a non-zero exit code in that case that we ignore?

**Comment by FiloSottile** [comment]
> This is intentional.

Umh, then the bug is the fact that brew is used at all? There should really be a way to access the Keg-only dependency from the pip install context.

> Does pip install return a non-zero exit code in that case that we ignore?

What I think is happening is something like `-I$(brew ...)`, and string interpolation errors are not fatal by default, so the broken build just proceeds.

**Comment by MikeMcQuaid** [comment]
> Umh, then the bug is the fact that brew is used at all?

Yes.

> There should really be a way to access the Keg-only dependency from the pip install context.

There is: specify it as `depends_on` and it'll be added to the `PATH`.

> What I think is happening is something like -I$(brew ...), and string interpolation errors are not fatal by default, so the broken build just proceeds.

Ok. That's a bug in their buildsystem rather than ours. Sorry we can't be more help.

**Comment by FiloSottile** [comment]
@MikeMcQuaid I don't think we are communicating well here :)

> There is: specify it as depends_on and it'll be added to the PATH.

I'm doing that:

> One of the packages, cffi, depends on libffi, so I have depends_on "libffi" in there.

I am very skeptical that the stock `cffi` pip package has the string `brew` anywhere in its buildsystem, so I don't think the bug is on their side.

This is all I'm doing:

```ruby
depends_on "libffi"

resource "cffi" do
  url "https://files.pythonhosted.org/packages/0a/f3/686af8873b70028fccf67b15c78fd4e4667a3da995007afc71e786d61b0a/cffi-1.8.3.tar.gz"
  sha256 "c321bd46faa7847261b89c0469569530cad5a41976bb6dba8202c0159f476568"
end

include Language::Python::Virtualenv

def install
    virtualenv_install_with_resources
end
```

It's not working. Am I doing something wrong, or is there a bug in brew?

**Comment by MikeMcQuaid** [comment]
> I am very skeptical that the stock cffi pip package has the string brew anywhere in its buildsystem

Can you verify that? Thanks.

**Comment by FiloSottile** [comment]
Well, nevermind me. You are right, they are insane.

https://bitbucket.org/cffi/cffi/src/94dc0b8274eec048fe013e0a7e151c13f371805f/setup.py?at=default&fileviewer=file-view-default#setup.py-78
