### ISSUE TITLE
/core_ext/kernel_require.rb:55:in `require': cannot load such file -- mach (LoadError)

### ISSUE THREAD

**Issue by Sajaki** [Homebrew/brew#1344]
### Bug reports:

when i run brew doctor or brew update, i get an error : 

```
Nomad:~ nix$ brew doctor
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- mach (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/Homebrew/extend/pathname.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/Homebrew/global.rb:3:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/brew.rb:15:in `<main>'
```
System details : 
```
nomad:~ nix$ SW_VERS
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G1004
```

**Comment by MikeMcQuaid** [comment]
Try `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

**Comment by Sajaki** [comment]
now i get

```
Nomad:~ nix$ cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- mach (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/Homebrew/extend/pathname.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/Homebrew/global.rb:3:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/brew.rb:15:in `<main>'
fatal: Not a git repository (or any of the parent directories): .git

```

**Comment by MikeMcQuaid** [comment]
Uninstall and reinstall Homebrew from https://github.com/homebrew/install.

**Comment by Sajaki** [comment]
thanks, it's fixed now.

**Comment by krongk** [comment]
thanks, fixed it now.

**Comment by radh82** [comment]
Thanks @MikeMcQuaid Unistalled and reinstalled Brew working fine.
