### ISSUE TITLE
ruby not found even though installed

### ISSUE THREAD

**Issue by xrisk** [Homebrew/brew#13559]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.5.4-74-g8dc46a7-dirty
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8dc46a7c477929185cba8ca0de5f9c843b3e9385
Last commit: 11 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6cc609694248185bf05737c2e8860b79a6040cb4
Core tap last commit: 12 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /home/xrisk/homebrew
HOMEBREW_REPOSITORY: /home/xrisk/homebrew
HOMEBREW_CELLAR: /home/xrisk/homebrew/Cellar
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.8 => /home/xrisk/.rbenv/versions/2.6.8/bin/ruby
CPU: quad-core 64-bit arm
Clang: N/A
Git: 2.34.1 => /bin/git
Curl: 7.81.0 => /bin/curl
Kernel: Linux 5.15.0-41-generic aarch64 GNU/Linux
OS: Ubuntu 22.04 LTS (jammy)
Host glibc: 2.35
/usr/bin/gcc: 11.2.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@5: N/A
xorg: N/A
```

### `brew doctor` output

```shell
Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /home/xrisk/.pyenv/shims/python3-config
  /home/xrisk/.pyenv/shims/python3.10-config
  /home/xrisk/.pyenv/shims/python-config

Warning: You have uncommitted modifications to Homebrew/brew.
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /home/xrisk/homebrew && git stash && git clean -d -f

Uncommitted files:
   M Library/Homebrew/utils/ruby.sh
   M Library/Homebrew/utils/ruby_check_version_script.rb

Warning: Your Homebrew's prefix is not /home/linuxbrew/.linuxbrew.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/home/linuxbrew/.linuxbrew).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
unsupported configuration.


Warning: Your CPU architecture (arm64) is not supported. We only support
x86_64 CPU architectures. You will be unable to use binary packages (bottles).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
unsupported configuration.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Use homebrew commands

### What happened (include all command output)?

Typing any brew command gives:

```
+ echo 'Failed to install Homebrew Portable Ruby and cannot find another Ruby 2.6.8!
If there'\''s no Homebrew Portable Ruby available for your processor:
- install Ruby 2.6.8 with your system package manager (or rbenv/ruby-build)
- make it first in your PATH
- try again
'
Failed to install Homebrew Portable Ruby and cannot find another Ruby 2.6.8!
If there's no Homebrew Portable Ruby available for your processor:
- install Ruby 2.6.8 with your system package manager (or rbenv/ruby-build)
- make it first in your PATH
- try again
```

```
xrisk@rishav-ubuntu:~/tmp$ ruby --version
ruby 2.6.8p205 (2021-07-07 revision 67951) [aarch64-linux]
```

Through tracing the script execution, I find that the call to the version detection script is: `/home/xrisk/.rbenv/shims/ruby --enable-frozen-string-literal --disable=gems,did_you_mean,rubyopt /home/xrisk/tmp/homebrew/Library/Homebrew/utils/ruby_check_version_script.rb 2.6.8`

Manually running this command gives

```
/home/xrisk/tmp/homebrew/Library/Homebrew/utils/ruby_check_version_script.rb:22:in `<main>': undefined method `present?' for nil:NilClass (NoMethodError)
```

from these lines: https://github.com/Homebrew/brew/blob/8dc46a7c477929185cba8ca0de5f9c843b3e9385/Library/Homebrew/utils/ruby_check_version_script.rb#L20-L21

I am assuming that .present? is only available on Homebrew’s ENV and not the native Ruby version. Please correct me if I’m wrong.

### What did you expect to happen?

Homebrew to use the Ruby on the path.

### Step-by-step reproduction instructions (by running `brew` commands)

```
xrisk@rishav-ubuntu:~/tmp$ git clone https://github.com/Homebrew/brew homebrew
Cloning into 'homebrew'...
remote: Enumerating objects: 211920, done.
remote: Counting objects: 100% (108/108), done.
remote: Compressing objects: 100% (60/60), done.
remote: Total 211920 (delta 53), reused 83 (delta 36), pack-reused 211812
Receiving objects: 100% (211920/211920), 58.67 MiB | 2.80 MiB/s, done.
Resolving deltas: 100% (155938/155938), done.
xrisk@rishav-ubuntu:~/tmp$ eval "$(homebrew/bin/brew shellenv)"
xrisk@rishav-ubuntu:~/tmp$ brew update --force
==> Homebrew has enabled anonymous aggregate formula and cask analytics.
Read the analytics documentation (and how to opt-out) here:
  https://docs.brew.sh/Analytics
No analytics have been recorded yet (nor will be during this `brew` run).

==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations
==> Tapping homebrew/core
Cloning into '/home/xrisk/tmp/homebrew/Library/Taps/homebrew/homebrew-core'...
remote: Enumerating objects: 1228550, done.
remote: Counting objects: 100% (69/69), done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 1228550 (delta 39), reused 59 (delta 32), pack-reused 1228481
Receiving objects: 100% (1228550/1228550), 493.48 MiB | 3.04 MiB/s, done.
Resolving deltas: 100% (847866/847866), done.
Tapped 3 commands and 6188 formulae (6,530 files, 541.2MB).
Already up-to-date.
xrisk@rishav-ubuntu:~/tmp$ brew
Example usage:
  brew search TEXT|/REGEX/
  brew info [FORMULA|CASK...]
  brew install FORMULA|CASK...
  brew update
  brew upgrade [FORMULA|CASK...]
  brew uninstall FORMULA|CASK...
  brew list [FORMULA|CASK...]

Troubleshooting:
  brew config
  brew doctor
  brew install --verbose --debug FORMULA|CASK

Contributing:
  brew create URL [--no-fetch]
  brew edit [FORMULA|CASK...]

Further help:
  brew commands
  brew help [COMMAND]
  man brew
  https://docs.brew.sh
xrisk@rishav-ubuntu:~/tmp$ brew developer on 
xrisk@rishav-ubuntu:~/tmp$ brew
Example usage:
  brew search TEXT|/REGEX/
  brew info [FORMULA|CASK...]
  brew install FORMULA|CASK...
  brew update
  brew upgrade [FORMULA|CASK...]
  brew uninstall FORMULA|CASK...
  brew list [FORMULA|CASK...]

Troubleshooting:
  brew config
  brew doctor
  brew install --verbose --debug FORMULA|CASK

Contributing:
  brew create URL [--no-fetch]
  brew edit [FORMULA|CASK...]

Further help:
  brew commands
  brew help [COMMAND]
  man brew
  https://docs.brew.sh
xrisk@rishav-ubuntu:~/tmp$ brew update
Already up-to-date.
xrisk@rishav-ubuntu:~/tmp$ brew
Error: No Homebrew ruby 2.6.8_1 available for aarch64 processors!
Error: Failed to install Homebrew Portable Ruby and cannot find another Ruby 2.6.8!
If there's no Homebrew Portable Ruby available for your processor:
- install Ruby 2.6.8 with your system package manager (or rbenv/ruby-build)
- make it first in your PATH
- try again

```

**Comment by xrisk** [comment]
Will reopen with concrete repo…

**Comment by xrisk** [comment]
```
xrisk@rishav-ubuntu:~$ brew config
Error: No Homebrew ruby 2.6.8_1 available for aarch64 processors!
Error: Failed to install Homebrew Portable Ruby and cannot find another Ruby 2.6.8!
If there's no Homebrew Portable Ruby available for your processor:
- install Ruby 2.6.8 with your system package manager (or rbenv/ruby-build)
- make it first in your PATH
- try again

xrisk@rishav-ubuntu:~$ ruby --version
ruby 2.6.8p205 (2021-07-07 revision 67951) [aarch64-linux]
xrisk@rishav-ubuntu:~$ echo $PATH
/home/xrisk/homebrew/bin:/home/xrisk/homebrew/sbin:/home/xrisk/.rbenv/shims:/home/xrisk/.rbenv/bin:/home/xrisk/.pyenv/shims:/home/xrisk/.local/share/nvm/v16.16.0/bin:/home/xrisk/.pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
xrisk@rishav-ubuntu:~$ which ruby
/home/xrisk/.rbenv/shims/ruby

```

**Comment by carlocab** [comment]
`#present?` is a Rails extension. https://apidock.com/rails/Object/present%3F

> The reason I have been able to repro it intermittently  is because this commit has not been released. On turning on developer mode, the incorrect codepath is executed...

Which commit are you referring to?

**Comment by xrisk** [comment]
@carlocab This is the stack trace I’m getting:

```
/home/xrisk/tmp/homebrew/Library/Homebrew/utils/ruby_check_version_script.rb:22:in `<main>': undefined method `present?' for nil:NilClass (NoMethodError)
```

(please look at the reproducer)

> Which commit are you referring to?

I meant that this commit `https://github.com/Homebrew/brew/commit/93ed7646b0b40ebe40ffda6b54af19e5d6eda25d` is not on the release branch, which is why I was having difficulty reproducing it.

As for it being a Rails extension, I don’t understand how 

```
/home/xrisk/.rbenv/shims/ruby --enable-frozen-string-literal --disable=gems,did_you_mean,rubyopt /home/xrisk/tmp/homebrew/Library/Homebrew/utils/ruby_check_version_script.rb 2.6.8
```

loads Rails? I don’t see any imports

**Comment by carlocab** [comment]
Yea, we probably shouldn't be relying on methods provided by Rails here.

Does this work?

```diff
diff --git a/Library/Homebrew/utils/ruby_check_version_script.rb b/Library/Homebrew/utils/ruby_check_version_script.rb
index e06ee69c5..6a46cb407 100755
--- a/Library/Homebrew/utils/ruby_check_version_script.rb
+++ b/Library/Homebrew/utils/ruby_check_version_script.rb
@@ -17,8 +17,8 @@ ruby_version_major, ruby_version_minor, = ruby_version.canonical_segments
 homebrew_required_ruby_version_major, homebrew_required_ruby_version_minor, =
   homebrew_required_ruby_version.canonical_segments
 
-if ENV["HOMEBREW_DEVELOPER"].present? &&
-   ENV["HOMEBREW_USE_RUBY_FROM_PATH"].present? &&
+if ENV.fetch("HOMEBREW_DEVELOPER") &&
+   ENV.fetch("HOMEBREW_USE_RUBY_FROM_PATH") &&
    ruby_version >= homebrew_required_ruby_version
   return
 elsif ruby_version_major != homebrew_required_ruby_version_major ||
```

**Comment by xrisk** [comment]
No

```
/home/xrisk/homebrew/Library/Homebrew/utils/ruby_check_version_script.rb:20:in `fetch': key not found: "HOMEBREW_DEVELOPER" (KeyError)
	from /home/xrisk/homebrew/Library/Homebrew/utils/ruby_check_version_script.rb:20:in `<main>’
```

```
ENV[“HOMEBREW_DEVELOPER”] works (returns `nil`).
