### ISSUE TITLE
It's just broken... Can't run `brew upgrade` `brew install` etc.

### ISSUE THREAD

**Issue by sinnrrr** [Homebrew/brew#13567]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.5.4-91-g5400254-dirty
ORIGIN: https://github.com/Homebrew/brew
HEAD: 5400254946b7e4bb68f45d2519f156e2d2529946
Last commit: 9 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: bedc1492d26b3872167262459f16c87256d82926
Core tap last commit: 4 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BROWSER: open-browser
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: lvim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.37.1 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.4-arm64
CLT: 13.4.0.0.1.1651278267
Xcode: N/A
Rosetta 2: false
```

### `brew doctor` output

```shell
Error: cannot load such file -- warning
/opt/homebrew/Library/Homebrew/warnings.rb:4:in `require'
/opt/homebrew/Library/Homebrew/warnings.rb:4:in `<top (required)>'
/opt/homebrew/Library/Homebrew/ignorable.rb:4:in `require'
/opt/homebrew/Library/Homebrew/ignorable.rb:4:in `<top (required)>'
/opt/homebrew/Library/Homebrew/formulary.rb:80:in `require'
/opt/homebrew/Library/Homebrew/formulary.rb:80:in `load_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:122:in `load_formula_from_path'
/opt/homebrew/Library/Homebrew/formulary.rb:309:in `load_file'
/opt/homebrew/Library/Homebrew/formulary.rb:466:in `load_file'
/opt/homebrew/Library/Homebrew/formulary.rb:299:in `klass'
/opt/homebrew/Library/Homebrew/formulary.rb:294:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:456:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:540:in `factory'
/opt/homebrew/Library/Homebrew/formulary.rb:588:in `from_keg'
/opt/homebrew/Library/Homebrew/formulary.rb:561:in `from_rack'
/opt/homebrew/Library/Homebrew/formula.rb:1703:in `block in installed'
/opt/homebrew/Library/Homebrew/formula.rb:1702:in `each'
/opt/homebrew/Library/Homebrew/formula.rb:1702:in `flat_map'
/opt/homebrew/Library/Homebrew/formula.rb:1702:in `installed'
/opt/homebrew/Library/Homebrew/diagnostic.rb:700:in `check_deprecated_disabled'
/opt/homebrew/Library/Homebrew/cmd/doctor.rb:64:in `block in doctor'
/opt/homebrew/Library/Homebrew/cmd/doctor.rb:57:in `each'
/opt/homebrew/Library/Homebrew/cmd/doctor.rb:57:in `doctor'
/opt/homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Install a package
```
❯ brew install fnm

Error: cannot load such file -- warning
/opt/homebrew/Library/Homebrew/warnings.rb:4:in `require'
/opt/homebrew/Library/Homebrew/warnings.rb:4:in `<top (required)>'
/opt/homebrew/Library/Homebrew/ignorable.rb:4:in `require'
/opt/homebrew/Library/Homebrew/ignorable.rb:4:in `<top (required)>'
/opt/homebrew/Library/Homebrew/formulary.rb:80:in `require'
/opt/homebrew/Library/Homebrew/formulary.rb:80:in `load_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:122:in `load_formula_from_path'
/opt/homebrew/Library/Homebrew/formulary.rb:309:in `load_file'
/opt/homebrew/Library/Homebrew/formulary.rb:299:in `klass'
/opt/homebrew/Library/Homebrew/formulary.rb:294:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:540:in `factory'
/opt/homebrew/Library/Homebrew/cli/parser.rb:626:in `block in formulae'
/opt/homebrew/Library/Homebrew/cli/parser.rb:622:in `map'
/opt/homebrew/Library/Homebrew/cli/parser.rb:622:in `formulae'
/opt/homebrew/Library/Homebrew/cli/parser.rb:307:in `parse'
/opt/homebrew/Library/Homebrew/cmd/install.rb:141:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

### What happened (include all command output)?

I just did a `Control-C` and that caused this issue. Even after the reboot, it stays the same.

### What did you expect to happen?

I expect it to work...

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
IDK how to reproduce this...
```

**Comment by carlocab** [comment]
Try doing
```
brew update-reset
```
but note this will destroy any local modifications you've made to your Homebrew installation.

Since this appears to be particular to your machine rather than a bug in Homebrew, I'm closing this. Please post in the Homebrew Discussions page if you're looking for more help to resolve this.
