### ISSUE TITLE
Reference to `brew.rb` in `ChangeLog` makes bottle non-relocatable

### ISSUE THREAD

**Issue by paperchalice** [Homebrew/brew#13571]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.5.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: f041a59af9daddc7c7afe8537e3858103f8f9ab9
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7bdba2d4245bbc2f3970544ee08362bd12ebaaa5
Core tap last commit: 82 minutes ago
Core tap branch: xserver
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.OULOWudGZq/homebrew.mxcl:0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 13.1.6 build 1316
Git: 2.37.0 => /usr/local/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.4-x86_64
CLT: 13.4.0.0.1.1651278267
Xcode: N/A
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some taps are not on the default git origin branch and may not receive
updates. If this is a surprise to you, check out the default branch with:
  git -C $(brew --repo homebrew/core) checkout master
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Bottle formula `xorg-server`, see https://github.com/Homebrew/homebrew-core/pull/101019

### What happened (include all command output)?

These lines from `ChangeLog` of `xorg-server` makes bottle non-relocatable
```
commit 5893e72a20ffa5cfcd6d0c7c5c934b92546d76c3
Author: Jon Turney <jon.turney@dronecode.org.uk>
Date:   Tue Oct 24 12:07:08 2017 +0100

    travis: Fix OSX build
    
    Turn off homebrew autoupdating before installing ccache, to avoid:
    
    /usr/local/Homebrew/Library/Homebrew/brew.rb:12:in `<main>': Homebrew must
    be run under Ruby 2.3! You're running 2.0.0. (RuntimeError)
    
    Signed-off-by: Jon Turney <jon.turney@dronecode.org.uk>
    Reviewed-by: Adam Jackson <ajax@redhat.com>
```

`brew` report bottle is non-relocatable:
```
==> Determining xorg-server bottle rebuild...
==> Bottling xorg-server--21.1.4.monterey.bottle.tar.gz...
tar --create --numeric-owner --file /Users/***/xorg-server--21.1.4.monterey.bottle.tar xorg-server/21.1.4
==> Detecting if xorg-server--21.1.4.monterey.bottle.tar.gz is relocatable...
Warning: String '/usr/local/Homebrew' still exists in these files:
/usr/local/Cellar/xorg-server/21.1.4/ChangeLog
 --> match '/usr/local/Homebrew/Library/Homebrew/brew.rb:12:in `<main>': Homebrew must' at offset 0xe44e3
Error: Bottle contains non-relocatable reference to /usr/local/Homebrew!
```

### What did you expect to happen?

`brew bottle xorg-server` return 0

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew install --build-bottle xorg-server`
`brew bottle xorg-server`
See https://github.com/Homebrew/homebrew-core/pull/101019
```

**Comment by MikeMcQuaid** [comment]
The workaround is to delete or modify the changelog file in the relevant formula.
