### ISSUE TITLE
Checking for duplicate pull requests fails

### ISSUE THREAD

**Issue by p-linnane** [Homebrew/brew#13634]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.5.7-11-g8a153de
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8a153de2bc6a335080d877c0eb14d71e2ff8c537
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2ee62b49a9f0a3026ae0966f5c282e06d3436a24
Core tap last commit: 57 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_FORCE_BREWED_CA_CERTIFICATES: set
HOMEBREW_FORCE_BREWED_CURL: set
HOMEBREW_FORCE_BREWED_GIT: set
HOMEBREW_FORCE_VENDOR_RUBY: set
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.37.1 => /opt/homebrew/opt/git/bin/git
Curl: 7.84.0 => /opt/homebrew/opt/curl/bin/curl
macOS: 12.5-arm64
CLT: 13.4.0.0.1.1651278267
Xcode: 13.4.1
Rosetta 2: false
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Update a cask that was outdated according to `livecheck`.

### What happened (include all command output)?

```
brew bump-cask-pr --debug --version=1.2.4 zprint
/opt/homebrew/Library/Homebrew/shims/shared/git --version
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.5.7-11-g8a153de\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.5\)\ curl/7.79.1 --header Accept-Language:\ en --retry 3 --location https://api.github.com/search/issues\?q=zprint\+repo\%3AHomebrew\%2Fhomebrew-cask\+state\%3Aopen\+in\%3Atitle\&per_page=100 --header Accept:\ application/vnd.github\+json --write-out '
'\%\{http_code\} --header Authorization:\ token\ ****** --dump-header /private/tmp/github_api_headers20220802-53160-14fwigd
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.5.7-11-g8a153de\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.5\)\ curl/7.79.1 --header Accept-Language:\ en --retry 3 --location https://api.github.com/repos/zprint/Homebrew/homebrew-cask/pulls/129070/files --header Accept:\ application/vnd.github\+json --write-out '
'\%\{http_code\} --header Authorization:\ token\ ****** --dump-header /private/tmp/github_api_headers20220802-53160-emb4pg
Error: Not Found
/opt/homebrew/Library/Homebrew/utils/github/api.rb:300:in `raise_error'
/opt/homebrew/Library/Homebrew/utils/github/api.rb:233:in `open_rest'
/opt/homebrew/Library/Homebrew/utils/github.rb:506:in `get_pull_request_changed_files'
/opt/homebrew/Library/Homebrew/utils/github.rb:482:in `block in check_for_duplicate_pull_requests'
/opt/homebrew/Library/Homebrew/utils/github.rb:481:in `select'
/opt/homebrew/Library/Homebrew/utils/github.rb:481:in `check_for_duplicate_pull_requests'
/opt/homebrew/Library/Homebrew/dev-cmd/bump-cask-pr.rb:211:in `check_open_pull_requests'
/opt/homebrew/Library/Homebrew/dev-cmd/bump-cask-pr.rb:94:in `bump_cask_pr'
/opt/homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

### What did you expect to happen?

Receive the usual error message about duplicate pull requests:
```
brew bump-cask-pr --version=1.2.4 zprint
Error: These pull requests may be duplicates:
Update zprint from 1.2.3 to 1.2.4 https://github.com/Homebrew/homebrew-cask/pull/129070
Duplicate PRs should not be opened. Use --force to override this error.
```

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew bump-cask-pr --version=1.2.4 zprint
```

**Comment by p-linnane** [comment]
This was introduced with the changes to `github.rb` in #13512. I reverted the changes locally and behavior is back to what is expected.

**Comment by MikeMcQuaid** [comment]
@iMichka can you take a look at this? Thanks!

**Comment by iMichka** [comment]
I was working a pull request to fix it. Here it is #13638. Sorry for the bugs.
Can't test the PR right now, as we need a duplicate pull request to test on.
