### ISSUE TITLE
brew audit --new-cask fails to audit casks with uninstall stanza while checking signing with undefined method `source' for #<Cask::Artifact::Uninstall:0x00007fa1e13c18f8>

### ISSUE THREAD

**Issue by aaronliu0130** [Homebrew/brew#13710]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.5.9-117-g6f196ad
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6f196ad9ba2d52b6bbecca8e65643886a8e228db
Last commit: 12 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 21a1ba14255e9039e71bacb4c1585b687ff2a6ea
Core tap last commit: 11 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_AUTO_UPDATE_SECS: 3600
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nano
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: quad-core 64-bit haswell
Clang: 12.0.0 build 1200
Git: 2.37.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.0.0.32.29
Xcode: N/A
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  python@2
  arm-gcc-bin

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /opt/devkitpro/tools/bin/pkg-config
  /opt/devkitpro/tools/bin/x86_64-apple-darwin15-pkg-config
  /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7-config
  /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7m-config
  /Library/Frameworks/Python.framework/Versions/3.7/bin/python3-config
  /Library/Frameworks/Python.framework/Versions/3.7/bin/pylint-config

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libndi.3.dylib
  /usr/local/lib/libwx_baseu-3.1.2.0.0.dylib
  /usr/local/lib/libwx_baseu_net-3.1.2.0.0.dylib
  /usr/local/lib/libwx_osx_cocoau_aui-3.1.2.0.0.dylib
  /usr/local/lib/libwx_osx_cocoau_core-3.1.2.0.0.dylib
  /usr/local/lib/libwx_osx_cocoau_gl-3.1.2.0.0.dylib
  /usr/local/lib/libwx_osx_cocoau_qa-3.1.2.0.0.dylib
  /usr/local/lib/libwx_osx_cocoau_ribbon-3.1.2.0.0.dylib
  /usr/local/lib/libwx_osx_cocoau_stc-3.1.2.0.0.dylib
  /usr/local/lib/libwx_osx_cocoau_webview-3.1.2.0.0.dylib
  /usr/local/lib/libwx_osx_cocoau_xrc-3.1.2.0.0.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/python2.7/pygame/_camera.h
  /usr/local/include/python2.7/pygame/_pygame.h
  /usr/local/include/python2.7/pygame/_surface.h
  /usr/local/include/python2.7/pygame/camera.h
  /usr/local/include/python2.7/pygame/fastevents.h
  /usr/local/include/python2.7/pygame/font.h
  /usr/local/include/python2.7/pygame/freetype.h
  /usr/local/include/python2.7/pygame/include/_pygame.h
  /usr/local/include/python2.7/pygame/include/bitmask.h
  /usr/local/include/python2.7/pygame/include/pgcompat.h
  /usr/local/include/python2.7/pygame/include/pgimport.h
  /usr/local/include/python2.7/pygame/include/pgplatform.h
  /usr/local/include/python2.7/pygame/include/pygame.h
  /usr/local/include/python2.7/pygame/include/pygame_bufferproxy.h
  /usr/local/include/python2.7/pygame/include/pygame_font.h
  /usr/local/include/python2.7/pygame/include/pygame_freetype.h
  /usr/local/include/python2.7/pygame/include/pygame_mask.h
  /usr/local/include/python2.7/pygame/include/pygame_mixer.h
  /usr/local/include/python2.7/pygame/include/sse2neon.h
  /usr/local/include/python2.7/pygame/mask.h
  /usr/local/include/python2.7/pygame/mixer.h
  /usr/local/include/python2.7/pygame/palette.h
  /usr/local/include/python2.7/pygame/pgarrinter.h
  /usr/local/include/python2.7/pygame/pgbufferproxy.h
  /usr/local/include/python2.7/pygame/pgcompat.h
  /usr/local/include/python2.7/pygame/pgimport.h
  /usr/local/include/python2.7/pygame/pgopengl.h
  /usr/local/include/python2.7/pygame/pgplatform.h
  /usr/local/include/python2.7/pygame/pygame.h
  /usr/local/include/python2.7/pygame/scrap.h
  /usr/local/include/python2.7/pygame/surface.h
  /usr/local/include/python3.9/pygame/_camera.h
  /usr/local/include/python3.9/pygame/_pygame.h
  /usr/local/include/python3.9/pygame/_surface.h
  /usr/local/include/python3.9/pygame/camera.h
  /usr/local/include/python3.9/pygame/fastevents.h
  /usr/local/include/python3.9/pygame/font.h
  /usr/local/include/python3.9/pygame/freetype.h
  /usr/local/include/python3.9/pygame/include/_pygame.h
  /usr/local/include/python3.9/pygame/include/bitmask.h
  /usr/local/include/python3.9/pygame/include/pgcompat.h
  /usr/local/include/python3.9/pygame/include/pgimport.h
  /usr/local/include/python3.9/pygame/include/pgplatform.h
  /usr/local/include/python3.9/pygame/include/pygame.h
  /usr/local/include/python3.9/pygame/include/pygame_bufferproxy.h
  /usr/local/include/python3.9/pygame/include/pygame_font.h
  /usr/local/include/python3.9/pygame/include/pygame_freetype.h
  /usr/local/include/python3.9/pygame/include/pygame_mask.h
  /usr/local/include/python3.9/pygame/include/pygame_mixer.h
  /usr/local/include/python3.9/pygame/include/sse2neon.h
  /usr/local/include/python3.9/pygame/mask.h
  /usr/local/include/python3.9/pygame/mixer.h
  /usr/local/include/python3.9/pygame/palette.h
  /usr/local/include/python3.9/pygame/pgarrinter.h
  /usr/local/include/python3.9/pygame/pgbufferproxy.h
  /usr/local/include/python3.9/pygame/pgcompat.h
  /usr/local/include/python3.9/pygame/pgimport.h
  /usr/local/include/python3.9/pygame/pgopengl.h
  /usr/local/include/python3.9/pygame/pgplatform.h
  /usr/local/include/python3.9/pygame/pygame.h
  /usr/local/include/python3.9/pygame/scrap.h
  /usr/local/include/python3.9/pygame/surface.h

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  meson

Warning: You have uncommitted modifications to Homebrew/brew.
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /usr/local/Homebrew && git stash && git clean -d -f

Uncommitted files:
(Library/Homebrew/vendor/bundle/ruby/2.3.0/gems truncated due to exceeding GitHub char limit)

You have uncommitted modifications to Homebrew/homebrew-core.
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core && git stash && git clean -d -f

Uncommitted files:
  ?? Formula/quilt-installer.rb

You have uncommitted modifications to Homebrew/homebrew-cask.
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask && git stash && git clean -d -f

Uncommitted files:
  ?? Casks/cider.rb
  ?? Casks/kit-scenarist.rb
  ?? Casks/roblox.rb
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I was trying to audit a new cask with an uninstall stanza.

### What happened (include all command output)?

While auditing signing, the audit fails due to
```zsh
==> undefined method `source' for #<Cask::Artifact::Uninstall:0x00007fa1e13c18f8>
/usr/local/Homebrew/Library/Homebrew/cask/audit.rb:577:in `block (2 levels) in check_signing'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/audit.rb:574:in `block in check_signing'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/cask/audit.rb:571:in `check_signing'
/usr/local/Homebrew/Library/Homebrew/cask/audit.rb:87:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/auditor.rb:146:in `audit_cask_instance'
/usr/local/Homebrew/Library/Homebrew/cask/auditor.rb:91:in `audit'
/usr/local/Homebrew/Library/Homebrew/cask/auditor.rb:40:in `audit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/audit.rb:109:in `block in audit_casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/audit.rb:107:in `to_h'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/audit.rb:107:in `audit_casks'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:222:in `audit'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
audit for powershell: failed
 - exception while auditing powershell: undefined method `source' for #<Cask::Artifact::Uninstall:0x00007fa1e13c18f8>
Error: 1 problem in 1 cask detected
```
The audit will fail for all casks that include an uninstall stanza.

### What did you expect to happen?

Audit passes.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew audit --new-cask powershell
# You can pass the -d flag to get more output
```

**Comment by carlocab** [comment]
@SMillerDev

**Comment by carlocab** [comment]
Does #13708 fix this?

**Comment by SMillerDev** [comment]
It should, yes

**Comment by carlocab** [comment]
It does not.
```
❯ brew audit --new-cask powershell; brew --version
==> Downloading https://github.com/PowerShell/PowerShell/releases/download/v7.2.6/powershell-7.2.6-osx-x64.pkg
Already downloaded: /Users/chisquared/Library/Caches/Homebrew/downloads/49178c30721f965d49b9ad26e020f778e0aa4738d25a1a2c00992d002f5b192a--powershell-7.2.6-osx-x64.pkg
==> Downloading https://github.com/PowerShell/PowerShell/releases/download/v7.2.6/powershell-7.2.6-osx-x64.pkg
Already downloaded: /Users/chisquared/Library/Caches/Homebrew/downloads/49178c30721f965d49b9ad26e020f778e0aa4738d25a1a2c00992d002f5b192a--powershell-7.2.6-osx-x64.pkg
audit for powershell: failed
 - exception while auditing powershell: undefined method `source' for #<Cask::Artifact::Pkg:0x00007fde73c549d8>
Error: 1 problem in 1 cask detected
Homebrew 3.5.9-119-g3f3c2f5
Homebrew/homebrew-core (git revision 4878fc24808; last commit 2022-08-17)
Homebrew/homebrew-cask (git revision a003509d6d; last commit 2022-08-17)
```

**Comment by carlocab** [comment]
Should be fixed by https://github.com/Homebrew/brew/pull/13711.
