### ISSUE TITLE
Can't finish install: undefined method `ruby_api_version' for Gem:Module

### ISSUE THREAD

**Issue by ptenteromano** [Homebrew/brew#14036]
### `brew config` output

```shell
brew config                                                                                                                                                                      :( 1 22-10-22 - 12:19:18
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/setup.rb:26:in `<top (required)>': undefined method `ruby_api_version' for Gem:Module (NoMethodError)
Did you mean?  ruby_version
               rubygems_version
	from /opt/homebrew/Library/Homebrew/standalone/load_path.rb:12:in `require_relative'
	from /opt/homebrew/Library/Homebrew/standalone/load_path.rb:12:in `<top (required)>'
	from /opt/homebrew/Library/Homebrew/startup.rb:6:in `require_relative'
	from /opt/homebrew/Library/Homebrew/startup.rb:6:in `<top (required)>'
	from /opt/homebrew/Library/Homebrew/global.rb:4:in `require_relative'
	from /opt/homebrew/Library/Homebrew/global.rb:4:in `<top (required)>'
	from /opt/homebrew/Library/Homebrew/brew.rb:22:in `require_relative'
	from /opt/homebrew/Library/Homebrew/brew.rb:22:in `<main>'
```

### `brew doctor` output

```shell
brew doctor                                                                                                                                                                      :( 1 22-10-22 - 12:19:18
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/setup.rb:26:in `<top (required)>': undefined method `ruby_api_version' for Gem:Module (NoMethodError)
Did you mean?  ruby_version
               rubygems_version
	from /opt/homebrew/Library/Homebrew/standalone/load_path.rb:12:in `require_relative'
	from /opt/homebrew/Library/Homebrew/standalone/load_path.rb:12:in `<top (required)>'
	from /opt/homebrew/Library/Homebrew/startup.rb:6:in `require_relative'
	from /opt/homebrew/Library/Homebrew/startup.rb:6:in `<top (required)>'
	from /opt/homebrew/Library/Homebrew/global.rb:4:in `require_relative'
	from /opt/homebrew/Library/Homebrew/global.rb:4:in `<top (required)>'
	from /opt/homebrew/Library/Homebrew/brew.rb:22:in `require_relative'
	from /opt/homebrew/Library/Homebrew/brew.rb:22:in `<main>'
```
### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Install Homebrew

### What happened (include all command output)?

Trying to install Homebrew. Using the default install ruby version on mac:

```
ruby -v                                                                                                                                                                          
ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.arm64e-darwin21]
```

### What did you expect to happen?

Homebrew to finish installing

### Step-by-step reproduction instructions (by running `brew` commands)

Ran install script: `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`

Gets to this section, where it downloads and installs Homebrew, but fails:
```shell
==> Downloading and installing Homebrew...
HEAD is now at faa995022 Merge pull request #14030 from Rylan12/checksum-json-api
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/setup.rb:26:in `<top (required)>': undefined method `ruby_api_version' for Gem:Module (NoMethodError)
Did you mean?  ruby_version
               rubygems_version
	from /opt/homebrew/Library/Homebrew/standalone/load_path.rb:12:in `require_relative'
	from /opt/homebrew/Library/Homebrew/standalone/load_path.rb:12:in `<top (required)>'
	from /opt/homebrew/Library/Homebrew/startup.rb:6:in `require_relative'
	from /opt/homebrew/Library/Homebrew/startup.rb:6:in `<top (required)>'
	from /opt/homebrew/Library/Homebrew/global.rb:4:in `require_relative'
	from /opt/homebrew/Library/Homebrew/global.rb:4:in `<top (required)>'
	from /opt/homebrew/Library/Homebrew/brew.rb:22:in `require_relative'
	from /opt/homebrew/Library/Homebrew/brew.rb:22:in `<main>'
Failed during: /opt/homebrew/bin/brew update --force --quiet
```

**Comment by Bo98** [comment]
Something seems off with your Ruby.

What does `ruby -e 'puts $LOADED_FEATURES'` output?

**Comment by jan-helak-wttech** [comment]
I got the same error as @ptenteromano .

```
▶ ruby -v
ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.arm64e-darwin21]
```
```
▶ ruby -e 'puts $LOADED_FEATURES'
enumerator.so
thread.rb
rational.so
complex.so
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin21/enc/encdb.bundle
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin21/enc/trans/transdb.bundle
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin21/rbconfig.rb
/Library/Ruby/Site/2.6.0/rubygems/compatibility.rb
/Library/Ruby/Site/2.6.0/rubygems/defaults.rb
/Library/Ruby/Site/2.6.0/rubygems/deprecate.rb
/Library/Ruby/Site/2.6.0/rubygems/errors.rb
/Library/Ruby/Site/2.6.0/rubygems/version.rb
/Library/Ruby/Site/2.6.0/rubygems/requirement.rb
/Library/Ruby/Site/2.6.0/rubygems/platform.rb
/Library/Ruby/Site/2.6.0/rubygems/specification.rb
/Library/Ruby/Site/2.6.0/rubygems/exceptions.rb
/Library/Ruby/Site/2.6.0/rubygems/dependency.rb
/Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_gem.rb
/Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb
/Library/Ruby/Site/2.6.0/rubygems.rb
/Library/Ruby/Site/2.6.0/rubygems/path_support.rb
/Library/Ruby/Gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean/version.rb
/Library/Ruby/Gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean/core_ext/name_error.rb
/Library/Ruby/Gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean/levenshtein.rb
/Library/Ruby/Gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean/jaro_winkler.rb
/Library/Ruby/Gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean/spell_checker.rb
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb
/Library/Ruby/Gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean/spell_checkers/name_error_checkers/class_name_checker.rb
/Library/Ruby/Gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean/spell_checkers/name_error_checkers/variable_name_checker.rb
/Library/Ruby/Gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean/spell_checkers/name_error_checkers.rb
/Library/Ruby/Gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean/spell_checkers/method_name_checker.rb
/Library/Ruby/Gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean/spell_checkers/key_error_checker.rb
/Library/Ruby/Gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean/spell_checkers/null_checker.rb
/Library/Ruby/Gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean/formatters/plain_formatter.rb
/Library/Ruby/Gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean.rb
```

**Comment by Bo98** [comment]
`rm -rf /Library/Ruby/Site/2.6.0/rubygems*` will probably work. I guess you somehow have a version of RubyGems installed that's even older than what the default was.

I'll look and see if there's a way to force system RubyGems on our side, but I recommend you remove that old version of RubyGems in any case. If you know how you managed to install that version, that would also be useful.

**Comment by jan-helak-wttech** [comment]
Thanks @Bo98 , that did the trick :). Brew is working now perfectly!

Cannot say how I got such old version of Ruby. Not sure if that is related, but I used Migration Assistant to move from intel mac to M1 mac. After migration brew was working fine, however I was using still using `intel` version. Once I  had tried to use apple silicon version, got the errors from above.

**Comment by ptenteromano** [comment]
`ruby -e` outputted something similar to @jan-helak-wttech. But removing `.../rubygems*` worked for me. Thanks so much @Bo98, this one really bothered me and I ran out of leads to follow. Nice PR btw, glad this brought some awareness to a rubygems issue.

**Comment by Bo98** [comment]
Thanks! Weird one but at least I've managed to mitigate the effects of it on Homebrew.
