### ISSUE TITLE
`Error: stack level too deep` for whatever `brew` command (from 3.6.0)

### ISSUE THREAD

**Issue by asdetrefle** [Homebrew/brew#14081]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 93ea8cb2c40e1ef25f1489b0267526bd47bc8030
Last commit: 8 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4eedfd64491f73860914d237b083daf60a9bff89
Core tap last commit: 9 weeks ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 104
HOMEBREW_NO_INSTALL_CLEANUP: set
Homebrew Ruby: 2.6.8 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: 104-core 64-bit icelake
Clang: N/A
Git: 2.31.1 => /bin/git
Curl: 7.61.1 => /bin/curl
Kernel: Linux 5.4.17-2136.300.7.el8uek.x86_64 x86_64 GNU/Linux
OS: Red Hat Enterprise Linux release 8.6 (Ootpa)
Host glibc: 2.28
/usr/bin/gcc: 8.5.0
/usr/bin/ruby: N/A
Error: stack level too deep
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/standalone/sorbet.rb:19:in `let'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/version.rb:62:in `initialize'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/version.rb:183:in `initialize'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/version.rb:43:in `new'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/version.rb:43:in `create'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/version.rb:663:in `block in tokenize'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/version.rb:663:in `map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/version.rb:663:in `tokenize'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/version.rb:651:in `tokens'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/version.rb:553:in `<=>'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/glibc.rb:50:in `<'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/glibc.rb:50:in `below_ci_version?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:26:in `glibc_dep_if_needed'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/formula.rb:40:in `add_global_deps_to_spec'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:273:in `spec_eval'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:210:in `initialize'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:306:in `new'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:306:in `get_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:551:in `factory'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1943:in `[]'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:58:in `global_deps_for'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:59:in `block in global_deps_for'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:58:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:58:in `flat_map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:58:in `global_deps_for'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:59:in `block in global_deps_for'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:58:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:58:in `flat_map'
...
...
...
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:58:in `global_deps_for'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:59:in `block in global_deps_for'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:58:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:58:in `flat_map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:58:in `global_deps_for'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:59:in `block in global_deps_for'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:58:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:58:in `flat_map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:58:in `global_deps_for'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:48:in `init_global_dep_tree_if_needed!'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dependency_collector.rb:33:in `initialize'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/software_spec.rb:42:in `new'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/software_spec.rb:42:in `initialize'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2716:in `new'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2716:in `block in inherited'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2714:in `instance_eval'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2714:in `inherited'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/glibc.rb:43:in `block in load_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:90:in `module_eval'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:90:in `block in load_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:102:in `load_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:122:in `load_formula_from_path'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:320:in `load_file'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:310:in `klass'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:305:in `get_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:551:in `factory'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/system_config.rb:31:in `formula_linked_version'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/system_config.rb:51:in `block in dump_verbose_config'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/system_config.rb:50:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/system_config.rb:50:in `dump_verbose_config'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/config.rb:27:in `config'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### `brew doctor` output

```shell
Error: stack level too deep
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/standalone/sorbet.rb:19:in `let'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/version.rb:62:in `initialize'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/version.rb:183:in `initialize'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/version.rb:43:in `new'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/version.rb:43:in `create'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/version.rb:663:in `block in tokenize'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/version.rb:663:in `map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/version.rb:663:in `tokenize'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/version.rb:651:in `tokens'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/version.rb:553:in `<=>'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/glibc.rb:50:in `<'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/glibc.rb:50:in `below_ci_version?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:26:in `glibc_dep_if_needed'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/formula.rb:40:in `add_global_deps_to_spec'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:273:in `spec_eval'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:210:in `initialize'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:306:in `new'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:306:in `get_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:551:in `factory'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1943:in `[]'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:58:in `global_deps_for'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:59:in `block in global_deps_for'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:58:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:58:in `flat_map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:58:in `global_deps_for'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:59:in `block in global_deps_for'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:58:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:58:in `flat_map'
...
...
...
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:58:in `global_deps_for'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:59:in `block in global_deps_for'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:58:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:58:in `flat_map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:58:in `global_deps_for'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:59:in `block in global_deps_for'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:58:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:58:in `flat_map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:58:in `global_deps_for'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:48:in `init_global_dep_tree_if_needed!'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dependency_collector.rb:33:in `initialize'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/software_spec.rb:42:in `new'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/software_spec.rb:42:in `initialize'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2716:in `new'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2716:in `block in inherited'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2714:in `instance_eval'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2714:in `inherited'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/glibc.rb:43:in `block in load_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:90:in `module_eval'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:90:in `block in load_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:102:in `load_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:122:in `load_formula_from_path'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:320:in `load_file'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:310:in `klass'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:305:in `get_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:551:in `factory'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/system_config.rb:31:in `formula_linked_version'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/system_config.rb:51:in `block in dump_verbose_config'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/system_config.rb:50:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/system_config.rb:50:in `dump_verbose_config'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/config.rb:27:in `config'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I was just trying to install a package today and immediately got the `Error: stack level too deep`. So I ran `brew config` and `brew doctor` and got the same output.

As I was pretty sure nothing has changed from the system side (last time I use `brew` was end of August), I tried to roll back the `Homebrew/brew` repo and found that the issue was introduced from version 3.6.0. I pinned `brew`@3.5.10 and succeeded installing the package I wanted. Then I checkout to 3.6 and the issue was still there. 

### What happened (include all command output)?

`brew config` and `brew doctor`

### What did you expect to happen?

normal usage of `brew`

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew config`
```

**Comment by carlocab** [comment]
Can you try the latest version? I think there have been fixes for this since then.

**Comment by MikeMcQuaid** [comment]
`brew update` to fix this. If not: `brew update-reset` to fix this.

**Comment by bepstein111** [comment]
Sorry to bring this up again, but, same issue, brew update and brew update-reset have not helped:

```
pi@home:~$ brew update-reset
==> Fetching /home/linuxbrew/.linuxbrew/Homebrew...

==> Resetting /home/linuxbrew/.linuxbrew/Homebrew...
Branch 'master' set up to track remote branch 'master' from 'origin'.
Switched to and reset branch 'master'
Your branch is up to date with 'origin/master'.

==> Fetching /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 5 (delta 4), reused 2 (delta 1), pack-reused 0
Unpacking objects: 100% (5/5), 773 bytes | 773.00 KiB/s, done.
From https://github.com/Homebrew/homebrew-core
 * [new branch]              ubuntu-18.04 -> origin/ubuntu-18.04

==> Resetting /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core...
Branch 'master' set up to track remote branch 'master' from 'origin'.
Reset branch 'master'

pi@home:~$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Error: stack level too deep
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:69:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:69:in `flat_map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:69:in `global_deps_for'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:70:in `block in global_deps_for'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:69:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:69:in `flat_map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:69:in `global_deps_for'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:70:in `block in global_deps_for'
...
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:69:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:69:in `flat_map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:69:in `global_deps_for'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/dependency_collector.rb:50:in `init_global_dep_tree_if_needed!'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dependency_collector.rb:33:in `initialize'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/software_spec.rb:42:in `new'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/software_spec.rb:42:in `initialize'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2697:in `new'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2697:in `block in inherited'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2695:in `instance_eval'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2695:in `inherited'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:1:in `block in load_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:90:in `module_eval'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:90:in `block in load_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:102:in `load_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:122:in `load_formula_from_path'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:322:in `load_file'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:312:in `klass'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:307:in `get_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:561:in `factory'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1917:in `[]'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/diagnostic.rb:763:in `check_for_non_prefixed_coreutils'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/doctor.rb:64:in `block in doctor'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/doctor.rb:57:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/doctor.rb:57:in `doctor'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

**Comment by trolley** [comment]
@bepstein111 - Same here. I'm going to log a new bug.

**Comment by trolley** [comment]
Logged https://github.com/Homebrew/brew/issues/14171.
