### ISSUE TITLE
Validation Failed (GitHub::Error)

### ISSUE THREAD

**Issue by medyagh** [Homebrew/brew#1425]
# Please follow the general troubleshooting steps first:
Done
- [x] Ran `brew update` and retried your prior step?
Yes
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
Yes
### Bug reports:

```
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/tmp/pybats--homebrew-virtualenv-20161102-71550-1iuyk4/target/lib/python2.7/site-packages/virtualenv.py", line 2332, in <module>
    main()
  File "/tmp/pybats--homebrew-virtualenv-20161102-71550-1iuyk4/target/lib/python2.7/site-packages/virtualenv.py", line 711, in main
    symlink=options.symlink)
  File "/tmp/pybats--homebrew-virtualenv-20161102-71550-1iuyk4/target/lib/python2.7/site-packages/virtualenv.py", line 944, in create_environment
    download=download,
  File "/tmp/pybats--homebrew-virtualenv-20161102-71550-1iuyk4/target/lib/python2.7/site-packages/virtualenv.py", line 900, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/tmp/pybats--homebrew-virtualenv-20161102-71550-1iuyk4/target/lib/python2.7/site-packages/virtualenv.py", line 795, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /usr/local/Cellar/py...ibexec/bin/python2.7 - setuptools pip wheel failed with error code 2
Running virtualenv with interpreter /usr/local/bin/python

READ THIS: https://git.io/brew-troubleshooting

/usr/local/Homebrew/Library/Homebrew/utils/github.rb:226:in `raise_api_error': Validation Failed (GitHub::Error)
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:184:in `open'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:233:in `issues_matching'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:266:in `issues_for_formula'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:323:in `fetch_issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:319:in `issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:364:in `dump'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:133:in `rescue in <main>'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:31:in `<main>'
```

**Comment by bfontaine** [comment]
> READ THIS: https://git.io/brew-troubleshooting

Please read this and follow the troubleshooting steps. Thanks!

**Comment by medyagh** [comment]
I tried all of the things in the link

**Comment by MikeMcQuaid** [comment]
@medyagh And your `brew doctor` output?

**Comment by MikeMcQuaid** [comment]
Closing due to no response.
