### ISSUE TITLE
`brew upgrade --cask --greedy-auto-updates` fails 

### ISSUE THREAD

**Issue by solzard** [Homebrew/brew#14463]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.20-146-g4b3d64d
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4b3d64d307c8aa7f364c3f854a0b4dc29d59ecd0
Last commit: 18 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3c1408e72eaa44545ead62fff22a0866a42033ae
Core tap last commit: 5 days ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.X6nT1k2VMz/org.xquartz:0
HOMEBREW_EDITOR: vim
HOMEBREW_INSTALL_FROM_API: set
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.39.1 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6.3-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

I tried to run `brew upgrade --cask --greedy-auto-updates` to update all apps with the `auto_updates` flag at once as well as I do every week; however, `brew` failed and left an error message below this time.

```shell
==> Casks with 'version :latest' will not be upgraded; pass `--greedy-latest` to upgrade them.
==> Upgrading 4 outdated packages:
Error: Cask 'bettertouchtool' is unavailable: No Cask with this name exists.
```

Cask `bettertouchtool` exists as `brew info --cask bettertouchtool` shows:

```shell
==> bettertouchtool: 3.9999,2207 (auto_updates)
https://folivora.ai/
/opt/homebrew/Caskroom/bettertouchtool/3.9999,2206 (129B)
==> Name
BetterTouchTool
==> Description
Tool to customize input devices and automate computer systems
==> Artifacts
BetterTouchTool.app (App)
==> Analytics
install: 1,163 (30 days), 3,450 (90 days), 12,931 (365 days)
```

### What happened (include all command output)?

```shell
# Executed command
brew upgrade --cask --greedy-auto-updates --debug
```

```shell
# Log
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/alfred.rb
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --fail --progress-bar --max-time 5 --retry 3 --location --remote-time --output /Users/solzard/Library/Caches/Homebrew/api/cask.json --time-cond /Users/solzard/Library/Caches/Homebrew/api/cask.json --compressed --silent https://formulae.brew.sh/api/cask.json
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/appcleaner.rb
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/avidemux.rb
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/bartender.rb
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/bettertouchtool.rb
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/brave-browser.rb
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/cheatsheet.rb
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/customshortcuts.rb
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/dash.rb
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/displays.rb
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/docker.rb
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/drivedx.rb
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/font-fira-code-nerd-font.rb
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/forklift.rb
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/gitify.rb
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/google-chrome.rb
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/google-japanese-ime.rb
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/iina.rb
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/imageoptim.rb
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/istat-menus.rb
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/iterm2.rb
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/jetbrains-toolbox.rb
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/launchcontrol.rb
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/menuwhere.rb
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/meta.rb
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/minecraft.rb
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/monitorcontrol.rb
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/mu-editor.rb
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/mullvadvpn.rb
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/obsidian.rb
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/onyx.rb
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/phantomjs.rb
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/raspberry-pi-imager.rb
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/secretive.rb
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/signal.rb
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/sublime-text.rb
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/the-unarchiver.rb
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/transmission.rb
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/trex.rb
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/visual-studio-code.rb
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/xld.rb
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/xquartz.rb
==> Casks with 'version :latest' will not be upgraded; pass `--greedy-latest` to upgrade them.
==> Upgrading 4 outdated packages:
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source//opt/homebrew/Caskroom/bettertouchtool/.metadata/3.9999,2206/20230128140516.851/Casks/bettertouchtool.rb.rb
Error: Cask 'bettertouchtool' is unavailable: No Cask with this name exists.
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:342:in `load'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:351:in `load'
/opt/homebrew/Library/Homebrew/cask/cmd/upgrade.rb:149:in `block in upgrade_casks'
/opt/homebrew/Library/Homebrew/cask/cmd/upgrade.rb:149:in `map'
/opt/homebrew/Library/Homebrew/cask/cmd/upgrade.rb:149:in `upgrade_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:226:in `upgrade_outdated_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:117:in `upgrade'
/opt/homebrew/Library/Homebrew/brew.rb:105:in `<main>'
```

### What did you expect to happen?

Update all casks with the `auto_updates` flag.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update && brew upgrade
brew upgrade --cask --greedy-auto-updates
```

**Comment by gromgit** [comment]
`export HOMEBREW_NO_INSTALL_FROM_API=1` and try your commands again.

**Comment by solzard** [comment]
> `export HOMEBREW_NO_INSTALL_FROM_API=1` and try your commands again.

It didn't work.

```shell
❯ export HOMEBREW_NO_INSTALL_FROM_API=1; brew upgrade --dry-run --cask --greedy-auto-updates
==> Casks with 'version :latest' will not be upgraded; pass `--greedy-latest` to upgrade them.
==> Upgrading 4 outdated package:
Error: Cask 'bettertouchtool' is unavailable: No Cask with this name exists.
```

**Comment by gromgit** [comment]
Interesting. What does `brew upgrade --dry-run --cask --greedy-auto-updates --debug` output?

**Comment by solzard** [comment]
```shell
❯ export HOMEBREW_NO_INSTALL_FROM_API=1

~ |
❯ brew config
HOMEBREW_VERSION: 3.6.20-146-g4b3d64d
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4b3d64d307c8aa7f364c3f854a0b4dc29d59ecd0
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b2439adf3b60c0e598a8a2f82b8574b8849ccecb
Core tap last commit: 3 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.pMWtwq1JRQ/org.xquartz:0
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_NO_INSTALL_FROM_API: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.39.1 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6.3-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
Rosetta 2: false

~ |
❯ brew upgrade --dry-run --cask --greedy-auto-updates --debug
==> Casks with 'version :latest' will not be upgraded; pass `--greedy-latest` to upgrade them.
==> Would upgrade 4 outdated package:
Error: Cask 'bettertouchtool' is unavailable: No Cask with this name exists.
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:342:in `load'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:351:in `load'
/opt/homebrew/Library/Homebrew/cask/cmd/upgrade.rb:149:in `block in upgrade_casks'
/opt/homebrew/Library/Homebrew/cask/cmd/upgrade.rb:149:in `map'
/opt/homebrew/Library/Homebrew/cask/cmd/upgrade.rb:149:in `upgrade_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:226:in `upgrade_outdated_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:117:in `upgrade'
/opt/homebrew/Library/Homebrew/brew.rb:105:in `<main>'
```

**Comment by gromgit** [comment]
OK, so you're actually seeing _two_ problems:
1. Homebrew's move to a universal "install from API" default is having some teething problems right now. Setting the `HOMEBREW_NO_INSTALL_FROM_API` environment variable fixes this by forcing your Homebrew to always consult the local taps (you'll notice the absence of ten thousand thundering `curl`s afterwards).
2. Either your `bettertouchtool` cask file is corrupted somehow, or your existing `bettertouchtool` installation is so old that Homebrew's own installation data for this cask isn't compatible with the current Homebrew code.

To check the first alternative, run `brew readall homebrew/cask`. If it errors out, retap the `homebrew/cask` tap (you'll lose any changes you made inside the tap itself):
```
brew untap --force homebrew/cask
brew tap homebrew/cask
```
If it finishes without error, then you'll need to manually "nuke" the stale installation data and reinstall the cask:
```
rm -fr /opt/homebrew/Caskroom/bettertouchtool
brew reinstall --cask bettertouchtool
```

**Comment by solzard** [comment]
It seems my `bettertouchtool` cask file was corrupted.
I uninstalled BetterTouchTool manually with AppCleaner and clean-installed with `brew`.

```shell
❯ rm -fr /opt/homebrew/Caskroom/bettertouchtool

❯ brew reinstall --cask bettertouchtool
==> Downloading https://folivora.ai/releases/btt3.9999-2208.zip
######################################################################## 100.0%
==> Installing Cask bettertouchtool
==> Purging files for version 3.9999,2208 of Cask bettertouchtool
Error: It seems there is already an App at '/Applications/BetterTouchTool.app'.

✗ brew info --cask bettertouchtool
==> bettertouchtool: 3.9999,2208 (auto_updates)
https://folivora.ai/
Not installed
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/bettertouchtool.rb
==> Name
BetterTouchTool
==> Description
Tool to customize input devices and automate computer systems
==> Artifacts
BetterTouchTool.app (App)
==> Analytics
install: 1,180 (30 days), 3,469 (90 days), 12,941 (365 days)

❯ brew uninstall --cask bettertouchtool
Error: Cask 'bettertouchtool' is not installed.

# Uninstalled BetterTouchTool manually outside the terminal here.

✗ brew install --cask bettertouchtool
==> Downloading https://folivora.ai/releases/btt3.9999-2208.zip
Already downloaded: /Users/solzard/Library/Caches/Homebrew/downloads/3ff472f13bf2f2d55efbd01c180d3f44ed7c00e174e658c2216bada07a464ff1--btt3.9999-2208.zip
==> Installing Cask bettertouchtool
==> Moving App 'BetterTouchTool.app' to '/Applications/BetterTouchTool.app'
🍺  bettertouchtool was successfully installed!
```

After reinstalling BetterTouchTool, the rest of the `auto_updates` apps were successfully upgraded with `brew upgrade --cask --greedy-auto-updates`.

I'll report back when BetterTouchTool gets a new update.
It'll be within a week since BetterTouchTool updates frequently.

**Comment by gromgit** [comment]
Sorry, I wasn't clear. That what you did worked meant the _second_ alternative I mentioned was true: your `bettertouchtool` installation metadata was too old for current Homebrew to process correctly.

I also forgot one important flag, that would probably have eliminated the need for manual removal:
```
brew reinstall --cask --force bettertouchtool
```

**Comment by solzard** [comment]
I installed most apps using `brew install --cask` when I bought my machine in November 2021, including BetterTouchTool. 
Is there any workaround to update their metadata at once? 
Or should I do `rm -rf /opt/homebrew/Caskroom/<app> && brew reinstall --cask --force <app>` only when needed?

**Comment by gromgit** [comment]
> Is there any workaround to update their metadata at once?
> Or should I do rm -rf /opt/homebrew/Caskroom/<app> && brew reinstall --cask --force <app> only when needed?

@Homebrew/cask is better positioned to advise, but I think the latter is the case.

Assuming I understand the cask mechanism in sufficient detail, I think you'll only run into these issues with auto-update casks (and maybe other casks if you only upgrade them once a year or so). The fundamental issue is that a cask file details the extra steps needed to install _and cleanly uninstall_ the cask; the latter is the reason it's cached as part of the installation metadata, and since the cask file may change over time as the upstream software evolves, uninstall stanzas for today's version of XYZ may be completely different from those when you originally installed the cask.

**Comment by solzard** [comment]
Another cask `launchcontrol` caused the same error but `rm -rf /opt/homebrew/Caskroom/<app> && brew reinstall --cask --force <app>` worked, and an update for `bettertouchtool` had no problem.
Thank you very much, @gromgit !

```shell
❯ brew upgrade --cask --greedy-auto-updates
==> Casks with 'version :latest' will not be upgraded; pass `--greedy-latest` to upgrade them.
==> Upgrading 2 outdated packages:
Error: Cask 'launchcontrol' is unavailable: No Cask with this name exists.

~ | ⏰ 12s
✗ export APP=launchcontrol; rm -rfv /opt/homebrew/Caskroom/$APP && brew reinstall --cask --force $APP
removed '/opt/homebrew/Caskroom/launchcontrol/.metadata/config.json'
removed directory '/opt/homebrew/Caskroom/launchcontrol/.metadata/2.1,2354/20230129144904.119/Casks'
removed directory '/opt/homebrew/Caskroom/launchcontrol/.metadata/2.1,2354/20230129144904.119'
removed directory '/opt/homebrew/Caskroom/launchcontrol/.metadata/2.1,2354'
removed directory '/opt/homebrew/Caskroom/launchcontrol/.metadata'
removed '/opt/homebrew/Caskroom/launchcontrol/2.1,2354/LaunchControl.app'
removed directory '/opt/homebrew/Caskroom/launchcontrol/2.1,2354'
removed directory '/opt/homebrew/Caskroom/launchcontrol'
==> Downloading https://www.soma-zone.com/download/files/LaunchControl-2.1.1.tar.xz
######################################################################## 100.0%
==> Installing Cask launchcontrol
Warning: It seems there is already an App at '/Applications/LaunchControl.app'; overwriting.
==> Removing App '/Applications/LaunchControl.app'
==> Moving App 'LaunchControl.app' to '/Applications/LaunchControl.app'
🍺  launchcontrol was successfully installed!

~ | ⏰ 21s
❯ brew upgrade --cask --greedy-auto-updates
==> Casks with 'version :latest' will not be upgraded; pass `--greedy-latest` to upgrade them.
==> Upgrading 1 outdated package:
bettertouchtool 3.9999,2208 -> 4.001,2214
==> Upgrading bettertouchtool
==> Downloading https://folivora.ai/releases/btt4.001-2214.zip
######################################################################## 100.0%
==> Quitting application 'com.hegenberg.BetterTouchTool'...
Application 'com.hegenberg.BetterTouchTool' quit successfully.
==> Backing App 'BetterTouchTool.app' up to '/opt/homebrew/Caskroom/bettertouchtool/3.9999,2208/Be
==> Removing App '/Applications/BetterTouchTool.app'
==> Moving App 'BetterTouchTool.app' to '/Applications/BetterTouchTool.app'
==> Purging files for version 3.9999,2208 of Cask bettertouchtool
🍺  bettertouchtool was successfully upgraded!
```

**Comment by MikeMcQuaid** [comment]
Thanks for the help @gromgit!
