### ISSUE TITLE
Cask 'stats' is unavailable: No Cask with this name exists.

### ISSUE THREAD

**Issue by CheyiLin** [Homebrew/brew#14504]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

Trying to upgrade cask `stats` from 2.8.5 to 2.8.6, got error `Cask 'stats' is unavailable: No Cask with this name exists.`.

```bash
$ brew update-reset
... # (no error)

$ brew update
Already up-to-date.

$ brew outdated --cask --greedy
stats (2.8.5) != 2.8.6

$ $ brew upgrade -d -v --cask --greedy stats
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.2\)\ curl/7.86.0 --header Accept-Language:\ en --fail --max-time 5 --retry 3 --location --remote-time --output /Users/zacklin/Library/Caches/Homebrew/api/formula.json --time-cond /Users/zacklin/Library/Caches/Homebrew/api/formula.json --compressed --silent https://formulae.brew.sh/api/formula.json
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.2\)\ curl/7.86.0 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/stats.rb
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.2\)\ curl/7.86.0 --header Accept-Language:\ en --fail --max-time 5 --retry 3 --location --remote-time --output /Users/zacklin/Library/Caches/Homebrew/api/cask.json --time-cond /Users/zacklin/Library/Caches/Homebrew/api/cask.json --compressed --silent https://formulae.brew.sh/api/cask.json
==> Upgrading 1 outdated package:
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.2\)\ curl/7.86.0 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source//opt/homebrew/Caskroom/stats/.metadata/2.8.5/20230124190602.001/Casks/stats.rb.rb
Error: Cask 'stats' is unavailable: No Cask with this name exists.
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:342:in `load'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:351:in `load'
/opt/homebrew/Library/Homebrew/cask/cmd/upgrade.rb:149:in `block in upgrade_casks'
/opt/homebrew/Library/Homebrew/cask/cmd/upgrade.rb:149:in `map'
/opt/homebrew/Library/Homebrew/cask/cmd/upgrade.rb:149:in `upgrade_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:226:in `upgrade_outdated_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:117:in `upgrade'
/opt/homebrew/Library/Homebrew/brew.rb:105:in `<main>'
```

### Command that failed

brew upgrade --cask --greedy stats

### Output of command with `--verbose --debug`

```shell
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.2\)\ curl/7.86.0 --header Accept-Language:\ en --fail --max-time 5 --retry 3 --location --remote-time --output /Users/zacklin/Library/Caches/Homebrew/api/formula.json --time-cond /Users/zacklin/Library/Caches/Homebrew/api/formula.json --compressed --silent https://formulae.brew.sh/api/formula.json
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.2\)\ curl/7.86.0 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/stats.rb
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.2\)\ curl/7.86.0 --header Accept-Language:\ en --fail --max-time 5 --retry 3 --location --remote-time --output /Users/zacklin/Library/Caches/Homebrew/api/cask.json --time-cond /Users/zacklin/Library/Caches/Homebrew/api/cask.json --compressed --silent https://formulae.brew.sh/api/cask.json
==> Upgrading 1 outdated package:
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.2\)\ curl/7.86.0 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source//opt/homebrew/Caskroom/stats/.metadata/2.8.5/20230124190602.001/Casks/stats.rb.rb
Error: Cask 'stats' is unavailable: No Cask with this name exists.
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:342:in `load'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:351:in `load'
/opt/homebrew/Library/Homebrew/cask/cmd/upgrade.rb:149:in `block in upgrade_casks'
/opt/homebrew/Library/Homebrew/cask/cmd/upgrade.rb:149:in `map'
/opt/homebrew/Library/Homebrew/cask/cmd/upgrade.rb:149:in `upgrade_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:226:in `upgrade_outdated_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:117:in `upgrade'
/opt/homebrew/Library/Homebrew/brew.rb:105:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  redis@6.2

Warning: The filesystem on /System/Volumes/Data appears to be case-sensitive.
The default macOS filesystem is case-insensitive. Please report any apparent problems.

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  kubernetes-cli

$ brew config
HOMEBREW_VERSION: 3.6.20-146-g4b3d64d
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4b3d64d307c8aa7f364c3f854a0b4dc29d59ecd0
Last commit: 30 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b53ed519c7187a6c5498f1a9e74d1cc7eaae3abb
Core tap last commit: 25 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: code
HOMEBREW_INSTALL_FROM_API: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.39.1 => /opt/homebrew/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
$ brew tap
aquasecurity/trivy
bufbuild/buf
gabrie30/utils
homebrew/cask
homebrew/core
homebrew/services
ngrok/ngrok
teamookla/speedtest
```

**Comment by solzard** [comment]
> can you check the `.metadata` directory of the cask and post it's contents?

@Rylan12 , `No Cask with this name exists` error persists in `bettertouchtool` for me even after several reinstalling with the command in https://github.com/Homebrew/brew/issues/14463.

```shell
# Modified to oneliner
export APP="bettertouchtool"; brew readall homebrew/cask || brew untap --force homebrew/cask && brew tap homebrew/cask; rm -rfv "$(brew --caskroom)/${APP:?}" && brew reinstall --cask --force "$APP"
```

`$(brew --caskroom bettertouchtool)/.metadata` info

```shell
❯ exa --tree -all "$(brew --caskroom bettertouchtool)/.metadata"
drwxr-xr-x   - solzard  4 Feb 00:43 /opt/homebrew/Caskroom/bettertouchtool/.metadata
drwxr-xr-x   - solzard  4 Feb 00:43 ├── 4.013,2227
drwxr-xr-x   - solzard  4 Feb 00:43 │  └── 20230203154329.991
drwxr-xr-x   - solzard  4 Feb 00:43 │     └── Casks
.rw-r--r-- 817 solzard  4 Feb 00:43 └── config.json

❯ bat "$(brew --caskroom bettertouchtool)/.metadata/config.json" | jq
{
  "default": {
    "languages": [
      "en-US",
      "ja-US"
    ],
    "appdir": "/Applications",
    "colorpickerdir": "/Users/solzard/Library/ColorPickers",
    "prefpanedir": "/Users/solzard/Library/PreferencePanes",
    "qlplugindir": "/Users/solzard/Library/QuickLook",
    "mdimporterdir": "/Users/solzard/Library/Spotlight",
    "dictionarydir": "/Users/solzard/Library/Dictionaries",
    "fontdir": "/Users/solzard/Library/Fonts",
    "servicedir": "/Users/solzard/Library/Services",
    "input_methoddir": "/Users/solzard/Library/Input Methods",
    "internet_plugindir": "/Users/solzard/Library/Internet Plug-Ins",
    "audio_unit_plugindir": "/Users/solzard/Library/Audio/Plug-Ins/Components",
    "vst_plugindir": "/Users/solzard/Library/Audio/Plug-Ins/VST",
    "vst3_plugindir": "/Users/solzard/Library/Audio/Plug-Ins/VST3",
    "screen_saverdir": "/Users/solzard/Library/Screen Savers"
  },
  "env": {},
  "explicit": {}
}
```

`bettertouchtool` info

```shell
❯ brew outdated --cask --greedy-auto-updates --verbose | grep bettertouchtool
bettertouchtool (4.013,2227) != 4.017,2232
```

`brew` info

```
❯ brew config
HOMEBREW_VERSION: 3.6.20-232-g39e158f
ORIGIN: https://github.com/Homebrew/brew
HEAD: 39e158fb939dadcdf6ee0a67a0930b15f9b16b39
Last commit: 13 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b2439adf3b60c0e598a8a2f82b8574b8849ccecb
Core tap last commit: 6 days ago
Core tap branch: master
Core tap JSON: 05 Feb 12:23
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.TDYCfL5KtA/org.xquartz:0
HOMEBREW_EDITOR: vim
HOMEBREW_INSTALL_FROM_API: set
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.39.1 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6.3-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
Rosetta 2: false

❯ brew tap
homebrew/bundle
homebrew/cask
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
homebrew/services
nextdns/tap
rhysd/hgrep
superbrothers/opener
wader/tap
```

**Comment by gbstan** [comment]
This is affecting many casks: over the past 2 days, it is affecting: bettertouchtool, whatsapp, obs, warp, signal

**Comment by Rylan12** [comment]
The underlying issue should now be fixed, so you should be able to unset `HOMEBREW_NO_INSTALL_FROM_API` and have upgrades work.

You might need to run `brew reinstall --force` once on casks that were already broken, but after doing that you should be good.
