### ISSUE TITLE
Most of the commands result in error.

### ISSUE THREAD

**Issue by seenukarthi** [Homebrew/brew#14542]
# Workaround

You can set `export HOMEBREW_NO_INSTALL_FROM_API=1` for now to work around this but we need to figure out what's going on here.

(added by @MikeMcQuaid)

---

### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.20-298-g8fdf6ac
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8fdf6aca11f685641c9b886c0b48462088d23505
Last commit: 4 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ee949c60592946683261f77857350d337ddb6454
Core tap last commit: 4 days ago
Core tap branch: master
Core tap JSON: 07 Feb 11:21 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.jMWJbufzPx/org.xquartz:0
HOMEBREW_EDITOR: /usr/local/bin/nvim
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ENV_HINTS: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 14.0.0 build 1400
Git: 2.39.1 => /usr/local/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
```

### What were you trying to do (and why)?

I'm trying to do `brew upgrade`

### What happened (include all command output)?

The command result in the following error.

```
$ brew upgrade                                                                                                                                                                                     
Error: No file found at https://raw.githubusercontent.com/Homebrew/homebrew-cask/9da035cce5f43a7a91305908c919cda2d1643571/Casks/vlc.rb
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/api.rb:91:in `fetch_file_source'
/usr/local/Homebrew/Library/Homebrew/api/cask.rb:20:in `fetch_source'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:242:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:382:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:50:in `block in casks'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:46:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:46:in `casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:98:in `upgrade_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:226:in `upgrade_outdated_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:117:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

### What did you expect to happen?

`brew upgrade` be successful.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew upgrade`
```

**Comment by MikeMcQuaid** [comment]
You can set `export HOMEBREW_NO_INSTALL_FROM_API=1` for now to work around this but we need to figure out what's going on here.

**Comment by andrioli** [comment]
Same issue here

```
Error: No file found at https://raw.githubusercontent.com/Homebrew/homebrew-cask/9da035cce5f43a7a91305908c919cda2d1643571/Casks/keepassx.rb
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/api.rb:91:in `fetch_file_source'
/usr/local/Homebrew/Library/Homebrew/api/cask.rb:20:in `fetch_source'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:242:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:382:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:50:in `block in casks'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:46:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:46:in `casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:98:in `upgrade_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:226:in `upgrade_outdated_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:117:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

this is my brew versions

```
Homebrew 3.6.20-298-g8fdf6ac
Homebrew/homebrew-core (git revision 0bd2ff60da9; last commit 2023-02-07)
Homebrew/homebrew-cask (git revision 9da035cce5; last commit 2023-02-07)
```

and my system is:

```
"big_sur": {
    "HOMEBREW_VERSION": "3.6.20-289-gebed4f5",
    "HOMEBREW_PREFIX": "/usr/local",
    "Homebrew/homebrew-core": "fea3233bc2c2b9cf0b312c9ee42302d461a07599",
    "CLT": "13.2.0.0.1.1638488800",
    "Xcode": "13.2.1",
    "macOS": "11.7.3"
}
```

**Comment by andrioli** [comment]
The system I got from brew bundle lock file. But I did a `brew update` and that why the versions look different

**Comment by dblanch369** [comment]
I am getting the same issue this morning when attempting a "brew update"...

Error: No file found at https://raw.githubusercontent.com/Homebrew/homebrew-cask/9da035cce5f43a7a91305908c919cda2d1643571/Casks/charles.rb
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/api.rb:91:in `fetch_file_source'
/usr/local/Homebrew/Library/Homebrew/api/cask.rb:20:in `fetch_source'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:242:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:382:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:50:in `block in casks'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:46:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:46:in `casks'
/usr/local/Homebrew/Library/Homebrew/cmd/outdated.rb:190:in `outdated_formulae_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/outdated.rb:84:in `outdated'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'

**Comment by bmorgenthaler** [comment]
I did a `brew update` yesterday with no issue and then when to do a search today and got the same error.
`❯ brew search docker
Error: No file found at https://raw.githubusercontent.com/Homebrew/homebrew-cask/9da035cce5f43a7a91305908c919cda2d1643571/Casks/docker-toolbox.rb
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/api.rb:91:in `fetch_file_source'
/opt/homebrew/Library/Homebrew/api/cask.rb:20:in `fetch_source'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:242:in `load'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:382:in `load'
/opt/homebrew/Library/Homebrew/search.rb:151:in `block in search_casks'
/opt/homebrew/Library/Homebrew/search.rb:150:in `map'
/opt/homebrew/Library/Homebrew/search.rb:150:in `search_casks'
/opt/homebrew/Library/Homebrew/search.rb:172:in `search_names'
/opt/homebrew/Library/Homebrew/cmd/search.rb:87:in `search'
/opt/homebrew/Library/Homebrew/brew.rb:105:in `<main>'`

`❯ brew doctor
Your system is ready to brew.`

`❯ brew update
Already up-to-date.`

**Comment by MadhavVij** [comment]
## Same Error:

```
Error: No file found at https://raw.githubusercontent.com/Homebrew/homebrew-cask/9da035cce5f43a7a91305908c919cda2d1643571/Casks/keybase.rb
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/api.rb:91:in `fetch_file_source'
/opt/homebrew/Library/Homebrew/api/cask.rb:20:in `fetch_source'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:242:in `load'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:382:in `load'
/opt/homebrew/Library/Homebrew/cask/caskroom.rb:50:in `block in casks'
/opt/homebrew/Library/Homebrew/cask/caskroom.rb:46:in `map'
/opt/homebrew/Library/Homebrew/cask/caskroom.rb:46:in `casks'
/opt/homebrew/Library/Homebrew/cask/cmd/upgrade.rb:98:in `upgrade_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:226:in `upgrade_outdated_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:117:in `upgrade'
/opt/homebrew/Library/Homebrew/brew.rb:93:in `<main>'
❯ brew tap https://formulae.brew.sh/api/cask/keybase.json
Error: Invalid tap name 'https://formulae.brew.sh/api/cask/keybase.json'
```

## brew config

```
HOMEBREW_VERSION: 3.6.20-309-g206d4c8
ORIGIN: https://github.com/Homebrew/brew
HEAD: 206d4c86b36d2d9e093dc886988be9fbb2b28a12
Last commit: 45 minutes ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3c1408e72eaa44545ead62fff22a0866a42033ae
Core tap last commit: 2 weeks ago
Core tap branch: master
Core tap JSON: 07 Feb 14:19 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /usr/bin/vim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_blizzard_avalanche
Clang: 14.0.0 build 1400
Git: 2.39.1 => /opt/homebrew/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
Rosetta 2: false
```

**Comment by glensc** [comment]
Throwing some 2ç

I checked the url that brew upgrade reported, opened in browser fine (authenticated). and curl as well (no authentication). so I was guessing github api limits are hit. my tokien seems in place, and brew doctor does not complain. does brew doctor do github api check to see if token is not rate limited or expired?

```
$ brew upgrade
Error: No file found at https://raw.githubusercontent.com/Homebrew/homebrew-cask/9da035cce5f43a7a91305908c919cda2d1643571/Casks/vlc.rb
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/api.rb:91:in `fetch_file_source'
/opt/homebrew/Library/Homebrew/api/cask.rb:20:in `fetch_source'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:242:in `load'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:382:in `load'
/opt/homebrew/Library/Homebrew/cask/caskroom.rb:50:in `block in casks'
/opt/homebrew/Library/Homebrew/cask/caskroom.rb:46:in `map'
/opt/homebrew/Library/Homebrew/cask/caskroom.rb:46:in `casks'
/opt/homebrew/Library/Homebrew/cask/cmd/upgrade.rb:98:in `upgrade_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:226:in `upgrade_outdated_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:117:in `upgrade'
/opt/homebrew/Library/Homebrew/brew.rb:93:in `<main>'

$  curl -si https://raw.githubusercontent.com/Homebrew/homebrew-cask/9da035cce5f43a7a91305908c919cda2d1643571/Casks/vlc.rb
HTTP/2 200
cache-control: max-age=300
content-security-policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
content-type: text/plain; charset=utf-8
etag: "f1fca55b18339f81a91581d790c916047f946668fa498fbfb70220d131ae72b1"
strict-transport-security: max-age=31536000
x-content-type-options: nosniff
x-frame-options: deny
x-xss-protection: 1; mode=block
x-github-request-id: CC9A:B326:A133ED:ABE8EE:63E26B8A
accept-ranges: bytes
date: Tue, 07 Feb 2023 15:17:30 GMT
via: 1.1 varnish
x-served-by: cache-hel1410028-HEL
x-cache: MISS
x-cache-hits: 0
x-timer: S1675783050.187847,VS0,VE134
vary: Authorization,Accept-Encoding,Origin
access-control-allow-origin: *
x-fastly-request-id: 38d5449b4211671b6252e65b965790a282829886
expires: Tue, 07 Feb 2023 15:22:30 GMT
source-age: 0
content-length: 1432

cask "vlc" do
  arch arm: "arm64", I
[...]
```

**Comment by glensc** [comment]
If it helps, so far all errors I've seen are related to casks.

**Comment by lgw4** [comment]
I do not want to pile on, but piling on. 🤷🏻‍♀️ 

```
❯ brew update
==> Updated Homebrew from 2bb5cdaaa to e26784f42.
Updated 1 tap (homebrew/cask-versions).
==> Outdated Formulae
chezmoi                                                 virtualenv
Error: No file found at https://raw.githubusercontent.com/Homebrew/homebrew-cask/9da035cce5f43a7a91305908c919cda2d1643571/Casks/zoom.rb
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/api.rb:91:in `fetch_file_source'
/opt/homebrew/Library/Homebrew/api/cask.rb:20:in `fetch_source'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:242:in `load'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:382:in `load'
/opt/homebrew/Library/Homebrew/cask/caskroom.rb:50:in `block in casks'
/opt/homebrew/Library/Homebrew/cask/caskroom.rb:46:in `map'
/opt/homebrew/Library/Homebrew/cask/caskroom.rb:46:in `casks'
/opt/homebrew/Library/Homebrew/cmd/update-report.rb:575:in `dump'
/opt/homebrew/Library/Homebrew/cmd/update-report.rb:210:in `output_update_report'
/opt/homebrew/Library/Homebrew/cmd/update-report.rb:43:in `update_report'
/opt/homebrew/Library/Homebrew/brew.rb:93:in `<main>'

❯ brew config
HOMEBREW_VERSION: 3.6.20-318-ge26784f
ORIGIN: https://github.com/Homebrew/brew
HEAD: e26784f424061ca16987afcb21e036c66a298492
Last commit: 2 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: deb1fd1f4212dfbfb26cd668d6aa49a17a3f9445
Core tap last commit: 89 minutes ago
Core tap branch: master
Core tap JSON: 07 Feb 16:23 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: ["--appdir=~/Applications"]
HOMEBREW_EDITOR: code
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_blizzard_avalanche
Clang: 14.0.0 build 1400
Git: 2.39.1 => /opt/homebrew/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
Rosetta 2: false

❯ brew doctor
Your system is ready to brew.
```

**Comment by Bo98** [comment]
We've disabled the code while GitHub have these CDN issues. Run `brew update` to get the change.

**Comment by gbstan** [comment]
I have the same issue:
```
brew outdated
Error: No file found at https://raw.githubusercontent.com/Homebrew/homebrew-cask/9da035cce5f43a7a91305908c919cda2d1643571/Casks/inkscape.rb
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/api.rb:91:in `fetch_file_source'
/usr/local/Homebrew/Library/Homebrew/api/cask.rb:20:in `fetch_source'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:242:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:382:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:50:in `block in casks'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:46:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:46:in `casks'
/usr/local/Homebrew/Library/Homebrew/cmd/outdated.rb:190:in `outdated_formulae_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/outdated.rb:84:in `outdated'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

**Comment by glensc** [comment]
indeed, got curl reproducer for that vlc.rb that worked before

```
$  curl -i https://raw.githubusercontent.com/Homebrew/homebrew-cask/9da035cce5f43a7a91305908c919cda2d1643571/Casks/vlc.rb
HTTP/2 404
content-security-policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
strict-transport-security: max-age=31536000
x-content-type-options: nosniff
x-frame-options: deny
x-xss-protection: 1; mode=block
content-type: text/plain; charset=utf-8
x-github-request-id: BF2E:B326:BB9B38:C7C227:63E2C5F8
accept-ranges: bytes
date: Tue, 07 Feb 2023 21:43:20 GMT
via: 1.1 varnish
x-served-by: cache-hel1410027-HEL
x-cache: MISS
x-cache-hits: 0
x-timer: S1675806200.320769,VS0,VE176
vary: Authorization,Accept-Encoding,Origin
access-control-allow-origin: *
x-fastly-request-id: 4872af7eaf90c5afa822ef0d11ab115ba83886d8
expires: Tue, 07 Feb 2023 21:48:20 GMT
source-age: 0
content-length: 14

404: Not Found
```

and moments later

```
➜ curl -i https://raw.githubusercontent.com/Homebrew/homebrew-cask/9da035cce5f43a7a91305908c919cda2d1643571/Casks/vlc.rb
HTTP/2 200
cache-control: max-age=300
content-security-policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
content-type: text/plain; charset=utf-8
etag: "f1fca55b18339f81a91581d790c916047f946668fa498fbfb70220d131ae72b1"
strict-transport-security: max-age=31536000
x-content-type-options: nosniff
x-frame-options: deny
x-xss-protection: 1; mode=block
x-github-request-id: 650E:6034:24F886:26DEAC:63E2C64A
accept-ranges: bytes
date: Tue, 07 Feb 2023 21:44:42 GMT
via: 1.1 varnish
x-served-by: cache-hel1410025-HEL
x-cache: MISS
x-cache-hits: 0
x-timer: S1675806282.477922,VS0,VE199
vary: Authorization,Accept-Encoding,Origin
access-control-allow-origin: *
x-fastly-request-id: 9ceaaf7e81afb1e99efc4ad60a3d3652d76547b0
expires: Tue, 07 Feb 2023 21:49:42 GMT
source-age: 0
content-length: 1432

cask "vlc" do
...
```

**Comment by glensc** [comment]
@Bo98: should really this command (can you put it to issue body?):

```
HOMEBREW_NO_INSTALL_FROM_API=1 brew update
```

because brew crashes before finishing the update:

```
➜ brew upgrade
Error: No file found at https://raw.githubusercontent.com/Homebrew/homebrew-cask/9da035cce5f43a7a91305908c919cda2d1643571/Casks/vlc.rb
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/api.rb:91:in `fetch_file_source'
/opt/homebrew/Library/Homebrew/api/cask.rb:20:in `fetch_source'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:242:in `load'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:382:in `load'
/opt/homebrew/Library/Homebrew/cask/caskroom.rb:50:in `block in casks'
/opt/homebrew/Library/Homebrew/cask/caskroom.rb:46:in `map'
/opt/homebrew/Library/Homebrew/cask/caskroom.rb:46:in `casks'
/opt/homebrew/Library/Homebrew/cask/cmd/upgrade.rb:98:in `upgrade_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:226:in `upgrade_outdated_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:117:in `upgrade'
/opt/homebrew/Library/Homebrew/brew.rb:93:in `<main>'
✖
```

**Comment by Bo98** [comment]
`brew update` and `brew upgrade` are different things.

**Comment by MikeMcQuaid** [comment]
Addressed for now by reverts.

**Comment by wincent** [comment]
I'm seeing this after running `brew update` just now.

```
brew --version
Homebrew 4.0.0
Homebrew/homebrew-core (git revision 86ff227deb1; last commit 2023-02-07)
Homebrew/homebrew-cask (git revision 9da035cce5; last commit 2023-02-07)
```

After a few runs, `brew update` claims `Already up-to-date`, and `brew doctor` reports no problems, but most commands still fail with:

```
Error: No file found at https://raw.githubusercontent.com/Homebrew/homebrew-cask/cc58401c0905753619a9fc12dc733518beb75b05/Casks/kitty.rb
Do not report this issue until you've run `brew update` and tried again.
/opt/homebrew/Library/Homebrew/api.rb:105:in `fetch_file_source'
...
```

I would remove that cask (eg. `brew uninstall --cask kitty`) but that is one of the commands that fails...

**Comment by AlphaHydrae** [comment]
I am getting similar errors right now.

```
brew update
Already up-to-date.

brew outdated --verbose
Warning: Calling plist_options is deprecated! Use service.require_root instead.
Please report this issue to the mongodb/brew tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/mongodb/homebrew-brew/Formula/mongodb-community.rb:55

Error: No file found at https://raw.githubusercontent.com/Homebrew/homebrew-cask/cc58401c0905753619a9fc12dc733518beb75b05/Casks/firefox.rb
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/api.rb:105:in `fetch_file_source'
/opt/homebrew/Library/Homebrew/api/cask.rb:20:in `fetch_source'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:236:in `load'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:376:in `load'
/opt/homebrew/Library/Homebrew/cask/caskroom.rb:50:in `block in casks'
/opt/homebrew/Library/Homebrew/cask/caskroom.rb:46:in `map'
/opt/homebrew/Library/Homebrew/cask/caskroom.rb:46:in `casks'
/opt/homebrew/Library/Homebrew/cmd/outdated.rb:190:in `outdated_formulae_casks'
/opt/homebrew/Library/Homebrew/cmd/outdated.rb:84:in `outdated'
/opt/homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

**Comment by AlekSi** [comment]
That seems to be #141436
