### ISSUE TITLE
brew outdated fails

### ISSUE THREAD

**Issue by theimpostor** [Homebrew/brew#14549]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 3.6.20-309-g206d4c8
ORIGIN: https://github.com/Homebrew/brew
HEAD: 206d4c86b36d2d9e093dc886988be9fbb2b28a12
Last commit: 16 minutes ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3c1408e72eaa44545ead62fff22a0866a42033ae
Core tap last commit: 2 weeks ago
Core tap branch: master
Core tap JSON: 07 Feb 14:19 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /usr/local/bin/nvim
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 14.0.0 build 1400
Git: 2.39.1 => /usr/local/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6.2-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
```

### What were you trying to do (and why)?

Run `brew outdated`

### What happened (include all command output)?

```
Error: No file found at https://raw.githubusercontent.com/Homebrew/homebrew-cask/9da035cce5f43a7a91305908c919cda2d1643571/Casks/zoom.rb
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/api.rb:91:in `fetch_file_source'
/usr/local/Homebrew/Library/Homebrew/api/cask.rb:20:in `fetch_source'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:242:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:382:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:50:in `block in casks'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:46:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:46:in `casks'
/usr/local/Homebrew/Library/Homebrew/cmd/outdated.rb:190:in `outdated_formulae_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/outdated.rb:84:in `outdated'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

### What did you expect to happen?

See a list of outdated packages.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew outdated
```

**Comment by nodeg** [comment]
Duplicate of https://github.com/Homebrew/brew/issues/14542.

**Comment by theimpostor** [comment]
Closing as dup.

**Comment by carlocab** [comment]
Duplicate of #14542

(Yes, this comment is a duplicate, but it's the only way to get GitHub to register it as one.)

**Comment by carlocab** [comment]
Yes, my previous comment is a duplicate, but it's the only way to get GitHub to register it as one.
