### ISSUE TITLE
`brew info --json=v2 --cask …` either crashes or prints incorrect output if the cask has preflight/postflight artifacts defined using a "do" block

### ISSUE THREAD

**Issue by dpoon** [Homebrew/brew#14541]
### `brew doctor` output

```shell
$ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
$ brew config
HOMEBREW_VERSION: 3.6.20-298-g8fdf6ac
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8fdf6aca11f685641c9b886c0b48462088d23505
Last commit: 3 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 01c9ef11804758fdbbbb58ff16511b51dde9b34b
Core tap last commit: 9 days ago
Core tap branch: master
Core tap JSON: 07 Feb 09:23 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: ["--no-quarantine"]
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.ahYI4vQ3nQ/org.xquartz:0
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.39.1 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6-arm64
CLT: 14.0.0.0.1.1661618636
Xcode: 14.2
Rosetta 2: false
```

### What were you trying to do (and why)?

Trying to run `brew info --json=v2` on some casks.

### What happened (include all command output)?

Crash when querying gimp:

```console
$ brew info --debug --json=v2 --cask gimp
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/3.6.20-298-g8fdf6ac\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6\)\ curl/7.79.1 --header Accept-Language:\ en --fail --progress-bar --max-time 10 --location --remote-time --output /Users/dpoon/Library/Caches/Homebrew/api/cask.json --time-cond /Users/dpoon/Library/Caches/Homebrew/api/cask.json --compressed --silent https://formulae.brew.sh/api/cask.json
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading gimp
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-298-g8fdf6ac\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6\)\ curl/7.79.1 --header Accept-Language:\ en --retry 3 --fail https://raw.githubusercontent.com/Homebrew/homebrew-cask/f24cc51f7b269619df1f8f847477ed63d5bbcaaa/Casks/gimp.rb
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading gimp
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading gimp
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading gimp
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading gimp
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading gimp
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading gimp
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading gimp
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading gimp
Error: Could not parse source for #<Proc:0x00000001041c4490@/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:66>: (eval):2: syntax error, unexpected end, expecting end-of-input
      end
      ^~~
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/method_source-1.0.0/lib/method_source.rb:29:in `rescue in source_helper'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/method_source-1.0.0/lib/method_source.rb:23:in `source_helper'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/method_source-1.0.0/lib/method_source.rb:110:in `source'
/opt/homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:42:in `transform_values'
/opt/homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:42:in `to_h'
/opt/homebrew/Library/Homebrew/cask/cask.rb:300:in `block in artifacts_list'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/opt/homebrew/Library/Homebrew/cask/cask.rb:297:in `map'
/opt/homebrew/Library/Homebrew/cask/cask.rb:297:in `artifacts_list'
/opt/homebrew/Library/Homebrew/cask/cask.rb:248:in `to_h'
/opt/homebrew/Library/Homebrew/cmd/info.rb:243:in `map'
/opt/homebrew/Library/Homebrew/cmd/info.rb:243:in `print_json'
/opt/homebrew/Library/Homebrew/cmd/info.rb:117:in `info'
/opt/homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

---

Incorrect `preflight` when querying Chromium:

```console
$ brew info --debug --json=v2 --cask chromium | head -30
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/3.6.20-298-g8fdf6ac\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6\)\ curl/7.79.1 --header Accept-Language:\ en --fail --progress-bar --silent --max-time 10 --location --remote-time --output /Users/dpoon/Library/Caches/Homebrew/api/cask.json --time-cond /Users/dpoon/Library/Caches/Homebrew/api/cask.json --compressed --silent https://formulae.brew.sh/api/cask.json
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading chromium
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-298-g8fdf6ac\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6\)\ curl/7.79.1 --header Accept-Language:\ en --retry 3 --fail https://raw.githubusercontent.com/Homebrew/homebrew-cask/f24cc51f7b269619df1f8f847477ed63d5bbcaaa/Casks/chromium.rb
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading chromium
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading chromium
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading chromium
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading chromium
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading chromium
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading chromium
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading chromium
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading chromium
{
  "formulae": [

  ],
  "casks": [
    {
      "token": "chromium",
      "full_token": "chromium",
      "tap": null,
      "name": [
        "Chromium"
      ],
      "desc": "Free and open-source web browser",
      "homepage": "https://www.chromium.org/Home",
      "url": "https://download-chromium.appspot.com/dl/Mac_Arm?type=snapshots",
      "appcast": null,
      "version": "latest",
      "versions": {
      },
      "installed": "965870",
      "outdated": false,
      "sha256": "no_check",
      "artifacts": [
        {
          "preflight": "        @token = path.basename(path.extname).to_s\n"
        },
        {
          "app": [
            "chrome-mac/Chromium.app"
          ]
```

### What did you expect to happen?

It shouldn't crash, and it shouldn't report arbitrary code for preflight/postflight.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ cd /opt/homebrew/Caskroom
$ for cask in * ; do brew info --json=v2 --cask "$cask" >/dev/null 2>&1 || echo "$cask" ; done
```

**Comment by dpoon** [comment]
Here is the code, distilled to a minimal test case:

```ruby
#!/bin/bash
exec /opt/homebrew/bin/brew ruby $0
#!ruby

require 'cask'
require 'method_source'

cask_loader = Cask::CaskLoader::FromAPILoader.new('gimp')

# Experiment 1: Try downloading the cask definition to a file, then loading
# it instead.
#cask_loader = Cask::CaskLoader::FromPathLoader.new('/tmp/gimp.rb')


# Experiment 2: Try a FromContentLoader (which is what the FromAPILoader
# ultimately uses), then varying the number of blank lines following the
# __END__ marker.
#cask_loader = Cask::CaskLoader::FromContentLoader.new(DATA.read)


cask = cask_loader.load(config: Cask::Config.new)

# Mimic Cask::Cask#artifacts_list in cask/cask.rb
flight_blocks = cask.artifacts.filter do |artifact|
  Cask::Artifact::AbstractFlightBlock === artifact
end
flight_blocks.map do |fb|
  puts fb
  puts fb.directives.values[0].source
end

__END__
cask "gimp" do
  arch arm: "arm64", intel: "x86_64"

  version "2.10.32-1"
  sha256 arm:   "4c3ae0ce49920fa3a8dd247888cd90fba8fd4a216f8759e8daa14754d25a5ed7",
         intel: "5669ca1f0ce63b0b7c2efd1ac1998116e5ea367b376d453f8341a5d28093f87f"

  url "https://download.gimp.org/gimp/v#{version.major_minor}/macos/gimp-#{version}-#{arch}.dmg"
  name "GIMP"
  name "GNU Image Manipulation Program"
  desc "Free and open-source image editor"
  homepage "https://www.gimp.org/"

  livecheck do
    url "https://www.gimp.org/downloads/"
    regex(%r{href=.*?/gimp[._-]v?(\d+(?:\.\d+)+(-\d)?)[._-]#{arch}\.dmg}i)
  end

  conflicts_with cask: "homebrew/cask-versions/gimp-dev"

  app "GIMP.app"
  shimscript = "#{staged_path}/gimp.wrapper.sh"
  binary shimscript, target: "gimp"

  preflight do
    File.write shimscript, <<~EOS
      #!/bin/sh
      "#{appdir}/GIMP.app/Contents/MacOS/gimp" "$@"
    EOS
  end

  zap trash: [
    "~/Library/Application Support/Gimp",
    "~/Library/Preferences/org.gimp.gimp-#{version.major_minor}:.plist",
    "~/Library/Saved Application State/org.gimp.gimp-#{version.major_minor}:.savedState",
  ]
end
```

---

If you uncomment the `FromContentLoader` line, the code crashes.  If you then insert one empty line after the `__END__` marker, it says that there is an empty preflight block.  If there are three empty lines after the `__END__` marker, then it prints:

```console
$ /tmp/testcase 
preflight (Preflight Block)
        raise CaskUnavailableError.new(token, "'#{path}' does not exist.")  unless path.exist?
```

That code came from `cask/cask_loader.rb`, line 69, and not from gimp's preflight block as expected.

To be precise, if the `preflight` block is at line _p_ of the cask definition, then this test case will print a code expression excerpted from `cask/cask_loader.rb` starting at line <code>42 + _p_ - 1</code>.  Note that line 42 of `cask/cask_loader.rb` is where it calls

```ruby
        instance_eval(content, __FILE__, __LINE__)
```

---

Ultimately, the problem is that the `method_source` 1.0.0 gem is unable to extract source code that is not loaded from a file.

1. In `Cask#artifacts_list`, it calls `Artifact::AbstractFlightBlock#to_h`
2. `Artifact::AbstractFlightBlock#to_h` is:

   ```ruby
      def to_h
        require "method_source"

        directives.transform_values(&:source)
      end
   ```


3. In `method_source.rb`, `#source` calls `MethodSource.source_helper`:

   ```ruby
    def source
      MethodSource.source_helper(source_location, defined?(name) ? name : inspect)
    end
   ```

4. `MethodSource.source_helper` is defined as:

    ```ruby
      # Helper method responsible for extracting method body.
      # Defined here to avoid polluting `Method` class.
      # @param [Array] source_location The array returned by Method#source_location
      # @param [String]  method_name
      # @return [String] The method body
      def self.source_helper(source_location, name=nil)
        raise SourceNotFoundError, "Could not locate source for #{name}!" unless source_location
        file, line = *source_location
    
        expression_at(lines_for(file), line)
      rescue SyntaxError => e
        raise SourceNotFoundError, "Could not parse source for #{name}: #{e.message}"
      end
   ```

There is no way that `expression_at(lines_for(file), …)` can work, when the code was evaluated from a string and not a file.

**Comment by MikeMcQuaid** [comment]
Thanks for the debugging here @dpoon!
