### ISSUE TITLE
ERROR: brew info --json=v2

### ISSUE THREAD

**Issue by moonfruit** [Homebrew/brew#14791]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.3-103-gd7029e9
ORIGIN: https://github.com/Homebrew/brew
HEAD: d7029e95cd888887ee80aaab0918c6a92ac81cad
Last commit: 13 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: bc18192d5f01cfc11a569af66792fb5009e42674
Core tap last commit: 4 hours ago
Core tap branch: master
Core tap JSON: 23 Feb 01:56 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_AUTO_UPDATE_SECS: 86400
HOMEBREW_BAT: set
HOMEBREW_CASK_OPTS: []
HOMEBREW_CLEANUP_MAX_AGE_DAYS: 7
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 14.0.0 build 1400
Git: 2.39.2 => /opt/homebrew/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2.1-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
Rosetta 2: false
```

### What were you trying to do (and why)?

```sh
brew info --json=v2 firefox
```

Some casks will fail to execute `brew info --json=v2`. So far I have only found the following casks.

* firefox
* kitty
* appcode
* clion
* datagrip
* dataspell
* goland
* intellij-idea
* phpstorm
* pycharm
* rider
* rubymine
* webstorm

### What happened (include all command output)?

```console
$ brew info --json=v2 firefox
Error: no implicit conversion of nil into String
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/digest.rb:50:in `initialize'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/digest.rb:50:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/digest.rb:50:in `file'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/digest.rb:35:in `file'
/opt/homebrew/Library/Homebrew/cask/cask.rb:356:in `ruby_source_checksum'
/opt/homebrew/Library/Homebrew/cask/cask.rb:302:in `to_h'
/opt/homebrew/Library/Homebrew/cmd/info.rb:232:in `map'
/opt/homebrew/Library/Homebrew/cmd/info.rb:232:in `print_json'
/opt/homebrew/Library/Homebrew/cmd/info.rb:110:in `info'
/opt/homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

### What did you expect to happen?

Command successfully executed.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ brew info --json=v2 firefox
```

**Comment by carlocab** [comment]
Can you try running it with `--debug`?

**Comment by moonfruit** [comment]
```console
$ brew info --json=v2 --debug firefox
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading firefox
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.3-103-gd7029e9\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.2.1\)\ curl/7.86.0 --header Accept-Language:\ en --retry 3 --fail https://raw.githubusercontent.com/Homebrew/homebrew-cask/f96dd73ba870b1d27cbcd324efb943a78b6072d1/Casks/firefox.rb
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading firefox
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading firefox
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading firefox
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading firefox
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading firefox
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading firefox
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading firefox
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading firefox
Error: no implicit conversion of nil into String
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/digest.rb:50:in `initialize'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/digest.rb:50:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/digest.rb:50:in `file'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/digest.rb:35:in `file'
/opt/homebrew/Library/Homebrew/cask/cask.rb:356:in `ruby_source_checksum'
/opt/homebrew/Library/Homebrew/cask/cask.rb:302:in `to_h'
/opt/homebrew/Library/Homebrew/cmd/info.rb:232:in `map'
/opt/homebrew/Library/Homebrew/cmd/info.rb:232:in `print_json'
/opt/homebrew/Library/Homebrew/cmd/info.rb:110:in `info'
/opt/homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

**Comment by MikeMcQuaid** [comment]
`ruby_source_checksum` looks like your most recent changes @Bo98

**Comment by apainintheneck** [comment]
The Firefox cask supports multiple languages so we don't actually load it from the JSON API we load it from the source API. So it looks what's happening here is that we can't load it because we don't have any `sourcefile_path` because we don't actually have a file that corresponds to the cask at all. All we have is the source as text that we downloaded from the source API.

```rb
irb(main):004:0> json_cask = Homebrew::API::Cask.all_casks["firefox"]; nil
=> nil
irb(main):005:0> cask = Cask::CaskLoader::FromAPILoader.new("firefox").load(config: nil); nil
=> nil
irb(main):006:0> cask.to_h
Traceback (most recent call last):
        8: from /usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
        7: from (irb):6
        6: from /usr/local/Homebrew/Library/Homebrew/cask/cask.rb:302:in `to_h'
        5: from /usr/local/Homebrew/Library/Homebrew/cask/cask.rb:356:in `ruby_source_checksum'
        4: from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/digest.rb:35:in `file'
        3: from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/digest.rb:50:in `file'
        2: from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/digest.rb:50:in `open'
        1: from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/digest.rb:50:in `initialize'
TypeError (no implicit conversion of nil into String)
irb(main):007:0> cask.instance_variable_set(:@ruby_source_checksum, json_cask["ruby_source_checksum"])
=> {"sha256"=>"4fe0b54b80d6d98d059839404f7fbddb155f8e2f4ab2bb5e7de25bbf1c643d41"}
irb(main):008:0> cask.to_h
=> {"token"=>"firefox", "full_token"=>"firefox", "tap"=>nil, "name"=>["Mozilla Firefox"], "desc"=>"Web browser", "homepage"=>"https://www.mozilla.org/firefox/", "url"=>#<URL::DSL:0x00007fddba13adb8 @uri=#<URI::HTTPS https://download-installer.cdn.mozilla.net/pub/firefox/releases/110.0/mac/en-US/Firefox%20110.0.dmg>, @verified="download-installer.cdn.mozilla.net/pub/firefox/releases/", @using=nil, @tag=nil, @branch=nil, @revisions=nil, @revision=nil, @trust_cert=nil, @cookies=nil, @referer=nil, @header=nil, @user_agent=:default, @data=nil, @only_path=nil, @specs={:verified=>"download-installer.cdn.mozilla.net/pub/firefox/releases/", :user_agent=>:default}>, "appcast"=>nil, "version"=>"110.0", "versions"=>{}, "installed"=>nil, "outdated"=>false, "sha256"=>#<Checksum:0x00007fddba13b6a0 @hexdigest="305161dd64565a816f22aa6f2e807f139a33c8afcdececaca0c7da0cd3bb3aa4">, "artifacts"=>[{:uninstall=>[{:quit=>"org.mozilla.firefox"}]}, {:app=>["Firefox.app"]}, {:zap=>[{:trash=>["~/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/org.mozilla.firefox.sfl*", "~/Library/Application Support/CrashReporter/firefox_*", "~/Library/Application Support/Firefox", "~/Library/Caches/Firefox", "~/Library/Caches/Mozilla/updates/Applications/Firefox", "~/Library/Caches/org.mozilla.crashreporter", "~/Library/Caches/org.mozilla.firefox", "~/Library/Preferences/org.mozilla.crashreporter.plist", "~/Library/Preferences/org.mozilla.firefox.plist", "~/Library/Saved Application State/org.mozilla.firefox.savedState", "~/Library/WebKit/org.mozilla.firefox", "/Library/Logs/DiagnosticReports/firefox_*"], :rmdir=>["~/Library/Application Support/Mozilla", "~/Library/Caches/Mozilla/updates/Applications", "~/Library/Caches/Mozilla/updates", "~/Library/Caches/Mozilla"]}]}], "caveats"=>nil, "depends_on"=>{:macos=>#<MacOSRequirement: version>="10.12" []>}, "conflicts_with"=>{:cask=>#<Set: {"homebrew/cask-versions/firefox-beta", "homebrew/cask-versions/firefox-esr"}>}, "container"=>nil, "auto_updates"=>true, "tap_git_head"=>nil, "languages"=>["af", "ar", "be", "bg", "bn", "ca", "cs", "de", "en-CA", "en-GB", "en", "eo", "es-AR", "es-CL", "es-ES", "fa", "ff", "fi", "fr", "gl", "gn", "gu", "he", "hi", "in", "it", "ja", "ka", "ko", "mr", "my", "ne", "nl", "pa-IN", "pl", "pt-BR", "pt", "ru", "si", "sq", "sr", "sv", "ta", "te", "th", "tl", "tr", "uk", "ur", "zh-TW", "zh"], "ruby_source_checksum"=>{"sha256"=>"4fe0b54b80d6d98d059839404f7fbddb155f8e2f4ab2bb5e7de25bbf1c643d41"}}
```

https://github.com/Homebrew/brew/blob/d7029e95cd888887ee80aaab0918c6a92ac81cad/Library/Homebrew/cask/cask_loader.rb#L233-L240

After loading the cask from the source API here we need to use the `source_checksum` from the JSON API to set `ruby_source_checksum` in the cask.

**Comment by moonfruit** [comment]
There are also many failed casks that do not support multiple languages. So I do not think that support for multiple languages is the cause of this problem.

**Comment by MikeMcQuaid** [comment]
Thanks for looking @apainintheneck! If you'd be able to braindump into a draft PR then I or Bo will finish it off. np if too late!
