### ISSUE TITLE
`brew info --eval-all --json=v2` fail

### ISSUE THREAD

**Issue by sugiura-hiromichi** [Homebrew/brew#15094]
### `brew doctor` output

```shell
❯ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
❯ brew config
HOMEBREW_VERSION: 4.0.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: cf6614b50eac1c9f4bf386dc6989f0d443148df8
Last commit: 3 days ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b7e525330968bcfe754ea1dd95b3f4768feaa0a0
Core tap last commit: 9 days ago
Core tap branch: master
Core tap JSON: 30 Mar 12:30 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit kabylake
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
```

### What were you trying to do (and why)?

when I ran `brew-file init`, it was failed with output that

```
[ERROR] Failed at command: /usr/local/bin/brew info --eval-all --json=v2
Error: no implicit conversion of nil into Hash
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:260:in `block in load'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:93:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:93:in `refresh'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:86:in `config='
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:76:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:251:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:251:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:387:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:125:in `block in os_versions'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:123:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:123:in `os_versions'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:299:in `to_h'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:232:in `map'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:232:in `print_json'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:110:in `info'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

Then, I ran `brew info --eval-all --json=v2`, it was failed with exact same error message

```
Error: no implicit conversion of nil into Hash
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:260:in `block in load'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:93:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:93:in `refresh'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:86:in `config='
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:76:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:251:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:251:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:387:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:125:in `block in os_versions'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:123:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:123:in `os_versions'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:299:in `to_h'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:232:in `map'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:232:in `print_json'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:110:in `info'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

`brew-file` is installation manager like `brew bundle`.

### What happened (include all command output)?

```
❯ brew info --eval-all --json=v2
Error: no implicit conversion of nil into Hash
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:260:in `block in load'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:93:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:93:in `refresh'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:86:in `config='
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:76:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:251:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:251:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:387:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:125:in `block in os_versions'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:123:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:123:in `os_versions'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:299:in `to_h'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:232:in `map'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:232:in `print_json'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:110:in `info'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### What did you expect to happen?

I don't know actually what `brew into --eval-all --json=v2` means, but I expect not to be failed.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
I just ran `brew into --eval-all --json=v2`
```

**Comment by MikeMcQuaid** [comment]
> brew-file init

What is this command and where is it from?

Try to run ``brew info --debug --verbose --eval-all --json=v2` and post the results here in a `<details>` block, thanks!

**Comment by carlocab** [comment]
Can't reproduce this. Can you try doing
```
brew untap homebrew/core homebrew/cask
```
and see if it helps?

**Comment by sugiura-hiromichi** [comment]
I run `brew-file init` and this time, it succeeds. I'm not sure why it succeeded because I do not change any configs and do not update brew and brew-file. It's curious but I have no problem now. Thank you!

**Comment by igorlg** [comment]
Having the same issue for a few days/perhaps a week now. Managed to isolate the problem to cask `apparency`:

```
$ brew info --cask --json=v2 --debug --verbose apparency
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading apparency
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading apparency
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading apparency
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading apparency
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading apparency
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading apparency
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading apparency
Error: no implicit conversion of nil into Hash
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:260:in `block in load'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:93:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:93:in `refresh'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:86:in `config='
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:76:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:251:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:251:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:387:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:125:in `block in os_versions'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:123:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:123:in `os_versions'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:299:in `to_h'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:232:in `map'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:232:in `print_json'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:110:in `info'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

Running on a Intel-based MacOS Ventura 13.2.1, with Homebrew versions:

```
brew --version
Homebrew 4.0.10-119-g931327d
Homebrew/homebrew-core (git revision fbf8af0430f; last commit 2023-04-02)
Homebrew/homebrew-cask (git revision 34c1d99da4; last commit 2023-04-03)
```

Note: This is a blocker since `brew info --eval-all --json=v2` uses the FormulaAPI, and thus the broken Formula/Cask cannot be skipepd...

**Comment by carlocab** [comment]
@igorlg could you open a new issue for that? Thanks!
