### ISSUE TITLE
Error: invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by yermulnik** [Homebrew/brew#15145]
### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  libgit2@1.5

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  gcc@5
  isl@0.18
  jsonschema
  libelf

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/python2.7/greenlet/greenlet.h
  /usr/local/include/python3.6m/Python-ast.h
  /usr/local/include/python3.6m/Python.h
  […]
  /usr/local/include/python3.6m/warnings.h
  /usr/local/include/python3.6m/weakrefobject.h

Warning: Unbrewed '.pc' files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected '.pc' files:
  /usr/local/lib/pkgconfig/python-3.6.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libpcrs.a
  /usr/local/lib/libpython3.6m.a
  /usr/local/lib/libtcp-portmon.a

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  pygments
  six
  elfutils
  opencl-icd-loader

The following tools exist at both paths:
  g++-5
  update-mime-database
  ldapexop
  timeout
  ps2pdf13
  […]
  toe
  xmllint
Error: invalid byte sequence in UTF-8
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.7.3/lib/active_support/core_ext/object/blank.rb:127:in `match?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.7.3/lib/active_support/core_ext/object/blank.rb:127:in `blank?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/doctor.rb:63:in `block in doctor'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/doctor.rb:55:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/doctor.rb:55:in `doctor'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.11-33-g7dbe1b4-dirty
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7dbe1b4877ca510b3832d84fb798e2f05e89494a
Last commit: 63 minutes ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3409af069e4c05f0493d17dc824e0fed4f2d512c
Core tap last commit: 8 weeks ago
Core tap branch: master
Core tap JSON: 04 Apr 09:15 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_AUTO_UPDATE_SECS: 7200
HOMEBREW_BAT: set
HOMEBREW_BAT_CONFIG_PATH: /home/yz/.config/bat/config
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: localhost:10.0
HOMEBREW_EDITOR: /usr/bin/vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_INSTALL_BADGE: ✔
HOMEBREW_MAKE_JOBS: 2
HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: set
Homebrew Ruby: 2.6.8 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: quad-core 64-bit haswell
Clang: 16.0.0
Git: 2.40.0 => /usr/bin/git
Curl: 7.47.0 => /usr/bin/curl
Kernel: Linux 4.4.0-210-generic x86_64 GNU/Linux
OS: Linux Mint 18.3 Sylvia (sylvia)
Host glibc: 2.23
/usr/bin/gcc: 4.9.4
/usr/bin/ruby: 2.3.1
glibc: 2.35_1
gcc@11: 11.3.0
gcc: 12.2.0
xorg: N/A
```

### What were you trying to do (and why)?

what: `brew cleanup`
why: previous run of `brew upgrade` ended up with the below:
```
[…]
Removing: /home/yz/.cache/Homebrew/Logs/packer... (4KB)
Error: invalid byte sequence in UTF-8
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cleanup.rb:535:in `match?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cleanup.rb:535:in `block (2 levels) in prune_prefix_symlinks_and_directories'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/pathname.rb:565:in `block in find'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/find.rb:49:in `block (2 levels) in find'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/find.rb:48:in `catch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/find.rb:48:in `block in find'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/find.rb:43:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/find.rb:43:in `find'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/pathname.rb:565:in `find'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cleanup.rb:531:in `block in prune_prefix_symlinks_and_directories'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cleanup.rb:528:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cleanup.rb:528:in `prune_prefix_symlinks_and_directories'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cleanup.rb:243:in `clean!'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cleanup.rb:225:in `periodic_clean!'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/upgrade.rb:131:in `upgrade'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### What happened (include all command output)?

```shell
> brew cleanup
Warning: Skipping (old) /home/linuxbrew/.linuxbrew/Cellar/autogen/5.18.16_2 due to it being linked
Warning: Skipping (old) /home/linuxbrew/.linuxbrew/Cellar/dive/0.10.0 due to it being linked                       W
arning: Skipping git-chglog/git-chglog/git-chglog: most recent version 0.15.4 not installed
Warning: Skipping dty1er/tap/kubecolor: most recent version 0.0.25 not installed
Warning: Skipping (old) /home/linuxbrew/.linuxbrew/Cellar/mesa-glu/9.0.2 due to it being linked
Warning: Skipping (old) /home/linuxbrew/.linuxbrew/Cellar/openjpeg/2.5.0 due to it being linked
Warning: Skipping snyk/tap/snyk: most recent version 1.1137.0 not installed
Warning: Skipping terragrunt: most recent version 0.45.1 not installed
Warning: Skipping terramate: most recent version 0.2.17 not installed
Warning: Skipping bridgecrewio/tap/yor: most recent version 0.1.171 not installed
Error: invalid byte sequence in UTF-8
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cleanup.rb:535:in `match?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cleanup.rb:535:in `block (2 levels) in prune_prefix_symlinks_and_directories'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/pathname.rb:565:in `block in find'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/find.rb:49:in `block (2 levels) in find'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/find.rb:48:in `catch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/find.rb:48:in `block in find'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/find.rb:43:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/find.rb:43:in `find'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/pathname.rb:565:in `find'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cleanup.rb:531:in `block in prune_prefix_symlinks_and_directories'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cleanup.rb:528:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cleanup.rb:528:in `prune_prefix_symlinks_and_directories'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cleanup.rb:243:in `clean!'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/cleanup.rb:58:in `cleanup'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### What did you expect to happen?

`brew cleanup` to not through error

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew cleanup`
```

**Comment by MikeMcQuaid** [comment]
Try to run `brew cleanup --dry-run` and it'll likely output `Would remove (broken link):` and then one of the paths for you to manually remove that's causing this error.

**Comment by yermulnik** [comment]
Thanks, I tried it and it didn't help =(
```shell
> brew cleanup --dry-run
Warning: Skipping (old) /home/linuxbrew/.linuxbrew/Cellar/autogen/5.18.16_2 due to it being linked
Warning: Skipping (old) /home/linuxbrew/.linuxbrew/Cellar/dive/0.10.0 due to it being linked
Warning: Skipping (old) /home/linuxbrew/.linuxbrew/Cellar/mesa-glu/9.0.2 due to it being linked
Warning: Skipping (old) /home/linuxbrew/.linuxbrew/Cellar/openjpeg/2.5.0 due to it being linked
Warning: Skipping bridgecrewio/tap/yor: most recent version 0.1.171 not installed
Error: invalid byte sequence in UTF-8
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cleanup.rb:535:in `match?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cleanup.rb:535:in `block (2 levels) in prune_prefix_symlinks_and_directories'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/pathname.rb:565:in `block in find'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/find.rb:49:in `block (2 levels) in find'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/find.rb:48:in `catch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/find.rb:48:in `block in find'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/find.rb:43:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/find.rb:43:in `find'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/pathname.rb:565:in `find'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cleanup.rb:531:in `block in prune_prefix_symlinks_and_directories'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cleanup.rb:528:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cleanup.rb:528:in `prune_prefix_symlinks_and_directories'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cleanup.rb:243:in `clean!'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/cleanup.rb:58:in `cleanup'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

**Comment by yermulnik** [comment]
Adding a debug statement into `cleanup.rb` on line 535 helped though:
```
Would remove (broken link): /home/linuxbrew/.linuxbrew/lib/�
```
Not sure where this came from, though this also helped to reveal other garbage in this dir 😲 
```shell
> LANG=C ll /home/linuxbrew/.linuxbrew/lib/ | less
total 311296
lrwxrwxrwx  1 root root    10 Oct 30 19:52 ^B -> libLLVM.so*
lrwxrwxrwx  1 root root    21 Oct 30 19:52 ^D -> libtextstyle.so.0.1.2*
lrwxrwxrwx  1 root root     9 Oct 30 19:52       -> libgts.so*
lrwxrwxrwx  1 root root    15 Oct 30 19:52
 -> libgvc.so.6.0.0*
lrwxrwxrwx  1 root root    19 Oct 30 19:52 ^K -> libsqlite3.so.0.8.6*
lrwxrwxrwx  1 root root    18 Oct 30 19:52 ^O -> libcgraph.so.6.0.0*
drwxrwx--- 18 yz   yz   69632 Apr  4 15:20 ./
drwx------ 14 yz   yz    4096 Nov 15  2020 ../
-rw-------  1 yz   yz       0 Nov 15  2020 .keepme
lrwxrwxrwx  1 root root    23 Oct 30 19:52 2.2.5 -> libgnutls-dane.so.0.4.1*
lrwxrwxrwx  1 root root    18 Oct 30 19:52 END__ -> libnetpbm.so.11.86*
lrwxrwxrwx  1 yz   yz      38 Mar 23 22:11 LLVMPolly.so -> ../Cellar/llvm/16.0.0/lib/LLVMPolly.so*
lrwxrwxrwx  1 yz   yz      37 Mar 23 22:11 LLVMgold.so -> ../Cellar/llvm/16.0.0/lib/LLVMgold.so*
lrwxrwxrwx  1 yz   yz      34 Sep 19  2022 Mcrt1.o -> ../Cellar/glibc/2.35_1/lib/Mcrt1.o*
lrwxrwxrwx  1 root root    17 Oct 30 19:52 Pk    -> libxml2.so.2.10.3*
lrwxrwxrwx  1 yz   yz      34 Sep 19  2022 Scrt1.o -> ../Cellar/glibc/2.35_1/lib/Scrt1.o*
lrwxrwxrwx  1 yz   yz      30 Feb  6 22:40 X11 -> ../Cellar/libx11/1.8.4/lib/X11/
lrwxrwxrwx  1 root root    16 Oct 30 19:52 _2.4 -> libbsd.so.0.11.7*
lrwxrwxrwx  1 root root    21 Oct 30 19:52 _ZN6gnutls7session7prf_rawEmPKcmS2_mPc -> libgnutlsxx.so.30.0.0*
lrwxrwxrwx  1 root root    10 Oct 30 19:52 _contPKcm -> libompd.so*
lrwxrwxrwx  1 root root    15 Oct 30 19:52 _msc_reply -> libEGL.so.1.0.0*
[snip line thhat look sane]
lrwxrwxrwx  1 root root    16 Oct 30 19:52 <B2>  -> libgxps.so.10.00
```
Am going to clean this garbage manually 🤔

**Comment by MikeMcQuaid** [comment]
Glad you're able to find it manually. Closing this because this will blow up all over Homebrew as it looks a lot like some sort of disk corruption.

**Comment by yermulnik** [comment]
Manual cleanup helped. Thanks @MikeMcQuaid 
Yep, looks a power outage could lead to some files got corrupted back then.

**Comment by yermulnik** [comment]
The `match?()` at this line in `cleanup.rb` might probably need to be secured against "improper" chars though:
```ruby
path.uninstall_info if path.to_s.match?(Keg::INFOFILE_RX) && !dry_run?
```

**Comment by MikeMcQuaid** [comment]
> The `match?()` at this line in `cleanup.rb` might probably need to be secured against "improper" chars though:

I don't think so. This will blow up all over Homebrew. I'd like to see it affecting multiple users before I think it's worth handling.
