### ISSUE TITLE
macOS brew 4.0.13-28 + python 3.9/3.10 + pip + ssl does not fetch packages.

### ISSUE THREAD

**Issue by cederom** [Homebrew/brew#15234]
### `brew doctor` output

```shell
`Your system is ready to brew.`
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.13-28-g4fe3436
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4fe3436682365f81eb68f56a2b8b5d766a372e00
Last commit: 66 minutes ago
Core tap JSON: 14 Apr 21:49 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.40.0 => /opt/homebrew/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3.1-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: 14.3
Rosetta 2: false
```

### What were you trying to do (and why)?

* Crosscompile Kivy's Python 3.9/3.10 application to a mobile platform (Android / iOS) with Buildozer / Python-For-Android (https://github.com/kivy/buildozer/issues/1595).
* This brew + python + pip + ssl is a known problem that happens when no system python is used, for some time, would be good to find a reliable fix, see https://python-for-android.readthedocs.io/en/latest/troubleshooting/#sslerror-can-t-connect-to-https-url-because-the-ssl-module-is-not-available.
* Kivy cannot yet use Python 3.11. Is this problem related with older python releases on brew?
* If this is a environment variables problem then this might be a general solution: https://github.com/Homebrew/brew/issues/15233.
* Any hints appreciated, thanks in advance :-)

### What happened (include all command output)?

```shell
[DEBUG]:   	WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
[DEBUG]:   	Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
Exception in thread background thread for pid 86116:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/XXX/pyvenv/lib/python3.10/site-packages/sh.py", line 1641, in wrap
    fn(*rgs, **kwargs)
  File "/XXX/pyvenv/lib/python3.10/site-packages/sh.py", line 2569, in background_thread
    handle_exit_code(exit_code)
  File "/XXX/pyvenv/lib/python3.10/site-packages/sh.py", line 2269, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/XXX/pyvenv/lib/python3.10/site-packages/sh.py", line 869, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1:

  RAN: /bin/bash -c 'venv/bin/pip install Cython'

  STDOUT:
Ignoring "sys._home = value" override
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/cython/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/cython/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/cython/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/cython/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/cython/
Could not fetch URL https://pypi.org/simple/cython/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/cython/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
ERROR: Could not find a version that satisfies the requirement Cython (from versions: none)
ERROR: No matching distribution found for Cython
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping


  STDERR:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/XXX/myapp/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 1312, in <module>
    main()
  File "/XXX/myapp/.buildozer/android/platform/python-for-android/pythonforandroid/entrypoints.py", line 18, in main
    ToolchainCL()
  File "/XXX/myapp/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 734, in __init__
    getattr(self, command)(args)
  File "/XXX/myapp/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 153, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/XXX/myapp/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 212, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx,
  File "/XXX/myapp/.buildozer/android/platform/python-for-android/pythonforandroid/build.py", line 528, in build_recipes
    run_pymodules_install(
  File "/XXX/myapp/.buildozer/android/platform/python-for-android/pythonforandroid/build.py", line 713, in run_pymodules_install
    shprint(sh.bash, '-c', (
  File "/XXX/myapp/.buildozer/android/platform/python-for-android/pythonforandroid/logger.py", line 167, in shprint
    for line in output:
  File "/XXX/pyvenv/lib/python3.10/site-packages/sh.py", line 915, in next
    self.wait()
  File "/XXX/pyvenv/lib/python3.10/site-packages/sh.py", line 845, in wait
    self.handle_command_exit_code(exit_code)
  File "/XXX/pyvenv/lib/python3.10/site-packages/sh.py", line 869, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1:

  RAN: /bin/bash -c 'venv/bin/pip install Cython'

  STDOUT:
Ignoring "sys._home = value" override
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/cython/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/cython/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/cython/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/cython/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/cython/
Could not fetch URL https://pypi.org/simple/cython/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/cython/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
ERROR: Could not find a version that satisfies the requirement Cython (from versions: none)
ERROR: No matching distribution found for Cython
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping


  STDERR:

# Command failed: ['/XXX/pyvenv/bin/python3.10', '-m', 'pythonforandroid.toolchain', 'create', '--dist_name=XXX', '--bootstrap=sdl2', '--requirements=python3,kivy==2.1.0,kivymd==1.1.1,asyncio,httpx,gitpython', '--arch=arm64-v8a', '--arch=armeabi-v7a', '--copy-libs', '--color=always', '--storage-dir=/XXX/myapp/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a', '--ndk-api=21', '--ignore-setup-py', '--debug']
# ENVIRONMENT:
#     LDFLAGS = '-L/opt/homebrew/opt/openssl@3/lib'
#     TERM = 'xterm'
#     SHELL = '/bin/zsh'
#     CPPFLAGS = '-I/opt/homebrew/opt/openssl@3/include'
#     TMPDIR = '/var/folders/q7/0x3z245x5_n8zlv02c0s05xm0000gq/T/'
#     SSH_CLIENT = '127.0.0.1 59084 22'
#     SSH_TTY = '/dev/ttys000'
#     USER = 'XXX'
#     SSH_AUTH_SOCK = '/tmp/ssh-X4wfEoo0f8/agent.91569'
#     VIRTUAL_ENV = '/XXX/pyvenv'
#     PATH = '/Users/XXX/.buildozer/android/platform/apache-ant-1.9.4/bin:/Users/XXX/pyvenv/bin:/opt/homebrew/opt/openssl@3/bin:/opt/homebrew/opt/cython/bin:/opt/homebrew/opt/python@3.10/libexec/bin:/opt/homebrew/bin:/Users/XXX/.local/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/homebrew/opt/openjdk/bin'
#     PWD = '/Users/XXX/myapp'
#     JAVA_HOME = '/opt/homebrew/opt/openjdk'
#     PS1 = '(pyvenv) '
#     SHLVL = '3'
#     HOME = '/Users/XXX'
#     LOGNAME = 'XXX'
#     SSH_CONNECTION = '127.0.0.1 59084 127.0.0.1 22'
#     VIRTUAL_ENV_PROMPT = '(pyvenv) '
#     OLDPWD = '/Users/XXX/myapp'
#     _ = '/XXX/pyvenv/bin/buildozer'
#     __CF_USER_TEXT_ENCODING = '0x1F7:0x0:0x0'
#     LC_CTYPE = 'UTF-8'
#     PACKAGES_PATH = '/Users/XXX/.buildozer/android/packages'
#     ANDROIDSDK = '/Users/XXX/.buildozer/android/platform/android-sdk'
#     ANDROIDNDK = '/Users/XXX/.buildozer/android/platform/android-ndk-r25c'
#     ANDROIDAPI = '33'
#     ANDROIDMINAPI = '21'
#
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
```

### What did you expect to happen?

* pip fetches required packages with no ssl problems.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew update
brew upgrade
brew install git python@3.10 openssl pkg-config autoconf automake cmake libtool ccache ant sdl2 sdl2_image sdl2_mixer sdl2_ttf openjdk

python3.10 -m venv --copies /XXX/pyvenv
source /XXX/pyvenv/bin/activate
(pyvenv) which pip
/XXX/pyvenv/bin/pip
(pyvenv) which python
XXX/pyvenv/bin/python
(pyvenv) python --version
Python 3.10.11
(pyvenv) pip --version
pip 23.0.1 from /XXX/pyvenv/lib/python3.10/site-packages/pip (python 3.10)
```

**Comment by MikeMcQuaid** [comment]
This does not look like a Homebrew problem and the reproduction instructions involve non-Homebrew software. You may be able to get help in our discussions forum.
