### ISSUE TITLE
Error: Unexpected platform! when running brew upgrade

### ISSUE THREAD

**Issue by oliverlabs** [Homebrew/brew#15242]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
I am getting the following error when running brew upgrade:
Error: Unexpected platform!
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

brew upgrade

### What happened (include all command output)?

Error: Unexpected platform!

### What did you expect to happen?

brew upgrade

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
type brew upgrade
```

Brew config output:
```shell
HOMEBREW_VERSION: 4.0.13
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9b60fcf7ac3f82fa589a64091376d0663262f8c6
Last commit: 5 days ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7f4ad84b9615b2bcceb751b07a40073cd90e2d88
Core tap last commit: 3 days ago
Core tap branch: master
Core tap JSON: 17 Apr 10:35 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.10 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/bin/ruby
CPU: quad-core 64-bit unknown_0x6_0x8c
Clang: N/A
Git: 2.34.1 => /bin/git
Curl: 7.81.0 => /bin/curl
Kernel: Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 GNU/Linux
OS: Ubuntu 22.04.2 LTS (jammy)
WSL: 2 (Microsoft Store)
Host glibc: 2.35
/usr/bin/gcc: 11.3.0
/usr/bin/ruby: 3.0.2
glibc: N/A
gcc@11: N/A
gcc: N/A
xorg: N/A
```

Brew doctor output:

```shell
Error: Unexpected platform!
```

**Comment by oliverlabs** [comment]
```shell
brew doctor --debug
==> Checking check_access_directories
==> Checking check_brew_git_origin
/usr/bin/env /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/shared/git --version
==> Checking check_casktap_integrity
==> Checking check_coretap_integrity
==> Checking check_deleted_formula
==> Checking check_deprecated_disabled
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading kubectx from API
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading libtirpc from API
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/azure/homebrew-kubelogin/Formula/kubelogin.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading mpdecimal from API
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading ncurses from API
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading libffi from API
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading krb5 from API
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading libuv from API
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading tfenv from API
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading bzip2 from API
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading readline from API
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading libnghttp2 from API
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading helm from API
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading gh from API
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading python@3.11 from API
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/hashicorp/homebrew-tap/Formula/terraform.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading brotli from API
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading c-ares from API
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading gdbm from API
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/azure/homebrew-bicep/Formula/bicep.rb
Error: Unexpected platform!
Error: Kernel.exit
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/kernel.rb:85:in `exit'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/kernel.rb:85:in `odie'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/azure/homebrew-bicep/Formula/bicep.rb:14:in `<class:Bicep>'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/azure/homebrew-bicep/Formula/bicep.rb:1:in `block in load_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:95:in `module_eval'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:95:in `block in load_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:107:in `load_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:127:in `load_formula_from_path'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:414:in `load_file'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:582:in `load_file'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:404:in `klass'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:399:in `get_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:572:in `get_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:670:in `factory'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:718:in `from_keg'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:691:in `from_rack'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1872:in `block in installed'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1871:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1871:in `flat_map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1871:in `installed'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/diagnostic.rb:635:in `check_deprecated_disabled'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/doctor.rb:62:in `block in doctor'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/doctor.rb:55:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/doctor.rb:55:in `doctor'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```
@SMillerDev here's an output

**Comment by gromgit** [comment]
Here's your problem:
https://github.com/Azure/homebrew-bicep/blob/af9d08c313e4429b35caeaf8e6c1363352d19f5e/Formula/bicep.rb#L6-L15

You tapped `azure/bicep`, whose formula explicitly only supports macOS platforms.

Cc @jeskew

**Comment by gromgit** [comment]
> I wonder how the platform compatibility checks passed this one through.

Homebrew polices its own core repos, but can't do much about third-party repos.

> Solved by deleting the following folder: `/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/azure/homebrew-bicep` and rerunning `brew update && brew upgrade`. 
> 
> Funny enough `brew untap azure/bicep` didn't work as it returned the same `odie` error

Ah, that's probably a side effect of how formulae are really Ruby programs of a sort, so quite a few Homebrew operations end up loading and evaluating a ton of connected formulae. `brew untap` probably tried to load all the formulae in that tap to ensure that you're not trying to remove a tap that you still have stuff installed from.
