### ISSUE TITLE
brew bump-formula-pr fail

### ISSUE THREAD

**Issue by matayoshi** [Homebrew/brew#15366]
### `brew doctor` output

```shell
$ brew doctor
Your system is ready to brew.
```
```


### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
$ brew config
HOMEBREW_VERSION: 4.0.16-35-g448bf8b
ORIGIN: https://github.com/Homebrew/brew
HEAD: 448bf8ba9f2e39539d6dc1835ac236b76843b809
Last commit: 3 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 20fc3caac5168fc6f2b78e66177bd49a5f988811
Core tap last commit: 4 hours ago
Core tap branch: master
Core tap JSON: 05 May 10:45 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CLEANUP_MAX_AGE_DAYS: 14
HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS: 14
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_NO_INSTALL_CLEANUP: set
HOMEBREW_NO_INSTALL_FROM_API: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3.1-x86_64
CLT: 14.3.0.0.1.1679647830
Xcode: N/A
```

### What were you trying to do (and why)?

Update node-build formula.

### What happened (include all command output)?

```
$ brew bump-formula-pr --strict node-build --version=4.9.115
==> Downloading https://github.com/nodenv/node-build/archive/v4.9.115.tar.gz
Already downloaded: /Users/matayoshi/Library/Caches/Homebrew/downloads/a329b85d12ba92867ed95de997b0ff825f21fa6c3e41dd3d18078dbb8a66873c--node-build-4.9.115.tar.gz
Warning: Cannot verify integrity of 'a329b85d12ba92867ed95de997b0ff825f21fa6c3e41dd3d18078dbb8a66873c--node-build-4.9.115.tar.gz'.
No checksum was provided.
For your reference, the checksum is:
  sha256 "5082191984141b193a6a2fef85ec0c78de9cb23ecd45c0638821410afd1b2108"
==> replace /https:\/\/github\.com\/nodenv\/node\-build\/archive\/v4\.9\.114\.ta
==> replace "598c90665c862aadc4e0410d439afe30d6640678fe68889b48366bb985f8cbed" w
Error: Parameter 'version': Expected type T.nilable(String), got type Version with hash -1020587535248230963
Caller: /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:113
Definition: /usr/local/Homebrew/Library/Homebrew/utils/pypi.rb:136
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/configuration.rb:296:in `call_validation_error_handler_default'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/configuration.rb:303:in `call_validation_error_handler'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:187:in `report_error'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:116:in `block in validate_call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/signature.rb:211:in `block in each_args_value_type'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/signature.rb:206:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/signature.rb:206:in `each_args_value_type'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:113:in `validate_call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/_methods.rb:270:in `block in _on_method_added'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb:327:in `bump_formula_pr'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### What did you expect to happen?

I expected brew to create a PR.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ brew livecheck --installed --newer-only
icu4c: 72.1 ==> 73.1
cURL failed without a detectable error
Error: libzip: Unable to get versions
node-build: 4.9.114 ==> 4.9.115
```

```
$ brew bump-formula-pr --strict node-build --version=4.9.115 --debug
 --verbose
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/node-build.rb
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/bin/bundle clean
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/git --version
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.16-35-g448bf8b\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.3.1\)\ curl/7.87.0 --header Accept-Language:\ en --retry 3 --location https://api.github.com/search/issues\?q=node-build\+is\%3Apr\+repo\%3AHomebrew\%2Fhomebrew-core\+state\%3Aopen\+in\%3Atitle\&per_page=100 --header Accept:\ application/vnd.github\+json --write-out '
'\%\{http_code\} --header Authorization:\ token\ ****** --header X-GitHub-Api-Version:2022-11-28 --dump-header /private/tmp/github_api_headers20230505-24424-1if16g5
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.16-35-g448bf8b\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.3.1\)\ curl/7.87.0 --header Accept-Language:\ en --retry 3 --location https://api.github.com/search/issues\?q=node-build\+4.9.115\+is\%3Apr\+repo\%3AHomebrew\%2Fhomebrew-core\+state\%3Aclosed\+in\%3Atitle\&per_page=100 --header Accept:\ application/vnd.github\+json --write-out '
'\%\{http_code\} --header Authorization:\ token\ ****** --header X-GitHub-Api-Version:2022-11-28 --dump-header /private/tmp/github_api_headers20230505-24424-13zv2x5
==> Downloading https://github.com/nodenv/node-build/archive/v4.9.115.tar.gz
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.16-35-g448bf8b\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.3.1\)\ curl/7.87.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://github.com/nodenv/node-build/archive/v4.9.115.tar.gz
Already downloaded: /Users/matayoshi/Library/Caches/Homebrew/downloads/a329b85d12ba92867ed95de997b0ff825f21fa6c3e41dd3d18078dbb8a66873c--node-build-4.9.115.tar.gz
==> Verifying checksum for 'a329b85d12ba92867ed95de997b0ff825f21fa6c3e41dd3d18078dbb8a66873c--node-build-4.9.115.tar.gz'
Warning: Cannot verify integrity of 'a329b85d12ba92867ed95de997b0ff825f21fa6c3e41dd3d18078dbb8a66873c--node-build-4.9.115.tar.gz'.
No checksum was provided.
For your reference, the checksum is:
  sha256 "5082191984141b193a6a2fef85ec0c78de9cb23ecd45c0638821410afd1b2108"
==> replace /https:\/\/github\.com\/nodenv\/node\-build\/archive\/v4\.9\.114\.tar\.gz/ with "https://github.com/nodenv/node-build/archive/v4.9.115.tar.gz"
==> replace "598c90665c862aadc4e0410d439afe30d6640678fe68889b48366bb985f8cbed" with "5082191984141b193a6a2fef85ec0c78de9cb23ecd45c0638821410afd1b2108"
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaContentsLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/node-build.rb
Error: Parameter 'version': Expected type T.nilable(String), got type Version with hash 932904781389018878
Caller: /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:113
Definition: /usr/local/Homebrew/Library/Homebrew/utils/pypi.rb:136
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/configuration.rb:296:in `call_validation_error_handler_default'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/configuration.rb:303:in `call_validation_error_handler'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:187:in `report_error'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:116:in `block in validate_call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/signature.rb:211:in `block in each_args_value_type'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/signature.rb:206:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/signature.rb:206:in `each_args_value_type'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:113:in `validate_call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/_methods.rb:270:in `block in _on_method_added'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb:327:in `bump_formula_pr'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```
```

**Comment by dawidd6** [comment]
Looks like this PR introduced a regression https://github.com/Homebrew/brew/pull/15326.

**Comment by carlocab** [comment]
Yup. It's also broken Homebrew/core CI. Mind opening a revert?

**Comment by dawidd6** [comment]
I think I have a fix for that, instead of a revert :slightly_smiling_face:.

**Comment by dawidd6** [comment]
Nevertheless the tap syntax job is broken too :/

https://github.com/Homebrew/homebrew-core/actions/runs/4892972572/jobs/8735365498?pr=130235

**Comment by matayoshi** [comment]
Thank for the fix!
