### ISSUE TITLE
`brew livecheck` on Sparkle formula with `sparkle:version=""` errors with: comparison of Array with Array failed

### ISSUE THREAD

**Issue by gibfahn** [Homebrew/brew#15436]
### `brew doctor` output

```shell
❯ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: The filesystem on /System/Volumes/Data appears to be case-sensitive.
The default macOS filesystem is case-insensitive. Please report any apparent problems.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
❯ brew config
HOMEBREW_VERSION: 4.0.18-18-g64259a4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 64259a420b666744dffb126a79781520bd266fc6
Last commit: 10 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 104cb4666786f23b369096a4cc85b0d43fed2a01
Core tap last commit: 24 minutes ago
Core tap branch: master
Core tap JSON: 15 May 16:30 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BAT_THEME: TwoDark
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 12.0.5 build 1205
Git: 2.38.1 => /usr/local/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3.1-x86_64
CLT: 12.5.0.22.9
Xcode: N/A
```

### What were you trying to do (and why)?

Trying to livecheck a cask that uses Sparkle.

### What happened (include all command output)?

```console
❯ brew livecheck --newer-only <formula>
Error: <formula>: comparison of Array with Array failed
No newer upstream versions.
```

Full stack trace:

```
/opt/homebrew/Library/Homebrew/livecheck/strategy/sparkle.rb:149:in `sort_by'
/opt/homebrew/Library/Homebrew/livecheck/strategy/sparkle.rb:149:in `versions_from_content'
/opt/homebrew/Library/Homebrew/livecheck/strategy/sparkle.rb:195:in `find_versions'
/opt/homebrew/Library/Homebrew/livecheck/livecheck.rb:751:in `block in latest_version'
/opt/homebrew/Library/Homebrew/livecheck/livecheck.rb:683:in `each'
/opt/homebrew/Library/Homebrew/livecheck/livecheck.rb:683:in `each_with_index'
/opt/homebrew/Library/Homebrew/livecheck/livecheck.rb:683:in `latest_version'
/opt/homebrew/Library/Homebrew/livecheck/livecheck.rb:278:in `block in run_checks'
/opt/homebrew/Library/Homebrew/livecheck/livecheck.rb:218:in `map'
/opt/homebrew/Library/Homebrew/livecheck/livecheck.rb:218:in `with_index'
/opt/homebrew/Library/Homebrew/livecheck/livecheck.rb:218:in `run_checks'
/opt/homebrew/Library/Homebrew/dev-cmd/livecheck.rb:122:in `livecheck'
/opt/homebrew/Library/Homebrew/brew.rb:98:in `<main>'
```

Minimal repro:

```console
❯ brew ruby -r bundle_version -e 'Homebrew::BundleVersion.new("1", nil) < Homebrew::BundleVersion.new("2", nil)'
-e:1:in `<': comparison of Homebrew::BundleVersion with Homebrew::BundleVersion failed (ArgumentError)
	from -e:1:in `<main>'
```

### What did you expect to happen?

This worked before commit a1efaf1864049977d7d90f32e5ff1e897cf57d96 , I assume due to the null version file.

This probably needs some comparison code copied from there, but unfortunately I don't know enough ruby to know what is missing.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
I don't know a public cask that has a nil version, so can't give repro steps. But I have a sanitised `releases.rss` file that reproduces the issue:

<details><summary><code>releases.rss</code></summary>


<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0" xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle"  xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>MyApp Changelog</title>
    <link>https://myorg.com/apps/myapp</link>
    <description>Most recent changes with links to updates.</description>
    <language>en</language>
      <item>
        <title>Version 1</title>
        <description>
          <![CDATA[No release notes]]>
        </description>
        <sparkle:releaseNotesLink>
          https://myorg.com/apps/myapp/releases?style=sparkle
        </sparkle:releaseNotesLink>
        <pubDate>Wed, 06, Apr 2016 07:26:18 +0000</pubDate>
        <enclosure
          url="https://myorg.com/apps/myapp/download?version=1"
          sparkle:version=""
          sparkle:shortVersionString="1"
          type="application/octet-stream"
          length="1366983"
        />
      </item>
      <item>
        <title>Version 2</title>
        <description>
          <![CDATA[No release notes]]>
        </description>
        <sparkle:releaseNotesLink>
          https://myorg.com/apps/myapp/releases?style=sparkle
        </sparkle:releaseNotesLink>
        <pubDate>Wed, 06, Apr 2016 07:26:18 +0000</pubDate>
        <enclosure
          url="https://myorg.com/apps/myapp/download?version=2"
          sparkle:version=""
          sparkle:shortVersionString="2"
          type="application/octet-stream"
          length="1367129"
        />
      </item>
      <item>
        <title>Version 3</title>
        <description>
          <![CDATA[No release notes]]>
        </description>
        <sparkle:releaseNotesLink>
          https://myorg.com/apps/myapp/releases?style=sparkle
        </sparkle:releaseNotesLink>
        <pubDate>Wed, 06, Apr 2016 07:26:18 +0000</pubDate>
        <enclosure
          url="https://myorg.com/apps/myapp/download?version=3"
          sparkle:version=""
          sparkle:shortVersionString="3"
          type="application/octet-stream"
          length="1374291"
        />
      </item>
      <item>
        <title>Version 4</title>
        <description>
          <![CDATA[No release notes]]>
        </description>
        <sparkle:releaseNotesLink>
          https://myorg.com/apps/myapp/releases?style=sparkle
        </sparkle:releaseNotesLink>
        <pubDate>Wed, 06, Apr 2016 07:26:18 +0000</pubDate>
        <enclosure
          url="https://myorg.com/apps/myapp/download?version=4"
          sparkle:version=""
          sparkle:shortVersionString="4"
          type="application/octet-stream"
          length="1394915"
        />
      </item>
      <item>
        <title>Version 5</title>
        <description>
          <![CDATA[No release notes]]>
        </description>
        <sparkle:releaseNotesLink>
          https://myorg.com/apps/myapp/releases?style=sparkle
        </sparkle:releaseNotesLink>
        <pubDate>Wed, 06, Apr 2016 07:26:18 +0000</pubDate>
        <enclosure
          url="https://myorg.com/apps/myapp/download?version=5"
          sparkle:version=""
          sparkle:shortVersionString="5"
          type="application/octet-stream"
          length="1394940"
        />
      </item>
  </channel>
</rss>


</details>
```

**Comment by gibfahn** [comment]
cc/ @reitermarkus as I believe this regressed in https://github.com/Homebrew/brew/pull/15336
