### ISSUE TITLE
Failing brew doctor and brew remove

### ISSUE THREAD

**Issue by marcinaylien** [Homebrew/brew#15454]
### `brew doctor` output

```shell
Error: Unexpected run command:
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/service.rb:571:in `deserialize'
/opt/homebrew/Library/Homebrew/formulary.rb:260:in `block in load_formula_from_api'
/opt/homebrew/Library/Homebrew/formulary.rb:149:in `initialize'
/opt/homebrew/Library/Homebrew/formulary.rb:149:in `new'
/opt/homebrew/Library/Homebrew/formulary.rb:149:in `load_formula_from_api'
/opt/homebrew/Library/Homebrew/formulary.rb:632:in `load_from_api'
/opt/homebrew/Library/Homebrew/formulary.rb:623:in `klass'
/opt/homebrew/Library/Homebrew/formulary.rb:403:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:663:in `factory'
/opt/homebrew/Library/Homebrew/formulary.rb:711:in `from_keg'
/opt/homebrew/Library/Homebrew/formulary.rb:684:in `from_rack'
/opt/homebrew/Library/Homebrew/diagnostic.rb:717:in `block in check_for_unreadable_installed_formula'
/opt/homebrew/Library/Homebrew/diagnostic.rb:716:in `each'
/opt/homebrew/Library/Homebrew/diagnostic.rb:716:in `check_for_unreadable_installed_formula'
/opt/homebrew/Library/Homebrew/cmd/doctor.rb:60:in `block in doctor'
/opt/homebrew/Library/Homebrew/cmd/doctor.rb:53:in `each'
/opt/homebrew/Library/Homebrew/cmd/doctor.rb:53:in `doctor'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.18
ORIGIN: https://github.com/Homebrew/brew
HEAD: b0dc84b117f54f6b18e0528b95477c54e409ebdd
Last commit: 5 days ago
Core tap JSON: 18 May 11:55 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 14.0.3 build 1403
Git: 2.40.1 => /opt/homebrew/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3.1-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

I wanted to remove a freshly installed cask of dbeaver-community. However, as I was unable to run it (that app is not signed by a developer and my Mac refuses to run it), I wanted to remove it with `brew remove dbeaver-community`. However, removing fails with similar exception as `brew doctor`:
```
Error: Unexpected run command:
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/service.rb:571:in `deserialize'
/opt/homebrew/Library/Homebrew/formulary.rb:260:in `block in load_formula_from_api'
/opt/homebrew/Library/Homebrew/formulary.rb:149:in `initialize'
/opt/homebrew/Library/Homebrew/formulary.rb:149:in `new'
/opt/homebrew/Library/Homebrew/formulary.rb:149:in `load_formula_from_api'
/opt/homebrew/Library/Homebrew/formulary.rb:632:in `load_from_api'
/opt/homebrew/Library/Homebrew/formulary.rb:623:in `klass'
/opt/homebrew/Library/Homebrew/formulary.rb:403:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:663:in `factory'
/opt/homebrew/Library/Homebrew/dependency.rb:42:in `to_formula'
/opt/homebrew/Library/Homebrew/cask_dependent.rb:30:in `block in runtime_dependencies'
/opt/homebrew/Library/Homebrew/cask_dependent.rb:30:in `each'
/opt/homebrew/Library/Homebrew/cask_dependent.rb:30:in `flat_map'
/opt/homebrew/Library/Homebrew/cask_dependent.rb:30:in `runtime_dependencies'
/opt/homebrew/Library/Homebrew/installed_dependents.rb:52:in `block in find_some_installed_dependents'
/opt/homebrew/Library/Homebrew/installed_dependents.rb:46:in `each'
/opt/homebrew/Library/Homebrew/installed_dependents.rb:46:in `find_some_installed_dependents'
/opt/homebrew/Library/Homebrew/uninstall.rb:109:in `check_for_dependents'
/opt/homebrew/Library/Homebrew/uninstall.rb:102:in `handle_unsatisfied_dependents'
/opt/homebrew/Library/Homebrew/uninstall.rb:12:in `uninstall_kegs'
/opt/homebrew/Library/Homebrew/cmd/uninstall.rb:60:in `uninstall'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>
```

### What happened (include all command output)?

As mentioned above, removing the cask failed. I wanted to check out what's wrong, but brew doctor is broken, too.
I tried reinstalling brew - it succeeds but doesn't solve the problem.

### What did you expect to happen?

I expected brew remove and brew doctor work.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
I have no idea if that will reproduce the error. But this is what I did today:
brew update
brew upgrade
...
upgrading podman failed with:

==> Purging files for version 1.0.0 of Cask podman-desktop
Error: podman-desktop: Unexpected run command:
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/service.rb:571:in `deserialize'
/opt/homebrew/Library/Homebrew/formulary.rb:260:in `block in load_formula_from_api'
/opt/homebrew/Library/Homebrew/formulary.rb:149:in `initialize'
/opt/homebrew/Library/Homebrew/formulary.rb:149:in `new'
/opt/homebrew/Library/Homebrew/formulary.rb:149:in `load_formula_from_api'
/opt/homebrew/Library/Homebrew/formulary.rb:632:in `load_from_api'
/opt/homebrew/Library/Homebrew/formulary.rb:623:in `klass'
/opt/homebrew/Library/Homebrew/formulary.rb:403:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:663:in `factory'
/opt/homebrew/Library/Homebrew/formula.rb:1949:in `[]'
/opt/homebrew/Library/Homebrew/utils/topological_hash.rb:26:in `block (2 levels) in graph_package_dependencies'
/opt/homebrew/Library/Homebrew/utils/topological_hash.rb:26:in `map'
/opt/homebrew/Library/Homebrew/utils/topological_hash.rb:26:in `block in graph_package_dependencies'
/opt/homebrew/Library/Homebrew/utils/topological_hash.rb:20:in `each'
/opt/homebrew/Library/Homebrew/utils/topological_hash.rb:20:in `graph_package_dependencies'
/opt/homebrew/Library/Homebrew/cask/installer.rb:293:in `collect_cask_and_formula_dependencies'
/opt/homebrew/Library/Homebrew/cask/installer.rb:322:in `cask_and_formula_dependencies'
/opt/homebrew/Library/Homebrew/cask/installer.rb:265:in `satisfy_dependencies'
/opt/homebrew/Library/Homebrew/cask/installer.rb:71:in `fetch'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:194:in `upgrade_cask'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:115:in `block in upgrade_casks'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:114:in `each'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:114:in `upgrade_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:253:in `upgrade_outdated_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:137:in `upgrade'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

then I installed dbeaver...

brew install dbeaver-community
brew remove dbeaver-community

which failed as mentioned above, then I run 

brew doctor

which fails, too
```

**Comment by marcinaylien** [comment]
It looks like that the issue is related to https://github.com/Homebrew/homebrew-core/issues/131284, because applying the mentioned change it the Ruby code solved the problem.
