### ISSUE TITLE
brew fetch error - undefined method `full_token' for #<Cask> 

### ISSUE THREAD

**Issue by angryjonny** [Homebrew/brew#15474]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.19-7-ga29b22f
ORIGIN: https://github.com/Homebrew/brew
HEAD: a29b22f1a2e12621a6139f72dc70575b5619d086
Last commit: 4 hours ago
Core tap JSON: 22 May 17:12 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_blizzard_avalanche
Clang: 14.0.0 build 1400
Git: 2.40.1 => /opt/homebrew/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 12.6.6-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
Rosetta 2: false
```

### What were you trying to do (and why)?

`brew fetch cask`

### What happened (include all command output)?

```
Error: undefined method `full_token' for #<Cask slack>
Did you mean?  full_name
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/cmd/fetch.rb:162:in `block in fetch'
/opt/homebrew/Library/Homebrew/cmd/fetch.rb:94:in `each'
/opt/homebrew/Library/Homebrew/cmd/fetch.rb:94:in `fetch'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### What did you expect to happen?

For `brew fetch` to work as expected.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Any attempt to run `brew fetch` resulted in the error. But I did edit `/opt/homebrew/Library/Homebrew/cmd/fetch.rb:162` from full_token to full_name and reran the commmand with success.
```

**Comment by angryjonny** [comment]
Any attempt to run `brew fetch` resulted in the error. But I did edit `/opt/homebrew/Library/Homebrew/cmd/fetch.rb:162` from full_token to full_name and reran the command with success.

**Comment by carlocab** [comment]
Looks like https://github.com/Homebrew/brew/commit/486c3765ced95f6432e2de22566269e9f87a3cfb.
