### ISSUE TITLE
Yarn Berry - Cannot create or tap git repo

### ISSUE THREAD

**Issue by helpdesk-at-REVREBEL** [Homebrew/brew#15504]
### `brew doctor` output

```shell
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/formula.rb:297:in `validate_attributes!'
/usr/local/Homebrew/Library/Homebrew/formula.rb:222:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:437:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:437:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:716:in `factory'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:122:in `load_formula_or_cask'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:80:in `block in to_formulae_and_casks'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:78:in `each'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:78:in `flat_map'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:78:in `to_formulae_and_casks'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:149:in `block in audit'
/usr/local/Homebrew/Library/Homebrew/extend/kernel.rb:498:in `with_env'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:352:in `without_api'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:125:in `audit'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.20-4-gd684472
ORIGIN: https://github.com/Homebrew/brew
HEAD: d684472b13bc04f76891445958b1c91304aaec71
Last commit: 10 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 01c9ef11804758fdbbbb58ff16511b51dde9b34b
Core tap last commit: 4 months ago
Core tap branch: master
Core tap JSON: 01 Jun 02:00 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: mvim
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 14.0.3 build 1403
Git: 2.40.1 => /usr/local/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4-x86_64
CLT: N/A
Xcode: 14.3
```

### What were you trying to do (and why)?

Install Yarn Berry manual since Brew doesn't have it available through regular install 

brew create https://github.com/yarnpkg/berry/archive/refs/tags/@yarnpkg/cli/3.5.1.tar.gz

brew create https://github.com/yarnpkg/berry.git

### What happened (include all command output)?

Please run `brew audit --new yarnpkg-cli-3.5.1` before submitting, thanks.
Editing /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/yarnpkg-cli-3.5.1.rb

Error: Failure while executing; `mvim /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/yarnpkg-cli-3.5.1.rb` exited with 1.

Warning: Cannot verify integrity of 'dd15413a4125b8173424837f4993ced0528d4b40a786cb486db3146408a21396--berry--yarnpkg-cli-3.5.1.tar.gz'.
No checksum was provided.
For your reference, the checksum is:
  sha256 "a3a0684b216de21a11a6dc76427b8490fb9b5fc8d3e88068c28d078238887399"
Please run `brew audit --new @yarnpkg/cli/3.5.1` before submitting, thanks.
Editing /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/homebrew/core/@yarnpkg/cli/3.5.1.rb
Error: Failure while executing; `mvim /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/homebrew/core/@yarnpkg/cli/3.5.1.rb` exited with 1.

### What did you expect to happen?

To install the yarn berry from their git repo.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew tap-new                            master * ] 7:01 PM
Usage: brew tap-new [options] user/repo

Generate the template files for a new tap.

      --no-git                     Don't initialize a Git repository for the
                                   tap.
      --pull-label                 Label name for pull requests ready to be
                                   pulled (default: pr-pull).
      --branch                     Initialize Git repository and setup GitHub
                                   Actions workflows with the specified branch
                                   name (default: main).
      --github-packages            Upload bottles to GitHub Packages.
  -d, --debug                      Display any debugging information.
  -q, --quiet                      Make some output more quiet.
  -v, --verbose                    Make some output more verbose.
  -h, --help                       Show this message.

Error: Invalid usage: This command requires exactly 1 tap argument.
zsh_debug/vscode-zsh-debug [ brew tap-new https://github.com/yarnpkg/berry.git --pull-label yarnpkg/core/3.5.1  
Error: Invalid tap name 'https://github.com/yarnpkg/berry.git'
zsh_debug/vscode-zsh-debug [ brew install https://github.com/yarnpkg/berry.git 
Error: Non-checksummed download of berry.git formula file from an arbitrary URL is unsupported! `brew extract` or `brew create` and `brew tap-new` to create a formula file in a tap on GitHub instead.
zsh_debug/vscode-zsh-debug [ brew create https://github.com/yarnpkg/berry.git 
Formula name [berry]: berry
Warning: Version cannot be determined from URL.
You'll need to add an explicit 'version' to the formula.
Please run `brew audit --new berry` before submitting, thanks.
Editing /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/berry.rb
Error: Failure while executing; `mvim /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/berry.rb` exited with 1.
zsh_debug/vscode-zsh-debug [ brew audit --new berry                  master * ] 7:05 PM
Error: invalid attribute for formula 'berry': version (nil)
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/formula.rb:297:in `validate_attributes!'
/usr/local/Homebrew/Library/Homebrew/formula.rb:222:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:437:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:437:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:716:in `factory'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:122:in `load_formula_or_cask'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:80:in `block in to_formulae_and_casks'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:78:in `each'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:78:in `flat_map'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:78:in `to_formulae_and_casks'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:149:in `block in audit'
/usr/local/Homebrew/Library/Homebrew/extend/kernel.rb:498:in `with_env'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:352:in `without_api'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:125:in `audit'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
zsh_debug/vscode-zsh-debug [ brew create https://github.com/yarnpkg/berry/tree/%40yarnpkg/core/3.5.1                                     
Formula name [3.5.1]: 3.5.1
==> Downloading https://github.com/yarnpkg/berry/tree/%40yarnpkg/core/3.5.1
#-#O#-  #                                                                              
Warning: Cannot verify integrity of '58e8d91c208d25480b394143602607aaf0508ce825e17c8fc05f981824f85bfe--3.5.1'.
No checksum was provided.
For your reference, the checksum is:
  sha256 "c7a387a2a1ac58852eecab2809a3ce56a38518d5a418e7b6d70ed44b3412b5f9"
Please run `brew audit --new 3.5.1` before submitting, thanks.
Editing /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/3.5.1.rb
Error: Failure while executing; `mvim /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/3.5.1.rb` exited with 1.
zsh_debug/vscode-zsh-debug [ brew audit --new 3.5.1                  master * ] 7:06 PM
Error: 3.5.1: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/3.5.1.rb:4: syntax error, unexpected '<', expecting '.' or &. or :: or '['
class 351 < Formula
          ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/3.5.1.rb:33: syntax error, unexpected end, expecting end-of-input
zsh_debug/vscode-zsh-debug [ brew create https://github.com/yarnpkg/berry/archive/refs/tags/@yarnpkg/cli/3.5.1.tar.gz
Formula name [3.5.1]: 
Error: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/3.5.1.rb already exists
zsh_debug/vscode-zsh-debug [ brew remove 3.5.1                       master * ] 7:10 PM
Error: 3.5.1: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/3.5.1.rb:4: syntax error, unexpected '<', expecting '.' or &. or :: or '['
class 351 < Formula
          ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/3.5.1.rb:33: syntax error, unexpected end, expecting end-of-input
zsh_debug/vscode-zsh-debug [ brew create https://github.com/yarnpkg/berry/archive/refs/tags/@yarnpkg/cli/3.5.1.tar.gz
Formula name [3.5.1]: @yarnpkg/cli/3.5.1
==> Downloading https://github.com/yarnpkg/berry/archive/refs/tags/@yarnpkg/cli/3.5.1.ta
==> Downloading from https://codeload.github.com/yarnpkg/berry/tar.gz/refs/tags/%40yarnp
                         #      #     #      # -=O=-                                   
Warning: Cannot verify integrity of 'dd15413a4125b8173424837f4993ced0528d4b40a786cb486db3146408a21396--berry--yarnpkg-cli-3.5.1.tar.gz'.
No checksum was provided.
For your reference, the checksum is:
  sha256 "a3a0684b216de21a11a6dc76427b8490fb9b5fc8d3e88068c28d078238887399"
Please run `brew audit --new @yarnpkg/cli/3.5.1` before submitting, thanks.
Editing /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/homebrew/core/@yarnpkg/cli/3.5.1.rb
Error: Failure while executing; `mvim /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/homebrew/core/@yarnpkg/cli/3.5.1.rb` exited with 1.
zsh_debug/vscode-zsh-debug [ brew audit --new @yarnpkg/cli/3.5.1     master * ] 7:12 PM
Error: No available formula or cask with the name "@yarnpkg/cli/3.5.1".
Please tap it and then try again: brew tap @yarnpkg/cli
zsh_debug/vscode-zsh-debug [ brew tap @yarnpkg/cli                   master * ] 7:12 PM
==> Tapping @yarnpkg/cli
Cloning into '/usr/local/Homebrew/Library/Taps/@yarnpkg/homebrew-cli'...
remote: Repository not found.
fatal: repository 'https://github.com/@yarnpkg/homebrew-cli/' not found
Error: Failure while executing; `git clone https://github.com/@yarnpkg/homebrew-cli /usr/local/Homebrew/Library/Taps/@yarnpkg/homebrew-cli --origin=origin --template=` exited with 128.
zsh_debug/vscode-zsh-debug [ brew create https://github.com/yarnpkg/berry.git
Formula name [berry]: yarnpkg-cli-3.5.1                   
Warning: Version cannot be determined from URL.
You'll need to add an explicit 'version' to the formula.
Please run `brew audit --new yarnpkg-cli-3.5.1` before submitting, thanks.
Editing /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/yarnpkg-cli-3.5.1.rb
Error: Failure while executing; `mvim /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/yarnpkg-cli-3.5.1.rb` exited with 1.
zsh_debug/vscode-zsh-debug [ brew audit brew audit --new yarnpkg-cli-3.5.1
Error: No available formula with the name "brew". Did you mean brev?
zsh_debug/vscode-zsh-debug [ brew audit brew audit --new yarnpkg-cli-3.5.1brew audit --new yarnpkg-cli-3.5.1
zsh_debug/vscode-zsh-debug [ brew audit --new yarnpkg-cli-3.5.1      master * ] 7:17 PM
Error: invalid attribute for formula 'yarnpkg-cli-3.5.1': version (nil)
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/formula.rb:297:in `validate_attributes!'
/usr/local/Homebrew/Library/Homebrew/formula.rb:222:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:437:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:437:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:716:in `factory'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:122:in `load_formula_or_cask'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:80:in `block in to_formulae_and_casks'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:78:in `each'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:78:in `flat_map'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:78:in `to_formulae_and_casks'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:149:in `block in audit'
/usr/local/Homebrew/Library/Homebrew/extend/kernel.rb:498:in `with_env'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:352:in `without_api'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:125:in `audit'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
zsh_debug/vscode-zsh-debug [ brew config                             master * ] 7:17 PM
HOMEBREW_VERSION: 4.0.20-4-gd684472
ORIGIN: https://github.com/Homebrew/brew
HEAD: d684472b13bc04f76891445958b1c91304aaec71
Last commit: 10 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 01c9ef11804758fdbbbb58ff16511b51dde9b34b
Core tap last commit: 4 months ago
Core tap branch: master
Core tap JSON: 01 Jun 02:00 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: mvim
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 14.0.3 build 1403
Git: 2.40.1 => /usr/local/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4-x86_64
CLT: N/A
Xcode: 14.3
```

**Comment by MikeMcQuaid** [comment]
> brew create https://github.com/yarnpkg/berry/archive/refs/tags/@yarnpkg/cli/3.5.1.tar.gz
> 
> brew create https://github.com/yarnpkg/berry.git

These are developer commands. We cannot support installing things from a formula you've created. If you'd like help: open a discussion in Homebrew/discussions.
