### ISSUE TITLE
Cannot install mp4v2 package

### ISSUE THREAD

**Issue by cxbig** [Homebrew/brew#1557]
I found a bug that I cannot install package `mp4v2`:

### Try 1:
```sh
$ brew install mp4v2
==> Downloading https://mp4v2.googlecode.com/files/mp4v2-2.0.0.tar.bz2

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "mp4v2"
Download failed: https://mp4v2.googlecode.com/files/mp4v2-2.0.0.tar.bz2
```

### Try 2 & 3 (Different binary url):
```sh
$ brew install mp4v2 --build-from-source https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/mp4v2/mp4v2-2.0.0.tar.bz2
# or
$ brew install mp4v2 --build-from-source http://pkgs.fedoraproject.org/repo/pkgs/libmp4v2/mp4v2-2.0.0.tar.bz2/c91f06711225b34b4c192c9114887b14/mp4v2-2.0.0.tar.bz2

######################################################################## 100.0%
Error: /Users/cxbig/Library/Caches/Homebrew/Formula/mp4v2-2.0.0.tar.bz2:1: invalid multibyte char (UTF-8)
/Users/cxbig/Library/Caches/Homebrew/Formula/mp4v2-2.0.0.tar.bz2:1: syntax error, unexpected end-of-input
BZh91AY&SY�VC8+�����o������������...
           ^
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:91:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:146:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:78:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:215:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:18:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:102:in `install'
/usr/local/Library/Homebrew/brew.rb:87:in `<main>'
```

Any suggestion?

**Comment by MikeMcQuaid** [comment]
> https://git.io/brew-troubleshooting

Sorry but you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by cxbig** [comment]
macOS : 10.12.1 (16B2555)
```
$ brew update
Already up-to-date.
$ brew update
Already up-to-date.
$ brew -v
Homebrew 0.9.9 (git revision 06fe3; last commit 2016-08-10)
Homebrew/homebrew-core (git revision a059; last commit 2016-08-10)
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
```

**Comment by MikeMcQuaid** [comment]
Run `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update` and then `brew update --force` again.

**Comment by MikeMcQuaid** [comment]
Also, in future please file formulae issues to homebrew/homebrew-core.
