### ISSUE TITLE
Problems installing opencv under Sierra

### ISSUE THREAD

**Issue by ythinker** [Homebrew/brew#1560]
Is this what is the reason？
Opencv installed in mac 10.12 suggested:

```
➜  ~ brew install opencv
Error: uninitialized constant Formulary::FormulaNamespaceb312684b3dcc6a6783f5511168d9e5cb::Opencv::DevelopmentTools
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Taps/homebrew/homebrew-science/opencv.rb:16:in `block in <class:Opencv>'
/usr/local/Library/Homebrew/formula.rb:1740:in `instance_eval'
/usr/local/Library/Homebrew/formula.rb:1740:in `stable'
/usr/local/Library/Taps/homebrew/homebrew-science/opencv.rb:8:in `<class:Opencv>'
/usr/local/Library/Taps/homebrew/homebrew-science/opencv.rb:3:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:23:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:23:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:36:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:85:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:76:in `klass'
/usr/local/Library/Homebrew/formulary.rb:72:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:207:in `factory'
/usr/local/Library/Homebrew/formulary.rb:352:in `find_with_priority'
/usr/local/Library/Homebrew/extend/ARGV.rb:20:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:45:in `install'
/usr/local/Library/brew.rb:85:in `<main>'

```

**Comment by MikeMcQuaid** [comment]
Please report this to homebrew/science, read https://git.io/brew-troubleshooting before creating future issues and fill out the issue template rather than just deleting it.
