### ISSUE TITLE
Unable to run brew install

### ISSUE THREAD

**Issue by MoienBowen** [Homebrew/brew#15748]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config
HOMEBREW_VERSION: 4.1.1-17-gd0f7d2b
ORIGIN: https://github.com/Homebrew/brew
HEAD: d0f7d2b01173d3f01107329af3064c9c9a5ab5c5
Last commit: 38 minutes ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: fa275261158e72f1f39d14c5561f8f4d6d15bdf2
Core tap last commit: 66 minutes ago
Core tap branch: master
Core tap JSON: 25 Jul 08:10 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: ["--appdir=/Users/bliu/Applications"]
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.Xj9UffUnRm/org.xquartz:0
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4.1-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: N/A
Rosetta 2: false
```

```
$ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

```
$ brew outdated --cask --greedy --verbose
zoom (5.15.3.20121) != 5.15.5.20753
```

```
brew install zoom
brew install --cask zoom
brew install --force zoom
```

### What happened (include all command output)?

The install command returns:
```
==> Downloading https://formulae.brew.sh/api/cask.jws.json
######################################################################### 100.0%
Error: uninitialized constant Cask::Upgrade
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/cmd/install.rb:248:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### What did you expect to happen?

The install should run correctly.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
As above.
```

**Comment by carlocab** [comment]
What's the output of `brew install --debug --verbose zoom`?

**Comment by MoienBowen** [comment]
> What's the output of `brew install --debug --verbose zoom`?

```
$ brew install --debug --verbose zoom
==> Downloading https://formulae.brew.sh/api/formula.jws.json
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/4.1.1-17-gd0f7d2b\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.4.1\)\ curl/7.88.1 --header Accept-Language:\ en --fail --remote-time --output /Users/bliu/Library/Caches/Homebrew/api/formula.jws.json --location --time-cond /Users/bliu/Library/Caches/Homebrew/api/formula.jws.json --compressed --speed-limit 100 --speed-time 5 https://formulae.brew.sh/api/formula.jws.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 3865k  100 3865k    0     0  6509k      0 --:--:-- --:--:-- --:--:-- 6562k
==> Downloading https://formulae.brew.sh/api/cask.jws.json
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/4.1.1-17-gd0f7d2b\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.4.1\)\ curl/7.88.1 --header Accept-Language:\ en --fail --remote-time --output /Users/bliu/Library/Caches/Homebrew/api/cask.jws.json --location --time-cond /Users/bliu/Library/Caches/Homebrew/api/cask.jws.json --compressed --speed-limit 100 --speed-time 5 https://formulae.brew.sh/api/cask.jws.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  994k  100  994k    0     0  7324k      0 --:--:-- --:--:-- --:--:-- 7591k
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading zoom
Error: uninitialized constant Cask::Upgrade
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/cmd/install.rb:248:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```
