### ISSUE TITLE
`bump --cask`: Error: no implicit conversion of nil into String

### ISSUE THREAD

**Issue by osalbahr** [Homebrew/brew#15825]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.1.3-58-g3f49592
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3f4959218105749e219087a53fb136d22d86f071
Last commit: 8 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6d08f69a9ed2356ada55f3771de29585335dfa3c
Core tap last commit: 55 minutes ago
Core tap branch: master
Core tap JSON: 05 Aug 00:37 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit kabylake
Clang: 14.0.3 build 1403
Git: 2.41.0 => /usr/local/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5-x86_64
CLT: 14.3.1.0.1.1683849156
Xcode: N/A
```

### What were you trying to do (and why)?

Bump casks.

### What happened (include all command output)?

```console
% brew update && brew update && brew bump --cask
Already up-to-date.
Already up-to-date.
==> Querying outdated casks from Repology
343 outdated casks found

Error: no implicit conversion of nil into String
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:84:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:84:in `Pathname'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:84:in `can_load?'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:175:in `can_load?'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:420:in `block in for'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:419:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:419:in `for'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:406:in `load'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump.rb:297:in `block (2 levels) in retrieve_versions_by_arch'
/usr/local/Homebrew/Library/Homebrew/simulate_system.rb:29:in `with'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `validate_call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/_methods.rb:270:in `block in _on_method_added'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump.rb:289:in `block in retrieve_versions_by_arch'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump.rb:288:in `each'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump.rb:288:in `retrieve_versions_by_arch'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump.rb:383:in `retrieve_and_display_info_and_open_pr'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump.rb:193:in `block (2 levels) in handle_api_response'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump.rb:167:in `each'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump.rb:167:in `each_with_index'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump.rb:167:in `block in handle_api_response'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump.rb:158:in `each'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump.rb:158:in `each_with_index'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump.rb:158:in `handle_api_response'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump.rb:85:in `bump'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### What did you expect to happen?

No errors.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
bump --cask
- OR -
brew bump --open-pr --cask
```

**Comment by osalbahr** [comment]
https://github.com/Homebrew/brew/blob/3f4959218105749e219087a53fb136d22d86f071/Library/Homebrew/cask/cask_loader.rb#L81-L86

It looks like `ref` was null, not sure why though. Some more logs:

```console
% brew bump --cask --verbose --debug
==> Querying outdated casks from Repology
==> Paginating Repology API page: 1
/usr/bin/env /usr/local/opt/curl/bin/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.3-58-g3f49592\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.5\)\ curl/8.1.2 --header Accept-Language:\ en --retry 3 https://repology.org/api/v1/projects/\?inrepo=homebrew_casks\&outdated=1 --silent
==> Paginating Repology API page: 2
/usr/bin/env /usr/local/opt/curl/bin/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.3-58-g3f49592\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.5\)\ curl/8.1.2 --header Accept-Language:\ en --retry 3 https://repology.org/api/v1/projects/mob/\?inrepo=homebrew_casks\&outdated=1 --silent
==> Paginating Repology API page: 3
/usr/bin/env /usr/local/opt/curl/bin/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.3-58-g3f49592\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.5\)\ curl/8.1.2 --header Accept-Language:\ en --retry 3 https://repology.org/api/v1/projects/zulu-openjdk/\?inrepo=homebrew_casks\&outdated=1 --silent
343 outdated casks found

/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading aegisub
Error: no implicit conversion of nil into String
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:84:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:84:in `Pathname'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:84:in `can_load?'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:175:in `can_load?'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:420:in `block in for'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:419:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:419:in `for'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:406:in `load'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump.rb:297:in `block (2 levels) in retrieve_versions_by_arch'
/usr/local/Homebrew/Library/Homebrew/simulate_system.rb:29:in `with'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `validate_call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/_methods.rb:270:in `block in _on_method_added'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump.rb:289:in `block in retrieve_versions_by_arch'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump.rb:288:in `each'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump.rb:288:in `retrieve_versions_by_arch'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump.rb:383:in `retrieve_and_display_info_and_open_pr'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump.rb:193:in `block (2 levels) in handle_api_response'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump.rb:167:in `each'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump.rb:167:in `each_with_index'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump.rb:167:in `block in handle_api_response'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump.rb:158:in `each'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump.rb:158:in `each_with_index'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump.rb:158:in `handle_api_response'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump.rb:85:in `bump'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

**Comment by apainintheneck** [comment]
`brew bump` should avoid loading casks from the API. It looks like what happened here was that it loaded a cask from the API and then tried to reference it's source file which doesn't exist. I'm not sure why it tried to do that though.

https://github.com/Homebrew/brew/blob/3f4959218105749e219087a53fb136d22d86f071/Library/Homebrew/dev-cmd/bump.rb#L51

This specific block of code seems to be brand new though. #15763 got merged in yesterday.

CC: @razvanazamfirei since that PR might be related.

**Comment by apainintheneck** [comment]
Ah, I think I understand what's happening here. Basically the `without_api` option in the arg parser only affects how named args are loaded. For example, if you ran `brew bump jrnl`, then the `jrnl` formula would not be loaded from the API.

However all other times where we load formulae or casks will just default to user preferences meaning we'll probably use the API since that's the default now.

We should probably wrap the cask and formula loading we're doing here in `Homebrew.with_no_api_env`. Probably best to just wrap each loop.

**Comment by osalbahr** [comment]
Interesting. Yeah, it works fine if I supply args.

```console
$ brew bump --cask ghidra
==> ghidra
Current cask version:     10.3.2,20230711
Latest livecheck version: 10.3.2,20230711
Latest Repology version:  10.3.2
Open pull requests:       none
Closed pull requests:     none
$ brew bump ghidra
==> ghidra
Current cask version:     10.3.2,20230711
Latest livecheck version: 10.3.2,20230711
Latest Repology version:  10.3.2
Open pull requests:       none
Closed pull requests:     none
```

**Comment by apainintheneck** [comment]
This should fix it. @osalbahr it'd be great if you could try out https://github.com/Homebrew/brew/pull/15826 when you get the chance.
