### ISSUE TITLE
Error: undefined method `curl_output' for GitHub:Module

### ISSUE THREAD

**Issue by Qyriad** [Homebrew/brew#15965]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.1.8-24-ge93d560
ORIGIN: https://github.com/Homebrew/brew
HEAD: e93d56008d5a7d5769d78e749726fb011b393f5c
Last commit: 3 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 47067c42aaa99711f8babbc73bdd7d39c36ae05c
Core tap last commit: 3 hours ago
Core tap branch: master
Core tap JSON: 05 Sep 17:06 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BOOTSNAP: set
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY_INSTALL_TIMES: set
HOMEBREW_EDITOR: /usr/local/bin/nvim
HOMEBREW_MAKE_JOBS: 6
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: hexa-core 64-bit kabylake
Clang: 14.0.3 build 1403
Git: 2.42.0 => /usr/local/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4.1-x86_64
CLT: 14.3.1.0.1.1683849156
Xcode: 14.3.1
```

### What were you trying to do (and why)?

Upgrade `HEAD` formulae, with `brew upgrade --formulae --fetch-HEAD` (non-HEAD upgrades work fine).

### What happened (include all command output)?

Homebrew errored with:
```
Error: undefined method `curl_output' for GitHub:Module
Do not report this issue until you've run `brew update` and tried again.
/usr/local/Homebrew/Library/Homebrew/utils/github.rb:731:in `last_commit'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:1117:in `commit_outdated?'
/usr/local/Homebrew/Library/Homebrew/formula.rb:660:in `block in head_version_outdated?'
/usr/local/Homebrew/Library/Homebrew/context.rb:72:in `with_context'
/usr/local/Homebrew/Library/Homebrew/formula.rb:659:in `head_version_outdated?'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1512:in `outdated_kegs'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1571:in `outdated?'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `validate_call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:89:in `block in create_validator_slow'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:163:in `block in upgrade_outdated_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:162:in `select'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:162:in `upgrade_outdated_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:136:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```
Attached is the same error, but with `--debug`: [homebrew_curl_error.log](https://github.com/Homebrew/brew/files/12527937/homebrew_curl_error.log)

### What did you expect to happen?

Formulae to upgrade correctly, or an error message indicating which formula caused the error.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ brew upgrade --formulae --fetch-HEAD
```

**Comment by Qyriad** [comment]
Thanks!
