### ISSUE TITLE
setupterm 'The terminal could not be found' error seen in CI jobs, since vendored Ruby 3.1 update

### ISSUE THREAD

**Issue by timsutton** [Homebrew/brew#16299]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.1.23
ORIGIN: https://github.com/Homebrew/brew
HEAD: fc259153591a309e2b6fee6f971eb61b16a3b6c0
Last commit: 26 hours ago
Core tap JSON: 05 Dec 21:30 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

We use brew as part of a Jenkins job to build AWS EC2 Mac AMI images, which run on Mac instances as part of a Mac CI cluster. This job runs daily. It works like this:

From a linux-based Jenkins worker, [Packer](https://github.com/hashicorp/packer) builds a template which launches an EC2 Mac (Ventura) instance. Packer SSHes into the host as a default user which already exists on the system. It then creates a new user named `build`, and interacts with the brew environment via that user using a function that looks like this:

```
function sudo_run_as_build() {
  sudo -u build --login "$@"
}
```

The only net-new formula we actually install using this wrapped function is `ansible`, which of course pulls in a bunch of Python dependencies. Most of our other commands are to just report on the `brew` environment, run a `brew doctor` for our own sanity checks, etc.

### What happened (include all command output)?

What _seems_ to happen is that at some point during the `ansible` dependencies installation of `python@3.12`, it fails due to an error from `reline`:
```
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/reline/terminfo.rb:106:in `setupterm': The terminal could not be found, or that it is a generic type, having too little information for curses applications to run. (Reline::Terminfo::TerminfoError)
```

The full output from our Jenkins -> Packer log:
```
16:17:34  ==> amazon-ebs.macos: + sudo_run_as_build brew update
16:17:34  ==> amazon-ebs.macos: + sudo -u build --login brew update
16:17:37  ==> amazon-ebs.macos: ==> Homebrew's analytics have entirely moved to our InfluxDB instance in the EU.
16:17:37  ==> amazon-ebs.macos: We gather less data than before and have destroyed all Google Analytics data:
16:17:37  ==> amazon-ebs.macos:   [https://docs.brew.sh/Analytics](https://docs.brew.sh/Analytics%1B[0m)
16:17:37  ==> amazon-ebs.macos: Please reconsider re-enabling analytics to help our volunteer maintainers with:
16:17:37  ==> amazon-ebs.macos:   brew analytics on
16:17:37  ==> amazon-ebs.macos: ==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
16:17:37  ==> amazon-ebs.macos:   [https://github.com/Homebrew/brew#donations](https://github.com/Homebrew/brew#donations%1B[0m)
16:17:37  ==> amazon-ebs.macos:
16:17:37  ==> amazon-ebs.macos: Already up-to-date.
16:17:38  ==> amazon-ebs.macos: + sudo_run_as_build brew --env
16:17:38  ==> amazon-ebs.macos: + sudo -u build --login brew --env
16:17:43      amazon-ebs.macos: export CC="clang"
16:17:43      amazon-ebs.macos: export CXX="clang\+\+"
16:17:43      amazon-ebs.macos: export OBJC="clang"
16:17:43      amazon-ebs.macos: export OBJCXX="clang\+\+"
16:17:43      amazon-ebs.macos: export HOMEBREW_CC="clang"
16:17:43  ==> amazon-ebs.macos: + sudo_run_as_build brew doctor
16:17:43  ==> amazon-ebs.macos: + sudo -u build --login brew doctor
16:17:43      amazon-ebs.macos: export HOMEBREW_CXX="clang\+\+"
16:17:43      amazon-ebs.macos: export MAKEFLAGS="-j8"
16:17:43      amazon-ebs.macos: export CMAKE_PREFIX_PATH="/opt/homebrew"
16:17:43      amazon-ebs.macos: export CMAKE_INCLUDE_PATH="/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers"
16:17:43      amazon-ebs.macos: export CMAKE_LIBRARY_PATH="/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries"
16:17:43      amazon-ebs.macos: export PKG_CONFIG_LIBDIR="/usr/lib/pkgconfig:/opt/homebrew/Library/Homebrew/os/mac/pkgconfig/13"
16:17:43      amazon-ebs.macos: export HOMEBREW_GIT="git"
16:17:43      amazon-ebs.macos: export HOMEBREW_SDKROOT="/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk"
16:17:43      amazon-ebs.macos: export PATH="/opt/homebrew/Library/Homebrew/shims/mac/super:/usr/bin:/bin:/usr/sbin:/sbin"
16:18:39      amazon-ebs.macos: Your system is ready to brew.
16:18:39  ==> amazon-ebs.macos: + install_formulas_as_build_user
16:18:39  ==> amazon-ebs.macos: + sudo_run_as_build brew install ansible
16:18:39  ==> amazon-ebs.macos: + sudo -u build --login brew install ansible
16:18:39      amazon-ebs.macos: ==> Downloading [https://ghcr.io/v2/homebrew/core/ansible/manifests/9.0.1](https://ghcr.io/v2/homebrew/core/ansible/manifests/9.0.1%1B[0m)
16:18:39      amazon-ebs.macos: ==> Fetching dependencies for ansible: python-certifi, python-cryptography, python-dateutil, python-markupsafe, python-jinja, python-lxml, python-packaging, python-pyparsing, python-pytz, python@3.12, libyaml and pyyaml
16:18:39      amazon-ebs.macos: ==> Downloading [https://ghcr.io/v2/homebrew/core/python-certifi/manifests/2023.11.17](https://ghcr.io/v2/homebrew/core/python-certifi/manifests/2023.11.17%1B[0m)
16:18:39      amazon-ebs.macos: ==> Fetching python-certifi
16:18:39      amazon-ebs.macos: ==> Downloading [https://ghcr.io/v2/homebrew/core/python-certifi/blobs/sha256:4f79fb464210d1710ee1308d49b29c31e126e7189561cf9ab149afc4f9a6e9b6](https://ghcr.io/v2/homebrew/core/python-certifi/blobs/sha256:4f79fb464210d1710ee1308d49b29c31e126e7189561cf9ab149afc4f9a6e9b6%1B[0m)
16:18:39      amazon-ebs.macos: ==> Downloading [https://ghcr.io/v2/homebrew/core/python-cryptography/manifests/41.0.7](https://ghcr.io/v2/homebrew/core/python-cryptography/manifests/41.0.7%1B[0m)
16:18:39      amazon-ebs.macos: ==> Fetching python-cryptography
16:18:39      amazon-ebs.macos: ==> Downloading [https://ghcr.io/v2/homebrew/core/python-cryptography/blobs/sha256:004366df7d5e15d5eb4f38be694fb8e16d45750e490066a69ed4cf04f7aaf6d1](https://ghcr.io/v2/homebrew/core/python-cryptography/blobs/sha256:004366df7d5e15d5eb4f38be694fb8e16d45750e490066a69ed4cf04f7aaf6d1%1B[0m)
16:18:39      amazon-ebs.macos: ==> Downloading [https://ghcr.io/v2/homebrew/core/python-dateutil/manifests/2.8.2-1](https://ghcr.io/v2/homebrew/core/python-dateutil/manifests/2.8.2-1%1B[0m)
16:18:39      amazon-ebs.macos: ==> Fetching python-dateutil
16:18:39      amazon-ebs.macos: ==> Downloading [https://ghcr.io/v2/homebrew/core/python-dateutil/blobs/sha256:c9e043c7c21453f6613a65aae1b44a61ced3a69cf4152e6a83374d0b483acc96](https://ghcr.io/v2/homebrew/core/python-dateutil/blobs/sha256:c9e043c7c21453f6613a65aae1b44a61ced3a69cf4152e6a83374d0b483acc96%1B[0m)
16:18:39      amazon-ebs.macos: ==> Downloading [https://ghcr.io/v2/homebrew/core/python-markupsafe/manifests/2.1.3_1](https://ghcr.io/v2/homebrew/core/python-markupsafe/manifests/2.1.3_1%1B[0m)
16:18:39      amazon-ebs.macos: ==> Fetching python-markupsafe
16:18:39      amazon-ebs.macos: ==> Downloading [https://ghcr.io/v2/homebrew/core/python-markupsafe/blobs/sha256:284a01f2b18ada3cbc87e859e1ef222697f90be4d22b267be74af14c82121eb6](https://ghcr.io/v2/homebrew/core/python-markupsafe/blobs/sha256:284a01f2b18ada3cbc87e859e1ef222697f90be4d22b267be74af14c82121eb6%1B[0m)
16:18:39      amazon-ebs.macos: ==> Downloading [https://ghcr.io/v2/homebrew/core/python-jinja/manifests/3.1.2](https://ghcr.io/v2/homebrew/core/python-jinja/manifests/3.1.2%1B[0m)
16:18:39      amazon-ebs.macos: ==> Fetching python-jinja
16:18:39      amazon-ebs.macos: ==> Downloading [https://ghcr.io/v2/homebrew/core/python-jinja/blobs/sha256:13464ec67985d66fdccb5177f1c7de1d6da35f5cac38c317852c0de009fe6586](https://ghcr.io/v2/homebrew/core/python-jinja/blobs/sha256:13464ec67985d66fdccb5177f1c7de1d6da35f5cac38c317852c0de009fe6586%1B[0m)
16:18:39      amazon-ebs.macos: ==> Downloading [https://ghcr.io/v2/homebrew/core/python-lxml/manifests/4.9.3-2](https://ghcr.io/v2/homebrew/core/python-lxml/manifests/4.9.3-2%1B[0m)
16:18:39      amazon-ebs.macos: ==> Fetching python-lxml
16:18:39      amazon-ebs.macos: ==> Downloading [https://ghcr.io/v2/homebrew/core/python-lxml/blobs/sha256:fc539279b955f01d0906f6bc5ddce1bf77401697f90c1dec94dc45d24c3bf91a](https://ghcr.io/v2/homebrew/core/python-lxml/blobs/sha256:fc539279b955f01d0906f6bc5ddce1bf77401697f90c1dec94dc45d24c3bf91a%1B[0m)
16:18:39      amazon-ebs.macos: ==> Downloading [https://ghcr.io/v2/homebrew/core/python-packaging/manifests/23.2_1](https://ghcr.io/v2/homebrew/core/python-packaging/manifests/23.2_1%1B[0m)
16:18:39      amazon-ebs.macos: ==> Fetching python-packaging
16:18:39      amazon-ebs.macos: ==> Downloading [https://ghcr.io/v2/homebrew/core/python-packaging/blobs/sha256:abddebc5027f9113b74b85bfe98002f2c5a1e23ed8591baa9929a79731879df6](https://ghcr.io/v2/homebrew/core/python-packaging/blobs/sha256:abddebc5027f9113b74b85bfe98002f2c5a1e23ed8591baa9929a79731879df6%1B[0m)
16:18:39      amazon-ebs.macos: ==> Downloading [https://ghcr.io/v2/homebrew/core/python-pyparsing/manifests/3.1.1_1](https://ghcr.io/v2/homebrew/core/python-pyparsing/manifests/3.1.1_1%1B[0m)
16:18:39      amazon-ebs.macos: ==> Fetching python-pyparsing
16:18:39      amazon-ebs.macos: ==> Downloading [https://ghcr.io/v2/homebrew/core/python-pyparsing/blobs/sha256:b7c4a8ef0422d4a6fc0f4af53c1c3d36b7c3b7df6f6742a6f662eabe78051066](https://ghcr.io/v2/homebrew/core/python-pyparsing/blobs/sha256:b7c4a8ef0422d4a6fc0f4af53c1c3d36b7c3b7df6f6742a6f662eabe78051066%1B[0m)
16:18:39      amazon-ebs.macos: ==> Downloading [https://ghcr.io/v2/homebrew/core/python-pytz/manifests/2023.3.post1_1](https://ghcr.io/v2/homebrew/core/python-pytz/manifests/2023.3.post1_1%1B[0m)
16:18:39      amazon-ebs.macos: ==> Fetching python-pytz
16:18:39      amazon-ebs.macos: ==> Downloading [https://ghcr.io/v2/homebrew/core/python-pytz/blobs/sha256:e33230c3b829cd914d847704f7edfd18ccc971bda97faee2d10cf3c91d9f8658](https://ghcr.io/v2/homebrew/core/python-pytz/blobs/sha256:e33230c3b829cd914d847704f7edfd18ccc971bda97faee2d10cf3c91d9f8658%1B[0m)
16:18:39      amazon-ebs.macos: ==> Downloading [https://ghcr.io/v2/homebrew/core/python/3.12/manifests/3.12.0-1](https://ghcr.io/v2/homebrew/core/python/3.12/manifests/3.12.0-1%1B[0m)
16:18:39      amazon-ebs.macos: ==> Fetching python@3.12
16:18:39      amazon-ebs.macos: ==> Downloading [https://ghcr.io/v2/homebrew/core/python/3.12/blobs/sha256:af08d7f69c5944fa5ef56bd791f1f162cb9435f870108e2fdbd6cbd335c276d4](https://ghcr.io/v2/homebrew/core/python/3.12/blobs/sha256:af08d7f69c5944fa5ef56bd791f1f162cb9435f870108e2fdbd6cbd335c276d4%1B[0m)
16:18:39      amazon-ebs.macos: ==> Downloading [https://ghcr.io/v2/homebrew/core/libyaml/manifests/0.2.5](https://ghcr.io/v2/homebrew/core/libyaml/manifests/0.2.5%1B[0m)
16:18:39      amazon-ebs.macos: ==> Fetching libyaml
16:18:39      amazon-ebs.macos: ==> Downloading [https://ghcr.io/v2/homebrew/core/libyaml/blobs/sha256:11239e8f5066c6d0d0718208d4eab518da00c7289f33c9c76c0a09ba5c0417c9](https://ghcr.io/v2/homebrew/core/libyaml/blobs/sha256:11239e8f5066c6d0d0718208d4eab518da00c7289f33c9c76c0a09ba5c0417c9%1B[0m)
16:18:39      amazon-ebs.macos: ==> Downloading [https://ghcr.io/v2/homebrew/core/pyyaml/manifests/6.0.1_1](https://ghcr.io/v2/homebrew/core/pyyaml/manifests/6.0.1_1%1B[0m)
16:18:40      amazon-ebs.macos: ==> Fetching pyyaml
16:18:40      amazon-ebs.macos: ==> Downloading [https://ghcr.io/v2/homebrew/core/pyyaml/blobs/sha256:eb0cb94ff9dc6ac7926c1ee71ccdc42dc844ad3ab949b9105456cf131c25027d](https://ghcr.io/v2/homebrew/core/pyyaml/blobs/sha256:eb0cb94ff9dc6ac7926c1ee71ccdc42dc844ad3ab949b9105456cf131c25027d%1B[0m)
16:18:40      amazon-ebs.macos: ==> Fetching ansible
16:18:40      amazon-ebs.macos: ==> Downloading [https://ghcr.io/v2/homebrew/core/ansible/blobs/sha256:8a685deee13ab6b6acb58fa89647b775a0146f1c0c77741827d5e3ea701521f9](https://ghcr.io/v2/homebrew/core/ansible/blobs/sha256:8a685deee13ab6b6acb58fa89647b775a0146f1c0c77741827d5e3ea701521f9%1B[0m)
16:18:42      amazon-ebs.macos: ==> Installing dependencies for ansible: python-certifi, python-cryptography, python-dateutil, python-markupsafe, python-jinja, python-lxml, python-packaging, python-pyparsing, python-pytz, python@3.12, libyaml and pyyaml
16:18:42      amazon-ebs.macos: ==> Installing ansible dependency: python-certifi
16:18:42      amazon-ebs.macos: ==> Downloading [https://ghcr.io/v2/homebrew/core/python-certifi/manifests/2023.11.17](https://ghcr.io/v2/homebrew/core/python-certifi/manifests/2023.11.17%1B[0m)
16:18:42      amazon-ebs.macos: Already downloaded: /Users/build/Library/Caches/Homebrew/downloads/dbe322159e601dd5783523959110fea4b391921f5ef7e48d9f53ec5d4512aade--python-certifi-2023.11.17.bottle_manifest.json
16:18:42      amazon-ebs.macos: ==> Pouring python-certifi--2023.11.17.arm64_ventura.bottle.tar.gz
16:18:42      amazon-ebs.macos: ����  /opt/homebrew/Cellar/python-certifi/2023.11.17: 43 files, 33.8KB
16:18:42      amazon-ebs.macos: ==> Installing ansible dependency: python-cryptography
16:18:42      amazon-ebs.macos: ==> Downloading [https://ghcr.io/v2/homebrew/core/python-cryptography/manifests/41.0.7](https://ghcr.io/v2/homebrew/core/python-cryptography/manifests/41.0.7%1B[0m)
16:18:42      amazon-ebs.macos: Already downloaded: /Users/build/Library/Caches/Homebrew/downloads/29d1c6634f14177bb7bc5b1a7420c8339ba6a8efbf7dd27dbf27648d44bd4ebb--python-cryptography-41.0.7.bottle_manifest.json
16:18:42      amazon-ebs.macos: ==> Pouring python-cryptography--41.0.7.arm64_ventura.bottle.tar.gz
16:18:42      amazon-ebs.macos: ����  /opt/homebrew/Cellar/python-cryptography/41.0.7: 211 files, 7.2MB
16:18:42      amazon-ebs.macos: ==> Installing ansible dependency: python-dateutil
16:18:42      amazon-ebs.macos: ==> Downloading [https://ghcr.io/v2/homebrew/core/python-dateutil/manifests/2.8.2-1](https://ghcr.io/v2/homebrew/core/python-dateutil/manifests/2.8.2-1%1B[0m)
16:18:42      amazon-ebs.macos: Already downloaded: /Users/build/Library/Caches/Homebrew/downloads/e550131925667be77fb15f47affdc11335cc9e47f97c70e8d7ebffd9fa60be09--python-dateutil-2.8.2-1.bottle_manifest.json
16:18:42      amazon-ebs.macos: ==> Pouring python-dateutil--2.8.2.arm64_ventura.bottle.1.tar.gz
16:18:42      amazon-ebs.macos: ����  /opt/homebrew/Cellar/python-dateutil/2.8.2: 62 files, 961.6KB
16:18:42      amazon-ebs.macos: ==> Installing ansible dependency: python-markupsafe
16:18:42      amazon-ebs.macos: ==> Downloading [https://ghcr.io/v2/homebrew/core/python-markupsafe/manifests/2.1.3_1](https://ghcr.io/v2/homebrew/core/python-markupsafe/manifests/2.1.3_1%1B[0m)
16:18:42      amazon-ebs.macos: Already downloaded: /Users/build/Library/Caches/Homebrew/downloads/7663f3e7f5e9849c7aae06708f9fa971c70ac6ab868f39284c7602ff0f37221a--python-markupsafe-2.1.3_1.bottle_manifest.json
16:18:42      amazon-ebs.macos: ==> Pouring python-markupsafe--2.1.3_1.arm64_ventura.bottle.tar.gz
16:18:42      amazon-ebs.macos: ����  /opt/homebrew/Cellar/python-markupsafe/2.1.3_1: 47 files, 237.3KB
16:18:42      amazon-ebs.macos: ==> Installing ansible dependency: python-jinja
16:18:42      amazon-ebs.macos: ==> Downloading [https://ghcr.io/v2/homebrew/core/python-jinja/manifests/3.1.2](https://ghcr.io/v2/homebrew/core/python-jinja/manifests/3.1.2%1B[0m)
16:18:42      amazon-ebs.macos: Already downloaded: /Users/build/Library/Caches/Homebrew/downloads/72796423afc9a2efba69c7a6c39561ebc03ea84679ec1f97cdaf2249f094b88b--python-jinja-3.1.2.bottle_manifest.json
16:18:42      amazon-ebs.macos: ==> Pouring python-jinja--3.1.2.arm64_ventura.bottle.tar.gz
16:18:42      amazon-ebs.macos: ����  /opt/homebrew/Cellar/python-jinja/3.1.2: 75 files, 1005.3KB
16:18:42      amazon-ebs.macos: ==> Installing ansible dependency: python-lxml
16:18:42      amazon-ebs.macos: ==> Downloading [https://ghcr.io/v2/homebrew/core/python-lxml/manifests/4.9.3-2](https://ghcr.io/v2/homebrew/core/python-lxml/manifests/4.9.3-2%1B[0m)
16:18:42      amazon-ebs.macos: Already downloaded: /Users/build/Library/Caches/Homebrew/downloads/798947131d4d8550594b3b1fa7644e92eb517f7f07974308f0682e71a8ea442c--python-lxml-4.9.3-2.bottle_manifest.json
16:18:42      amazon-ebs.macos: ==> Pouring python-lxml--4.9.3.arm64_ventura.bottle.2.tar.gz
16:18:43      amazon-ebs.macos: ����  /opt/homebrew/Cellar/python-lxml/4.9.3: 303 files, 15.2MB
16:18:43      amazon-ebs.macos: ==> Installing ansible dependency: python-packaging
16:18:43      amazon-ebs.macos: ==> Downloading [https://ghcr.io/v2/homebrew/core/python-packaging/manifests/23.2_1](https://ghcr.io/v2/homebrew/core/python-packaging/manifests/23.2_1%1B[0m)
16:18:43      amazon-ebs.macos: Already downloaded: /Users/build/Library/Caches/Homebrew/downloads/b4720c6b9e8f88804fc0b8bf8127418c0670c3b7ce80b4f87ebd30e57b0cb8d8--python-packaging-23.2_1.bottle_manifest.json
16:18:43      amazon-ebs.macos: ==> Pouring python-packaging--23.2_1.arm64_ventura.bottle.tar.gz
16:18:43      amazon-ebs.macos: ����  /opt/homebrew/Cellar/python-packaging/23.2_1: 79 files, 539.2KB
16:18:43      amazon-ebs.macos: ==> Installing ansible dependency: python-pyparsing
16:18:43      amazon-ebs.macos: ==> Downloading [https://ghcr.io/v2/homebrew/core/python-pyparsing/manifests/3.1.1_1](https://ghcr.io/v2/homebrew/core/python-pyparsing/manifests/3.1.1_1%1B[0m)
16:18:43      amazon-ebs.macos: Already downloaded: /Users/build/Library/Caches/Homebrew/downloads/3fcfc51b9ff9c0602d8fd25382c63ef5805245e59fbc79709e9ac52ca99e72ae--python-pyparsing-3.1.1_1.bottle_manifest.json
16:18:43      amazon-ebs.macos: ==> Pouring python-pyparsing--3.1.1_1.arm64_ventura.bottle.tar.gz
16:18:43      amazon-ebs.macos: ����  /opt/homebrew/Cellar/python-pyparsing/3.1.1_1: 62 files, 1.3MB
16:18:43      amazon-ebs.macos: ==> Installing ansible dependency: python-pytz
16:18:43      amazon-ebs.macos: ==> Downloading [https://ghcr.io/v2/homebrew/core/python-pytz/manifests/2023.3.post1_1](https://ghcr.io/v2/homebrew/core/python-pytz/manifests/2023.3.post1_1%1B[0m)
16:18:43      amazon-ebs.macos: Already downloaded: /Users/build/Library/Caches/Homebrew/downloads/a3d3eb717497fef0ae26394666f905972a908f299976daf4c8868423205634f0--python-pytz-2023.3.post1_1.bottle_manifest.json
16:18:43      amazon-ebs.macos: ==> Pouring python-pytz--2023.3.post1_1.arm64_ventura.bottle.tar.gz
16:18:44      amazon-ebs.macos: ����  /opt/homebrew/Cellar/python-pytz/2023.3.post1_1: 1,855 files, 2.9MB
16:18:44      amazon-ebs.macos: ==> Installing ansible dependency: python@3.12
16:18:44      amazon-ebs.macos: ==> Downloading [https://ghcr.io/v2/homebrew/core/python/3.12/manifests/3.12.0-1](https://ghcr.io/v2/homebrew/core/python/3.12/manifests/3.12.0-1%1B[0m)
16:18:44      amazon-ebs.macos: Already downloaded: /Users/build/Library/Caches/Homebrew/downloads/1d0e36aa721b7d8acd766516670f97049b43de5aeca6a81a88fbc208ff4eff5f--python@3.12-3.12.0-1.bottle_manifest.json
16:18:44      amazon-ebs.macos: ==> Pouring python@3.12--3.12.0.arm64_ventura.bottle.1.tar.gz
16:18:49      amazon-ebs.macos: /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/reline/terminfo.rb:106:in `setupterm': The terminal could not be found, or that it is a generic type, having too little information for curses applications to run. (Reline::Terminfo::TerminfoError)
16:18:49      amazon-ebs.macos: 	from /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/reline/ansi.rb:21:in `<class:ANSI>'
16:18:49      amazon-ebs.macos: 	from /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/reline/ansi.rb:6:in `<top (required)>'
16:18:49      amazon-ebs.macos: 	from /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/reline.rb:580:in `require'
16:18:49      amazon-ebs.macos: 	from /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/reline.rb:580:in `<top (required)>'
16:18:49      amazon-ebs.macos: 	from /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/irb.rb:13:in `require'
16:18:49      amazon-ebs.macos: 	from /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/irb.rb:13:in `<top (required)>'
16:18:49      amazon-ebs.macos: 	from /opt/homebrew/Library/Homebrew/debrew/irb.rb:4:in `require'
16:18:49      amazon-ebs.macos: 	from /opt/homebrew/Library/Homebrew/debrew/irb.rb:4:in `<top (required)>'
16:18:49      amazon-ebs.macos: 	from /opt/homebrew/Library/Homebrew/debrew.rb:5:in `require'
16:18:49      amazon-ebs.macos: 	from /opt/homebrew/Library/Homebrew/debrew.rb:5:in `<top (required)>'
16:18:49      amazon-ebs.macos: 	from /opt/homebrew/Library/Homebrew/postinstall.rb:9:in `require'
16:18:49      amazon-ebs.macos: 	from /opt/homebrew/Library/Homebrew/postinstall.rb:9:in `<main>'
16:18:49  ==> amazon-ebs.macos: Warning: The post-install step did not complete successfully
16:18:49      amazon-ebs.macos: You can try again using:
16:18:49      amazon-ebs.macos:   brew postinstall python@3.12
16:18:49      amazon-ebs.macos: ==> Summary
16:18:49      amazon-ebs.macos: ����  /opt/homebrew/Cellar/python@3.12/3.12.0: 2,995 files, 60.4MB
16:18:49      amazon-ebs.macos: ==> Installing ansible dependency: libyaml
16:18:49      amazon-ebs.macos: ==> Downloading [https://ghcr.io/v2/homebrew/core/libyaml/manifests/0.2.5](https://ghcr.io/v2/homebrew/core/libyaml/manifests/0.2.5%1B[0m)
16:18:49      amazon-ebs.macos: Already downloaded: /Users/build/Library/Caches/Homebrew/downloads/5f6b0af1730aa1bc02f8021c90ed7ffe988eeba95eec83e6c828f77332ba6406--libyaml-0.2.5.bottle_manifest.json
16:18:49      amazon-ebs.macos: ==> Pouring libyaml--0.2.5.arm64_ventura.bottle.tar.gz
16:18:49      amazon-ebs.macos: ����  /opt/homebrew/Cellar/libyaml/0.2.5: 10 files, 351.3KB
16:18:49      amazon-ebs.macos: ==> Installing ansible dependency: pyyaml
16:18:49      amazon-ebs.macos: ==> Downloading [https://ghcr.io/v2/homebrew/core/pyyaml/manifests/6.0.1_1](https://ghcr.io/v2/homebrew/core/pyyaml/manifests/6.0.1_1%1B[0m)
16:18:49      amazon-ebs.macos: Already downloaded: /Users/build/Library/Caches/Homebrew/downloads/bb167293fae0bea9e7a2acd7496bdc04de8fd1d22a0d4c554a42477cda37397a--pyyaml-6.0.1_1.bottle_manifest.json
16:18:49      amazon-ebs.macos: ==> Pouring pyyaml--6.0.1_1.arm64_ventura.bottle.tar.gz
16:18:49      amazon-ebs.macos: ����  /opt/homebrew/Cellar/pyyaml/6.0.1_1: 86 files, 1.5MB
16:18:49      amazon-ebs.macos: ==> Installing ansible
16:18:49      amazon-ebs.macos: ==> Pouring ansible--9.0.1.arm64_ventura.bottle.tar.gz
16:19:11      amazon-ebs.macos: ����  /opt/homebrew/Cellar/ansible/9.0.1: 30,126 files, 443.6MB
16:19:11      amazon-ebs.macos: ==> Running `brew cleanup ansible`...
16:19:11      amazon-ebs.macos: Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
16:19:11      amazon-ebs.macos: Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
```

### What did you expect to happen?

The ansible installation command would finish successfully. This was the case with the vendored 2.6 Ruby. However it seems that since the recent change in 4.1.23 to use the newer Ruby 3.1 bundle, it seems to have an issue with the terminal environment.

Wondering if there's any additional environment vars I could for example set here to work around it? I did try and set `HOMEBREW_NO_COLOR` in case that could help bypass any code related to ANSI codes but I suspect I'm either setting it wrong, or it wouldn't have any effect anyway

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
function sudo_run_as_build() {
  sudo -u build --login "$@"
}

sudo_run_as_build brew update || true
sudo_run_as_build brew --env
sudo_run_as_build brew doctor || true
sudo_run_as_build brew install ansible
```
```

**Comment by Bo98** [comment]
Ok, so it seems it is detecting stdout as a TTY so there is some form of terminal. Does `$TERM` equate to `dumb`? Looks like a bug that's fixed in Ruby 3.2: https://github.com/ruby/ruby/commit/59e8569cf938e0e449fd649b564da995ffb67470

Good news though is we can likely workaround it by lazy loading that part of the code to only the parts that need it (i.e. interactive debugging).

**Comment by timsutton** [comment]
Thanks for the response! I can check back early tomorrow when I have access again. I can also then look into testing the brew version off of your branch to test that fix. 🤞🏻

**Comment by Bo98** [comment]
I've tried to reproduce the issue locally but nothing I've tried has managed to so far: setting/unsetting TERM/TERMINFO, sudo, `bash -ic`, ssh localhost, combination of all the previous etc.

With that said, I've merged and released the fix anyway (4.1.24) as I'm confident enough in it. Loading less things is often a benefit on its own anyway.

**Comment by timsutton** [comment]
@Bo98 Just had the chance to re-run our build and confirmed your fix definitely addressed the issue, thanks for the super-quick response! I'll close this issue. ❤️
