### ISSUE TITLE
Error: Directory not empty @ dir_s_rmdir

### ISSUE THREAD

**Issue by mrichman** [Homebrew/brew#16371]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.2.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: ff899e5b3ff6731208564ef502db237e2627e8ba
Last commit: 2 days ago
Core tap JSON: 20 Dec 16:23 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 3.1.4 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 15.0.0 build 1500
Git: 2.43.0 => /usr/local/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.6.1-x86_64
CLT: 15.1.0.0.1.1700200546
Xcode: 15.0.1
```

### What were you trying to do (and why)?

Install/update any cask

### What happened (include all command output)?

```
❯ brew install plexamp --verbose --debug
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading plexamp
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://plexamp.plex.tv/plexamp.plex.tv/desktop/Plexamp-4.9.3.dmg
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.0\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.6.1\)\ curl/8.1.2 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://plexamp.plex.tv/plexamp.plex.tv/desktop/Plexamp-4.9.3.dmg
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.0\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.6.1\)\ curl/8.1.2 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://plexamp.plex.tv/plexamp.plex.tv/desktop/Plexamp-4.9.3.dmg
Already downloaded: /Users/mrkrchm/Library/Caches/Homebrew/downloads/2d00b47bd5bf0c46dc2505afc5be66890926a61670ed65b3c1db8dce2111b8b8--Plexamp-4.9.3.dmg
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /usr/bin/swift -target x86_64-apple-macosx13 /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/mrkrchm/Library/Caches/Homebrew/downloads/2d00b47bd5bf0c46dc2505afc5be66890926a61670ed65b3c1db8dce2111b8b8--Plexamp-4.9.3.dmg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/mrkrchm/Library/Caches/Homebrew/downloads/2d00b47bd5bf0c46dc2505afc5be66890926a61670ed65b3c1db8dce2111b8b8--Plexamp-4.9.3.dmg
==> /Users/mrkrchm/Library/Caches/Homebrew/downloads/2d00b47bd5bf0c46dc2505afc5be66890926a61670ed65b3c1db8dce2111b8b8--Plexamp-4.9.3.dmg is quarantined
==> Verifying checksum for '2d00b47bd5bf0c46dc2505afc5be66890926a61670ed65b3c1db8dce2111b8b8--Plexamp-4.9.3.dmg'
/usr/bin/env hdiutil imageinfo -format /Users/mrkrchm/Library/Caches/Homebrew/downloads/2d00b47bd5bf0c46dc2505afc5be66890926a61670ed65b3c1db8dce2111b8b8--Plexamp-4.9.3.dmg
==> Installing Cask plexamp
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/mrkrchm/Library/Caches/Homebrew/downloads/2d00b47bd5bf0c46dc2505afc5be66890926a61670ed65b3c1db8dce2111b8b8--Plexamp-4.9.3.dmg
/usr/bin/env hdiutil attach -plist -nobrowse -readonly -mountrandom /private/tmp/d20231220-47396-d01lli /Users/mrkrchm/Library/Caches/Homebrew/downloads/2d00b47bd5bf0c46dc2505afc5be66890926a61670ed65b3c1db8dce2111b8b8--Plexamp-4.9.3.dmg
/usr/bin/env find . -print0
/usr/bin/env mkbom -s -i /private/tmp/20231220-47396-ktd7k6.list -- /private/tmp/20231220-47396-jydlg4.bom
/usr/bin/env ditto --bom /private/tmp/20231220-47396-jydlg4.bom -- /private/tmp/d20231220-47396-d01lli/dmg.YyTXIC /private/tmp/d20231220-47396-9uxrho
/usr/bin/env diskutil info -plist /private/tmp/d20231220-47396-d01lli/dmg.YyTXIC
/usr/bin/env diskutil eject /private/tmp/d20231220-47396-d01lli/dmg.YyTXIC
/usr/bin/env diskutil info -plist /private/tmp/d20231220-47396-d01lli/dmg.YyTXIC
/usr/bin/env diskutil eject /private/tmp/d20231220-47396-d01lli/dmg.YyTXIC
/usr/bin/env diskutil unmount force /private/tmp/d20231220-47396-d01lli/dmg.YyTXIC
==> Purging files for version 4.9.3 of Cask plexamp
Error: Directory not empty @ dir_s_rmdir - /private/tmp/d20231220-47396-d01lli
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/fileutils.rb:1440:in `rmdir'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/fileutils.rb:1440:in `block in remove_dir1'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/fileutils.rb:1451:in `platform_support'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/fileutils.rb:1439:in `remove_dir1'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/fileutils.rb:1432:in `remove'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/fileutils.rb:773:in `block in remove_entry'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/fileutils.rb:1489:in `ensure in postorder_traverse'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/fileutils.rb:1489:in `postorder_traverse'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/fileutils.rb:771:in `remove_entry'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/tmpdir.rb:104:in `ensure in mktmpdir'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/tmpdir.rb:104:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/dmg.rb:181:in `mount'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/dmg.rb:171:in `extract_to_dir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:116:in `extract'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:131:in `block in extract_nestedly'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/tmpdir.rb:96:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:128:in `extract_nestedly'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:219:in `extract_primary_container'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:80:in `stage'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:107:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:244:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:233:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:233:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:86:in `<main>'
```

### What did you expect to happen?

Clean install.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew install plexamp --verbose` but this could be any formula. This just started happening a couple of days ago.
```

**Comment by MikeMcQuaid** [comment]
> ### Step-by-step reproduction instructions (by running `brew` commands)
> 
> ```shell
> `brew install plexamp --verbose` but this could be any formula. This just started happening a couple of days ago.
> ```

Just to be clear: this is happening when you install literally any cask? Thanks!

**Comment by mrichman** [comment]
@MikeMcQuaid Yes it's every cask.

**Comment by mrichman** [comment]
Here's another example:

```
❯ brew install todoist --verbose --debug
==> Downloading https://formulae.brew.sh/api/formula.jws.json
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/4.2.0\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.6.1\)\ curl/8.1.2 --header Accept-Language:\ en --fail --remote-time --output /Users/mrkrchm/Library/Caches/Homebrew/api/formula.jws.json --location --time-cond /Users/mrkrchm/Library/Caches/Homebrew/api/formula.jws.json --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.0\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.6.1\)\ curl/8.1.2 --header Accept-Language:\ en --fail --compressed --speed-limit 100 --speed-time 5 https://formulae.brew.sh/api/formula.jws.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4355k  100 4355k    0     0  17.5M      0 --:--:-- --:--:-- --:--:-- 18.2M
==> Downloading https://formulae.brew.sh/api/cask.jws.json
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/4.2.0\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.6.1\)\ curl/8.1.2 --header Accept-Language:\ en --fail --remote-time --output /Users/mrkrchm/Library/Caches/Homebrew/api/cask.jws.json --location --time-cond /Users/mrkrchm/Library/Caches/Homebrew/api/cask.jws.json --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.0\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.6.1\)\ curl/8.1.2 --header Accept-Language:\ en --fail --compressed --speed-limit 100 --speed-time 5 https://formulae.brew.sh/api/cask.jws.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1043k  100 1043k    0     0  7694k      0 --:--:-- --:--:-- --:--:-- 8347k
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading todoist
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.0\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.6.1\)\ curl/8.1.2 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://electron-dl.todoist.com/mac/Todoist-darwin-8.12.1-universal.dmg
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.0\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.6.1\)\ curl/8.1.2 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://electron-dl.todoist.com/mac/Todoist-darwin-8.12.1-universal.dmg
==> Downloading https://electron-dl.todoist.com/mac/Todoist-darwin-8.12.1-universal.dmg
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.0\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.6.1\)\ curl/8.1.2 --header Accept-Language:\ en --fail --retry 3 --remote-time --output /Users/mrkrchm/Library/Caches/Homebrew/downloads/5251835396f2412fbec6f0f1763f771507b789ddeba46e9b74f53531969b1393--Todoist-darwin-8.12.1-universal.dmg.incomplete --location https://electron-dl.todoist.com/mac/Todoist-darwin-8.12.1-universal.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  172M  100  172M    0     0  23.7M      0  0:00:07  0:00:07 --:--:-- 30.2M
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /usr/bin/swift -target x86_64-apple-macosx13 /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/mrkrchm/Library/Caches/Homebrew/downloads/5251835396f2412fbec6f0f1763f771507b789ddeba46e9b74f53531969b1393--Todoist-darwin-8.12.1-universal.dmg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/mrkrchm/Library/Caches/Homebrew/downloads/5251835396f2412fbec6f0f1763f771507b789ddeba46e9b74f53531969b1393--Todoist-darwin-8.12.1-universal.dmg
==> /Users/mrkrchm/Library/Caches/Homebrew/downloads/5251835396f2412fbec6f0f1763f771507b789ddeba46e9b74f53531969b1393--Todoist-darwin-8.12.1-universal.dmg is not quarantined
==> Quarantining /Users/mrkrchm/Library/Caches/Homebrew/downloads/5251835396f2412fbec6f0f1763f771507b789ddeba46e9b74f53531969b1393--Todoist-darwin-8.12.1-universal.dmg
/usr/bin/env /usr/bin/swift -target x86_64-apple-macosx13 /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift /Users/mrkrchm/Library/Caches/Homebrew/downloads/5251835396f2412fbec6f0f1763f771507b789ddeba46e9b74f53531969b1393--Todoist-darwin-8.12.1-universal.dmg https://electron-dl.todoist.com/mac/Todoist-darwin-8.12.1-universal.dmg https://todoist.com/home
==> Verifying checksum for '5251835396f2412fbec6f0f1763f771507b789ddeba46e9b74f53531969b1393--Todoist-darwin-8.12.1-universal.dmg'
/usr/bin/env hdiutil imageinfo -format /Users/mrkrchm/Library/Caches/Homebrew/downloads/5251835396f2412fbec6f0f1763f771507b789ddeba46e9b74f53531969b1393--Todoist-darwin-8.12.1-universal.dmg
==> Installing Cask todoist
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/mrkrchm/Library/Caches/Homebrew/downloads/5251835396f2412fbec6f0f1763f771507b789ddeba46e9b74f53531969b1393--Todoist-darwin-8.12.1-universal.dmg
/usr/bin/env hdiutil attach -plist -nobrowse -readonly -mountrandom /private/tmp/d20231220-54479-xoadf6 /Users/mrkrchm/Library/Caches/Homebrew/downloads/5251835396f2412fbec6f0f1763f771507b789ddeba46e9b74f53531969b1393--Todoist-darwin-8.12.1-universal.dmg
/usr/bin/env find . -print0
/usr/bin/env mkbom -s -i /private/tmp/20231220-54479-3qnery.list -- /private/tmp/20231220-54479-zbatc.bom
/usr/bin/env ditto --bom /private/tmp/20231220-54479-zbatc.bom -- /private/tmp/d20231220-54479-xoadf6/dmg.jUgVAv /private/tmp/d20231220-54479-zn1w08
/usr/bin/env diskutil info -plist /private/tmp/d20231220-54479-xoadf6/dmg.jUgVAv
/usr/bin/env diskutil eject /private/tmp/d20231220-54479-xoadf6/dmg.jUgVAv
/usr/bin/env diskutil info -plist /private/tmp/d20231220-54479-xoadf6/dmg.jUgVAv
/usr/bin/env diskutil eject /private/tmp/d20231220-54479-xoadf6/dmg.jUgVAv
/usr/bin/env diskutil unmount force /private/tmp/d20231220-54479-xoadf6/dmg.jUgVAv
==> Purging files for version 8.12.1 of Cask todoist
Error: Directory not empty @ dir_s_rmdir - /private/tmp/d20231220-54479-xoadf6
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/fileutils.rb:1440:in `rmdir'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/fileutils.rb:1440:in `block in remove_dir1'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/fileutils.rb:1451:in `platform_support'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/fileutils.rb:1439:in `remove_dir1'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/fileutils.rb:1432:in `remove'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/fileutils.rb:773:in `block in remove_entry'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/fileutils.rb:1489:in `ensure in postorder_traverse'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/fileutils.rb:1489:in `postorder_traverse'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/fileutils.rb:771:in `remove_entry'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/tmpdir.rb:104:in `ensure in mktmpdir'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/tmpdir.rb:104:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/dmg.rb:181:in `mount'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/dmg.rb:171:in `extract_to_dir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:116:in `extract'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:131:in `block in extract_nestedly'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/tmpdir.rb:96:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:128:in `extract_nestedly'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:219:in `extract_primary_container'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:80:in `stage'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:107:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:244:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:233:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:233:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:86:in `<main>'

```

**Comment by MikeMcQuaid** [comment]
@mrichman can I see the output of `ls -lha /private/tmp/d20231220-54479-xoadf6` (or whatever the latest directory is) and your current username? Thanks!

**Comment by mrichman** [comment]
```
❯ ls -lha /private/tmp/d20231220-54479-xoadf6
total 0
drwx------@  3 mrkrchm  wheel    96B Dec 20 13:00 .
drwxrwxrwt  27 root     wheel   864B Dec 21 08:51 ..
drwxr-xr-x@  8 mrkrchm  staff   340B Dec 19 16:58 dmg.jUgVAv

❯ whoami
mrkrchm
```

**Comment by MikeMcQuaid** [comment]
No ideas what's going on here. @Homebrew/cask any thoughts or ideas?

**Comment by mrichman** [comment]
A reboot after OS update seems to have fixed it. I'm chalking it up to a macOS bug. Closing.
