### ISSUE TITLE
Error: Calling Formula.sha1 is disabled!

### ISSUE THREAD

**Issue by Naggi-Goishi** [Homebrew/brew#1644]
### Bug reports:

When I try to run, `brew install https://raw.github.com/quantiverge/homebrew-binary/pdftk/pdftk.rb`
it gives me an error like below
```
######################################################################## 100.0%
Error: Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/Users/naggigoishi/Library/Caches/Homebrew/Formula/pdftk.rb:16:in `<class:Pdftk>'
Please report this bug:
  https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Homebrew/utils.rb:85:in `odeprecated'
/usr/local/Homebrew/Library/Homebrew/utils.rb:93:in `odisabled'
/usr/local/Homebrew/Library/Homebrew/compat/sha1.rb:3:in `sha1'
/Users/naggigoishi/Library/Caches/Homebrew/Formula/pdftk.rb:16:in `<class:Pdftk>'
/Users/naggigoishi/Library/Caches/Homebrew/Formula/pdftk.rb:12:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:97:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:153:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:241:in `factory'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:43:in `block in formulae'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:41:in `map'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:41:in `formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:107:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

I have no idea what I should do.  And it says 

> Please report this bug:

So I am reporting this. 

Thank you!

#### brew config
```HOMEBREW_VERSION: 1.1.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0f529dae1043639058130092cf35e68d18907cb8
Last commit: 12 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1a7bfb82fde7ed52ee035e863fa8c7e85a852a71
Core tap last commit: 18 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
Clang: 7.3 build 703
Git: 2.7.4 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: /Users/naggigoishi/.pyenv/shims/python => /Users/naggigoishi/.pyenv/versions/3.5.2/bin/python3.5
Ruby: /Users/naggigoishi/.rbenv/shims/ruby => /Users/naggigoishi/.rbenv/versions/2.2.3/bin/ruby
Java: 1.8.0_101
macOS: 10.11.6-x86_64
Xcode: N/A
CLT: 7.3.1.0.1.1461711523
X11: N/A```

**Comment by dunn** [comment]
The tap you're trying to install from (https://github.com/quantiverge/homebrew-binary) needs to update its formula to use SHA256 checksums instead of SHA1.  But that repository looks abandoned.
