### ISSUE TITLE
brew create fails with error

### ISSUE THREAD

**Issue by aurimasniekis** [Homebrew/brew#1688]
Then running `brew create https://github.com/aurimasniekis/wallpaperutil/releases/download/1.0.0/wallpaperutil.zip`

It fails with error:
```
Formula name [wallpaperutil]: WallpaperUtl
Error: version '#<Version::NULL>' should be a string
Please report this bug:
  https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Homebrew/resource.rb:168:in `detect_version'
/usr/local/Homebrew/Library/Homebrew/resource.rb:149:in `version'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/create.rb:150:in `generate!'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/create.rb:88:in `create'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

***brew config:***
```
HOMEBREW_VERSION: 1.1.4-2-g9cd5a21b473f
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9cd5a21b473f0271b162bbe7f77f7d1468c0cfa1
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: aabe1d90489b6991b45bb1cccc59026b9a5867e8
Core tap last commit: 42 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.11.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_112
macOS: 10.11.5-x86_64
Xcode: 8.1
CLT: 7.3.1.0.1.1461711523
X11: 2.7.11 => /opt/X11
```

***brew doctor***
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libzmq.3.dylib

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  docker-machine
  php56
  php71

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc

Warning: Your Xcode (8.1) is outdated.
Please update to Xcode 8.2 (or delete it).
Xcode can be updated from the App Store.


Warning: Some installed formula are missing dependencies.
You should `brew install` the missing dependencies:
  brew install doxygen

Run `brew missing` for more details.
```

**Comment by ilovezfs** [comment]
This should fix it
```
diff --git a/Library/Homebrew/dev-cmd/create.rb b/Library/Homebrew/dev-cmd/create.rb
index 11544db..f684f95 100644
--- a/Library/Homebrew/dev-cmd/create.rb
+++ b/Library/Homebrew/dev-cmd/create.rb
@@ -119,7 +119,7 @@ class FormulaCreator
     if @version
       @version = Version.create(@version)
     else
-      @version = Pathname.new(url).version
+      @version = Version.detect(url, {})
     end
   end
 
```
