### ISSUE TITLE
python fails to install and link pip

### ISSUE THREAD

**Issue by nodesocket** [Homebrew/brew#1704]
Running macOS Sierra 10.12.2.

When the postinstall runs for python 2.7.13, it is failing with:

```shell
MacBook-Pro ➜  brew postinstall python
==> Using the sandbox
==> /usr/local/Cellar/python/2.7.13/bin/python -s setup.py --no-user-cfg install --force --verbose --single-version-externally-managed --rec
==> /usr/local/Cellar/python/2.7.13/bin/python -s setup.py --no-user-cfg install --force --verbose --single-version-externally-managed --rec
Last 15 lines from /Users/justin/Library/Logs/Homebrew/python/post_install.02.python:

Traceback (most recent call last):
  File "setup.py", line 92, in <module>
    cmdclass={'test': PyTest},
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/Users/justin/.venvburrito/lib/python/distribute-0.6.35-py2.7.egg/setuptools/dist.py", line 225, in __init__
    _Distribution.__init__(self,attrs)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/Users/justin/.venvburrito/lib/python/distribute-0.6.35-py2.7.egg/setuptools/dist.py", line 258, in finalize_options
    ep.load()(self, ep.name, value)
  File "/Users/justin/.venvburrito/lib/python/distribute-0.6.35-py2.7.egg/pkg_resources.py", line 2020, in load
    raise ImportError("%r has no %r attribute" % (entry,attr))
ImportError: <module 'setuptools.dist' from '/Users/justin/.venvburrito/lib/python/distribute-0.6.35-py2.7.egg/setuptools/dist.pyc'> has no 'check_specifier' attribute
```

It is strange because everything else seems in place except I don't have `pip`.

````shell
MacBook-Pro ➜  pwd
/usr/local/Cellar/python/2.7.13/bin
MacBook-Pro ➜  ll
total 184
lrwxr-xr-x  1 justin  admin    52B Dec 19 17:47 2to3 -> ../Frameworks/Python.framework/Versions/2.7/bin/2to3
lrwxr-xr-x  1 justin  admin    54B Dec 19 17:47 2to3-2 -> ../Frameworks/Python.framework/Versions/2.7/bin/2to3-2
lrwxr-xr-x  1 justin  admin    56B Dec 19 17:47 2to3-2.7 -> ../Frameworks/Python.framework/Versions/2.7/bin/2to3-2.7
-rwxr-xr-x  1 justin  admin   423B Dec 19 18:52 easy_install
-rwxr-xr-x  1 justin  admin   431B Dec 19 18:52 easy_install-2.7
lrwxr-xr-x  1 justin  admin    52B Dec 19 17:47 idle -> ../Frameworks/Python.framework/Versions/2.7/bin/idle
lrwxr-xr-x  1 justin  admin    53B Dec 19 17:47 idle2 -> ../Frameworks/Python.framework/Versions/2.7/bin/idle2
lrwxr-xr-x  1 justin  admin    55B Dec 19 17:47 idle2.7 -> ../Frameworks/Python.framework/Versions/2.7/bin/idle2.7
lrwxr-xr-x  1 justin  admin    53B Dec 19 17:47 pydoc -> ../Frameworks/Python.framework/Versions/2.7/bin/pydoc
lrwxr-xr-x  1 justin  admin    54B Dec 19 17:47 pydoc2 -> ../Frameworks/Python.framework/Versions/2.7/bin/pydoc2
lrwxr-xr-x  1 justin  admin    56B Dec 19 17:47 pydoc2.7 -> ../Frameworks/Python.framework/Versions/2.7/bin/pydoc2.7
lrwxr-xr-x  1 justin  admin    54B Dec 19 17:47 python -> ../Frameworks/Python.framework/Versions/2.7/bin/python
lrwxr-xr-x  1 justin  admin    61B Dec 19 17:47 python-config -> ../Frameworks/Python.framework/Versions/2.7/bin/python-config
lrwxr-xr-x  1 justin  admin    55B Dec 19 17:47 python2 -> ../Frameworks/Python.framework/Versions/2.7/bin/python2
lrwxr-xr-x  1 justin  admin    62B Dec 19 17:47 python2-config -> ../Frameworks/Python.framework/Versions/2.7/bin/python2-config
lrwxr-xr-x  1 justin  admin    57B Dec 19 17:47 python2.7 -> ../Frameworks/Python.framework/Versions/2.7/bin/python2.7
lrwxr-xr-x  1 justin  admin    64B Dec 19 17:47 python2.7-config -> ../Frameworks/Python.framework/Versions/2.7/bin/python2.7-config
lrwxr-xr-x  1 justin  admin    55B Dec 19 17:47 pythonw -> ../Frameworks/Python.framework/Versions/2.7/bin/pythonw
lrwxr-xr-x  1 justin  admin    56B Dec 19 17:47 pythonw2 -> ../Frameworks/Python.framework/Versions/2.7/bin/pythonw2
lrwxr-xr-x  1 justin  admin    58B Dec 19 17:47 pythonw2.7 -> ../Frameworks/Python.framework/Versions/2.7/bin/pythonw2.7
lrwxr-xr-x  1 justin  admin    56B Dec 19 17:47 smtpd.py -> ../Frameworks/Python.framework/Versions/2.7/bin/smtpd.py
lrwxr-xr-x  1 justin  admin    59B Dec 19 17:47 smtpd2.7.py -> ../Frameworks/Python.framework/Versions/2.7/bin/smtpd2.7.py
lrwxr-xr-x  1 justin  admin    57B Dec 19 17:47 smtpd2.py -> ../Frameworks/Python.framework/Versions/2.7/bin/smtpd2.py
````

**Comment by coreice** [comment]
I'm experiencing the same problem with 2.7.13 using on MacOS 12.2.2 and Homebrew v1.1.5.

I've already tried removing and reinstalling Python. This is what happens when installing. 

```
$ brew install python
==> Downloading https://homebrew.bintray.com/bottles/python-2.7.13.sierra.bottle.tar.gz
Already downloaded: /Users/mark/Library/Caches/Homebrew/python-2.7.13.sierra.bottle.tar.gz
==> Pouring python-2.7.13.sierra.bottle.tar.gz
==> Using the sandbox
==> /usr/local/Cellar/python/2.7.13/bin/python -s setup.py --no-user-cfg install --force --verbose --single-version-externally-managed --record=installed.txt --install-scripts=/usr/l
Last 15 lines from /Users/mark/Library/Logs/Homebrew/python/post_install.01.python:
creating build/lib/setuptools/extern
copying setuptools/extern/__init__.py -> build/lib/setuptools/extern
copying setuptools/script (dev).tmpl -> build/lib/setuptools
copying setuptools/script.tmpl -> build/lib/setuptools
copying setuptools/cli-32.exe -> build/lib/setuptools
copying setuptools/cli-64.exe -> build/lib/setuptools
copying setuptools/cli.exe -> build/lib/setuptools
copying setuptools/gui-32.exe -> build/lib/setuptools
copying setuptools/gui-64.exe -> build/lib/setuptools
copying setuptools/gui.exe -> build/lib/setuptools
copying setuptools/command/launcher manifest.xml -> build/lib/setuptools/command
running install_lib
copying build/lib/easy_install.py -> /usr/local/lib/python2.7/site-packages
copying build/lib/pkg_resources/__init__.py -> /usr/local/lib/python2.7/site-packages/pkg_resources
error: could not delete '/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py': Permission denied
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall python
```

So using `brew postinstall python`

```
$ brew postinstall python
==> Using the sandbox
==> /usr/local/Cellar/python/2.7.13/bin/python -s setup.py --no-user-cfg install --force --verbose --single-version-externally-managed --record=installed.txt --install-scripts=/usr/l
Last 15 lines from /Users/mark/Library/Logs/Homebrew/python/post_install.01.python:
install
--force
--verbose
--single-version-externally-managed
--record=installed.txt
--install-scripts=/usr/local/Cellar/python/2.7.13/bin
--install-lib=/usr/local/lib/python2.7/site-packages

running install
running build
running build_py
running install_lib
copying build/lib/easy_install.py -> /usr/local/lib/python2.7/site-packages
copying build/lib/pkg_resources/__init__.py -> /usr/local/lib/python2.7/site-packages/pkg_resources
error: could not delete '/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py': Permission denied

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
Python or GTK crash after upgrade to Sierra https://github.com/Homebrew/homebrew-core/issues/8022
mercurial: --with-custom-python can be a no-op https://github.com/Homebrew/homebrew-core/pull/6764
[ansible] New python dependency needs --with-custom-python option like vim https://github.com/Homebrew/homebrew-core/issues/6728
vim and macvim bottles need to be rebuilt after new python (from #7973) https://github.com/Homebrew/homebrew-core/issues/8005
Building python 3.6 (python3 --devel) fails on MacPro, Sierra; https://github.com/Homebrew/homebrew-core/issues/5565
Wrong Python directory when installing MacVim from bottle https://github.com/Homebrew/homebrew-core/issues/5428

Error: You have MacPorts or Fink installed:
  /opt/local/bin/port

This can cause trouble. You don't have to uninstall them, but you may want to
temporarily move them out of the way, e.g.

  sudo mv /opt/local ~/macports
```

The files and folders in `/usr/local/lib/python2.7/site-packages/pkg_resources` are marked as root. Not sure if this is right? Somehow it fails on there.

Also pip fails, not sure why it is suddenly pointing towards the `/Library/Python/` folder as this is under the system protection of MacOS. This shouldn't be the case right?

```
$   pip install --upgrade pip setuptools
Requirement already up-to-date: pip in /Library/Python/2.7/site-packages
Collecting setuptools
  Downloading setuptools-32.1.3-py2.py3-none-any.whl (477kB)
    100% |████████████████████████████████| 481kB 1.6MB/s 
Installing collected packages: setuptools
  Found existing installation: setuptools 32.1.2
    Uninstalling setuptools-32.1.2:
      Successfully uninstalled setuptools-32.1.2
  Rolling back uninstall of setuptools
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/easy_install.py'
```

**Comment by MikeMcQuaid** [comment]
> Please note we may immediately close your issue without comment if you do not fill out the issue template and provide the requested information.
