### ISSUE TITLE
sha256 :no_check broken from April 25 commit

### ISSUE THREAD

**Issue by AlexanderTerp** [Homebrew/brew#17175]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.2.19-146-gc2ed332
ORIGIN: https://github.com/Homebrew/brew
HEAD: c2ed3327c605c3e738359c9807b8f4cd6fec09eb
Last commit: 5 hours ago
Core tap HEAD: f6d23d18c5d7ee4c908a0b6a1e83e82debc6a8a1
Core tap last commit: 2 hours ago
Core tap JSON: 29 Apr 07:31 UTC
Core cask tap JSON: 29 Apr 07:31 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_ARTIFACT_DOMAIN: https://homebrew-proxy.trading.imc.intra/
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.3-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: 15.3
Rosetta 2: false
```

### What were you trying to do (and why)?

I was trying to `brew install` an internal company homebrew formula. This formula uses `sha256 :no_check`.

### What happened (include all command output)?

(let's call the formula company-scripts for ease)

```
> brew install company-scripts

Error: Parameter 'hexdigest': Expected type String, got type Symbol with value :no_check
Caller: /opt/homebrew/Library/Homebrew/resource.rb:175
Definition: /opt/homebrew/Library/Homebrew/checksum.rb:12
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11361/lib/types/configuration.rb:296:in `call_validation_error_handler_default'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11361/lib/types/configuration.rb:303:in `call_validation_error_handler'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11361/lib/types/private/methods/call_validation.rb:300:in `report_error'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11361/lib/types/private/methods/call_validation.rb:218:in `block in validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11361/lib/types/private/methods/signature.rb:213:in `each_args_value_type'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11361/lib/types/private/methods/call_validation.rb:215:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11361/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/resource.rb:175:in `new'
/opt/homebrew/Library/Homebrew/resource.rb:175:in `sha256'
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/forwardable.rb:238:in `sha256'
/opt/homebrew/Library/Homebrew/formula.rb:3334:in `sha256'
/opt/homebrew/Library/Taps/imc/homebrew-apac-strat/Formula/imc-strat-scripts.rb:7:in `<class:ImcStratScripts>'
/opt/homebrew/Library/Taps/imc/homebrew-apac-strat/Formula/imc-strat-scripts.rb:1:in `block in load_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:107:in `module_eval'
/opt/homebrew/Library/Homebrew/formulary.rb:107:in `block in load_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:119:in `load_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:150:in `load_formula_from_path'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11361/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11361/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11361/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/formulary.rb:542:in `load_file'
/opt/homebrew/Library/Homebrew/formulary.rb:763:in `load_file'
/opt/homebrew/Library/Homebrew/formulary.rb:533:in `klass'
/opt/homebrew/Library/Homebrew/formulary.rb:528:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:753:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:968:in `factory'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11361/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11361/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11361/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cli/parser.rb:710:in `block in formulae'
/opt/homebrew/Library/Homebrew/cli/parser.rb:706:in `each'
/opt/homebrew/Library/Homebrew/cli/parser.rb:706:in `filter_map'
/opt/homebrew/Library/Homebrew/cli/parser.rb:706:in `formulae'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11361/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11361/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11361/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cli/parser.rb:364:in `parse'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11361/lib/types/private/methods/call_validation.rb:167:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11361/lib/types/private/methods/call_validation.rb:167:in `validate_call_skip_block_type'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11361/lib/types/private/methods/call_validation.rb:109:in `block in create_validator_slow_skip_block_type'
/opt/homebrew/Library/Homebrew/abstract_command.rb:52:in `initialize'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11361/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11361/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11361/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11361/lib/types/private/abstract/declare.rb:37:in `new'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11361/lib/types/private/abstract/declare.rb:37:in `block in declare_abstract'
/opt/homebrew/Library/Homebrew/brew.rb:90:in `<main>'
If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/mycompany/homebrew-myteam/issues/new
```

### What did you expect to happen?

It should install like it has for the last several months that this formula has been in use.

### Step-by-step reproduction instructions (by running `brew` commands)

(works on M1 Mac)

0. Ensure you're on the latest Homebrew in `/opt/homebrew`
1. `cd /tmp`
2. `mkdir hbtest`
3. `cd hbtest`
4. `mkdir Formula`
5. `vim ./Formula/test.rb`
6. Paste in the following and `:wq`:

```rb
class Test < Formula
    sha256 :no_check
end
```

7. `brew install --build-from-source ./Formula/test.rb`
8. Witness "What happened" error above.
9. In a separate terminal, `cd /opt/homebrew`.
10. `git checkout f381b2cdf7` -- this is the commit *before* `58b50badef` which I think broke this
11. In the original tab, try step 7 again.
12. Witness a new error `Error: formulae require at least a URL`, indicating that `:no__check` at least is not a problem.

---

Thanks as always for your work maintaining Homebrew! 🙏

**Comment by AlexanderTerp** [comment]
I ran `git bisect` and found that this commit appears to be the culprit: https://github.com/Homebrew/brew/commit/58b50badef728ad3661ed5e3b86db73f9c6ef176

I realize that `sha256 :no_check` is perhaps an unusual workflow, but I presume it's meant to be supported? I'm open to other solutions (ideally not involving actually generating shas).

**Comment by MikeMcQuaid** [comment]
> /opt/homebrew/Library/Taps/imc/homebrew-apac-strat/Formula/imc-strat-scripts.rb:7:in `<class:ImcStratScripts>'

The issue is in this file, not Homebrew.

> I realize that `sha256 :no_check` is perhaps an unusual workflow, but I presume it's meant to be supported?

It's not supported and never has been for formulae, sorry (but does work for casks). This failure is a legitimate one.

**Comment by MikeMcQuaid** [comment]
> Thanks as always for your work maintaining Homebrew! 🙏

Also: thanks for the kind words, they are rare and appreciated ❤️

**Comment by AlexanderTerp** [comment]
Gotcha, sorry for the misunderstanding -- happy to close. It also appears simply removing that line from the formula works, I thought I had originally added it because Homebrew would refuse to install the formula if I didn't put a sha, but that appears to not be the case here.

Thanks Mike!

**Comment by MikeMcQuaid** [comment]
You're welcome @AlexanderTerp!
