### ISSUE TITLE
brew update --greedy:  Parameter 'message': Expected type String, got type OptionParser::InvalidOption with value #<OptionParser::InvalidOption: --greedy>

### ISSUE THREAD

**Issue by dimberr** [Homebrew/brew#17269]
### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  terraform
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.2.21-86-ge26e673
ORIGIN: https://github.com/Homebrew/brew
HEAD: e26e6731195c5791262354537642ecdf21829b5d
Last commit: 27 minutes ago
Core tap JSON: 10 May 12:18 UTC
Core cask tap JSON: 10 May 12:18 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 16
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 15.0.0 build 1500
Git: 2.45.0 => /usr/local/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.4.1-x86_64
CLT: 15.3.0.0.1.1708646388
Xcode: N/A
```

### What were you trying to do (and why)?

brew update --greedy

### What happened (include all command output)?

```
==> Updating Homebrew...
Usage: brew update-report [--auto-update] [--force]

The Ruby implementation of brew update. Never called manually.

      --auto-update, --preinstall  Run in 'auto-update' mode (faster, less
                                   output).
  -f, --force                      Treat installed and updated formulae as if
                                   they are from the same taps and migrate them
                                   anyway.
  -d, --debug                      Display any debugging information.
  -q, --quiet                      Make some output more quiet.
  -v, --verbose                    Make some output more verbose.
  -h, --help                       Show this message.
Error: invalid option: --greedy
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11370/lib/types/configuration.rb:296:in `call_validation_error_handler_default': Parameter 'message': Expected type String, got type OptionParser::InvalidOption with value #<OptionParser::InvalidOption: --greedy> (TypeError)
Caller: /usr/local/Homebrew/Library/Homebrew/extend/kernel.rb:77
Definition: /usr/local/Homebrew/Library/Homebrew/utils/github/actions.rb:50
	from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11370/lib/types/configuration.rb:303:in `call_validation_error_handler'
	from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11370/lib/types/private/methods/call_validation.rb:300:in `report_error'
	from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11370/lib/types/private/methods/call_validation.rb:218:in `block in validate_call'
	from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11370/lib/types/private/methods/signature.rb:213:in `each_args_value_type'
	from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11370/lib/types/private/methods/call_validation.rb:215:in `validate_call'
	from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11370/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from /usr/local/Homebrew/Library/Homebrew/extend/kernel.rb:77:in `block in onoe'
	from /usr/local/Homebrew/Library/Homebrew/utils/tty.rb:46:in `with'
	from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11370/lib/types/private/methods/call_validation.rb:270:in `bind_call'
	from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11370/lib/types/private/methods/call_validation.rb:270:in `validate_call'
	from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11370/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from /usr/local/Homebrew/Library/Homebrew/extend/kernel.rb:75:in `onoe'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:181:in `rescue in <main>'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:140:in `<main>'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:329:in `parse_remaining': invalid option: --greedy (OptionParser::InvalidOption)
	from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11370/lib/types/private/methods/call_validation.rb:167:in `bind_call'
	from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11370/lib/types/private/methods/call_validation.rb:167:in `validate_call_skip_block_type'
	from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11370/lib/types/private/methods/call_validation.rb:109:in `block in create_validator_slow_skip_block_type'
	from /usr/local/Homebrew/Library/Homebrew/cli/parser.rb:381:in `parse'
	from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11370/lib/types/private/methods/call_validation.rb:167:in `bind_call'
	from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11370/lib/types/private/methods/call_validation.rb:167:in `validate_call_skip_block_type'
	from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11370/lib/types/private/methods/call_validation.rb:109:in `block in create_validator_slow_skip_block_type'
	from /usr/local/Homebrew/Library/Homebrew/abstract_command.rb:53:in `initialize'
	from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11370/lib/types/private/methods/call_validation.rb:270:in `bind_call'
	from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11370/lib/types/private/methods/call_validation.rb:270:in `validate_call'
	from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11370/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11370/lib/types/private/abstract/declare.rb:37:in `new'
	from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11370/lib/types/private/abstract/declare.rb:37:in `block in declare_abstract'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:90:in `<main>'
```

### What did you expect to happen?

==> Updating Homebrew...
Already up-to-date.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. run brew update --greedy 
2. fails with output above
3. run brew update --greedy - normal output without error
4. after some time (like 1h for example) run brew update --greedy and see the same error
```

**Comment by MikeMcQuaid** [comment]
> ```shell
> 3. run brew update --greedy - normal output without error
> ```

Note: this error is bad/wrong but `brew update --greedy` is not valid. You meant `brew upgrade --greedy`.
