### ISSUE TITLE
'invalid multibyte char' error when using bump-formula-pr

### ISSUE THREAD

**Issue by tomhoover** [Homebrew/brew#1728]
### Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

### Description:

`rmlint` has been updated to v2.4.5, so I thought I'd try `brew bump-formula-pr` rather than `brew edit`. (Please note this is my first attempt using `bump-formula-pr`--I've always manually edited formulas in the past. When I couldn't get `bump-formula-pr` to work for me, I submitted [PR#8187](https://github.com/Homebrew/homebrew-core/pull/8187) to homebrew-core after using `brew edit` the 'old' way).

`brew bump-formula-pr --url https://github.com/sahib/rmlint/archive/v2.4.5.tar.gz rmlint` resulted in the following errors:

```
Error: /Users/tom/Library/Caches/Homebrew/Formula/v2.4.5.tar.gz:1: Invalid char `\x1F' in expression
/Users/tom/Library/Caches/Homebrew/Formula/v2.4.5.tar.gz:1: invalid multibyte char (UTF-8)
Please report this bug:
  https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:97:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:153:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:253:in `factory'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:43:in `block in formulae'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:41:in `map'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:41:in `formulae'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb:82:in `bump_formula_pr'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### `brew config`:

```
HOMEBREW_VERSION: 1.1.5-42-g5b806c09ae
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 5b806c09ae064aaf5d61d84308009deec6cca5de
Last commit: 20 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 766d627d8ae726f936c2b7c5205f3dc108101a93
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.11.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /Users/tom/.pyenv/shims/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/tom/.rbenv/shims/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_102, 1.8.0_77
macOS: 10.12.2-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: N/A
```

### `brew doctor`:

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/tom/.pyenv/shims/python-config
  /Users/tom/.pyenv/shims/python2-config
  /Users/tom/.pyenv/shims/python2.7-config
  /Users/tom/.pyenv/shims/python3-config
  /Users/tom/.pyenv/shims/python3.4-config
  /Users/tom/.pyenv/shims/python3.4m-config
```

**Comment by MikeMcQuaid** [comment]
> brew bump-formula-pr --url https://github.com/sahib/rmlint/archive/v2.4.5.tar.gz rmlint

The correct syntax is `brew bump-formula-pr --url=https://github.com/sahib/rmlint/archive/v2.4.5.tar.gz rmlint`

**Comment by tomhoover** [comment]
duh...sorry about that
