### ISSUE TITLE
Migration to other tap broken

### ISSUE THREAD

**Issue by pe** [Homebrew/brew#17290]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.2.21-117-gd7e81be
ORIGIN: https://github.com/Homebrew/brew
HEAD: d7e81bed359e1cbe9fb935ff40e1fd85269388fb
Last commit: 12 hours ago
Core tap HEAD: 1847a9646b873b32ed47e26c31b348fca27caf01
Core tap last commit: 14 minutes ago
Core tap JSON: 13 May 19:06 UTC
Core cask tap JSON: 13 May 19:06 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: micro
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.45.0 => /opt/homebrew/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.4.1-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

I am trying to migrate a cask from one tap to another tap. For this, I followed [Migrating a Formula to a Tap](https://docs.brew.sh/Migrating-A-Formula-To-A-Tap).

To reproduce, I created two repositories. And migrated a sample cask (a copy of AnyBar).

As per the instructions I
- copied the cask as-is to the new tap https://github.com/pe/homebrew-new-tap/commit/692bfe6977a0e115fd40d4b49ad5901432aeaab9
- deleted the cask file and added it to `tap_migrations.json` in the old tap https://github.com/pe/homebrew-old-tap/commit/3bb7e458dc8589855e4ac9dfdec5e9849f9693e7

### What happened (include all command output)?

Working with the migrated cask returns errors.
There are two warnings instead of one. One for a cask and one for a formula. But there is only a cask.
The error list the same tap twice.

```shell
~ > brew info example --debug --verbose
Warning: Formula pe/old-tap/example was renamed to pe/new-tap/example.
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading example
Warning: Cask pe/old-tap/example was renamed to pe/new-tap/example.
Error: Cask example exists in multiple taps:
       * pe/new-tap/example
       * pe/new-tap/example

Please use the fully-qualified name (e.g. pe/new-tap/example) to refer to a specific Cask.
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:467:in `try_new'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11375/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11375/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11375/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:567:in `block in for'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:566:in `each'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:566:in `for'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:517:in `load'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:179:in `block in load_formula_or_cask'
/opt/homebrew/Library/Homebrew/api.rb:201:in `with_no_api_env_if_needed'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11375/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11375/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11375/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:138:in `load_formula_or_cask'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:131:in `block in to_formulae_and_casks_and_unavailable'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:130:in `map'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:130:in `to_formulae_and_casks_and_unavailable'
/opt/homebrew/Library/Homebrew/cmd/info.rb:153:in `print_info'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11375/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11375/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11375/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cmd/info.rb:106:in `run'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11375/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11375/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11375/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/brew.rb:92:in `<main>'
```

It can only be uninstalled with the full name.

```shell
~ > brew uninstal example
Warning: Formula pe/old-tap/example was renamed to pe/new-tap/example.
Warning: Cask pe/old-tap/example was renamed to pe/new-tap/example.
Error: Cask example exists in multiple taps:
       * pe/new-tap/example
       * pe/new-tap/example

Please use the fully-qualified name (e.g. pe/new-tap/example) to refer to a specific Cask.
~ > brew uninstal pe/new-tap/example
==> Uninstalling Cask example
==> Backing App 'AnyBar.app' up to '/opt/homebrew/Caskroom/example/0.2.3/AnyBar.app'
==> Removing App '/Applications/AnyBar.app'
==> Purging files for version 0.2.3 of Cask example
```

It can only be installed with the full name.

```shell
~ > brew install pe/old-tap/example
==> Auto-updating Homebrew...
Adjust how often this is run with HOMEBREW_AUTO_UPDATE_SECS or disable with
HOMEBREW_NO_AUTO_UPDATE. Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
Warning: Formula pe/old-tap/example was renamed to pe/new-tap/example.
==> Downloading https://github.com/tonsky/AnyBar/releases/download/0.2.3/AnyBar-0.2.3.zip
Already downloaded: /Users/philippe.eberli/Library/Caches/Homebrew/downloads/c2696299dd799237cb088ec14ae2b8ead2d3d84b6bcb1eb7dfa52eef9219318d--AnyBar-0.2.3.zip
==> Installing Cask example
==> Moving App 'AnyBar.app' to '/Applications/AnyBar.app'
🍺  example was successfully installed!
~ > brew uninstal pe/new-tap/example
==> Uninstalling Cask example
==> Backing App 'AnyBar.app' up to '/opt/homebrew/Caskroom/example/0.2.3/AnyBar.app'
==> Removing App '/Applications/AnyBar.app'
==> Purging files for version 0.2.3 of Cask example
~ > brew install pe/new-tap/example
==> Downloading https://github.com/tonsky/AnyBar/releases/download/0.2.3/AnyBar-0.2.3.zip
Already downloaded: /Users/philippe.eberli/Library/Caches/Homebrew/downloads/c2696299dd799237cb088ec14ae2b8ead2d3d84b6bcb1eb7dfa52eef9219318d--AnyBar-0.2.3.zip
==> Installing Cask example
==> Moving App 'AnyBar.app' to '/Applications/AnyBar.app'
🍺  example was successfully installed!
```

### What did you expect to happen?

The migrated cask can be used without errors and without having to specify the full name (=excluding the tap)

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
~ ❯ brew tap pe/old-tap
==> Tapping pe/old-tap
Cloning into '/opt/homebrew/Library/Taps/pe/homebrew-old-tap'...
remote: Enumerating objects: 14, done.
remote: Counting objects: 100% (14/14), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 14 (delta 1), reused 13 (delta 0), pack-reused 0
Receiving objects: 100% (14/14), done.
Resolving deltas: 100% (1/1), done.
Tapped (16 files, 9.8KB).
~ ❯ brew install example
==> Downloading https://github.com/tonsky/AnyBar/releases/download/0.2.3/AnyBar-0.2.3.zip
Already downloaded: /Users/philippe.eberli/Library/Caches/Homebrew/downloads/c2696299dd799237cb088ec14ae2b8ead2d3d84b6bcb1eb7dfa52eef9219318d--AnyBar-0.2.3.zip
==> Installing Cask example
==> Moving App 'AnyBar.app' to '/Applications/AnyBar.app'
🍺  example was successfully installed!


⇒ migrating the example cask from old-tap to new-tap. See commits in the description.


~ ❯ brew tap pe/new-tap
==> Tapping pe/new-tap
Cloning into '/opt/homebrew/Library/Taps/pe/homebrew-new-tap'...
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 11 (delta 0), reused 11 (delta 0), pack-reused 0
Receiving objects: 100% (11/11), done.
Tapped 1 cask (16 files, 9.9KB).
```

**Comment by carlocab** [comment]
I think your `tap_migrations.json` in `pe/old-tap` should be
```
{
    "example": "pe/new-tap/example"
}
```

**Comment by pe** [comment]
> I think your `tap_migrations.json` in `pe/old-tap` should be
> 
> ```json
> {
>     "example": "pe/new-tap/example"
> }
> ```

Looking at other examples I don't think so: https://github.com/brewsci/homebrew-science/blob/5d14d2fda3934c0eb8243c1cbdb9fb4621ec110b/tap_migrations.json

I tried it with https://github.com/pe/homebrew-old-tap/commit/cc86591af67324b7cb9c075bc98e6609e431bf6e. Same error.

**Comment by pe** [comment]
I think I found the source of the issue. The same cask is found twice. Once in the new tap and once in the old but mapped to the new tap.

If I inspect `loaders` from this code https://github.com/Homebrew/brew/blob/5e6a43e5d52b899daa156bfa3d42980b3d6b493b/Library/Homebrew/cask/cask_loader.rb#L459-L461

I get this:

```
[
#<Cask::CaskLoader::FromNameLoader:0x0000000125cac788 @token="example", @path=#<Pathname:/opt/homebrew/Library/Taps/pe/homebrew-new-tap/Casks/example.rb>, @tap=#<Tap:0x0000000122de3898 @user="pe", @repo="new-tap", @name="pe/new-tap", @full_name="pe/homebrew-new-tap", @path=#<Pathname:/opt/homebrew/Library/Taps/pe/homebrew-new-tap>, @git_repo=#<GitRepository:0x0000000122e0f6f0 @pathname=#<Pathname:/opt/homebrew/Library/Taps/pe/homebrew-new-tap>>, @alias_dir=#<Pathname:/opt/homebrew/Library/Taps/pe/homebrew-new-tap/Aliases>, @alias_files=[], @alias_table={}, @formula_renames={}, @tap_migrations={}, @potential_formula_dirs=[#<Pathname:/opt/homebrew/Library/Taps/pe/homebrew-new-tap/Formula>, #<Pathname:/opt/homebrew/Library/Taps/pe/homebrew-new-tap/HomebrewFormula>, #<Pathname:/opt/homebrew/Library/Taps/pe/homebrew-new-tap>], @formula_dir=#<Pathname:/opt/homebrew/Library/Taps/pe/homebrew-new-tap>, @formula_files=[], @formula_files_by_name={}, @cask_renames={}, @cask_dir=#<Pathname:/opt/homebrew/Library/Taps/pe/homebrew-new-tap/Casks>, @cask_files=[#<Pathname:/opt/homebrew/Library/Taps/pe/homebrew-new-tap/Casks/example.rb>], @cask_files_by_name={"example"=>#<Pathname:/opt/homebrew/Library/Taps/pe/homebrew-new-tap/Casks/example.rb>}>>,
#<Cask::CaskLoader::FromNameLoader:0x0000000125caa410 @token="example", @path=#<Pathname:/opt/homebrew/Library/Taps/pe/homebrew-new-tap/Casks/example.rb>, @tap=#<Tap:0x0000000122de3898 @user="pe", @repo="new-tap", @name="pe/new-tap", @full_name="pe/homebrew-new-tap", @path=#<Pathname:/opt/homebrew/Library/Taps/pe/homebrew-new-tap>, @git_repo=#<GitRepository:0x0000000122e0f6f0 @pathname=#<Pathname:/opt/homebrew/Library/Taps/pe/homebrew-new-tap>>, @alias_dir=#<Pathname:/opt/homebrew/Library/Taps/pe/homebrew-new-tap/Aliases>, @alias_files=[], @alias_table={}, @formula_renames={}, @tap_migrations={}, @potential_formula_dirs=[#<Pathname:/opt/homebrew/Library/Taps/pe/homebrew-new-tap/Formula>, #<Pathname:/opt/homebrew/Library/Taps/pe/homebrew-new-tap/HomebrewFormula>, #<Pathname:/opt/homebrew/Library/Taps/pe/homebrew-new-tap>], @formula_dir=#<Pathname:/opt/homebrew/Library/Taps/pe/homebrew-new-tap>, @formula_files=[], @formula_files_by_name={}, @cask_renames={}, @cask_dir=#<Pathname:/opt/homebrew/Library/Taps/pe/homebrew-new-tap/Casks>, @cask_files=[#<Pathname:/opt/homebrew/Library/Taps/pe/homebrew-new-tap/Casks/example.rb>], @cask_files_by_name={"example"=>#<Pathname:/opt/homebrew/Library/Taps/pe/homebrew-new-tap/Casks/example.rb>}>>
]
```

The only difference is the object_id.

I could solve this by changeing the above code like so:

```ruby
loaders = Tap.select { |tap| tap.installed? && !tap.core_cask_tap? }
             .filter_map { |tap| super("#{tap}/#{token}", warn:) }
             .select { |tap| tap.path.exist? }
             .uniq{ |cask| cask.tap } # this line was added by me
```

But my knowledge of this codebase is none and my ruby is very limited. I can't judge if this is a good idea or not.

How to proceed? Should I just create a PR and we'll discuss there? Whould you need any tests for this change?

**Comment by gromgit** [comment]
> I can't judge if this is a good idea or not.

My Ruby-fu is limited too, but I'm pretty sure that:
* the whole point of migrations is that the formula _no longer exists in the old tap_
* taps are processing in alpha-sorted order, so if your old taps sorts _before_ the new one, your fix will pick the wrong tap

**Comment by MikeMcQuaid** [comment]
> * the whole point of migrations is that the formula/cask _no longer exists in the old tap_

Yes, this. You should delete the formula/cask from the old file or it won't work as expected.

**Comment by MikeMcQuaid** [comment]
> How to proceed? Should I just create a PR and we'll discuss there?

Yes, this would be best.

> Would you want any tests for this change? Where?

Ideally the corresponding `_spec.rb` file to the source file(s) you edit. That can wait until we've validated the approach with a draft PR, though.

**Comment by pe** [comment]
> taps are processed in alpha-sorted order, so if your old tap sorts before the new one (e.g. pe/tap1 -> pe/tap2), your fix will pick the wrong tap

I don't think that the order matters because both cask are _identical_ (except for the object_id). The cask from the old tap was already migrated to the new one, that's why they are identical.

> > * the whole point of migrations is that the formula/cask _no longer exists in the old tap_
>
> Yes, this. You should delete the formula/cask from the old file or it won't work as expected.

I did delete it in the old tap and get this error nevertheless. See _What were you trying to do (and why)?_.

> > How to proceed? Should I just create a PR and we'll discuss there?
>
> Yes, this would be best.

OK. Will do.

**Comment by apainintheneck** [comment]
https://github.com/Homebrew/brew/blob/ff950e6629f7a09fabc8fd21048d4ab204a9fd27/Library/Homebrew/cask/cask_loader.rb#L459-L461

I suspect what's happening here is that we're getting identical cask loaders because the call to `super` evaluates cask renames and migrations so it's possible that the original tap that the cask was migrated from is returning the cask loader for the new tap.

https://github.com/Homebrew/brew/blob/ff950e6629f7a09fabc8fd21048d4ab204a9fd27/Library/Homebrew/cask/cask_loader.rb#L205-L212

The `super` call leads to the `Cask::CaskLoader::FromTapLoader.try_new` method which calls the `Cask::CaskLoader.tap_cask_token_type` method. Normally it just returns the cask token, tap and type specified but if the cask has been renamed or migrated it returns the new token, tap and type. Since they are identical, just removing duplicates by path makes sense here. Tap would also work but path is a bit more specific.

Ideally, we'd figure out how to refactor this so that this doesn't happen in this sort of situation but I'm not really sure what that would look like.

**Comment by MikeMcQuaid** [comment]
@reitermarkus Could you take a look at this if you get a chance as you did a bunch of migration work recently? Thanks ❤️

**Comment by apainintheneck** [comment]
Fixed by https://github.com/Homebrew/brew/pull/17385
