### ISSUE TITLE
HEAD-only formulae can no longer be installed

### ISSUE THREAD

**Issue by tbvdm** [Homebrew/brew#17333]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.3.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8378cc825d83acffd125fb0fec041793df378a57
Last commit: 5 days ago
Core tap JSON: 14 May 22:34 UTC
Core cask tap JSON: 14 May 22:34 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: ["--no-quarantine"]
HOMEBREW_COLOR: set
HOMEBREW_MAKE_JOBS: 3
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_NO_INSTALL_CLEANUP: set
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 3-core 64-bit dunno
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Applications/Xcode_15.0.1.app/Contents/Developer/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.4.1-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.0.1 => /Applications/Xcode_15.0.1.app/Contents/Developer
Rosetta 2: false
```

### What were you trying to do (and why)?

I have a tap with a few HEAD-only formulae. Installing these formulae has recently started to fail, presumably because of the recent SBOM changes.

### What happened (include all command output)?

The installation failed. Please see the reproducer below for details.

### What did you expect to happen?

The installation should succeed.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
This example uses awk.rb to illustrate the problem.

Fetch awk.rb and install its HEAD version. This works as expected:

$ curl -LO https://github.com/Homebrew/homebrew-core/raw/HEAD/Formula/a/awk.rb
$ brew install --verbose --HEAD --formula awk.rb

Now remove the "url" and "sha256" fields from awk.rb (thus turning it into a
HEAD-only formula) and try to install the HEAD version again. This fails:

$ sed -i -e /url/,/sha256/d awk.rb
$ brew uninstall awk
$ brew install --verbose --HEAD --formula awk.rb
[...]
==> Finishing up
ln -s ../Cellar/awk/HEAD-f8be48f/bin/awk awk
ln -s ../../../Cellar/awk/HEAD-f8be48f/share/man/man1/awk.1 awk.1
Error: undefined method `bottle_specification' for nil:NilClass
/opt/homebrew/Library/Homebrew/formula.rb:2582:in `bottle_hash'
/opt/homebrew/Library/Homebrew/sbom.rb:37:in `create'
/opt/homebrew/Library/Homebrew/formula_installer.rb:834:in `finish'
/opt/homebrew/Library/Homebrew/upgrade.rb:238:in `install_formula'
/opt/homebrew/Library/Homebrew/install.rb:350:in `install_formula'
/opt/homebrew/Library/Homebrew/install.rb:301:in `block in install_formulae'
/opt/homebrew/Library/Homebrew/install.rb:300:in `each'
/opt/homebrew/Library/Homebrew/install.rb:300:in `install_formulae'
/opt/homebrew/Library/Homebrew/cmd/install.rb:297:in `run'
/opt/homebrew/Library/Homebrew/brew.rb:92:in `<main>'
Please report this issue:
  https://docs.brew.sh/Troubleshooting
```

**Comment by dtrodrigues** [comment]
The installation is succeeding, but the SBOM generation after the installation is failing. This started as of https://github.com/Homebrew/brew/pull/17254 .
