### ISSUE TITLE
`brew fetch --os=linux` fails on macOS

### ISSUE THREAD

**Issue by carlocab** [Homebrew/brew#17375]
### `brew doctor` output

```shell
❯ brew dr
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.3.2-14-g44d0d64
ORIGIN: https://github.com/Homebrew/brew
HEAD: 44d0d64e79895b51064ff3ba670de126f463825e
Last commit: 2 hours ago
Core tap HEAD: 94c4a182ae09dd52d5a66da66eaedb9b3074967b
Core tap last commit: 41 minutes ago
Core tap JSON: 13 May 09:28 UTC
Core cask tap HEAD: 70bf2608ea401e809be79cd0191b092c6705c415
Core cask tap last commit: 30 minutes ago
Core cask tap JSON: 13 May 09:26 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_AUTO_UPDATE_SECS: 43200
HOMEBREW_BAT: set
HOMEBREW_BOOTSNAP: set
HOMEBREW_CASK_OPTS: []
HOMEBREW_DEVELOPER: set
HOMEBREW_EDITOR: nvim
HOMEBREW_FORCE_BREWED_CURL: set
HOMEBREW_FORCE_BREWED_GIT: set
HOMEBREW_GIT_EMAIL: 30379873+carlocab@users.noreply.github.com
HOMEBREW_GIT_NAME: Carlo Cabrera
HOMEBREW_MAKE_JOBS: 16
HOMEBREW_NO_CLEANUP_FORMULAE: zsh
HOMEBREW_NO_INSTALL_FROM_API: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.1 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.1/bin/ruby
CPU: 16-core 64-bit arm_palma
Clang: 15.0.0 build 1500
Git: 2.45.1 => /opt/homebrew/opt/git/bin/git
Curl: 8.8.0 => /opt/homebrew/opt/curl/bin/curl
macOS: 14.5-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.4
Rosetta 2: false
```

### What were you trying to do (and why)?

I was trying to fetch the Linux bottles for OpenBLAS while trying to debug a formula build issue. 

### What happened (include all command output)?

```
❯ brew fetch --os=linux openblas
Error: Calling `MacOS.version` on Linux is disabled! There is no replacement.
Please report this issue:
  https://docs.brew.sh/Troubleshooting
❯ brew fetch --os=linux --arch=intel openblas
Error: Calling `MacOS.version` on Linux is disabled! There is no replacement.
Please report this issue:
  https://docs.brew.sh/Troubleshooting
```

### What did you expect to happen?

I expected `brew` to download the Linux bottle.

### Step-by-step reproduction instructions (by running `brew` commands)

On macOS:
```shell
brew fetch --os=linux openblas
```

**Comment by carlocab** [comment]
Output with `--debug` and `--verbose`:
```
❯ brew fetch --os=linux --debug --verbose openblas
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromNameLoader): loading openblas
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::NullLoader): loading openblas
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/o/openblas.rb
Error: Calling `MacOS.version` on Linux is disabled! There is no replacement.
/opt/homebrew/Library/Homebrew/os/mac.rb:29:in `version'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11391/lib/types/private/methods/call_validation_2_7.rb:59:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11391/lib/types/private/methods/call_validation_2_7.rb:59:in `block in create_validator_method_fast0'
/opt/homebrew/Library/Homebrew/extend/os/mac/utils/bottles.rb:10:in `tag'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11391/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11391/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11391/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/software_spec.rb:110:in `bottle_tag?'
/opt/homebrew/Library/Homebrew/software_spec.rb:114:in `bottled?'
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.1/lib/ruby/3.3.0/forwardable.rb:240:in `bottled?'
/opt/homebrew/Library/Homebrew/formula.rb:421:in `bottle'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11391/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11391/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11391/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/fetch.rb:17:in `fetch_bottle?'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11391/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11391/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11391/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cmd/fetch.rb:104:in `block (3 levels) in run'
/opt/homebrew/Library/Homebrew/simulate_system.rb:27:in `with'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11391/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11391/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11391/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cmd/fetch.rb:98:in `block (2 levels) in run'
/opt/homebrew/Library/Homebrew/cmd/fetch.rb:97:in `each'
/opt/homebrew/Library/Homebrew/cmd/fetch.rb:97:in `block in run'
/opt/homebrew/Library/Homebrew/cmd/fetch.rb:91:in `each'
/opt/homebrew/Library/Homebrew/cmd/fetch.rb:91:in `run'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11391/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11391/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11391/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/brew.rb:92:in `<main>'
Please report this issue:
  https://docs.brew.sh/Troubleshooting
```

**Comment by carlocab** [comment]
It looks like this method is being called, despite being inside a [`SimulateSystem` block](https://github.com/Homebrew/brew/blob/44d0d64e79895b51064ff3ba670de126f463825e/Library/Homebrew/cmd/fetch.rb#L98):

https://github.com/Homebrew/brew/blob/44d0d64e79895b51064ff3ba670de126f463825e/Library/Homebrew/extend/os/mac/utils/bottles.rb#L9-L13
