### ISSUE TITLE
homebrew -cask-fonts

### ISSUE THREAD

**Issue by califool** [Homebrew/brew#17536]
### `brew doctor` output

```shell
califool@macMike3  ~   master ±  brew untap homebrew-cask-fonts
Error: Invalid tap name: 'homebrew-cask-fonts'
Warning: Removed Sorbet lines from backtrace!
Rerun with `--verbose` to see the original backtrace
/opt/homebrew/Library/Homebrew/tap.rb:61:in `fetch'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:348:in `block in to_taps'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:348:in `map'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:348:in `to_taps'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:353:in `to_installed_taps'
/opt/homebrew/Library/Homebrew/cmd/untap.rb:21:in `run'
/opt/homebrew/Library/Homebrew/brew.rb:92:in `<main>'
Please report this issue:
  https://docs.brew.sh/Troubleshooting




with backtrace:



califool@macMike3  ~   master ±  brew untap homebrew-cask-fonts --verbose
Error: Invalid tap name: 'homebrew-cask-fonts'
/opt/homebrew/Library/Homebrew/tap.rb:61:in `fetch'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11435/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11435/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11435/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:348:in `block in to_taps'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:348:in `map'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:348:in `to_taps'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11435/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11435/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11435/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:353:in `to_installed_taps'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11435/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11435/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11435/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cmd/untap.rb:21:in `run'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11435/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11435/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11435/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/brew.rb:92:in `<main>'
Please report this issue:
  https://docs.brew.sh/Troubleshooting
 ✘ califool@macMike3  ~   master ± 
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
✘ califool@macMike3  ~   master ±  brew config
HOMEBREW_VERSION: 4.3.6-32-g30e2ae1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 30e2ae10a38181972d21d67422143d3d9ff8a724
Last commit: 2 hours ago
Core tap JSON: 19 Jun 21:52 UTC
Core cask tap JSON: 19 Jun 21:52 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: code
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.3 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/bin/ruby
CPU: octa-core 64-bit arm_blizzard_avalanche
Clang: 15.0.0 build 1500
Git: 2.45.2 => /opt/homebrew/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.4
Rosetta 2: false
 califool@macMike3  ~   master ± 
```

### What were you trying to do (and why)?

fix location of casks after brew audit found 50 problems

### What happened (include all command output)?

all command output has been provided above

### What did you expect to happen?

to continue debugging and fix issues but it says to please report this error so i did.  

if you do not want thses errors submitted I would remove the "please report this issue" with please refer to community forum. 

also I did not follow those instructions because there is no way to save this issue submission for later. and I didnt want to waste the time I took trying to help a program I LOVE using...... 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew untap homebrew-cask-fonts
```

**Comment by bevanjkay** [comment]
Try `brew untap homebrew/cask-fonts`

**Comment by califool** [comment]
> Try `brew untap homebrew/cask-fonts`

thanks!
