### ISSUE TITLE
Homebrew not updating

### ISSUE THREAD

**Issue by ironfish** [Homebrew/brew#17657]
### `brew doctor` output

```shell
❯ brew doctor
Error: 502 Gateway Error
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/open-uri.rb:376:in `open_http'
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/open-uri.rb:770:in `buffer_open'
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/open-uri.rb:220:in `block in open_loop'
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/open-uri.rb:218:in `catch'
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/open-uri.rb:218:in `open_loop'
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/open-uri.rb:158:in `open_uri'
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/open-uri.rb:750:in `open'
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/open-uri.rb:29:in `open'
/opt/homebrew/Library/Taps/nidnogg/homebrew-zeitfetch/Formula/zeitfetch.rb:10:in `<class:Zeitfetch>'
/opt/homebrew/Library/Taps/nidnogg/homebrew-zeitfetch/Formula/zeitfetch.rb:6:in `block in load_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:107:in `module_eval'
/opt/homebrew/Library/Homebrew/formulary.rb:107:in `block in load_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:119:in `load_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:150:in `load_formula_from_path'
/opt/homebrew/Library/Homebrew/formulary.rb:582:in `load_file'
/opt/homebrew/Library/Homebrew/formulary.rb:807:in `load_file'
/opt/homebrew/Library/Homebrew/formulary.rb:573:in `klass'
/opt/homebrew/Library/Homebrew/formulary.rb:568:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:797:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:1013:in `factory'
/opt/homebrew/Library/Homebrew/formulary.rb:1104:in `from_keg'
/opt/homebrew/Library/Homebrew/formulary.rb:1055:in `from_rack'
/opt/homebrew/Library/Homebrew/diagnostic.rb:730:in `block in check_for_unreadable_installed_formula'
/opt/homebrew/Library/Homebrew/diagnostic.rb:729:in `each'
/opt/homebrew/Library/Homebrew/diagnostic.rb:729:in `check_for_unreadable_installed_formula'
/opt/homebrew/Library/Homebrew/cmd/doctor.rb:59:in `block in run'
/opt/homebrew/Library/Homebrew/cmd/doctor.rb:52:in `each'
/opt/homebrew/Library/Homebrew/cmd/doctor.rb:52:in `run'
/opt/homebrew/Library/Homebrew/brew.rb:92:in `<main>'
If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/nidnogg/homebrew-zeitfetch/issues/new
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
❯ brew config
HOMEBREW_VERSION: 4.3.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1c98a33a376e5b35ebc801d0f7d6ba7b9eb118ac
Last commit: 18 hours ago
Core tap JSON: 08 Jul 18:43 UTC
Core cask tap JSON: 08 Jul 18:47 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: hx
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 3.3.3 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/bin/ruby
CPU: octa-core 64-bit arm_blizzard_avalanche
Clang: 15.0.0 build 1500
Git: 2.45.2 => /opt/homebrew/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: N/A
Rosetta 2: false
❯ brew update
==> Updating Homebrew...
Error: Failed to download https://formulae.brew.sh/api/formula.jws.json!
Failed to download https://formulae.brew.sh/api/cask.jws.json!
Failed to download https://formulae.brew.sh/api/formula_tap_migrations.jws.json!
```

### What were you trying to do (and why)?

brew update

### What happened (include all command output)?

❯ brew update
==> Updating Homebrew...
Error: Failed to download https://formulae.brew.sh/api/formula.jws.json!
Failed to download https://formulae.brew.sh/api/cask.jws.json!
Failed to download https://formulae.brew.sh/api/formula_tap_migrations.jws.json!

### What did you expect to happen?

Brew to update

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
❯ brew update
==> Updating Homebrew...
Error: Failed to download https://formulae.brew.sh/api/formula.jws.json!
Failed to download https://formulae.brew.sh/api/cask.jws.json!
Failed to download https://formulae.brew.sh/api/formula_tap_migrations.jws.json!
```

**Comment by ironfish** [comment]
Seems to be working now. Closing issue.

**Comment by MikeMcQuaid** [comment]
> ```shell
> If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
>   https://github.com/nidnogg/homebrew-zeitfetch/issues/new
> ```

In future: do this.

**Comment by yurikoles** [comment]
Maybe at [formulae.brew.sh](../formulae.brew.sh/issues)?
```sh
❯ brew update
==> Updating Homebrew...
Error: Failed to download https://formulae.brew.sh/api/formula.jws.json!
Failed to download https://formulae.brew.sh/api/cask.jws.json!
Failed to download https://formulae.brew.sh/api/formula_tap_migrations.jws.json!
```
