### ISSUE TITLE
`Error: bad URI(is not URI?):` when search item contains a space 

### ISSUE THREAD

**Issue by psawa** [Homebrew/brew#17752]
### `brew doctor` output

```shell
(base) user@macbook:~$ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.3.9-225-g0f120b0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0f120b0837b869e609437adb1508effee8947b93
Last commit: 6 hours ago
Core tap JSON: 15 Jul 09:17 UTC
Core cask tap JSON: 15 Jul 09:17 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4/bin/ruby
CPU: octa-core 64-bit arm_blizzard_avalanche
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.4
Rosetta 2: false
```

### What were you trying to do (and why)?

Search for a formula by name, where name containing a space 

### What happened (include all command output)?

```
$ brew search modern csv
==> Casks
modern-csv
Error: bad URI(is not URI?): "modern csv"
Warning: Removed Sorbet lines from backtrace!
Rerun with `--verbose` to see the original backtrace
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4/lib/ruby/3.3.0/uri/rfc3986_parser.rb:130:in `split'
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4/lib/ruby/3.3.0/uri/rfc3986_parser.rb:135:in `parse'
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4/lib/ruby/3.3.0/uri/common.rb:185:in `parse'
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4/lib/ruby/3.3.0/uri/common.rb:846:in `URI'
/opt/homebrew/Library/Homebrew/formulary.rb:701:in `try_new'
/opt/homebrew/Library/Homebrew/formulary.rb:1216:in `block in loader_for'
/opt/homebrew/Library/Homebrew/formulary.rb:1215:in `each'
/opt/homebrew/Library/Homebrew/formulary.rb:1215:in `loader_for'
/opt/homebrew/Library/Homebrew/formulary.rb:1155:in `path'
/opt/homebrew/Library/Homebrew/missing_formula.rb:131:in `deleted_reason'
/opt/homebrew/Library/Homebrew/missing_formula.rb:12:in `reason'
/opt/homebrew/Library/Homebrew/cmd/search.rb:154:in `print_missing_formula_help'
/opt/homebrew/Library/Homebrew/cmd/search.rb:146:in `print_results'
/opt/homebrew/Library/Homebrew/cmd/search.rb:82:in `run'
/opt/homebrew/Library/Homebrew/brew.rb:95:in `<main>'
Please report this issue:
  https://docs.brew.sh/Troubleshooting
```

### What did you expect to happen?

I expected brew search to be able to handle spaces in the search terms. While I am not sure, I have the impression that it used to work in the past.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
(base) user@mac:~$ brew update
==> Updating Homebrew...
Already up-to-date.
(base) user@mac:~$ brew doctor
Your system is ready to brew.
(base) user@mac:~$ brew search modern csv
==> Casks
modern-csv
Error: bad URI(is not URI?): "modern csv"
Warning: Removed Sorbet lines from backtrace!
Rerun with `--verbose` to see the original backtrace
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4/lib/ruby/3.3.0/uri/rfc3986_parser.rb:130:in `split'
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4/lib/ruby/3.3.0/uri/rfc3986_parser.rb:135:in `parse'
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4/lib/ruby/3.3.0/uri/common.rb:185:in `parse'
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4/lib/ruby/3.3.0/uri/common.rb:846:in `URI'
/opt/homebrew/Library/Homebrew/formulary.rb:701:in `try_new'
/opt/homebrew/Library/Homebrew/formulary.rb:1216:in `block in loader_for'
/opt/homebrew/Library/Homebrew/formulary.rb:1215:in `each'
/opt/homebrew/Library/Homebrew/formulary.rb:1215:in `loader_for'
/opt/homebrew/Library/Homebrew/formulary.rb:1155:in `path'
/opt/homebrew/Library/Homebrew/missing_formula.rb:131:in `deleted_reason'
/opt/homebrew/Library/Homebrew/missing_formula.rb:12:in `reason'
/opt/homebrew/Library/Homebrew/cmd/search.rb:154:in `print_missing_formula_help'
/opt/homebrew/Library/Homebrew/cmd/search.rb:146:in `print_results'
/opt/homebrew/Library/Homebrew/cmd/search.rb:82:in `run'
/opt/homebrew/Library/Homebrew/brew.rb:95:in `<main>'
Please report this issue:
  https://docs.brew.sh/Troubleshooting
(base) user@mac:~$ 
```
```

**Comment by Rylan12** [comment]
Thanks for the report! I've opened a PR to fix this
