### ISSUE TITLE
cmake ninja dfu-util

### ISSUE THREAD

**Issue by MasterSkillNoob** [Homebrew/brew#17781]
### `brew doctor` output

```shell
Error: no implicit conversion of false into String
/home/york/homebrew/Library/Homebrew/utils/popen.rb:47:in `initialize'
/home/york/homebrew/Library/Homebrew/utils/popen.rb:47:in `popen'
/home/york/homebrew/Library/Homebrew/utils/popen.rb:47:in `popen'
/home/york/homebrew/Library/Homebrew/utils/popen.rb:9:in `popen_read'
/home/york/homebrew/Library/Homebrew/os/linux/ld.rb:13:in `brewed_ld_so_diagnostics'
/home/york/homebrew/Library/Homebrew/os/linux/ld.rb:23:in `sysconfdir'
/home/york/homebrew/Library/Homebrew/os/linux/ld.rb:44:in `library_paths'
/home/york/homebrew/Library/Homebrew/os/linux/elf.rb:165:in `find_full_lib_path'
/home/york/homebrew/Library/Homebrew/os/linux/elf.rb:131:in `block in initialize'
/home/york/homebrew/Library/Homebrew/os/linux/elf.rb:131:in `map'
/home/york/homebrew/Library/Homebrew/os/linux/elf.rb:131:in `initialize'
/home/york/homebrew/Library/Homebrew/os/linux/elf.rb:213:in `new'
/home/york/homebrew/Library/Homebrew/os/linux/elf.rb:213:in `metadata'
/home/york/homebrew/Library/Homebrew/os/linux/elf.rb:222:in `dynamically_linked_libraries'
/home/york/homebrew/Library/Homebrew/linkage_checker.rb:115:in `block in check_dylibs'
/home/york/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/pathname.rb:577:in `block in find'
/home/york/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/find.rb:51:in `block (2 levels) in find'
/home/york/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/find.rb:50:in `catch'
/home/york/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/find.rb:50:in `block in find'
/home/york/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/find.rb:45:in `each'
/home/york/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/find.rb:45:in `find'
/home/york/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/pathname.rb:577:in `find'
/home/york/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/forwardable.rb:240:in `find'
/home/york/homebrew/Library/Homebrew/linkage_checker.rb:108:in `check_dylibs'
/home/york/homebrew/Library/Homebrew/extend/os/linux/linkage_checker.rb:32:in `check_dylibs'
/home/york/homebrew/Library/Homebrew/linkage_checker.rb:32:in `initialize'
/home/york/homebrew/Library/Homebrew/upgrade.rb:261:in `new'
/home/york/homebrew/Library/Homebrew/upgrade.rb:261:in `block (2 levels) in check_broken_dependents'
/home/york/homebrew/Library/Homebrew/upgrade.rb:256:in `select'
/home/york/homebrew/Library/Homebrew/upgrade.rb:256:in `block in check_broken_dependents'
/home/york/homebrew/Library/Homebrew/cache_store.rb:26:in `use'
/home/york/homebrew/Library/Homebrew/upgrade.rb:253:in `check_broken_dependents'
/home/york/homebrew/Library/Homebrew/upgrade.rb:306:in `check_installed_dependents'
/home/york/homebrew/Library/Homebrew/cmd/install.rb:320:in `run'
/home/york/homebrew/Library/Homebrew/brew.rb:92:in `<main>'
Please report this issue:
  https://docs.brew.sh/Troubleshooting
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
Error: no implicit conversion of false into String
/home/york/homebrew/Library/Homebrew/utils/popen.rb:47:in `initialize'
/home/york/homebrew/Library/Homebrew/utils/popen.rb:47:in `popen'
/home/york/homebrew/Library/Homebrew/utils/popen.rb:47:in `popen'
/home/york/homebrew/Library/Homebrew/utils/popen.rb:9:in `popen_read'
/home/york/homebrew/Library/Homebrew/os/linux/ld.rb:13:in `brewed_ld_so_diagnostics'
/home/york/homebrew/Library/Homebrew/os/linux/ld.rb:23:in `sysconfdir'
/home/york/homebrew/Library/Homebrew/os/linux/ld.rb:44:in `library_paths'
/home/york/homebrew/Library/Homebrew/os/linux/elf.rb:165:in `find_full_lib_path'
/home/york/homebrew/Library/Homebrew/os/linux/elf.rb:131:in `block in initialize'
/home/york/homebrew/Library/Homebrew/os/linux/elf.rb:131:in `map'
/home/york/homebrew/Library/Homebrew/os/linux/elf.rb:131:in `initialize'
/home/york/homebrew/Library/Homebrew/os/linux/elf.rb:213:in `new'
/home/york/homebrew/Library/Homebrew/os/linux/elf.rb:213:in `metadata'
/home/york/homebrew/Library/Homebrew/os/linux/elf.rb:222:in `dynamically_linked_libraries'
/home/york/homebrew/Library/Homebrew/linkage_checker.rb:115:in `block in check_dylibs'
/home/york/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/pathname.rb:577:in `block in find'
/home/york/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/find.rb:51:in `block (2 levels) in find'
/home/york/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/find.rb:50:in `catch'
/home/york/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/find.rb:50:in `block in find'
/home/york/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/find.rb:45:in `each'
/home/york/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/find.rb:45:in `find'
/home/york/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/pathname.rb:577:in `find'
/home/york/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/forwardable.rb:240:in `find'
/home/york/homebrew/Library/Homebrew/linkage_checker.rb:108:in `check_dylibs'
/home/york/homebrew/Library/Homebrew/extend/os/linux/linkage_checker.rb:32:in `check_dylibs'
/home/york/homebrew/Library/Homebrew/linkage_checker.rb:32:in `initialize'
/home/york/homebrew/Library/Homebrew/upgrade.rb:261:in `new'
/home/york/homebrew/Library/Homebrew/upgrade.rb:261:in `block (2 levels) in check_broken_dependents'
/home/york/homebrew/Library/Homebrew/upgrade.rb:256:in `select'
/home/york/homebrew/Library/Homebrew/upgrade.rb:256:in `block in check_broken_dependents'
/home/york/homebrew/Library/Homebrew/cache_store.rb:26:in `use'
/home/york/homebrew/Library/Homebrew/upgrade.rb:253:in `check_broken_dependents'
/home/york/homebrew/Library/Homebrew/upgrade.rb:306:in `check_installed_dependents'
/home/york/homebrew/Library/Homebrew/cmd/install.rb:320:in `run'
/home/york/homebrew/Library/Homebrew/brew.rb:92:in `<main>'
Please report this issue:
  https://docs.brew.sh/Troubleshooting
```

### What were you trying to do (and why)?

brew install cmake ninja dfu-util

### What happened (include all command output)?

by end issu

### What did you expect to happen?

no error

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
i copy it and past it
```

**Comment by gromgit** [comment]
Try `brew update-reset`, then run `brew config` and `brew doctor` again.

**Comment by Bo98** [comment]
Closing due to no response. Your issue seems similar to #17828 so feel free to comment there with any further details.
