### ISSUE TITLE
"undefined method `chomp' for nil" When brew update

### ISSUE THREAD

**Issue by xycabcd** [Homebrew/brew#17894]
### `brew doctor` output

```
xyc@ycMacBook Desktop % /Users/xyc/Desktop/brewTest/bin/brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Your Homebrew's prefix is not /usr/local.

Many of Homebrew's bottles (binary packages) can only be used with the default prefix.
Consider uninstalling Homebrew and reinstalling into the default prefix.
It is expected behaviour that some formulae will fail to build in this unsupported configuration.
It is expected behaviour that Homebrew will be buggy and slow.
Do not create any issues about this on Homebrew's GitHub repositories.
Do not create any issues even if you think this message is unrelated.
Any opened issues will be immediately closed without response.
Do not ask for help from Homebrew or its maintainers on social media.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.


Warning: Homebrew's "bin" was not found in your PATH.
Consider setting your PATH for example like so:
  echo 'export PATH="/Users/xyc/Desktop/brewTest/bin:$PATH"' >> ~/.zshrc
```

### Verification

- [ ] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [x] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```
xyc@ycMacBook Desktop % /Users/xyc/Desktop/brewTest/bin/brew config
HOMEBREW_VERSION: >=4.1.0 (shallow or no git repository)
ORIGIN: https://github.com/xycabcd/brewTest
HEAD: 077b4edcc5ff1145a72b12a7aaa7bba7e609249c
Last commit: 4 minutes ago
Core tap JSON: 29 Jul 13:29 UTC
Core cask tap JSON: 29 Jul 13:29 UTC
HOMEBREW_PREFIX: /Users/xyc/Desktop/brewTest
HOMEBREW_REPOSITORY: /Users/xyc/Desktop/brewTest
HOMEBREW_CELLAR: /Users/xyc/Desktop/brewTest/Cellar
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 3.3.4 => /Users/xyc/Desktop/brewTest/Library/Homebrew/vendor/portable-ruby/3.3.4/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-x86_64
CLT: N/A
Xcode: 15.4
```

### What were you trying to do (and why)?

run `brew update`

### What happened (include all command output)?

It says :
```
xyc@ycMacBook ~ % /Users/xyc/Desktop/brewTest/bin/brew update
==> Updating Homebrew...
To restore the stashed changes to /Users/Shared/Homebrew, run:
  cd /Users/Shared/Homebrew && git stash pop
Error: undefined method `chomp' for nil
/Users/Shared/Homebrew/Library/Homebrew/cmd/update-report.rb:118:in `output_update_report'
/Users/Shared/Homebrew/Library/Homebrew/cmd/update-report.rb:33:in `run'
/Users/Shared/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
Please report this issue:
  https://docs.brew.sh/Troubleshooting
```

### What did you expect to happen?

Successfully Updated

### Step-by-step reproduction instructions (by running `brew` commands)

fork from Homebrew.
clone it to local and do `brew update`
make any change
do `brew update` again

### Also
I'm really sorry that `brew doctor` didn't says that my system is ready, but I really don't have an enviroment to put a new fork of Homebrew into `/usr/local`. But I'm pretty sure that this problem isn't cause by a different prefix.

**Comment by Bo98** [comment]
> `ORIGIN: https://github.com/xycabcd/brewTest`

This will be why - your fork isn't set up correctly. Please don't change origin.
