### ISSUE TITLE
"brew upgrade" fails with "Error: Version must not be empty"

### ISSUE THREAD

**Issue by llimllib** [Homebrew/brew#17898]
### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  neofetch
  openssl@1.1
  python-packaging
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.3.11-3-g38e47ea
ORIGIN: https://github.com/Homebrew/brew
HEAD: 38e47ea9964a6991125d44a373a7de038b70ee10
Last commit: 61 minutes ago
Core tap HEAD: 04fbd71d56ad72b201449d1d1ad96a3510673957
Core tap last commit: 6 months ago
Core tap JSON: 29 Jul 15:37 UTC
Core cask tap HEAD: 1a98cd7bf4117c79d6c79916d06cb9223b084844
Core cask tap last commit: 6 months ago
Core cask tap JSON: 29 Jul 14:47 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BAT_THEME: ansi
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /opt/homebrew/bin/nvim
HOMEBREW_MAKE_JOBS: 12
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 15.0.0 build 1500
Git: 2.42.0 => /opt/homebrew/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.4
Rosetta 2: false
```

### What were you trying to do (and why)?

`brew upgrade`

### What happened (include all command output)?

```
$ brew upgrade --verbose --debug
/usr/bin/env PATH=/opt/homebrew/opt/gh/bin:/opt/homebrew/Library/Homebrew/shims/shared:/usr/bin:/bin:/usr/sbin:/sbin HOME=/Users/llimllib gh auth token --hostname github.com
==> Downloading https://formulae.brew.sh/api/formula.jws.json
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/4.3.11-3-g38e47ea\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --fail --remote-time --output /Users/llimllib/Library/Caches/Homebrew/api/formula.jws.json --location --time-cond /Users/llimllib/Library/Caches/Homebrew/api/formula.jws.json --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.11-3-g38e47ea\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --fail --compressed --speed-limit 100 --speed-time 5 https://formulae.brew.sh/api/formula.jws.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4287k  100 4287k    0     0  7410k      0 --:--:-- --:--:-- --:--:-- 7404k
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading gh
/usr/bin/env /opt/homebrew/bin/gh --version
Error: Version must not be empty
/opt/homebrew/Library/Homebrew/version.rb:497:in `initialize'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11495/lib/types/private/methods/call_validation.rb:167:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11495/lib/types/private/methods/call_validation.rb:167:in `validate_call_skip_block_type'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11495/lib/types/private/methods/call_validation.rb:109:in `block in create_validator_slow_skip_block_type'
/opt/homebrew/Library/Homebrew/attestation.rb:86:in `new'
/opt/homebrew/Library/Homebrew/attestation.rb:86:in `block in gh_executable'
/opt/homebrew/Library/Homebrew/extend/kernel.rb:534:in `with_env'
/opt/homebrew/Library/Homebrew/attestation.rb:83:in `gh_executable'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11495/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11495/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11495/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/attestation.rb:114:in `sort_formulae_for_install'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11495/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11495/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11495/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:137:in `run'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11495/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11495/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11495/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/brew.rb:95:in `<main>'
Please report this issue:
  https://docs.brew.sh/Troubleshooting
```

### What did you expect to happen?

brew upgrade to succeed

### Step-by-step reproduction instructions (by running `brew` commands)

I don't have an exact repro; @carlocab asked me to file an issue in [this discussion](https://github.com/orgs/Homebrew/discussions/5530#discussioncomment-10181269). My best guess is:

- set brew to this version:
```
$ brew --version
Homebrew 4.3.11-3-g38e47ea
Homebrew/homebrew-core (git revision 04fbd71d56a; last commit 2024-01-23)
Homebrew/homebrew-cask (git revision 1a98cd7bf4; last commit 2024-01-23)
```
- Install `gh` from version `HEAD-53c36d0` (not sure how to tell brew to do that)
- `brew upgrade`

One feature thought: it seems like homebrew ought to log the formula that failed without needing to run `--debug`

**Comment by woodruffw** [comment]
Thanks @llimllib! This will be fixed by #17899.
