### ISSUE TITLE
IRB no longer has irb_at_exit method

### ISSUE THREAD

**Issue by onlynone** [Homebrew/brew#17921]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.3.12-30-ga396c2f
ORIGIN: https://github.com/Homebrew/brew
HEAD: a396c2f8a2b6c2f80a987ab8ea337b0d2115e2f0
Last commit: 33 minutes ago
Core tap HEAD: eaa9dc33038996847f8ae7e2637dbb6e9a2546c0
Core tap last commit: 15 minutes ago
Core tap JSON: 09 May 15:36 UTC
Core cask tap HEAD: 95b733c705dceb0effd718af4925445c29b284e4
Core cask tap last commit: 23 minutes ago
Core cask tap JSON: 09 May 15:36 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.6h1UxUaXXs/org.xquartz:0
HOMEBREW_EDITOR: emacs
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: set
HOMEBREW_NO_INSTALL_CLEANUP: set
HOMEBREW_NO_INSTALL_FROM_API: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.45.1 => /opt/homebrew/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.3.1-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: 15.2
Rosetta 2: false
```

### What were you trying to do (and why)?

Debug a new formula.

### What happened (include all command output)?

After closing the irb shell, there's an error about how there's no `irb_at_exit` variable or method in `IRB`:

```
irb(new-formula):005> 

==> Temporary files retained at:
/private/tmp/docker-dns-20240731-85399-4i239i
Error: An exception occurred within a child process:
  NameError: undefined local variable or method `irb_at_exit' for module IRB
/opt/homebrew/Library/Homebrew/debrew/irb.rb:29:in `start_within'
/opt/homebrew/Library/Homebrew/debrew.rb:120:in `block (5 levels) in debug'
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4/lib/ruby/3.3.0/mutex_m.rb:77:in `synchronize'
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4/lib/ruby/3.3.0/mutex_m.rb:77:in `mu_synchronize'
/opt/homebrew/Library/Homebrew/debrew.rb:118:in `block (4 levels) in debug'
/opt/homebrew/Library/Homebrew/ignorable.rb:35:in `raise'
/opt/homebrew/Library/Homebrew/formula.rb:3058:in `block in system'
/opt/homebrew/Library/Homebrew/formula.rb:2994:in `open'
/opt/homebrew/Library/Homebrew/formula.rb:2994:in `system'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11501/lib/types/private/methods/call_validation.rb:167:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11501/lib/types/private/methods/call_validation.rb:167:in `validate_call_skip_block_type'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11501/lib/types/private/methods/call_validation.rb:109:in `block in create_validator_slow_skip_block_type'
```

Here's what I can see about irb when the session is still live:

```
BuildError: Failed executing: false
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 4
When you exit this IRB session, execution will continue.
irb(docker-dns):001> IRB.version
=> "irb 1.13.1 (2024-05-05)"
irb(docker-dns):002> IRB.method(:version).source_location
=> ["/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4/lib/ruby/3.3.0/irb/init.rb", 41]
irb(docker-dns):003> IRB.method(:irb_at_exit)
(irb):3:in `method': undefined method `irb_at_exit' for class `#<Class:IRB>' (NameError)
	from (irb):3:in `raise'
	from <internal:kernel>:187:in `loop'
	from /opt/homebrew/Library/Homebrew/debrew.rb:120:in `block (5 levels) in debug'
	from /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4/lib/ruby/3.3.0/mutex_m.rb:77:in `synchronize'
	from /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4/lib/ruby/3.3.0/mutex_m.rb:77:in `mu_synchronize'
	from /opt/homebrew/Library/Homebrew/debrew.rb:118:in `block (4 levels) in debug'
	from /opt/homebrew/Library/Homebrew/ignorable.rb:35:in `raise'
	from /opt/homebrew/Library/Homebrew/formula.rb:3058:in `block in system'
	from /opt/homebrew/Library/Homebrew/formula.rb:2994:in `open'
	from /opt/homebrew/Library/Homebrew/formula.rb:2994:in `system'
	from /opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11501/lib/types/private/methods/call_validation.rb:167:in `bind_call'
	from /opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11501/lib/types/private/methods/call_validation.rb:167:in `validate_call_skip_block_type'
	from /opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11501/lib/types/private/methods/call_validation.rb:109:in `block in create_validator_slow_skip_block_type'
```

So it looks like you're using ruby 3.3.4 which comes bundled with irb-1.13.1. But the `irb_at_exit` method was removed from irb back in irb-1.6.4:

https://github.com/ruby/irb/pull/554/files#diff-47c7db963078b26254124a03825554105d46c8b153dbb15c9aad4a20350223fb

And every version of irb bundled with ruby since ruby-3.3.0:

https://github.com/ruby/ruby/commit/f25791884c8efa5ea6598c82ae5015f5fcfb8ebb#diff-47c7db963078b26254124a03825554105d46c8b153dbb15c9aad4a20350223fb

### What did you expect to happen?

After closing the irb shell, execution would continue.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ brew install -vd new-formula # that has system "false" in the install stanza
[... lots of trimmed logs...]
BuildError: Failed executing: false
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 4
When you exit this IRB session, execution will continue.
irb(new-formula):001> exit
==> Temporary files retained at:
/private/tmp/docker-dns-20240731-4126-p5kuu1
Error: An exception occurred within a child process:
  NameError: undefined local variable or method `irb_at_exit' for module IRB
```

**Comment by onlynone** [comment]
I tried creating the issue with a reference to the line in question, but I guess that doesn't make it through when a template is used... anyway, there's the line:

https://github.com/Homebrew/brew/blob/a396c2f8a2b6c2f80a987ab8ea337b0d2115e2f0/Library/Homebrew/debrew/irb.rb#L29

**Comment by Bo98** [comment]
A lot of that code is indeed quite old. I think basically everything Line 16 and down can be replaced with `irb.run(@CONF)` now.
