### ISSUE TITLE
brew upgrade or install fails with comparison of PkgVersion with String

### ISSUE THREAD

**Issue by daviehh** [Homebrew/brew#18029]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.3.15-46-gaafa81b
ORIGIN: https://github.com/Homebrew/brew
HEAD: aafa81b3d9612613118654c8f66b9e6d34c65b11
Last commit: 8 minutes ago
Core tap JSON: 12 Aug 19:36 UTC
Core cask tap JSON: 12 Aug 19:36 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.46.0 => /opt/homebrew/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 14.6.1-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.4
Rosetta 2: false
```

### What were you trying to do (and why)?

`brew upgrade`

or `brew install` anything

### What happened (include all command output)?

```
brew upgrade                                                                                                                                                        03:29:53 PM
Error: comparison of PkgVersion with String failed
Warning: Removed Sorbet lines from backtrace!
Rerun with `--verbose` to see the original backtrace
/opt/homebrew/Library/Homebrew/attestation.rb:66:in `<'
/opt/homebrew/Library/Homebrew/attestation.rb:66:in `enabled?'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:137:in `run'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
Please report this issue:
  https://docs.brew.sh/Troubleshooting
```

and verbose,
```
brew upgrade --verbose                                                                                                                                              03:29:58 PM
Error: comparison of PkgVersion with String failed
/opt/homebrew/Library/Homebrew/attestation.rb:66:in `<'
/opt/homebrew/Library/Homebrew/attestation.rb:66:in `enabled?'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11518/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11518/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11518/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:137:in `run'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11518/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11518/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11518/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
Please report this issue:
  https://docs.brew.sh/Troubleshooting
```

### What did you expect to happen?

command works

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew upgrade`
```

**Comment by daviehh** [comment]
saw the report submitted around the same time (was not there when drafting this report)

https://github.com/Homebrew/brew/issues/18028

closing in favor of that one.
