### ISSUE TITLE
brew create crashes

### ISSUE THREAD

**Issue by ahundt** [Homebrew/brew#1821]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with Homebrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new

Brew create seems to crash:
```
± brew create https://github.com/gabime/spdlog
Formula name [spdlog]:
Error: version '#<Version::NULL>' should be a string
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Homebrew/resource.rb:168:in `detect_version'
/usr/local/Homebrew/Library/Homebrew/resource.rb:149:in `version'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/create.rb:153:in `generate!'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/create.rb:91:in `create'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

```
± brew config
HOMEBREW_VERSION: 1.1.6-45-g9cce3414fb
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9cce3414fbd39d146d97911dbb3bf07fffaa1080
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 96ffdc930ed3e0a295dcc35a788c282b3205452f
Core tap last commit: 8 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.11.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.0/bin/ruby
Java: 1.8.0_25, 1.8.0_20
macOS: 10.11.6-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.9 => /opt/X11
```

**Comment by bfontaine** [comment]
`brew create` takes a tarball URL:

```
EDITOR=cat brew create https://github.com/gabime/spdlog/archive/v0.11.0.tar.gz
==> Downloading https://github.com/gabime/spdlog/archive/v0.11.0.tar.gz
==> Downloading from https://codeload.github.com/gabime/spdlog/tar.gz/v0.11.0
######################################################################## 100.0%
Please `brew audit --new-formula spdlog` before submitting, thanks.
Editing /home/baptiste/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/spdlog.rb
# Documentation: https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md
#                http://www.rubydoc.info/github/Homebrew/brew/master/Formula
# PLEASE REMOVE ALL GENERATED COMMENTS BEFORE SUBMITTING YOUR PULL REQUEST!

class Spdlog < Formula
  desc ""
  homepage ""
  url "https://github.com/gabime/spdlog/archive/v0.11.0.tar.gz"
  sha256 "8c0f1810fb6b7d23fef70c2ea8b6fa6768ac8d18d6e0de39be1f48865e22916e"

  # depends_on "cmake" => :build

  def install
    # ENV.deparallelize  # if your formula fails when building in parallel

    # Remove unrecognized options if warned by configure
    system "./configure", "--disable-debug",
                          "--disable-dependency-tracking",
                          "--disable-silent-rules",
                          "--prefix=#{prefix}"
    # system "cmake", ".", *std_cmake_args
    system "make", "install" # if this fails, try separate make/make install steps
  end

  test do
    # `test do` will create, run in and delete a temporary directory.
    #
    # This test will fail and we won't accept that! It's enough to just replace
    # "false" with the main program this formula installs, but it'd be nice if you
    # were more thorough. Run the test with `brew test spdlog`. Options passed
    # to `brew install` such as `--HEAD` also need to be provided to `brew test`.
    #
    # The installed folder is not in the path, so use the entire path to any
    # executables being tested: `system "#{bin}/program", "do", "something"`.
    system "false"
  end
end
```

**Comment by ahundt** [comment]
ah that makes sense... I'll see if I can update the cookbook to clarify that
