### ISSUE TITLE
Brew appears to be broken

### ISSUE THREAD

**Issue by rocktavious** [Homebrew/brew#18300]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
rocktavious@Kyle-Rockman-OL-MBP internal % brew update
==> Updating Homebrew...
Already up-to-date.
rocktavious@Kyle-Rockman-OL-MBP internal % brew update
==> Updating Homebrew...
Already up-to-date.
rocktavious@Kyle-Rockman-OL-MBP internal % brew doctor
Error: formulae require at least a URL
Warning: Removed Sorbet lines from backtrace!
Rerun with `--verbose` to see the original backtrace
/usr/local/Homebrew/Library/Homebrew/formula.rb:319:in `determine_active_spec'
/usr/local/Homebrew/Library/Homebrew/formula.rb:253:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:571:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:571:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:800:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:1016:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:1107:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:1058:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:730:in `block in check_for_unreadable_installed_formula'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:729:in `each'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:729:in `check_for_unreadable_installed_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:59:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:52:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:52:in `run'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
Please report this issue:
  https://docs.brew.sh/Troubleshooting
rocktavious@Kyle-Rockman-OL-MBP internal % brew config
HOMEBREW_VERSION: 4.3.20-36-gf0be97f
ORIGIN: https://github.com/Homebrew/brew
HEAD: f0be97f59219c29e4c70decbd59cb04e24fbdf93
Last commit: 14 hours ago
Core tap JSON: 10 Sep 13:53 UTC
Core cask tap JSON: 10 Sep 13:53 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 16
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.4 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 15.0.0 build 1500
Git: 2.46.0 => /usr/local/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 14.6.1-x86_64
CLT: 15.3.0.0.1.1708646388
Xcode: N/A
```

### Verification

- [ ] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue. (edited to false after ticket creation because brew doctor is whats failing)
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Get brew into a healthy state to try and install a tap - but brew doctor is failing

### What happened (include all command output)?

```
rocktavious@Kyle-Rockman-OL-MBP internal % brew config
HOMEBREW_VERSION: 4.3.20-36-gf0be97f
ORIGIN: https://github.com/Homebrew/brew
HEAD: f0be97f59219c29e4c70decbd59cb04e24fbdf93
Last commit: 14 hours ago
Core tap JSON: 10 Sep 13:53 UTC
Core cask tap JSON: 10 Sep 13:53 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 16
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.4 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 15.0.0 build 1500
Git: 2.46.0 => /usr/local/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 14.6.1-x86_64
CLT: 15.3.0.0.1.1708646388
Xcode: N/A
```

### What did you expect to happen?

I expected `brew doctor` to not crash

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
rocktavious@Kyle-Rockman-OL-MBP internal % brew config
HOMEBREW_VERSION: 4.3.20-36-gf0be97f
ORIGIN: https://github.com/Homebrew/brew
HEAD: f0be97f59219c29e4c70decbd59cb04e24fbdf93
Last commit: 14 hours ago
Core tap JSON: 10 Sep 13:53 UTC
Core cask tap JSON: 10 Sep 13:53 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 16
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.4 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 15.0.0 build 1500
Git: 2.46.0 => /usr/local/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 14.6.1-x86_64
CLT: 15.3.0.0.1.1708646388
Xcode: N/A
```

**Comment by carlocab** [comment]
What's the output of `brew tap`?

**Comment by xakep8** [comment]
i think it is this pidof package that has a URL problem

**Comment by Rylan12** [comment]
> It would be nice if the error reported which formula was the problem.

Agreed. I'll open a PR to modify the error message
