### ISSUE TITLE
Ran brew update, now nothing works

### ISSUE THREAD

**Issue by externl** [Homebrew/brew#1831]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with Homebrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new

## What happened
I ran `brew update`. Now all brew commands fail with a similar error. Not really sure if this reall an issue with homebrew-php's composer formula, but since nothing in that repo was updated recently I'm guessing here is the right place to file this bug.

```
$ brew update
Updated 6 taps (caskroom/cask, homebrew/core, homebrew/dupes, homebrew/nginx, homebrew/services, homebrew/versions).
==> New Formulae
homebrew/nginx/openresty-debug            homebrew/nginx/openresty-openssl          homebrew/versions/mapnik2
==> Updated Formulae
autotrace                      grafana                        mktorrent                      stoken
bind                           homebrew/dupes/nano ✔          mongo-c-driver                 synfig
blockhash                      homebrew/versions/gnupg21      notmuch                        terraform
cattle                         imagemagick ✔                  openconnect ✔                  udunits
certbot ✔                      kobalt                         pstoedit                       vim ✔
darcs                          kubernetes-cli                 rancid                         zbar
dbt                            lmdb ✔                         ruby-build ✔
gnutls ✔                       macvim ✔                       rust ✔
$ brew upgrade
Error: cannot load such file -- /usr/local/opt/composer/Abstract/abstract-php-phar
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/opt/composer/.brew/composer.rb:1:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:97:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:255:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:289:in `rescue in from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:285:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:269:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1420:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1418:in `map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1418:in `installed'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:37:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Error: cannot load such file -- /usr/local/opt/php56/Abstract/abstract-php
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/opt/php56/.brew/php56.rb:1:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:97:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:255:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:289:in `rescue in from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:285:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:269:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:1022:in `block in check_for_unlinked_but_not_keg_only'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:1019:in `reject'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:1019:in `check_for_unlinked_but_not_keg_only'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:43:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

**Comment by bfontaine** [comment]
It seems to be an issue with the `homebrew/php/php56` formula: https://github.com/Homebrew/homebrew-php/blob/c8c5e4238a27f803cfe1c5e66e417cc153596e1f/Formula/php56.rb#L1

**Comment by externl** [comment]
I don't think so. All of the homebrew-php formulae do that.

**Comment by bfontaine** [comment]
Can you please run the following code then try again?

    cd $(brew --prefix)/Library/Taps/homebrew/homebrew-php && git fetch && git reset --hard origin/master

**Comment by externl** [comment]
Huh, so my php tap is suddenly missing...

**Comment by externl** [comment]
I re-taped, working now. I have no idea how my tap disappeared though...
