### ISSUE TITLE
Brew upgrade ran from another app error: undefined method `exitstatus' for nil

### ISSUE THREAD

**Issue by Pe8er** [Homebrew/brew#18706]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.4.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 91f3671b16fe62121364c465c14e0dfd088d7ead
Last commit: 7 days ago
Core tap JSON: 03 Nov 20:34 UTC
Core cask tap JSON: 03 Nov 20:34 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 3.3.5 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.5/bin/ruby
CPU: octa-core 64-bit arm_blizzard_avalanche
Clang: 16.0.0 build 1600
Git: 2.39.5 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.1-arm64
CLT: 16.1.0.0.1.1729049160
Xcode: 16.1
Rosetta 2: false
```

### What were you trying to do (and why)?

I have a brew widget in my [Sketchybar](https://github.com/FelixKratz/SketchyBar) setup. What is important: when I click on widget icon, it attempts to run command

`brew update && brew upgrade`

And errors out. Note: if I run this command via terminal, it works normally.

[Here's my widget code:](https://github.com/Pe8er/dotfiles/blob/57c8e78f26c782a08b1a256b3bd9ebe90a0e2487/config.symlink/sketchybar/items/brew.sh)

```bash
#!/bin/zsh

# Load global styles, colors and icons
source "$CONFIG_DIR/globalstyles.sh"

brew=(
  "${notification_defaults[@]}"
  icon=$ICON_PACKAGE
  script="$PLUGIN_DIR/brew.sh"
  click_script="brew update && brew upgrade"
)

sketchybar --add item  brew right            \
           --set       brew "${brew[@]}"
```

### What happened (include all command output)?

Error output:

```
==> Updating Homebrew...
Already up-to-date.
==> Upgrading 1 outdated package:
icu4c@76 76.1 -> 76.1_1
==> Downloading https://ghcr.io/v2/homebrew/core/icu4c/76
Error: undefined method `exitstatus' for nil
/opt/homebrew/Library/Homebrew/system_command.rb:388:in `initialize'
/opt/homebrew/Library/Homebrew/system_command.rb:74:in `new'
/opt/homebrew/Library/Homebrew/system_command.rb:74:in `run!'
/opt/homebrew/Library/Homebrew/system_command.rb:40:in `run'
/opt/homebrew/Library/Homebrew/system_command.rb:25:in `system_command'
/opt/homebrew/Library/Homebrew/utils/curl.rb:158:in `curl_with_workarounds'
/opt/homebrew/Library/Homebrew/utils/curl.rb:233:in `curl_output'
/opt/homebrew/Library/Homebrew/download_strategy.rb:580:in `curl_output'
/opt/homebrew/Library/Homebrew/utils/curl.rb:509:in `curl_version'
/opt/homebrew/Library/Homebrew/utils/curl.rb:239:in `curl_headers'
/opt/homebrew/Library/Homebrew/utils/curl.rb:207:in `curl_download'
/opt/homebrew/Library/Homebrew/download_strategy.rb:546:in `_curl_download'
/opt/homebrew/Library/Homebrew/download_strategy.rb:542:in `_fetch'
/opt/homebrew/Library/Homebrew/download_strategy.rb:428:in `fetch'
/opt/homebrew/Library/Homebrew/downloadable.rb:103:in `fetch'
/opt/homebrew/Library/Homebrew/resource.rb:155:in `fetch'
/opt/homebrew/Library/Homebrew/software_spec.rb:417:in `fetch_tab'
/opt/homebrew/Library/Homebrew/formula.rb:3173:in `fetch_bottle_tab'
/opt/homebrew/Library/Homebrew/formula_installer.rb:1289:in `fetch_bottle_tab'
/opt/homebrew/Library/Homebrew/formula_installer.rb:573:in `compute_dependencies'
/opt/homebrew/Library/Homebrew/formula_installer.rb:277:in `verify_deps_exist'
/opt/homebrew/Library/Homebrew/formula_installer.rb:264:in `prelude'
/opt/homebrew/Library/Homebrew/upgrade.rb:71:in `block in upgrade_formulae'
/opt/homebrew/Library/Homebrew/upgrade.rb:52:in `each'
/opt/homebrew/Library/Homebrew/upgrade.rb:52:in `filter_map'
/opt/homebrew/Library/Homebrew/upgrade.rb:52:in `upgrade_formulae'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:219:in `upgrade_outdated_formulae'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:136:in `run'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
Please report this issue:
  https://docs.brew.sh/Troubleshooting
```

I tried to apply the fix from [Common Issues page](https://docs.brew.sh/Common-Issues#brew-upgrade-errors-out) but `"$(brew --repository)/Library/Contributions/examples"` directory doesn't exist on my system.

I also uninstalled and reinstalled brew, and the issue persists.

OS: MacOs 15.1
Shell: zsh 5.9 (arm64-apple-darwin24.0)
Sketchybar: v2.21.0

### What did you expect to happen?

Update brew and upgrade brew normally.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Run `brew update && brew upgrade` via Sketchybar
```

**Comment by gromgit** [comment]
Try changing your click script to:
```
brew shellenv; brew update && brew upgrade
```
and see if it helps.

**Comment by carlocab** [comment]
This seems to be an issue with your setup rather than an issue with `brew`.

Please use the [discussions page](https://github.com/orgs/Homebrew/discussions) if you need more help with this.

**Comment by Pe8er** [comment]
@gromgit thanks but unfortunately that didn't work. @carlocab I'll create a new discussion, thanks for the pointer.
