### ISSUE TITLE
Can't install or upgrade any packages

### ISSUE THREAD

**Issue by pstinghua** [Homebrew/brew#18752]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.4.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 254bf3fe9d8fa2e1b2fb55dbcf535b2d870180c4
Last commit: 14 hours ago
Core tap JSON: 11 Nov 23:58 UTC
Core cask tap JSON: 11 Nov 23:58 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 3.3.6 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.6/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 16.0.0 build 1600
Git: 2.47.0 => /usr/local/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.1-x86_64
CLT: 16.1.0.0.1.1729049160
Xcode: 16.1
```

### What were you trying to do (and why)?

brew upgrade

### What happened (include all command output)?

```shell
==> Upgrading 7 outdated packages:
vim 9.1.0800 -> 9.1.0850
wget 1.24.5 -> 1.25.0
python-packaging 24.1_1 -> 24.2
c-ares 1.34.2 -> 1.34.3
kind 0.24.0 -> 0.25.0
jadx 1.5.0 -> 1.5.1
fzf 0.56.0 -> 0.56.2
==> Downloading https://ghcr.io/v2/homebrew/core/vim/manifests/9.1.0850
Already downloaded: /Users/xieyuanliang/Library/Caches/Homebrew/downloads/123510ef2e8d97392d2e81fc17c69f0933e12fb24e496b14e50d583c8657a7a3--vim-9.1.0850.bottle_manifest.json
==> Fetching vim
==> Downloading https://ghcr.io/v2/homebrew/core/vim/blobs/sha256:d5ba1f754cfbfbf7a06135be2dfab52b
Already downloaded: /Users/xieyuanliang/Library/Caches/Homebrew/downloads/16f3a3de77041f0b55e37a5b57c9fbc57d44ebf8ba0aac7b9e56d7fdc1a86866--vim--9.1.0850.sonoma.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/wget/manifests/1.25.0
Already downloaded: /Users/xieyuanliang/Library/Caches/Homebrew/downloads/3de072a2f67f68eba0252eb2bdd190bb864b5c35c81ea66bdee039f69d28cc4a--wget-1.25.0.bottle_manifest.json
==> Fetching wget
==> Downloading https://ghcr.io/v2/homebrew/core/wget/blobs/sha256:5650778a8e7a60c2dea9412dd21d2f5
Already downloaded: /Users/xieyuanliang/Library/Caches/Homebrew/downloads/9dafa674df1aded023f4bc92e9a65040a6cac509ebd6272e697b3aaafdc43de1--wget--1.25.0.sonoma.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/python-packaging/manifests/24.2
Already downloaded: /Users/xieyuanliang/Library/Caches/Homebrew/downloads/a654ed84d67e434e714ac548959721dfcfc2297e1cb87be9237baee7632a2b76--python-packaging-24.2.bottle_manifest.json
==> Fetching python-packaging
==> Downloading https://ghcr.io/v2/homebrew/core/python-packaging/blobs/sha256:81d0db4704a8a4d5332
Already downloaded: /Users/xieyuanliang/Library/Caches/Homebrew/downloads/2ce5bd24826be4f109b675fb9602e4c0e5424b4962c8f45612434da96167dade--python-packaging--24.2.all.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/c-ares/manifests/1.34.3
Already downloaded: /Users/xieyuanliang/Library/Caches/Homebrew/downloads/a7247aee29b6c331ce6ec6227ce4c11ab5aa34f2073cbcaa5977bdafe8c996b4--c-ares-1.34.3.bottle_manifest.json
==> Fetching c-ares
==> Downloading https://ghcr.io/v2/homebrew/core/c-ares/blobs/sha256:1e05842f0ed0d461ad12df47938ff
Already downloaded: /Users/xieyuanliang/Library/Caches/Homebrew/downloads/241f114b8b6c19e8d5f9637b165b61657a1c5edec2603ac1e2e5f0a9b989b233--c-ares--1.34.3.sonoma.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/kind/manifests/0.25.0
Already downloaded: /Users/xieyuanliang/Library/Caches/Homebrew/downloads/48d7239b0f9403ea32dbfc7301a6dad06a83dac5146b873db7801addf79617f2--kind-0.25.0.bottle_manifest.json
==> Fetching kind
==> Downloading https://ghcr.io/v2/homebrew/core/kind/blobs/sha256:072b9207013e8a64230fae40fdc55d3
Already downloaded: /Users/xieyuanliang/Library/Caches/Homebrew/downloads/41c4d8ec6ab230615dbac24666b90b53942d2dcee58eb48ee3e91f3ec2151ac1--kind--0.25.0.sonoma.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/jadx/manifests/1.5.1
########################################################################################### 100.0%
==> Fetching jadx
==> Downloading https://ghcr.io/v2/homebrew/core/jadx/blobs/sha256:735427c63f8e20f067a5a50d4273cea
########################################################################################### 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/fzf/manifests/0.56.2
Already downloaded: /Users/xieyuanliang/Library/Caches/Homebrew/downloads/bb60502aa049f26f1054f3c3ea258d716b88324a1a28cbc8da4c13dc962262b0--fzf-0.56.2.bottle_manifest.json
==> Fetching fzf
==> Downloading https://ghcr.io/v2/homebrew/core/fzf/blobs/sha256:620ef3d40401dab2e808f704116599c2
Already downloaded: /Users/xieyuanliang/Library/Caches/Homebrew/downloads/c1f6c702bc64a40d92304b458ae07b0dc1e69c38421f6cff51bf8622bd262b3f--fzf--0.56.2.sonoma.bottle.tar.gz
==> Upgrading vim
  9.1.0800 -> 9.1.0850
==> Pouring vim--9.1.0850.sonoma.bottle.tar.gz
cp: chflags: /usr/local/Cellar/vim: Operation not permitted
Error: Failure while executing; `/usr/bin/env cp -pR /private/tmp/homebrew-unpack-20241112-23761-3zx314/vim /usr/local/Cellar` exited with 1. Here's the output:
cp: chflags: /usr/local/Cellar/vim: Operation not permitted
```

### What did you expect to happen?

brew upgrade successfully

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew upgrade
```

**Comment by gromgit** [comment]
What's the output of `/bin/ls -lde@ /usr/local /usr/local/Cellar /usr/local/Cellar/vim`?

**Comment by pstinghua** [comment]
> /bin/ls -lde@ /usr/local /usr/local/Cellar /usr/local/Cellar/vim

drwxr-xr-x   15 xieyuanliang  admin   480 Oct 29 17:11 /usr/local
drwxrwxr-x  136 xieyuanliang  admin  4352 Nov 11 11:57 /usr/local/Cellar
drwxr-xr-x    3 xieyuanliang  admin    96 Nov 12 09:17 /usr/local/Cellar/vim

**Comment by gromgit** [comment]
Are you running an antivirus or other security software on your machine? If so, stop it and try `brew upgrade` again.

**Comment by pstinghua** [comment]
> Are you running an antivirus or other security software on your machine? If so, stop it and try `brew upgrade` again.

no

**Comment by gromgit** [comment]
Wait, is your username `xieyuanliang`? If not, you have to login as that user to run any `brew` command that changes the filesystem.

**Comment by pstinghua** [comment]
> Wait, is your username `xieyuanliang`? If not, you have to login as that user to run any `brew` command that changes the filesystem.

it's my username

**Comment by pstinghua** [comment]
```shell
whoami
xieyuanliang
```

**Comment by pstinghua** [comment]
> Wait, is your username `xieyuanliang`? If not, you have to login as that user to run any `brew` command that changes the filesystem.

```shell
whoami
xieyuanliang
```

**Comment by gromgit** [comment]
What's the output of `/bin/ls -ldeO@ /usr/local /usr/local/Cellar /usr/local/Cellar/vim`? (The `O` flag is new.)

**Comment by dieterdreist** [comment]
I also have similar issues. It happened since I upgraded from MacOS 13 to MacOS 15, I have tried removing and reinstalling homebrew, removing and reinstalling casks, setting ownership of /usr/local to $(whoami):admin, I gave full disk access to terminal and to /usr/bin/env and to "brew", and tried other things as well.

It seems the problem is limited to casks, other packages install. Strangely, also 2 casks were successfully installed despite the problems with the other casks (problems e.g. with libreoffice, blender, inkscape but no problems with android-platform-tools and gstreamer-runtime)


Here is a sample failure:

```
brew install inkscape
==> Downloading https://formulae.brew.sh/api/formula.jws.json
############################################################################################################################################################ 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
############################################################################################################################################################ 100.0%
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-cask/703893f437eb916725ea1ce887a315f072407d04/Casks/i/inkscape.rb
############################################################################################################################################################ 100.0%
==> Downloading https://media.inkscape.org/dl/resources/file/Inkscape-1.4.028868_arm64.dmg
Already downloaded: /Users/myself/Library/Caches/Homebrew/downloads/5ffcea429049dcf0d3e4bb5de0e4d2a9f639f9226909d22eaff31e3567a81fd5--Inkscape-1.4.028868_arm64.dmg
==> Installing Cask inkscape
hdiutil: attach failed - Permission denied
==> Purging files for version 1.4.028868 of Cask inkscape
Error: Failure while executing; `/usr/bin/env hdiutil attach -plist -nobrowse -readonly -mountrandom /Volumes/MyVolume/homebrew_temp/homebrew-dmg20241205-10493-ftnx0e /Volumes/MyVolume/homebrew_temp/homebrew-dmg20241205-10493-ftnx0e/5ffcea429049dcf0d3e4bb5de0e4d2a9f639f9226909d22eaff31e3567a81fd5--Inkscape-1.4.028868_arm64.cdr` exited with 1. Here's the output:
hdiutil: attach failed - Permission denied
```

I also tried to attach the dmg with hdiutil and it works. 
```
hdiutil attach /Users/myself/Library/Caches/Homebrew/downloads/5ffcea429049dcf0d3e4bb5de0e4d2a9f639f9226909d22eaff31e3567a81fd5--Inkscape-1.4.028868_arm64.dmg
expected CRC32 $1E0233EC
/dev/disk13         	GUID_partition_scheme          	
/dev/disk13s1       	Apple_HFS                      	/Volumes/Inkscape
```

**Comment by dieterdreist** [comment]
There is one thing that might be useful to know, it is on a M1 machine and I linked /opt/homebrew/ to an external drive /Volumes/myVolume/homebrew/

this is doctor:
```
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  spreet

Warning: The filesystem on /Volumes/myVolume appears to be case-sensitive.
The default macOS filesystem is case-insensitive. Please report any apparent problems.

Warning: gettext files detected at a system prefix.
These files can cause compilation and link failures, especially if they
are compiled with improper architectures. Consider removing these files:
  /opt/homebrew/lib/libgettextlib.dylib
  /opt/homebrew/lib/libintl.dylib
  /opt/homebrew/include/libintl.h

```




here is the install in debug mode:
```
brew install --cask inkscape --debug
==> Downloading https://formulae.brew.sh/api/cask.jws.json
/usr/bin/env /Volumes/myVolume/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/4.4.9\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 15.1.1\)\ curl/8.7.1 --header Accept-Language:\ en --fail --progress-bar --remote-time --output /Users/myUser/Library/Caches/Homebrew/api/cask.jws.json --location --time-cond /Users/myUser/Library/Caches/Homebrew/api/cask.jws.json --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.4.9\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 15.1.1\)\ curl/8.7.1 --header Accept-Language:\ en --fail --progress-bar --compressed --speed-limit 100 --speed-time 5 https://formulae.brew.sh/api/cask.jws.json
###################################################################################################################################################################### 100.0%
/Volumes/myVolume/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading inkscape
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
/usr/bin/env /Volumes/myVolume/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.4.9\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 15.1.1\)\ curl/8.7.1 --header Accept-Language:\ en --retry 3 -V
/usr/bin/env /Volumes/myVolume/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.4.9\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 15.1.1\)\ curl/8.7.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://raw.githubusercontent.com/Homebrew/homebrew-cask/c075073718330ff426f8c8a6e73822d52d36513b/Casks/i/inkscape.rb
/usr/bin/env /Volumes/myVolume/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.4.9\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 15.1.1\)\ curl/8.7.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET --http1.1 https://raw.githubusercontent.com/Homebrew/homebrew-cask/c075073718330ff426f8c8a6e73822d52d36513b/Casks/i/inkscape.rb
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-cask/c075073718330ff426f8c8a6e73822d52d36513b/Casks/i/inkscape.rb
/usr/bin/env /Volumes/myVolume/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.4.9\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 15.1.1\)\ curl/8.7.1 --header Accept-Language:\ en --fail --progress-bar --connect-timeout 15 --retry 3 --remote-time --output /Users/myUser/Library/Caches/Homebrew/downloads/6b6af6a8bf746fa7f062ba38a4b5046fa9d3b59576679201c17857efc256f861--inkscape.rb.incomplete --location https://raw.githubusercontent.com/Homebrew/homebrew-cask/c075073718330ff426f8c8a6e73822d52d36513b/Casks/i/inkscape.rb
###################################################################################################################################################################### 100.0%
==> Downloading https://media.inkscape.org/dl/resources/file/Inkscape-1.4.028868_arm64.dmg
/usr/bin/env /Volumes/myVolume/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.4.9\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 15.1.1\)\ curl/8.7.1 --header Accept-Language:\ en --retry 3 -V
/usr/bin/env /Volumes/myVolume/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.4.9\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 15.1.1\)\ curl/8.7.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://media.inkscape.org/dl/resources/file/Inkscape-1.4.028868_arm64.dmg
Already downloaded: /Users/myUser/Library/Caches/Homebrew/downloads/5ffcea429049dcf0d3e4bb5de0e4d2a9f639f9226909d22eaff31e3567a81fd5--Inkscape-1.4.028868_arm64.dmg
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -target arm64-apple-macosx15 /Volumes/myVolume/homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/myUser/Library/Caches/Homebrew/downloads/5ffcea429049dcf0d3e4bb5de0e4d2a9f639f9226909d22eaff31e3567a81fd5--Inkscape-1.4.028868_arm64.dmg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/myUser/Library/Caches/Homebrew/downloads/5ffcea429049dcf0d3e4bb5de0e4d2a9f639f9226909d22eaff31e3567a81fd5--Inkscape-1.4.028868_arm64.dmg
==> /Users/myUser/Library/Caches/Homebrew/downloads/5ffcea429049dcf0d3e4bb5de0e4d2a9f639f9226909d22eaff31e3567a81fd5--Inkscape-1.4.028868_arm64.dmg is quarantined
/usr/bin/env tar --list --file /Users/myUser/Library/Caches/Homebrew/downloads/5ffcea429049dcf0d3e4bb5de0e4d2a9f639f9226909d22eaff31e3567a81fd5--Inkscape-1.4.028868_arm64.dmg
/usr/bin/env hdiutil imageinfo -format /Users/myUser/Library/Caches/Homebrew/downloads/5ffcea429049dcf0d3e4bb5de0e4d2a9f639f9226909d22eaff31e3567a81fd5--Inkscape-1.4.028868_arm64.dmg
==> Installing Cask inkscape
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/myUser/Library/Caches/Homebrew/downloads/5ffcea429049dcf0d3e4bb5de0e4d2a9f639f9226909d22eaff31e3567a81fd5--Inkscape-1.4.028868_arm64.dmg
/usr/bin/env hdiutil attach -plist -nobrowse -readonly -mountrandom /Volumes/myVolume/homebrew_temp/homebrew-dmg20241205-16272-44kilx /Users/myUser/Library/Caches/Homebrew/downloads/5ffcea429049dcf0d3e4bb5de0e4d2a9f639f9226909d22eaff31e3567a81fd5--Inkscape-1.4.028868_arm64.dmg
/usr/bin/env hdiutil convert -quiet -format UDTO -o /Volumes/myVolume/homebrew_temp/homebrew-dmg20241205-16272-44kilx/5ffcea429049dcf0d3e4bb5de0e4d2a9f639f9226909d22eaff31e3567a81fd5--Inkscape-1.4.028868_arm64.cdr /Users/myUser/Library/Caches/Homebrew/downloads/5ffcea429049dcf0d3e4bb5de0e4d2a9f639f9226909d22eaff31e3567a81fd5--Inkscape-1.4.028868_arm64.dmg
/usr/bin/env hdiutil attach -plist -nobrowse -readonly -mountrandom /Volumes/myVolume/homebrew_temp/homebrew-dmg20241205-16272-44kilx /Volumes/myVolume/homebrew_temp/homebrew-dmg20241205-16272-44kilx/5ffcea429049dcf0d3e4bb5de0e4d2a9f639f9226909d22eaff31e3567a81fd5--Inkscape-1.4.028868_arm64.cdr
hdiutil: attach failed - Permission denied
==> Purging files for version 1.4.028868 of Cask inkscape
Error: Failure while executing; `/usr/bin/env hdiutil attach -plist -nobrowse -readonly -mountrandom /Volumes/myVolume/homebrew_temp/homebrew-dmg20241205-16272-44kilx /Volumes/myVolume/homebrew_temp/homebrew-dmg20241205-16272-44kilx/5ffcea429049dcf0d3e4bb5de0e4d2a9f639f9226909d22eaff31e3567a81fd5--Inkscape-1.4.028868_arm64.cdr` exited with 1. Here's the output:
hdiutil: attach failed - Permission denied

/Volumes/myVolume/homebrew/Library/Homebrew/system_command.rb:396:in `assert_success!'
/Volumes/myVolume/homebrew/Library/Homebrew/system_command.rb:75:in `run!'
/Volumes/myVolume/homebrew/Library/Homebrew/system_command.rb:40:in `run'
/Volumes/myVolume/homebrew/Library/Homebrew/system_command.rb:44:in `run!'
/Volumes/myVolume/homebrew/Library/Homebrew/system_command.rb:32:in `system_command!'
/Volumes/myVolume/homebrew/Library/Homebrew/unpack_strategy/dmg.rb:227:in `block in mount'
/Volumes/myVolume/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.6/lib/ruby/3.3.0/tmpdir.rb:99:in `mktmpdir'
/Volumes/myVolume/homebrew/Library/Homebrew/unpack_strategy/dmg.rb:197:in `mount'
/Volumes/myVolume/homebrew/Library/Homebrew/unpack_strategy/dmg.rb:186:in `extract_to_dir'
/Volumes/myVolume/homebrew/Library/Homebrew/unpack_strategy.rb:149:in `extract'
/Volumes/myVolume/homebrew/Library/Homebrew/unpack_strategy.rb:164:in `block in extract_nestedly'
/Volumes/myVolume/homebrew/Library/Homebrew/mktemp.rb:92:in `run'
/Volumes/myVolume/homebrew/Library/Homebrew/unpack_strategy.rb:161:in `extract_nestedly'
/Volumes/myVolume/homebrew/Library/Homebrew/cask/installer.rb:232:in `extract_primary_container'
/Volumes/myVolume/homebrew/Library/Homebrew/cask/installer.rb:84:in `stage'
/Volumes/myVolume/homebrew/Library/Homebrew/cask/installer.rb:111:in `install'
/Volumes/myVolume/homebrew/Library/Homebrew/cmd/install.rb:245:in `block in run'
/Volumes/myVolume/homebrew/Library/Homebrew/cmd/install.rb:234:in `each'
/Volumes/myVolume/homebrew/Library/Homebrew/cmd/install.rb:234:in `run'
/Volumes/myVolume/homebrew/Library/Homebrew/brew.rb:94:in `<main>'

```

**Comment by MikeMcQuaid** [comment]
> There is one thing that might be useful to know, it is on a M1 machine and I linked /opt/homebrew/ to an external drive /Volumes/myVolume/homebrew/

This seems very likely to break things. Don't do that.

**Comment by dieterdreist** [comment]
It worked for 4 years, since 2020, never had any problems. It still works for package installing and removing, just a few casks give this strange hdiutil permission problem.

**Comment by EricFromCanada** [comment]
Have you set `HOMEBREW_TEMP` to `/Volumes/myVolume/homebrew_temp`? Try unsetting that. Homebrew needs access to a temp directory when mounting .dmg files (but not for .zip or .pkg files, which is why installing android-platform-tools and gstreamer-runtime still worked).

**Comment by dieterdreist** [comment]
> Have you set `HOMEBREW_TEMP` to `/Volumes/myVolume/homebrew_temp`? Try unsetting that. Homebrew needs access to a temp directory when mounting .dmg files (but not for .zip or .pkg files, which is why installing android-platform-tools and gstreamer-runtime still worked).

THANK YOU, this did it. You are my hero, have been trying for 2 days...
