### ISSUE TITLE
brew unbottled not working as intended on both macos 15 and gnu+linux to list unbottled deps for vtk

### ISSUE THREAD

**Issue by ipatch** [Homebrew/brew#18993]
### `brew doctor` output

```shell
na
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
na
```

### What were you trying to do (and why)?

```
brew unbottled --tag arm64_sequoia --dependents -v vtk
```

### What happened (include all command output)?

running above command with homebrew on ubuntu 22.04 with homebrew setup in the default prefix gives me the below stack trace.

```
==> Populating dependency tree...
==> :arm64_sequoia bottle status
Error: uninitialized constant Homebrew::DevCmd::Unbottled::MacOS
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/unbottled.rb:242:in `block (2 levels) in output_unbottled'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.6/lib/ruby/3.3.0/set.rb:501:in `each_key'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.6/lib/ruby/3.3.0/set.rb:501:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.6/lib/ruby/3.3.0/delegate.rb:87:in `all?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.6/lib/ruby/3.3.0/delegate.rb:87:in `method_missing'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/unbottled.rb:233:in `block in output_unbottled'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/unbottled.rb:214:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/unbottled.rb:214:in `output_unbottled'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11708/lib/types/private/methods/call_validation.rb:278:in `bind_call'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11708/lib/types/private/methods/call_validation.rb:278:in `validate_call'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11708/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/unbottled.rb:107:in `block in run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/simulate_system.rb:29:in `with'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11708/lib/types/private/methods/call_validation.rb:278:in `bind_call'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11708/lib/types/private/methods/call_validation.rb:278:in `validate_call'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11708/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/unbottled.rb:67:in `run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11708/lib/types/private/methods/call_validation.rb:278:in `bind_call'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11708/lib/types/private/methods/call_validation.rb:278:in `validate_call'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11708/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
Please report this issue:
  https://docs.brew.sh/Troubleshooting
```

---

running that same command on macos 15 m1 aka arm64 box gives me the below output,

```
==> Populating dependency tree...
==> :arm64_sequoia bottle status
vtk: doesn't support this macOS
```

### What did you expect to happen?

i would expect the command list the dependencies of vtk that are not bottled.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
run above mentioned commands,

https://github.com/orgs/Homebrew/discussions/5816
```

**Comment by MikeMcQuaid** [comment]
@ipatch Can you please supply your `brew config` output on both systems? Thanks.

**Comment by ipatch** [comment]
on ubuntu 22.04 with the default homebrew prefix, ie. `/home/linuxbrew/.linuxbrew`

```
HOMEBREW_VERSION: 4.4.13-11-g4ecf9b5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4ecf9b5d3e459b8eef7f4e5848c0924b716c7855
Last commit: 21 hours ago
Branch: master
Core tap HEAD: c942eb305995489ff20610191d83830103a94c69
Core tap last commit: 17 hours ago
Core tap JSON: 19 Dec 22:10 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CACHE: /home/linuxbrew/.linuxbrew/cache
HOMEBREW_CASK_OPTS: []
HOMEBREW_DEVELOPER: set
HOMEBREW_DISPLAY: localhost:10.0
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_NO_AUTOREMOVE: set
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_NO_GITHUB_API: set
HOMEBREW_NO_INSTALL_CLEANUP: set
HOMEBREW_NO_INSTALL_FROM_API: set
HOMEBREW_SORBET_RUNTIME: set
HOMEBREW_TEMP: /home/brewer/tmp/homebrew
Homebrew Ruby: 3.3.6 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.6/bin/ruby
CPU: octa-core 64-bit haswell
Clang: 19.1.6
Git: 2.34.1 => /bin/git
Curl: 7.81.0 => /bin/curl
Kernel: Linux 6.8.0-50-generic x86_64 GNU/Linux
OS: Ubuntu 22.04.5 LTS (jammy)
Host glibc: 2.35
/usr/bin/gcc: 11.4.0
/usr/bin/ruby: 3.0.2
glibc: N/A
gcc@11: N/A
gcc: 14.2.0_1
xorg: N/A
```

---

on macos 15 arm64 with a non standard install prefix

```
HOMEBREW_VERSION: 4.4.13-11-g4ecf9b5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4ecf9b5d3e459b8eef7f4e5848c0924b716c7855
Last commit: 21 hours ago
Branch: master
Core tap origin: https://github.com/ipatch/homebrew-core.git
Core tap HEAD: ff53977a86fca5ce653da8f99ff6791da60cc699
Core tap last commit: 2 days ago
Core cask tap HEAD: 0fb12eb9028d5abc9b4ea0aeafbfd12abed54235
Core cask tap last commit: 17 hours ago
HOMEBREW_PREFIX: /Users/chris/homebrew
HOMEBREW_REPOSITORY: /Users/chris/homebrew
HOMEBREW_CELLAR: /Users/chris/homebrew/Cellar
HOMEBREW_CACHE: /Users/chris/homebrew/cache
HOMEBREW_CASK_OPTS: []
HOMEBREW_DEVELOPER: set
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_NO_AUTOREMOVE: set
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_NO_GITHUB_API: set
HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: set
HOMEBREW_NO_INSTALL_CLEANUP: set
HOMEBREW_NO_INSTALL_FROM_API: set
HOMEBREW_SORBET_RUNTIME: set
HOMEBREW_TEMP: /Users/chris/tmp/homebrew
Homebrew Ruby: 3.3.6 => /Users/chris/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.6/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 16.0.0 build 1600
Git: 2.39.5 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.0.1-arm64
CLT: 16.0.0.0.1.1724870825
Xcode: 16.1
Rosetta 2: false
```

**Comment by ipatch** [comment]
are we not suppose to see which deps are unbottled? i'm only seeing the below in the output of the updated command,

```
╰─λ brew unbottled --tag arm64_sequoia --dependents -v vtk                                                             
==> Populating dependency tree...
==> :arm64_sequoia bottle status
vtk: doesn't support this macOS
```
