### ISSUE TITLE
brew tap fails during installation

### ISSUE THREAD

**Issue by brian-eng** [Homebrew/brew#193]
Computer is behind a proxy and $ALL_PROXY is set. Cloning repo via git works fine, but one of the later steps of installing homebrew tries to tap homebrew/core which fails with the unhelpful message of Error: Connection refused - connect(2)

Trying to add different taps also results in the same message. However homebrew thinks the taps were installed properly as they're listed under brew tap.

Attached is the text output of installation, brew update (x2) and brew doctor, as well as trying to add a new tap, and the result of running brew tap.

```
admin$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
==> This script will install:
/usr/local/bin/brew
/usr/local/Library/...
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew

Press RETURN to continue or any other key to abort
==> /usr/bin/sudo /bin/mkdir /Library/Caches/Homebrew
==> /usr/bin/sudo /bin/chmod g+rwx /Library/Caches/Homebrew
==> /usr/bin/sudo /usr/sbin/chown admin /Library/Caches/Homebrew
==> Downloading and installing Homebrew...
remote: Counting objects: 468, done.
remote: Compressing objects: 100% (425/425), done.
remote: Total 468 (delta 26), reused 258 (delta 17), pack-reused 0
Receiving objects: 100% (468/468), 756.07 KiB | 0 bytes/s, done.
Resolving deltas: 100% (26/26), done.
From https://github.com/Homebrew/brew
 * [new branch]      master     -> origin/master
HEAD is now at bf23ba1 pull: fix polling code for Ruby 1.8.7 Net::HTTP (#191)
==> Tapping homebrew/core
Cloning into '/usr/local/Library/Taps/homebrew/homebrew-core'...
remote: Counting objects: 3688, done.
remote: Compressing objects: 100% (3575/3575), done.
remote: Total 3688 (delta 14), reused 550 (delta 1), pack-reused 0
Receiving objects: 100% (3688/3688), 2.82 MiB | 0 bytes/s, done.
Resolving deltas: 100% (14/14), done.
Checking connectivity... done.
Tapped 3563 formulae (3,714 files, 8.8M)
Error: Connection refused - connect(2)
Failed during: /usr/local/bin/brew tap homebrew/core

admin$ brew update
Updated Homebrew from bf23ba1 to b5007c4.
No changes to formulae.

admin$ brew update
Already up-to-date.

admin$ brew doctor
Your system is ready to brew.

admin$ brew tap homebrew/science
==> Tapping homebrew/science
Cloning into '/usr/local/Library/Taps/homebrew/homebrew-science'...
remote: Counting objects: 591, done.
remote: Compressing objects: 100% (591/591), done.
remote: Total 591 (delta 1), reused 65 (delta 0), pack-reused 0
Receiving objects: 100% (591/591), 492.44 KiB | 0 bytes/s, done.
Resolving deltas: 100% (1/1), done.
Checking connectivity... done.
Tapped 581 formulae (611 files, 1.6M)
Error: Connection refused - connect(2)

admin$ brew tap
homebrew/core
homebrew/science
```
Is there any additional information I can print out to help diagnose where that error is coming from? Adding the -v option to tap command only lists the actual git command (which works fine), but nothing about what is causing the connect failure.

Trying to install formulas fails with the same error as well.

```
admin$ brew install -v iperf3
Error: Connection refused - connect(2)

admin$ brew install -v root6
==> Installing root6 from homebrew/science
==> Installing dependencies for homebrew/science/root6: readline, sqlite, gdbm, openssl, python, gsl
==> Installing homebrew/science/root6 dependency: readline
Error: Connection refused - connect(2)
```

**Comment by mikemcquaid** [comment]
@brian-eng Can you paste the output of `brew install -v iperf3 --debug`? Thanks!

**Comment by brian-eng** [comment]
@mikemcquaid Here's the output with debug flag added.

```
admin$ brew install -v iperf3 --debug
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/iperf3.rb
Error: Connection refused - connect(2)
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `initialize'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `block in connect'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:877:in `connect'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:851:in `start'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:313:in `open_http'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:709:in `buffer_open'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:210:in `block in open_loop'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `open_loop'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:149:in `open_uri'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:689:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:30:in `open'
/usr/local/Library/Homebrew/utils.rb:648:in `open'
/usr/local/Library/Homebrew/utils.rb:739:in `private_repo?'
/usr/local/Library/Homebrew/tap.rb:493:in `read_or_set_private_config'
/usr/local/Library/Homebrew/tap.rb:156:in `private?'
/usr/local/Library/Homebrew/formula_installer.rb:205:in `install'
/usr/local/Library/Homebrew/cmd/install.rb:270:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:144:in `block in install'
/usr/local/Library/Homebrew/cmd/install.rb:144:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:144:in `install'
/usr/local/Library/brew.rb:87:in `<main>'
```

**Comment by mikemcquaid** [comment]
@xu-cheng Thoughts on what to do here? It seems the `private_repo?` stuff doesn't support proxies.

**Comment by xu-cheng** [comment]
I think this is the problem that Github API module doesn't support proxies well, which has always been a known case.

**Comment by mikemcquaid** [comment]
Unfortunately as @xu-cheng has said @brian-eng it's an issue with your proxy usage. You may want to set `HOMEBREW_NO_GITHUB_API` in your environment.

**Comment by brian-eng** [comment]
Setting that variable allowed Homebrew to install without any errors, installing bottles works now too.

Any chance that this is the issue: https://www.jethrocarr.com/2014/08/14/ruby-nethttp-proxies/

**Comment by mikemcquaid** [comment]
@brian-eng It could be but I think it's a little deeper than that, unfortunately.

**Comment by brian-eng** [comment]
Bummer.

Since I've got a workaround now, I'll leave the decision to close this issue up to you guys.

**Comment by UniqMartin** [comment]
Closing this in favor of #264 where discussion on resolving the proxy issues is currently ongoing, see particularly https://github.com/Homebrew/brew/issues/264#issuecomment-220852772 and below. Any help with getting this implemented is much appreciated!

**Comment by tc0nn** [comment]
Solved by owning /usr/local/Library in my case. I do use a proxy also.
