### ISSUE TITLE
On `brew upgrade`

### ISSUE THREAD

**Issue by aichholzer** [Homebrew/brew#2049]
Error: undefined method `strip' for :versioned_formula:Symbol

```
/usr/local/Homebrew/Library/Homebrew/formula_support.rb:55:in `to_s'
/usr/local/Homebrew/Library/Homebrew/caveats.rb:49:in `keg_only_text'
/usr/local/Homebrew/Library/Homebrew/caveats.rb:18:in `caveats'
/usr/local/Homebrew/Library/Homebrew/caveats.rb:30:in `empty?'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:484:in `caveats'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:512:in `finish'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:466:in `install_dependency'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:429:in `block in install_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:429:in `each'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:429:in `install_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:201:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:113:in `upgrade_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:79:in `block in upgrade'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:78:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:78:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

**Comment by vitorgalvao** [comment]
Please fill [the issue template](https://github.com/Homebrew/brew/blob/master/.github/ISSUE_TEMPLATE.md) with the requested information. [It says right there](https://github.com/Homebrew/brew/blob/master/.github/ISSUE_TEMPLATE.md#bug-reports):

> Please note we may immediately close your issue without comment if you do not fill out the issue template and provide the requested information.
