### ISSUE TITLE
Error: undefined method `llvm_build_version' for OS::Mac:Module

### ISSUE THREAD

**Issue by jayhesselberth** [Homebrew/brew#216]
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

### Bug reports:

After updating brew:

``` bash
$ brew update
Updated Homebrew from 05efd70 to 9e7b8c6.
```

getting this error:

``` bash
$ brew upgrade
Error: undefined method `llvm_build_version' for OS::Mac:Module
/usr/local/Library/Homebrew/os/mac/xcode.rb:108:in `uncached_version'
/usr/local/Library/Homebrew/os/mac/xcode.rb:73:in `version'
/usr/local/Library/Homebrew/extend/os/mac/diagnostic.rb:125:in `check_for_osx_gcc_installer'
/usr/local/Library/Homebrew/cmd/install.rb:230:in `block in check_xcode'
/usr/local/Library/Homebrew/cmd/install.rb:229:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:229:in `check_xcode'
/usr/local/Library/Homebrew/cmd/install.rb:255:in `perform_preinstall_checks'
/usr/local/Library/Homebrew/cmd/upgrade.rb:18:in `upgrade'
/usr/local/Library/brew.rb:87:in `<main>'
```
`brew doctor` generates the same error:

``` bash
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.
Error: undefined method `llvm_build_version' for OS::Mac:Module
/usr/local/Library/Homebrew/os/mac/xcode.rb:108:in `uncached_version'
/usr/local/Library/Homebrew/os/mac/xcode.rb:73:in `version'
/usr/local/Library/Homebrew/extend/os/mac/diagnostic.rb:125:in `check_for_osx_gcc_installer'
/usr/local/Library/Homebrew/cmd/doctor.rb:42:in `block in doctor'
/usr/local/Library/Homebrew/cmd/doctor.rb:35:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:35:in `doctor'
/usr/local/Library/brew.rb:87:in `<main>'
```

**Comment by jayhesselberth** [comment]
Fixed the first problem. Now getting the (possibly related, looks similar) error:

``` bash
==> Upgrading vim
Error: undefined method `locate' for OS::Mac:Module
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/os/mac/sdk.rb:40:in `sdk_paths'
/usr/local/Library/Homebrew/os/mac/sdk.rb:18:in `sdk_for'
/usr/local/Library/Homebrew/os/mac.rb:97:in `sdk'
/usr/local/Library/Homebrew/os/mac.rb:108:in `sdk_path'
/usr/local/Library/Homebrew/extend/ENV/std.rb:175:in `remove_macosxsdk'
/usr/local/Library/Homebrew/extend/ENV/std.rb:193:in `macosxsdk'
/usr/local/Library/Homebrew/extend/ENV/std.rb:64:in `setup_build_environment'
/usr/local/Library/Homebrew/build.rb:91:in `install'
/usr/local/Library/Homebrew/build.rb:178:in `<main>'
```

**Comment by mikemcquaid** [comment]
@jayhesselberth On it. Can I see your `brew config`? Thanks!

**Comment by mikemcquaid** [comment]
@jayhesselberth Still interested in seeing your `brew config` if you get the chance so I can figure out why I didn't hit this locally. Thanks!

**Comment by jayhesselberth** [comment]
``` bash
$ brew config
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 504152038cb591a661721b09e989f428bbc6ae0a
Last commit: 20 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 965c7ad780fb4d831d3f4cbd625f3fa775131cc1
Core tap last commit: 23 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit ivybridge
Clang: 7.3 build 703
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_92, 1.6.0_65-b14-468
System Ruby: 2.0.0-p648
OS X: 10.11.4-x86_64
Xcode: N/A
CLT: 7.3.1.0.1.1461711523
X11: 2.7.8 => /opt/X11
```
