### ISSUE TITLE
`brew cleanup` throws exception

### ISSUE THREAD

**Issue by Tristor** [Homebrew/brew#218]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

```
❯ brew cleanup
Error: undefined method `bottle_file_outdated?' for Homebrew::Cleanup:Module
/usr/local/Library/Homebrew/cleanup.rb:91:in `block in cleanup_cache'
/usr/local/Library/Homebrew/cleanup.rb:48:in `each'
/usr/local/Library/Homebrew/cleanup.rb:48:in `cleanup_cache'
/usr/local/Library/Homebrew/cleanup.rb:11:in `cleanup'
/usr/local/Library/Homebrew/cmd/cleanup.rb:20:in `cleanup'
/usr/local/Library/brew.rb:87:in `<main>'
```

And my brew doctor is clean:
```
❯ brew doctor
Your system is ready to brew.
```

This behavior started just today, previously it was working fine to perform a `brew cleanup`

**Comment by Tristor** [comment]
I ran `brew update` again right after creating this issue, and it appears the issue has already been resolved 👍 

```
❯ brew update
Updated Homebrew from 9e7b8c6 to 5041520.
No changes to formulae.
```

Thanks.
