### ISSUE TITLE
Error: uninitialized constant OS::Mac::DeveloperTools

### ISSUE THREAD

**Issue by mankoff** [Homebrew/brew#220]
### Bug reports:

`brew install octave`  reports `Error: uninitialized constant OS::Mac::DeveloperTools`

I have no issues with `brew doctor` except:

```
Warning: The filesystem on / appears to be case-sensitive.
The default OS X filesystem is case-insensitive. Please report any apparent problems.
```

I've just upgraded Xcode to 7.3.1 and Command Line Tools (OS X 10.11) v 7.3 and `$ xcode-select --version` reports `xcode-select version 2343`.

**Comment by mankoff** [comment]
Full error message is:

```
$ brew install octave
Error: uninitialized constant OS::Mac::DeveloperTools
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/compat/macos.rb:85:in `clang_version'
/usr/local/Library/Taps/homebrew/homebrew-science/octave.rb:32:in `<class:Octave>'
/usr/local/Library/Taps/homebrew/homebrew-science/octave.rb:1:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:21:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:21:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:38:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:87:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:78:in `klass'
/usr/local/Library/Homebrew/formulary.rb:74:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:211:in `factory'
/usr/local/Library/Homebrew/formulary.rb:356:in `find_with_priority'
/usr/local/Library/Homebrew/extend/ARGV.rb:20:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:100:in `install'
/usr/local/Library/brew.rb:87:in `<main>'
```

**Comment by lanjiann** [comment]
**Similar Bug Report:**
I just `brew update` (more than twice), and then `brew upgrade`. I get the error message below:

```
Error: uninitialized constant OS::Mac::DeveloperTools
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/compat/macos.rb:87:in `clang_version'
/usr/local/Library/Taps/homebrew/homebrew-science/octave.rb:32:in `<class:Octave>'
/usr/local/Library/Taps/homebrew/homebrew-science/octave.rb:1:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:21:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:21:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:38:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:87:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:78:in `klass'
/usr/local/Library/Homebrew/formulary.rb:74:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:171:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:211:in `factory'
/usr/local/Library/Homebrew/formulary.rb:230:in `from_rack'
/usr/local/Library/Homebrew/formula.rb:1141:in `block in installed'
/usr/local/Library/Homebrew/formula.rb:1139:in `map'
/usr/local/Library/Homebrew/formula.rb:1139:in `installed'
/usr/local/Library/Homebrew/cmd/upgrade.rb:21:in `upgrade'
/usr/local/Library/brew.rb:87:in `<main>'
```

My softwares have the same versions information as **mankoff**, and  I'm pretty sure that I run `brew update` when @mikemcquaid has already committed some bug fix code and closed this issue.

**Comment by UniqMartin** [comment]
@lanjiann Thanks for the report! The previous fix unfortunately contained a typo. 4059d5fc2634e24a0b5f9f02a416bda1a7016435 should have fixed things for real (tested locally using `brew info octave`). `brew upgrade` should finally work again for you after one final `brew update`.
