### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by yanzhiying** [Homebrew/brew#262]
# Please follow the general troubleshooting steps first:

- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

```
chaorenyeyedeMacBook-Air:libpng-1.6.21 chaorenyeye$ brew install Caskroom/cask/xquartz
Cloning into '/usr/local/Library/Taps/caskroom/homebrew-cask'...
remote: Counting objects: 200675, done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 200675 (delta 12), reused 0 (delta 0), pack-reused 200646
Receiving objects: 100% (200675/200675), 59.38 MiB | 55.00 KiB/s, done.
Resolving deltas: 100% (137230/137230), done.
Checking connectivity... done.
Tapped 1 formula
Error: Unsupported special dependency :ruby
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/dependency_collector.rb:136:in `parse_symbol_spec'
/usr/local/Library/Homebrew/dependency_collector.rb:81:in `parse_spec'
/usr/local/Library/Homebrew/dependency_collector.rb:65:in `build'
/usr/local/Library/Homebrew/dependency_collector.rb:48:in `block in fetch'
/usr/local/Library/Homebrew/dependency_collector.rb:48:in `fetch'
/usr/local/Library/Homebrew/dependency_collector.rb:48:in `fetch'
/usr/local/Library/Homebrew/dependency_collector.rb:38:in `add'
/usr/local/Library/Homebrew/software_spec.rb:129:in `depends_on'
/usr/local/Library/Homebrew/formula.rb:921:in `block in depends_on'
/usr/local/Library/Homebrew/formula.rb:921:in `each'
/usr/local/Library/Homebrew/formula.rb:921:in `depends_on'
/usr/local/Library/Taps/caskroom/homebrew-cask/brew-cask.rb:5:in `<class:BrewCask>'
/usr/local/Library/Taps/caskroom/homebrew-cask/brew-cask.rb:1:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:92:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:92:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:71:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:200:in `factory'
/usr/local/Library/Homebrew/cmd/install.rb:27:in `install'
/usr/local/Library/brew.rb:135:in `<main>'
```

### Propose a feature:

Instead of creating an issue here, please create a pull request with your change proposal in the [Homebrew Evolution](https://github.com/Homebrew/brew-evolution) repository using the [proposal template](https://github.com/Homebrew/brew-evolution/blob/master/proposal_template.md).

**Comment by mikemcquaid** [comment]
Sorry but you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by DomT4** [comment]
Closing as dead but please do shout if there's anything further we can do to help here. Thanks!
