### ISSUE TITLE
`lsdvd` formula out-of-date

### ISSUE THREAD

**Issue by decorate** [Homebrew/brew#2807]
Sadly I am not very technical on the command line, and was unable to parse the contribution guidelines beyond the following to attempt to upgrade the `lsdvd` formula.

`brew bump-formula-pr --strict lsdvd --url=https://downloads.sourceforge.net/project/lsdvd/lsdvd/lsdvd-0.17.tar.gz -sha256=aa44b8c33c66df2a131e469988ced2b11ebf9aab`

My command line output terminated with:

```
lsdvd:
  * A `test do` test block should be added
Error: 1 problem in 1 formula
Error: brew audit failed!
/usr/local/Homebrew/Library/Homebrew/utils.rb:55:in `exit'
/usr/local/Homebrew/Library/Homebrew/utils.rb:55:in `odie'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb:275:in `bump_formula_pr'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

Wish I could be of more help.

**Comment by decorate** [comment]
Sorry I think I have posted this in wrong repository.
