### ISSUE TITLE
Cannot Brew Update: 403 Forbidden; brew doctor reports errors

### ISSUE THREAD

**Issue by jclark-dot-org** [Homebrew/brew#2836]
**Summary:**

I am unable to run `brew update`, I get a "403 Forbidden" error from github.  `brew doctor` also returns errors with instructions to report to https://git.io/brew-troubleshooting, which doesn't appear to be around anymore.

**Full details & repro**
While trying to install mono-mdk, I got a warning:
```
You haven't updated Homebrew in a while.
A formula for mono-mdk might have been added recently.
Run `brew update` to get the latest Homebrew updates!
```

I attempted `brew update`:
```
==> Migrating Homebrew to v0.9.9
warning: Option "depth" is ignored for https://github.com/Homebrew/brew.git

fatal: https://github.com/Homebrew/brew.git/info/refs download error - The requested URL returned error: 403 Forbidden
```

After some googling pointed me at (https://github.com/Homebrew/brew/issues/330), I tried using git to update:
```
 > $ cd "$(brew --repository)"
                                                                                                                                                                                      
 > $ git remote -v
origin	https://github.com/Homebrew/brew.git (fetch)
origin	https://github.com/Homebrew/brew.git (push)
                                                                                                                                                                                      
 > $ git fetch origin
remote: Counting objects: 57299, done.
remote: Total 57299 (delta 3688), reused 3688 (delta 3688), pack-reused 53610
Receiving objects: 100% (57299/57299), 14.10 MiB | 25.78 MiB/s, done.
Resolving deltas: 100% (36973/36973), completed with 288 local objects.
From https://github.com/Homebrew/brew
 + 5a9e19f...4fb60d8 master     -> origin/master  (forced update)
 * [new tag]         0.1        -> 0.1
 * [new tag]         0.2        -> 0.2
 * [new tag]         0.3        -> 0.3
 * [new tag]         0.4        -> 0.4
 * [new tag]         0.5        -> 0.5
 * [new tag]         0.6        -> 0.6
 * [new tag]         0.7        -> 0.7
 * [new tag]         0.7.1      -> 0.7.1
 * [new tag]         0.8        -> 0.8
 * [new tag]         0.8.1      -> 0.8.1
 * [new tag]         0.9        -> 0.9
 * [new tag]         0.9.1      -> 0.9.1
 * [new tag]         0.9.2      -> 0.9.2
 * [new tag]         0.9.3      -> 0.9.3
 * [new tag]         0.9.4      -> 0.9.4
 * [new tag]         0.9.5      -> 0.9.5
 * [new tag]         0.9.8      -> 0.9.8
 * [new tag]         0.9.9      -> 0.9.9
 * [new tag]         1.0.0      -> 1.0.0
 * [new tag]         1.0.1      -> 1.0.1
 * [new tag]         1.0.2      -> 1.0.2
 * [new tag]         1.0.3      -> 1.0.3
 * [new tag]         1.0.4      -> 1.0.4
 * [new tag]         1.0.5      -> 1.0.5
 * [new tag]         1.0.6      -> 1.0.6
 * [new tag]         1.0.7      -> 1.0.7
 * [new tag]         1.0.8      -> 1.0.8
 * [new tag]         1.0.9      -> 1.0.9
 * [new tag]         1.1.0      -> 1.1.0
 * [new tag]         1.1.1      -> 1.1.1
 * [new tag]         1.1.10     -> 1.1.10
 * [new tag]         1.1.11     -> 1.1.11
 * [new tag]         1.1.12     -> 1.1.12
 * [new tag]         1.1.13     -> 1.1.13
 * [new tag]         1.1.2      -> 1.1.2
 * [new tag]         1.1.3      -> 1.1.3
 * [new tag]         1.1.4      -> 1.1.4
 * [new tag]         1.1.5      -> 1.1.5
 * [new tag]         1.1.6      -> 1.1.6
 * [new tag]         1.1.7      -> 1.1.7
 * [new tag]         1.1.8      -> 1.1.8
 * [new tag]         1.1.9      -> 1.1.9
 * [new tag]         1.2.0      -> 1.2.0
 * [new tag]         1.2.1      -> 1.2.1
 * [new tag]         1.2.2      -> 1.2.2
 * [new tag]         1.2.3      -> 1.2.3
```

Now, `brew update` still fails, although the message is slightly different:
```
 > $ brew update
warning: Option "depth" is ignored for https://github.com/Homebrew/brew.git

fatal: https://github.com/Homebrew/brew.git/info/refs download error - The requested URL returned error: 403 Forbidden
```

Other relevant bits:
`which brew` returns:

    /usr/local/bin/brew1

`brew --version` returns:
```
Homebrew 0.9.8 (git revision 5a9e19; last commit 2016-10-09)
Homebrew/homebrew-core (git revision b996; last commit 2017-06-28)
```

brew config:
```
 > $ brew config
HOMEBREW_VERSION: 0.9.8
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 5a9e19f9d5c70e904dae5bcc4efda71886e3b13d
Last commit: 9 months ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b99697df4e7d7729a8a26b2cc9862c3121c203e2
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
OS X: 10.11.6-x86_64
Xcode: 7.3.1
CLT: N/A
Clang: 7.3 build 703
X11: 2.7.11 => /opt/X11
System Ruby: 2.0.0-p648
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /Users/jclark/.rvm/rubies/ruby-1.9.3-p125/bin/ruby
Java: 1.8.0_101, 1.7.0_55, 1.6.0_65-b14-462
```

brew doctor:
```
 > $ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
    /System/Library/Frameworks/Python.framework/Versions/Current/bin/python-config
    /System/Library/Frameworks/Python.framework/Versions/Current/bin/python2-config
    /System/Library/Frameworks/Python.framework/Versions/Current/bin/python2.7-config
Error: undefined method `rebuild' for #<BottleSpecification:0x007ff50ba7bb08>
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/findutils.rb:10:in `block in <class:Findutils>'
/usr/local/Library/Homebrew/software_spec.rb:91:in `instance_eval'
/usr/local/Library/Homebrew/software_spec.rb:91:in `bottle'
/usr/local/Library/Homebrew/formula.rb:1726:in `bottle'
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/findutils.rb:8:in `<class:Findutils>'
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/findutils.rb:1:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:21:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:21:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:83:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:74:in `klass'
/usr/local/Library/Homebrew/formulary.rb:70:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:207:in `factory'
/usr/local/Library/Homebrew/formula.rb:1183:in `[]'
/usr/local/Library/Homebrew/diagnostic.rb:1217:in `check_for_non_prefixed_findutils'
/usr/local/Library/Homebrew/cmd/doctor.rb:34:in `block in doctor'
/usr/local/Library/Homebrew/cmd/doctor.rb:27:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:27:in `doctor'
/usr/local/Library/brew.rb:84:in `<main>'
```

**Comment by ilovezfs** [comment]
@jclark-dot-org can you come on IRC?

freenode #machomebrew
https://www.irccloud.com/#!/ircs://irc.freenode.net:6697/%23machomebrew

**Comment by MikeMcQuaid** [comment]
I'd suggest `brew tap homebrew/bundle; brew bundle dump` uninstalling and reinstalling Homebrew and then `brew bundle` to reinstall your formulae.

**Comment by jclark-dot-org** [comment]
@ilovezfs Sorry, I'm on EDT and only just saw your comment.

@MikeMcQuaid No joy:
```
 > $ brew tap homebrew/bundle
==> Tapping homebrew/bundle
Cloning into '/usr/local/Library/Taps/homebrew/homebrew-bundle'...
remote: Counting objects: 57, done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 57 (delta 5), reused 12 (delta 0), pack-reused 0
Unpacking objects: 100% (57/57), done.
Checking connectivity... done.
Tapped 0 formulae (126 files, 164.9K)
                                                                                                                                                                                      
 > $ brew bundle dump
Error: undefined method `rebuild' for #<BottleSpecification:0x007fc31d94ec78>
Please report this bug:
Error: uninitialized constant Formatter
/usr/local/Library/Taps/homebrew/homebrew-bundle/cmd/brew-bundle.rb:87:in `rescue in <top (required)>'
/usr/local/Library/Taps/homebrew/homebrew-bundle/cmd/brew-bundle.rb:57:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:22:in `require?'
/usr/local/Library/brew.rb:90:in `<main>'
```

**Comment by ilovezfs** [comment]
@jclark-dot-org you're welcome to come on IRC now if you can.

**Comment by jclark-dot-org** [comment]
@ilovezfs Sorry, I've been out of town for a few days.  Tried the channel for a bit this afternoon but no one was about.  What's a good time to hop on?  Or, are there other diagnostics or potential fixes I can run and post results here?   I basically have a non-functional install at this point, and don't know how to fix it.

**Comment by ilovezfs** [comment]
@jclark-dot-org I'm on now if you're still around.

**Comment by jclark-dot-org** [comment]
This can be closed.  With plenty of help from @ilovezfs on IRC, was determined that main issue was an out-of-date git
