### ISSUE TITLE
`brew test` breaking with "undefined method 'assertions'"

### ISSUE THREAD

**Issue by apjanke** [Homebrew/brew#2856]
Uh oh. My `brew test` calls involving `shell_output` are breaking with errors like the following.

```
$ brew install xtitle
==> Using the sandbox
==> Downloading https://www.cs.indiana.edu/~kinzler/xtitle/xtitle-1.0.4.tgz
######################################################################## 100.0%
🍺  /usr/local/Cellar/xtitle/1.0.4: 7 files, 27KB, built in 3 seconds
[/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula on ⇄ master ±]
$ brew test xtitle
Testing xtitle
==> Using the sandbox
==> /usr/local/Cellar/xtitle/1.0.4/bin/xtitle --version
Error: xtitle: failed
undefined method `assertions' for #<Formulary::FormulaNamespace92dc123c55dfe0a3c8dd638bb2c8c0ad::Xtitle:0x007fc9bb1ef3e8>
/Library/Ruby/Gems/2.0.0/gems/minitest-5.9.0/lib/minitest/assertions.rb:135:in `assert'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit/assertions.rb:38:in `assert'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit/assertions.rb:187:in `assert_equal'
/usr/local/Homebrew/Library/Homebrew/formula_assertions.rb:10:in `shell_output'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/xtitle.rb:16:in `block in <class:Xtitle>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1639:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:832:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1638:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1632:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:27:in `<main>'
```

Anyone else seeing this?

Running Sierra, just updated to latest `brew update` tonight.

###  brew config

```
$ brew config
HOMEBREW_VERSION: 1.2.3-121-gb55290849
ORIGIN: https://github.com/Homebrew/brew
HEAD: b5529084906af89827f6d9befd613457a1615918
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 57eda6ce967b9fee82f6b7e4abc4d5bdd7b2e21f
Core tap last commit: 7 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.13.2 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.0/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.1_1/bin/ruby
Java: 1.8.0_91
macOS: 10.12.5-x86_64
Xcode: 8.3.3 => /Applications/Xcode-8.3.3.app/Contents/Developer
CLT: 8.3.2.0.1.1492020469
X11: 2.7.11 => /opt/X11
```

###  brew doctor

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libtcl8.6.dylib
  /usr/local/lib/libtk8.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/fakemysql.h
  /usr/local/include/fakepq.h
  /usr/local/include/fakesql.h
  /usr/local/include/itcl.h
  /usr/local/include/itcl2TclOO.h
  /usr/local/include/itclDecls.h
  /usr/local/include/itclInt.h
  /usr/local/include/itclIntDecls.h
  /usr/local/include/itclMigrate2TclCore.h
  /usr/local/include/itclTclIntStubsFcn.h
  /usr/local/include/mysqlStubs.h
  /usr/local/include/odbcStubs.h
  /usr/local/include/pqStubs.h
  /usr/local/include/tcl.h
  /usr/local/include/tclDecls.h
  /usr/local/include/tclOO.h
  /usr/local/include/tclOODecls.h
  /usr/local/include/tclPlatDecls.h
  /usr/local/include/tclThread.h
  /usr/local/include/tclTomMath.h
  /usr/local/include/tclTomMathDecls.h
  /usr/local/include/tdbc.h
  /usr/local/include/tdbcDecls.h
  /usr/local/include/tdbcInt.h
  /usr/local/include/tk.h
  /usr/local/include/tkDecls.h
  /usr/local/include/tkPlatDecls.h

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
  /usr/local/lib/pkgconfig/tcl.pc
  /usr/local/lib/pkgconfig/tk.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libtclstub8.6.a
  /usr/local/lib/libtkstub8.6.a

Warning: Broken symlinks were found. Remove them with `brew prune`:
  /usr/local/bin/calibre
  /usr/local/bin/calibre-complete
  /usr/local/bin/calibre-customize
  /usr/local/bin/calibre-debug
  /usr/local/bin/calibre-parallel
  /usr/local/bin/calibre-server
  /usr/local/bin/calibre-smtp
  /usr/local/bin/calibredb
  /usr/local/bin/ebook-convert
  /usr/local/bin/ebook-device
  /usr/local/bin/ebook-edit
  /usr/local/bin/ebook-meta
  /usr/local/bin/ebook-polish
  /usr/local/bin/ebook-viewer
  /usr/local/bin/fetch-ebook-metadata
  /usr/local/bin/lrf2lrs
  /usr/local/bin/lrfviewer
  /usr/local/bin/lrs2lrf
  /usr/local/bin/markdown-calibre
  /usr/local/bin/vlc
  /usr/local/bin/web2disk
  /usr/local/etc/fonts/conf.d/10-hinting-slight.conf
  /usr/local/etc/fonts/conf.d/10-scale-bitmap-fonts.conf
  /usr/local/etc/fonts/conf.d/20-unhint-small-vera.conf
  /usr/local/etc/fonts/conf.d/30-metric-aliases.conf
  /usr/local/etc/fonts/conf.d/30-urw-aliases.conf
  /usr/local/etc/fonts/conf.d/40-nonlatin.conf
  /usr/local/etc/fonts/conf.d/45-latin.conf
  /usr/local/etc/fonts/conf.d/49-sansserif.conf
  /usr/local/etc/fonts/conf.d/50-user.conf
  /usr/local/etc/fonts/conf.d/51-local.conf
  /usr/local/etc/fonts/conf.d/60-latin.conf
  /usr/local/etc/fonts/conf.d/65-fonts-persian.conf
  /usr/local/etc/fonts/conf.d/65-nonlatin.conf
  /usr/local/etc/fonts/conf.d/69-unifont.conf
  /usr/local/etc/fonts/conf.d/80-delicious.conf
  /usr/local/etc/fonts/conf.d/90-synthetic.conf
  /usr/local/opt/kubernetes-cli@1.5
  /usr/local/opt/kubernetes-cli@1.6
  /usr/local/opt/node@7
[✘ /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula on ⇄ master ±]
$
```

I believe all these `brew doctor` warnings are just from external installs, and everything is actually healthy.

**Comment by ilovezfs** [comment]
@apjanke https://github.com/Homebrew/brew/pull/2823#issuecomment-312504164

**Comment by MikeMcQuaid** [comment]
`sudo brew uninstall minitest`

**Comment by peterromfeldhk** [comment]
for people coming here with same problem :
`sudo gem uninstall minitest`
