### ISSUE TITLE
postinstall should determine prefix from spec not ARGV

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/brew#2941]
# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

```
bash-3.2$ brew config
HOMEBREW_VERSION: 1.2.5-4-g53038a1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 53038a14b37158bc32c7c54b16cb4e06333dd8c4
Last commit: 61 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7ed8718a7b1d21f27564feb04570b0fc0788de88
Core tap last commit: 65 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.0.0-p648 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/bin/ruby
Clang: 8.0 build 800
Git: 2.10.1 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.0/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.1_1/bin/ruby
Java: 1.8.0_121
macOS: 10.11.6-x86_64
Xcode: N/A
CLT: 8.2.0.0.1.1480973914
X11: N/A
bash-3.2$ 
```
```
bash-3.2$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: The filesystem on / appears to be case-sensitive.
The default macOS filesystem is case-insensitive. Please report any apparent problems.
```

To help us debug your issue please explain:
- What you were trying to do (and why)
```
brew install -dv --HEAD yarn
```
(I wanted to test whether it worked with the new `--without-node`)

- What happened (include command output)
```
bash-3.2$ brew install -dv --HEAD yarn
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/yarn.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/node.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pkg-config.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/icu4c.rb
==> Installing dependencies for yarn: node
==> Installing yarn dependency: node
==> Downloading https://homebrew.bintray.com/bottles/node-8.2.1.el_capitan.bottle.tar.gz
Already downloaded: /Users/joe/Library/Caches/Homebrew/node-8.2.1.el_capitan.bottle.tar.gz
==> Verifying node-8.2.1.el_capitan.bottle.tar.gz checksum
==> Pouring node-8.2.1.el_capitan.bottle.tar.gz
tar xzf /Users/joe/Library/Caches/Homebrew/node-8.2.1.el_capitan.bottle.tar.gz
Changing install name in /usr/local/Cellar/node/8.2.1/bin/node
  from @@HOMEBREW_PREFIX@@/opt/icu4c/lib/libicui18n.58.dylib
    to /usr/local/opt/icu4c/lib/libicui18n.58.dylib
Changing install name in /usr/local/Cellar/node/8.2.1/bin/node
  from @@HOMEBREW_PREFIX@@/opt/icu4c/lib/libicuuc.58.dylib
    to /usr/local/opt/icu4c/lib/libicuuc.58.dylib
Changing install name in /usr/local/Cellar/node/8.2.1/bin/node
  from @@HOMEBREW_PREFIX@@/opt/icu4c/lib/libicudata.58.2.dylib
    to /usr/local/opt/icu4c/lib/libicudata.58.2.dylib
==> Finishing up
ln -s ../../Cellar/node/8.2.1/etc/bash_completion.d/npm npm
ln -s ../Cellar/node/8.2.1/bin/node node
ln -s ../Cellar/node/8.2.1/include/node node
ln -s ../../Cellar/node/8.2.1/share/doc/node node
ln -s ../../../Cellar/node/8.2.1/share/man/man1/node.1 node.1
ln -s ../Cellar/node/8.2.1/share/systemtap systemtap
mkdir -p /usr/local/lib/dtrace
ln -s ../../Cellar/node/8.2.1/lib/dtrace/node.d node.d
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20170725-19636-1ii70vw.sb nice /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/postinstall.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/node.rb -dv --HEAD
/usr/local/Homebrew/Library/Homebrew/postinstall.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/node.rb
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall node`
==> unknown file type: /usr/local/Cellar/node/HEAD/libexec/lib/node_modules/npm
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/lib/ruby/2.0.0/fileutils.rb:1375:in `copy'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/lib/ruby/2.0.0/fileutils.rb:463:in `block in copy_entry'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/lib/ruby/2.0.0/fileutils.rb:1485:in `call'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/lib/ruby/2.0.0/fileutils.rb:1485:in `wrap_traverse'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/lib/ruby/2.0.0/fileutils.rb:460:in `copy_entry'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/lib/ruby/2.0.0/fileutils.rb:435:in `block in cp_r'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/lib/ruby/2.0.0/fileutils.rb:1558:in `block in fu_each_src_dest'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/lib/ruby/2.0.0/fileutils.rb:1572:in `fu_each_src_dest0'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/lib/ruby/2.0.0/fileutils.rb:1556:in `fu_each_src_dest'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/lib/ruby/2.0.0/fileutils.rb:434:in `cp_r'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/node.rb:85:in `post_install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:974:in `block (2 levels) in run_post_install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:832:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:973:in `block in run_post_install'
/usr/local/Homebrew/Library/Homebrew/utils.rb:554:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:965:in `run_post_install'
/usr/local/Homebrew/Library/Homebrew/postinstall.rb:16:in `<main>'
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/node/8.2.1: 4,151 files, 46MB
==> Installing yarn --HEAD
/usr/bin/sandbox-exec -f /tmp/homebrew20170725-19642-1cpnhcp.sb nice /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/yarn.rb --verbose --debug --HEAD
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/yarn.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/node.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/icu4c.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pkg-config.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/git.rb
==> Cloning https://github.com/yarnpkg/yarn.git
Updating /Users/joe/Library/Caches/Homebrew/yarn--git
git config remote.origin.url https://github.com/yarnpkg/yarn.git
git config remote.origin.fetch +refs/heads/master:refs/remotes/origin/master
git fetch origin
==> Checking out branch master
git checkout -f master --
Already on 'master'
Your branch is up-to-date with 'origin/master'.
git reset --hard origin/master
HEAD is now at d56c6db Breaking: rename every `yarn <command> rm` to `yarn <command> remove` (#3989)
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
Utils::InreplaceError: inreplace failed
/usr/local/Cellar/yarn/HEAD-d56c6db/libexec/package.json:
  expected replacement of "\"installationMethod\": \"tar\"" with "\"installationMethod\": \"homebrew\""
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action:
```

- What you expected to happen

`node`'s postinstall step to complete successfully.

- Step-by-step reproduction instructions (by running `brew` commands)

```
brew uninstall --ignore-dependencies node yarn
brew install -dv --HEAD yarn
```

So despite pouring the `node` bottle (stable spec), the `postinstall` step thinks the node prefix is a head spec due to the `--HEAD` in `ARGV`.

So we get the error:
```
==> unknown file type: /usr/local/Cellar/node/HEAD/libexec/lib/node_modules/npm
```
even though
```
bash-3.2$ ls -l /usr/local/Cellar/node/
total 0
drwxr-xr-x  9 joe  admin  476 Jul 25 09:14 8.2.1
bash-3.2$ 
```

**Comment by ilovezfs** [comment]
CC @vladshablinsky

**Comment by MikeMcQuaid** [comment]
CC @apjanke that you could pick this up, too

**Comment by ilovezfs** [comment]
Go away you stupid robot.
