### ISSUE TITLE
undefined method `head?' for nil:NilClass when Golang has update

### ISSUE THREAD

**Issue by b3618477** [Homebrew/brew#2944]
# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
>'brew update' is ok
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?
```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/name/.pyenv/shims/python-config
  /Users/name/.pyenv/shims/python2-config
  /Users/name/.pyenv/shims/python2.7-config
  /Users/name/.pyenv/shims/python3-config
  /Users/name/.pyenv/shims/python3.6-config
  /Users/name/.pyenv/shims/python3.6m-config
Error: undefined method `head?' for nil:NilClass
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:55:in `block in owner='
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:53:in `each_value'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:53:in `owner='
/usr/local/Homebrew/Library/Homebrew/formula.rb:231:in `spec_eval'
/usr/local/Homebrew/Library/Homebrew/formula.rb:188:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:224:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:275:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:306:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:289:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1383:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1381:in `map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1381:in `installed'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:844:in `check_missing_deps'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:43:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```
```
$ brew config                                                             
HOMEBREW_VERSION: 1.2.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: b5529084906af89827f6d9befd613457a1615918
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b9381a551461da1ad224013933f6d676d7443fa9
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit dunno
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.13.3 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /Users/name/.pyenv/shims/python => /Users/name/.pyenv/versions/2.7.13/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_131
macOS: 10.12.6-x86_64
Xcode: 8.3.3
CLT: 8.3.2.0.1.1492020469
X11: N/A
```
```
$ brew readall
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/go.rb
undefined method `head?' for nil:NilClass
```
**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)
> when I use 'brew update' and find go language has updates, issue comes out
- What happened (include command output)
```
$ brew upgrade                                                            
Error: undefined method `head?' for nil:NilClass
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:55:in `block in owner='
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:53:in `each_value'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:53:in `owner='
/usr/local/Homebrew/Library/Homebrew/formula.rb:231:in `spec_eval'
/usr/local/Homebrew/Library/Homebrew/formula.rb:188:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:224:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:275:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:306:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:289:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1383:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1381:in `map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1381:in `installed'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:37:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```
- What you expected to happen
>How to upgrade go and how to deal with the warning about pyenv
- Step-by-step reproduction instructions (by running `brew` commands)

# Or propose a feature:
Please replace this section with a detailed description of your proposed feature, the motivation for it, how it would be relevant to at least 90% of Homebrew users and alternatives considered.
Please note we will close this issue or ask you to create a pull-request if it's something we're not actively planning to work on.

**Comment by MikeMcQuaid** [comment]
What's the output of `brew doctor --debug`?

**Comment by MikeMcQuaid** [comment]
See also: https://github.com/Homebrew/homebrew-core/issues/16049

**Comment by b3618477** [comment]
@MikeMcQuaid 
here is new 'brew upgrade' output
```
$ brew upgrade                                                            1 ↵
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (caskroom/cask, homebrew/core).
==> New Formulae
sccache
==> Updated Formulae
convox                     jboss-forge                node-build
cryptol                    kobalt                     packetbeat
dhall-json                 kubernetes-helm            rom-tools
duck                       lxc                        rtags
encfs                      makensis                   ruby-build
filebeat                   mame                       trafficserver
gitlab-ci-multi-runner     metabase                   webpack
go ✔                       metricbeat                 wiredtiger
haskell-stack              monax                      wireguard-tools
heroku                     mysql-sandbox              xsv
hyperscan                  nnn
Error: undefined method `head?' for nil:NilClass
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:55:in `block in owner='
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:53:in `each_value'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:53:in `owner='
/usr/local/Homebrew/Library/Homebrew/formula.rb:231:in `spec_eval'
/usr/local/Homebrew/Library/Homebrew/formula.rb:188:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:224:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:275:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:306:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:289:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1383:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1381:in `map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1381:in `installed'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:505:in `migrate_formula_rename'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:101:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:101:in `update_report'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
Error: undefined method `head?' for nil:NilClass
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:55:in `block in owner='
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:53:in `each_value'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:53:in `owner='
/usr/local/Homebrew/Library/Homebrew/formula.rb:231:in `spec_eval'
/usr/local/Homebrew/Library/Homebrew/formula.rb:188:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:224:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:275:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:306:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:289:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1383:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1381:in `map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1381:in `installed'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:37:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```
and 'brew doctor --debug'
```
brew doctor --debug                                                     1 ↵
Checking check_access_cache
Checking check_access_cellar
Checking check_access_homebrew_repository
Checking check_access_lock_dir
Checking check_access_logs
Checking check_access_prefix_directories
Checking check_access_site_packages
Checking check_brew_git_origin
Checking check_clt_minimum_version
Checking check_clt_up_to_date
Checking check_coretap_git_origin
Checking check_dyld_vars
Checking check_filesystem_case_sensitive
Checking check_for_anaconda
Checking check_for_bad_curl
Checking check_for_bad_install_name_tool
Checking check_for_bad_python_symlink
Checking check_for_beta_xquartz
Checking check_for_config_scripts
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/name/.pyenv/shims/python-config
  /Users/name/.pyenv/shims/python2-config
  /Users/name/.pyenv/shims/python2.7-config
  /Users/name/.pyenv/shims/python3-config
  /Users/name/.pyenv/shims/python3.6-config
  /Users/name/.pyenv/shims/python3.6m-config
Checking check_for_enthought_python
Checking check_for_external_cmd_name_conflict
Checking check_for_gettext
Checking check_for_git
Checking check_for_iconv
Checking check_for_installed_developer_tools
Checking check_for_latest_xquartz
Checking check_for_library_python
Checking check_for_multiple_volumes
Checking check_for_non_prefixed_coreutils
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb
Checking check_for_non_prefixed_findutils
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/findutils.rb
Checking check_for_old_env_vars
Checking check_for_old_homebrew_share_python_in_path
Checking check_for_osx_gcc_installer
Checking check_for_other_frameworks
Checking check_for_other_package_managers
Checking check_for_pth_support
Checking check_for_pydistutils_cfg_in_home
Checking check_for_stray_developer_directory
Checking check_for_stray_dylibs
Checking check_for_stray_headers
Checking check_for_stray_las
Checking check_for_stray_pcs
Checking check_for_stray_static_libs
Checking check_for_symlinked_cellar
Checking check_for_tap_ruby_files_locations
Checking check_for_unlinked_but_not_keg_only
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/readline.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/sqlite.rb
Checking check_for_unsupported_curl_vars
Checking check_for_unsupported_macos
Checking check_git_newline_settings
Checking check_git_status
Checking check_git_version
Checking check_homebrew_prefix
Checking check_multiple_cellars
Checking check_path_for_trailing_slashes
Checking check_ruby_version
Checking check_ssl_cert_file
Checking check_tmpdir
Checking check_tmpdir_sticky_bit
Checking check_user_curlrc
Checking check_user_path_1
Checking check_user_path_2
Checking check_user_path_3
Checking check_which_pkg_config
Checking check_xcode_8_without_clt_on_el_capitan
Checking check_xcode_license_approved
Checking check_xcode_minimum_version
Checking check_xcode_prefix
Checking check_xcode_prefix_exists
Checking check_xcode_select_path
Checking check_xcode_up_to_date
Checking check_for_broken_symlinks
Checking check_missing_deps
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/aria2.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/autoconf.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gdbm.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/git.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/go.rb
Error: undefined method `head?' for nil:NilClass
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:55:in `block in owner='
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:53:in `each_value'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:53:in `owner='
/usr/local/Homebrew/Library/Homebrew/formula.rb:231:in `spec_eval'
/usr/local/Homebrew/Library/Homebrew/formula.rb:188:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:224:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:275:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:306:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:289:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1383:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1381:in `map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1381:in `installed'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:844:in `check_missing_deps'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:43:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

**Comment by b3618477** [comment]
@MikeMcQuaid 
I tried 'brew update --force'
And it works now with HOMEBREW_VERSION: 1.2.5
thanks~~~
and the new 'brew config'
```
brew config                                                             1 ↵
HOMEBREW_VERSION: 1.2.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: f0ca3108f779f7248c4ea38426a4c43ed0e9793f
Last commit: 26 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ffa5a7ff463451d77837a69c978da319c8a81766
Core tap last commit: 47 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit dunno
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.13.3 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /Users/name/.pyenv/shims/python => /Users/name/.pyenv/versions/2.7.13/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_131
macOS: 10.12.6-x86_64
Xcode: 8.3.3
CLT: 8.3.2.0.1.1492020469
X11: N/A
```
thanks again~

**Comment by EarlGray** [comment]
My solution:

```sh
$ cd /usr/local/Homebrew
$ git pull origin master
```

worked for me: Homebrew updated from 1.0.4 to 1.3.1 and the error was gone.
