### ISSUE TITLE
Infinite loop when calling `brew style --fix`

### ISSUE THREAD

**Issue by externl** [Homebrew/brew#2948]
# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

```
brew config
HOMEBREW_VERSION: 1.2.5-14-g88b762f
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 88b762f78447842a6187e0fda49c9493f029cbef
Last commit: 22 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5049eb5db103baccd7d3c92d49e0f2a9abfc6595
Core tap last commit: 17 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.13.3 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.0/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.1_1/bin/ruby
Java: 1.8.0_131, 1.8.0_121, 1.7.0_79
macOS: 10.12.6-x86_64
Xcode: 8.3.3
CLT: 8.3.2.0.1.1492020469
X11: N/A
```

```
brew doctor
Your system is ready to brew.
```

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew` commands)

# Or propose a feature:
Please replace this section with a detailed description of your proposed feature, the motivation for it, how it would be relevant to at least 90% of Homebrew users and alternatives considered.
Please note we will close this issue or ask you to create a pull-request if it's something we're not actively planning to work on.

---

I tried to fix style issues with a formula and recieved this error.

```
brew style ice --fix
== Formula/ice.rb ==
C: 36: 38: [Corrected] Only use parentheses for ternary expressions with complex conditions.
C: 36: 50: [Corrected] Don't use parentheses around a literal.
C: 36: 50: [Corrected] Use parentheses for ternary expressions with complex conditions.
C: 36: 51: [Corrected] Prefer double-quoted strings inside interpolations.
C: 36: 66: [Corrected] Prefer double-quoted strings inside interpolations.
C: 36: 94: [Corrected] Prefer double-quoted strings inside interpolations.
C: 38: 32: [Corrected] Only use parentheses for ternary expressions with complex conditions.
C: 38: 47: [Corrected] Don't use parentheses around a literal.
C: 38: 47: [Corrected] Use parentheses for ternary expressions with complex conditions.
C: 38: 48: [Corrected] Prefer double-quoted strings inside interpolations.
C: 38: 74: [Corrected] Prefer double-quoted strings inside interpolations.
C: 38:105: [Corrected] Prefer double-quoted strings inside interpolations.
C: 39:  7: [Corrected] Put a comma after the last item of a multiline array.
C: 39: 36: [Corrected] Only use parentheses for ternary expressions with complex conditions.
C: 39: 48: [Corrected] Don't use parentheses around a literal.
C: 39: 48: [Corrected] Use parentheses for ternary expressions with complex conditions.
C: 39: 49: [Corrected] Prefer double-quoted strings inside interpolations.
C: 39: 59: [Corrected] Prefer double-quoted strings inside interpolations.
C: 39: 80: [Corrected] Prefer double-quoted strings inside interpolations.

0 files inspected, 19 offenses detected, 19 offenses corrected
Infinite loop detected in /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ice.rb.
/Users/joe/.gem/ruby/2.0.0/gems/rubocop-0.49.1/lib/rubocop/runner.rb:248:in `check_for_infinite_loop'
/Users/joe/.gem/ruby/2.0.0/gems/rubocop-0.49.1/lib/rubocop/runner.rb:231:in `block in iterate_until_no_changes'
/Users/joe/.gem/ruby/2.0.0/gems/rubocop-0.49.1/lib/rubocop/runner.rb:230:in `loop'
/Users/joe/.gem/ruby/2.0.0/gems/rubocop-0.49.1/lib/rubocop/runner.rb:230:in `iterate_until_no_changes'
/Users/joe/.gem/ruby/2.0.0/gems/rubocop-0.49.1/lib/rubocop/runner.rb:201:in `do_inspection_loop'
/Users/joe/.gem/ruby/2.0.0/gems/rubocop-0.49.1/lib/rubocop/runner.rb:111:in `block in file_offenses'
/Users/joe/.gem/ruby/2.0.0/gems/rubocop-0.49.1/lib/rubocop/runner.rb:121:in `file_offense_cache'
/Users/joe/.gem/ruby/2.0.0/gems/rubocop-0.49.1/lib/rubocop/runner.rb:109:in `file_offenses'
/Users/joe/.gem/ruby/2.0.0/gems/rubocop-0.49.1/lib/rubocop/runner.rb:100:in `process_file'
/Users/joe/.gem/ruby/2.0.0/gems/rubocop-0.49.1/lib/rubocop/runner.rb:78:in `block in each_inspected_file'
/Users/joe/.gem/ruby/2.0.0/gems/rubocop-0.49.1/lib/rubocop/runner.rb:75:in `each'
/Users/joe/.gem/ruby/2.0.0/gems/rubocop-0.49.1/lib/rubocop/runner.rb:75:in `reduce'
/Users/joe/.gem/ruby/2.0.0/gems/rubocop-0.49.1/lib/rubocop/runner.rb:75:in `each_inspected_file'
/Users/joe/.gem/ruby/2.0.0/gems/rubocop-0.49.1/lib/rubocop/runner.rb:67:in `inspect_files'
/Users/joe/.gem/ruby/2.0.0/gems/rubocop-0.49.1/lib/rubocop/runner.rb:39:in `run'
/Users/joe/.gem/ruby/2.0.0/gems/rubocop-0.49.1/lib/rubocop/cli.rb:82:in `execute_runner'
/Users/joe/.gem/ruby/2.0.0/gems/rubocop-0.49.1/lib/rubocop/cli.rb:28:in `run'
/Users/joe/.gem/ruby/2.0.0/gems/rubocop-0.49.1/bin/rubocop:13:in `block in <top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/benchmark.rb:296:in `realtime'
/Users/joe/.gem/ruby/2.0.0/gems/rubocop-0.49.1/bin/rubocop:12:in `<top (required)>'
/Users/joe/.gem/ruby/2.0.0/bin/rubocop:23:in `load'
/Users/joe/.gem/ruby/2.0.0/bin/rubocop:23:in `<main>'
```

**Comment by MikeMcQuaid** [comment]
This isn't something we can fix as it's `rubocop` behaviour (and I don't think they can really fix it either). Sorry!
