### ISSUE TITLE
Formula#system doesn't actually call Kernel#system

### ISSUE THREAD

**Issue by elliang** [Homebrew/brew#3029]
# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

```
HOMEBREW_VERSION: 1.3.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 69799d97b1e7314912b2ee234dec2c179c5fb969
Last commit: 33 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c433112e52279b2373f561e881387d95f18cf4fd
Core tap last commit: 20 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit dunno
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.14.0 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.0/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.1_1/bin/ruby
Java: N/A
macOS: 10.12.6-x86_64
Xcode: N/A
CLT: 8.3.2.0.1.1492020469
X11: N/A
```
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libfreebl3.dylib
  /usr/local/lib/libnspr4.dylib
  /usr/local/lib/libnss3.dylib
  /usr/local/lib/libnssckbi.dylib
  /usr/local/lib/libnssdbm3.dylib
  /usr/local/lib/libnssutil3.dylib
  /usr/local/lib/libplc4.dylib
  /usr/local/lib/libplds4.dylib
  /usr/local/lib/libsmime3.dylib
  /usr/local/lib/libsoftokn3.dylib
  /usr/local/lib/libssl3.dylib

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libcertdb.a
  /usr/local/lib/libcerthi.a
  /usr/local/lib/libcrmf.a
  /usr/local/lib/libcryptohi.a
  /usr/local/lib/libdbm.a
  /usr/local/lib/libfreebl.a
  /usr/local/lib/libjar.a
  /usr/local/lib/libnspr4.a
  /usr/local/lib/libnss.a
  /usr/local/lib/libnssb.a
  /usr/local/lib/libnssckfw.a
  /usr/local/lib/libnssdbm.a
  /usr/local/lib/libnssdev.a
  /usr/local/lib/libnsspki.a
  /usr/local/lib/libnssutil.a
  /usr/local/lib/libpk11wrap.a
  /usr/local/lib/libpkcs12.a
  /usr/local/lib/libpkcs7.a
  /usr/local/lib/libpkixcertsel.a
  /usr/local/lib/libpkixchecker.a
  /usr/local/lib/libpkixcrlsel.a
  /usr/local/lib/libpkixmodule.a
  /usr/local/lib/libpkixparams.a
  /usr/local/lib/libpkixpki.a
  /usr/local/lib/libpkixresults.a
  /usr/local/lib/libpkixstore.a
  /usr/local/lib/libpkixsystem.a
  /usr/local/lib/libpkixtop.a
  /usr/local/lib/libpkixutil.a
  /usr/local/lib/libplc4.a
  /usr/local/lib/libplds4.a
  /usr/local/lib/libsectool.a
  /usr/local/lib/libsmime.a
  /usr/local/lib/libsoftokn.a
  /usr/local/lib/libssl.a

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc
```
**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)

I was installing a formula

- What happened (include command output)

```
brew postinstall foo-formula
==> Postinstalling foo-formula
==> Creating /exampleFolder (requires sudo)
==> sudo mkdir /exampleFolder
Last 15 lines from stuff/post_install.01.sudo:
2017-08-08 15:56:55 -0400

sudo
mkdir
/exampleFolder


If reporting this issue please do so to (not Homebrew/brew or Homebrew/core):
tap/tap

/usr/local/Homebrew/Library/Homebrew/utils/github.rb:226:in `raise_api_error': curl failed!  (GitHub::Error)
curl: (22) The requested URL returned error: 422 Unprocessable Entity
curl: (3) <url> malformed
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:184:in `open'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:233:in `issues_matching'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:272:in `issues_for_formula'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:369:in `fetch_issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:365:in `issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:419:in `dump'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:133:in `rescue in <main>'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:26:in `<main>'
```

- What you expected to happen

I expected to be prompted for a password when the formula attempted to use sudo to create the folder at root, and then for the folder creation to succeed.

- Step-by-step reproduction instructions (by running `brew` commands)
```
$ brew install foo-formula
```
``` 
# relevant command in formula

system "sudo mkdir /exampleFolder"
```

# Or propose a feature:
It looks like the problem is caused by `Formula#system` eventually calling `Kernel#exec` rather than `Kernel#system`. `Kernel#system` spawns a new subshell and prompts for permissions, while `Kernel#exec` just replaces the current process and reuses the current process's permissions.

Updating `Formula#system` to use `Kernel#system` rather than `Kernel#exec` would allow formula writers to selectively perform tasks that require elevated permissions rather than having users run `sudo brew install blah` or having to manually perform the steps that require elevated permissions.

**Comment by MikeMcQuaid** [comment]
> Updating Formula#system to use Kernel#system rather than Kernel#exec would allow formula writers to selectively perform tasks that require elevated permissions

We intentionally do not want to allow formula writers to do this, sorry.
