### ISSUE TITLE
Error: 784: unexpected token at '{

### ISSUE THREAD

**Issue by Kyslik** [Homebrew/brew#3238]
**Before you read any further I am still on Yosemite (OS X 10.10).** I don't think it has anything to do with OS X version though, since 2 hours before, everything worked.

---

- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

CLI output

```
➜  ~ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  php56

Warning: You are using macOS 10.10.
We (and Apple) do not provide support for this old version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
Error: 784: unexpected token at '{
  "httpd24": "homebrew/core",
}
'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/json/common.rb:156:in `parse'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/json/common.rb:156:in `parse'
/usr/local/Homebrew/Library/Homebrew/tap.rb:475:in `tap_migrations'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:200:in `formula_name_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:180:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:351:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:351:in `loader_for'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:271:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:302:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:285:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1384:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1382:in `map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1382:in `installed'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:855:in `check_missing_deps'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:43:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
➜  ~ brew config
HOMEBREW_VERSION: 1.3.4-33-g296a441
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 296a44195bb8c8c0d5d9b512f10c7ee70f400efb
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ab315476a04ad9281957af3318f9241d19b93b0f
Core tap last commit: 9 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 7.0 build 700
Git: 2.14.2 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.0/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.2/bin/ruby
Java: 1.8.0_92, 1.8.0_66, 1.6.0_65-b14-468
macOS: 10.10.5-x86_64
Xcode: 7.2.1
CLT: 7.2.0.0.1.1447826929
X11: N/A
```

**Comment by mmindenhall** [comment]
I can confirm this, running in MacOS Sierra.

```
$ brew update
Updated 1 tap (homebrew/core).
No changes to formulae.

$ brew outdated
Error: 784: unexpected token at '{
  "httpd24": "homebrew/core",
}
'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/json/common.rb:156:in `parse'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/json/common.rb:156:in `parse'
/usr/local/Homebrew/Library/Homebrew/tap.rb:475:in `tap_migrations'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:200:in `formula_name_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:180:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:351:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:351:in `loader_for'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:271:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:302:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:285:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1384:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1382:in `map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1382:in `installed'
/usr/local/Homebrew/Library/Homebrew/cmd/outdated.rb:28:in `outdated'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

**Comment by mmindenhall** [comment]
Ah...I see over in homebrew/core that this was just renamed.  Re-filing the issue over there.

**Comment by cwonrails** [comment]
Exact same issue.
