### ISSUE TITLE
Error: undefined method `head?' for nil:NilClass

### ISSUE THREAD

**Issue by pengshp** [Homebrew/brew#3307]
```
Error: undefined method `head?' for nil:NilClass
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:55:in `block in owner='
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:53:in `each_value'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:53:in `owner='
/usr/local/Homebrew/Library/Homebrew/formula.rb:231:in `spec_eval'
/usr/local/Homebrew/Library/Homebrew/formula.rb:187:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:224:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:275:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:306:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:289:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1383:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1381:in `map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1381:in `installed'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:855:in `check_missing_deps'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:43:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

How to fix the bug?

**Comment by ilovezfs** [comment]
```
git -C "$(brew --repo)" fetch --tags
brew update --force
```

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from every submitting issues to Homebrew again.**

If you add the necessary information this issue may be reopened.

**Comment by pengshp** [comment]
Thanks <https://github.com/Homebrew/brew/issues/2944>, I haved fixed the bug by 
```
$ cd /usr/local/Homebrew
$ git pull origin master
```
