### ISSUE TITLE
Unable to run `brew update` on macOS 10.13 High Sierra

### ISSUE THREAD

**Issue by weicool** [Homebrew/brew#3322]
I'm trying to run `brew update` on macOS 10.13 High Sierra, but get

> Error: /usr/local must be writable!

Running `brew doctor` gives me outdated instructions that no longer apply to 10.13. I followed the instructions in https://github.com/Homebrew/brew/issues/3228, running `sudo chown -R $(whoami) $(brew --prefix)/*`, but am still unable to run `brew update`.

**Comment by JCount** [comment]
@weicool What is the output of `ls -ld /usr/local`?

**Comment by weicool** [comment]
drwxr-xr-x  25 root  wheel  800 Oct 15 10:57 /usr/local/

**Comment by JCount** [comment]
Ok, what's the output of `ls -ld /usr/local/*`?

**Comment by weicool** [comment]
```
-rw-r--r--    1 weicool  admin  3161 Jan 18  2016 /usr/local/CODEOFCONDUCT.md
drwxr-xr-x   18 weicool  admin   576 Oct  8 13:58 /usr/local/Cellar/
drwxr-xr-x    2 weicool  wheel    64 Oct 15 10:57 /usr/local/Frameworks/
-rw-r--r--    1 weicool  admin  1241 Jan 18  2016 /usr/local/LICENSE.txt
drwxr-xr-x@  12 weicool  admin   384 Oct  8 13:58 /usr/local/Library/
-rw-r--r--    1 weicool  admin  3940 Mar 26  2016 /usr/local/README.md
drwxrwxr-x@ 131 weicool  admin  4192 Oct  8 13:58 /usr/local/bin/
drwxr-xr-x@   4 weicool  admin   128 Oct  8 13:57 /usr/local/etc/
drwxrwxr-x@  18 weicool  admin   576 Oct  8 13:57 /usr/local/include/
drwxrwxr-x@  41 weicool  admin  1312 Oct  8 13:58 /usr/local/lib/
drwxr-xr-x@   3 weicool  wheel    96 Oct  8 13:55 /usr/local/libexec/
lrwxr-xr-x    1 weicool  wheel    27 Jan 18  2016 /usr/local/mysql@ -> mysql-5.7.10-osx10.9-x86_64
drwxr-xr-x   13 weicool  wheel   416 Oct  8 13:58 /usr/local/mysql-5.7.10-osx10.9-x86_64/
drwxr-xr-x@  18 weicool  admin   576 Oct  8 13:57 /usr/local/opt/
drwxr-xr-x    3 weicool  wheel    96 Oct  8 13:56 /usr/local/remotedesktop/
drwxrwxr-x@  15 weicool  admin   480 Oct  8 13:57 /usr/local/share/
drwxr-xr-x    3 weicool  admin    96 Oct  8 13:58 /usr/local/var/
```

**Comment by ilovezfs** [comment]
And what is the output of
```
ls -al /usr/local/
```

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from every submitting issues to Homebrew again.**

Please add your `brew config` and `brew doctor` output ASAP.

**Comment by zhexuany** [comment]
brew config
```
HOMEBREW_VERSION: 1.3.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 91ab116ace7f4f97d3440190463c93be9ec6d675
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 31133863d086f7d3e68f35d3611bba1ab533d0af
Core tap last commit: 12 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.13.5 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: 9, 1.8.0_131
macOS: 10.13-x86_64
Xcode: N/A
CLT: 9.0.1.0.1.1506734476
X11: N/A
```

**Comment by zhexuany** [comment]
brew doctor
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libclblast.dylib
  /usr/local/lib/libeasycl.dylib
  /usr/local/lib/libcocl.dylib
  /usr/local/lib/libclew.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/clew.h
Error: undefined method `strip' for nil:NilClass
/usr/local/Homebrew/Library/Taps/cheba/homebrew-rust-nightly/rust-nightly.rb:7:in `latest_rust_nightly_revision'
/usr/local/Homebrew/Library/Taps/cheba/homebrew-rust-nightly/rust-nightly.rb:19:in `<class:RustNightly>'
/usr/local/Homebrew/Library/Taps/cheba/homebrew-rust-nightly/rust-nightly.rb:4:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:26:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:26:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:46:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:101:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:238:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:92:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:228:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:279:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:310:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:293:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1384:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1382:in `map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1382:in `installed'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:855:in `check_missing_deps'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:43:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:99:in `<main>'
```

**Comment by ilovezfs** [comment]
@weicool Hmm ... I saw `brew config` and `brew doctor` output from you via email (and also CC'd to the relevant GitHub addresses) but not posted on this issue. Did you maybe delete the posts? Or maybe GitHub somehow drop them? Please make sure to post or re-post them on this issue itself.

Also, I still haven't seen `ls -al /usr/local/` output.

**Comment by jmsundar** [comment]
Reinstalling homebrew worked. Found that solution at #3285. My specific error came when running `brew upgrade`. 

```
⇒  brew upgrade
==> Upgrading 2 outdated packages, with result:
gmp 6.1.2_1, speedtest-cli 1.0.7
==> Upgrading gmp 
Error: Permission denied @ unlink_internal - /usr/local/lib/libgmp.10.dylib
```
```
⇒ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  #no unexpected dylibs here

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/python3.6m/greenlet/greenlet.h
  /usr/local/include/python2.7/greenlet/greenlet.h
  #no unexpected header files here

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
  #no unexpected .pc files here
⇒  brew config 
HOMEBREW_VERSION: 1.3.5-67-g270b752
ORIGIN: https://github.com/Homebrew/brew
HEAD: 270b752f5d9d218bfbed6fe85b6974fa653fb25f
Last commit: 25 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c78e42731a343b4370346157bacd55add6ce663e
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.14.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: 1.8.0_144
macOS: 10.13-x86_64
Xcode: 9.0
CLT: N/A
X11: N/A
```

**Comment by ilovezfs** [comment]
@jmsundar thanks for letting us know!

**Comment by skaraman** [comment]
had a similar problem with permission denials and unable to chown /usr/local, reinstalling homebrew fixed it

**Comment by chuim** [comment]
Just for the record: I had the same issue and re-running the install command fixed it as well.

**Comment by MikeMcQuaid** [comment]
@skaraman @chuim Please don't post stuff like that just for the record, thanks.
