### ISSUE TITLE
Link to Brew Troubleshooting not working

### ISSUE THREAD

**Issue by yaykyle** [Homebrew/brew#3353]
- [X] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why):
I was attempting to run ```brew outdated``` to see which packages are out of date
- What happened (include command output)
I received a package related error, but it told me to visit https://git.io/brew-troubleshooting. When visiting that page, it responds "No url found for brew-troubleshooting". See output below.
- What you expected to happen
I expected to see a page to tell me more about reporting the package related error
- Step-by-step reproduction instructions (by running `brew` commands)

### Steps:
- I ran `brew update` twice, without error, then ran `brew outdated`, saw a bunch of errors (see output below).
- Tried the broken link.
- Then ran `brew doctor` (see broken output below).
- `brew config` worked successfully (output below).

### Brew Config:
```
HOMEBREW_VERSION: 1.1.5
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 9cd5a21b473f0271b162bbe7f77f7d1468c0cfa1
Last commit: 10 months ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 94caae24875610574dfde8c3c7db9e44638d98c6
Core tap last commit: 7 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.0.0-p648
Clang: 9.0 build 900
Git: 2.14.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_101, 1.7.0_45
macOS: 10.12.6-x86_64
Xcode: 9.0.1
CLT: 9.0.1.0.1.1506734476
X11: 2.7.9 => /opt/X11
```

### Brew Doctor:
```
Error: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:73: syntax error, unexpected <<
  def caveats; <<~EOS
                 ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:77: syntax error, unexpected tIDENTIFIER, expecting keyword_end
    can add a "gnubin" directory to your PATH from your bashrc like:
                                ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:77: syntax error, unexpected ':', expecting keyword_end
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:79: dynamic constant assignment
        PATH="#{opt_libexec}/gnubin:$PATH"
             ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:81: dynamic constant assignment
    Additionally, you can access their man pag...
                 ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:81: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
    Additionally, you can access their man pages with ...
                         ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:82: syntax error, unexpected tIDENTIFIER, expecting keyword_end
    the "gnuman" directory to your MANPATH from your bashrc as well:
                          ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:82: syntax error, unexpected ':', expecting keyword_end
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:84: dynamic constant assignment
        MANPATH="#{opt_libexec}/gnuman:$MANPATH"
                ^
Please report this bug:
  https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:97:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:253:in `factory'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1460:in `[]'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:969:in `check_for_non_prefixed_coreutils'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:43:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### Brew Outdated:
```
Error: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ansible.rb:565: syntax error, unexpected tLABEL
      - hosts: all
              ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ansible.rb:566: syntax error, unexpected ':', expecting keyword_end
        gather_facts: False
                     ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ansible.rb:567: syntax error, unexpected ':', expecting keyword_end
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ansible.rb:569: syntax error, unexpected ':', expecting keyword_end
Please report this bug:
  https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:97:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:212:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:206:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:253:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:284:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:267:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1406:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1404:in `map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1404:in `installed'
/usr/local/Homebrew/Library/Homebrew/cmd/outdated.rb:28:in `outdated'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

**Comment by ilovezfs** [comment]
If you run
```
brew update --force
```
what is the output of `brew config` afterwards?

**Comment by yaykyle** [comment]
```
$ brew update --force
error: Could not read ef6b55125c3af20ac39d1d98848cf2aa0f6c4dd5
error: Could not read ef6b55125c3af20ac39d1d98848cf2aa0f6c4dd5
fatal: pack has 243 unresolved deltas
fatal: index-pack failed
Error: Fetching /usr/local/Homebrew failed!
Updated 3 taps (caskroom/cask, homebrew/core, homebrew/php).
==> Updated Formulae
ansible-lint                             homebrew/php/php72-tidy
convox                                   irssi
homebrew/php/deployer                    libmatio
homebrew/php/php72                       libwebsockets
homebrew/php/php72-gmp                   mosquitto
homebrew/php/php72-intl                  ripgrep
homebrew/php/php72-opcache               terraform-docs
homebrew/php/php72-pcntl                 terragrunt
homebrew/php/php72-pdo-dblib             ttyd
homebrew/php/php72-pdo-pgsql             wxmaxima
homebrew/php/php72-pspell                ykman
homebrew/php/php72-snmp
```

```
$ brew config
HOMEBREW_VERSION: 1.1.5
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 9cd5a21b473f0271b162bbe7f77f7d1468c0cfa1
Last commit: 10 months ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1436f5f9ee6728662ef377cc00377f0fa93bd00e
Core tap last commit: 7 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.0.0-p648
Clang: 9.0 build 900
Git: 2.14.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_101, 1.7.0_45
macOS: 10.12.6-x86_64
Xcode: 9.0.1
CLT: 9.0.1.0.1.1506734476
X11: 2.7.9 => /opt/X11
```

**Comment by ilovezfs** [comment]
OK try this
```
rm -rf /usr/local/Homebrew/.git
brew update
brew config
```

**Comment by ilovezfs** [comment]
@yaykyle ping

**Comment by yaykyle** [comment]
Sorry for delayed response. This appears to have resolved my issues. I can now run `brew outdated` without errors.

Thank you for the help! Let me know if you need me to provide anything else.

```
$ rm -rf /usr/local/Homebrew/.git
```

```
$ brew update
Initialized empty Git repository in /usr/local/Homebrew/.git/
remote: Counting objects: 1136, done.
remote: Compressing objects: 100% (1044/1044), done.
remote: Total 1136 (delta 116), reused 368 (delta 48), pack-reused 0
Receiving objects: 100% (1136/1136), 1.21 MiB | 9.37 MiB/s, done.
Resolving deltas: 100% (116/116), done.
From https://github.com/Homebrew/brew
 * [new branch]      master     -> origin/master
HEAD is now at 357b7bb Merge pull request #3350 from DomT4/gpg_executable
To restore the stashed changes to /usr/local/Homebrew run:
  'cd /usr/local/Homebrew && git stash pop'
==> Downloading https://homebrew.bintray.com/bottles-portable/portable-ruby-2.3.3.leopard_64.bottle.1.tar.gz
######################################################################## 100.0%
==> Pouring portable-ruby-2.3.3.leopard_64.bottle.1.tar.gz
==> Homebrew has enabled anonymous aggregate user behaviour analytics.
Read the analytics documentation (and how to opt-out) here:
  https://docs.brew.sh/Analytics.html

Already up-to-date.
```

```
$ brew config
HOMEBREW_VERSION: 1.3.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 270b752f5d9d218bfbed6fe85b6974fa653fb25f
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b7d1e926e9f2e3e950866b7e82ad1fbe34f1fb12
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.14.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_101, 1.7.0_45
macOS: 10.12.6-x86_64
Xcode: 9.0.1
CLT: 9.0.1.0.1.1506734476
X11: 2.7.9 => /opt/X11
```

**Comment by jvoros** [comment]
I was having same problem with ruby multiline strings (<<~EOS).

This fixed it.
