### ISSUE TITLE
virtualenv_install_with_resources deletes some temporary files even with --keep-tmp

### ISSUE THREAD

**Issue by jbarlow83** [Homebrew/brew#3357]
- What you were trying to do (and why)

I am trying to debug my formula which fails for some users for unknown reasons while working on my machine and Travis CI.

https://github.com/jbarlow83/homebrew-ocrmypdf/blob/master/Formula/ocrmypdf.rb

In relation to this issue:
https://github.com/jbarlow83/homebrew-ocrmypdf/issues/4

- What happened (include command output)

When using `brew install --keep-tmp --debug ocrmypdf` the build log shows temporary files named things like `/private/tmp/pip-_g5xah0z-build`

It appears that the error occurred inside that source file, but Homebrew deletes it so it cannot be inspected.

The actual error message is below, but this is not helpful. It only seems to say a temporary script generated by homebrew failed:

```
Already downloaded: /Users/joe/Library/Caches/Homebrew/ocrmypdf--Pillow-4.1.1.tar.gz
==> /usr/local/Cellar/ocrmypdf/5.4.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/ocrmypdf--Pillow-20171023-71704-yb0wvf/Pillow-4.1.1
Last 15 lines from /Users/joe/Library/Logs/Homebrew/ocrmypdf/06.pip:
  Removing source in /private/tmp/pip-_g5xah0z-build
Command "/usr/local/Cellar/ocrmypdf/5.4.1/libexec/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-_g5xah0z-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-m23zgd62-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/ocrmypdf/5.4.1/libexec/bin/../include/site/python3.6/Pillow" failed with error code 1 in /private/tmp/pip-_g5xah0z-build/
Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/ocrmypdf/5.4.1/libexec/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/Cellar/ocrmypdf/5.4.1/libexec/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/Cellar/ocrmypdf/5.4.1/libexec/lib/python3.6/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/Cellar/ocrmypdf/5.4.1/libexec/lib/python3.6/site-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/usr/local/Cellar/ocrmypdf/5.4.1/libexec/lib/python3.6/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "/usr/local/Cellar/ocrmypdf/5.4.1/libexec/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-_g5xah0z-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-m23zgd62-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/ocrmypdf/5.4.1/libexec/bin/../include/site/python3.6/Pillow" failed with error code 1 in /private/tmp/pip-_g5xah0z-build/
```

- What you expected to happen

All temporary files should be retained when `--keep-tmp` is given so they can be debugged.

- Step-by-step reproduction instructions (by running `brew` commands)
Install any formula that uses `virtualenv_install_with_resources` with `--keep-tmp`, and check /tmp for temproary files

**Comment by MikeMcQuaid** [comment]
Sorry, this is a WONTFIX from us but we would accept a pull request to fix it. In future please always provide your `brew config` and `brew doctor` output as the issue template requests.
