### ISSUE TITLE
Error: stack level too deep

### ISSUE THREAD

**Issue by domoritz** [Homebrew/brew#3426]
I'm trying to run brew commands but get this error: `Error: stack level too deep`

```
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:76:in `bundle_path'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:60:in `prefix'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:85:in `installed?'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:115:in `detect_version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:105:in `version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:275:in `detect_version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:265:in `version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:193:in `installed?'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:115:in `detect_version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:105:in `version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:275:in `detect_version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:265:in `version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:193:in `installed?'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:115:in `detect_version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:105:in `version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:275:in `detect_version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:265:in `version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:193:in `installed?'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:115:in `detect_version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:105:in `version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:275:in `detect_version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:265:in `version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:193:in `installed?'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:115:in `detect_version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:105:in `version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:275:in `detect_version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:265:in `version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:193:in `installed?'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:115:in `detect_version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:105:in `version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:275:in `detect_version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:265:in `version'
...
```

I'm getting this error when I run brew doctor, config and install.

# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

brew config output: 
[brew_config.txt](https://github.com/Homebrew/brew/files/1444380/brew_config.txt)

brew doctor output:
[brew_doctor.txt](https://github.com/Homebrew/brew/files/1444381/brew_doctor.txt)

**Comment by ilovezfs** [comment]
Should be fixed now if you brew update.

**Comment by domoritz** [comment]
Thanks!
