### ISSUE TITLE
undefined method `<=' for nil:NilClass

### ISSUE THREAD

**Issue by pat-s** [Homebrew/brew#3442]
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

Appears for every `brew upgrade` `brew remove` and `brew install` and `brew doctor`.
See `brew doctor` output for more information. 

`brew doctor`

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  saga4
  docker
  lcdf-typetools
  ghostscript
  kate
  gdal
  kf5-okteta
  pygame
  qgis2-ltr
  grass7
  sip-qt4
  qgis2
Error: undefined method `<=' for nil:NilClass
Did you mean?  <=>
Please report this bug:
  https://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:151:in `resource_dep'
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:80:in `parse_spec'
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:58:in `build'
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:45:in `block in fetch'
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:45:in `fetch'
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:45:in `fetch'
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:35:in `add'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:202:in `patch'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2283:in `block in patch'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2283:in `each'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2283:in `patch'
/usr/local/Homebrew/Library/Taps/kde-mac/homebrew-kde/kf5-kdelibs4support.rb:24:in `<class:Kf5Kdelibs4support>'
/usr/local/Homebrew/Library/Taps/kde-mac/homebrew-kde/kf5-kdelibs4support.rb:3:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:27:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:27:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:47:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:102:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:239:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:93:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:89:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:229:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:280:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:311:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:294:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1384:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1382:in `each'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1382:in `flat_map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1382:in `installed'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:869:in `check_missing_deps'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:43:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

`brew config`

```
HOMEBREW_VERSION: 1.3.6-217-g441c212
ORIGIN: https://github.com/Homebrew/brew
HEAD: 441c212f2dd70f053ee21eac8398c5fe5dfd0551
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1312d96a344c3aeb6cdc91385fdb805dbf765626
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_GIT_CONFIG_FILE: /usr/local/Homebrew/.git/config
HOMEBREW_VISUAL: nano
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.15.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.1/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.2_1/bin/ruby
Java: 9.0.1, 9, 1.8.0_144, 1.8.0_141, 1.8.0_131, 1.8.0_121, 1.8.0_112, 1.8.0_102, 1.8.0_92, 1.8.0_77
macOS: 10.13.1-x86_64
Xcode: 9.1
CLT: N/A
X11: 2.7.11 => /opt/X11


```

**Comment by ilovezfs** [comment]
Please report this to https://github.com/KDE-mac/homebrew-kde/issues

There is a bug in the kf5-kdelicbs4support formula. These lines need to be removed:
https://github.com/KDE-mac/homebrew-kde/blob/38bb8d43a5b77d5efb3aece833ad922d45df6526/kf5-kdelibs4support.rb#L24-L25

CC @yurikoles

**Comment by pat-s** [comment]
Thanks @ilovezfs!

**Comment by ilovezfs** [comment]
You're welcome!
