### ISSUE TITLE
Squiggly heredocs break homebrew on 10.12 with stock Ruby 2.0.0

### ISSUE THREAD

**Issue by christophercurrie** [Homebrew/brew#3444]
Summary: I believe #3319 has broken homebrew on 10.12.x with only stock Ruby 2.0.0-p648 installed. Squiggly heredocs appear to be a Ruby 2.3 feature.

# Please always follow these steps:
- [X] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew config` and `brew doctor` and included their output with your issue?

```
$ brew config
HOMEBREW_VERSION: 1.0.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 817bc2746e594761911edd78f743a640f089494f
Last commit: 1 year, 2 months ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8c40e71a15fe779a27d059823f1d9cd00a5f70c3
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 9.0 build 900
Git: 2.14.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /Users/ccurrie/.pyenv/shims/python => /Users/ccurrie/.pyenv/versions/2.7.12/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_112, 1.8.0_92, 1.7.0_80
macOS: 10.12.6-x86_64
Xcode: 9.1
CLT: N/A
X11: 2.7.11 => /opt/X11
```

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
    /Users/ccurrie/.pyenv/shims/python-config
    /Users/ccurrie/.pyenv/shims/python2-config
    /Users/ccurrie/.pyenv/shims/python2.7-config
Error: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:73: syntax error, unexpected <<
  def caveats; <<~EOS
                 ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:77: syntax error, unexpected tIDENTIFIER, expecting keyword_end
    can add a "gnubin" directory to your PATH from your bashrc like:
                                ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:77: syntax error, unexpected ':', expecting keyword_end
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:79: dynamic constant assignment
        PATH="#{opt_libexec}/gnubin:$PATH"
             ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:81: dynamic constant assignment
    Additionally, you can access their man pag...
                 ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:81: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
    Additionally, you can access their man pages with ...
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:82: syntax error, unexpected tIDENTIFIER, expecting keyword_end
    the "gnuman" directory to your MANPATH from your bashrc as well:
                          ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:82: syntax error, unexpected ':', expecting keyword_end
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:84: dynamic constant assignment
        MANPATH="#{opt_libexec}/gnuman:$MANPATH"
                ^
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:97:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:222:in `factory'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1411:in `[]'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:927:in `check_for_non_prefixed_coreutils'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:42:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:34:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:34:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:99:in `<main>'
```

To help us debug your issue please explain:
- What you were trying to do (and why)
Trying to install gpg after a period of not updating homebrew

- What happened (include command output)
```
Error: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gnupg.rb:66: syntax error, unexpected <<
  def caveats; <<~EOS
                 ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gnupg.rb:67: void value expression
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gnupg.rb:68: syntax error, unexpected tIDENTIFIER, expecting '('
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gnupg.rb:70: syntax error, unexpected tIDENTIFIER, expecting keyword_end
    creating a backup of your `~/.gnupg` prior to first use.
                                              ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gnupg.rb:73: syntax error, unexpected keyword_in
      https://www.gnupg.org/faq/whats-new-in-2.1.html
                                            ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gnupg.rb:79: syntax error, unexpected tLABEL
      Key-Type: RSA
               ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gnupg.rb:80: syntax error, unexpected tLABEL
      Key-Length: 2048
                 ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gnupg.rb:81: syntax error, unexpected tLABEL
      Subkey-Type: RSA
                  ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gnupg.rb:82: syntax error, unexpected tLABEL
      Subkey-Length: 2048
                    ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gnupg.rb:83: syntax error, unexpected tLABEL
      Name-Real: Testing
                ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gnupg.rb:84: syntax error, unexpected tLABEL
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gnupg.rb:84: syntax error, unexpected tLABEL
      Name-Email: testing@foo.bar
                 ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gnupg.rb:85: syntax error, unexpected tLABEL
      Expire-Date: 1d
                  ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gnupg.rb:86: unknown type of %string
      %no-protection
         ^
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:97:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:222:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:387:in `find_with_priority'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:20:in `block in formulae'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:105:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:99:in `<main>'
```

- What you expected to happen
gpg to be installed.

- Step-by-step reproduction instructions (by running `brew` commands)
** Run `brew install gpg` on a MacOS 10.12 with only stock Ruby installed.

**Comment by ilovezfs** [comment]
```
git -C "$(brew --repo)" fetch --tags
brew update --force
```

**Comment by christophercurrie** [comment]
I'm sorry, but those instructions do not fix the issue. Could you please reopen?

**Comment by ilovezfs** [comment]
```
HOMEBREW_VERSION: 1.0.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 817bc2746e594761911edd78f743a640f089494f
Last commit: 1 year, 2 months ago
```

You need to get on the current version of Homebrew. Perhaps you're in a branch?

```
git -C "$(brew --repo)" status
```

**Comment by christophercurrie** [comment]
```
$ git -C "$(brew --repo)" status
On branch stable
nothing to commit, working tree clean
```

**Comment by ilovezfs** [comment]
Try
```
brew update-reset
```

**Comment by christophercurrie** [comment]
```
$ brew update-reset
Error: Unknown command: update-reset
```

**Comment by ilovezfs** [comment]
```
git -C "$(brew --repo)" rev-parse origin/master
```

**Comment by christophercurrie** [comment]
```
$ git -C "$(brew --repo)" rev-parse origin/master
2225febfb396f7db3ccf0c68feae6143128d9935
```

**Comment by ilovezfs** [comment]
```
git -C "$(brew --repo)" reset --hard origin/master
brew update-reset
```

**Comment by christophercurrie** [comment]
That did it. Not sure how I got into the broken state, but thanks for the guidance.

**Comment by ilovezfs** [comment]
no worries.

**Comment by ilovezfs** [comment]
I'm going to clear out most of the comments here since they're not things we want people copy pasting.
