### ISSUE TITLE
GitHubPrivateRepositoryReleaseDownloadStrategy asks for password and fails

### ISSUE THREAD

**Issue by alexgiuvara** [Homebrew/brew#3445]
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
1. I want to download an artifact from a private GitHub repository using this formula:
```
class Anonymizer < Formula
  desc "Encrypts a database"
  url "https://github.com/owner/repo/releases/download/v0.0.28/osx.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
....
```
2.  `owner` is our organization
3.  `repo` is a private repository that I have access to
4.  I generated a personal access token with `repo` scope used by HOMEBREW_GITHUB_API_TOKEN (alternatively I check a token with full rights on entire organization)
5. we use double auth factor (if related with password failure)
- What happened (include command output)
brew tap Owner/reponame asks for user/password, despite the fact that the HOMEBREW_GITHUB_API_TOKEN is set and valid.
```
brew tap Owner/reponame
==> Tapping owner/reponame
Cloning into '/usr/local/Homebrew/Library/Taps/owner/homebrew-reponame'...
Username for 'https://github.com': user
Password for 'https://user@github.com':
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/Owner/homebrew-reponame/'
Error: Failure while executing: git clone https://github.com/Owner/homebrew-reponame /usr/local/Homebrew/Library/Taps/owner/homebrew-reponame --depth=1
```
- What you expected to happen
to download the archive using the HOMEBREW_GITHUB_API_TOKEN
- Step-by-step reproduction instructions (by running `brew` commands)
```
~ brew --config
HOMEBREW_VERSION: 1.3.7-2-g2225feb
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2225febfb396f7db3ccf0c68feae6143128d9935
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: abca0c531748f860ec20f490c6407a4c00ba92fb
Core tap last commit: 16 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_GITHUB_USER: githubuser
HOMEBREW_GIT_CONFIG_FILE: /usr/local/Homebrew/.git/config
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.13.5 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: N/A
macOS: 10.13.1-x86_64
Xcode: N/A
CLT: 9.0.1.0.1.1506734476
X11: 2.7.11 => /opt/X11
```

```
~ brew doctor
Your system is ready to brew.
```

```
~ brew tap owner/reponame --debug
==> Tapping owner/reponame
Cloning into '/usr/local/Homebrew/Library/Taps/owner/homebrew-reponame'...
Username for 'https://github.com': githubuser
Password for 'https://githubuser@github.com':
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/owner/homebrew-reponame/'
Error: Failure while executing: git clone https://github.com/owner/homebrew-reponame /usr/local/Homebrew/Library/Taps/owner/homebrew-reponame --depth=1
/usr/local/Homebrew/Library/Homebrew/utils.rb:296:in `safe_system'
/usr/local/Homebrew/Library/Homebrew/tap.rb:245:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/tap.rb:52:in `tap'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

**Comment by MikeMcQuaid** [comment]
Sorry, you'll need to figure this out on your own.
