### ISSUE TITLE
Poppler - Failed to load shared library '@rpath/libpoppler-glib.8.dylib'

### ISSUE THREAD

**Issue by plugpulled** [Homebrew/brew#3692]
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

- Trying to run a rails server with poppler gem included in gem file.
- Command Output:
```
ruby -v -rpoppler -e ''
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
(null)-WARNING **: Failed to load shared library '@rpath/libpoppler-glib.8.dylib' referenced by the typelib: dlopen(@rpath/libpoppler-glib.8.dylib, 9): image not found
	from /Users/BigBoss/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/gobject-introspection-3.2.1/lib/gobject-introspection/loader.rb:629:in `load_union_info'
	from /Users/BigBoss/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/gobject-introspection-3.2.1/lib/gobject-introspection/loader.rb:74:in `load_info'
	from /Users/BigBoss/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/gobject-introspection-3.2.1/lib/gobject-introspection/loader.rb:43:in `block in load'
	from /Users/BigBoss/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/gobject-introspection-3.2.1/lib/gobject-introspection/repository.rb:34:in `block (2 levels) in each'
	from /Users/BigBoss/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/gobject-introspection-3.2.1/lib/gobject-introspection/repository.rb:33:in `times'
	from /Users/BigBoss/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/gobject-introspection-3.2.1/lib/gobject-introspection/repository.rb:33:in `block in each'
	from /Users/BigBoss/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/gobject-introspection-3.2.1/lib/gobject-introspection/repository.rb:32:in `each'
	from /Users/BigBoss/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/gobject-introspection-3.2.1/lib/gobject-introspection/repository.rb:32:in `each'
	from /Users/BigBoss/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/gobject-introspection-3.2.1/lib/gobject-introspection/loader.rb:42:in `load'
	from /Users/BigBoss/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/poppler-3.2.1/lib/poppler.rb:35:in `<module:Poppler>'
	from /Users/BigBoss/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/poppler-3.2.1/lib/poppler.rb:30:in `<top (required)>'
	from /Users/BigBoss/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
	from /Users/BigBoss/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from /Users/BigBoss/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
/Users/BigBoss/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/gobject-introspection-3.2.1/lib/gobject-introspection/loader.rb:162:in `const_set': wrong constant name 3D (NameError)
	from /Users/BigBoss/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/gobject-introspection-3.2.1/lib/gobject-introspection/loader.rb:162:in `load_enum_value'
	from /Users/BigBoss/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/gobject-introspection-3.2.1/lib/gobject-introspection/loader.rb:187:in `block in load_enum_info'
	from /Users/BigBoss/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/gobject-introspection-3.2.1/lib/gobject-introspection/loader.rb:186:in `each'
	from /Users/BigBoss/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/gobject-introspection-3.2.1/lib/gobject-introspection/loader.rb:186:in `load_enum_info'
	from /Users/BigBoss/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/poppler-3.2.1/lib/poppler/loader.rb:57:in `load_enum_info'
	from /Users/BigBoss/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/gobject-introspection-3.2.1/lib/gobject-introspection/loader.rb:66:in `load_info'
	from /Users/BigBoss/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/gobject-introspection-3.2.1/lib/gobject-introspection/loader.rb:43:in `block in load'
	from /Users/BigBoss/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/gobject-introspection-3.2.1/lib/gobject-introspection/repository.rb:34:in `block (2 levels) in each'
	from /Users/BigBoss/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/gobject-introspection-3.2.1/lib/gobject-introspection/repository.rb:33:in `times'
	from /Users/BigBoss/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/gobject-introspection-3.2.1/lib/gobject-introspection/repository.rb:33:in `block in each'
	from /Users/BigBoss/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/gobject-introspection-3.2.1/lib/gobject-introspection/repository.rb:32:in `each'
	from /Users/BigBoss/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/gobject-introspection-3.2.1/lib/gobject-introspection/repository.rb:32:in `each'
	from /Users/BigBoss/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/gobject-introspection-3.2.1/lib/gobject-introspection/loader.rb:42:in `load'
	from /Users/BigBoss/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/poppler-3.2.1/lib/poppler.rb:35:in `<module:Poppler>'
	from /Users/BigBoss/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/poppler-3.2.1/lib/poppler.rb:30:in `<top (required)>'
	from /Users/BigBoss/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
	from /Users/BigBoss/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from /Users/BigBoss/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require' 
```
- Expected to run Rails server without any issues
- Step by Step commands:

1. brew install poppler
2. bundle install (included poppler in gem file)
3. rails s
4. the above crash is produced.

This could be a problem with path not set correctly. My dependency exists because i'm trying to integrate this https://documentcloud.github.io/docsplit/. 
I posted on developer's github which he says is problem with path set by brew ([Refer](https://github.com/ruby-gnome2/ruby-gnome2/issues/1124#issuecomment-357696737)).

This command might help
```
% ruby -r fiddle -e 'p Fiddle.dlopen("libpoppler.dylib")'
% DYLD_LIBRARY_PATH=/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/:$(brew --prefix)/lib ruby -r fiddle -e 'p Fiddle.dlopen("libpoppler.dylib")'
```

**Comment by meetajhu** [comment]
Hi @ilovezfs 

I did post [there](https://github.com/ruby-gnome2/ruby-gnome2/issues/1124)

The developer says its a issue with Homebrew. Since Ubuntu(Linux) doesn't have this issue because the path mentioned are proper.

**Comment by MikeMcQuaid** [comment]
Regardless, this is not a Homebrew issue as it's coming from `rbenv` and your Rails application.

**Comment by meetajhu** [comment]
oh. I'll take a look.
