### ISSUE TITLE
Calling 'depends_on :python' is deprecated

### ISSUE THREAD

**Issue by phush0** [Homebrew/brew#3711]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed all issues and retried your prior step?
```
Warning: Calling 'depends_on :python' is deprecated!
Use 'depends_on "python"' instead.
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:88:in `parse_spec'
```
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

```
HOMEBREW_VERSION: 1.5.0-6-gd14fd49
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: d14fd49b3062ab1d95e86b78a8228c8aee3a3304
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7ac6f28b4dd06a5a086d085d2b1ada65ba64aa51
Core tap last commit: 80 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.16.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: 1.8.0_45
macOS: 10.13.3-x86_64
Xcode: 9.2
CLT: 9.2.0.0.1.1510905681
X11: 2.7.11 => /opt/X11
```

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/python2.7/greenlet/greenlet.h
  /usr/local/include/python3.6m/greenlet/greenlet.h
Warning: Calling 'depends_on :python' is deprecated!
Use 'depends_on "python"' instead.
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:88:in `parse_spec'
```

To help us debug your issue please explain:
On brew update or brew doctor I have this warning. Brew is still working but on every updated formula this rows pop up.

**Comment by ilovezfs** [comment]
What's the output of
```
find $(brew --cellar) -maxdepth 4 -mindepth 4 -regex '.*\.rb$' -exec grep -r 'depends_on :hg' "{}" \;
```

**Comment by phush0** [comment]
empty string

**Comment by ilovezfs** [comment]
Sorry I meant
```
find $(brew --cellar) -maxdepth 4 -mindepth 4 -regex '.*\.rb$' -exec grep -r 'depends_on :python' "{}" \;
```

**Comment by phush0** [comment]
```
/usr/local/Cellar/libxml2/2.9.7/.brew/libxml2.rb:  depends_on :python if MacOS.version <= :snow_leopard
/usr/local/Cellar/pygobject3/3.26.1/.brew/pygobject3.rb:  depends_on :python3 => :optional
/usr/local/Cellar/llvm/5.0.1/.brew/llvm.rb:    depends_on :python
/usr/local/Cellar/llvm/5.0.1/.brew/llvm.rb:    depends_on :python => :optional
/usr/local/Cellar/mpv/HEAD-69ae23f_3/.brew/mpv.rb:  depends_on :python3 => :build
/usr/local/Cellar/py2cairo/1.15.4/.brew/py2cairo.rb:  depends_on :python if MacOS.version <= :snow_leopard
/usr/local/Cellar/itstool/2.0.4_1/.brew/itstool.rb:  depends_on :python if MacOS.version <= :snow_leopard
/usr/local/Cellar/libepoxy/1.4.3/.brew/libepoxy.rb:  depends_on :python => :build if MacOS.version <= :snow_leopard
/usr/local/Cellar/meld/3.16.4/.brew/meld.rb:  depends_on :python
/usr/local/Cellar/protobuf/3.5.1/.brew/protobuf.rb:  depends_on :python => :recommended if MacOS.version <= :snow_leopard
/usr/local/Cellar/protobuf/3.5.1/.brew/protobuf.rb:  depends_on :python3 => :optional

```

**Comment by ilovezfs** [comment]
```
brew update
brew upgrade
brew rm -f --ignore-dependencies mpv
brew cleanup libxml2 pygobject3 llvm mpv py2cairo itstool libepoxy meld protobuf
brew install --HEAD mpv
```

**Comment by ilovezfs** [comment]
Good!

**Comment by kirk86** [comment]
I'm getting the same thing but I'm not quite sure if I should remove everything and reinstall?

```
Warning: Calling 'depends_on :fortran' is deprecated!
Use 'depends_on "gcc"' instead.
/usr/local/Homebrew/Library/Taps/staticfloat/homebrew-julia/arpack-julia.rb:19:in `<class:ArpackJulia>'
Please report this to the staticfloat/julia tap!

Warning: Calling 'depends_on :python' is deprecated!
Use 'depends_on "python"' instead.
/usr/local/Homebrew/Library/Taps/staticfloat/homebrew-julia/llvm37-julia.rb:149:in `<class:Llvm37Julia>'
Please report this to the staticfloat/julia tap!
```

```
ind $(brew --cellar) -maxdepth 4 -mindepth 4 -regex '.*\.rb$' -exec grep -r 'depends_on :python' "{}" \;
/usr/local/Cellar/libmagic/5.32/.brew/libmagic.rb:  depends_on :python => :optional
/usr/local/Cellar/nlopt/2.4.2_2/.brew/nlopt.rb:  depends_on :python => "numpy" if build.with? "python"
/usr/local/Cellar/tbb/2018_U2/.brew/tbb.rb:  depends_on :python if MacOS.version <= :snow_leopard
/usr/local/Cellar/graphviz/2.40.1/.brew/graphviz.rb:    depends_on :python
```

```
find $(brew --cellar) -maxdepth 4 -mindepth 4 -regex '.*\.rb$' -exec grep -r 'depends_on :fortran' "{}" \;
/usr/local/Cellar/hdf5/1.10.1_2/.brew/hdf5.rb:  depends_on :fortran
/usr/local/Cellar/openblas-julia/0.2.20/.brew/openblas-julia.rb:  depends_on :fortran
```

**Comment by MikeMcQuaid** [comment]
> staticfloat/homebrew-julia

@kirk86 Report this to that tap.

**Comment by kirk86** [comment]
@MikeMcQuaid  Thanks, I just did! I didn't notice the message indicating where to report the bug in the first place.
