### ISSUE TITLE
Undefined method: patch for #<Resource

### ISSUE THREAD

**Issue by stevehayaes** [Homebrew/brew#3737]
# Please always follow these steps:
- [ X ] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [ X ] Ran `brew update` and retried your prior step?
- [ X ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ X ] Ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
    I had just installed rust (successfully) and I tried to uninstall rust. 

- What happened (include command output)
    It appears that rust did not uninstall. The command `brew uninstall rust`, and the error happens when I issue `brew update` and `brew doctor` as well. Output from `brew install rust`:

```
[steve.hay@Steves-MacBook-Pro ~ $] brew install rust
Updating Homebrew...
Auto packing the repository in background for optimum performance.
See "git help gc" for manual housekeeping.
Auto packing the repository in background for optimum performance.
See "git help gc" for manual housekeeping.
==> Auto-updated Homebrew!
Updated 3 taps (homebrew/core, caskroom/drivers, caskroom/cask).
==> Updated Formulae
oniguruma ✔         augeas              cromwell            dscanner            fn                  hadolint            micro               saldl               w3m
angular-cli         certbot             diamond             firebase-cli        gradle              iron-functions      mp3gain             superlu
Error: undefined method `patch' for #<Resource:0x0000010102b410>
Please report this bug:
  https://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/llvm.rb:66:in `block (2 levels) in <class:Llvm>'
/usr/local/Homebrew/Library/Homebrew/resource.rb:49:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/resource.rb:49:in `initialize'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:111:in `new'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:111:in `resource'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/llvm.rb:59:in `block in <class:Llvm>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2109:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2109:in `stable'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/llvm.rb:23:in `<class:Llvm>'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/llvm.rb:19:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:27:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:27:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:47:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:102:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:239:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:93:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:89:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:229:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:280:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:311:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:294:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1386:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1384:in `each'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1384:in `flat_map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1384:in `installed'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:506:in `migrate_formula_rename'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:101:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:101:in `update_report'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
==> Installing dependencies for rust: libssh2
==> Installing rust dependency: libssh2
==> Downloading https://homebrew.bintray.com/bottles/libssh2-1.8.0.high_sierra.bottle.1.tar.gz
######################################################################## 100.0%
==> Pouring libssh2-1.8.0.high_sierra.bottle.1.tar.gz
🍺  /usr/local/Cellar/libssh2/1.8.0: 182 files, 797.4KB
==> Installing rust
==> Downloading https://homebrew.bintray.com/bottles/rust-1.23.0.high_sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring rust-1.23.0.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/rust/1.23.0: 5,995 files, 375.3MB
```

- What you expected to happen
    The automated brew update should have happened without error, and the installation and uninstallation of rust both should have been successful.

- Step-by-step reproduction instructions (by running `brew` commands)
    Not sure if I know how to reproduce from a bare system not showing this error, but here is what I did...
```
brew install rust
brew uninstall rust
brew doctor
```
Is it possible this is  LLVM related?

# Features
N/A

# brew config output
```
HOMEBREW_VERSION: 1.5.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 985202cf8e3f9e221753dd99adf1e8874fece03a
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d7895a19fb7781635e85a52db150da56077b47ca
Core tap last commit: 7 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GITHUB_API_TOKEN: set
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.16.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.1/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: 1.8.0_121
macOS: 10.13.3-x86_64
Xcode: 9.2
CLT: 9.2.0.0.1.1510905681
X11: 2.7.11 => /opt/X11
```

# brew doctor output
```
Error: undefined method `patch' for #<Resource:0x0000010283fcb8>
Please report this bug:
  https://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/llvm.rb:66:in `block (2 levels) in <class:Llvm>'
/usr/local/Homebrew/Library/Homebrew/resource.rb:49:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/resource.rb:49:in `initialize'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:111:in `new'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:111:in `resource'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/llvm.rb:59:in `block in <class:Llvm>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2109:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2109:in `stable'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/llvm.rb:23:in `<class:Llvm>'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/llvm.rb:19:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:27:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:27:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:47:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:102:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:239:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:93:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:89:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:229:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:280:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:311:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:294:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:1003:in `block in check_for_unlinked_but_not_keg_only'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:1000:in `reject'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:1000:in `check_for_unlinked_but_not_keg_only'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:46:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:38:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:38:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

**Comment by ilovezfs** [comment]
Your Homebrew is outdated. Please try `brew update --force` and then post `brew config`

**Comment by stevehayaes** [comment]
### brew update --force

```
Already up-to-date.
```

### brew config
```
HOMEBREW_VERSION: 1.5.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 60a30e966b7cece5bd4823dae3fb981ab85106ea
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d7895a19fb7781635e85a52db150da56077b47ca
Core tap last commit: 8 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GITHUB_API_TOKEN: set
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.16.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.1/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: 1.8.0_121
macOS: 10.13.3-x86_64
Xcode: 9.2
CLT: 9.2.0.0.1.1510905681
X11: 2.7.11 => /opt/X11
```
I believe the issue has been fixed with the --force command. Thanks.

For completeness, here's my `brew doctor` output:
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile
```

**Comment by ilovezfs** [comment]
You're welcome!
