### ISSUE TITLE
Error: undefined method `patch'

### ISSUE THREAD

**Issue by bcardarella** [Homebrew/brew#3750]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
  I was trying to uninstall a package.
- What happened (include command output)

I get the following output:

```
Error: undefined method `patch' for #<Resource:0x00000102bccde0>
Please report this bug:
  https://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/elm.rb:19:in `block (2 levels) in <class:Elm>'
/usr/local/Homebrew/Library/Homebrew/resource.rb:49:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/resource.rb:49:in `initialize'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:111:in `new'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:111:in `resource'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/elm.rb:13:in `block in <class:Elm>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2113:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2113:in `stable'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/elm.rb:9:in `<class:Elm>'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/elm.rb:3:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:27:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:27:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:47:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:102:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:239:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:93:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:89:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:229:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:280:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:311:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:294:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1384:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1382:in `each'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1382:in `flat_map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1382:in `installed'
/usr/local/Homebrew/Library/Homebrew/keg.rb:119:in `find_some_installed_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:90:in `check_for_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:83:in `handle_unsatisfied_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:31:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

Here is the output from `brew config`

```
HOMEBREW_VERSION: 1.3.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4f5e938a5dbe049e05dea19495b6547acc5c5b5b
Last commit: 8 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 628620e3b1c3c9fb3cbf6bb1c90338c7ae9371ee
Core tap last commit: 7 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
GCC-4.2: build 5666
Clang: 9.0 build 900
Git: 2.2.1.62 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.1/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.2_1/bin/ruby
Java: 1.8.0_73
macOS: 10.13.2-x86_64
Xcode: 9.2
CLT: N/A
X11: N/A
```

Here is the output from `brew doctor`

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  phantomjs@1.98
Error: undefined method `patch' for #<Resource:0x000001024be030>
Please report this bug:
  https://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/elm.rb:19:in `block (2 levels) in <class:Elm>'
/usr/local/Homebrew/Library/Homebrew/resource.rb:49:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/resource.rb:49:in `initialize'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:111:in `new'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:111:in `resource'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/elm.rb:13:in `block in <class:Elm>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2113:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2113:in `stable'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/elm.rb:9:in `<class:Elm>'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/elm.rb:3:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:27:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:27:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:47:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:102:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:239:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:93:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:89:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:229:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:280:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:311:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:294:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1384:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1382:in `each'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1382:in `flat_map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1382:in `installed'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:870:in `check_missing_deps'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:43:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

- What you expected to happen

The package to uninstall without error

- Step-by-step reproduction instructions (by running `brew` commands)

Noted above

**Comment by bcardarella** [comment]
This appears to be an issue for most (all?) `brew` commands. I just tried to `brew install` something and got the same error.

**Comment by wndxlori** [comment]
+1 I am experiencing this exact bug

**Comment by scpeters** [comment]
Your `brew` says it is 8 weeks old, but `homebrew-core` says 7 hours old. They are both complaining about syntax in the `elm` formula that was updated in https://github.com/Homebrew/homebrew-core/pull/23146

The following command should update your `brew` repository:

~~~
cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update
~~~

Are you purposefully using an old version of `brew`?

**Comment by MikeMcQuaid** [comment]
`brew update --force` and if that doesn't work `brew update-reset`.
