### ISSUE TITLE
Having trouble installing a bottle...

### ISSUE THREAD

**Issue by jszakmeister** [Homebrew/brew#3766]
I would treat this as a formula error, but I suspect it's actually a Homebrew issue.  I tried installing wine via Homebrew and it just hangs:

```text
:: brew install -v wine
==> Downloading https://homebrew.bintray.com/bottles/wine-3.0.high_sierra.bottle.tar.gz
Already downloaded: /Users/jszakmeister/Library/Caches/Homebrew/wine-3.0.high_sierra.bottle.tar.gz
==> Verifying wine-3.0.high_sierra.bottle.tar.gz checksum
==> Pouring wine-3.0.high_sierra.bottle.tar.gz
tar xzf /Users/jszakmeister/Library/Caches/Homebrew/wine-3.0.high_sierra.bottle.tar.gz
```

I've run the tar command outside of Homebrew without issue.  The tar file looks fine and the content looks fine too.  However, Homebrew doesn't appear to move on and I can't figure out why.  I'm happy to help debug if you can provide me some guidance.  FWIW, other bottles seemed to install fine, so it's possible this is actually a formula issue--I just can't confirm it one way or the other right now based on the outputs that I see.

# Please always follow these steps:
- [ ] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new

  - I cannot confirm this, though it appears to be a core issue to me since we're failing to move on from a tar command.

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

`brew config`

```text
:: brew config
HOMEBREW_VERSION: 1.5.2-48-g62f85cf
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 62f85cfabbcff722afb406e48e56d5b10e6fc654
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: dc0c6aa82e15ec88b75b91d1760b1f0e6230c899
Core tap last commit: 45 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_NO_EMOJI: 1
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.16.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: 1.8.0_112, 1.8.0_102, 1.8.0_65, 1.8.0_25
macOS: 10.13.3-x86_64
Xcode: 9.2
CLT: 9.2.0.0.1.1510905681
X11: 2.7.11 => /opt/X11
```

`brew doctor`

```text
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2-config
  /System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7-config
  /System/Library/Frameworks/Python.framework/Versions/2.7/bin/python-config

Warning: Some frameworks can be picked up by CMake's build system and likely
cause the build to fail. To compile CMake, you may wish to move these
out of the way:
  /Library/Frameworks/libcurl.framework
```

**Comment by MikeMcQuaid** [comment]
What's the error message? I don't see one?

**Comment by jszakmeister** [comment]
Sorry Mike, there is no error message--it just hangs.  From the output, it appears to be waiting for tar to finish, but looking at the disk, it already has.  I let things sit for 30 minutes just in case, but it never completed and returned to the prompt. :-(

**Comment by ilovezfs** [comment]
Is there anything in /usr/local/Cellar/wine/3.0/ ?

**Comment by jszakmeister** [comment]
Yes, it looks like everything is there.  If I watch, I can see the tar process fire up and exit, but brew still seems to be waiting for it to end. :-(

**Comment by ilovezfs** [comment]
What does it print if you hit control + \

**Comment by jszakmeister** [comment]
```text
^\Error: SIGQUIT
Warning: Bottle installation failed: building from source.
/usr/bin/sandbox-exec -f /tmp/homebrew20180205-30362-nww3y1.sb nice /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/wine.rb --verbose
```

And then proceeds to build from source.

**Comment by ilovezfs** [comment]
how about if you `export HOMEBREW_DEVELOPER=1` and run with `brew install --debug --verbose wine` and then hit control + \ while it's stuck.

**Comment by jszakmeister** [comment]
```text
:: brew install --debug --verbose wine
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/wine.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pkg-config.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/cmake.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/sphinx-doc.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/makedepend.rb
==> Downloading https://homebrew.bintray.com/bottles/wine-3.0.high_sierra.bottle.tar.gz
Already downloaded: /Users/jszakmeister/Library/Caches/Homebrew/wine-3.0.high_sierra.bottle.tar.gz
==> Verifying wine-3.0.high_sierra.bottle.tar.gz checksum
==> Pouring wine-3.0.high_sierra.bottle.tar.gz
tar xzf /Users/jszakmeister/Library/Caches/Homebrew/wine-3.0.high_sierra.bottle.tar.gz
^\Error: SIGQUIT
Please report this bug:
  https://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Homebrew/vendor/macho/macho.rb:28:in `read'
/usr/local/Homebrew/Library/Homebrew/vendor/macho/macho.rb:28:in `block in open'
/usr/local/Homebrew/Library/Homebrew/vendor/macho/macho.rb:28:in `open'
/usr/local/Homebrew/Library/Homebrew/vendor/macho/macho.rb:28:in `open'
/usr/local/Homebrew/Library/Homebrew/os/mac/mach.rb:8:in `macho'
/usr/local/Homebrew/Library/Homebrew/os/mac/mach.rb:18:in `mach_data'
/usr/local/Homebrew/Library/Homebrew/os/mac/mach.rb:98:in `dylib?'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/keg_relocate.rb:118:in `block in mach_o_files'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/pathname.rb:563:in `block in find'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/find.rb:49:in `block (2 levels) in find'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/find.rb:48:in `catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/find.rb:48:in `block in find'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/find.rb:43:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/find.rb:43:in `find'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/pathname.rb:563:in `find'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/keg_relocate.rb:116:in `mach_o_files'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/keg_relocate.rb:23:in `relocate_dynamic_linkage'
/usr/local/Homebrew/Library/Homebrew/keg_relocate.rb:55:in `replace_placeholders_with_locations'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:858:in `pour'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:295:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:342:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:232:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:230:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:230:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

**Comment by ilovezfs** [comment]
Is there anything unusual or special about your Homebrew installation or Mac's setup? For example, is anything involved here on external storage?

**Comment by jszakmeister** [comment]
No, it's pretty typical.  No external storage or shares.  I do have Docker installed along with Sophos (anti-virus) and Little Snitch (to monitor network connections, but I turned it off prior to trying again, just in case... it made no difference).

**Comment by ilovezfs** [comment]
what happens if you
```
rm -rf "$(brew --repo)"/Library/Homebrew/vendor
git -C "$(brew --repo)" checkout .
```
and try again

**Comment by jszakmeister** [comment]
Same issue.  I have to run to a meeting, but I'll happily run through other suggestions later!

**Comment by MikeMcQuaid** [comment]
Can you try to turn off your antivirus temporarily?

**Comment by jszakmeister** [comment]
Well, I was going to try that but just did another test run and something has changed.  I'm now at a different location, so maybe that had some affect?  Unfortunately, I can't reproduce the problem now. :-(  If something changes, I'll bring it up again.  Thank you both for trying to help!  And sorry we could point to something concrete as the issue.

**Comment by jszakmeister** [comment]
So I'm back at my previous location and there is some interaction happening between the anti-virus and Homebrew.  I think the anti-virus is trying to reach out to a service and for some reason isn't getting a response.  Temporarily disabling Sophos did let things proceed though.  It's a bit disappointing--Sophos has bene pretty well-behaved for quite a while.  Guess that status has changed.  Sorry for wasting your time on this, and I'll be sure to make sure anti-virus isn't getting in the way in the future.  I was pretty convinced it was not the problem since 20 other packages installed just fine (most of them bottles).

Thanks again for the help!

**Comment by MikeMcQuaid** [comment]
For what it's worth antivirus on macOS is completely unnecessary (and on modern versions of Windows too). Good luck in future.
