### ISSUE TITLE
Multiple errors on brew install <x>, brew doctor, brew upgrade

### ISSUE THREAD

**Issue by heisenburger** [Homebrew/brew#3772]
## Checklist:
- [x] _Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new_
- [x] _Ran `brew update` and retried your prior step?_
    - Already up-to-date.
- [x] _Ran `brew doctor`, fixed all issues and retried your prior step?_
    - **Note**: running `brew doctor` also throws up a similar list of errors
- [x] _Ran `brew config` and `brew doctor` and included their output with your issue?_
    - Here is my `brew config`:

```
HOMEBREW_VERSION: >1.0.0 (no git repository)
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 63122c241ce5c46e8201fe55773632e11e7eb187
Last commit: 1 year, 4 months ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 83f665fe3cefb8adeb0c447343d813eb30eea579
Core tap last commit: 7 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 9.0 build 900
Git: 2.14.1 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /Users/734665/.rbenv/shims/ruby => /Users/734665/.rbenv/versions/2.1.2/bin/ruby
Java: 1.7.0_45
macOS: 10.12.6-x86_64
Xcode: 9.2
CLT: 9.2.0.0.1.1510905681
X11: N/A
```

_To help us debug your issue please explain:_
- _What you were trying to do (and why)_
    - I was trying to install python3 and came across the errors. I then ran `brew update`, `brew upgrade` (error'd) and `brew doctor` (error'd) in an attempt to troubleshoot.
- _What happened (include command output)_
    - Here are the errors I get while trying to run `brew doctor`:

```
$ brew doctor
Error: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:72: syntax error, unexpected <<
  def caveats; <<~EOS
                 ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:76: syntax error, unexpected tIDENTIFIER, expecting keyword_end
    can add a "gnubin" directory to your PATH from your bashrc like:
                                ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:76: syntax error, unexpected ':', expecting keyword_end
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:78: dynamic constant assignment
        PATH="#{opt_libexec}/gnubin:$PATH"
             ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:80: dynamic constant assignment
    Additionally, you can access their man pag...
                 ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:80: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
    Additionally, you can access their man pages with ...
                         ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:81: syntax error, unexpected tIDENTIFIER, expecting keyword_end
    the "gnuman" directory to your MANPATH from your bashrc as well:
                          ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:81: syntax error, unexpected ':', expecting keyword_end
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:83: dynamic constant assignment
        MANPATH="#{opt_libexec}/gnuman:$MANPATH"
                ^
Please report this bug:
  https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:97:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:222:in `factory'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1411:in `[]'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:944:in `check_for_non_prefixed_coreutils'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:43:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'

```

- _What you expected to happen_
    - I expected some troubleshooting information :(
- _Step-by-step reproduction instructions (by running `brew` commands)_
    - The following brew commands error out for me:
        - `brew upgrade`
        - `brew doctor`
        - `brew install [formula]`

I suspect `HOMEBREW_VERSION: >1.0.0 (no git repository)` is a problem, though I can't find how to add a git repo for brew. I also suspect it might be an x-code problem, as I had just completed an update prior, but I'm not sure how to get to the bottom of it. Any help or direction at all would be very much appreciated.

Thanks :)

**Comment by scpeters** [comment]
From https://github.com/Homebrew/brew/issues/3750#issuecomment-362154576:

`brew update --force` and if that doesn't work `brew update-reset`

**Comment by heisenburger** [comment]
Wow, that seems to have fixed it! Thank you so much!
