### ISSUE TITLE
Endless loop during install name fixing

### ISSUE THREAD

**Issue by felixbuenemann** [Homebrew/brew#3786]
I'm trying to put together a working Samba 4.7.5 formula based on the graveyard formula and fixes from @DomT4.

Compilation and install step works fine, but `brew` runs into an endless loop while trying to fix install names on the installed dylibs.

Here's a gist of the formula: https://gist.github.com/0bfe17b7da8a6470880f33008bae828a

Way to reproduce:

```
brew install --verbose --debug https://gist.githubusercontent.com/felixbuenemann/0bfe17b7da8a6470880f33008bae828a/raw/c29799fee2a13614089db258568f79e9ddcf9da5/samba.rb
```

Make sure Xcode CLT is installed, or you will get lots of "clang: error: no input files" during compilation.

Brew will go through the entire install phase successfully and then start running name tool to fix lib install paths in the installed .dylib (samba libs) and .so (python libs) files.

This process goes on forever, I killed it with Ctrl+C after half an hour or so.

By looking at the console output it appears the same files are processed over and over again.

It also reports a warning that the path could not be replaced for some files – maybe because it was already replaced?

Output from `brew config`:

```
HOMEBREW_VERSION: 1.5.3-8-g021fe22
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 021fe22e3c982b08346422d1e7897e929a709380
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 681bec80827b271260fe0535f3e64d00b1620bb9
Core tap last commit: 76 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: --appdir=/Applications
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.15.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.1/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/felix/.rvm/rubies/ruby-2.5.0/bin/ruby
Java: 1.8.0_144, 1.8.0_20, 1.6.0_65-b14-468
macOS: 10.13.3-x86_64
Xcode: 9.2
CLT: 9.2.0.0.1.1510905681
X11: 2.7.11 => /opt/X11
```

Output from `brew doctor`:

```
Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libbase64.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/python2.7/greenlet/greenlet.h
```

Here's a snipped of the repetitive output while fixing linkage:

```
Changing install name in /usr/local/Cellar/samba/4.7.5/bin/regpatch
  from /private/tmp/samba-20180210-81358-i9n1xk/samba-4.7.5/bin/default/source4/dsdb/libsamdb-common-samba4.dylib
    to /usr/local/Cellar/samba/4.7.5/lib/samba/libsamdb-common-samba4.dylib
Warning: Could not fix /private/tmp/samba-20180210-81358-i9n1xk/samba-4.7.5/bin/default/source4/heimdal_build/libcom_err-samba4.dylib in /usr/local/Cellar/samba/4.7.5/bin/regpatch
Warning: Could not fix /private/tmp/samba-20180210-81358-i9n1xk/samba-4.7.5/bin/default/lib/ldb/libldb.dylib in /usr/local/Cellar/samba/4.7.5/bin/regpatch
Warning: Could not fix /private/tmp/samba-20180210-81358-i9n1xk/samba-4.7.5/bin/default/source4/heimdal_build/libgssapi-samba4.dylib in /usr/local/Cellar/samba/4.7.5/bin/regpatch
Warning: Could not fix /private/tmp/samba-20180210-81358-i9n1xk/samba-4.7.5/bin/default/lib/talloc/libtalloc.dylib in /usr/local/Cellar/samba/4.7.5/bin/regpatch
Changing install name in /usr/local/Cellar/samba/4.7.5/bin/regpatch
  from /private/tmp/samba-20180210-81358-i9n1xk/samba-4.7.5/bin/default/auth/credentials/libsamba-credentials.dylib
    to /usr/local/Cellar/samba/4.7.5/lib/libsamba-credentials.dylib
Changing install name in /usr/local/Cellar/samba/4.7.5/bin/regpatch
  from /private/tmp/samba-20180210-81358-i9n1xk/samba-4.7.5/bin/default/source4/lib/registry/libregistry-samba4.dylib
    to /usr/local/Cellar/samba/4.7.5/lib/samba/libregistry-samba4.dylib
Changing install name in /usr/local/Cellar/samba/4.7.5/bin/regpatch
  from /private/tmp/samba-20180210-81358-i9n1xk/samba-4.7.5/bin/default/lib/param/libsamba-hostconfig.dylib
    to /usr/local/Cellar/samba/4.7.5/lib/libsamba-hostconfig.dylib
Warning: Could not fix /private/tmp/samba-20180210-81358-i9n1xk/samba-4.7.5/bin/default/lib/tevent/libtevent.dylib in /usr/local/Cellar/samba/4.7.5/bin/regpatch
Changing install name in /usr/local/Cellar/samba/4.7.5/bin/regpatch
  from /private/tmp/samba-20180210-81358-i9n1xk/samba-4.7.5/bin/default/lib/dbwrap/libdbwrap-samba4.dylib
    to /usr/local/Cellar/samba/4.7.5/lib/samba/libdbwrap-samba4.dylib
Changing install name in /usr/local/Cellar/samba/4.7.5/bin/regpatch
  from /private/tmp/samba-20180210-81358-i9n1xk/samba-4.7.5/bin/default/libcli/security/libsamba-security-samba4.dylib
    to /usr/local/Cellar/samba/4.7.5/lib/samba/libsamba-security-samba4.dylib
Changing install name in /usr/local/Cellar/samba/4.7.5/bin/regpatch
  from /private/tmp/samba-20180210-81358-i9n1xk/samba-4.7.5/bin/default/lib/tdb_wrap/libtdb-wrap-samba4.dylib
    to /usr/local/Cellar/samba/4.7.5/lib/samba/libtdb-wrap-samba4.dylib
```

And the backtrace when aborting it (might be usefull to find the right methods):

```
Changing install name in /usr/local/Cellar/samba/4.7.5/bin/regpatch
  from /private/tmp/samba-20180210-81358-i9n1xk/samba-4.7.5/bin/default/libcli/auth/libcliauth-samba4.dylib
    to /usr/local/Cellar/samba/4.7.5/lib/samba/libcliauth-samba4.dylib
^CError: Failed to fix install linkage
The formula built, but you may encounter issues using it or linking other
formula against it.
==>
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/find.rb:65:in `block (3 levels) in find'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/find.rb:64:in `reverse_each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/find.rb:64:in `block (2 levels) in find'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/find.rb:48:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/find.rb:48:in `block in find'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/find.rb:43:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/find.rb:43:in `find'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/pathname.rb:563:in `find'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/keg_relocate.rb:110:in `find_dylib'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/keg_relocate.rb:73:in `fixed_name'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/keg_relocate.rb:13:in `block (3 levels) in fix_dynamic_linkage'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/keg_relocate.rb:84:in `each'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/keg_relocate.rb:84:in `each_install_name_for'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/keg_relocate.rb:7:in `block (2 levels) in fix_dynamic_linkage'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:384:in `ensure_writable'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/keg_relocate.rb:4:in `block in fix_dynamic_linkage'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/keg_relocate.rb:3:in `each'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/keg_relocate.rb:3:in `fix_dynamic_linkage'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:811:in `fix_dynamic_linkage'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:589:in `finish'
/usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:48:in `reinstall_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:19:in `block in reinstall'
/usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:13:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:13:in `reinstall'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
/usr/bin/sandbox-exec -f /tmp/homebrew20180210-96284-hji855.sb nice /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/postinstall.rb /Users/felix/Library/Caches/Homebrew/Formula/samba.rb --verbose --debug
/usr/local/Homebrew/Library/Homebrew/postinstall.rb (Formulary::FromPathLoader): loading /Users/felix/Library/Caches/Homebrew/Formula/samba.rb
```

# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Homebrew/homebrew-core https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew` commands)

We will close this issue or ask you to create a pull-request if it's something we're not actively planning to work on.

**Comment by woodruffw** [comment]
I'll take a look at this tonight. Thanks for the report, @felixbuenemann!

**Comment by felixbuenemann** [comment]
@woodruffw Did you make any progress on this?

**Comment by woodruffw** [comment]
@felixbuenemann I was able to replicate it, but I've been a bit busy. My best guess so far is that Samba's build tree has some kind of vicious link in it, and it's confusing our `mach_o_files` method. But we check for links to avoid clobbering our own work, so I'm not sure.

```ruby
  def mach_o_files
    hardlinks = Set.new
    mach_o_files = []
    path.find do |pn|
      next if pn.symlink? || pn.directory?
      next unless pn.dylib? || pn.mach_o_bundle? || pn.mach_o_executable?
      # if we've already processed a file, ignore its hardlinks (which have the same dev ID and inode)
      # this prevents relocations from being performed on a binary more than once
      next unless hardlinks.add? [pn.stat.dev, pn.stat.ino]
      mach_o_files << pn
    end

    mach_o_files
  end
```

**Comment by felixbuenemann** [comment]
I think I checked the samba install dir in the cellar for symlinks using "find -type l" before opening this issue, but that did not turn up anything suspicious. I did not check for hardlinks though.

**Comment by felixbuenemann** [comment]
@woodruffw Replying here to remove the stale issue, let me know if you have any news on this issue or ideas how to debug it.

**Comment by MikeMcQuaid** [comment]
Given this just seems to be affecting you @felixbuenemann I'm going to close this out but you and @woodruffw should continue to chat away here.
