### ISSUE TITLE
brew upgrade failed with unexpected token at `Homebrew/vendor/portable-ruby/`

### ISSUE THREAD

**Issue by ExiaSR** [Homebrew/brew#3918]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
    - I am trying to upgrade all formulas.
- What happened (include command output)
    - [https://gist.github.com/ExiaSR/a628519bf3580999d12a0d9b5e731971](https://gist.github.com/ExiaSR/a628519bf3580999d12a0d9b5e731971)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew` commands)
    - `brew update`
    - `brew upgrade`
    - then it broke with the above error message in the gist.
    - `brew update` * 2
    - `brew doctor`
    - then it broke again with the above error message in the gist.

## Additional info
I don't know what's wrong with all those wired characters.

### `brew config`
```
→ brew config
HOMEBREW_VERSION: 1.5.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: 04efbadb9ef155c5921a03bf5f5d9052cd378c21
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e0358eef635d6a93e8b7d7ebee2e1ab1964d90c9
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_RUBY_WARNINGS: -W0
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.15.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.3_1/bin/ruby
Java: 1.8.0_131, 1.8.0_121
macOS: 10.13.3-x86_64
Xcode: 9.2
CLT: 9.2.0.0.1.1510905681
X11: 2.7.11 => /opt/X11
```
### `brew install python3`
The error message shows up agagin, though the installation went through.
```
→ brew install python3
==> Processing python3 formula rename to python
==> Unlinking python3
==> Temporarily unlinking python
==> Moving python3 versions to /usr/local/Cellar/python
==> Relinking python
Error: Error occurred while migrating.
784: unexpected token at '����F������ܚ��F ��#0j�E�h����U����O~b�4>�M,�i�8�̫���~��
                                                                                ��iޟ��Ќ
                                                                                       XQ����P^�ģ����������ܷe1��hG�MT7��z0]�r�Sj7���K�O5�#-N�WS8�%&-n�WO�ntB��F<1r�:�'
Backing up...
==> Installing dependencies for python: gdbm, sqlite
==> Installing python dependency: gdbm
==> Downloading https://homebrew.bintray.com/bo
```

### `brew doctor`
```
→ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libmysqlclient.20.dylib
  /usr/local/lib/libmysqlclient.dylib

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
  /usr/local/lib/pkgconfig/mysqlclient.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libmysqlclient.a
  /usr/local/lib/libmysqld.a
  /usr/local/lib/libmysqlservices.a

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  opencv
  mysql

Warning: Some directories in your path end in a slash.
Directories in your path should not end in a slash. This can break other
doctor checks. The following directories should be edited:
  /Users/michael/Library/Python/3.6/bin/
  /usr/local/go/bin/
  /Users/michael/golang/bin/
  /bin/

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc
Error: 784: unexpected token at '����F������ܚ��F ��#0j�E�h����U����O~b�4>�M,�i�8�̫���~��
                                                                                       ��iޟ��Ќ
                                                                                              XQ����P^�ģ����������ܷe1��hG�MT7��z0]�r�Sj7���K�O5�#-N�WS8�%&-n�WO�ntB��F<1r�:�'
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/json/common.rb:156:in `parse'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/json/common.rb:156:in `parse'
/usr/local/Homebrew/Library/Homebrew/tab.rb:63:in `from_file_content'
/usr/local/Homebrew/Library/Homebrew/tab.rb:58:in `block in from_file'
/usr/local/Homebrew/Library/Homebrew/tab.rb:58:in `fetch'
/usr/local/Homebrew/Library/Homebrew/tab.rb:58:in `from_file'
/usr/local/Homebrew/Library/Homebrew/tab.rb:103:in `for_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:303:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:294:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1386:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1384:in `each'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1384:in `flat_map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1384:in `installed'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:869:in `check_missing_deps'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:47:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:39:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:39:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

We will close this issue or ask you to create a pull-request if it's something the maintainers are not actively planning to work on.

**Comment by MikeMcQuaid** [comment]
`rm -rf /usr/local/Cellar/python*` and then reinstall anything as needed. This is corruption specific to your machine.
