### ISSUE TITLE
After attempting Brew update any command fails

### ISSUE THREAD

**Issue by TheMSB** [Homebrew/brew#392]
### Bug report:

After attempting to run brew update any and all commands, including brew doctor, now return the same error:

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- mach (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/Homebrew/extend/pathname.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/Homebrew/global.rb:3:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/brew.rb:16:in `<main>'
```

**Comment by MikeMcQuaid** [comment]
Try to `cd /usr/local; git fetch; git reset --hard origin/master; brew update`.

**Comment by TheMSB** [comment]
Unfortunately I can't try that anymore, I ended up working around the issue by completely removing brew and then reinstalling it. Less than ideal since I had to reinstall a bunch of other stuff because of it.
