### ISSUE TITLE
Scipy fails to install as formula resource

### ISSUE THREAD

**Issue by jlmcgehee21** [Homebrew/brew#4017]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/jeff/.asdf/shims/python2-config
  /Users/jeff/.asdf/shims/python3.6m-config
  /Users/jeff/.asdf/shims/python2.7-config
  /Users/jeff/.asdf/shims/python-config
  /Users/jeff/.asdf/shims/python3-config
  /Users/jeff/.asdf/shims/python3.6-config
```

```
$ brew config
HOMEBREW_VERSION: 1.5.14
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7fd6210127f088b6ee8708a1d7f4ec2df3fc5bb4
Last commit: 18 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0d5a5ae95bbaff3e6123db879c92a9478b276090
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GITHUB_API_TOKEN: set
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.14.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 9.0.4
macOS: 10.13.3-x86_64
CLT: 9.2.0.0.1.1510905681
Xcode: 9.2
XQuartz: N/A
```

## What I'm trying to do:
I'm the developer of a [small tool](https://github.com/jlmcgehee21/disterminal/tree/master) that some of my co-workers want to install with brew -- I'm sure it's not big enough to warrant a real brew formula, so I'm making a [tap](https://github.com/jlmcgehee21/disterminal/blob/master/Formula/disterminal.rb)

## What happened:
My formula fails on the scipy installation.  I have my app released on PyPI and `pip install disterminal` works fine.

`$ brew tap jlmcgehee21/disterminal https://github.com/jlmcgehee21/disterminal`
```
$ brew install disterminal
==> Auto-updated Homebrew!
Updated 1 tap (jlmcgehee21/disterminal).
No changes to formulae.

==> Installing disterminal from jlmcgehee21/disterminal
==> Downloading https://github.com/jlmcgehee21/disterminal/archive/v0.2.0.tar.gz
Already downloaded: /Users/jeff/Library/Caches/Homebrew/disterminal-0.2.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/b1/72/2d70c5a1de409ceb3a27ff2ec007ecdd5cc52239e7c74990e32af57affe9/virtualenv-15.2.0.tar.gz
Already downloaded: /Users/jeff/Library/Caches/Homebrew/disterminal--homebrew-virtualenv-15.2.0.tar.gz
==> python3 -c import setuptools... --no-user-cfg install --prefix=/tmp/disterminal--homebrew-virtualenv-20180402-46112-vnfd58/target --single-version-externally-managed --record=installed.txt
==> python3 -s /tmp/disterminal--homebrew-virtualenv-20180402-46112-vnfd58/target/bin/virtualenv -p python3 /usr/local/Cellar/disterminal/0.2.0/libexec
==> Downloading https://files.pythonhosted.org/packages/0b/66/86185402ee2d55865c675c06a5cfef742e39f4635a4ce1b1aefd20711c13/numpy-1.14.2.zip
Already downloaded: /Users/jeff/Library/Caches/Homebrew/disterminal--numpy-1.14.2.zip
==> /usr/local/Cellar/disterminal/0.2.0/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/disterminal--numpy-20180402-46112-1ln8rmt/numpy-1.14.2
==> Downloading https://files.pythonhosted.org/packages/d0/73/76fc6ea21818eed0de8dd38e1e9586725578864169a2b31acdeffb9131c8/scipy-1.0.0.tar.gz
Already downloaded: /Users/jeff/Library/Caches/Homebrew/disterminal--scipy-1.0.0.tar.gz
==> /usr/local/Cellar/disterminal/0.2.0/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/disterminal--scipy-20180402-46112-1vwyc57/scipy-1.0.0
Last 15 lines from /Users/jeff/Library/Logs/Homebrew/disterminal/04.pip:
  Removing source in /private/tmp/pip-ckr8cghy-build
Command "/usr/local/Cellar/disterminal/0.2.0/libexec/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-ckr8cghy-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-yo5euubj-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/disterminal/0.2.0/libexec/bin/../include/site/python3.6/scipy" failed with error code 1 in /private/tmp/pip-ckr8cghy-build/
Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/disterminal/0.2.0/libexec/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/Cellar/disterminal/0.2.0/libexec/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/Cellar/disterminal/0.2.0/libexec/lib/python3.6/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/Cellar/disterminal/0.2.0/libexec/lib/python3.6/site-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/usr/local/Cellar/disterminal/0.2.0/libexec/lib/python3.6/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "/usr/local/Cellar/disterminal/0.2.0/libexec/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-ckr8cghy-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-yo5euubj-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/disterminal/0.2.0/libexec/bin/../include/site/python3.6/scipy" failed with error code 1 in /private/tmp/pip-ckr8cghy-build/

If reporting this issue please do so to (not Homebrew/brew or Homebrew/core):
jlmcgehee21/disterminal

/usr/local/Homebrew/Library/Homebrew/utils/github.rb:220:in `raise_api_error': curl failed!  (GitHub::Error)
curl: (22) The requested URL returned error: 422 Unprocessable Entity
curl: (3) <url> malformed
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:178:in `open_api'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:278:in `search'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:225:in `search_issues'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:238:in `issues_for_formula'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:368:in `fetch_issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:364:in `issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:418:in `dump'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:138:in `rescue in <main>'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:30:in `<main>'
```

## What I expected:
A clean install of `disterminal`

## To Reproduce:
* `$ brew tap jlmcgehee21/disterminal https://github.com/jlmcgehee21/disterminal`
* `$ brew install disterminal`

The only reason I'm reporting this is because I feel like there is a specific installation method homebrew is using for scipy which is not working.  More than willing to have someone point out an error I have made though :)

**Comment by scpeters** [comment]
If you're not sure there is a bug in brew, then discourse is probably the better place for this. If you append `--verbose` and `--debug` to your install command and post that result on discourse, I'll take a look at it.

**Comment by MikeMcQuaid** [comment]
> If reporting this issue please do so to (not Homebrew/brew or Homebrew/core):
> jlmcgehee21/disterminal

**Comment by mjs2600** [comment]
@MikeMcQuaid he is `jlmcgehee21/disterminal`...

**Comment by MikeMcQuaid** [comment]
@mjs2600 Thanks for pointing that out. 

> If you're not sure there is a bug in brew, then discourse is probably the better place for this.

I agree @jlmcgehee21; that's a better place to ask for help with writing a formula.
