### ISSUE TITLE
Error: xcode version detection

### ISSUE THREAD

**Issue by jaimelopez** [Homebrew/brew#4084]
```
~ » brew doctor --debug                                                                                                               jlopez@bcn-lm-000978
Checking check_access_cache
Checking check_access_cellar
Checking check_access_homebrew_repository
Checking check_access_lock_dir
Checking check_access_logs
Checking check_access_prefix_directories
Checking check_access_site_packages
Checking check_brew_git_origin
Checking check_build_from_source
Checking check_clt_minimum_version
Error: stack level too deep
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:85:in `bundle_path'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:69:in `prefix'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:94:in `installed?'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:124:in `detect_version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:114:in `version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:283:in `detect_version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:273:in `version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:202:in `installed?'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:124:in `detect_version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:114:in `version'
...
```

**Comment by l4m4re** [comment]
Exact same problem here, running on El Capitan 10.11.6.

Darwin McAsterix.local 15.6.0 Darwin Kernel Version 15.6.0: Tue Jan 30 11:45:51 PST 2018; root:xnu-3248.73.8~1/RELEASE_X86_64 x86_64
