### ISSUE TITLE
Regexp error when using bump-formula-pr

### ISSUE THREAD

**Issue by fentie** [Homebrew/brew#4242]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

I was trying to submit a version bump PR for youtube-dl and received the following output:

```sh
brew bump-formula-pr --strict youtube-dl --tag=2018.05.30 --revision=e425710554f1ed96504389fb526b898a942012dd
Already up-to-date.
==> replace nil with "2018.05.30"
Error: wrong argument type nil (expected Regexp)
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/extend/string.rb:39:in `gsub!'
/usr/local/Homebrew/Library/Homebrew/extend/string.rb:39:in `gsub!'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb:355:in `block (2 levels) in inreplace_pairs'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb:351:in `each'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb:351:in `block in inreplace_pairs'
/usr/local/Homebrew/Library/Homebrew/utils/inreplace.rb:26:in `block in inreplace'
/usr/local/Homebrew/Library/Homebrew/utils/inreplace.rb:22:in `each'
/usr/local/Homebrew/Library/Homebrew/utils/inreplace.rb:22:in `inreplace'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb:350:in `inreplace_pairs'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb:233:in `bump_formula_pr'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

### brew config:
```sh
HOMEBREW_VERSION: 1.6.6-32-g0f65758
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0f65758f855712b02a1fc87f4903851810a622a2
Last commit: 8 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b1814bda721b02d0d196065cd79184afb47f9410
Core tap last commit: 53 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/bin/ruby
Clang: 9.1 build 902
Git: 2.17.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: N/A
macOS: 10.13.4-x86_64
CLT: 9.3.0.0.1.1521514116
Xcode: N/A
XQuartz: N/A
```

### brew doctor:
```sh
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  node
  gnupg
```

**Comment by scpeters** [comment]
I think this is happening because [youtube-dl has a url](https://github.com/Homebrew/homebrew-core/blob/master/Formula/youtube-dl.rb#L4) and not a `:tag` / `:revision` pair. The tool could probably use some logic to detect `nil` and at the very least print a better error message.

**Comment by fentie** [comment]
Thanks peoples 😄

**Comment by MikeMcQuaid** [comment]
@fentie You're welcome!
