### ISSUE TITLE
brew doctor: "no implicit conversion of nil into String" error

### ISSUE THREAD

**Issue by noyannus** [Homebrew/brew#4262]
> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?

`brew doctor` triggers the problem. 

- [ x ] ran `brew config` and `brew doctor` and included their output with your issue?

Please see below.

> To help us debug your issue please explain:
> - What you were trying to do (and why)

I ran `brew doctor` after `upgrade`, `prune`, and `cleanup`.
Reason: free disk space, check for errors.

> - What happened (include command output)

The error below was printed.  `brew doctor` alone suffices now to reproduce:
```
$ brew doctor
Error: no implicit conversion of nil into String
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/formulary.rb:363:in `extname'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:363:in `loader_for'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:280:in `factory'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:33:in `to_formula'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1564:in `map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1564:in `missing_dependencies'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:13:in `block in missing_deps'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:12:in `each'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:12:in `missing_deps'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:720:in `check_missing_deps'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:46:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:38:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:38:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

> - What you expected to happen

No error. 

> - Step-by-step reproduction instructions (by running `brew` commands)

`$ brew upgrade

$ brew prune && brew cleanup && brew doctor`

_Output of `brew config`:_
```
`$ brew config
HOMEBREW_VERSION: 1.6.6-63-ga674a97
ORIGIN: https://github.com/Homebrew/brew
HEAD: a674a972a56850a6f76eb1d9e812438bc435152b
Last commit: 34 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 44ca0d278857397e87273740bb3229772cd733e5
Core tap last commit: 73 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/bin/ruby
Clang: 9.0 build 900
Git: 2.17.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_151, 1.6.0_65-b14-468
macOS: 10.12.6-x86_64
CLT: 9.2.0.0.1.1510905681
Xcode: 9.2
XQuartz: 2.7.11 => /opt/X11`
```

**Comment by loadaverage** [comment]
Same problem with last brew update (38bc435152b)

**Comment by scpeters** [comment]
This looks like a duplicate of #4261
