### ISSUE TITLE
`brew tests` failing on master: '' cannot be parsed to a Locale

### ISSUE THREAD

**Issue by apjanke** [Homebrew/brew#4339]
- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

-------

On `master`, `brew tests` is raising an error for me.

```
Failures:

  1) OS::Mac::language can be parsed by Locale::parse
     Failure/Error: expect { Locale.parse(subject.language) }.not_to raise_error

       expected no Exception, got #<Locale::ParserError: '' cannot be parsed to a Locale> with backtrace:
         # ./locale.rb:15:in `parse'
         # ./test/os/mac_spec.rb:19:in `block (4 levels) in <top (required)>'
         # ./test/os/mac_spec.rb:19:in `block (3 levels) in <top (required)>'
         # ./test/spec_helper.rb:117:in `block (2 levels) in <top (required)>'
         # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:123:in `block in run'
         # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:110:in `loop'
         # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:110:in `run'
         # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.6.1/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
         # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:37:in `block (2 levels) in setup'
         # ./vendor/bundle/ruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block (2 levels) in <top (required)>'
     # ./test/os/mac_spec.rb:19:in `block (3 levels) in <top (required)>'
     # ./test/spec_helper.rb:117:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:123:in `block in run'
     # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:110:in `loop'
     # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:110:in `run'
     # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.6.1/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
     # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:37:in `block (2 levels) in setup'
     # ./vendor/bundle/ruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block (2 levels) in <top (required)>'

Finished in 1 minute 10.43 seconds (files took 2.03 seconds to load)
534 examples, 1 failure, 1 pending

Failed examples:

rspec ./test/os/mac_spec.rb:18 # OS::Mac::language can be parsed by Locale::parse
```

I don't think I have any special config that would cause this. This is a normal English installation of 10.13.5, as far as I know.

```
$ brew config                                                                                         ✘ 1 master
HOMEBREW_VERSION: 1.6.8-19-ge39b6f5
ORIGIN: https://github.com/Homebrew/brew
HEAD: e39b6f5891f2aa98fa2bef7775aecf73fc246afb
Last commit: 10 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4436ba86592b5e3298aef69ae583d1f0abf0d439
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEVELOPER: 1
HOMEBREW_LINKAGE_CACHE: 1
HOMEBREW_NO_AUTO_UPDATE: 1
HOMEBREW_SANDBOX: 1
HOMEBREW_VISUAL: subl -w
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.1 build 902
Git: 2.17.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_144
macOS: 10.13.5-x86_64
CLT: 9.4.0.0.1.1526532315
Xcode: 9.3.1 => /Applications/Xcode-9.3.1.app/Contents/Developer
XQuartz: 2.7.11 => /opt/X11
```

```
$ brew doctor
Your system is ready to brew.
``` 

Diagnosis
----------------

Note to self: this is on host `toast`.

```
$ brew irb
==> Interactive Homebrew Shell
Example commands available with: brew irb --examples
irb(main):001:0> OS::Mac::language
2018-06-13 14:58:47.052 defaults[47517:253056]
The domain/default pair of (kCFPreferencesAnyApplication, AppleLanguages) does not exist
=> nil
irb(main):002:0>
```

My System Preferences seems to show English as the default:

<img width="668" alt="screen shot 2018-06-13 at 3 00 14 pm" src="https://user-images.githubusercontent.com/2618447/41372202-9120bce6-6f1a-11e8-844c-61906e11d261.png">

And it appears in the shell when using `defaults read`:

```
$ defaults read -g AppleLanguages
(
    "en-US"
)
```

**Comment by apjanke** [comment]
Restarting my terminal emulator fixed this. No idea why. Closing unless I can reproduce again.
