### ISSUE TITLE
Error: Calling keg_only :shadowed_by_osx is disabled!

### ISSUE THREAD

**Issue by mingxian** [Homebrew/brew#4354]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [*] ran `brew update` and can still reproduce the problem? 
- [*] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [] ran `brew config` and `brew doctor` and included their output with your issue?

```
$ brew config

HOMEBREW_VERSION: 1.6.9-8-g25542d7
ORIGIN: https://github.com/Homebrew/brew
HEAD: 25542d7398512df4f0add9381fec1d375ab5b4d6
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/brew.git
Core tap HEAD: 25542d7398512df4f0add9381fec1d375ab5b4d6
Core tap last commit: 7 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_LINKAGE_CACHE: 1
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/bin/ruby
Clang: 9.1 build 902
Git: 2.17.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_162, 1.8.0_121
macOS: 10.13.5-x86_64
CLT: 9.4.1.0.1.1528165917
Xcode: 9.4.1
XQuartz: N/A
```

```
$ brew doctor

Error: Calling keg_only :shadowed_by_osx is disabled!
Use keg_only :shadowed_by_macos instead.
/usr/local/Homebrew/Library/Homebrew/formula.rb:1034:in `keg_only?'
Or, even better, submit a PR to fix it!

```

To help us debug your issue please explain:
- What you were trying to do (and why)
just wanna use `brew doctor` to fix all issuses
- What happened (include command output)
output: 
` Error: Calling keg_only :shadowed_by_osx is disabled!
Use keg_only :shadowed_by_macos instead.
/usr/local/Homebrew/Library/Homebrew/formula.rb:1034:in 'keg_only?'
Or, even better, submit a PR to fix it! `

- What you expected to happen
no Error

- Step-by-step reproduction instructions (by running `brew` commands)
brew doctor

**Comment by scpeters** [comment]
I'm guessing this is related to a specific formula. We may be able to pinpoint which formula it is from `brew doctor --verbose --debug`. Can you post the results of that?

**Comment by mingxian** [comment]
@scpeters sure.

```
Checking check_access_cache
Checking check_access_cellar
Checking check_access_homebrew_repository
Checking check_access_lock_dir
Checking check_access_logs
Checking check_access_prefix_directories
Checking check_access_site_packages
Checking check_brew_git_origin
Checking check_build_from_source
Checking check_clt_minimum_version
Checking check_clt_up_to_date
Checking check_coretap_git_origin
Checking check_filesystem_case_sensitive
Checking check_for_anaconda
Checking check_for_bad_curl
Checking check_for_bad_python_symlink
Checking check_for_beta_xquartz
Checking check_for_config_scripts
Checking check_for_external_cmd_name_conflict
Checking check_for_gettext
Checking check_for_git
Checking check_for_iconv
Checking check_for_installed_developer_tools
Checking check_for_multiple_volumes
Checking check_for_non_prefixed_coreutils
Checking check_for_non_prefixed_findutils
Checking check_for_other_frameworks
Checking check_for_other_package_managers
Checking check_for_pydistutils_cfg_in_home
Checking check_for_stray_dylibs
Checking check_for_stray_headers
Checking check_for_stray_las
Checking check_for_stray_pcs
Checking check_for_stray_static_libs
Checking check_for_symlinked_cellar
Checking check_for_tap_ruby_files_locations
Checking check_for_unlinked_but_not_keg_only
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/icu4c.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/opt/icu4c/.brew/icu4c.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/gettext.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/opt/gettext/.brew/gettext.rb
Error: Calling keg_only :shadowed_by_osx is disabled!
Use keg_only :shadowed_by_macos instead.
/usr/local/Homebrew/Library/Homebrew/formula.rb:1034:in `keg_only?'
Or, even better, submit a PR to fix it!
```
Oh, it seems that the error comes from gettext.rb.

**Comment by ilovezfs** [comment]
```
Core tap ORIGIN: https://github.com/Homebrew/brew.git
```

That is very odd. It could be a failed migration.

**Comment by ilovezfs** [comment]
What is the output of
```
brew formula wget
```

**Comment by mingxian** [comment]
@ilovezfs 
```
$ brew formula wget
/usr/local/opt/wget/.brew/wget.rb
```
seems ok

**Comment by ilovezfs** [comment]
@mingxian the output should be

```
Josephs-MacBook-Pro:~ joe$ brew formula wget
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/wget.rb
```

so definitely not OK.

How about the output of
```
brew tap
```
and
```
brew --repo homebrew/core
```
and
```
ls /usr/local/Homebrew/Library/Taps/homebrew/
```

**Comment by mingxian** [comment]
@ilovezfs 

```
$ brew tap

Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (ruffjs/ruff).
==> Updated Formulae
ruffjs/ruff/ruff ✔

homebrew/cask
homebrew/core
homebrew/services
ruffjs/ruff

$ brew --repo homebrew/core
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core

$ ls /usr/local/Homebrew/Library/Taps/homebrew/
homebrew-cask		homebrew-core		homebrew-services
```

**Comment by ilovezfs** [comment]
Thanks. And how about
```
ls /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core
```
and
```
git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core remote show origin
git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core status
git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core rev-parse HEAD
```

**Comment by mingxian** [comment]
@ilovezfs  not at all

```
$ ls /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core
CHANGELOG.md		Library			docs
CODE_OF_CONDUCT.md	README.md		manpages
CONTRIBUTING.md		bin
LICENSE.txt		completions

$ git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core remote show origin
* remote origin
  Fetch URL: https://github.com/Homebrew/brew.git
  Push  URL: https://github.com/Homebrew/brew.git
  HEAD branch: master
  Remote branch:
    master tracked
  Local branch configured for 'git pull':
    master merges with remote master
  Local ref configured for 'git push':
    master pushes to master (up to date)

$ git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

$ git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core rev-parse HEAD
25542d7398512df4f0add9381fec1d375ab5b4d6
```

**Comment by ilovezfs** [comment]
OK. You should be able to fix it with
```
rm -rf /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core
brew tap homebrew/core
```

Then what is output of
```
brew config
```
and
```
brew doctor
```
and
```
brew formula wget
```

**Comment by mingxian** [comment]
@ilovezfs  Yeah, it's ok. Thank you very much!

```
$ brew config
HOMEBREW_VERSION: 1.6.9-8-g25542d7
ORIGIN: https://github.com/Homebrew/brew
HEAD: 25542d7398512df4f0add9381fec1d375ab5b4d6
Last commit: 12 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 418ea4d64db5c2160cded69e1b799639c147b4e5
Core tap last commit: 41 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_LINKAGE_CACHE: 1
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/bin/ruby
Clang: 9.1 build 902
Git: 2.17.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_162, 1.8.0_121
macOS: 10.13.5-x86_64
CLT: 9.4.1.0.1.1528165917
Xcode: 9.4.1
XQuartz: N/A

$ brew doctor
Warning: Broken symlinks were found. Remove them with `brew prune`:
  /usr/local/etc/bash_completion.d/brew
  /usr/local/share/man/man1/README.md
  /usr/local/share/man/man1/brew-cask.1
  /usr/local/share/man/man1/brew.1
  /usr/local/share/zsh/site-functions/_brew
  /usr/local/share/zsh/site-functions/_brew_cask

$ brew formula wget
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/wget.rb

**Comment by MikeMcQuaid** [comment]
Glad you got it fixed.
