### ISSUE TITLE
NewFormulaAudit/DependencyOrder undefined method `metadata' for nil:NilClass

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/brew#4395]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Get https://github.com/Homebrew/homebrew-core/pull/29574 to pass CI because green is a  nice color.
- What happened (include command output)
```
==> brew audit crystal --online --new-formula
==> FAILED
Error: Error running `rubocop --format json --force-exclusion --parallel --config /usr/local/Homebrew/Library/.rubocop_audit.yml /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/crystal.rb`
An error occurred while NewFormulaAudit/DependencyOrder cop was inspecting /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/crystal.rb:1:0.
To see the complete backtrace run rubocop -d.
An error occurred while NewFormulaAudit/DependencyOrder cop was inspecting /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/crystal.rb:1:0.
To see the complete backtrace run rubocop -d.

1 error occurred:
An error occurred while NewFormulaAudit/DependencyOrder cop was inspecting /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/crystal.rb:1:0.
undefined method `metadata' for nil:NilClass
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/rubocop-0.55.0/lib/rubocop/cli.rb:265:in `display_error_summary'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/rubocop-0.55.0/lib/rubocop/cli.rb:158:in `execute_runner'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/rubocop-0.55.0/lib/rubocop/cli.rb:84:in `execute_runners'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/rubocop-0.55.0/lib/rubocop/cli.rb:41:in `run'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/rubocop-0.55.0/bin/rubocop:13:in `block in <top (required)>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/rubocop-0.55.0/bin/rubocop:12:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/bin/rubocop:22:in `load'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/bin/rubocop:22:in `<main>'
```
- What you expected to happen

Typical audit output.

- Step-by-step reproduction instructions (by running `brew` commands)

```
bash-3.2$ brew audit --new-formula crystal-lang
Error: Error running `rubocop --format json --force-exclusion --parallel --config /usr/local/Homebrew/Library/.rubocop_audit.yml /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/crystal-lang.rb`
An error occurred while NewFormulaAudit/DependencyOrder cop was inspecting /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/crystal-lang.rb:1:0.
To see the complete backtrace run rubocop -d.
An error occurred while NewFormulaAudit/DependencyOrder cop was inspecting /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/crystal-lang.rb:1:0.
To see the complete backtrace run rubocop -d.

1 error occurred:
An error occurred while NewFormulaAudit/DependencyOrder cop was inspecting /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/crystal-lang.rb:1:0.
undefined method `metadata' for nil:NilClass
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/rubocop-0.55.0/lib/rubocop/cli.rb:265:in `display_error_summary'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/rubocop-0.55.0/lib/rubocop/cli.rb:158:in `execute_runner'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/rubocop-0.55.0/lib/rubocop/cli.rb:84:in `execute_runners'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/rubocop-0.55.0/lib/rubocop/cli.rb:41:in `run'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/rubocop-0.55.0/bin/rubocop:13:in `block in <top (required)>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/rubocop-0.55.0/bin/rubocop:12:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/bin/rubocop:22:in `load'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/bin/rubocop:22:in `<main>'
bash-3.2$ 
```

The exception is not triggered if the line `depends_on "libyaml" if build.with? "shards"` is removed from the formula.

CC @MikeMcQuaid @GauthamGoli

**Comment by GauthamGoli** [comment]
Addressed in https://github.com/Homebrew/brew/pull/4396
