### ISSUE TITLE
Pip2 Broken Mac OSX 10.13.5

### ISSUE THREAD

**Issue by secfb** [Homebrew/brew#4432]
* pip version:10.0.1
* Python version:Python 2.7.15
* OS: Mac OSX 10.13.5

$ which pip
/usr/local/bin/pip

$brew info python@2
`python@2: stable 2.7.15 (bottled), HEAD
Interpreted, interactive, object-oriented programming language
https://www.python.org/
/usr/local/Cellar/python@2/2.7.15_1 (4,726 files, 83.8MB) *
  Poured from bottle on 2018-06-26 at 23:44:11
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/python@2.rb
==> Dependencies
Build: pkg-config ✔, sphinx-doc ✘
Required: gdbm ✔, openssl ✔, readline ✔, sqlite ✔
Optional: tcl-tk ✘
==> Options
--with-tcl-tk
	Use Homebrew's Tk instead of macOS Tk (has optional Cocoa and threads support)
--HEAD
	Install HEAD version
==> Caveats
Pip and setuptools have been installed. To update them
  pip install --upgrade pip setuptools

You can install Python packages with
  pip install <package>

They will install into the site-package directory
  /usr/local/lib/python2.7/site-packages

See: https://docs.brew.sh/Homebrew-and-Python`

<img width="780" alt="brewpython" src="https://user-images.githubusercontent.com/38748801/42378592-75b876ba-8130-11e8-83d0-15055fd3757b.png">

I can not do anything with Pip. I can not even learn version knowledge.It gives the following error.
Screenshot of fault screen 

<img width="996" alt="pip" src="https://user-images.githubusercontent.com/38748801/42378474-15319a38-8130-11e8-919c-29f48ff503b0.png">

`➜  ~  pip --version
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 11, in <module>
    load_entry_point('pip==10.0.1', 'console_scripts', 'pip')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/site-packages/pip/_internal/__init__.py", line 42, in <module>
    from pip._internal import cmdoptions
  File "/usr/local/lib/python2.7/site-packages/pip/_internal/cmdoptions.py", line 16, in <module>
    from pip._internal.index import (
  File "/usr/local/lib/python2.7/site-packages/pip/_internal/index.py", line 15, in <module>
    from pip._vendor import html5lib, requests, six
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/requests/__init__.py", line 86, in <module>
    from pip._vendor.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/local/lib/python2.7/site-packages/pyOpenSSL-18.0.0-py2.7.egg/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/local/lib/python2.7/site-packages/pyOpenSSL-18.0.0-py2.7.egg/OpenSSL/crypto.py", line 16, in <module>
    from OpenSSL._util import (
  File "/usr/local/lib/python2.7/site-packages/pyOpenSSL-18.0.0-py2.7.egg/OpenSSL/_util.py", line 18, in <module>
    no_zero_allocator = ffi.new_allocator(should_clear_after_alloc=False)
AttributeError: 'CompiledFFI' object has no attribute 'new_allocator'`

* pip3 command works fine 

$ pip3 -V
pip 10.0.1 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**
