### ISSUE TITLE
Error: undefined method `mktemp' for FileUtils:Module

### ISSUE THREAD

**Issue by navidR** [Homebrew/brew#4473]
Your last patch seems is not tested and merged to mainline and it breaks `mktemp` functions. Here is the report: 

```
┌─[21:11:23]─[navid@air]
└──> ~ $ >> brew update; brew upgrade
Already up-to-date.
==> Upgrading 11 outdated packages, with result:
coreutils 8.29 -> 8.30, libuv 1.21.0 -> 1.22.0, python 3.6.5_1 -> 3.7.0, llvm 6.0.0 -> 6.0.1, lua 5.3.4_4 -> 5.3.5, meson 0.46.1 -> 0.47.1, curl 7.60.0 -> 7.61.0, re2 20180401 -> 20180701, tor 0.3.3.7 -> 0.3.3.9, mercurial 4.6.1 -> 4.6.2, youtube-dl 2018.06.25 -> 2018.07.10
==> Upgrading llvm --with-lldb --with-graphviz
Error: undefined method `mktemp' for FileUtils:Module
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/llvm.rb:5:in `block in <class:CodesignRequirement>'
/usr/local/Homebrew/Library/Homebrew/requirement.rb:56:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/requirement.rb:56:in `block in satisfied?'
/usr/local/Homebrew/Library/Homebrew/requirement.rb:186:in `yielder'
/usr/local/Homebrew/Library/Homebrew/requirement.rb:56:in `satisfied?'
/usr/local/Homebrew/Library/Homebrew/requirement.rb:79:in `modify_build_environment'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/set.rb:306:in `each_key'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/set.rb:306:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/delegate.rb:341:in `block in delegating_block'
/usr/local/Homebrew/Library/Homebrew/build.rb:86:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:191:in `<main>'
┌─[✗]─[21:11:34]─[navid@air]
└──> ~ $ >> 
```

(removed Homebrew community commentary)

**Comment by MikeMcQuaid** [comment]
@navidR This will be fixed by https://github.com/Homebrew/homebrew-core/pull/30057. Please refrain from insulting our community, thanks.

**Comment by MikeMcQuaid** [comment]
@navidR And please always fill out the issue template in future so we know e.g. what version of Homebrew you are running.
