### ISSUE TITLE
Error: invalid byte sequence in UTF-8 when installing jars with unicode filenames

### ISSUE THREAD

**Issue by nevillelyh** [Homebrew/brew#4522]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Installing jar files with unicode filenames causes "invalid byte sequence in UTF-8" error.
Details in https://github.com/spotify/scio/issues/1253

`.split("\n")` in [unpack_strategy.rb](https://github.com/Homebrew/brew/commit/d3534c1cc2af6f2e5b2aa1511433ee9c6473957d#diff-6ed6c0c2f49b4e25fa206752ad20318bR96) fails if the jar contains files with unicode names. After inspecting my failure case the filenames are UTF-16 encoded while ruby runtime expects UTF-8 (system default).

- What happened (include command output)
```
==> Installing scio from spotify/public
==> Downloading https://github.com/spotify/scio/releases/download/v0.5.6/scio-repl-0.5.6.jar
Already downloaded: /Users/neville/Library/Caches/Homebrew/scio-0.5.6.jar
Error: invalid byte sequence in UTF-8
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:139:in `split'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:139:in `can_extract?'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:40:in `block in detect'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:39:in `each'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:39:in `detect'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:39:in `detect'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:50:in `stage'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:171:in `stage'
/usr/local/Homebrew/Library/Homebrew/resource.rb:116:in `block in unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:189:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:55:in `block in run'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:55:in `chdir'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:55:in `run'
/usr/local/Homebrew/Library/Homebrew/resource.rb:188:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/resource.rb:115:in `unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:93:in `stage'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/forwardable.rb:202:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2014:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1112:in `brew'
/usr/local/Homebrew/Library/Homebrew/build.rb:113:in `block in install'
/usr/local/Homebrew/Library/Homebrew/utils.rb:557:in `with_env'
/usr/local/Homebrew/Library/Homebrew/build.rb:110:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:191:in `<main>'
```

- What you expected to happen
The package should install correctly.

- Step-by-step reproduction instructions (by running `brew` commands)
```bash
brew tap spotify/public
brew install scio
```

My system info:
```
$ brew doctor
Your system is ready to brew.

$ brew config
HOMEBREW_VERSION: 1.7.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7e8fb9a0f8ab5e841763ec6c7fefa72a8462b594
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 195949c1ec970a6295716869715f571cdc5fe0c8
Core tap last commit: 74 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.1 build 902
Git: 2.18.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_171
macOS: 10.13.6-x86_64
CLT: 9.4.1.0.1.1528165917
Xcode: 9.4.1
XQuartz: N/A
```

**Comment by nevillelyh** [comment]
I can workaround the issue by forcing encoding before `.split("\n")` but not sure that's the proper way to fix this. Happy to submit a PR.

```diff
diff --git a/Library/Homebrew/unpack_strategy.rb b/Library/Homebrew/unpack_strategy.rb
index 96c0f14ce..b14d663cf 100644
--- a/Library/Homebrew/unpack_strategy.rb
+++ b/Library/Homebrew/unpack_strategy.rb
@@ -115,7 +115,7 @@ class JarUnpackStrategy < UncompressedUnpackStrategy

     # Check further if the ZIP is a JAR/WAR.
     out, _, status = Open3.capture3("zipinfo", "-1", path)
-    status.success? && out.split("\n").include?("META-INF/MANIFEST.MF")
+    status.success? && out.force_encoding("ISO-8859-1").split("\n").include?("META-INF/MANIFEST.MF")
   end
 end
```

**Comment by nevillelyh** [comment]
Verified that latest brew works for me now. Closing this. Thanks!
