### ISSUE TITLE
Error: undefined method `downcase' for nil:NilClass in `brew desc -s`

### ISSUE THREAD

**Issue by crowell** [Homebrew/brew#4533]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

```
busytown ~ » brew config                                                                      1 ↵
HOMEBREW_VERSION: 1.7.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7e8fb9a0f8ab5e841763ec6c7fefa72a8462b594
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 47d170afb91a448297dc44331736b3827d0cd8c1
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 9.1 build 902
Git: 2.15.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.6.0_65-b14-468
macOS: 10.13.6-x86_64
CLT: 9.4.1.0.1.1528165917
Xcode: 9.4.1
XQuartz: 2.7.11 => /opt/X11
```

```
busytown ~ »  brew doctor
Your system is ready to brew.
```

To help us debug your issue please explain:
- What you were trying to do (and why)

run `brew desc -s` to search for several packages (cutter, z3)

- What happened (include command output)

```
busytown ~ » brew desc -s z3                                                                  1 ↵
Error: undefined method `downcase' for nil:NilClass
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/searchable.rb:14:in `simplify_string'
/usr/local/Homebrew/Library/Homebrew/searchable.rb:28:in `block (2 levels) in search_string'
/usr/local/Homebrew/Library/Homebrew/searchable.rb:28:in `any?'
/usr/local/Homebrew/Library/Homebrew/searchable.rb:28:in `block in search_string'
/usr/local/Homebrew/Library/Homebrew/searchable.rb:26:in `select'
/usr/local/Homebrew/Library/Homebrew/searchable.rb:26:in `search_string'
/usr/local/Homebrew/Library/Homebrew/searchable.rb:7:in `search'
/usr/local/Homebrew/Library/Homebrew/descriptions.rb:112:in `search'
/usr/local/Homebrew/Library/Homebrew/cmd/desc.rb:36:in `desc'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

- What you expected to happen

the output of the search with all items matching the description or title of my query

- Step-by-step reproduction instructions (by running `brew` commands)

`brew desc -s z3`

**Comment by crowell** [comment]
updated description after fixing `brew prune` issue still exists
