### ISSUE TITLE
brew search throws undefined method error - macOS 10.13.6

### ISSUE THREAD

**Issue by thenoelforte** [Homebrew/brew#4562]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue? _(Included below)_

---

To help us debug your issue please explain:

**What you were trying to do (and why)**
I was attempting to run `brew search <package name>`. I am able to reproduce this issue regardless of the package specified.

**What happened (include command output)**
After running `brew search`, I received the following error message:
```
Error: undefined method `token' for nil:NilClass
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/searchable.rb:28:in `block in search_string'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask.rb:20:in `block in each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask.rb:19:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask.rb:19:in `each'
/usr/local/Homebrew/Library/Homebrew/searchable.rb:27:in `select'
/usr/local/Homebrew/Library/Homebrew/searchable.rb:27:in `search_string'
/usr/local/Homebrew/Library/Homebrew/searchable.rb:7:in `search'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/search.rb:29:in `search_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/search.rb:83:in `search'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
```

**What you expected to happen**
Expected to receive a list of packages, from all taps, matching search string

**Step-by-step reproduction instructions (by running `brew` commands)**
```
$ brew search <package name>
```
---

**Additional information**

Output of `brew doctor`:
```
$ brew doctor
Your system is ready to brew.
```

Output of `brew config`:
```
HOMEBREW_VERSION: 1.7.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: d6a245c05110c240e680da594c2cc6038998b82e
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6517c2ef3174c76f1216e64d23923acf768e712c
Core tap last commit: 14 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_VISUAL: nano
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: N/A
macOS: 10.13.6-x86_64
CLT: 10.0.0.0.1.1527767617
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11
```

**Comment by reitermarkus** [comment]
Can you post the output of `brew tap`?

**Comment by KenjiTakahashi** [comment]
Same here.
```
 ~/ brew doctor
Your system is ready to brew.
```
```
 ~/ brew config
HOMEBREW_VERSION: 1.7.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: d6a245c05110c240e680da594c2cc6038998b82e
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0e25f23d130a5e700786025f387a7507b80880e5
Core tap last commit: 7 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 9.0 build 900
Git: 2.14.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_181
macOS: 10.12.6-x86_64
CLT: 9.2.0.0.1.1510905681
Xcode: 9.2
XQuartz: N/A
```
```
 ~/ brew tap
homebrew/cask
homebrew/cask-versions
homebrew/core
homebrew/fuse
kylef/formulae
mengbo/ch340g-ch34g-ch34x-mac-os-x-driver
pvinis/pvinis
universal-ctags/universal-ctags
```

**Comment by reitermarkus** [comment]
@thenoelforte, the problem is `spacemacs-nightly` from `pvinis/pvinis`, which is empty.

```ruby
cat /usr/local/Homebrew/Library/Taps/pvinis/homebrew-pvinis/Casks/spacemacs-nightly.rb
#cask 'spacemacs-nightly' do
  #version '2016-10-06_01-43-38-6e6c08815347a78008211613c9ddfa0acd7f0ef8'
  #sha256 '53a53cf2c62dcaada4ab6ec0e114ab9ca930688bbba455a90c6d3b316a7b0830'

 # url "https://emacsformacosx.com/emacs-builds/Emacs-#{version}-universal.dmg"
 # appcast 'https://emacsformacosx.com/atom/daily',
  #        checkpoint: 'e99da4f3923fdfcd3a28efae9fae7e624d070cc210bb45099ff570caef2eab00'
  #name 'Spacemacs'
  #homepage 'https://emacsformacosx.com/'
  #license :gpl

 # preflight do
    #system "mv", "#{staged_path}/Emacs.app", "#{staged_path}/Spacemacs.app"
    #system "rm", "#{staged_path}/Spacemacs.app/Contents/Resources/Emacs.icns"
   # system "curl -L \"https://github.com/nashamri/spacemacs-logo/blob/master/spacemacs.icns?raw=true\" -o #{staged_path}/Spacemacs.app/Contents/Resources/Emacs.icns"
  #end

 # app 'Spacemacs.app'
#end
```
