### ISSUE TITLE
`env` on Yosemite does not support "-u"

### ISSUE THREAD

**Issue by asharpe** [Homebrew/brew#4566]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew` commands)

I assume I should just add stuff here...

Was trying to upgrade a cask (to replicate an issue on that version) and brew failed on the download step.

```
$ brew cask upgrade vagrant --debug
==> Upgrading 1 outdated package, with result:
vagrant 2.1.2
==> Started upgrade process for Cask vagrant
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://releases.hashicorp.com/vagrant/2.1.2/vagrant_2.1.2_x86_64.dmg
==> env -u SSL_CERT_FILE /usr/bin/curl -q --show-error --user-agent Homebrew/1.7.1-41-g3c3b05d-dirty\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.10.5\)\ curl/7.43.0 --fail --progress-bar --location --remote-time --continue-at - --output /Users/asharpe/Library/Caches/Homebrew/Cask/vagrant--2.1.2.dmg.incomplete https://releases.hashicorp.com/vagrant/2.1.2/vagrant_2.1.2_x86_64.dmg
env: illegal option -- u
usage: env [-i] [name=value ...] [utility [argument ...]]
==> Purging files for version 2.1.2 of Cask vagrant
Error: Download failed on Cask 'vagrant' with message: Download failed: https://releases.hashicorp.com/vagrant/2.1.2/vagrant_2.1.2_x86_64.dmg
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/download.rb:42:in `rescue in fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/download.rb:39:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/download.rb:15:in `perform'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:135:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:56:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/upgrade.rb:60:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/upgrade.rb:33:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/upgrade.rb:33:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:33:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:93:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:159:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:124:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:164:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:164:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:147:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:124:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
```

I expected brew to be able to download the file.  Reproduce by running a command that requires brew to download on OSX Yosemite.

**Comment by asharpe** [comment]
```
$ brew config
HOMEBREW_VERSION: 1.7.1-41-g3c3b05d-dirty
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 3c3b05d45732915f7f1d2bd12fc01e7b4318bb31
Last commit: 17 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4d466900f0cffb5eb24aa810e977913aa6703d39
Core tap last commit: 27 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 7.0 build 700
Git: 2.13.0 => /usr/local/bin/git
Curl: 7.43.0 => /usr/bin/curl
Java: 1.8.0_74
macOS: 10.10.5-x86_64
CLT: 7.2.0.0.1.1447826929
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11
```

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/asharpe/.pyenv/shims/python-config
  /usr/local/munki/munkiwebadmin-config

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  python@2

Warning: You are using macOS 10.10.
We (and Apple) do not provide support for this old version.
You will encounter build failures and other breakages.
Please create pull-requests instead of asking for help on Homebrew's
GitHub, Discourse, Twitter or IRC. As you are running this old version,
you are responsible for resolving any issues you experience.

Warning: You have uncommitted modifications to Homebrew
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /usr/local/Homebrew/Library && git stash && git clean -d -f

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile
Warning: Use php@7.0 instead of deprecated homebrew/php/php70

Warning: Some installed formulae are missing dependencies.
You should `brew install` the missing dependencies:
  brew install php@7.0

Run `brew missing` for more details.
```

**Comment by asharpe** [comment]
Appears to have been introduced with !4561

**Comment by commitay** [comment]
https://github.com/Homebrew/brew/pull/4567
