### ISSUE TITLE
brew cleanup failing: #<DATAPatch: :p1>

### ISSUE THREAD

**Issue by mischwartz23** [Homebrew/brew#4666]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [N/A] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X ] ran `brew update` and can still reproduce the problem?
- [ X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Running brew cleanup. I run it about once per week to keep clutter down.
- What happened (include command output)
[Complete output]
Error: undefined method `resource' for #<DATAPatch: :p1>
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:87:in `map'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:87:in `stale_formula?'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:53:in `stale?'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:228:in `block in cleanup_cache'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:215:in `each'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:215:in `cleanup_cache'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:185:in `cleanup_formula'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:153:in `block in clean!'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:152:in `each'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:152:in `clean!'
/usr/local/Homebrew/Library/Homebrew/cmd/cleanup.rb:29:in `cleanup'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
- What you expected to happen
Old formula deleted, no other output.

- Step-by-step reproduction instructions (by running `brew` commands)
brew cleanup

I apologize that this does not fit your usual template, and that I cannot tell what component is causing the problem. After cleaning up brew doctor reports, this is the only output of brew cleanup.
If you point me in the right direction, I will properly investigate and report the correct cause.

Other notes on the problem:
  The first time brew cleanup ran this week, many lock files were removed, even for formulae that haven't been updated in a long time. There are now no lock files
  The most recent formulae updated via brew update, all successful, were checkstyle, erlang, erlang@19, erlang@20, glib-networking, p11-kit, and unixodbc.

Thank you. Please correct me on my reporting, so I can do better if I ever need to do so again.

[output of brew config]
HOMEBREW_VERSION: 1.7.1-220-g46f531b
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 46f531b2b1295e4e9269f9e67cef630e5c357ad8
Last commit: 21 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3c3328734e519b46dffe491e18d28e87557c2281
Core tap last commit: 68 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 9.1 build 902
Git: 2.18.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 10.0.1, 9.0.4, 1.8.0_172, 1.8.0, 1.7.0_13, 1.6.0_65-b14-468
macOS: 10.13.6-x86_64
CLT: 10.0.0.0.1.1527767617
CLT headers: N/A
Xcode: 9.4.1
XQuartz: 2.7.11 => /opt/X11

**Comment by MikeMcQuaid** [comment]
Do you get this error if you run `brew cleanup` again? What's your `brew doctor` output? Thanks!

**Comment by reitermarkus** [comment]
> Do you get this error if you run `brew cleanup` again?

If you do, can you post the output of `ls -al $(brew -- cache)`?

**Comment by hellerve** [comment]
I just reposted this issue (sorry about that), but I experience the same thing. I do get this error again, and the output of `ls -al $(brew -- cache)` is:

```
Error: Unknown command: --
[ Proceeds to do ls -al for  the current directory ]
```

**Comment by hellerve** [comment]
@reitermarkus did you possible misspell the command?

**Comment by reitermarkus** [comment]
> @reitermarkus did you possible misspell the command?

I did, was on my phone. Fixed now.

**Comment by mischwartz23** [comment]
yes he did.

No space after the --

**Comment by hellerve** [comment]
Oh well, could’ve figured that out myself I guess...

Anyway, here’s the output:

```
total 3870248
drwxrwxr-x  154 veitheller  staff       4928 Aug 12 19:18 .
drwx------+ 104 veitheller  staff       3328 Aug 12 12:10 ..
-rw-r--r--    1 veitheller  staff     275444 Sep 16  2017 adns--1.5.1.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff      48597 Jun 30 21:23 asciinema--2.0.1.tar.gz
-rw-r--r--    1 veitheller  staff     147794 Nov 26  2017 aspcud--1.9.4_1.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff     430748 Apr  4 05:38 atk--2.28.1_2.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff     983819 Mar 21 10:36 atkmm--2.24.2_1.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff     892119 Sep 14  2017 autoconf--2.69.high_sierra.bottle.4.tar.gz
-rw-r--r--    1 veitheller  staff     965610 Mar 12 00:32 automake--1.16.1.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff    1970558 May 17 01:37 awscli--homebrew--virtualenv--16.0.0.tar.gz
-rw-r--r--    1 veitheller  staff     498892 Apr 20 22:37 bdw--gc--7.6.6.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff   35998271 Jun 15 10:26 berkeley--db--18.1.25.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff   40844512 Jul 18 11:14 binutils--2.31.1.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff   91375309 Apr 18 17:30 boost--1.67.0_1.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff     758936 Apr 17 00:21 boost--build--1.67.0.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff    6439528 Mar 29 01:35 cabal--install--2.2.0.0.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff      60164 Jul 30 07:00 cabextract--1.7.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff    1687239 Dec 15  2017 cairo--1.14.12.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff     854566 Sep 16  2017 cairomm--1.12.2.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff    2155162 Jul  9 23:34 clingo--5.3.0.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff     317574 Feb 10  2018 cloc--1.76.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff      29341 Sep 18  2017 cowsay--3.04.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff   33822490 Oct  4  2017 elm--0.18.0.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff   20645343 Jul 18 17:18 ffmpeg--4.0.2.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff     547741 Jun 11 09:53 flac--1.3.2_1.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff    1225354 May  3 12:33 fontconfig--2.13.0.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff    1474037 Sep 18  2017 fortune--9708.high_sierra.bottle.2.tar.gz
-rw-r--r--    1 veitheller  staff     897837 May  2 13:45 freetype--2.9.1.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff     126732 Jul 24 09:02 fribidi--1.0.5.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff  102793918 Jul 26 20:45 gcc--8.2.0.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff        596 Dec 19  2017 gcc--patch--863957f90a934ee8f89707980473769cff47ca0663c3906992da6afb242fb220.patch
-rw-r--r--    1 veitheller  staff        689 Dec 19  2017 gcc--patch--f7772a6ba73f44a6b378e4fe3548e0284f48ae2d02c701df1be93780c1607074.patch
-rw-r--r--    1 veitheller  staff     297146 Sep 15  2017 gd--2.2.5.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff    3461644 Aug  1 07:58 gdb--8.1.1.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff     195269 Jul 31 14:52 gdbm--1.17.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff    1084229 Apr  8 10:25 gdk--pixbuf--2.36.12.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff    8202376 Sep 15  2017 gettext--0.19.8.1.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff  243449724 May 30 03:01 ghc--8.4.3.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff  137702128 Apr 17 23:44 ghc--binary--8.4.2.tar.xz
-rw-r--r--    1 veitheller  staff    1946336 Dec 18  2016 ghc--gmp--6.1.2.tar.xz
-rw-r--r--    1 veitheller  staff   13894061 Jun 21 20:39 git--2.18.0.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff      77228 Sep 16  2017 glfw--3.2.1.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff    7361421 Apr  9 14:23 glib--2.56.1.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff     136067 May 22 10:11 glib--networking--2.56.1.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff     152949 Aug 12 02:13 glib-networking--2.56.1_1.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff   10047160 Jun  8 13:06 glibmm--2.56.0_1.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff    1029123 Mar 19 19:02 gmp--6.1.2_2.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff      32380 Sep 15  2017 gnu--getopt--1.1.6.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff    4261001 Jul 12 21:38 gnupg--2.2.9.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff    2381332 Jul 16 14:49 gnutls--3.5.19.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff  107588198 Jun  8 01:20 go--1.10.3.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff     109372 May 26 11:49 graphite2--1.3.11.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff    7272085 Sep 15  2017 graphviz--2.40.1.high_sierra.bottle.1.tar.gz
-rw-r--r--    1 veitheller  staff    1263102 Mar 12 16:49 gsettings-desktop--schemas--3.28.0.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff    2795364 Jun 14 23:11 gsl--2.5.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff   12159628 Mar 20 22:50 gtk+--2.24.32_2.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff   21362044 Mar 21 14:24 gtkmm--2.24.5_1.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff    1618451 Aug  9 18:07 harfbuzz--1.8.7.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff    8936389 Apr 28 09:20 haskell--stack--1.7.1.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff      15585 Sep 15  2017 hicolor-icon--theme--0.17.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff   15665042 Aug  1 13:01 hugo--0.46.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff   26690933 Jun 22 04:15 icu4c--62.1.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff    8922453 Jul 24 01:07 imagemagick--7.0.8-8.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff    8925740 Aug  8 10:45 imagemagick--7.0.8-9.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff      54481 Sep 15  2017 intltool--0.51.0.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff    1439120 Jul 29 02:58 isl--0.20.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff     251631 Jun 15 10:26 jack--0.125.0_3.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff     777775 Jan 28  2018 lame--3.100.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff     149919 Dec  9  2017 libassuan--2.5.1.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff     771138 Sep 15  2017 libevent--2.1.8.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff      99543 Sep 15  2017 libffi--3.2.1.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff    1077076 Jun 13 13:16 libgcrypt--1.8.3.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff     268264 Jul 12 11:53 libgpg--error--1.32.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff     134928 Sep 16  2017 libksba--1.3.5.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff     176255 Sep 24  2017 libmodplug--0.8.9.0.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff     116961 Jan 12  2018 libmpc--1.1.0.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff     208056 Nov  9  2017 libogg--1.3.3.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff     456010 Jul 25 14:20 libpng--1.6.35.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff    2727700 Sep 15  2017 libsamplerate--0.1.9.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff    4399483 Sep 16  2017 libsigc++--2.10.0.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff     610825 Sep 15  2017 libsndfile--1.0.28.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff    1105080 Aug 10 14:54 libsoup--2.62.3.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff     134277 Jan 16  2018 libtasn1--4.13.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff    1094660 Jul  2 09:33 libtiff--4.0.9_4.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff    1033724 Sep 15  2017 libtool--2.4.6_1.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff    1461723 May 25 19:21 libunistring--0.9.10.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff     163009 Mar 30 08:22 libusb--1.0.22.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff     578385 Mar 16 23:45 libvorbis--1.3.6.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff    3177570 Jun  6 02:10 libxmlsec1--1.2.26.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff     104171 Jun 27 08:20 libyaml--0.2.1.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff     925696 Aug 12 19:18 linkage.db
-rw-r--r--    1 veitheller  staff     269015 Sep 16  2017 little--cms--1.19_1.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff     387268 Nov 26  2017 little--cms2--2.9.high_sierra.bottle.1.tar.gz
-rw-r--r--    1 veitheller  staff  429778967 Jul  5 21:03 llvm--6.0.1.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff     232131 Jul 11 10:07 lua--5.3.5.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff      34188 Jul 24 08:03 mdp--1.0.13.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff    1166570 Feb  8  2018 mpfr--4.0.1.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff     738901 Nov 19  2017 nettle--3.4.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff   13650656 Aug  2 00:02 node--10.8.0.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff      24441 Jul 17 02:23 npth--1.6.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff     303299 Sep 18  2017 oath--toolkit--2.6.2.high_sierra.bottle.1.tar.gz
-rw-r--r--    1 veitheller  staff    5234274 Nov  4  2017 opam--1.2.2_4.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff    2003442 Oct  5  2017 openjpeg--2.3.0.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff     712986 May 31 00:14 p11--kit--0.23.12.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff     706078 Aug 12 02:13 p11-kit--0.23.13.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff    2056614 Feb  9  2018 p7zip--16.02_1.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff   12657589 Aug  7 22:27 pandoc--2.2.3.2.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff     872006 Jul 31 09:12 pango--1.42.3.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff     877809 Mar 21 19:27 pangomm--2.40.1_1.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff      46650 Jun 14 17:46 pass--1.7.2.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff    1835792 Mar 21 07:13 pcre--8.42.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff   17007611 Jun 26 18:18 perl--5.28.0.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff     105237 Feb 20 11:02 pinentry--1.1.0_1.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff     257980 Sep 18  2017 pinentry--mac--0.9.4.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff     509876 Sep 15  2017 pixman--0.34.0_1.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff     241451 Sep 14  2017 pkg--config--0.29.2.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff    7571579 Jul 20 11:14 poppler--0.67.0.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff      63371 Sep 15  2017 popt--1.16.high_sierra.bottle.1.tar.gz
-rw-r--r--    1 veitheller  staff   12991649 Jul 12 22:53 portable--ruby--2.3.7.leopard_64.bottle.tar.gz
-rw-r--r--    1 veitheller  staff     119889 Sep 16  2017 potrace--1.15.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff   16922100 Jun 27 08:06 python--3.7.0.tar.xz
-rw-r--r--    1 veitheller  staff    1246072 Apr 19 20:56 python--pip--10.0.1.tar.gz
-rw-r--r--    1 veitheller  staff    1197370 Dec 19  2017 python--pip--9.0.1.tar.gz
-rw-r--r--    1 veitheller  staff     721505 Dec 19  2017 python--setuptools--36.5.0.zip
-rw-r--r--    1 veitheller  staff     851112 May 19 21:19 python--setuptools--39.2.0.zip
-rw-r--r--    1 veitheller  staff      43087 Dec 19  2017 python--wheel--0.30.0.tar.gz
-rw-r--r--    1 veitheller  staff      38574 May 13 19:28 python--wheel--0.31.1.tar.gz
-rw-r--r--    1 veitheller  staff    1197370 Dec 19  2017 python3--pip--9.0.1.tar.gz
-rw-r--r--    1 veitheller  staff     721505 Dec 19  2017 python3--setuptools--36.5.0.zip
-rw-r--r--    1 veitheller  staff      43087 Dec 19  2017 python3--wheel--0.30.0.tar.gz
-rw-r--r--    1 veitheller  staff      66560 Jun  6 11:41 qrencode--4.0.2.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff     505902 Jul  5 18:21 readline--7.0.5.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff      12660 Aug  5 07:20 reattach-to-user--namespace--2.7.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff    8401796 Mar 29 02:54 ruby--2.5.1.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff   18567402 Jul 26 17:36 sbcl--1.4.10.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff    1197031 Mar  2 15:29 sdl2--2.0.8.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff     130311 Mar  2 17:03 sdl2_image--2.0.3.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff     129927 Nov 27  2017 sdl2_mixer--2.0.2_3.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff      22432 Sep 15  2017 sdl2_ttf--2.0.14.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff   12212982 Jul 17 06:03 sphinx--doc--1.7.6.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff    1761795 Jun  5 03:17 sqlite--3.24.0.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff      96490 Dec 20  2017 telnet--54.50.1.high_sierra.bottle.1.tar.gz
-rw-r--r--    1 veitheller  staff     712336 Nov 25  2017 tidy--html5--5.6.0.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff      49412 Sep 16  2017 tree--1.7.0.high_sierra.bottle.1.tar.gz
-rw-r--r--    1 veitheller  staff     246773 Jun 26 13:01 unrar--5.6.5.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff    2987543 Jul 17 08:18 vala--0.40.8.high_sierra.bottle.tar.gz
drwxr-xr-x   80 veitheller  staff       2560 May 23 14:23 valgrind--git
-rw-r--r--    1 veitheller  staff   13777612 Aug  9 21:56 vim--8.1.0250.tar.gz
-rw-r--r--    1 veitheller  staff     855208 Apr 21 09:04 webp--1.0.0.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff  263130829 Jul  7 11:14 wine--3.0.2.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff     651678 Aug  8 17:42 winetricks--20180603.tar.gz
-rw-r--r--    1 veitheller  staff     451277 Jan 15  2018 xvid--1.3.5.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff     381666 May  1 13:07 xz--5.2.4.high_sierra.bottle.tar.gz
-rw-r--r--    1 veitheller  staff    3522629 Apr 17 10:18 zsh--5.5.1.high_sierra.bottle.tar.gz
```

**Comment by reitermarkus** [comment]
Should be working now after a `brew update`.

**Comment by hellerve** [comment]
Can confirm, works like a charm! :+1:  Thank you for the quick fix!
