### ISSUE TITLE
brew cleanup results in undefined method error

### ISSUE THREAD

**Issue by hellerve** [Homebrew/brew#4668]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

## What you were trying to do (and why)

I was trying to clean up old formulae to save space on my machine. I run `brew clenup` periodically to do this.

## What happened (include command output)

Running `brew cleanup` resulted in an exception being thrown, thusly:

```
Removing: /usr/local/var/homebrew/locks/libpng.formula.lock... (0B)
Removing: /usr/local/var/homebrew/locks/libunistring.formula.lock... (0B)
Removing: /usr/local/var/homebrew/locks/sphinx-doc.formula.lock... (0B)
Removing: /usr/local/var/homebrew/locks/pcre.formula.lock... (0B)
Removing: /usr/local/var/homebrew/locks/python.formula.lock... (0B)
Removing: /usr/local/var/homebrew/locks/update... (0B)
Removing: /usr/local/var/homebrew/locks/gobject-introspection.formula.lock... (0B)
Removing: /usr/local/var/homebrew/locks/libtasn1.formula.lock... (0B)
Removing: /usr/local/var/homebrew/locks/python@2.formula.lock... (0B)
Removing: /usr/local/var/homebrew/locks/meson.formula.lock... (0B)
Removing: /usr/local/var/homebrew/locks/sqlite.formula.lock... (0B)
Removing: /usr/local/var/homebrew/locks/readline.formula.lock... (0B)
Removing: /usr/local/var/homebrew/locks/fontconfig.formula.lock... (0B)
Removing: /usr/local/var/homebrew/locks/gnutls.formula.lock... (0B)
Removing: /usr/local/var/homebrew/locks/gettext.formula.lock... (0B)
Removing: /usr/local/var/homebrew/locks/nettle.formula.lock... (0B)
Removing: /usr/local/var/homebrew/locks/autoconf.formula.lock... (0B)
Removing: /usr/local/var/homebrew/locks/pkg-config.formula.lock... (0B)
Removing: /usr/local/var/homebrew/locks/cairo.formula.lock... (0B)
Removing: /usr/local/var/homebrew/locks/libffi.formula.lock... (0B)
Removing: /usr/local/var/homebrew/locks/glib.formula.lock... (0B)
Removing: /usr/local/var/homebrew/locks/gdbm.formula.lock... (0B)
Removing: /usr/local/var/homebrew/locks/intltool.formula.lock... (0B)
Removing: /usr/local/var/homebrew/locks/pixman.formula.lock... (0B)
Removing: /usr/local/var/homebrew/locks/python3.formula.lock... (0B)
Removing: /usr/local/var/homebrew/locks/libtool.formula.lock... (0B)
Removing: /usr/local/var/homebrew/locks/xz.formula.lock... (0B)
Removing: /usr/local/var/homebrew/locks/p11-kit.formula.lock... (0B)
Removing: /usr/local/var/homebrew/locks/makedepend.formula.lock... (0B)
Removing: /usr/local/var/homebrew/locks/gsettings-desktop-schemas.formula.lock... (0B)
Removing: /usr/local/var/homebrew/locks/glib-networking.formula.lock... (0B)
Removing: /usr/local/var/homebrew/locks/ninja.formula.lock... (0B)
Removing: /usr/local/var/homebrew/locks/gmp.formula.lock... (0B)
Removing: /usr/local/var/homebrew/locks/openssl.formula.lock... (0B)
Removing: /usr/local/var/homebrew/locks/automake.formula.lock... (0B)
Removing: /usr/local/var/homebrew/locks/freetype.formula.lock... (0B)
Error: undefined method `resource' for #<DATAPatch: :p1>
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:87:in `map'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:87:in `stale_formula?'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:53:in `stale?'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:228:in `block in cleanup_cache'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:215:in `each'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:215:in `cleanup_cache'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:185:in `cleanup_formula'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:153:in `block in clean!'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:152:in `each'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:152:in `clean!'
/usr/local/Homebrew/Library/Homebrew/cmd/cleanup.rb:29:in `cleanup'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
```

I included the whole output of running it for the first time. Ever since the failed cleanup operation, I just get the error output thusly:

```
Error: undefined method `resource' for #<DATAPatch: :p1>
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:87:in `map'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:87:in `stale_formula?'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:53:in `stale?'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:228:in `block in cleanup_cache'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:215:in `each'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:215:in `cleanup_cache'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:185:in `cleanup_formula'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:153:in `block in clean!'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:152:in `each'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:152:in `clean!'
/usr/local/Homebrew/Library/Homebrew/cmd/cleanup.rb:29:in `cleanup'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
```

## What you expected to happen

I expected the cleanup operation to succeed.

## Step-by-step reproduction instructions (by running `brew` commands)

That’s a tough one, as this happened after I ran `brew upgrade` and then ran `brew cleanup`. I’m happy to provide additional information as requested, but am unsure what could help you triage this bug more effectively. I am aware that this means that I actually do not provide a *reproducible* bug report, but I gave you all that I have (and the error message told me to report this bug!).

Cheers

## Appendix

Output of brew config:
```
HOMEBREW_VERSION: 1.7.1-220-g46f531b
ORIGIN: https://github.com/Homebrew/brew
HEAD: 46f531b2b1295e4e9269f9e67cef630e5c357ad8
Last commit: 23 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3c3328734e519b46dffe491e18d28e87557c2281
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_NO_ANALYTICS: 1
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 9.1 build 902
Git: 2.18.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 9.0.1
macOS: 10.13.6-x86_64
CLT: 10.0.0.0.1.1527767617
CLT headers: N/A
Xcode: 9.4.1
XQuartz: N/A
```

Output of brew doctor:
```
Your system is ready to brew.
```

**Comment by hellerve** [comment]
Closing this! It’s a duplicate of #4666. Sorry about that!
