### ISSUE TITLE
Operation not permitted @ utime_internal

### ISSUE THREAD

**Issue by OldCrow** [Homebrew/brew#4699]
When trying to install or update any formulae, the bottle installation fails with the following error and warning combination:
```
Error: Operation not permitted @ utime_internal - /usr/local/Cellar/<name of package>
Warning: Bottle installation failed: building from source.
```
The package is then built from source.  This happens for all formulae, and appears to have started since the last El Capitan security update (perhaps something in the SIP have changed?).

I have run `brew update` and the problem persists.

I have run `brew doctor` - there are no issues reported, and the problem persists.

The output of `brew config` follows:
```
HOMEBREW_VERSION: 1.7.1
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: d6a245c05110c240e680da594c2cc6038998b82e
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1796d3c7560a2c2bf300cbff33b424606600ecc8
Core tap last commit: 63 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: dual-core 64-bit penryn
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 8.0 build 800
Git: 2.10.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.43.0 => /usr/bin/curl
Java: 1.8.0_60, 1.8.0_05, 1.7.0_40
macOS: 10.11.6-x86_64
CLT: 8.2.0.0.1.1480973914
Xcode: 8.2.1
XQuartz: 2.7.11 => /opt/X11
```

The output of `brew doctor` follows:
`Your system is ready to brew.`

As a note, my normal update/upgrade process is to run the following chain of commands via an alias:
`brew update && brew upgrade && brew cleanup && brew cask cleanup && brew prune && brew doctor`
The last time I ran it, this was the result (some path info redacted):
```
Already up-to-date.
==> Upgrading 1 outdated package, with result:
sysdig 0.23.0 -> 0.23.1
==> Upgrading sysdig
==> Downloading https://homebrew.bintray.com/bottles/sysdig-0.23.1.el_capitan.bottle.tar.gz
Already downloaded: /Users/<>/Library/Caches/Homebrew/sysdig-0.23.1.el_capitan.bottle.tar.gz
==> Pouring sysdig-0.23.1.el_capitan.bottle.tar.gz
Error: Operation not permitted @ utime_internal - /usr/local/Cellar/sysdig
Warning: Bottle installation failed: building from source.
==> Downloading https://github.com/draios/sysdig/archive/0.23.1.tar.gz
Already downloaded: /Users/<>/Library/Caches/Homebrew/sysdig-0.23.1.tar.gz
==> cmake .. -DSYSDIG_VERSION=0.23.1 -DUSE_BUNDLED_DEPS=OFF -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-
==> make install
==> Downloading https://gist.githubusercontent.com/juniorz/9986999/raw/a3556d7e93fa890a157a33f4233efaf8f5e01a6f/sample.s
######################################################################## 100.0%
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/sysdig/0.23.1: 115 files, 5MB, built in 2 minutes 32 seconds
Removing: /usr/local/Cellar/graphite2/1.3.11... (18 files, 268.2KB)
Removing: /usr/local/Cellar/harfbuzz/1.8.7... (151 files, 6.3MB)
Removing: /usr/local/Cellar/sysdig/0.23.0... (115 files, 5MB)
Removing: /Users/<>/Library/Caches/Homebrew/harfbuzz-1.8.7.el_capitan.bottle.tar.gz... (1.5MB)
Removing: /Users/<>/Library/Caches/Homebrew/harfbuzz-1.8.7.tar.bz2... (3.7MB)
Removing: /Users/<>/Library/Caches/Homebrew/sysdig-0.23.0.el_capitan.bottle.tar.gz... (1.2MB)
Removing: /Users/<>/Library/Caches/Homebrew/sysdig-0.23.0.tar.gz... (810.3KB)
==> This operation has freed approximately 18.9MB of disk space.
==> Removing cached downloads
Nothing to do
Your system is ready to brew.
```

**Comment by MikeMcQuaid** [comment]
What filesystem is `/usr/local/Cellar` on? Please rerun the `install` or `upgrade` command with `--debug` and paste any backtraces here.

**Comment by OldCrow** [comment]
`/usr/local/Cellar` is on a HFS+ filesystem (the default; never changed or modified).

Here's the debug backtrace you requested.  Hope it's useful:

```
brew upgrade yara --debug
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/yara.rb
==> Upgrading 1 outdated package, with result:
yara 3.8.1
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/autoconf.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/automake.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libtool.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/makedepend.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pkg-config.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/python@2.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/sphinx-doc.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gdbm.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/readline.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/sqlite.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/icu4c.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/tcl-tk.rb
==> Upgrading yara
==> Downloading https://homebrew.bintray.com/bottles/yara-3.8.1.el_capitan.bottle.tar.gz
Already downloaded: /Users/wolfman/Library/Caches/Homebrew/yara-3.8.1.el_capitan.bottle.tar.gz
==> Pouring yara-3.8.1.el_capitan.bottle.tar.gz
Error: Operation not permitted @ utime_internal - /usr/local/Cellar/yara
Warning: Bottle installation failed: building from source.
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/yara.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/python@2.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gdbm.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/readline.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/sqlite.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/autoconf.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/automake.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libtool.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/makedepend.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pkg-config.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/sphinx-doc.rb
==> Downloading https://github.com/VirusTotal/yara/archive/v3.8.1.tar.gz
Already downloaded: /Users/wolfman/Library/Caches/Homebrew/yara-3.8.1.tar.gz
==> ./bootstrap.sh
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/yara/3.8.1 --enable-dotnet
==> make install
Fixing /usr/local/Cellar/yara/3.8.1/bin/yara permissions from 755 to 555
Fixing /usr/local/Cellar/yara/3.8.1/bin/yarac permissions from 755 to 555
Fixing /usr/local/Cellar/yara/3.8.1/lib/libyara.3.dylib permissions from 755 to 444
Fixing /usr/local/Cellar/yara/3.8.1/lib/libyara.a permissions from 644 to 444
Fixing /usr/local/Cellar/yara/3.8.1/lib/pkgconfig/yara.pc permissions from 644 to 444
Changing dylib ID of /usr/local/Cellar/yara/3.8.1/lib/libyara.3.dylib
  from /usr/local/Cellar/yara/3.8.1/lib/libyara.3.dylib
    to /usr/local/opt/yara/lib/libyara.3.dylib
/usr/local/Homebrew/Library/Homebrew/postinstall.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/yara.rb
🍺  /usr/local/Cellar/yara/3.8.1: 43 files, 881.7KB, built in 1 minute 51 seconds
```

**Comment by sophiebits** [comment]
Seeing this too. Stack trace:

```
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/fileutils.rb:1403:in `utime'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/fileutils.rb:1403:in `copy_metadata'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/fileutils.rb:476:in `block in copy_entry'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/fileutils.rb:1505:in `wrap_traverse'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/fileutils.rb:470:in `copy_entry'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:100:in `block in extract_to_dir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:99:in `each'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:99:in `extract_to_dir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:68:in `extract'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:86:in `block in extract_nestedly'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:72:in `extract_nestedly'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:51:in `stage'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:173:in `stage'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:13:in `stage'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:312:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:936:in `block in pour'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:271:in `block in cd'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:271:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:271:in `cd'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:935:in `pour'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:308:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:52:in `reinstall_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:23:in `block in reinstall'
/usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:17:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:17:in `reinstall'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
```

**Comment by sophiebits** [comment]
Works if I own the directory `/usr/local/Cellar/foo`, doesn't work if it's owned by another user on my machine even if it has 775 permissions with a group that include me.

**Comment by MikeMcQuaid** [comment]
@sophiebits Thanks! Can I see your `brew config` too?

**Comment by sophiebits** [comment]
Should be pretty standard I think:

```
HOMEBREW_VERSION: 1.7.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: d6a245c05110c240e680da594c2cc6038998b82e
Last commit: 4 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 79457959f4f6b15238589ab6746b00ef4b842a1e
Core tap last commit: 21 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 9.1 build 902
Git: 2.15.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: N/A
macOS: 10.13.5-x86_64
CLT: 9.4.1.0.1.1528165917
Xcode: N/A
XQuartz: N/A
```

**Comment by OldCrow** [comment]
#4731 seems to have done the job and fixed the issue.  Thanks!  As an aside, `brew update` didn't seem to pick up the change automagically; I had to go into `/usr/local/Homebrew` and `git fetch origin`, `git reset --hard FETCH_HEAD`first.  Not sure if that's another issue or if I just missed something (thought `brew update` was supposed to do all that git fetching behind the scenes).
