### ISSUE TITLE
brew search <formula> returns SSL certificate failure

### ISSUE THREAD

**Issue by kaspermalfroid** [Homebrew/brew#4750]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)
Search for formula.

- What happened (include command output)
I get back some SSL certificate failure:

```
$ brew search vim
Error: SSL_connect returned=1 errno=0 state=error: certificate verify failed
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/net/protocol.rb:44:in `connect_nonblock'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/net/protocol.rb:44:in `ssl_socket_connect'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/net/http.rb:928:in `connect'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/net/http.rb:852:in `start'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/open-uri.rb:319:in `open_http'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/open-uri.rb:737:in `buffer_open'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/open-uri.rb:212:in `block in open_loop'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/open-uri.rb:210:in `catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/open-uri.rb:210:in `open_loop'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/open-uri.rb:151:in `open_uri'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/open-uri.rb:717:in `open'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions/Casks/gpg-suite-nightly.rb:7:in `block (2 levels) in load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/dsl.rb:161:in `block (2 levels) in url'
/usr/local/Homebrew/Library/Homebrew/lazy_object.rb:8:in `__getobj__'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/delegate.rb:80:in `method_missing'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions/Casks/gpg-suite-nightly.rb:12:in `block in load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask.rb:40:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask.rb:40:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:32:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:32:in `cask'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:76:in `cask'
/usr/local/Homebrew/Library/Homebrew/compat/hbc/cask_loader.rb:15:in `cask'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:122:in `cask'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions/Casks/gpg-suite-nightly.rb:1:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:59:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:59:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask.rb:21:in `block in each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask.rb:19:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask.rb:19:in `each'
/usr/local/Homebrew/Library/Homebrew/searchable.rb:27:in `select'
/usr/local/Homebrew/Library/Homebrew/searchable.rb:27:in `search_string'
/usr/local/Homebrew/Library/Homebrew/searchable.rb:7:in `search'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/search.rb:29:in `search_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/search.rb:83:in `search'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
```

- What you expected to happen
A list of formula containing "vim"

- Step-by-step reproduction instructions (by running `brew` commands)
`brew search vim`

Output of `brew config` and `brew doctor`:

```
$ brew config
HOMEBREW_VERSION: 1.7.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: b119591c6963bff320501f52f9029e4862c00e97
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f36fec1af49581a4a95ef4e3acc0a0b0a263968e
Core tap last commit: 18 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_NO_AUTO_UPDATE: 1
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 9.1 build 902
Git: 2.18.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 10.0.2, 10.0.1, 9.0.4, 1.8.0_181, 1.8.0_172
macOS: 10.13.6-x86_64
CLT: 10.0.0.0.1.1527767617
CLT headers: N/A
Xcode: 9.4.1
XQuartz: N/A

$ brew doctor
Your system is ready to brew.```

**Comment by MikeMcQuaid** [comment]
This is an issue with your machine in connecting to GitHub.

**Comment by kaspermalfroid** [comment]
@MikeMcQuaid I have no problem cloning repositories from GitHub from the same terminal, so I don't believe my machine has any issue connecting to GitHub. Could you provide any other ideas to further troubleshoot or run some other commands to test what exactly is going wrong here?

**Comment by MikeMcQuaid** [comment]
@kaspermalfroid Try to use `curl` to connect to api.github.com.

**Comment by kaspermalfroid** [comment]
```
$ curl https://api.github.com
{
  "current_user_url": "https://api.github.com/user",
  "current_user_authorizations_html_url": "https://github.com/settings/connections/applications{/client_id}",
  "authorizations_url": "https://api.github.com/authorizations",
  "code_search_url": "https://api.github.com/search/code?q={query}{&page,per_page,sort,order}",
  "commit_search_url": "https://api.github.com/search/commits?q={query}{&page,per_page,sort,order}",
  "emails_url": "https://api.github.com/user/emails",
  "emojis_url": "https://api.github.com/emojis",
  "events_url": "https://api.github.com/events",
  "feeds_url": "https://api.github.com/feeds",
  "followers_url": "https://api.github.com/user/followers",
  "following_url": "https://api.github.com/user/following{/target}",
  "gists_url": "https://api.github.com/gists{/gist_id}",
  "hub_url": "https://api.github.com/hub",
  "issue_search_url": "https://api.github.com/search/issues?q={query}{&page,per_page,sort,order}",
  "issues_url": "https://api.github.com/issues",
  "keys_url": "https://api.github.com/user/keys",
  "notifications_url": "https://api.github.com/notifications",
  "organization_repositories_url": "https://api.github.com/orgs/{org}/repos{?type,page,per_page,sort}",
  "organization_url": "https://api.github.com/orgs/{org}",
  "public_gists_url": "https://api.github.com/gists/public",
  "rate_limit_url": "https://api.github.com/rate_limit",
  "repository_url": "https://api.github.com/repos/{owner}/{repo}",
  "repository_search_url": "https://api.github.com/search/repositories?q={query}{&page,per_page,sort,order}",
  "current_user_repositories_url": "https://api.github.com/user/repos{?type,page,per_page,sort}",
  "starred_url": "https://api.github.com/user/starred{/owner}{/repo}",
  "starred_gists_url": "https://api.github.com/gists/starred",
  "team_url": "https://api.github.com/teams",
  "user_url": "https://api.github.com/users/{user}",
  "user_organizations_url": "https://api.github.com/user/orgs",
  "user_repositories_url": "https://api.github.com/users/{user}/repos{?type,page,per_page,sort}",
  "user_search_url": "https://api.github.com/search/users?q={query}{&page,per_page,sort,order}"
}
```

**Comment by kaspermalfroid** [comment]
Possibly important finding to mention: I am able to `brew install` formula, but not able to `brew search` formula.

**Comment by MikeMcQuaid** [comment]
I'm sorry, I'm not sure what else to suggest.
