### ISSUE TITLE
Error: parent directory is world writable but not sticky

### ISSUE THREAD

**Issue by zelsonia** [Homebrew/brew#477]
when install composer,have this error

brew install josegonzalez/php/composer
...
Error: parent directory is world writable but not sticky

```
Installing composer from josegonzalez/php
==> Installing dependencies for josegonzalez/php/composer: libpng, freety
==> Installing josegonzalez/php/composer dependency: libpng
==> Downloading https://homebrew.bintray.com/bottles/libpng-1.6.23.yosemite.bott
######################################################################## 100.0%
==> Pouring libpng-1.6.23.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/libpng/1.6.23: 25 files, 1.2M
==> Installing josegonzalez/php/composer dependency: freetype
==> Downloading https://homebrew.bintray.com/bottles/freetype-2.6.3.yosemite.bot
######################################################################## 100.0%
==> Pouring freetype-2.6.3.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/freetype/2.6.3: 61 files, 2.5M
==> Installing josegonzalez/php/composer dependency: gettext
==> Downloading https://homebrew.bintray.com/bottles/gettext-0.19.8.1.yosemite.b
#######                                                                   10.7%
curl: (56) SSLRead() return error -9806
Error: Failed to download resource "gettext"
Download failed: https://homebrew.bintray.com/bottles/gettext-0.19.8.1.yosemite.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://ftpmirror.gnu.org/gettext/gettext-0.19.8.1.tar.xz
==> Downloading from http://mirrors.ustc.edu.cn/gnu/gettext/gettext-0.19.8.1.tar
######################################################################## 100.0%
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/gettext/0.19.8
==> make
==> make install
Error: parent directory is world writable but not sticky
Please report this bug:
    https://git.io/brew-troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:92:in `mktmpdir'
/usr/local/Library/Homebrew/utils/fork.rb:6:in `safe_fork'
/usr/local/Library/Homebrew/formula_installer.rb:574:in `build'
/usr/local/Library/Homebrew/formula_installer.rb:236:in `install'
/usr/local/Library/Homebrew/formula_installer.rb:436:in `install_dependency'
/usr/local/Library/Homebrew/formula_installer.rb:387:in `block in install_dependencies'
/usr/local/Library/Homebrew/formula_installer.rb:387:in `each'
/usr/local/Library/Homebrew/formula_installer.rb:387:in `install_dependencies'
/usr/local/Library/Homebrew/formula_installer.rb:188:in `install'
/usr/local/Library/Homebrew/cmd/install.rb:269:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:149:in `block in install'
/usr/local/Library/Homebrew/cmd/install.rb:149:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:149:in `install'
/usr/local/Library/brew.rb:87:in `<main>'
```

**Comment by DomT4** [comment]
Yikes, I haven't seen this crop up for a while.

`brew doctor` contains fix instructions, but if you can't execute `brew doctor` for some reason the answer is `sudo chmod +t /tmp` unless you've manually set a different `HOMEBREW_TEMP`.

**Comment by zelsonia** [comment]
Thank you very much for helping me resolve this issue. After use brew doctor,l also find other problem, ` `/usr/bin occurs before /usr/local/bin` and l found how to resolve it in http://stackoverflow.com/,but l can't find the page now,it say rewrite etc/paths,and list how to rewrite, l just copy it and didn't see if l have the directory. so when l `source ~/.bash_profile`, many commands l can't use , l found the problem is in the file etc/paths have one path is wrong.l modified this file,and restart computer or restart apache,or source etc/paths,source ~/.bash_profile, it isn't work. The wrong path also in the terminal.
```
-bash: /usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin: No such file or directory
-bash: /usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin: No such file or directory
-bash: /usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin: No such file or directory
```

`/usr/local/sbin ` this one
In etc/paths already not exists,l don't understand why still load it when open terminal.
l'm sorry for my poor english, could you give me some suggestions?
@DomT4

**Comment by zelsonia** [comment]
```
echo $PATH
/usr/local/bin:/usr/local/mysql/bin:.
```

the first is set by  etc/profile
the second  is  set by ~/.bash_profile
so all  in the etc/paths isn't work 

etc/paths
```
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin

```

**Comment by zelsonia** [comment]
l know how to resolve it! my bash_profile is wrong too,open it in terminal is different from open in the l don't know how to call it ,the txt editor,maybe.
thank you again.~
