### ISSUE TITLE
brew update throws error "No such file or directory @ realpath_rec"

### ISSUE THREAD

**Issue by javian** [Homebrew/brew#4786]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew` commands)

After running brew update today I started getting an error about an old bottle from the retired php tap.

```
➜  ~ brew update --debug
<snipped everything in between>
==> Migrating cache entries...
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/wget.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/automake.rb
Error: No such file or directory @ realpath_rec - /usr/local/Homebrew/php71-v8js-2.1.0.high_sierra.bottle.tar.gz
/usr/local/Homebrew/Library/Homebrew/formulary.rb:114:in `realpath'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:114:in `realpath'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:114:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:358:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:358:in `loader_for'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:275:in `factory'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1467:in `[]'
/usr/local/Homebrew/Library/Homebrew/update_migrator.rb:97:in `block in migrate_cache_entries_to_symlinks'
/usr/local/Homebrew/Library/Homebrew/update_migrator.rb:113:in `map'
/usr/local/Homebrew/Library/Homebrew/update_migrator.rb:113:in `migrate_cache_entries_to_symlinks'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:116:in `update_report'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
+ return 1
+ exit 1
```
```
➜  ~ brew config
HOMEBREW_VERSION: 1.7.2-94-gd8dc1f7
ORIGIN: https://github.com/Homebrew/brew
HEAD: d8dc1f7fe076c8f92d8f15c700de4230435ac3f6
Last commit: 3 hours ago
Core tap ORIGIN: git@github.com:Homebrew/homebrew-core.git
Core tap HEAD: 487e16ba1521de9cc16711a901c8bd3820f8efd0
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEVELOPER: 1
HOMEBREW_NO_INSECURE_REDIRECT: 1
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 9.1 build 902
Git: 2.15.2 => /usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: N/A
macOS: 10.13.6-x86_64
CLT: 9.4.1.0.1.1528165917
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11
➜  ~
```

**Comment by reitermarkus** [comment]
What's the output of `ls -al $(brew --cache)`?
