### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by vagnerfonseca** [Homebrew/brew#4803]
Error: uninitialized constant #<Class:0x000000010133d6d0>::MinimumMacOSRequirement
Did you mean?  MaximumMacOSRequirement
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/opt/nanopolish/.brew/nanopolish.rb:19:in `<class:Nanopolish>'
/usr/local/opt/nanopolish/.brew/nanopolish.rb:1:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:26:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:26:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:46:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:95:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:86:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:82:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:275:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:316:in `rescue in from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:312:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:289:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1412:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1410:in `each'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1410:in `flat_map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1410:in `installed'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:720:in `check_missing_deps'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:46:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:38:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:38:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'

**Comment by vagnerfonseca** [comment]
```
$ brew config
HOMEBREW_VERSION: 1.7.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: b119591c6963bff320501f52f9029e4862c00e97
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 371a5c80b68e678371b6defb817c553d69218403
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 7.3 build 703
Git: 2.7.4 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.43.0 => /usr/bin/curl
Java: 1.8.0_91, 1.6.0_65-b14-468
macOS: 10.11.6-x86_64
CLT: 8.2.0.0.1.1480973914
Xcode: 7.3.1
XQuartz: 2.7.11 => /opt/X11
```


```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: /usr/bin occurs before /usr/local/bin
This means that system-provided programs will be used instead of those
provided by Homebrew. The following tools exist at both paths:
  info
  infokey
  install-info
  makeinfo
  texi2dvi
  texi2pdf
  texindex

Consider setting your PATH so that /usr/local/bin
occurs before /usr/bin. Here is a one-liner:
  echo 'export PATH="/usr/local/bin:$PATH"' >> ~/.bash_profile

Warning: Your Xcode (7.3.1) is outdated.
Please update to Xcode 8.2.1 (or delete it).
Xcode can be updated from the App Store.

Error: uninitialized constant #<Class:0x0000000101a26a78>::MinimumMacOSRequirement
Did you mean?  MaximumMacOSRequirement
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/opt/nanopolish/.brew/nanopolish.rb:19:in `<class:Nanopolish>'
/usr/local/opt/nanopolish/.brew/nanopolish.rb:1:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:26:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:26:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:46:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:95:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:86:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:82:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:275:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:316:in `rescue in from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:312:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:289:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1412:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1410:in `each'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1410:in `flat_map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1410:in `installed'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:720:in `check_missing_deps'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:46:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:38:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:38:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
```
