### ISSUE TITLE
rubocop failure during `brew audit` 

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/brew#4987]
- [X] are reporting a bug others will be able to reproduce and not asking a question.
- [X] ran a `brew` command and reproduced the problem with multiple formulae?
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

- What you were trying to do (and why)

Running `brew audit gcc` (or `brew audit` on any other formula).

- What happened (include command output)

```
$ brew audit --strict gcc
Error: Error running `rubocop --format json --require rubocop-rspec --force-exclusion --parallel --except NewFormulaAudit --config /usr/local/Homebrew/Library/.rubocop_audit.yml /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gcc.rb`
Ignoring jaro_winkler-1.5.1 because its extensions are not built.  Try: gem pristine jaro_winkler --version 1.5.1
Ignoring json-2.1.0 because its extensions are not built.  Try: gem pristine json --version 2.1.0
Ignoring rainbow-2.2.2 because its extensions are not built.  Try: gem pristine rainbow --version 2.2.2
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- jaro_winkler (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/rubocop-0.59.1/lib/rubocop/string_util.rb:3:in `<top (required)>'
	from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/rubocop-0.59.1/lib/rubocop.rb:21:in `require_relative'
	from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/rubocop-0.59.1/lib/rubocop.rb:21:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/rubocop-0.59.1/exe/rubocop:6:in `<top (required)>'
	from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/bin/rubocop:22:in `load'
	from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/bin/rubocop:22:in `<main>'
```

**Comment by fxcoudert** [comment]
If I try to run the commands suggested, I get:

```
$ gem pristine jaro_winkler --version 1.5.1
ERROR:  While executing gem ... (Gem::Exception)
    Failed to find gems ["jaro_winkler"] = 1.5.1
```

**Comment by MikeMcQuaid** [comment]
@fxcoudert Try to `cd /usr/local/Homebrew/Library/Homebrew/test/` and run `bundle install`. If that doesn't fix it: `bundle pristine`.

**Comment by MikeMcQuaid** [comment]
@fxcoudert Not `brew bundle`, just `bundle` 😄

**Comment by fxcoudert** [comment]
@MikeMcQuaid I had tried that, but:

```
$ bundle install
zsh: correct 'bundle' to '.bundle' [nyae]? n
zsh: command not found: bundle
```

**Comment by MikeMcQuaid** [comment]
Could try `../bin/bundle install`

**Comment by fxcoudert** [comment]
Worked, thanks! It said:

```
Ignoring rainbow-2.2.2 because its extensions are not built.  Try: gem pristine rainbow --version 2.2.2
Warning: the running version of Bundler (1.15.4) is older than the version that created the lockfile (1.16.4). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
```

Is there any chance others might see the same issue, or do I close?

**Comment by MikeMcQuaid** [comment]
I think close. Was it `bundle install` that fixed it or `bundle pristine`?

**Comment by fxcoudert** [comment]
`bundle install`
