### ISSUE TITLE
Brew requests to please file a bug for known issues with known workarounds.

### ISSUE THREAD

**Issue by JensTimmerman** [Homebrew/brew#5051]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?
``` brew config
HOMEBREW_VERSION: 1.7.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: f239b7a62790cfb4f33bda9aab7597d43f1b1e3b
Last commit: 10 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5945052828109ec8b738663fcb0a0319436a0254
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GIT: git
HOMEBREW_MACOS_VERSION_NUMERIC: 101401
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 10.0 build 1000
Git: 2.19.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 9, 1.8.0_172
macOS: 10.14.1-x86_64
CLT: 10.0.0.0.1.1535735448
CLT headers: N/A
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11
```
```
brew doctor 
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.

Warning: Putting non-prefixed findutils in your path can cause python builds to fail.

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libbeidpkcs11.4.2.7.dylib
  /usr/local/lib/libbeidpkcs11.4.3.5.dylib
  /usr/local/lib/libopenh264-1.4.0-osx64.dylib
```

To help us debug your issue please explain:
- What you were trying to do (and why)
Following brew's kind request to report a bug (to help the brew developers/community)
- What happened (include command output)
The bug was a known issue and was closed, I look like I wasted someones time and nobody was helped.
https://github.com/Homebrew/homebrew-core/issues/32590#issuecomment-427598078

- What you expected to happen
Brew didn't ask me to report a bug/ brew fixed the issue itself by reinitialising the cache/ brew doctor showed me I could fix an issue by deleting the cache `rm ~/Library/Caches/Homebrew/linkage.db` (as I learned by going trough the process of submitting a bug https://github.com/Homebrew/homebrew-core/issues/32590#issuecomment-427598078 )
```
- Step-by-step reproduction instructions (by running `brew` commands)
- brew upgrade
==> Pouring pango-1.42.4.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/pango/1.42.4: 106 files, 4.3MB
Error: 784: unexpected token at '{"keg_files_dylibs":{"/usr/local/Cellar/gtk+/2.24.32_2/bin/gtk-demo":["/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation","/usr/local/Cellar/gtk+/2.24.32_2/lib/libgdk-quartz-2.0.0.dylib","/usr/local/Cellar/gtk+/2.24.32_2/lib/libgtk-quartz-2.0.0.dylib","/usr/local/opt/glib/lib/libgmodule-2.0.0.dylib","/usr/local/opt/pango/lib/libpangocairo-1.0.0.dylib","/usr/local/opt/pango/lib/libpango-1.0.0.dylib","/usr/local/opt/atk/lib/libatk-1.0.0.dylib","/usr/local/opt/cairo/lib/libcairo.2.dylib","/usr/local/opt/gdk-pixbuf/lib/libgdk_pixbuf-2.0.0.dylib","/usr/local/opt/glib/lib/libgio-2.0.0.dylib","/usr/local/opt/glib/lib/libgobject-2.0.0.dylib","/usr/local/opt/glib/lib/libglib-2.0.0.dylib","/usr/lib/libSystem.B.dylib","/usr/local/opt/gettext/lib/libintl.8.dylib","/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa"],"/usr/local/Cellar/gtk+/2.24.32_2/bin/gtk-query-immodules-2.0":["/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation","/usr/local/Cellar/gtk+/2.24.32_2/lib/libgtk-quartz-2.0.0.dylib","/usr/local/Cellar/gtk+/2.24.32_2/lib/libgdk-quartz-2.0.0.dylib","/usr/local/opt/pango/lib/libpangocairo-1.0.0.dylib","/usr/local/opt/pango/lib/libpango-1.0.0.dylib","/usr/local/opt/atk/lib/libatk-1.0.0.dylib","/usr/local/opt/cairo/lib/libcairo.2.dylib","/usr/local/opt/gdk-pixbuf/lib/libgdk_pixbuf-2.0.0.dylib","/usr/local/opt/glib/lib/libgio-2.0.0.dylib","/usr/local/opt/glib/lib/libgobject-2.0.0.dylib","/usr/lib/libSystem.B.dylib","/usr/local/opt/glib/lib/libgmodule-2.0.0.dylib","/usr/local/opt/glib/lib/libglib-2.0.0.dylib","/usr/local/opt/gettext/lib/libintl.8.dylib","/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa"],"/usr/local/Cellar/gtk+/2.24.32_2/bin/gtk-update-icon-cache":["/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation","/usr/local/opt/gdk-pixbuf/lib/libgdk_pixbuf-2.0.0.dylib","/usr/local/opt/glib/lib/libgobject-2.0.0.dylib","/usr/local/opt/glib/lib/libglib-2.0.0.dylib","/usr/local/opt/gettext/lib/libintl.8.dylib","/usr/lib/libSystem.B.dylib"],"/usr/local/Cellar/gtk+/2.24.32_2/lib/gtk-2.0/2.10.0/engines/libpixmap.so":["/usr/local/Cellar/gtk+/2.24.32_2/lib/libgdk-quartz-2.0.0.dylib","/usr/local/Cellar/gtk+/2.24.32_2/lib/libgtk-quartz-2.0.0.dylib","/usr/local/opt/glib/lib/libgmodule-2.0.0.dylib","/usr/local/opt/pango/lib/libpangocairo-1.0.0.dylib","/usr/local/opt/pango/lib/libpango-1.0.0.dylib","/usr/local/opt/atk/lib/libatk-1.0.0.dylib","/usr/local/opt/cairo/lib/libcairo.2.dylib","/usr/local/opt/gdk-pixbuf/lib/libgdk_pixbuf-2.0.0.dylib","/usr/local/opt/glib/lib/libgio-2.0.0.dylib","/usr/local/opt/glib/lib/libgobject-2.0.0.dylib","/usr/local/opt/glib/lib/libglib-2.0.0.dylib","/usr/lib/libSystem.B.dylib","/usr/local/opt/gettext/lib/libintl.8.dylib","/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation","/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa"],"/usr/local/Cellar/gtk+/2.24.32_2/lib/gtk-2.0/2.10.0/immodules/im-am-et.so":["/usr/local/Cellar/gtk+/2.24.32_2/lib/libgdk-quartz-2.0.0.dylib","/usr/local/Cellar/gtk+/2.24.32_2/lib/libgtk-quartz-2.0.0.dylib","/usr/local/opt/glib/lib/libgmodule-2.0.0.dylib","/usr/local/opt/pango/lib/libpangocairo-1.0.0.dylib","/usr/local/opt/pango/lib/libpango-1.0.0.dylib","/usr/local/opt/atk/lib/libatk-1.0.0.dylib","/usr/local/opt/cairo/lib/libcairo.2.dylib","/usr/local/opt/gdk-pixbuf/lib/libgdk_pixbuf-2.0.0.dylib","/usr/local/opt/glib/lib/libgio-2.0.0.dylib","/usr/local/opt/glib/lib/libgobject-2.0.0.dylib","/usr/local/opt/glib/lib/libglib-2.0.0.dylib","/usr/lib/libSystem.B.dylib","/usr/local/opt/gettext/lib/libintl.8.dylib","/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation","/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa"],"/usr/local/Cellar/gtk+/2.24.32_2/lib/gtk-2.0/2.10.0/immodules/im-cedilla.so":["/usr/local/Cellar/gtk+/2.24.32_2/lib/libgdk-quartz-2.0.0.dylib","/usr/local/Cellar/gtk+/2.24.32_2/lib/libgtk-quartz-2.0.0.dylib","/usr/local/opt/glib/lib/libgmodule-2.0.0.dylib","/usr/local/opt/pango/lib/libpangocairo-1.0.0.dylib","/usr/local/opt/pango/lib/libpango-1.0.0.dylib","/usr/local/opt/atk/lib/libatk-1.0.0.dylib","/usr/local/opt/cairo/lib/libcairo.2.dylib","/usr/local/opt/gdk-pixbuf/lib/libgdk_pixbuf-2.0.0.dylib","/usr/local/opt/glib/lib/libgio-2.0.0.dylib","/usr/local/opt/glib/lib/libgobject-2.0.0.dylib","/usr/local/opt/glib/lib/libglib-2.0.0.dylib","/usr/lib/libSystem.B.dylib","/usr/local/opt/gettext/lib/libintl.8.dylib","/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation","/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa"],"/usr/local/Cellar/gtk+/2.24.32_2/lib/gtk-2.0/2.10.0/immodules/im-cyrillic-translit.so":["/usr/local/Cellar/gtk+/2.24.32_2/lib/libgdk-quartz-2.0.0.dylib","/usr/local/Cellar/gtk+/2.24.32_2/lib/libgtk-quartz-2.0.0.dylib","/usr/local/opt/glib/lib/libgmodule-2.0.0.dylib","/usr/local/opt/pango/lib/libpangocairo-1.0.0.dylib","/usr/local/opt/pango/lib/libpango-1.0.0.dylib","/usr/local/opt/atk/lib/libatk-1.0.0.dylib","/usr/local/opt/cairo/lib/libcairo.2.dylib","/usr/local/opt/gdk-pixbuf/lib/libgdk_pixbuf-2.0.0.dylib","/usr/local/opt/glib/lib/libgio-2.0.0.dylib","/usr/local/opt/glib/lib/libgobject-2.0.0.dylib","/usr/local/opt/glib/lib/libglib-2.0.0.dylib","/usr/lib/libSystem.B.dylib","/usr/local/opt/gettext/lib/libintl.8.dylib","/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation","/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa"],"/usr/local/Cellar/gtk+/2.24.32_2/lib/gtk-2.0/2.10.0/immodules/im-inuktitut.so":["/usr/local/Cellar/gtk+/2.24.32_2/lib/libgdk-quartz-2.0.0.dylib","/usr/local/Cellar/gtk+/2.24.32_2/lib/libgtk-quartz-2.0.0.dylib","/usr/local/opt/glib/lib/libgmodule-2.0.0.dylib","/usr/local/opt/pango/lib/libpangocairo-1.0.0.dylib","/usr/local/opt/pango/lib/libpango-1.0.0.dylib","/usr/local/opt/atk/lib/libatk-1.0.0.dylib","/usr/local/opt/cairo/lib/libcairo.2.dylib","/usr/local/opt/gdk-pixbuf/lib/libgdk_pixbuf-2.0.0.dylib","/usr/local/opt/glib/lib/libgio-2.0.0.dylib","/usr/local/opt/glib/lib/libgobject-2.0.0.dylib","/usr/local/opt/glib/lib/libglib-2.0.0.dylib","/usr/lib/libSystem.B.dylib","/usr/local/opt/gettext/lib/libintl.8.dylib","/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation","/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa"],"/usr/local/Cellar/gtk+/2.24.32_2/lib/gtk-2.0/2.10.0/immodules/im-ipa.so":["/usr/local/Cellar/gtk+/2.24.32_2/lib/libgdk-quartz-2.0.0.dylib","/usr/local/Cellar/gtk+/2.24.32_2/lib/libgtk-quartz-2.0.0.dylib","/usr/local/opt/glib/lib/libgmodule-2.0.0.dylib","/usr/local/opt/pango/lib/libpangocairo-1.0.0.dylib","/usr/local/opt/pango/lib/libpango-1.0.0.dylib","/usr/local/opt/atk/lib/libatk-1.0.0.dylib","/usr/local/opt/cairo/lib/libcairo.2.dylib","/usr/local/opt/gdk-pixbuf/lib/libgdk_pixbuf-2.0.0.dylib","/usr/local/opt/glib/lib/libgio-2.0.0.dylib","/usr/local/opt/glib/lib/libgobject-2.0.0.dylib","/usr/local/opt/glib/lib/libglib-2.0.0.dylib","/usr/lib/libSystem.B.dylib","/usr/local/opt/gettext/lib/libintl.8.dylib","/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation","/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa"],"/usr/local/Cellar/gtk+/2.24.32_2/lib/gtk-2.0/2.10.0/immodules/im-multipress.so":["/usr/local/Cellar/gtk+/2.24.32_2/lib/libgdk-quartz-2.0.0.dylib","/usr/local/Cellar/gtk+/2.24.32_2/lib/libgtk-quartz-2.0.0.dylib","/usr/local/opt/glib/lib/libgmodule-2.0.0.dylib","/usr/local/opt/pango/lib/libpangocairo-1.0.0.dylib","/usr/local/opt/pango/lib/libpango-1.0.0.dylib","/usr/local/opt/atk/lib/libatk-1.0.0.dylib","/usr/local/opt/cairo/lib/libcairo.2.dylib","/usr/local/opt/gdk-pixbuf/lib/libgdk_pixbuf-2.0.0.dylib","/usr/local/opt/glib/lib/libgio-2.0.0.dylib","/usr/local/opt/glib/lib/libgobject-2.0.0.dylib","/usr/local/opt/glib/lib/libglib-2.0.0.dylib","/usr/lib/libSystem.B.dylib","/usr/local/opt/gettext/lib/libintl.8.dylib","/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation","/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa"],"/usr/local/Cellar/gtk/usr/local/Cellar/gnome-keyring/2.28.2'
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/json/common.rb:156:in `parse'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/json/common.rb:156:in `parse'
/usr/local/Homebrew/Library/Homebrew/cache_store.rb:185:in `json_string_to_ruby_hash'
/usr/local/Homebrew/Library/Homebrew/linkage_cache_store.rb:71:in `fetch_hash_values'
/usr/local/Homebrew/Library/Homebrew/linkage_cache_store.rb:53:in `fetch_type'
/usr/local/Homebrew/Library/Homebrew/linkage_checker.rb:84:in `check_dylibs'
/usr/local/Homebrew/Library/Homebrew/linkage_checker.rb:25:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:247:in `new'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:247:in `block (3 levels) in broken_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:241:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:241:in `block (2 levels) in broken_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:231:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:231:in `block in broken_dependents'
/usr/local/Homebrew/Library/Homebrew/cache_store.rb:17:in `use'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:230:in `broken_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:332:in `check_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:86:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
```

**Comment by MikeMcQuaid** [comment]
Don’t recreat closed issues. This is not an issue. This has been fixed but is not in a tagged release yet.
