### ISSUE TITLE
Failure to stage resources in test block

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/brew#5122]
Formulas that unpack resources within their `test` block fail. For example:

`brew install flann && brew test flann`

will fail with:

```
Testing flann
Error: flann: failed
An exception occurred within a child process:
  Errno::EPERM: Operation not permitted @ rb_sysopen - /usr/local/var/homebrew/locks/06d890f081f7bf26f8c1e15cbfa7030ae456c9e786f0774dd9a9f172490d6c4e--dataset.dat.incomplete.lock
/usr/local/Homebrew/Library/Homebrew/lock_file.rb:39:in `initialize'
/usr/local/Homebrew/Library/Homebrew/lock_file.rb:39:in `open'
/usr/local/Homebrew/Library/Homebrew/lock_file.rb:39:in `open'
/usr/local/Homebrew/Library/Homebrew/lock_file.rb:39:in `create_lockfile'
/usr/local/Homebrew/Library/Homebrew/lock_file.rb:14:in `lock'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:281:in `fetch'
/usr/local/Homebrew/Library/Homebrew/resource.rb:121:in `fetch'
/usr/local/Homebrew/Library/Homebrew/resource.rb:73:in `stage'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/flann.rb:50:in `block in <class:Flann>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1720:in `block (3 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/utils.rb:523:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1719:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:869:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1718:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1959:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:55:in `block in run'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:55:in `chdir'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:55:in `run'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1958:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1712:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:27:in `<main>'
```

This may be coming from https://github.com/Homebrew/brew/pull/5103 (merged in  https://github.com/Homebrew/brew/commit/1f24c6600c7138785db1b7a5e1783fd7142719cd), cc @reitermarkus

**Comment by fxcoudert** [comment]
I am seeing this locally, and CI shows it for formulas such as [flann](https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/31946/version=sierra/testReport/junit/brew-test-bot/sierra/test_flann/), [libmatio](https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/31946/version=sierra/testReport/junit/brew-test-bot/sierra/test_libmatio/), [caffe](https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/31946/version=sierra/testReport/junit/brew-test-bot/sierra/test_caffe/), and [nco](https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/31946/version=sierra/testReport/junit/brew-test-bot/sierra/test_nco/)

The common denominator is the use of `resource("xxx").stage` inside the `test` block.

**Comment by fxcoudert** [comment]
Thanks @reitermarkus
