### ISSUE TITLE
HEAD installs broken.

### ISSUE THREAD

**Issue by DomT4** [Homebrew/brew#531]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

```
brew install pond --HEAD -v
...
==> go build -tags nogui -o /usr/local/Cellar/pond/HEAD-72b0708_1/bin/pond ./client
Error: Empty installation
/usr/local/Library/Homebrew/formula_installer.rb:592:in `build'
/usr/local/Library/Homebrew/formula_installer.rb:237:in `install'
/usr/local/Library/Homebrew/cmd/install.rb:269:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:149:in `block in install'
/usr/local/Library/Homebrew/cmd/install.rb:149:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:149:in `install'
/usr/local/Library/Homebrew/brew.rb:87:in `<main>'
```

```
ls -1 /usr/local/Cellar/pond/HEAD-72b0708_1
INSTALL_RECEIPT.json
LICENSE
README.md
bin
```

```
/usr/local/Cellar/pond/HEAD-72b0708_1/bin/pond
>>> Pond...
>>> Pond keeps private keys, messages etc on disk for a limited amount of time and that information can be encrypted with a passphrase.
```

@vladshablinsky

**Comment by vladshablinsky** [comment]
😥I'm on it.

**Comment by vladshablinsky** [comment]
The problem is in `update_commit`. When we install `pond` we go to `stage_deps` which triggers resource downloaders fetches and on each of these fetches we rewrite `last_commit` of the formula with the commit of resource.
