### ISSUE TITLE
test block still uses old-style HEAD prefixes

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/brew#535]
`test do` blocks are currently broken for head specs for basically all formulae since the test block code is still using the old-style prefixes:

```
iMac-TMP:Formula joe$ brew install --HEAD wget
==> Cloning git://git.savannah.gnu.org/wget.git
Updating /Users/joe/Library/Caches/Homebrew/wget--git
==> Checking out branch master
==> ./bootstrap
==> ./configure --prefix=/usr/local/Cellar/wget/HEAD-ef372a4 --sysconfdir=/usr/local/etc --with-ssl=openssl --with-libssl-prefix=/usr/local/opt/openssl --disable-iri --disable-pcre
==> make install
🍺  /usr/local/Cellar/wget/HEAD-ef372a4: 48 files, 2.7M, built in 1 minute 59 seconds
iMac-TMP:Formula joe$ brew test -v wget
Testing wget
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20160716-90573-8amf4j.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /usr/local/Library/Taps/homebrew/homebrew-core/Formula/wget.rb -v --HEAD
==> /usr/local/Cellar/wget/HEAD/bin/wget -O - https://google.com
Failed to execute: /usr/local/Cellar/wget/HEAD/bin/wget
Error: wget: failed
Failed executing: /usr/local/Cellar/wget/HEAD/bin/wget -O - https://google.com
/usr/local/Library/Homebrew/formula.rb:1515:in `block in system'
/usr/local/Library/Homebrew/formula.rb:1452:in `open'
/usr/local/Library/Homebrew/formula.rb:1452:in `system'
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/wget.rb:69:in `block in <class:Wget>'
/usr/local/Library/Homebrew/formula.rb:1356:in `block in run_test'
/usr/local/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Library/Homebrew/extend/fileutils.rb:75:in `block in run'
/usr/local/Library/Homebrew/extend/fileutils.rb:75:in `chdir'
/usr/local/Library/Homebrew/extend/fileutils.rb:75:in `run'
/usr/local/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Library/Homebrew/formula.rb:1350:in `run_test'
/usr/local/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Library/Homebrew/test.rb:27:in `<main>'
iMac-TMP:Formula joe$ which wget
/usr/local/bin/wget
iMac-TMP:Formula joe$ readlink `which wget`
../Cellar/wget/HEAD-ef372a4/bin/wget
```

**Comment by ilovezfs** [comment]
CC @vladshablinsky @xu-cheng

**Comment by vladshablinsky** [comment]
Happens because we initialize `HeadSodtwareSpec`'s version with `Version.create("HEAD")`.

**Comment by ilovezfs** [comment]
also affects brew audit's linkage test.
