### ISSUE TITLE
"undefined method `cmd' for FormulaUnavailableError" error during install

### ISSUE THREAD

**Issue by apjanke** [Homebrew/brew#5443]
- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] ran a `brew` command and reproduced the problem with multiple formulae? *Only one formula, but since it's a stacktrace that shouldn't happen, that seems enough to justify a bug report.*
- [X] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem? *One unlinked formula remaining; I doubt it's related.*
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

Trying to install my custom `octave-head-test` formula.

# What happened (include command output)

Got an internal error when trying to build the formula.

```
==> Applying fix-java-char-boxing-segfault.patch
patching file libinterp/octave-value/ov-java.cc
Hunk #1 succeeded at 1363 (offset 55 lines).
/usr/local/Homebrew/Library/Homebrew/build.rb:206:in `rescue in <main>': undefined method `cmd' for #<FormulaUnavailableError:0x00007fd6a8706760> (NoMethodError)
```

<details>
  <summary>Command output</summary>
  <pre>
$ brew install -s --HEAD octave-head-test
==> Installing octave-head-test from octave-app/octave-app-bases
==> Cloning https://hg.savannah.gnu.org/hgweb/octave
Updating /Users/janke/Library/Caches/Homebrew/octave-head-test--hg
pulling from https://hg.savannah.gnu.org/hgweb/octave
searching for changes
no changes found
==> Checking out branch default
0 files updated, 0 files merged, 0 files removed, 0 files unresolved
==> Downloading https://gist.githubusercontent.com/apjanke/da92f70978aa8db01f484c782aed89a9/raw/37e18bf40da77dedbab6b5a02cb28dd142bb9
######################################################################## 100.0%
==> Patching
patching file libgui/src/main-window.cc
Hunk #1 succeeded at 2831 with fuzz 2 (offset 2610 lines).
Hunk #2 succeeded at 2898 with fuzz 2 (offset 1365 lines).
==> Applying fix-java-char-boxing-segfault.patch
patching file libinterp/octave-value/ov-java.cc
Hunk #1 succeeded at 1363 (offset 55 lines).
/usr/local/Homebrew/Library/Homebrew/build.rb:206:in `rescue in <main>': undefined method `cmd' for #<FormulaUnavailableError:0x00007fd6a8706760> (NoMethodError)
	from /usr/local/Homebrew/Library/Homebrew/build.rb:183:in `<main>'
Error: Failure while executing; `/usr/bin/sandbox-exec -f /private/tmp/homebrew20181225-94869-qthjpi.sb nice /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.1.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-rspec-1.30.1/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-0.61.1/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/unicode-display_width-1.4.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-progressbar-1.10.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rainbow-3.0.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/powerpack-0.1.2/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.4.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parser-2.5.3.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parallel-1.12.1/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/jaro_winkler-1.5.1/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/jaro_winkler-1.5.1:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ast-2.4.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/activesupport-5.2.2/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/i18n-1.3.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.1.4/lib:/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib:/Library/Ruby/Site/2.3.0:/Library/Ruby/Site/2.3.0/x86_64-darwin17:/Library/Ruby/Site/2.3.0/universal-darwin17:/Library/Ruby/Site:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17:/usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/octave-app/homebrew-octave-app-bases/Formula/octave-head-test.rb --HEAD` exited with 1.  
  </pre>
</details>

Config and doctor:

```
$ brew config                                                                                                               master ✱
HOMEBREW_VERSION: 1.8.6-38-g8842832
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8842832cf412382d8c74dc9c5399bd122f44e0c9
Last commit: 31 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 51ffaf95fdbf938c6d39e0e067d404681e068286
Core tap last commit: 9 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEVELOPER: 1
HOMEBREW_NO_AUTO_UPDATE: 1
HOMEBREW_SANDBOX: 1
HOMEBREW_VISUAL: subl -w
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.20.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 11.0.1, 10.0.1, 9.0.4, 1.8.0_191, 1.8.0_181, 1.8.0_171, 1.8.0_141, 1.7.0_79
macOS: 10.13.6-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1 => /Applications/Xcode-10.1.app/Contents/Developer
XQuartz: 2.7.11 => /opt/X11
[/usr/local/Homebrew/Library/Taps/octave-app/homebrew-octave-app-bases]
$ brew doctor                                                                                                               master ✱
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  ghostscript
[/usr/local/Homebrew/Library/Taps/octave-app/homebrew-octave-app-bases]
$
```

The unlinked `ghostscript` is there because I have a non-Homebrewed Ghostscript installed on this machine.

# What you expected to happen

Better error message that describes what went wrong, instead of an "undefined method" error.

# Step-by-step reproduction instructions (by running `brew` commands)

```
brew tap octave-app/octave-app-bases
brew install -s --HEAD octave-app-test
```

**Comment by apjanke** [comment]
I think I see the error, or at least part of it.

https://github.com/Homebrew/brew/blob/8842832cf412382d8c74dc9c5399bd122f44e0c9/Library/Homebrew/build.rb#L205

That single `=` is an assignment, not a comparison. Wonder why Rubocop didn't catch that?
