### ISSUE TITLE
brew tap-new generates not working azure-config

### ISSUE THREAD

**Issue by sashkab** [Homebrew/brew#5481]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

Trying to create new tap and enable CI checks using `brew tap-new` command. 

# What happened (include command output)

After creating tap, pushing to repository, enabling Azure Pipelines on that repository, build will success even if it shouldn't. 

# What you expected to happen

Build should have failed. 

# Step-by-step reproduction instructions (by running `brew` commands)

```sh
brew tap-new sashkab/homebrew-azuretest
cp -pr /usr/local/Homebrew/Library/Taps/sashkab/homebrew-azuretest .
cd homebrew-azuretest
git remote add origin git@github.com:sashkab/homebrew-azuretest.git
git add --all
git ci -am "test"
brew install Formula/test3.rb
$ brew test Formula/test3.rb
Testing test3
Error: test3: failed
An exception occurred within a child process:
  ArgumentError: wrong number of arguments (given 0, expected 1+)
/usr/local/Homebrew/Library/Homebrew/formula.rb:1833:in `system'
/Users/b/Work/homebrew/homebrew-azuretest/Formula/test3.rb:10:in `block in <class:Test3>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1732:in `block (3 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/utils.rb:523:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1731:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:870:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1730:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1971:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:55:in `block in run'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:55:in `chdir'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:55:in `run'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1970:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1724:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:27:in `<main>'
git push origin master
```

Then check pipeline to... succeed — https://dev.azure.com/sashka1/sashka1/_build/results?buildId=10

Test repository is at https://github.com/sashkab/homebrew-azuretest

**Comment by MikeMcQuaid** [comment]
You're using invalid syntax in your formula.

> * ran a `brew` command and reproduced the problem with multiple formulae?

You didn't do this.

> * ran `brew config` and `brew doctor` and included their output with your issue?

Please do this in future.

**Comment by sashkab** [comment]
> > * ran `brew config` and `brew doctor` and included their output with your issue?
> 
> Please do this in future.

These are irrelevant here, as I'm having issue with the Azure. 

But if you insist —


```
$ brew config
HOMEBREW_VERSION: 1.8.6-97-g191a999
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 191a9998a8e101c0972387f00f981681ccb500f0
Last commit: 19 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 62a67fa76ea3afa09d64d76a08c9a1b2338d95e4
Core tap last commit: 72 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_LOGS: /Users/b/Library/Logs/Homebrew
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.20.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.2-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11
$ brew doctor
Your system is ready to brew.
```


> > * ran a `brew` command and reproduced the problem with multiple formulae?
> 
> You didn't do this.
> 

I created a test repository, which reproduces this issue. I have second repository, where I observing same issue — https://github.com/sashkab/homebrew-python/pull/34

**Comment by sashkab** [comment]
> You're using invalid syntax in your formula.

That's the purpose of the repository — I need build to fail, but it succeeds.

**Comment by MikeMcQuaid** [comment]
> These are irrelevant here, as I'm having issue with the Azure.

You should post the results from Azure, then. Please let us decide what's irrelevant, thanks.

> That's the purpose of the repository — I need build to fail, but it succeeds.

Did you read the build output? It's not testing your formula at all because it hasn't changed in the given commit/pull request. Read the documentation (and code) for `brew test-bot`, we don't provide this level of support, sorry.

**Comment by sashkab** [comment]
Understood, sorry for misunderstanding. 

```
2019-01-04T13:23:01.4421560Z [34m==>[0m [1mbrew doctor[0m
2019-01-04T13:23:03.4708090Z Your system is ready to brew.
```

```
2019-01-04T13:23:05.2227590Z [34m==>[0m [1mbrew config[0m
2019-01-04T13:23:06.1429630Z HOMEBREW_VERSION: 1.8.6-97-g191a999
2019-01-04T13:23:06.2447360Z ORIGIN: https://github.com/Homebrew/brew
2019-01-04T13:23:06.2953940Z HEAD: 191a9998a8e101c0972387f00f981681ccb500f0
2019-01-04T13:23:06.3488730Z Last commit: 19 hours ago
2019-01-04T13:23:06.4009040Z Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
2019-01-04T13:23:06.4532310Z Core tap HEAD: 62a67fa76ea3afa09d64d76a08c9a1b2338d95e4
2019-01-04T13:23:06.5148710Z Core tap last commit: 52 minutes ago
2019-01-04T13:23:06.5149860Z HOMEBREW_PREFIX: /usr/local
2019-01-04T13:23:06.5150470Z HOMEBREW_AZURE_PIPELINES: 1
2019-01-04T13:23:06.5151050Z HOMEBREW_COLOR: 1
2019-01-04T13:23:06.5151540Z HOMEBREW_DEVELOPER: 1
2019-01-04T13:23:06.5151680Z HOMEBREW_FAIL_LOG_LINES: 150
2019-01-04T13:23:06.5154350Z HOMEBREW_LANGUAGES: en-GB
2019-01-04T13:23:06.5154960Z HOMEBREW_LOGS: /Users/vsts/Library/Logs/Homebrew
2019-01-04T13:23:06.5155400Z HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
2019-01-04T13:23:06.5155570Z HOMEBREW_NO_AUTO_UPDATE: 1
2019-01-04T13:23:06.5155690Z HOMEBREW_NO_EMOJI: 1
2019-01-04T13:23:06.5271360Z CPU: quad-core 64-bit ivybridge
2019-01-04T13:23:06.5278720Z Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
2019-01-04T13:23:06.5671390Z Clang: 10.0 build 1000
2019-01-04T13:23:06.6778460Z Git: 2.17.1 => /Applications/Xcode_10.app/Contents/Developer/usr/bin/git
2019-01-04T13:23:06.6936930Z Curl: 7.54.0 => /usr/bin/curl
2019-01-04T13:23:06.8479710Z Java: 11.0.1, 10.0.2, 9.0.4, 1.8.0_192, 1.7.0_80
2019-01-04T13:23:06.8522690Z macOS: 10.13.6-x86_64
2019-01-04T13:23:06.9899030Z CLT: 10.1.0.0.1.1539992718
2019-01-04T13:23:06.9904980Z Xcode: 10.0 => /Applications/Xcode_10.app/Contents/Developer
```

[Commit in question introduces new formula](https://github.com/sashkab/homebrew-azuretest/commit/8e1267bf4e009159c2a683016da1b6a38c756613), which shouldn't pass test. Pipeline ends with:

```
2019-01-04T13:23:07.1615250Z [34m==>[0m [1mbrew readall --aliases sashkab/azuretest[0m
2019-01-04T13:23:08.3176320Z ##[section]Finishing: Run brew test-bot
```

I'm not asking for support. I am reporting an issue with the recent change.

**Comment by MikeMcQuaid** [comment]
> I am reporting an issue with the recent change.

`brew test-bot` did not work differently on Travis CI.

**Comment by sashkab** [comment]
> `brew test-bot` did not work differently on Travis CI.

What would be the reason for brew-bot exiting right after `brew readall --aliases tapname`? I cannot understand that and unable to reproduce it locally.

**Comment by MikeMcQuaid** [comment]
Can you explain:
- What you were trying to do (and why)
- What happened
- What you expected to happen
- Step-by-step reproduction instructions (with as minimal input data as possible)

**Comment by sashkab** [comment]
> * What you were trying to do (and why)

I am trying to enable CI for my homebrew tap. 

> * What happened

While my repository had errors in one of the formula, CI ran was passing. I was modifying the formula in question in my commits with CI enabled. Upon closer inspection it seems that CI run was stopping after `brew readall --aliases tapname ` step and further steps did not ran.

> * What you expected to happen

I expected CI to fail and report problem building the formula. 

> * Step-by-step reproduction instructions (with as minimal input data as possible)

I've created two test projects:

1. https://github.com/sashkab/x
1. https://github.com/sashkab/homebrew-azuretest

The second project is Formula to build the  first one, which introduces build failure. 

On my local workstation, it fails to build as expected:

```sh
$ brew tap sashkab/azuretest
$ brew install test3
==> Installing test3 from sashkab/azuretest
==> Downloading https://github.com/sashkab/x/archive/0.0.0.tar.gz
Already downloaded: /Users/b/Library/Caches/Homebrew/downloads/9cd256cda922d6be07c801b28bebe3ef589691e49a985b483f124a9f3659c416--x-0.0.0.tar.gz
==> ./configure --prefix=/usr/local/Cellar/test3/0.0.0_2
==> make clean
==> make install
==> make false
Last 15 lines from /Users/b/Library/Logs/Homebrew/test3/04.make:
2019-01-09 12:21:19 -0500

make
false

make: *** No rule to make target `false'.  Stop.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/sashkab/homebrew-azuretest/issues
```

The CI job successes for this code, as you can see here — https://dev.azure.com/sashka1/sashka1/_build/results?buildId=26

The last lines in the log are:

```txt
...
2019-01-09T17:25:57.8076330Z ‌==>‌ ‌brew readall --aliases sashkab/azuretest‌
2019-01-09T17:25:57.8077400Z brew readall --aliases sashkab/azuretest
2019-01-09T17:25:58.6701540Z /usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `exit'
2019-01-09T17:25:58.6702360Z /usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
2019-01-09T17:25:58.7498010Z ##[debug]Exit code 0 received from tool '/bin/bash'
2019-01-09T17:25:58.7562240Z ##[debug]STDIO streams have closed for tool '/bin/bash'
2019-01-09T17:25:58.7577030Z ##[debug]task result: Succeeded
2019-01-09T17:25:58.7602050Z ##[debug]Processed: ##vso[task.complete result=Succeeded;done=true;]
```


And since you always ask for the `brew doctor` and `brew config` here they are:

```
2019-01-09T17:25:52.2252410Z ‌==>‌ ‌brew doctor‌
2019-01-09T17:25:52.2278320Z brew doctor
2019-01-09T17:25:54.2117630Z Your system is ready to brew.
2019-01-09T17:25:54.2231350Z 
```

```
2019-01-09T17:25:55.9089250Z ‌==>‌ ‌brew config‌
2019-01-09T17:25:55.9091910Z brew config
2019-01-09T17:25:56.7552910Z HOMEBREW_VERSION: 1.9.0-2-g04b8cb8
2019-01-09T17:25:56.8598240Z ORIGIN: https://github.com/Homebrew/brew
2019-01-09T17:25:56.9128360Z HEAD: 04b8cb852cc4c5ed69e54429c66ab5b42867d57a
2019-01-09T17:25:56.9663220Z Last commit: 6 minutes ago
2019-01-09T17:25:57.0211380Z Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
2019-01-09T17:25:57.0781670Z Core tap HEAD: 53fc2f730f3d75df74111ec29d6af0d2e2de5102
2019-01-09T17:25:57.1436130Z Core tap last commit: 3 hours ago
2019-01-09T17:25:57.1438030Z HOMEBREW_PREFIX: /usr/local
2019-01-09T17:25:57.1439750Z HOMEBREW_AZURE_PIPELINES: 1
2019-01-09T17:25:57.1440990Z HOMEBREW_COLOR: 1
2019-01-09T17:25:57.1441440Z HOMEBREW_DEVELOPER: 1
2019-01-09T17:25:57.1441840Z HOMEBREW_FAIL_LOG_LINES: 150
2019-01-09T17:25:57.1443310Z HOMEBREW_LANGUAGES: en-GB
2019-01-09T17:25:57.1443560Z HOMEBREW_LOGS: /Users/vsts/Library/Logs/Homebrew
2019-01-09T17:25:57.1443780Z HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
2019-01-09T17:25:57.1444450Z HOMEBREW_NO_AUTO_UPDATE: 1
2019-01-09T17:25:57.1444630Z HOMEBREW_NO_EMOJI: 1
2019-01-09T17:25:57.1580190Z CPU: quad-core 64-bit ivybridge
2019-01-09T17:25:57.1580620Z Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
2019-01-09T17:25:57.1992340Z Clang: 10.0 build 1000
2019-01-09T17:25:57.3039540Z Git: 2.17.1 => /Applications/Xcode_10.app/Contents/Developer/usr/bin/git
2019-01-09T17:25:57.3185840Z Curl: 7.54.0 => /usr/bin/curl
2019-01-09T17:25:57.4752560Z Java: 11.0.1, 10.0.2, 9.0.4, 1.8.0_192, 1.7.0_80
2019-01-09T17:25:57.4792550Z macOS: 10.13.6-x86_64
2019-01-09T17:25:57.6293690Z CLT: 10.1.0.0.1.1539992718
2019-01-09T17:25:57.6311610Z Xcode: 10.0 => /Applications/Xcode_10.app/Contents/Developer
```

**Comment by sashkab** [comment]
@MikeMcQuaid  did you have a chance to look into my answers? Thanks!

**Comment by MikeMcQuaid** [comment]
@sashkab sorry you’ll need to figure this out yourself.
