### ISSUE TITLE
brew gist-logs throws uninitialized constant Homebrew::Install

### ISSUE THREAD

**Issue by nextstopsun** [Homebrew/brew#5586]
When I do 
```
brew gist-logs qgis
```
I get 
```
Error: uninitialized constant Homebrew::Install
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/cmd/gist-logs.rb:137:in `gist_logs'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

Is gist-logs broken currently?

**Comment by MikeMcQuaid** [comment]
Please always fill in the issue template.
