### ISSUE TITLE
error installing go from HEAD: go does not define resource "gotools"

### ISSUE THREAD

**Issue by nhooyr** [Homebrew/brew#570]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

When trying to install go from `HEAD` I get the following error:

```
[$] brew install --HEAD go
==> Cloning https://github.com/golang/go.git
Updating /Users/nhooyr/Library/Caches/Homebrew/go--git
==> Checking out branch master
==> Downloading https://storage.googleapis.com/golang/go1.4.2.darwin-amd64-osx10.8.tar.gz
Already downloaded: /Users/nhooyr/Library/Caches/Homebrew/go--gobootstrap-10.8.tar.gz
==> ./make.bash --no-clean
==> ./make.bash --no-clean
==> /usr/local/Cellar/go/HEAD-243d51f/bin/go install -race std
Error: go does not define resource "gotools"
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/software_spec.rb:107:in `block in resource'
/usr/local/Library/Homebrew/software_spec.rb:107:in `fetch'
/usr/local/Library/Homebrew/software_spec.rb:107:in `resource'
/usr/local/Library/Homebrew/formula.rb:308:in `resource'
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/go.rb:88:in `install'
/usr/local/Library/Homebrew/build.rb:131:in `block in install'
/usr/local/Library/Homebrew/formula.rb:945:in `block in brew'
/usr/local/Library/Homebrew/formula.rb:1581:in `block in stage'
/usr/local/Library/Homebrew/resource.rb:98:in `block in unpack'
/usr/local/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Library/Homebrew/extend/fileutils.rb:75:in `block in run'
/usr/local/Library/Homebrew/extend/fileutils.rb:75:in `chdir'
/usr/local/Library/Homebrew/extend/fileutils.rb:75:in `run'
/usr/local/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Library/Homebrew/resource.rb:94:in `unpack'
/usr/local/Library/Homebrew/resource.rb:86:in `stage'
/usr/local/Library/Homebrew/formula.rb:1569:in `stage'
/usr/local/Library/Homebrew/formula.rb:940:in `brew'
/usr/local/Library/Homebrew/build.rb:108:in `install'
/usr/local/Library/Homebrew/build.rb:179:in `<main>'
```

gist-logs: https://gist.github.com/nhooyr/32dd18c44b1ec133b98e8a4952960457

**Comment by DomT4** [comment]
Sorry, stupid mistake on my part when I fixed things for the `devel` version of Go the other day. Should be alright after a `brew update`.
