### ISSUE TITLE
'Error: can't modify frozen object' for update and doctor if recipe attempts to mutate ARGV

### ISSUE THREAD

**Issue by fredemmott** [Homebrew/brew#5770]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

A brew install failed with with ` Error: can't modify frozen object'; after that - though it actually did install successfully by the looks of things, despite non-zero exit. After that, `brew update` and `brew doctor exit with the same error.

I have this on two issues after running `brew upgrade`. No problem on 2.0.2

# What happened (include command output)

## Failed build

```
+ brew upgrade
Updating Homebrew...
==> Auto-updated Homebrew!
Updated Homebrew from 117c24f4b to 78a1732ba.
Updated 1 tap (homebrew/core).
==> New Formulae
mage
==> Updated Formulae
allure
autoconf-archive
ballerina
crowdin
flake8
fonttools
handbrake
jenkins
jfrog-cli-go
mariadb@10.1
mysql@5.7
phpunit
pixman
pypy3
rabbitmq
ship
squid
texinfo
tmux-xpanes

+ cd Formula
+ brew install --build-bottle ./hhvm-nightly.rb
==> Downloading https://dl.hhvm.com/source/nightlies/hhvm-nightly-2019.02.19.tar.gz
==> cmake -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/hhvm-nightly/2019.02.19 -DCMAKE_INSTALL_SYSCONFDIR=/usr/local/etc -DDEFAULT_CONFIG_DIR=/usr/local/etc/hhvm -DENABLE_MCROUTER=OFF -DENABLE_EXTENSION_MCROUTER=OFF -DENABLE_EXTENSION_IMAP=OFF -DMYSQL_UNIX_SOCK_ADDR=/tmp/mysql.sock -DCMAKE_C_FLAGS=-DLZ4_DISABLE_DEPRECATE_WARNINGS=1 -DCMAKE_CXX_FLAGS=-DLZ4_DISABLE_DEPRECATE_WARNINGS=1 -DU_USING_ICU_NAMESPACE=1 -DSYSTEM_PCRE_HAS_JIT=1 -DICU_INCLUDE_DIR=/usr/local/opt/icu4c/include -DICU_I18N_LIBRARY=/usr/local/opt/icu4c/lib/libicui18n.a -DICU_LIBRARY=/usr/local/opt/icu4c/lib/libicuuc.a -DICU_DATA_LIBRARY=/usr/local/opt/icu4c/lib/libicudata.a -DTBB_INCLUDE_DIR=/usr/local/opt/tbb/include -DTBB_INSTALL_DIR=/usr/local/opt/tbb -DTBB_LIBRARY=/usr/local/opt/tbb/lib/libtbb.dylib -DTBB_LIBRARY_DEBUG=/usr/local/opt/tbb/lib/libtbb.dylib -DTBB_LIBRARY_DIR=/usr/local/opt/tbb/lib -DTBB_MALLOC_LIBRARY=/usr/local/opt/tbb/lib/libtbbmalloc.dylib -DTBB_MALLOC_LIBRARY_DEBUG=/usr/local/opt/tbb/lib/libtbbmalloc.dylib .
==> make
==> make install
Error: can't modify frozen object
==> Not running post_install as we're building a bottle
You can run it manually using `brew postinstall hhvm-nightly`
==> Caveats
To have launchd start hhvm-nightly now and restart at login:
  brew services start hhvm-nightly
Or, if you don't want/need a background service you can just run:
  hhvm -m daemon -c /usr/local/etc/hhvm/php.ini -c /usr/local/etc/hhvm/server.ini
==> Summary
�  /usr/local/Cellar/hhvm-nightly/2019.02.19: 1,150 files, 283.5MB, built in 29 minutes 15 seconds
```

## brew config

```
HOMEBREW_VERSION: 2.0.2-10-g605c0e8
ORIGIN: https://github.com/Homebrew/brew
HEAD: 605c0e82398f7e90ae92e42dd4dc7af134736e0d
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1317e7f77d9583b560f1f62af98c90b4beee068c
Core tap last commit: 56 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_LOGS: /Users/hhvmoss/Library/Logs/Homebrew
CPU: dodeca-core 64-bit ivybridge
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.1-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: N/A
```

## Failing built-ins after that

```
hhvm-mojave:~ hhvmoss$ brew update; echo "Exit: $?"
Already up-to-date.
Exit: 0
hhvm-mojave:~ hhvmoss$ brew upgrade; echo "Exit: $?"
Error: can't modify frozen object
Exit: 1
hhvm-mojave:~ hhvmoss$ brew doctor; echo "Exit: $?"
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  md5sha1sum
Error: can't modify frozen object
Exit: 1
```

## Git info

```
hhvm-mojave:Homebrew hhvmoss$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
hhvm-mojave:Homebrew hhvmoss$ git log -1
commit 605c0e82398f7e90ae92e42dd4dc7af134736e0d (HEAD -> master, origin/master)
Merge: 78a1732ba d4e3fb45c
Author: Mike McQuaid <mike@mikemcquaid.com>
Date:   Tue Feb 19 12:56:36 2019 +0000

    Merge pull request #5769 from waldyrious/patch-1

    missing_formula.rb: add help message for uconv
```

# What you expected to happen

brew upgrade and brew doctor to exit without error

# Step-by-step reproduction instructions (by running `brew` commands)

```
brew upgrade # to get to 605c0e82398f7e90ae92e42dd4dc7af134736e0d
brew doctor # fails
```

# Problem does not exist in 2.0.2

```
hhvm-mojave:~ hhvmoss$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  md5sha1sum
Error: can't modify frozen object
hhvm-mojave:~ hhvmoss$ cd /usr/local/Homebrew
hhvm-mojave:Homebrew hhvmoss$ git reset --hard 2.0.2
HEAD is now at 117c24f4b Merge pull request #5756 from MikeMcQuaid/update-untap
hhvm-mojave:Homebrew hhvmoss$ cd
hhvm-mojave:~ hhvmoss$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  md5sha1sum
```

No error on last line.

**Comment by fredemmott** [comment]
So, this is a formula-specific issue:

```
$ brew doctor -d --verbose
.....
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/opt/hhvm-nightly/.brew/hhvm-nightly.rb
Error: can't modify frozen object
/usr/local/opt/hhvm-nightly/.brew/hhvm-nightly.rb:17:in `<class:HhvmNightly>'
/usr/local/opt/hhvm-nightly/.brew/hhvm-nightly.rb:1:in `load_formula'
```

```
$ head -n 25 /usr/local/opt/hhvm-nightly/.brew/hhvm-nightly.rb | nl | tail -n 10
    15    end
    16    def ARGV.bottle_arch
    17      :sandybridge
    18    end

    19    option "with-debug", <<~EOS
    20      Make an unoptimized build with assertions enabled. This will run PHP and
    21      Hack code dramatically slower than a release build, and is suitable mostly
    22      for debugging HHVM itself.
    23    EOS
```

this will be cee75b6af2114cf48fbbd25a7f2bcc04de413654

Will re-build hhvm without this and see if using the new default is acceptable for us performance-wise.

Leaving open as while there is a formula-specific issue here, `brew doctor` should probably handle it withotu --verbose --debug

**Comment by fredemmott** [comment]
It looks like if you have any recipes installed that do this, or similar, after a `brew update` gets you to a broken state that `brew update` and `brew doctor` can't fix, and don't give you useful output.

**Comment by scpeters** [comment]
This may be a consequence of https://github.com/Homebrew/brew/pull/5765

**Comment by scpeters** [comment]
I believe this is from a 3rd-party tap:

* https://github.com/hhvm/homebrew-hhvm/commit/4e1aaca6eed6b023098ff1e73440a823c260ca99

**Comment by fredemmott** [comment]
Yeah, I've removed the change from the tap - however, a tap being able to accidentally break `brew doctor` is probably a bug in brew itself :)
