### ISSUE TITLE
inreplace is changing file permissions

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/brew#5916]
Let's consider the following minimal formula:

```
$ cat libspatialite.rb
class Libspatialite < Formula
  url "https://www.gaia-gis.it/gaia-sins/libspatialite-sources/libspatialite-4.3.0a.tar.gz"
  sha256 "88900030a4762904a7880273f292e5e8ca6b15b7c6c3fb88ffa9e67ee8a5a499"

  patch do
   url "https://raw.githubusercontent.com/Homebrew/formula-patches/27a0e51936e01829d0a6f3c75a7fbcaf92bb133f/libspatialite/sqlite310.patch"
   sha256 "459434f5e6658d6f63d403a7795aa5b198b87fc9f55944c714180e7de662fce2"
  end

  def install
    system "stat", "configure"
    inreplace "configure",
              "shrext_cmds='`test .$module = .yes && echo .so || echo .dylib`'",
              "shrext_cmds='.dylib'"
    system "stat", "configure"
    system "false"
  end
end
```

The `inreplace` statement is changing the permissions of the `configure` file, as a verbose install reveals:

```
==> stat configure
16777220 29422446 -rwxr-xr-x 1 fx wheel 0 651938 "Mar 23 22:10:35 2019" "Mar 23 22:10:35 2019" "Mar 23 22:10:35 2019" "Mar 23 22:10:35 2019" 4096 1280 0 configure
==> stat configure
16777220 29422455 -rw------- 1 fx admin 0 651852 "Mar 23 22:10:35 2019" "Mar 23 22:10:35 2019" "Mar 23 22:10:35 2019" "Mar 23 22:10:35 2019" 4096 1280 0 configure
==> false
```

In the first `stat`, `configure` was `-rwxr-xr-x`, in the second one it's `-rw-------`.

This issue is making `libspatialite` in Homebrew core fail to build, while it works working a while ago… so it is actually a `brew` regression.

**Comment by fxcoudert** [comment]
What is totally puzzling to me, is that this only occurs if the `patch do` block is present. Otherwise, the permission is unchanged by `inreplace`. I have no idea how this is happening.

**Comment by amyspark** [comment]
I went as far as 1.4.0 (`git checkout`) and this still repro's, so I don't think this is a Homebrew issue. (Perhaps some change in vendored Ruby?)

**Comment by amyspark** [comment]
@fxcoudert, 

https://github.com/Homebrew/brew/blob/167363525136f48010939fdebd309bce5a79c9bf/Library/Homebrew/utils/inreplace.rb#L35

It seems that the atomic write primitive in `inreplace` is dropping the existing file's permissions.

I employed this little patch to use `write` instead and test again:

```diff
diff --git a/Library/Homebrew/extend/pathname.rb b/Library/Homebrew/extend/pathname.rb
index c27322e2..b21575a8 100644
--- a/Library/Homebrew/extend/pathname.rb
+++ b/Library/Homebrew/extend/pathname.rb
@@ -148,7 +148,7 @@ class Pathname
 
   # We assume this pathname object is a file, obviously
   def write(content, *open_args)
-    raise "Will not overwrite #{self}" if exist?
+    #raise "Will not overwrite #{self}" if exist?
 
     dirname.mkpath
     open("w", *open_args) { |f| f.write(content) }
diff --git a/Library/Homebrew/utils/inreplace.rb b/Library/Homebrew/utils/inreplace.rb
index 67881953..2e1d1b02 100644
--- a/Library/Homebrew/utils/inreplace.rb
+++ b/Library/Homebrew/utils/inreplace.rb
@@ -32,7 +32,7 @@ module Utils
 
         errors[path] = s.errors unless s.errors.empty?
 
-        Pathname(path).atomic_write(s)
+        Pathname(path).write(s)
       end
 
       raise InreplaceError, errors unless errors.empty?
```

```
amalia@Sakura:/usr/local/Homebrew $ brew install amyspark/dev-tap/libspatialite --verbose
==> Installing libspatialite from amyspark/dev-tap
<snip>
==> Downloading https://www.gaia-gis.it/gaia-sins/libspatialite-sources/libspatialite-4.3.0a.tar.gz
Already downloaded: /Users/amalia/Library/Caches/Homebrew/downloads/3ef5e810c67c101a7620c263b527c9f85676a2e101660b8a84cd7421d09a76a0--libspatialite-4.3.0a.tar.gz
==> Verifying 3ef5e810c67c101a7620c263b527c9f85676a2e101660b8a84cd7421d09a76a0--libspatialite-4.3.0a.tar.gz checksum
tar xof /Users/amalia/Library/Caches/Homebrew/downloads/3ef5e810c67c101a7620c263b527c9f85676a2e101660b8a84cd7421d09a76a0--libspatialite-4.3.0a.tar.gz -C /private/tmp/d20190408-90069-8ntclg
cp -pR /private/tmp/d20190408-90069-8ntclg/libspatialite-4.3.0a/. /private/tmp/libspatialite-20190408-90069-ro7pbv/libspatialite-4.3.0a
chmod -Rf +w /private/tmp/d20190408-90069-8ntclg
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/27a0e51936e01829d0a6f3c75a7fbcaf92bb133f/libspatialite/sqlite310.patch
Already downloaded: /Users/amalia/Library/Caches/Homebrew/downloads/6519ed0da29a84aadffcee29704e6990eb77896bf29d0d424cc81d07ac4e527c--sqlite310.patch
==> Verifying 6519ed0da29a84aadffcee29704e6990eb77896bf29d0d424cc81d07ac4e527c--sqlite310.patch checksum
==> Patching
cp -p /Users/amalia/Library/Caches/Homebrew/downloads/6519ed0da29a84aadffcee29704e6990eb77896bf29d0d424cc81d07ac4e527c--sqlite310.patch /private/tmp/libspatialite--patch-20190408-90069-1pj4tc5/sqlite310.patch
==> Applying sqlite310.patch
patch -g 0 -f -p1 -i /private/tmp/libspatialite--patch-20190408-90069-1pj4tc5/sqlite310.patch
patching file config.h.in
patching file configure
patching file configure.ac
patching file src/spatialite/virtualXL.c
patching file src/spatialite/virtualdbf.c
patching file src/spatialite/virtualshape.c
==> stat configure
16777220 8594478795 -rwxr-xr-x 1 amalia wheel 0 651938 "Apr  8 21:18:54 2019" "Apr  8 21:18:54 2019" "Apr  8 21:18:54 2019" "Apr  8 21:18:54 2019" 4194304 1280 0 configure
==> stat configure
16777220 8594478795 -rwxr-xr-x 1 amalia wheel 0 651852 "Apr  8 21:18:54 2019" "Apr  8 21:18:54 2019" "Apr  8 21:18:54 2019" "Apr  8 21:18:54 2019" 4194304 1280 0 configure
==> false
```

**Comment by amyspark** [comment]
@fxcoudert, it is an internal failure in the `activesupport` gem. It cannot copy ownership to the temporary file:

https://github.com/Homebrew/brew/blob/1c655916fe9a9fd46b73fc23f5f54d15d934b8f9/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.3/lib/active_support/core_ext/file/atomic.rb#L40-L46

```
amalia@Sakura:/usr/local/Homebrew $ brew install amyspark/dev-tap/libspatialite 
==> Installing libspatialite from amyspark/dev-tap
==> Downloading https://www.gaia-gis.it/gaia-sins/libspatialite-sources/libspatialite-4.3.0a.tar.gz
Already downloaded: /Users/amalia/Library/Caches/Homebrew/downloads/3ef5e810c67c101a7620c263b527c9f85676a2e101660b8a84cd7421d09a76a0--libspatialite-4.3.0a.tar.gz
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/27a0e51936e01829d0a6f3c75a7fbcaf92bb133f/libspatialit
Already downloaded: /Users/amalia/Library/Caches/Homebrew/downloads/6519ed0da29a84aadffcee29704e6990eb77896bf29d0d424cc81d07ac4e527c--sqlite310.patch
==> Patching
==> Applying sqlite310.patch
patching file config.h.in
patching file configure
patching file configure.ac
patching file src/spatialite/virtualXL.c
patching file src/spatialite/virtualdbf.c
patching file src/spatialite/virtualshape.c
==> stat configure
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.3/lib/active_support/core_ext/file/atomic.rb:43:in `chown'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.3/lib/active_support/core_ext/file/atomic.rb:43:in `block in atomic_write'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/tempfile.rb:295:in `open'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.3/lib/active_support/core_ext/file/atomic.rb:24:in `atomic_write'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:166:in `atomic_write'
/usr/local/Homebrew/Library/Homebrew/utils/inreplace.rb:35:in `block in inreplace'
/usr/local/Homebrew/Library/Homebrew/utils/inreplace.rb:23:in `each'
/usr/local/Homebrew/Library/Homebrew/utils/inreplace.rb:23:in `inreplace'
/usr/local/Homebrew/Library/Taps/amyspark/homebrew-dev-tap/Formula/libspatialite.rb:12:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:143:in `block (2 levels) in install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1130:in `block in brew'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2046:in `block (2 levels) in stage'
/usr/local/Homebrew/Library/Homebrew/utils.rb:474:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2045:in `block in stage'
/usr/local/Homebrew/Library/Homebrew/resource.rb:101:in `block in unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:171:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:55:in `block in run'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:55:in `chdir'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:55:in `run'
/usr/local/Homebrew/Library/Homebrew/resource.rb:170:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/resource.rb:96:in `unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:73:in `stage'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/forwardable.rb:202:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2021:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1125:in `brew'
/usr/local/Homebrew/Library/Homebrew/build.rb:114:in `block in install'
/usr/local/Homebrew/Library/Homebrew/utils.rb:474:in `with_env'
/usr/local/Homebrew/Library/Homebrew/build.rb:111:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:192:in `<main>'
Error: An exception occurred within a child process:
  Errno::EPERM: Operation not permitted @ chown_internal - ./.configure20190410-10123-1k5h05s
```

**Comment by amyspark** [comment]
cc @MikeMcQuaid because the last commit that involved this was #4913.

**Comment by amyspark** [comment]
Since @MikeMcQuaid suggested to file #6007 in Rails, I've had second thoughts about the fix. It's clearly intended as a sort of atomic permission copy -- clearly a half baked one is better in our use case, but the real problem comes from `patch`:

<blockquote>
patch creates new file, that's why it holds effective user credentials.
</blockquote>
(https://unix.stackexchange.com/questions/41181/patch-without-changing-owner-and-group)

Is there any way in which we can repair user permissions after a `patch`, or should I edit `inreplace` and restore permissions there if `atomic_write` breaks them?

**Comment by MikeMcQuaid** [comment]
> or should I edit `inreplace` and restore permissions there if `atomic_write` breaks them?

This seems like a good idea 👍
