### ISSUE TITLE
Cannot create more TTY in Catalina sandbox

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/brew#6546]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

# Bug description

Several formulas see their test fail on macOS Catalina, due to impossibility to allocate a new TTY. One example is PuTTY:

```
$ brew test --verbose putty
[…]
==> ./command.sh
spawn /usr/local/Cellar/putty/0.72/bin/puttygen -t rsa -b 4096 -q -o test.key
The system has no more ptys.  Ask your system administrator to create more.
    while executing
"spawn /usr/local/Cellar/putty/0.72/bin/puttygen -t rsa -b 4096 -q -o test.key"
    (file "./command.sh" line 3)
Error: putty: failed
```

This failure reproduces in the shell within `brew test`. However, if I execute the same Expect script outside the sandbox, it succeeds:

```
$ cat command.sh
#!/usr/bin/expect -f
set timeout -1
spawn /usr/local/Cellar/putty/0.72/bin/puttygen -t rsa -b 4096 -q -o test.key
expect -exact "Enter passphrase to save key: "
send -- "Homebrew
"
expect -exact "
Re-enter passphrase to verify: "
send -- "Homebrew
"
expect eof
$ ./command.sh 
spawn /usr/local/Cellar/putty/0.72/bin/puttygen -t rsa -b 4096 -q -o test.key
Enter passphrase to save key: 
Re-enter passphrase to verify: 
```

**Comment by fxcoudert** [comment]
Another example is `tintin`, where the same error is observed under pure Ruby. Running `brew test --verbose tintin` will lead to:

```
Error: tintin: failed
An exception occurred within a child process:
  RuntimeError: can't get Master/Slave device
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/tintin.rb:33:in `spawn'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/tintin.rb:33:in `block in <class:Tintin>'
```
