### ISSUE TITLE
devel should auto-upgrade if needed, like stable does

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/brew#668]
Unfortunately the devel spec won't auto-upgrade itself for some reason when it's fulfilling the go dependency, so the Sierra failure came back as soon as core upgraded rc5 -> rc6. (simulated on El Capitan by setting :yosemite)

```
iMac-TMP:homebrew-core joe$ brew install -s godep
go: This formula either does not compile or function as expected on OS X
versions newer than Yosemite due to an upstream incompatibility.
Error: An unsatisfied requirement failed this build.
iMac-TMP:homebrew-core joe$ brew outdated go
go (1.7rc5) < 1.7rc6
iMac-TMP:homebrew-core joe$ brew upgrade go
==> Upgrading 1 outdated package, with result:
go 1.7rc6
==> Upgrading go
==> Downloading https://storage.googleapis.com/golang/go1.7rc6.src.tar.gz
Already downloaded: /Users/joe/Library/Caches/Homebrew/go-1.7rc6.tar.gz
==> Downloading https://storage.googleapis.com/golang/go1.7rc6.darwin-amd64.tar.gz
Already downloaded: /Users/joe/Library/Caches/Homebrew/go--gobootstrap-1.7rc6.tar.gz
==> ./make.bash --no-clean
==> /usr/local/Cellar/go/1.7rc6/bin/go install -race std
==> Cloning https://go.googlesource.com/tools.git
Updating /Users/joe/Library/Caches/Homebrew/go--gotools--git
==> Checking out branch release-branch.go1.7
==> go build
==> Caveats
As of go 1.2, a valid GOPATH is required to use the `go get` command:
  https://golang.org/doc/code.html#GOPATH

You may wish to add the GOROOT-based install location to your PATH:
  export PATH=$PATH:/usr/local/opt/go/libexec/bin
==> Summary
🍺  /usr/local/Cellar/go/1.7rc6: 6,435 files, 250.6M, built in 36 seconds
iMac-TMP:homebrew-core joe$ brew install -s godep
==> Downloading https://github.com/tools/godep/archive/v74.tar.gz
Already downloaded: /Users/joe/Library/Caches/Homebrew/godep-74.tar.gz
==> go build -o /usr/local/Cellar/godep/74_1/bin/godep
🍺  /usr/local/Cellar/godep/74_1: 2 files, 8.6M, built in 1 second
```

**Comment by ilovezfs** [comment]
bump.

**Comment by MikeMcQuaid** [comment]
@ilovezfs You can implement this too, y'know 😉.

**Comment by ilovezfs** [comment]
I'm not the one who favors this solution ;)

**Comment by MikeMcQuaid** [comment]
`upgrade --devel` upgrades this, right?

**Comment by MikeMcQuaid** [comment]
@vladshablinsky Did you end up fixing this?

**Comment by vladshablinsky** [comment]
I'm not sure how I reproduce this one now.

**Comment by ilovezfs** [comment]
This is on 10.11 (so please forgive the perl):
```
bash-4.4$ pwd
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core
bash-4.4$ git reset --hard origin/master
HEAD is now at e420e60034 gtk-vnc: update 0.7.0 bottle.
bash-4.4$ brew uninstall go godep --ignore-dependencies -f
bash-4.4$ git checkout 9476215 -- Formula/go.rb Formula/godep.rb
bash-4.4$ perl -p -i -e 's/(MaximumMacOSRequirement => ):el_capitan/\1:yosemite/' Formula/go.rb
bash-4.4$ brew instal -s godep
go: This formula either does not compile or function as expected on macOS
versions newer than Yosemite due to an upstream incompatibility.
Error: An unsatisfied requirement failed this build.
bash-4.4$ brew instal -s go
go: This formula either does not compile or function as expected on macOS
versions newer than Yosemite due to an upstream incompatibility.
Error: An unsatisfied requirement failed this build.
bash-4.4$ brew instal --devel go
==> Using the sandbox
==> Downloading https://storage.googleapis.com/golang/go1.7rc5.src.tar.gz
Already downloaded: /Users/joe/Library/Caches/Homebrew/go-1.7rc5.tar.gz
==> Downloading https://storage.googleapis.com/golang/go1.7rc5.darwin-amd64.tar.gz
Already downloaded: /Users/joe/Library/Caches/Homebrew/go--gobootstrap-1.7rc5.tar.gz
==> ./make.bash --no-clean
==> /usr/local/Cellar/go/1.7rc5/bin/go install -race std
==> Cloning https://go.googlesource.com/tools.git
Updating /Users/joe/Library/Caches/Homebrew/go--gotools--git
==> Checking out branch release-branch.go1.7
==> go build
==> Caveats
As of go 1.2, a valid GOPATH is required to use the `go get` command:
  https://golang.org/doc/code.html#GOPATH

You may wish to add the GOROOT-based install location to your PATH:
  export PATH=$PATH:/usr/local/opt/go/libexec/bin
==> Summary
🍺  /usr/local/Cellar/go/1.7rc5: 6,435 files, 250.6M, built in 37 seconds
bash-4.4$ brew instal -s godep
==> Using the sandbox
==> Downloading https://github.com/tools/godep/archive/v74.tar.gz
Already downloaded: /Users/joe/Library/Caches/Homebrew/godep-74.tar.gz
==> go build -o /usr/local/Cellar/godep/74_1/bin/godep
🍺  /usr/local/Cellar/godep/74_1: 3 files, 8.6M, built in 1 second
bash-4.4$ brew uninstall godep
Uninstalling /usr/local/Cellar/godep/74_1... (3 files, 8.6M)
bash-4.4$ git checkout f98619c -- Formula/go.rb Formula/godep.rb
bash-4.4$ perl -p -i -e 's/(MaximumMacOSRequirement => ):el_capitan/\1:yosemite/' Formula/go.rb
bash-4.4$ brew instal -s godep
go: This formula either does not compile or function as expected on macOS
versions newer than Yosemite due to an upstream incompatibility.
Error: An unsatisfied requirement failed this build.
bash-4.4$ brew outdated go
go (1.7rc5) < 1.7rc6
bash-4.4$ brew upgrade go
==> Upgrading 1 outdated package, with result:
go 1.7rc6
==> Upgrading go 
==> Using the sandbox
==> Downloading https://storage.googleapis.com/golang/go1.7rc6.src.tar.gz
Already downloaded: /Users/joe/Library/Caches/Homebrew/go-1.7rc6.tar.gz
==> Downloading https://storage.googleapis.com/golang/go1.7rc6.darwin-amd64.tar.gz
Already downloaded: /Users/joe/Library/Caches/Homebrew/go--gobootstrap-1.7rc6.tar.gz
==> ./make.bash --no-clean
==> /usr/local/Cellar/go/1.7rc6/bin/go install -race std
==> Cloning https://go.googlesource.com/tools.git
Updating /Users/joe/Library/Caches/Homebrew/go--gotools--git
==> Checking out branch release-branch.go1.7
==> go build
==> Caveats
As of go 1.2, a valid GOPATH is required to use the `go get` command:
  https://golang.org/doc/code.html#GOPATH

You may wish to add the GOROOT-based install location to your PATH:
  export PATH=$PATH:/usr/local/opt/go/libexec/bin
==> Summary
🍺  /usr/local/Cellar/go/1.7rc6: 6,436 files, 250.6M, built in 37 seconds
bash-4.4$ brew instal -s godep
==> Using the sandbox
==> Downloading https://github.com/tools/godep/archive/v74.tar.gz
Already downloaded: /Users/joe/Library/Caches/Homebrew/godep-74.tar.gz
==> go build -o /usr/local/Cellar/godep/74_1/bin/godep
🍺  /usr/local/Cellar/godep/74_1: 3 files, 8.6M, built in 1 second
bash-4.4$
```

**Comment by vladshablinsky** [comment]
First of all let's take a look at the stack trace.

```
go: This formula either does not compile or function as expected on macOS
versions newer than El Capitan due to an upstream incompatibility.
Error: An unsatisfied requirement failed this build.
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:390:in `check_requirements'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:349:in `compute_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:134:in `verify_deps_exist'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:127:in `prelude'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:305:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:199:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:199:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:199:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'

```

The reason this bug occurs is that we don't care about specs while checking for requirements and dependencies. In the specific case in the comment above we don't take in account that it's `devel` version which is installed and try to check requirements for `stable` spec of `go` which is not satisfied on `sierra`. If `devel` `go` is up-to date, we skip the requirement check for it because `Formula#installed?` handles all the specs and returns true for up-to-date `go`. For outdated go we don't skip check and end up checking the requirement of `stable` even though having `devel` installed. So, this is the reason.

* Check that fails for outdated formula (any spec) https://github.com/Homebrew/brew/blob/master/Library/Homebrew/formula_installer.rb#L377

*  [Here we call `FormulaInstaller#expand_requirements`](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/formula_installer.rb#L402-L403)

```ruby
def expand_requirements
    unsatisfied_reqs = Hash.new { |h, k| h[k] = [] }
    deps = []
    formulae = [formula]

    while f = formulae.pop
      f.recursive_requirements do |dependent, req|
        build = effective_build_options_for(dependent)

        #... several ifs
        #
        #...
        else
          unsatisfied_reqs[dependent] << req
        end
      end
    end

    deps = Dependency.merge_repeats(deps)
    [unsatisfied_reqs, deps]
end
```

and [`recursive_requirements`](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/requirement.rb#L209) don't care about installed `spec`'s while calling [`recursive_dependencies`](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dependency.rb#L77) to get requirements.

So, right now we only use `stable` spec for requirements of dependents for some formula we install.


One more tricky thing caused by this behaviour happens when there are no unsatisfied requirements for `devel` outdated dependent formula. Let's suppose we install `godep` that depends on `go` and have `go-1.7rc5` installed and outdated (`go-1.7rc6` is the latest `devel` and go-1.6.3 is the latest `stable`). Guess what Homebrew does. Well, it thinks that `go` dependency is not satisfied and installs us `stable` `go`. So after that we're left with **downgraded** go.

After we discussed this with @ilovezfs there we came up with some ideas, but let's discuss them a bit more before writing code -- there still are tricky cases.

Basically we should not downgrade dependencies. But how do we achieve that?

1. What if we have `devel` version installed and outdated, but `stable` is still too outdated so it's less than old `devel`:
  * `go`-stable : `1.6.3`
  * `go`-devel : `1.7rc6`
  * `go`-devel outdated: `1.7rc5` <-- installed

There are two possible options when we install `godep`. For now if we skip `sierra` requirements check, we get `stable` go installed and linked, however we might want to have `devel` version instlalled. We can either **upgrade** go-devel or **leave** it as it is. Which one is better?

2. Supposing `devel` is always greater than `stable` what should we do in this situation:
  * `go`-stable : `1.7.6`
  * `go`-devel : `1.8rc1`
  * `go`-devel outdated: `1.7rc5` <-- installed.

Do we install `stable` or `devel` to satisfy dependency?

3. What do we do with requirements for different specs? It's good to know which requirement we will use: `stable` or `devel`. So we need to know the answer to the two questions above and resolve requirements according to what spec we choose to install fulfilling some dependency.

@MikeMcQuaid maybe you leave some thoughts when you have spare time?

**Comment by MikeMcQuaid** [comment]
> We can either upgrade go-devel or leave it as it is. Which one is better?

I'd say upgrade `go-devel`. That's more consistent with how stable is handled.

> Do we install stable or devel to satisfy dependency?

I think either is fine but I'd probably lean towards upgrading to stable for binary packages and, well, stability.

> What do we do with requirements for different specs? It's good to know which requirement we will use: stable or devel. So we need to know the answer to the two questions above and resolve requirements according to what spec we choose to install fulfilling some dependency.

I think we'd ideally autoinstall devel (or even HEAD) if there's stable-only requirements that prevent installation but not devel. That said, I think manual intervention is fine for this case as long as the main issue noted in here (1) is addressed.

**Comment by MikeMcQuaid** [comment]
There's been no activity on this for over a year so I'm going to close this out.
