### ISSUE TITLE
brew upgrade fails to work after upgrade brew from 20cf2afed to 1b926389a

### ISSUE THREAD

**Issue by laggardkernel** [Homebrew/brew#6739]
Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)
`brew upgrade mkcert`, or any other outdated packages. And there is not any output, even with `--verbose`.

## What happened (include command output)
```
~/.local/share
❯ brew config
HOMEBREW_VERSION: 2.1.16-67-g1b92638
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 1b926389ad78ebdecf846844d7604da9f155eb78
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core.git
Core tap HEAD: a74f2c803d70f1b7b5e50aa1d3be4cebceab162c
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_FORCE_BREWED_CURL: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_NO_ANALYTICS: 1
HOMEBREW_NO_AUTO_UPDATE: 1
HOMEBREW_NO_INSTALL_CLEANUP: 1
HOMEBREW_VISUAL: nvim
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 10.0 build 1000
Git: 2.24.0 => /usr/local/bin/git
Curl: 7.66.0 => /usr/local/opt/curl/bin/curl
Java: 1.8.0_232
macOS: 10.13.6-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11

~/.local/share
❯ brew doctor
Your system is ready to brew.

~/.local/share
❯ brew outdated
ansifilter (2.14) < 2.15
erlang (22.1.5) < 22.1.7
harfbuzz (2.6.1, 2.6.2) < 2.6.4
mysql (8.0.18) < 8.0.18_1
qt (5.13.1) < 5.13.2

~/.local/share
❯ brew upgrade ansifilter

~/.local/share
❯
```

It seems some commits broke it. After I reset the brew repo back to `20cf2afed` from the latest `1b926389a`. The `brew upgrade` command works again.

**Comment by kbd** [comment]
I'm getting something similar:

```bash
$ git --version
git version 2.23.0
$ brew info git | head -1
git: stable 2.24.0 (bottled), HEAD
$ brew upgrade git  # does nothing
...
/usr/local/Homebrew[master]$ git rev-parse @
1b926389ad78ebdecf846844d7604da9f155eb78
```

**Comment by joemiller** [comment]
looks like the `exit` on line 84 that was added a couple day ago in https://github.com/Homebrew/brew/commit/9d2cb8e9b3fcce894e683b7b32d3d82b268668c8

```console
$ brew upgrade -d azure-cli
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/azure-cli.rb
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:84:in `exit'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:84:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```
