### ISSUE TITLE
`brew uninstall` produces an error

### ISSUE THREAD

**Issue by miketheman** [Homebrew/brew#7540]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

During a couple of packages I was uninstalling, I received an error message. I think it uninstalls the package , but produces the error message repeatedly, so I figured I'd report it, because I couldn't see any other issues for this.

## What happened (include command output)

An error message of: `Error: no implicit conversion of nil into Array` was returned

<details>
  <summary>Command output</summary>

```shellsession
$ brew uninstall unar
Uninstalling /usr/local/Cellar/unar/1.10.1... (79 files, 13.3MB)
Error: no implicit conversion of nil into Array
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:95:in `-'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:95:in `block (3 levels) in uninstall'
/usr/local/Homebrew/Library/Homebrew/keg.rb:362:in `block in lock'
/usr/local/Homebrew/Library/Homebrew/lock_file.rb:31:in `with_lock'
/usr/local/Homebrew/Library/Homebrew/keg.rb:358:in `lock'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:71:in `block (2 levels) in uninstall'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:60:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:60:in `block in uninstall'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:46:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:46:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

</details>

## What you expected to happen

No error message.

## Step-by-step reproduction instructions (by running `brew` commands)

I was able to reproduce this with reinstalling and uninstalling the package again, and tried another package:

<details>

```shellsession
$ brew install unar && brew uninstall unar
==> Downloading https://homebrew.bintray.com/bottles/unar-1.10.1.catalina.bottle.1.tar.gz
Already downloaded: /Users/miketheman/Library/Caches/Homebrew/downloads/8793175367f1a6e5499a41d8e8bb7cc0d91620994b8486632154464e2edade82--unar-1.10.1.catalina.bottle.1.tar.gz
==> Pouring unar-1.10.1.catalina.bottle.1.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/unar/1.10.1: 79 files, 13.3MB
Uninstalling /usr/local/Cellar/unar/1.10.1... (79 files, 13.3MB)
Error: no implicit conversion of nil into Array
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:95:in `-'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:95:in `block (3 levels) in uninstall'
/usr/local/Homebrew/Library/Homebrew/keg.rb:362:in `block in lock'
/usr/local/Homebrew/Library/Homebrew/lock_file.rb:31:in `with_lock'
/usr/local/Homebrew/Library/Homebrew/keg.rb:358:in `lock'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:71:in `block (2 levels) in uninstall'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:60:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:60:in `block in uninstall'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:46:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:46:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

</details>

I repeated this with the `trash` package as well, similar results.

The error appears to stem from this line:

https://github.com/Homebrew/brew/blob/270fd422dc2a9223e92b56209c1fc200a04e3c42/Library/Homebrew/cmd/uninstall.rb#L95

My guess is that `paths` is `nil` at this point, but am not certain.

## Output of `brew config` and `brew doctor` commands

<pre>
$ brew config
HOMEBREW_VERSION: 2.2.15-47-g270fd42
ORIGIN: https://github.com/Homebrew/brew
HEAD: 270fd422dc2a9223e92b56209c1fc200a04e3c42
Last commit: 22 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4bc91aaa93b2c4d57103e275b5e8d0152554e3f5
Core tap last commit: 33 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.64wgJsmqST/org.macosforge.xquartz:0
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 4
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.26.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.0_77, 1.7.0_80
macOS: 10.15.4-x86_64
CLT: 11.4.1.0.1.1586360307
Xcode: 11.4.1
XQuartz: 2.7.11 => /opt/X11

$ brew doctor
Your system is ready to brew.
</pre>

**Comment by miketheman** [comment]
Possibly a result of this recent change: https://github.com/Homebrew/brew/pull/7526 by
@MikeMcQuaid ?
