### ISSUE TITLE
Error: Invalid tap name '...'

### ISSUE THREAD

**Issue by giucal** [Homebrew/brew#7734]
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?

  In fact, `brew doctor` fails with the same error.

- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

    brew upgrade youtube-dl

## What happened (include command output)

It failed with the error:

```
Error: Invalid tap name 'filippo.io/homebrew-age'
```
## What you expected to happen

`youtube-dl` to be upgraded.

## Step-by-step reproduction instructions (by running `brew` commands)

See above.

## Output of `brew config` and `brew doctor` commands

```
% brew config
HOMEBREW_VERSION: 2.4.0-33-g91b4d45
ORIGIN: https://github.com/Homebrew/brew
HEAD: 91b4d450703bcc2de6dce22eb5fdecb5a843f92e
Last commit: 22 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8b7b8849a93ffa87e2b6bc627a00c40a27885015
Core tap last commit: 62 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.Cw3ZKMohiP/org.macosforge.xquartz:0
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 8
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_1/bin/ruby
Clang: 10.0 build 1001
Git: 2.26.2 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 14, 12.0.1
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11
% brew doctor
Error: Invalid tap name 'filippo.io/homebrew-age'
```

---

This fails too:

```
brew untap filippo.io/homebrew-age
```

And so do other commands, such as `list` and `search`.

The issue may be related with the commit fe75934? See:

```
% brew doctor --debug
==> Checking check_access_directories
==> Checking check_brew_git_origin
==> Checking check_casktap_git_origin
==> Checking check_clt_minimum_version
==> Checking check_clt_up_to_date
==> Checking check_coretap_git_branch
==> Checking check_coretap_git_origin
==> Checking check_deleted_formula
==> Checking check_deprecated_caskroom_taps
Error: Invalid tap name 'filippo.io/homebrew-age'
/usr/local/Homebrew/Library/Homebrew/tap.rb:38:in `fetch'
/usr/local/Homebrew/Library/Homebrew/tap.rb:582:in `block (2 levels) in each'
/usr/local/Homebrew/Library/Homebrew/tap.rb:581:in `each'
/usr/local/Homebrew/Library/Homebrew/tap.rb:581:in `block in each'
/usr/local/Homebrew/Library/Homebrew/tap.rb:580:in `each'
/usr/local/Homebrew/Library/Homebrew/tap.rb:580:in `each'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/diagnostic.rb:350:in `select'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/diagnostic.rb:350:in `check_deprecated_caskroom_taps'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:61:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:53:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:53:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

**Comment by MikeMcQuaid** [comment]
> The issue may be related with the commit [fe75934](https://github.com/Homebrew/brew/commit/fe75934acf048046142781c08c7c9fadd87467a0)? See:

Yup, my bad. New PR in https://github.com/Homebrew/brew/pull/7735
