### ISSUE TITLE
trying to install homebrew on Apple development Kit Mac Mini

### ISSUE THREAD

**Issue by zdavatz** [Homebrew/brew#7890]
Processor: Apple A12Z Bionic
MacOS: 11.0 Beta
```
zdavatz@Zenos-Mac ~ % /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
Password:
==> You are using macOS 11.0.
==> We do not provide support for this pre-release version.
This installation may not succeed.
After installation, you will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew\'s GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this pre-release version.

==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew

Press RETURN to continue or any other key to abort
==> Downloading and installing Homebrew...
HEAD is now at 6d27367c7 Merge pull request #7887 from vidusheeamoli/set-utils-files-to-true
Traceback (most recent call last):
	19: from /usr/local/Homebrew/Library/Homebrew/brew.rb:23:in `<main>'
	18: from /usr/local/Homebrew/Library/Homebrew/brew.rb:23:in `require_relative'
	17: from /usr/local/Homebrew/Library/Homebrew/global.rb:132:in `<top (required)>'
	16: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	15: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	14: from /usr/local/Homebrew/Library/Homebrew/tap.rb:5:in `<top (required)>'
	13: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	12: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	11: from /usr/local/Homebrew/Library/Homebrew/readall.rb:3:in `<top (required)>'
	10: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 9: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 8: from /usr/local/Homebrew/Library/Homebrew/formula.rb:20:in `<top (required)>'
	 7: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /usr/local/Homebrew/Library/Homebrew/linkage_checker.rb:6:in `<top (required)>'
	 4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 2: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fiddle.rb:2:in `<top (required)>'
	 1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': dlopen(/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin20/fiddle.bundle, 0x0009): symbol '_ffi_prep_closure' not found, expected in flat namespace by '/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin20/fiddle.bundle' - /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin20/fiddle.bundle (LoadError)
Failed during: /usr/local/bin/brew update --force
```

**Comment by jonchang** [comment]
> Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this pre-release version.

**Comment by zdavatz** [comment]
I am not asking for help. I am just showing output. So please be precise.

**Comment by MikeMcQuaid** [comment]
@zdavatz You need to fix your own issues instead of opening issues on GitHub.

**Comment by zdavatz** [comment]
I will, but first I need to share them in the right place.

**Comment by iMichka** [comment]
The point that this issue tracker is not the right place to share this.

We have maintainers that are already working on fixes for these issues. Once we have made enough progress, we will make a release supporting Big Sur. At this point we will be supporting it officially.
And then only you will be able to report issues if they have not been fixed.

Meanwhile, issues like you opened are just "useless" noise for us, distracting us from our work to gets things shipped quickly.

This is why we have this message:
```
==> We do not provide support for this pre-release version.
This installation may not succeed.
After installation, you will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew\'s GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this pre-release version.
```

We could reword it from `Please create pull requests instead of asking for help` to `Please create pull requests instead of asking for help and/or sharing issues` to be more clear (I am unsure about the best wording here).

**Comment by zdavatz** [comment]
Ok, thank you. Let me know when I can test.

**Comment by Bo98** [comment]
> Let me know when I can test.

Perhaps the next beta. The current beta has major bugs in system Ruby that have been reported to Apple.

**Comment by zdavatz** [comment]
Installed Ruby Version on this Apple Dev machine is `ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.arm64e-darwin20]`

**Comment by zdavatz** [comment]
Also if any Homebrew-Dev has a Github sponsorship button on his page I am ready to sponsor. Please let me know. I done so as well for this Ruby-Date Issue: https://github.com/ruby/date/issues/20

**Comment by iMichka** [comment]
We have a project wide sponsoring page: https://github.com/sponsors/Homebrew

**Comment by zdavatz** [comment]
Thank you, done!

**Comment by zdavatz** [comment]
https://github.com/Homebrew/brew/issues/7857 @clau is doing a great job! I started sponsoring her.

**Comment by claui** [comment]
@zdavatz I can’t thank you enough!

I’m just a casual contributor so if others read this:
**Please sponsor Homebrew,** not me!
