### ISSUE TITLE
Python pip install with --target option doesn't work

### ISSUE THREAD

**Issue by chhantyal** [Homebrew/brew#837]
### Bug reports:

`pip` has nice option to specify where a package should be installed.
```
pip install requests --target python_packages/
``` 
With Homebrew installed Python and pip, this doesn't work anymore.

```
 pip install requests -t python_packages/
Collecting requests
  Using cached requests-2.11.1-py2.py3-none-any.whl
Installing collected packages: requests
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 831, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 1032, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "/usr/local/lib/python2.7/site-packages/pip/locations.py", line 153, in distutils_scheme
    i.finalize_options()
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 264, in finalize_options
    "must supply either home or prefix/exec-prefix -- not both"
DistutilsOptionError: must supply either home or prefix/exec-prefix -- not both
```

Issue with `--user` option is mentioned in docs (though it's not corret, see #821 ), but not `--target`.

**Comment by MikeMcQuaid** [comment]
CC @tdsmith for thoughts.

**Comment by tdsmith** [comment]
cf #821

**Comment by MikeMcQuaid** [comment]
Closing this and https://github.com/Homebrew/brew/pull/821 but @tdsmith feel free to reopen.

**Comment by dagheyman** [comment]
Same issue.

**Comment by pointtonull** [comment]
@tdsmith ; this mean we are happy with brew not longer being the recommended way to install python, I guess.

**Comment by tdsmith** [comment]
pyenv is good!
