### ISSUE TITLE
Error: undefined method `named' for #<OptionParser:0x00007f96d03f6c18>

### ISSUE THREAD

**Issue by gMan1990** [Homebrew/brew#8721]
```plain
> brew --version
Homebrew 2.2.10
Homebrew/homebrew-core (git revision c14db; last commit 2020-03-10)

> brew services list
Error: undefined method `named' for #<OptionParser:0x00007f96d03f6c18>
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/services_cli.rb:67:in `run!'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:48:in `services'
/usr/local/Homebrew/Library/Homebrew/brew.rb:103:in `<main>'
```

**Comment by Rylan12** [comment]
You're running a very outdated version of Homebrew (we're on 2.5.1 now). Run `brew update` and try again. If there is still an issue, feel free to reopen.

Also, please always fill out the issue template.
