### ISSUE TITLE
Formula that use shell_profile are failing 

### ISSUE THREAD

**Issue by WillAbides** [Homebrew/brew#875]
### Bug reports:

Since #201 was merged, formula that use the shell_profile method are failing.  Two formula that I have seen this on are nvm and gnupg.

This is the error from nvm:

```
  brew install nvm
==> Using the sandbox
==> Downloading https://github.com/creationix/nvm/archive/v0.31.7.tar.gz
==> Downloading from https://codeload.github.com/creationix/nvm/tar.gz/v0.31.7
######################################################################## 100.0%
Error: undefined local variable or method `shell_profile' for #<Formulary::FormulaNamespace04637aebbac9f42aa8b16bb58c3b99b8::Nvm:0x007f991680dca0>
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/nvm.rb:24:in `caveats'
/usr/local/Library/Homebrew/caveats.rb:12:in `caveats'
/usr/local/Library/Homebrew/caveats.rb:29:in `empty?'
/usr/local/Library/Homebrew/formula_installer.rb:484:in `caveats'
/usr/local/Library/Homebrew/formula_installer.rb:513:in `finish'
/usr/local/Library/Homebrew/cmd/install.rb:273:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:150:in `block in install'
/usr/local/Library/Homebrew/cmd/install.rb:150:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:150:in `install'
/usr/local/Library/Homebrew/brew.rb:91:in `<main>'
```

**Comment by gregory-nisbet** [comment]
`shell_profile` now resides in `Utils.Shell`. It was moved there with some other functions that handle things like quoting. We could include `Utils.Shell` in the `Formula` module.

I have a patch here.

https://github.com/Homebrew/brew/pull/876

**Comment by mistydemeo** [comment]
This is now fixed; thanks for your patience!
