### ISSUE TITLE
All commands broken with "uninitialized constant URL::T (NameError)"

### ISSUE THREAD

**Issue by gkze** [Homebrew/brew#8908]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Hi, my Homebrew installation suddenly broke this morning. None of the commands seem to work, as they all fail with the same stack trace.

I did some investigating, and it seems that Homebrew/brew@3b94443 is the one to introduce this bug. It's strange because it has nothing to do with the stack trace above, but if I checkout Homebrew to the commit immediately before it (Homebrew/brew@3095fbc), Homebrew starts working fine again.

## What happened (include command output)

When I ran `brew update` this morning, I got the following stack trace:

<details>
  <summary>Command output</summary>

```
  Traceback (most recent call last):
	21: from /usr/local/Homebrew/Library/Homebrew/brew.rb:30:in `<main>'
	20: from /usr/local/Homebrew/Library/Homebrew/brew.rb:30:in `require_relative'
	19: from /usr/local/Homebrew/Library/Homebrew/global.rb:51:in `<top (required)>'
	18: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	17: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	16: from /usr/local/Homebrew/Library/Homebrew/cli/args.rb:3:in `<top (required)>'
	15: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	14: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	13: from /usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:5:in `<top (required)>'
	12: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	11: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	10: from /usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:4:in `<top (required)>'
	 9: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 8: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 7: from /usr/local/Homebrew/Library/Homebrew/cask/cask.rb:5:in `<top (required)>'
	 6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 4: from /usr/local/Homebrew/Library/Homebrew/cask/dsl.rb:23:in `<top (required)>'
	 3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 2: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 1: from /usr/local/Homebrew/Library/Homebrew/cask/url.rb:7:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/cask/url.rb:8:in `<class:URL>': uninitialized constant URL::T (NameError)
```

</details>

## What you expected to happen

I expected the normal brew update process to take place.

## Step-by-step reproduction instructions (by running `brew` commands)

Be on the latest Homebrew commit (https://github.com/Homebrew/brew/commit/b8a93279fd31b0569a9046f61df0da0121ce4df5)

## Output of `brew config` and `brew doctor` commands

<details>
<summary>brew config</summary>

```
Traceback (most recent call last):
	21: from /usr/local/Homebrew/Library/Homebrew/brew.rb:30:in `<main>'
	20: from /usr/local/Homebrew/Library/Homebrew/brew.rb:30:in `require_relative'
	19: from /usr/local/Homebrew/Library/Homebrew/global.rb:51:in `<top (required)>'
	18: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	17: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	16: from /usr/local/Homebrew/Library/Homebrew/cli/args.rb:3:in `<top (required)>'
	15: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	14: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	13: from /usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:5:in `<top (required)>'
	12: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	11: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	10: from /usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:4:in `<top (required)>'
	 9: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 8: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 7: from /usr/local/Homebrew/Library/Homebrew/cask/cask.rb:5:in `<top (required)>'
	 6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 4: from /usr/local/Homebrew/Library/Homebrew/cask/dsl.rb:23:in `<top (required)>'
	 3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 2: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 1: from /usr/local/Homebrew/Library/Homebrew/cask/url.rb:7:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/cask/url.rb:8:in `<class:URL>': uninitialized constant URL::T (NameError)
```

</details>

<details>
<summary>brew doctor</summary>

```
Traceback (most recent call last):
	21: from /usr/local/Homebrew/Library/Homebrew/brew.rb:30:in `<main>'
	20: from /usr/local/Homebrew/Library/Homebrew/brew.rb:30:in `require_relative'
	19: from /usr/local/Homebrew/Library/Homebrew/global.rb:51:in `<top (required)>'
	18: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	17: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	16: from /usr/local/Homebrew/Library/Homebrew/cli/args.rb:3:in `<top (required)>'
	15: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	14: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	13: from /usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:5:in `<top (required)>'
	12: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	11: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	10: from /usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:4:in `<top (required)>'
	 9: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 8: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 7: from /usr/local/Homebrew/Library/Homebrew/cask/cask.rb:5:in `<top (required)>'
	 6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 4: from /usr/local/Homebrew/Library/Homebrew/cask/dsl.rb:23:in `<top (required)>'
	 3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 2: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 1: from /usr/local/Homebrew/Library/Homebrew/cask/url.rb:7:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/cask/url.rb:8:in `<class:URL>': uninitialized constant URL::T (NameError)
```

</details>

**Comment by ToniRib** [comment]
+1. This is happening to me also.

**Comment by gkze** [comment]
Seems like the current solution is to uninstall the system Sorbet.https://github.com/Homebrew/discussions/discussions/53 https://github.com/Homebrew/discussions/discussions/56

**Comment by reitermarkus** [comment]
Did https://github.com/Homebrew/brew/pull/8909 fix this?

**Comment by Rylan12** [comment]
I did not have system sorbet installed and was still experiencing this. #8909 alone didn't seem to fix it but manually installing and uninstalling the system `sorbet-runtime` gem did the trick for me.

**Comment by gkze** [comment]
[This solution](https://github.com/Homebrew/discussions/discussions/56#discussioncomment-95641) worked for me - if others can confirm I'm happy to close this out.

**Comment by MikeMcQuaid** [comment]
Think we're good for now, thanks all and @reitermarkus for the fix.
