### ISSUE TITLE
uninitialized constant SystemCommand::Predicable

### ISSUE THREAD

**Issue by NoahCardoza** [Homebrew/brew#8924]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Run `brew`. No matter how I call brew I get this output. 

## What happened (include command output)

`/usr/local/Homebrew/Library/Homebrew/system_command.rb:30:in `<class:SystemCommand>': uninitialized constant SystemCommand::Predicable (NameError)`

<details>
  <summary>Command output</summary>
  <pre>

```Traceback (most recent call last):
	18: from /usr/local/Homebrew/Library/Homebrew/brew.rb:30:in `<main>'
	17: from /usr/local/Homebrew/Library/Homebrew/brew.rb:30:in `require_relative'
	16: from /usr/local/Homebrew/Library/Homebrew/global.rb:48:in `<top (required)>'
	15: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	14: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	13: from /usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:3:in `<top (required)>'
	12: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	11: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	10: from /usr/local/Homebrew/Library/Homebrew/resource.rb:3:in `<top (required)>'
	 9: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 8: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 7: from /usr/local/Homebrew/Library/Homebrew/download_strategy.rb:5:in `<top (required)>'
	 6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 4: from /usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:4:in `<top (required)>'
	 3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 2: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 1: from /usr/local/Homebrew/Library/Homebrew/system_command.rb:28:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:30:in `<class:SystemCommand>': uninitialized constant SystemCommand::Predicable (NameError)```
```
  </pre>
</details>

## What you expected to happen

Brew to run normally.

## Step-by-step reproduction instructions (by running `brew` commands)

`brew`

## Output of `brew config` and `brew doctor` commands

<pre>
I can't run `brew config`. I get the same error.
</pre>

**Comment by NoahCardoza** [comment]
Seems to have been fixed by updating it via the install script: ` $ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)" `
