### ISSUE TITLE
Homebrew for SCRCPY not working on Huawei P30 Lite device

### ISSUE THREAD

**Issue by ixlatall** [Homebrew/brew#8937]
# Bug report

--------
Hey guys. I installed scrcpy on my 2012 Macbook Pro (High Sierra). It works flawlessly with my Moto G7 but I am getting the following results with my Huawei P30 Lite. (I have debugging and ADB turned on, and I've tried every combination I can think of with debugging and File Transfer options.

Can anyone help please?
--------

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem? YES
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem? YES
- [x] ran `brew config` and `brew doctor` and included their output with your issue? YES

## What you were trying to do (and why)

Install scrcpy on my 2012 Macbook Pro (High Sierra) to view my android screens (Moto G7 and Huawei P30 Lite) on the Macbook.

## What happened (include command output)

Moto G7 worked flawlessly and Huawei P30 Lite failed repeatedly.

<details>
  This format is over my head.  I'm not sure what you are asking here.  However, please see the entire code output at the end below.  
  
## What you expected to happen

To be able to see and control the screen from my android devices on my Macbook pro.

## Step-by-step reproduction instructions (by running `brew` commands)

FOR EACH DEVICE
1.	Enabled the USB debugging settings in the Developer options in my Android device.

ONCE
2.	Went to Spotlight on my Mac and opened Terminal.
3.	Installed Homebrew by entering:
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)" 
4.	Entered the command “brew cask install android-platform-tools” 
5.	Installed Scrcpy by entering the command “brew install scrcpy” 

FOR EACH DEVICE
6.	Plugged in my Android device using a USB cable.
7.	Allowed USB Debugging confirmation on the device.
8.	Entered the command “scrcpy” in the Terminal

## Output of `brew config` and `brew doctor` commands

After a successful installation, I received the following code results when trying to connect and view my devices on my Macbook (I intentionally separated each attempt for easier reading):
 
You can install adb from Homebrew Cask:
  brew cask install android-platform-tools

GeForce:~ alixa$ scrcpy
2020-10-16 22:14:02.108 scrcpy[70918:1896905] INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
* daemon not running; starting now at tcp:5037
* daemon started successfully
adb: error: failed to get feature set: no devices/emulators found
2020-10-16 22:14:02.284 scrcpy[70918:1896905] ERROR: "adb push" returned with value 1

GeForce:~ alixa$ scrcpy
2020-10-16 22:14:59.409 scrcpy[70931:1897212] INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
/usr/local/Cellar/scrcpy/1.16/share/s...ed. 60.2 MB/s (33622 bytes in 0.001s)
[server] INFO: Device: motorola moto g(7) (Android 9)
2020-10-16 22:15:01.708 scrcpy[70931:1897212] INFO: Renderer: metal
2020-10-16 22:15:01.713 scrcpy[70931:1897212] INFO: Initial texture: 1080x2264
2020-10-16 22:15:16.480 scrcpy[70931:1897212] WARN: Device disconnected

GeForce:~ alixa$ scrcpy
2020-10-16 22:17:30.985 scrcpy[70958:1898168] INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
adb: error: failed to get feature set: no devices/emulators found
2020-10-16 22:17:30.992 scrcpy[70958:1898168] ERROR: "adb push" returned with value 1

GeForce:~ alixa$ scrcpy
2020-10-16 22:17:50.261 scrcpy[70962:1898236] INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
adb: error: failed to get feature set: no devices/emulators found
2020-10-16 22:17:50.268 scrcpy[70962:1898236] ERROR: "adb push" returned with value 1

GeForce:~ alixa$ scrcpy
2020-10-16 22:18:23.325 scrcpy[70985:1898590] INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
/usr/local/Cellar/scrcpy/1.16/share/s...ed. 77.3 MB/s (33622 bytes in 0.000s)
[server] INFO: Device: HUAWEI MAR-LX3A (Android 10)
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffc0e
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:2023)
	at android.media.MediaCodec.configure(MediaCodec.java:1951)
	at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:205)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:84)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:55)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:76)
	at com.genymobile.scrcpy.Server.main(Server.java:225)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
[server] ERROR: The hardware encoder is not able to encode at the given definition.
[server] ERROR: Try with a lower definition:
[server] ERROR:     scrcpy -m 1024
2020-10-16 22:18:26.155 scrcpy[70985:1898590] INFO: Renderer: metal
2020-10-16 22:18:26.161 scrcpy[70985:1898590] INFO: Initial texture: 1080x2312
2020-10-16 22:18:26.493 scrcpy[70985:1898590] WARN: Device disconnected

GeForce:~ alixa$ scrcpy
2020-10-16 22:18:51.020 scrcpy[71003:1898888] INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
adb: error: failed to get feature set: no devices/emulators found
2020-10-16 22:18:51.029 scrcpy[71003:1898888] ERROR: "adb push" returned with value 1

GeForce:~ alixa$ scrcpy
2020-10-16 22:19:23.963 scrcpy[71019:1899189] INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
/usr/local/Cellar/scrcpy/1.16/share/s...ed. 76.6 MB/s (33622 bytes in 0.000s)
[server] INFO: Device: HUAWEI MAR-LX3A (Android 10)
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffc0e
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:2023)
	at android.media.MediaCodec.configure(MediaCodec.java:1951)
	at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:205)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:84)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:55)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:76)
	at com.genymobile.scrcpy.Server.main(Server.java:225)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
[server] ERROR: The hardware encoder is not able to encode at the given definition.
[server] ERROR: Try with a lower definition:
[server] ERROR:     scrcpy -m 1024
2020-10-16 22:19:25.441 scrcpy[71019:1899189] INFO: Renderer: metal
2020-10-16 22:19:25.447 scrcpy[71019:1899189] INFO: Initial texture: 1080x2312
2020-10-16 22:19:25.776 scrcpy[71019:1899189] WARN: Device disconnected

GeForce:~ alixa$ scrcpy
2020-10-16 22:20:31.069 scrcpy[71036:1899588] INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
/usr/local/Cellar/scrcpy/1.16/share/s...ed. 77.0 MB/s (33622 bytes in 0.000s)
[server] INFO: Device: HUAWEI MAR-LX3A (Android 10)
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffc0e
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:2023)
	at android.media.MediaCodec.configure(MediaCodec.java:1951)
	at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:205)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:84)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:55)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:76)
	at com.genymobile.scrcpy.Server.main(Server.java:225)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
[server] ERROR: The hardware encoder is not able to encode at the given definition.
[server] ERROR: Try with a lower definition:
[server] ERROR:     scrcpy -m 1024
2020-10-16 22:20:32.559 scrcpy[71036:1899588] INFO: Renderer: metal
2020-10-16 22:20:32.565 scrcpy[71036:1899588] INFO: Initial texture: 1080x2312
2020-10-16 22:20:32.894 scrcpy[71036:1899588] WARN: Device disconnected

GeForce:~ alixa$ scrcpy
2020-10-16 22:21:12.620 scrcpy[71057:1899965] INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
adb: error: failed to get feature set: no devices/emulators found
2020-10-16 22:21:12.627 scrcpy[71057:1899965] ERROR: "adb push" returned with value 1

GeForce:~ alixa$ scrcpy
2020-10-16 22:22:41.796 scrcpy[71091:1900883] INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
/usr/local/Cellar/scrcpy/1.16/share/s...ed. 72.4 MB/s (33622 bytes in 0.000s)
[server] INFO: Device: HUAWEI MAR-LX3A (Android 10)
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffc0e
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:2023)
	at android.media.MediaCodec.configure(MediaCodec.java:1951)
	at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:205)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:84)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:55)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:76)
	at com.genymobile.scrcpy.Server.main(Server.java:225)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
[server] ERROR: The hardware encoder is not able to encode at the given definition.
[server] ERROR: Try with a lower definition:
[server] ERROR:     scrcpy -m 1024
2020-10-16 22:22:43.269 scrcpy[71091:1900883] INFO: Renderer: metal
2020-10-16 22:22:43.280 scrcpy[71091:1900883] INFO: Initial texture: 1080x2312
2020-10-16 22:22:43.609 scrcpy[71091:1900883] WARN: Device disconnected

GeForce:~ alixa$ scrcpy
2020-10-16 22:23:55.055 scrcpy[71113:1901475] INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
/usr/local/Cellar/scrcpy/1.16/share/s...ed. 80.7 MB/s (33622 bytes in 0.000s)
[server] INFO: Device: HUAWEI MAR-LX3A (Android 10)
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffc0e
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:2023)
	at android.media.MediaCodec.configure(MediaCodec.java:1951)
	at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:205)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:84)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:55)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:76)
	at com.genymobile.scrcpy.Server.main(Server.java:225)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
[server] ERROR: The hardware encoder is not able to encode at the given definition.
[server] ERROR: Try with a lower definition:
[server] ERROR:     scrcpy -m 1024
2020-10-16 22:23:56.555 scrcpy[71113:1901475] INFO: Renderer: metal
2020-10-16 22:23:56.563 scrcpy[71113:1901475] INFO: Initial texture: 1080x2312
2020-10-16 22:23:56.893 scrcpy[71113:1901475] WARN: Device disconnected

GeForce:~ alixa$ scrcpy
2020-10-16 22:24:14.432 scrcpy[71133:1901822] INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
/usr/local/Cellar/scrcpy/1.16/share/s...ed. 73.5 MB/s (33622 bytes in 0.000s)
[server] INFO: Device: HUAWEI MAR-LX3A (Android 10)
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffc0e
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:2023)
	at android.media.MediaCodec.configure(MediaCodec.java:1951)
	at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:205)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:84)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:55)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:76)
	at com.genymobile.scrcpy.Server.main(Server.java:225)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
[server] ERROR: The hardware encoder is not able to encode at the given definition.
[server] ERROR: Try with a lower definition:
[server] ERROR:     scrcpy -m 1024
2020-10-16 22:24:15.929 scrcpy[71133:1901822] INFO: Renderer: metal
2020-10-16 22:24:15.937 scrcpy[71133:1901822] INFO: Initial texture: 1080x2312
2020-10-16 22:24:16.265 scrcpy[71133:1901822] WARN: Device disconnected

GeForce:~ alixa$ scrcpy
2020-10-16 22:24:23.573 scrcpy[71139:1901966] INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
/usr/local/Cellar/scrcpy/1.16/share/s...ed. 79.3 MB/s (33622 bytes in 0.000s)
[server] INFO: Device: HUAWEI MAR-LX3A (Android 10)
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffc0e
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:2023)
	at android.media.MediaCodec.configure(MediaCodec.java:1951)
	at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:205)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:84)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:55)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:76)
	at com.genymobile.scrcpy.Server.main(Server.java:225)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
[server] ERROR: The hardware encoder is not able to encode at the given definition.
[server] ERROR: Try with a lower definition:
[server] ERROR:     scrcpy -m 1024
2020-10-16 22:24:25.080 scrcpy[71139:1901966] INFO: Renderer: metal
2020-10-16 22:24:25.086 scrcpy[71139:1901966] INFO: Initial texture: 1080x2312
2020-10-16 22:24:25.418 scrcpy[71139:1901966] WARN: Device disconnected

GeForce:~ alixa$ scrcpy
2020-10-16 22:24:34.711 scrcpy[71152:1902207] INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
/usr/local/Cellar/scrcpy/1.16/share/s...ed. 77.2 MB/s (33622 bytes in 0.000s)
[server] INFO: Device: HUAWEI MAR-LX3A (Android 10)
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffc0e
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:2023)
	at android.media.MediaCodec.configure(MediaCodec.java:1951)
	at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:205)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:84)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:55)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:76)
	at com.genymobile.scrcpy.Server.main(Server.java:225)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
[server] ERROR: The hardware encoder is not able to encode at the given definition.
[server] ERROR: Try with a lower definition:
[server] ERROR:     scrcpy -m 1024
2020-10-16 22:24:36.168 scrcpy[71152:1902207] INFO: Renderer: metal
2020-10-16 22:24:36.175 scrcpy[71152:1902207] INFO: Initial texture: 1080x2312
2020-10-16 22:24:36.505 scrcpy[71152:1902207] WARN: Device disconnected

GeForce:~ alixa$ brew update
fatal: unable to access 'https://github.com/Homebrew/brew/': Failed to connect to github.com port 443: Operation timed out
Error: Fetching /usr/local/Homebrew failed!

GeForce:~ alixa$ brew update
Already up-to-date.

GeForce:~ alixa$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.profile

GeForce:~ alixa$ brew config
HOMEBREW_VERSION: 2.5.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: abf214c01ff1edb57acf7e23d5eb24a777335e11
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 735883ad612e402c3dfc995a3073e73cf1548c9a
Core tap last commit: in the future
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit ivybridge
Clang: 10.0 build 1000
Git: 2.17.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.13.6-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: N/A

GeForce:~ alixa$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.profile

GeForce:~ alixa$ scrcpy
2020-10-16 22:40:38.290 scrcpy[73371:1911966] INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
/usr/local/Cellar/scrcpy/1.16/share/scrcpy/scrcpy-serve...le pushed, 0 skipped. 76.3 MB/s (33622 bytes in 0.000s)
[server] INFO: Device: HUAWEI MAR-LX3A (Android 10)
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffc0e
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:2023)
	at android.media.MediaCodec.configure(MediaCodec.java:1951)
	at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:205)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:84)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:55)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:76)
	at com.genymobile.scrcpy.Server.main(Server.java:225)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
[server] ERROR: The hardware encoder is not able to encode at the given definition.
[server] ERROR: Try with a lower definition:
[server] ERROR:     scrcpy -m 1024
2020-10-16 22:40:39.833 scrcpy[73371:1911966] INFO: Renderer: metal
2020-10-16 22:40:39.839 scrcpy[73371:1911966] INFO: Initial texture: 1080x2312
2020-10-16 22:40:40.170 scrcpy[73371:1911966] WARN: Device disconnected

GeForce:~ alixa$ 
</pre>

**Comment by MikeMcQuaid** [comment]
Sorry, you'll need to figure this out yourself.

**Comment by ixlatall** [comment]
> Sorry, you'll need to figure this out yourself.

Wow, that's harsh.

**Comment by MikeMcQuaid** [comment]
There's no indication this is a bug in Homebrew and we have literally millions of users and tens of maintainers; we cannot help all people with all problems, sorry.
