### ISSUE TITLE
brew CI has general failures

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/brew#8979]
Reporting a bug in `brew` CI. Take pull request https://github.com/Homebrew/brew/pull/8977

Testing fails repeatedly on Linux, with:

```
Error: brew update didn't update master!
Start commit:        c4ae961efac4904aabdd7dc3cbe20dc4ed004869
Expected end commit: 7881a93c5b077ccf0a3b1d173fb899d5609ea5f5
Actual end commit:   8982dc3f7eeee13d189324f38b3b9d3e9124b38f
```

At least once, testing failed on macOS, due to timeout:

```
2020-10-23T15:56:04.5367910Z Failures:
2020-10-23T15:56:04.5368070Z 
2020-10-23T15:56:04.5368660Z   1) Cask::Cmd::Zap can zap and unlink multiple Casks at once
2020-10-23T15:56:04.5369860Z      Failure/Error: raise "Example exceeded maximum runtime of #{timeout} seconds."
2020-10-23T15:56:04.5370230Z 
2020-10-23T15:56:04.5370520Z      RuntimeError:
2020-10-23T15:56:04.5370930Z        Example exceeded maximum runtime of 120 seconds.
2020-10-23T15:56:04.5372420Z      # ./test/spec_helper.rb:200:in `rescue in block (2 levels) in <top (required)>'
2020-10-23T15:56:04.5373380Z      # ./test/spec_helper.rb:191:in `block (2 levels) in <top (required)>'
2020-10-23T15:56:04.5374370Z      # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:124:in `block in run'
2020-10-23T15:56:04.5375440Z      # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `loop'
2020-10-23T15:56:04.5376470Z      # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `run'
2020-10-23T15:56:04.5377670Z      # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
2020-10-23T15:56:04.5378800Z      # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:37:in `block (2 levels) in setup'
2020-10-23T15:56:04.5394020Z      # ./vendor/bundle/ruby/2.6.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block (2 levels) in <top (required)>'
2020-10-23T15:56:04.5395030Z      # ------------------
2020-10-23T15:56:04.5395650Z      # --- Caused by: ---
2020-10-23T15:56:04.5395960Z      # Timeout::Error:
2020-10-23T15:56:04.5396270Z      #   execution expired
2020-10-23T15:56:04.5396990Z      #   ./system_command.rb:157:in `select'
```

**Comment by jonchang** [comment]
The brew PR probably needs to be rebased. This was one of the issues I had earlier.

**Comment by fxcoudert** [comment]
I'm not sure I understand why. It applies cleanly, there is no conflict. There's actually been only one commit to master since then.

**Comment by jonchang** [comment]
Yeah, there's something wrong with the test too. But rebasing should work around it.

**Comment by fxcoudert** [comment]
I've opened another PR with another commit, we'll see how it goes: https://github.com/Homebrew/brew/pull/8980

**Comment by fxcoudert** [comment]
The other PR failed 😢

**Comment by MikeMcQuaid** [comment]
> Error: brew update didn't update master!

https://github.com/Homebrew/brew/pull/8990 doesn't fix this but should provide a lot more debugging output that will make it easier for me to fix this when it crops up again.



> 2020-10-23T15:56:04.5370930Z        Example exceeded maximum runtime of 120 seconds.

https://github.com/Homebrew/brew/pull/9004 should fix this by allowing these tests to be retried when they timeout.

**Comment by fxcoudert** [comment]
> Error: brew update didn't update master!

Reopening this issue: we are seeing the same CI failure in https://github.com/Homebrew/brew/pull/9018

**Comment by MikeMcQuaid** [comment]
Opened https://github.com/Homebrew/brew/pull/9028 to add more debugging output and, hopefully, fix this. From the last debugging output addition I can guess that the reason this is happening is if there's a merge to `master` during the CI run of another PR. This will hopefully work around that (and provide more information if it starts failing again).
