### ISSUE TITLE
Error when upgrading dependency of upgradable formula

### ISSUE THREAD

**Issue by muneebmahmed** [Homebrew/brew#8997]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Upgrade a formula (ffmpeg) and its dependent (cmus) by calling `brew upgrade` only on the dependency (`brew upgrade ffmpeg`)

## What happened (include command output)

After installing `ffmpeg`'s dependencies and upgrading the dependent `cmus`, I got the error message
```
Removing: /usr/local/Cellar/cmus/2.8.0_1... (36 files, 613.5KB)
==> Checking for dependents of upgraded formulae...
Error: No such file or directory - /usr/local/Cellar/cmus/2.8.0_1
```
I was also able to reproduce a similar error message on another computer with `cocoapods` and its dependency `ruby` after running `brew upgrade ruby`

<details>
  <summary>Command output</summary>
  <pre>

$ brew upgrade ffmpeg
==> Upgrading 1 outdated package:
ffmpeg 4.3.1_1 -> 4.3.1_2
==> Upgrading ffmpeg 4.3.1_1 -> 4.3.1_2
==> Downloading https://homebrew.bintray.com/bottles/python%403.9-3.9.0.mojave.bottle.1.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/49d663baef12229a4b236cd6d7827e671142709cb3b58f0bf7ef7756d4774a3a?response-content-disposition=attachment%3Bfilename%3D%22python%403.9-3.9.0.mojave.bottle.1.tar.gz%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0
######################################################################## 100.0%
==> Downloading https://homebrew.bintray.com/bottles/glib-2.66.2_1.mojave.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/0715e8debe9a6a1e1f8223759a29c300eccb151c2fd5e4c376f8f71636501e0d?response-content-disposition=attachment%3Bfilename%3D%22glib-2.66.2_1.mojave.bottle.tar.gz%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8
######################################################################## 100.0%
==> Downloading https://homebrew.bintray.com/bottles/gobject-introspection-1.66.1_1.mojave.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/1d42d9c900dab307aefddffe723140ec2dfa25201426b4426c76cca28a4c46fa?response-content-disposition=attachment%3Bfilename%3D%22gobject-introspection-1.66.1_1.mojave.bottle.tar.gz%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdX
######################################################################## 100.0%
==> Downloading https://homebrew.bintray.com/bottles/x264-r3018.mojave.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/fee48981609b1f3d59cbd018150d97fa009288a48995c2c6d02cadefea57c072?response-content-disposition=attachment%3Bfilename%3D%22x264-r3018.mojave.bottle.tar.gz%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZD
######################################################################## 100.0%
==> Downloading https://homebrew.bintray.com/bottles/ffmpeg-4.3.1_2.mojave.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/68f51c0b4fe35370039b0a7126f9d5be63e87074906458a49c002ecee3c0a5e4?response-content-disposition=attachment%3Bfilename%3D%22ffmpeg-4.3.1_2.mojave.bottle.tar.gz%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi
######################################################################## 100.0%
==> Installing dependencies for ffmpeg: python@3.9, glib, gobject-introspection and x264
==> Installing ffmpeg dependency: python@3.9
==> Pouring python@3.9-3.9.0.mojave.bottle.1.tar.gz
==> /usr/local/Cellar/python@3.9/3.9.0/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts=/usr/local/Cellar/python@3.9/3.9.0/bin --install-lib=/usr/local/lib/python3.9/site-packages --single-version-externally-managed --record=installed.txt
==> /usr/local/Cellar/python@3.9/3.9.0/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts=/usr/local/Cellar/python@3.9/3.9.0/bin --install-lib=/usr/local/lib/python3.9/site-packages --single-version-externally-managed --record=installed.txt
==> /usr/local/Cellar/python@3.9/3.9.0/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts=/usr/local/Cellar/python@3.9/3.9.0/bin --install-lib=/usr/local/lib/python3.9/site-packages --single-version-externally-managed --record=installed.txt
==> Caveats
Python has been installed as
  /usr/local/bin/python3

Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
`python3`, `python3-config`, `pip3` etc., respectively, have been installed into
  /usr/local/opt/python@3.9/libexec/bin

You can install Python packages with
  pip3 install <package>
They will install into the site-package directory
  /usr/local/lib/python3.9/site-packages

See: https://docs.brew.sh/Homebrew-and-Python

python@3.9 is keg-only, which means it was not symlinked into /usr/local,
because this is an alternate version of another formula.

If you need to have python@3.9 first in your PATH run:
  echo 'export PATH="/usr/local/opt/python@3.9/bin:$PATH"' >> ~/.zshrc

For compilers to find python@3.9 you may need to set:
  export LDFLAGS="-L/usr/local/opt/python@3.9/lib"

For pkg-config to find python@3.9 you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/python@3.9/lib/pkgconfig"

==> Summary
🍺  /usr/local/Cellar/python@3.9/3.9.0: 4,459 files, 69.8MB
==> Installing ffmpeg dependency: glib
==> Pouring glib-2.66.2_1.mojave.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/glib/2.66.2_1: 436 files, 15MB
==> Installing ffmpeg dependency: gobject-introspection
==> Pouring gobject-introspection-1.66.1_1.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/gobject-introspection/1.66.1_1: 191 files, 12.5MB
==> Installing ffmpeg dependency: x264
==> Pouring x264-r3018.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/x264/r3018: 11 files, 5.7MB
==> Installing ffmpeg
==> Pouring ffmpeg-4.3.1_2.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/ffmpeg/4.3.1_2: 273 files, 53.8MB
Removing: /usr/local/Cellar/ffmpeg/4.3.1_1... (273 files, 53.8MB)
==> Upgrading 1 dependent:
cmus 2.8.0_1 -> 2.8.0_2
==> Upgrading cmus 2.8.0_1 -> 2.8.0_2
==> Downloading https://homebrew.bintray.com/bottles/cmus-2.8.0_2.mojave.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/4c5095917ced94e028bf33b8330f46dd692ab62fbd0304d14f1d9664b8045b3d?response-content-disposition=attachment%3Bfilename%3D%22cmus-2.8.0_2.mojave.bottle.tar.gz%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8v
######################################################################## 100.0%
==> Pouring cmus-2.8.0_2.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/cmus/2.8.0_2: 39 files, 657.5KB
Removing: /usr/local/Cellar/cmus/2.8.0_1... (36 files, 613.5KB)
==> Checking for dependents of upgraded formulae...
Error: No such file or directory - /usr/local/Cellar/cmus/2.8.0_1
  </pre>
</details>

## What you expected to happen

`brew upgrade ffmpeg` should have returned with a zero return code

## Step-by-step reproduction instructions (by running `brew` commands)

* Have one formula and one of its dependencies able to be upgraded
* Run `brew upgrade` on the dependency but not the dependent

## Output of `brew config` and `brew doctor` commands

<pre>

$ brew config
HOMEBREW_VERSION: 2.5.7-2-gc8fcd05
ORIGIN: https://github.com/Homebrew/brew
HEAD: c8fcd050c7b85e2b48f7b1b2c5465980b8705679
Last commit: 12 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8a34acb309ba9d62b2d0377fe76c1a5731ddacc7
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_AUTO_UPDATE: set
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 11.0 build 1100
Git: 2.21.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 15.0.1
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 11.3.1

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  guile@2

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc
</pre>

-----
My guess is that when dependents are upgraded, the list of installed formulae does not refresh before checking for broken dependents, causing file paths to be searched that no longer exist. Could this issue be solved by regenerating the list of formulae before this line?
https://github.com/Homebrew/brew/blob/c8fcd050c7b85e2b48f7b1b2c5465980b8705679/Library/Homebrew/upgrade.rb#L190

**Comment by muneebmahmed** [comment]
I created a [PR](https://github.com/Homebrew/brew/pull/8998) that might fix this, but haven't done any testing on it beyond calling `brew upgrade x264` once to verify there were no errors when upgrading ffmeg.

**Comment by muneebmahmed** [comment]
Hi @MikeMcQuaid, can you reopen this? It turns out my PR was not enough to fix the issue.

I noticed `cmus` was updated again today, and I ran a `brew reinstall ffmpeg --debug` to test if the issue was still present. Here's the relevant output:
```
🍺  /usr/local/Cellar/cmus/2.8.0_3: 36 files, 613.8KB
Removing: /usr/local/Cellar/cmus/2.8.0_2... (39 files, 657.5KB)
==> Checking for dependents of upgraded formulae...
Error: No such file or directory - /usr/local/Cellar/cmus/2.8.0_2
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/find.rb:43:in `block in find'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/find.rb:43:in `collect!'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/find.rb:43:in `find'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/pathname.rb:565:in `find'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/forwardable.rb:230:in `find'
/usr/local/Homebrew/Library/Homebrew/linkage_checker.rb:146:in `check_dylibs'
/usr/local/Homebrew/Library/Homebrew/linkage_checker.rb:34:in `initialize'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:132:in `new'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:132:in `block (2 levels) in check_broken_dependents'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:128:in `select'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:128:in `block in check_broken_dependents'
/usr/local/Homebrew/Library/Homebrew/cache_store.rb:26:in `use'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:125:in `check_broken_dependents'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:194:in `check_installed_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:103:in `reinstall'
/usr/local/Homebrew/Library/Homebrew/brew.rb:120:in `<main>'
```
I do have the whole log output but it's 1000+ lines and I didn't think the rest was relevant to this.

Also, here are some better steps to reproduce the issue:
1. Choose an installed formula that has a dependency (e.g `cmus` and `ffmpeg`), and uninstall the formula: `brew uninstall cmus`
2. Check out a commit in homebrew core before the formula was last updated: 
```
cd $(brew --repository homebrew/core) && git checkout 235846b3ec2
``` 
3. Install the old version of the formula: `brew install cmus`
4. Check out the latest homebrew core and reinstall the dependency:
```
git checkout master && brew reinstall ffmpeg --debug
```
