### ISSUE TITLE
Error: undefined method `desc' for Formulary::Formulae::Mysql56:Class

### ISSUE THREAD

**Issue by jinnguyen** [Homebrew/brew#913]
```
/usr/local/Library/Taps/homebrew/homebrew-versions/mysql56.rb:2:in `<class:Mysql56>'
/usr/local/Library/Taps/homebrew/homebrew-versions/mysql56.rb:1:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:92:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:92:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:71:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:200:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:41:in `install'
/usr/local/Library/brew.rb:140:in `<main>'
```

**Comment by DomT4** [comment]
Suspect your Homebrew is out-of-date. Try:
```bash
cd "$(brew --repo)" && git fetch && git reset --hard origin/master
```

**Comment by DomT4** [comment]
If that doesn't work, please let us know. Thanks!
