### ISSUE TITLE
Error when running subliminal

### ISSUE THREAD

**Issue by nmk** [Homebrew/brew#920]
Using the default installed Python on 10.11.6.

```
~ $ subliminal
Traceback (most recent call last):
  File "/usr/local/bin/subliminal", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/Cellar/subliminal/2.0.5/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 17, in <module>
    from __future__ import absolute_import
ImportError: No module named __future__
~ $ python
Python 2.7.10 (default, Oct 23 2015, 19:19:21)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from __future__ import absolute_import
>>> ^D
~ $
```
`brew doctor` does not report any problems.

**Comment by tdsmith** [comment]
That's bizarre! It works for me. What happens if you run `/usr/local/Cellar/subliminal/2.0.5/libexec/bin/python -c "from __future__ import absolute_import"`?

**Comment by nmk** [comment]
After installing the brew supplied python, the issue was resolved. Even after I uninstalled the brew supplied python, the issue does not appear any more.
