### ISSUE TITLE
NoSDKError encountered when calling sdk_path

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/brew#9324]
When trying to `brew install -svd python@3.9` on ARM Big Sur, I currently get:

```
OS::Mac::BaseSDKLocator::NoSDKError: OS::Mac::BaseSDKLocator::NoSDKError
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 3
/opt/homebrew/Library/Homebrew/debrew.rb:18:in `raise'
/opt/homebrew/Library/Homebrew/os/mac/sdk.rb:29:in `sdk_for'
/opt/homebrew/Library/Homebrew/os/mac/sdk.rb:48:in `sdk_if_applicable'
/opt/homebrew/Library/Homebrew/os/mac.rb:120:in `sdk'
/opt/homebrew/Library/Homebrew/os/mac.rb:132:in `sdk_path'
/opt/homebrew/Library/Homebrew/os/mac.rb:147:in `sdk_path_if_needed'
/opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/python@3.9.rb:103:in `install'
/opt/homebrew/Library/Homebrew/debrew.rb:30:in `block in install'
/opt/homebrew/Library/Homebrew/debrew.rb:104:in `debrew'
/opt/homebrew/Library/Homebrew/debrew.rb:30:in `install'
/opt/homebrew/Library/Homebrew/build.rb:172:in `block (2 levels) in install'
/opt/homebrew/Library/Homebrew/formula.rb:1214:in `block in brew'
/opt/homebrew/Library/Homebrew/formula.rb:2230:in `block (2 levels) in stage'
/opt/homebrew/Library/Homebrew/utils.rb:500:in `with_env'
/opt/homebrew/Library/Homebrew/formula.rb:2229:in `block in stage'
/opt/homebrew/Library/Homebrew/resource.rb:119:in `block in unpack'
/opt/homebrew/Library/Homebrew/mktemp.rb:63:in `block in run'
/opt/homebrew/Library/Homebrew/mktemp.rb:63:in `chdir'
/opt/homebrew/Library/Homebrew/mktemp.rb:63:in `run'
/opt/homebrew/Library/Homebrew/resource.rb:207:in `mktemp'
/opt/homebrew/Library/Homebrew/resource.rb:114:in `unpack'
/opt/homebrew/Library/Homebrew/resource.rb:89:in `stage'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `stage'
/opt/homebrew/Library/Homebrew/formula.rb:2209:in `stage'
/opt/homebrew/Library/Homebrew/formula.rb:1207:in `brew'
/opt/homebrew/Library/Homebrew/build.rb:140:in `block in install'
/opt/homebrew/Library/Homebrew/utils.rb:500:in `with_env'
/opt/homebrew/Library/Homebrew/build.rb:135:in `install'
/opt/homebrew/Library/Homebrew/build.rb:224:in `<main>'
```

The config is as follows:

```
% brew config
HOMEBREW_VERSION: 2.5.12-263-gd7f03bc
ORIGIN: https://github.com/Homebrew/brew
HEAD: d7f03bc2dd61e3495f0b48b6c8371f567c215304
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/armbottles/homebrew-core
Core tap HEAD: 28b452251d444ed7ccf3d7b7c94cb86c8ba2d6c9
Core tap last commit: 9 days ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_REPOSITORY: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_vortex_tempest
Clang: 12.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 15
macOS: 11.1-arm64
CLT: 12.3.0.0.1.1605054730
Xcode: 12.3 => /Applications/Xcode-beta.app/Contents/Developer
Rosetta 2: false
```

I'm wondering if this could be fallout from https://github.com/Homebrew/brew/pull/9267

**Comment by fxcoudert** [comment]
What is weird is that this is working if called from `brew irb`:

```
irb(main):001:0> MacOS.sdk_path_if_needed
=> #<Pathname:/Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk>
```

Are there differences in environment between those two use cases?

**Comment by fxcoudert** [comment]
The content of `sdk_paths` is:

```
sdk_paths = {#<OS::Mac::Version:0x00000001399e9e38 @version="11.1", @detected_from_url=false, @comparison_cache={#<OS::Mac::Version:0x000000014a1daf38 @version="11", @detected_from_url=false, @comparison_cache={"12"=>-1, "10.14"=>1, nil=>1, "10.12"=>1, "10.11"=>1}, @tokens=[#<Version::NumericToken 11>]>=>1}, @tokens=[#<Version::NumericToken 11>, #<Version::NumericToken 1>]>=>"/Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk", #<OS::Mac::Version:0x00000001399e9d70 @version="10.15", @detected_from_url=false, @comparison_cache={#<OS::Mac::Version:0x00000001399e9e38 @version="11.1", @detected_from_url=false, @comparison_cache={#<OS::Mac::Version:0x000000014a1daf38 @version="11", @detected_from_url=false, @comparison_cache={"12"=>-1, "10.14"=>1, nil=>1, "10.12"=>1, "10.11"=>1}, @tokens=[#<Version::NumericToken 11>]>=>1}, @tokens=[#<Version::NumericToken 11>, #<Version::NumericToken 1>]>=>-1}, @tokens=[#<Version::NumericToken 10>, #<Version::NumericToken 15>]>=>"/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk"}
```

so when `sdk_for(11)` gets called, it raises an error.

**Comment by fxcoudert** [comment]
Others confirm having the same problem, with SDK variables not being correctly populated in formulas: https://github.com/Homebrew/brew/issues/7857#issuecomment-734951036

**Comment by fxcoudert** [comment]
I confirm that this was introduced by https://github.com/Homebrew/brew/pull/9267
Prior to that, `MacOS.version = 11.1` (incorrect) and `MacOS.sdk_path = /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk` (correct)
