### ISSUE TITLE
Error: No such file or directory for every command

### ISSUE THREAD

**Issue by Mishail** [Homebrew/brew#996]
- [x] Ran `brew update` and retried your prior step?
- [x]  Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

I'm using eb23a39
```
mstepura:local mikhail$ cd "$(brew --repo)" && git fetch && git reset --hard origin/master
HEAD is now at eb23a39 utils: remove bad symlink if it already exists.
```

And every `brew` command fails with `No such file or directory`:
```
mstepura:local mikhail$ brew doctor
Error: No such file or directory - (../../../Cellar/ant/1.9.7, /usr/local/var/homebrew/linked/ant)
```

```
mstepura:local mikhail$ brew doctor -d
Error: No such file or directory - (../../../Cellar/ant/1.9.7, /usr/local/var/homebrew/linked/ant)
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:349:in `symlink'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:349:in `block in ln_s'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1574:in `fu_each_src_dest0'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:347:in `ln_s'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:370:in `ln_sf'
/usr/local/Library/Homebrew/utils.rb:641:in `block in migrate_legacy_keg_symlinks_if_necessary'
/usr/local/Library/Homebrew/utils.rb:628:in `each'
/usr/local/Library/Homebrew/utils.rb:628:in `migrate_legacy_keg_symlinks_if_necessary'
/usr/local/Library/Homebrew/brew.rb:91:in `<main>'
```

**Comment by zmwangx** [comment]
Please try to run `brew update --debug` twice and report your findings.

**Comment by Mishail** [comment]
here is output for `brew update --debug`: http://pastebin.com/H5LQwhhF

**Comment by zmwangx** [comment]
What if you run it **twice**, i.e., can you run it a second time?

**Comment by Mishail** [comment]
@zmwangx trust me, I've executed those multiple times. Anyway 295e937 has fixed the problem

**Comment by Mishail** [comment]
#991
